export const gorouVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "General Gorou of the Watatsumi Island resistance, ready and waiting! I've long heard of your sterling reputation and I look forward to fighting our way to victory side-by-side! ...Heh, so what do you think? Did that sound inspiring?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Tactics',
      audio: '1101',
      text: "Keep your weapon at the ready. You never know what's around the corner...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Training',
      audio: '1102',
      text: 'The fighting has ceased for now... Commence physical training!',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Physique',
      audio: '1103',
      text: 'A strong body shows strength and instills confidence in others around you. I must always stay at the top of my game!',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Ugh, my tail's getting wet... Let's find a fire and dry off.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Stay alert!',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Whew *shivering*... it's cold. These conditions are unsuitable for outdoor maneuvers.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "It'd be nice to just lie in the sun... Ahem, but I must set an example for the others.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'We can attack downwind and press the advantage. Or, bolster our courage and fight upwind!',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: 'The sun is up and it is time to train. Shall we go climb a mountain?',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Let's have Radish and Fish Stew with plain rice for lunch today. It's been a favorite among the troops lately, so I suggest you try it, too.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Though the sun is setting, our guard must remain high. We should let our eyes adapt to the dark... Even in the darkness of night, a battle may be looming.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "If you're feeling fatigued, then best turn in for the night. I'll take watch! Don't worry, you have my word that everything will still be in good order on your return.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Gorou: Top Dog',
      audio: '2001',
      text: 'Huh? "Top Dog Gorou"? Where did you hear that? *sigh* To be honest, I\'ve grown quite close with my fellow officers, and always share any good news I might have with them. In private, they\'ve all started calling me Top Dog out of respect... But in terms of age, they are all my seniors.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Gorou: Advice',
      audio: '2005',
      text: "The troops seem to picture me as someone of extraordinary abilities — I think it might be because of our streak of victories lately. Now they always come to me for advice on even the most trivial matters. When I see the expectant look in their eyes, it's impossible for me to turn them away, but at the same time, my strategic ability is limited... All I can do is give some general pointers, or failing that, respond based on my gut feeling alone. *sigh* I just hope I'm not letting them down.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Speaking Your Mind',
      audio: '2003',
      text: "If there's anything ever troubling you, don't keep it all muzzled up inside. You can always speak your mind with me! Although I can't guarantee that I'll always have an answer, I'll certainly offer you my best advice! Even when I can't muster much of a response, you can always count on me to be a good listener. Whatever it is, I'm all ears.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Camaraderie',
      audio: '2002',
      text: "We train together, eat together, and relax together. There's no better way to strengthen communication and build tacit understanding between everyone on the team. In the heat of battle, just a simple glance can transmit crucial information. Hmm? You don't think it's very appropriate? Huh... Well, I mean, that's how the troops and I have been bonding as a team.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "My Vision amplifies my abilities in battle. It allows me to take greater responsibility on the battlefield and forge a way forward for the troops. But I also understand that one person alone, no matter how strong, is never enough to turn the tide of a battle. The key to victory is everyone's united effort, fighting for a common cause.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Dressed for Battle',
      audio: '3002',
      text: "I don't like to enter battle wearing lots of heavy equipment. I travel light, that's my style. My strength is in moving quickly around the battlefield, seeking out opportunities to take control of the fight. I always target the strongest warriors first to weaken the enemy's morale.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Ever-Victorious General',
      audio: '3004',
      text: 'The troops have come up with a nickname for me, the "ever-victorious pointy-eared general." Now there\'s even a rumor going around saying that "if you want Top Dog Gorou\'s victorious luck, give his pointy ears a rub." Grrr, there will be no rubbing of my ears, and that\'s final. If they think they can smile their way into persuading me otherwise, well, they\'ve got another thing... Hmm? Hey, wh—what are you doing? Not you too...? Come on now, I... I thought I... Mm... Mm...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "I've heard that there's a mountain range in Liyue that reaches all the way up into the clouds. Ah, I'd relish a chance to go climbing there!",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Beidou',
      audio: '4001',
      text: "Captain Beidou values camaraderie, and her exceptional abilities command respect. She once said that she prefers to avoid involving her companions in disputes that don't concern them, which I can completely understand. That's why I only request her help when we have no one else to turn to.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Kaedehara Kazuha',
      audio: '4002',
      text: "I've seen all kinds of wandering samurai before, and Kazuha is categorically a different breed from the others. He's like a gust of wind that sweeps through the land. Though he never stays for long, he is always able to contribute something to those who are around him. When I fought alongside him, I learned more about what it means to be truly carefree and without constraints. In any case, I think that Kazuha and I make a great team together!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Sangonomiya Kokomi: Duties',
      audio: '4003',
      text: 'As the leader of Watatsumi Island, Her Excellency is responsible for assessing the scenario and formulating a plan. It is then my duty to put every detail of the plan into action and to keep the situation under control on the front line. We are united with the whole resistance in achieving a single purpose: victory.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Sangonomiya Kokomi: Attitude',
      audio: '4004',
      text: "I have only the utmost respect for Her Excellency. Without her ingenious and insightful strategies, the resistance could never have come as far as it has today. But if you ask me, it seems that deep down she prefers a much quieter existence. So when there's no pressing military matters, I try not to disturb her too much.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About the Raiden Shogun',
      audio: '4005',
      text: 'Grr, the Raiden Shogun... I could never bring myself to accept her past actions, no matter what her reasoning may have been. Though a peace treaty has been signed between Watatsumi Island and the Shogunate, I refuse to let my guard down. If conflict ever breaks out again, I will resume my place back on the front line.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Kujou Sara',
      audio: '4006',
      text: "I have nothing good to say about the Shogun's Army, but Kujou Sara is perhaps the most honorable officer among their ranks. We've met each other countless times in battle, emerging both victorious and defeated at different times. *sigh* I know now that it's not realistic to think this way, but I did use to wonder what things would be like if those like her could value the wishes of the people and be free from the grip of the Shogunate.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '27': {
      title: 'About Yae Miko',
      audio: '4007',
      text: "Oh, her... I'd prefer not to talk about her. Can we change the topic? Or, if there are any tasks I can take off your hand, I'll gladly oblige! Anything at all? ...Ahem, let's just say it'd be best for my general well-being if we can we avoid talking about her...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Kamisato Ayaka',
      audio: '4008',
      text: "The Yashiro Commission operates as part of the Shogunate, but on many issues they tend to side with the people of Inazuma. In fact, the Shirasagi Himegimi has managed to establish an excellent reputation for herself, despite facing pressure from both sides. I suppose she must know how to keep her composure at all times and navigate sensitive situations tactfully... There's much I could learn from her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'About Sayu',
      audio: '4009',
      text: "Hmm, according to our intel, she is a ninja proficient in the art of infiltration — a skill set which could prove very useful in some of Her Excellency's special operations... However, our intel also indicates that she could be difficult to recruit as she is rather unruly, and often disappears without a trace. Hmm? She's with the Yashiro Commission? Oh, well forget it then.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Shikanoin Heizou',
      audio: '4010',
      text: "You mean that sneaky detective that never seems to actually be working on a case? Well, no one from the Shogunate can be fully trusted, so I'll be keeping my eyes and ears on him! On a separate note, he does have some talent for investigation. But how can we know that this isn't all part of some nefarious scheme? Hmm. Only time will tell, I suppose.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Gorou: I',
      audio: '5001',
      text: "Hmm, I'm afraid that most of my days have been spent on the battlefield, so there's not much to tell about me. But if you'd really like to hear my stories, I'm happy to sit down and tell you everything!",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Gorou: II',
      audio: '5002',
      text: "I may not have superior cunning or intelligence, but what I do have is my own two hands and my life to lay on the line. Countless battles in, I'm still here, so I guess these hands and my will to survive were both strong enough to see me through. Some even say that no matter how dire the battle may be, everyone will emerge unscathed as long as they follow me. And with that, I've somehow gained enough reputation among our forces to become the leader that I am now.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Gorou: III',
      audio: '5003',
      text: "At first, our only enemies were roaming bandits, pirates, and monsters. But then, everything changed when the Raiden Shogun enacted the Vision Hunt Decree. The Shogun's Army marched up expecting to put us in our place, but we were ready for them, and we hit them hard. Hehe, I bet they never expected to meet such fierce resistance.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '34': {
      title: 'More About Gorou: IV',
      audio: '5004',
      text: "Her Excellency once warned me of my fatal flaw... I tend to get too engrossed in battle, fighting deep into enemy lines and forgetting about everything else. She told me that my bravery is commendable, but as a ranking officer, it's not my place to do this. I'm doing my best to improve, but... Would you also be able to keep an eye on me?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Gorou: V',
      audio: '5005',
      text: 'We are not fighting against any particular group or faction. No, we fight against a destructive malice — a malice that has trampled the aspirations of the people and destroyed the peaceful lives they once knew. After I rid the land of such evil I will be able to peacefully lay down my weapon. Only then will I trade my uniform for civilian attire... and finally stroll the beautiful landscape of Watatsumi Island together with you.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "Gorou's Hobbies",
      audio: '6001',
      text: "I love mountain climbing! The steeper, the better. Climbing trains my body and mind, making me stronger with every grip and every foothold. Better yet is climbing mountains with fellow companions. After hours of dirt and sweat scaling the summit, we can sit down and enjoy the view together. It's one of life's greatest joys! Ahem, however, I have absolutely no desire to scale the tallest peak in Inazuma...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Gorou's Troubles",
      audio: '6002',
      text: 'There are times when being lightly armored has its shortcomings... For example, I have to be particularly careful of my tail when the enemy attacks with fire.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6003',
      text: "My favorites are cake and Tricolor Dango, probably because I seldom get the chance to enjoy the luxury of sweets. The rations we have in the field are intended to be simple, effective, and quick, and are seldom served with any seasonings at all, let alone sugar... It's probably the most precious commodity of all. Ah, what can I say — I guess I just have a sweet tooth!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I'll pretty much eat anything, but onions are an exception. One time, the logistics division added ground onion to my food and I bawled in front of everyone, right there at the mess table... *sigh* Talk about embarrassing. The soldiers from logistics felt terrible about it, too.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Mm! I become powerless in the face of sweets!',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Oh, I feel invigorated! Is there anything I can help you with?',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "It's a little spicier than I expected... *sniff* I—I don't think I can keep going.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "Today's a momentous occasion, your birthday! Allow me to arrange all the celebrations for you! We can make a bonfire on the beach and catch some fresh fish and crabs. I'll personally prepare a morale-boosting meal that would make even the highest-ranking generals jealous.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'With this newfound strength, I will defend those who fight alongside me.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Protecting my soldiers doesn't just mean having a robust defense in place. Sometimes, it means going on the attack!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'The key to seizing victory in battle lies in remembering the meaning of battle and employing the right tactics to generate momentum, making your forces unstoppable.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'With momentum on our side and close camaraderie, we are unstoppable. Thank you for your guidance. This is a victory that belongs to the both of us.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Advance!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Charge!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Fall in!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Everyone on me!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Press the advantage!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Rally!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'The tide of battle is in our favor!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Let's distribute these among our forces.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Careful, it could be a trap... Oh? Never mind.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Follow my lead!',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'I can still fight!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I got careless!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Surrender is not an option!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Fall back!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Stay in formation!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: "We're... defeated...",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'For... Watatsumi Island...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'All forces... retreat...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Shake it off!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: "C'mon!",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Ready and waiting!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Prepare to move out!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Company, fall in!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Gorou is the great general of Watatsumi Island\'s military, and he is deeply loved by his subordinates.\\nDuring the period of the Vision Hunt Decree, Gorou led the forces of Watatsumi against the Shogun\'s Army, and successfully held the line against them.\\nThe troops call him the "ever-victorious pointy-eared general," a nickname that has also seen broad use among Shogunate warriors.\\nIn private, however, Gorou puts on no airs and is a straightforward person, which has led him to be regarded by all as the man with the plan.\\nBut even such an exemplary general must have his fair share of troubles...',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Gorou was once an ordinary Watatsumi soldier.\\nDuring a certain special operation, Gorou\'s unit, Gorgasia II, faced an unprecedented crisis.\\nTheir captain had been felled by a stray arrow, and the survivors were surrounded deep in the mountains.\\nTo continue their mission, to ask for reinforcements, to open negotiations with the enemy... Countless choices lay before them, but the mountain was silent.\\nLeaderless and without any supplies, the unit was on its last legs. With their morale flagging, thoughts of surrender shrouded many minds.\\nAt this critical moment, Gorou stood up. He rejected negotiation and surrender, and instead proposed a bold plan.\\nThey would not hide any longer. Instead, he would lead the larger part of the platoon in a feigned attack to buy the others a chance to call for reinforcements. Once those reinforcements arrived, they could perform a pincer attack together.\\nWhen asked what they should do if they failed, Gorou replied:\\n"If the enemy surrounds us any further, our options will be even more limited. The way I see it, we still have a chance, so we\'ve got to give it all we\'ve got."\\n"I\'ll take responsibility if the plan fails."\\nAfter holding the line for several days without rest, the exhausted Gorou and his companions were finally relieved by a force led by Sangonomiya Kokomi herself.\\nAfter that, he was promoted to serve as the captain of Gorgasia II, and from there he would work his way up to the rank of General.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'In the eyes of the men, Gorou is a strict but humble general.\\nHe is straightforward and easy-going, and he treats his subordinates like his own family, sharing weal and woe with them.\\nSangonomiya Kokomi once told Gorou that material, supplies, and salaries were the three most important things to an army.\\nFrom that day on, he would personally explain weapon maintenance to his subordinates. Every time the granaries were opened, he would supervise the process strictly to prevent any unlawful deductions.\\nAnd as General Gorou, he will always lead from the front.\\nThe sight of him charging at the tip of the spear is like a rallying banner, encouraging the troops behind him to continue advancing.\\nThese are all reasons why the troops greatly respect him. As with Kokomi, Gorou greatly treasures the lives of his troops, but by contrast, values his own quite little.\\nSome who understand little of the thought process behind this occasionally joke that Gorou is a "kid" who doesn\'t seem like a general at all.\\nBut to the soldiers of Watatsumi Island, this kid is the best general they could ask for.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Gorou is valiant and decisive, often leading inferior forces to victory over superior opposition.\\nHowever, he does have a shortcoming of his own — a sometimes unstable temper.\\nThat is to say that the blood sometimes rushes to his head at the height of a battle.\\nWar is cruel, and Gorou does indeed lack experience compared to veterans who have been scrapping it out on battlefields for decades.\\nFortunately, he learns fast and is currently trying to make up for his various small failings.\\nSangonomiya Kokomi often provides her various commanders with directives, but how they are used is up to the skill of the commander in question.\\nFor his part, Gorou is always able to execute the courses of action that best suit the present situation from the directives he has been given.\\nGorou believes that over time, he will come to internalize the concepts behind them. Perhaps then, he can take the field with even more confidence than before.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'At Yae Miko\'s request, Gorou has taken up a certain extra "job" at Yae Publishing House.\\nWith the end of the Vision Hunt Decree, and the successful negotiations between Watatsumi Island and the Shogunate, relations between the two sides are beginning to warm.\\nGorou has also visited Narukami Island quite a few times to check out the changes, buy a few popular books, and go to Yae Publishing House to complete the task he agreed to help with.\\nYae Miko set up an anonymous column for Gorou in the "That\'s Life" magazine. Here, readers will write about the things that trouble them and send them to Yae Publishing House, upon which Gorou will give them some suggestions.\\nYae Publishing House will take special care to redact any personal information revealed on the part of the write-ins or Gorou\'s replies, and will replace real names with pseudonyms.\\nAccording to Yae Miko, she chose him because she\'d heard that he often listened to his subordinates when they chatted about personal matters.\\nThe column proved to be very popular indeed, but for whatever reason, every time an editor delivers the royalties to Gorou, they might sheepishly ask:\\n"Ah, speaking of which, Gorou, have you heard of Ms. Hina?"\\n"I\'ve heard that she\'s a rather popular columnist, and a recent one, too. Is something the matter?"\\n"Oh, no, no... It\'s nothing..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Just as the troops don't exactly tell Gorou everything happening in their lives, Gorou, too, has some troubles that are difficult to share.\\nFor example, how his tail fur starts to get dull and look haggard after being exposed to the elements for too long, and how he'd love to tend to it — if he could only spare the time out in the field.\\nOr how he sometimes feels a bit inferior about his slight physique when bathing together with his subordinates.\\nOr about how encountering inscrutable women like Yae Miko sends him into defense mode instantly, rendering him unable to properly interact with them...\\nIn trying to maintain a respectable image, Gorou refrains from telling his soldiers about such troubles.\\nAnd while they have been able to guess at his troubles to some extent, the Watatsumi soldiers often just play along and pretend that they don't notice.\\nAs such, his worries just kept piling up, until the Traveler arrived, thus granting the Watatsumi general, ever good at banishing the worries of others, someone who could help relieve him of his own woes.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Mountaineering Gear',
      title2: null,
      text: 'Of Gorou\'s various hobbies, "mountaineering" is likely up there in the top three.\\nSweating it out while climbing a mountain with companions before admiring the beauty all around you helps to train both the mind and body and is a great camaraderie-builder.\\nTo better enjoy this hobby of his, Gorou bought a set of mountaineering gear from a traveling merchant.\\nThe set is not particularly pricey, but it is both sturdy and durable and has seen Gorou through many dangerous ascents.\\nJust as he maintains his weapons well, Gorou has also kept this set of gear in tip-top shape. There is little doubt that it will accompany him through many future journeys as well.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'There was a time when Gorou ascribed responsibility for victory or loss in battle entirely to himself.\\n"If only I became a little stronger, perhaps I\'d be able to turn the tide."\\nIt was in this spirit that Gorou trained his archery day and night, hoping to rely on his strength to lead his comrades to victory.\\nBut after some time on the battlefield, Gorou saw powerful warriors being isolated and captured alive, while weak troops in inferior positions could rout their enemies through unity.\\nThat was when Gorou realized that a single person\'s battlefield capabilities are limited.\\nGetting stronger is important, naturally, but uniting the troops to fight as one is even more crucial.\\nA troop can only be unbeatable if they are strong together.\\nHaving realized this, Gorou no longer pursued the apex of excellence in archery, but instead invested time and effort in those around him, helping everyone improve together.\\nThinking back on it, this may have opened the door for Gorou to obtain his Vision.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
