export const ittoVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'I\'m the head honcho of the Arataki Gang, and everyone knows my name...s. Names, I have many. Arataki "The One and Oni" Itto, Arataki "The Oni Sumo King" Itto, Arataki "The Pride of Oni" Itto, Arataki "Beetle Gladiator" Itto, Arataki "The Ultimate TCG Champion" Itto, Arataki "He Might Lose but He\'ll Never Admit Defeatto"... Anyway, these are some of the ones I usually go by, so go ahead, take your pick. I\'ll respond to whichever one you choose, I promise. Hehe, you\'re welcome.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: "Chat: Itto's Here",
      audio: '1101',
      text: 'Arataki "Numero Uno" Itto, here in the flesh! Hahaha... *cough*',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Snacks',
      audio: '1102',
      text: "Best flavor in the world? The sweet, sweet taste of victory. And that's why I've never spent a single Mora on any of my snacks — I've won 'em all fair and square... That's right.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Beetle Fighting',
      audio: '1103',
      text: "Don't underestimate the beetle — they can be some of the toughest little guys around! Yes you can, yes you can— Wanna know what's on this beetle's diet? Sweat and tears, that's what! That's how it gets stronger... I think we can all learn somethin' from that!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Pff, real men don't carry umbrellas... Oh boy, wow, it's really starting to pick up. Uh quick, c'mon, get yours out! C'mon, quick, quick, quick!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Hey! Raiden Shogun, is that you? Well guess what — you're not the boss of me. Uh-huh, that's right, you heard me! Go ahead, strike me down!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Alright, it's time for a snowball fight! You're never gonna win, though, I... Ha, ah... Ah-choo!!! Whew.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "The sky is clear and the sun is shining... Time to get the Onikabuto out for some training! C'mon little guy, let's go!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "Bottom line: Never let the wind get to you. Especially when you've got a killer hairstyle like mine. Oh yeah!",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning, sunshine! Hey, uh... So listen, I'm fresh out of Mora... again. But hey, who needs some lousy job when we can just go find somewhere fun to hang out! Haha, whaddya say?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Now that we've had some grub, why don't we go find somewhere to kick it for a while? Hanamizaka? Nah, boring. Tenryou Commission... No, no, no... Ah, forget it, let's go hang around Ritou!",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Shh! You hear that? *gasp* Oh no... it's a ghost, RUN!!! ... Haha, psyche! Ah, I got you good there! ... I got you, didn't I?",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "If you're tired, go ahead and call it a night. Hmm? Me? Oh, don't worry... I sleep with my eyes open... Haha... Literally.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Itto: Getting a Real Job',
      audio: '2001',
      text: "Oh, so they're saying I can't hold down a real job, huh? Well! Hahaha! Sorry to break it to ya, but I'm a delinquent. That means it's my job to not have a real job, and if anyone's got a problem with that... Who's got a problem with that, huh? You got a problem with that!? You got a problem with— *coughing* Sorry. Got a little worked up there. Where was I? Ah yeah, so work isn't really my thing, but don't worry — I don't rob or steal or anything like that. When I'm really runnin' low on funds, I just take the odd job here and there to make ends meet. You know, like transporting stuff, delivering documents, helping businesses attract customers... Just enough to keep the wolf from the door. Hehe!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Itto: Oni',
      audio: '2005',
      text: "The oni have been through a lot to get to where we are today, and look at us now — living peacefully alongside the humans. Unfortunately, there's still plenty of people out there who've got a bone to pick with us. Hmm? Change? Oh yeah, things are gonna change, alright! You can count on that! But I'll tell you what, it won't involve any sucking up to the humans on my part, nuh-uh! I'm gonna let my actions do the talkin'. They'll come to respect me eventually.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Cooperation',
      audio: '2003',
      text: "Hey, so I always see you running around everywhere doing this and that for other people, but you're not in it for the Mora, are you? No, you're just straight-up lookin' out for your fellow man. I know a true homie when I see one, and no one appreciates a homies' homie more than yours truly. Put it here, partner! You and I are gonna make a great team, I just know it!",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Response',
      audio: '2002',
      text: "You know what, I gotta admit — I respect you, always have. I could really see you as a member of the gang, you know — I mean, you really have what it takes... Whaddya say? I've even come up with a catchy title to tag on after your name, get this: \"The Traveler, 'Second to One'\"! Get it? 'Cause y'know, I'm numero uno, you're my number two, and together we're the most powerful duo in the whole friggin' world, baby! Hahaha! Ah... But, uh, all jokes aside, I know you're on some important journey or whatever. So, go ahead! Get out there and do whatcha wanna do! Just remember, the Arataki Gang will always answer your call.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Ugh, don't even ask. Just the thought of it makes my blood boil! First, the Shogun's Army goes out and steals everyone's precious Visions — which, already a heinous crime, right? But then... then they go and stick them all over that statue with absolutely no sense of organization whatsoever. I mean, think about it... the more powerful the Vision, the higher up on the statue it should go, that would make sense, right? But nooo, some class-A jerk in the Tenryou Commission thought it'd be funny to put my Vision right at the very bottom! Ugh... Come on!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Hina',
      audio: '3002',
      text: "If you ever have something on your mind, you can always try writing in to \"That's Life\" magazine's advice column. Ms. Hina always manages to come up with an encouraging and heartwarming response for all her readers. Just look at me — I used to be a lost soul, but not anymore, and it's all thanks to her. Oh, that reminds me, I managed to sign up for one of her upcoming meet-and-greets! I've been counting down the days — wish it would go faster...",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Horns',
      audio: '3004',
      text: "Question for ya! Do my horns look boring once you get used to them? 'Cause, uh, I was thinking of switching up the style, going for a total overhaul, you know? I'm thinking paint them in rainbow stripes and then strap a few Fireflies on for good measure! Eh, eh? I bet that would turn some heads on the streets... like \"Dude, you're rockin' those sweet rainbow horns, man!\" ...Ah, man, this is totally genius! I'm gonna round up the gang and get them working on it ASAP.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Wanna know the real secret to catching Onikabuto? It's all in the eyeballs. You gotta keep those bad boys squeaky clean at all times, make sure your eyesight's as sharp as a hawk. Trust me, when you're in the middle of a thunderstorm, and the rain's coming down, and the wind's blowing in your face, you gotta watch out, because Lavender Melons and Onikabuto? Well, they can really start to look the same... believe me, I know.",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Thoma',
      audio: '4001',
      text: "Some of the boys have been telling me that he was the star of the show at the Vision Hunt Ceremony. I'm like — are you kidding me??? How come he gets his own special ceremony!? Was the hundredth Vision supposed to be, like, stronger than the other ninety-nine, or something? Pff, nah, it can't have been that, 'cause, uh, hello! They would've chosen me if that's what they were going for.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Kamisato Ayato',
      audio: '4002',
      text: "Haha, I only wish I could have met my bro Ayato sooner. He really taught me something. \"You can kindle the warrior spirit in even the weakest of bugs\"... Yep, I really took that one to heart. If it weren't for those words of wisdom, I'm pretty sure I would have given up beetle fighting after losing for the 780th time... Heh, I guess sometimes it takes a warrior to understand a warrior. When we're playing trading card games or battling beetles, we're always totally on the same wavelength.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Yoimiya',
      audio: '4003',
      text: "Hmph, she's always showing off her fancy fireworks and toys to the kids. Well, I'm sick of it! Nobody steals my thunder! I'm the one that's supposed to be adored by the kids! Me! That goes for you too, you're siding with me on this, okay... Huh? Whaddya mean, you're not a kid? Eh, details. If you're shorter than me, you're a kid as far as I'm concerned.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaedehara Kazuha',
      audio: '4004',
      text: "Word on the street is that he blocked the Musou no Hitotachi after you escaped from Tenshukaku. Seriously? 'Cause I mean, that is awesome! Who knows how he pulled it off. Hey, now that I think about it, he's from a fallen clan, and I'm from a fallen clan... That kinda makes us equals, haha! Yeah, so next time someone attacks you, it's my turn to block the blade!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '25': {
      title: 'About the Raiden Shogun',
      audio: '4005',
      text: "During the Vision Hunt Decree, the Shogun had to send her top tengu in person to get my Vision off me. Heh, means she must have found me to be quite the pain in the neck. But, y'know, she's abolished the Vision Hunt Decree now, so no hard feelings, I guess. As long as she's learned her lesson, of course. 'Cause if she pulls something like that again, this old pain in the neck will be back with a vengeance.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About the Lady with Fox Ears',
      audio: '4006',
      text: "I crushed that Kitsune Ramen eating contest we had. Even all that Fried Tofu couldn't stand in my way — she didn't come close to beating me! ... I was, uh, bedridden for more than a month after that, but you know what? I'd rather lie in bed a winner than walk away a loser! So... Anyway, I had the last laugh, 'cause she had to foot the bill for 32 bowls of noodles! Haha!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Kujou Sara',
      audio: '4007',
      text: "You know what, yeah, she beat me during the Vision Hunt Decree. I'm not ashamed to admit it. When you lose, you admit defeat, and when you screw up, you take it on the chin, like a man! And anyway, let's not forget which one of us won't agree to a rematch — her, the tengu warrior! It's just a sumo street fight, I mean, what's she so afraid of? If she keeps snubbing me, I'm gonna have to stop calling her Kujou Tengu and start calling her Kujou Chicken! Heh, we'll see what she thinks of that.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2007,
              questTitle: 'A Flower Blooms in a Prison',
              chapterId: 1202,
              chapterTitle: 'The Immovable God and the Eternal Euthymia',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'About Gorou',
      audio: '4008',
      text: "Oh yeah, the doggy general in the resistance... Hey, I've gotta hand it to him, he may be on the small side, but he's got quite the fighting spirit. Also, he gives off this vibe that makes me feel all warm and fuzzy inside, almost as if he understands my innermost feelings... I mean, I've barely met the guy, so that's kinda weird.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Kuki Shinobu',
      audio: '4009',
      text: "Nobody questions my leadership in the gang, what I say goes — except when it comes to Shinobu. She's always challenging everything I say. And not only that — all the hard-earned loot I bring back and share with everyone? She goes and returns it! But also, she gets me out of jail, and out of every mess we get ourselves into, so I'll let it slide. Besides, I don't wanna get on her bad side... An angry Shinobu would make my life a nightmare.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Sayu',
      audio: '4010',
      text: "All I did was give her a little pat on the head this one time when she wasn't looking, and now, she pounces to attack every time she lays eyes on me. Haha, what can I say? Tanuki are adorable! What am I supposed to do — not pat one on the head? ...Oh yeah, and that's the other thing — she beats you up for calling her a tanuki, too! What's up with that? I mean, a tanuki's what she's going for, right? Sheesh, talk about getting your fur all ruffled over nothing...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Itto: I',
      audio: '5001',
      text: "I know what you're thinking: \"I don't see it — how did this guy get to become the boss of the Arataki Gang on the back of beetle fighting and trading card games?\" Well, you're right, those are just child's play. Wanna know the hard skills that really got me where I am? Eating ramen standing upside down, sleeping with my eyes open, playing the harmonica with my nose, and swatting houseflies with my hair. Yeah, I know. Betcha see it now, huh?",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Itto: II',
      audio: '5002',
      text: "People in Inazuma have this ritual every time there's a holiday, or they move, or get sick, or whatever, where they throw beans around and chant: \"Fortune beans are falling down, send the oni out of town. Fortune in, oni out. Fortune in, oni out!\" ...Ugh, the chant gets worse every time I hear it, but the streets full of beans, with my allergies? Total disaster. I've gotta fix this, for every oni out there! We're innocent, people! Quit trying to ward us off and drive us out every time there's a minor life event!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Itto: III',
      audio: '5003',
      text: 'In a... "attempt"... to end human prejudice toward the oni, I had the gang use a Kamera to take a picture of me showing my softer side and stick it to the Message Board in Inazuma City. Next thing we know, some jerks have graffitied all over it! Tsk! Then, some ashigaru blockheads from the Tenryou Commission accused me of disrupting the peace, next it was the Yashiro Commission, complaining it ruined the atmosphere in the area, and finally, even the Kanjou Commission got involved — they sent some lackeys over demanding advertising tax! Ugh, they have no idea who the bad guys are here!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Itto: IV',
      audio: '5004',
      text: "In the Arataki Gang, we're proud to welcome people who've experienced adversity in their lives. Don't listen to the people who call us freaks, or weirdos. Every member of my gang is like family to me, and they all feel the same way. Whatever happens, the gang will face it together — both the highs and the lows.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Itto: V',
      audio: '5005',
      text: "I gotta respect the Blue Oni for sacrificing themselves so that the Crimson Oni could live on... In principle, though, I'm absolutely against it. No one should have to sacrifice their own kind for the sake of a better tomorrow, period. It's only a better tomorrow if it's a better tomorrow for everyone. We need to work together, not have everyone just focused on themselves, making their own sacrifice, trying to look cool in the process... Eh, I guess there's no changing the past, what's done is done. But from this day forward, no more sacrificing, not on my watch! You go to sacrifice yourself, I'll stand right in your way!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 12026,
              questTitle: "The Oni's Pride",
              chapterId: 2026,
              chapterTitle: 'Rise Up, Golden Soul',
            },
          ],
        },
      ],
    },
    '36': {
      title: "Itto's Hobbies",
      audio: '6001',
      text: "Beetle fighting, trading card games, spinning tops, kendama, hide-and-seek, you name it, I can play it! Whaddya say, pick one and we'll have a little contest? Just make sure you're ready to get thrashed! Hahaha!",
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Itto's Troubles",
      audio: '6002',
      text: "Granny Oni isn't an oni at all... In fact, she's the kindest human that has ever lived. She only got her nickname because she took me in. If people have got a problem with me, fine, I don't care what other people think anyway... *sigh* But I wish people wouldn't go after her because of me.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'Lollipops are pretty much the best things ever. The candy tastes awesome, but also, it looks really cool just having a stick hanging out of your mouth. It gives me, like... a real punk kind of vibe. Here, you try it!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Uh, well I am an oni! So there's nothing I hate more than beans. Soybeans, Mung Beans, whatever, I hate 'em all. Just touching one is enough to set off my allergies, let alone eating them. We have to get people to resist this constant urge to throw beans everywhere!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Hahahahahahahaha! Mm, mm, mm! I haven't eaten somethin' this good in three whole years!",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Fine! I'll let you treat me to a meal today, but know that the Arataki Gang always pays its debts.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Hey, are you sure you ain't trying to poison me!? Ah!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "Today's an important day. I had to send the gang away, otherwise they'd be accusing me of favoritism. Here, take a look at this. I got you the greatest birthday gift combo ever! One top-grade Onikabuto — I'll have you know it took me three whole days and nights to catch this bad boy — one out-of-print collectible trading card that took me 300 rounds to get my hands on, and finally, a birthday song performance performed personally by yours truly! Happy Birthday to you, Happy Birthday to you, Happy Biiiirthday dear Traveler, Happy Birthday to youuuu!",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Now that's what I'm talking about, baby! Woo-haha! Better look out, I'm way stronger now!",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Ah yeah, this is gonna do wonders for my win ratio!',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Feel the power, baby! Wanna see me smash a boulder?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I think \"Numero Uno\" just went from nickname to reality, boom! Haha! Hey, but just because I made it to the top doesn't mean I'm gonna forget all the things you've done for me, okay? I've still got your back, anytime, anywhere.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Let's roll!",
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Haha! Bam!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Attaboy!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Oni, comin' through!",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Who wants some of this!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "It's SHOWTIME!!!",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Alriiiight! New toys for the boys!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "I'm on a roll, haha!",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Hello, free money, goodbye working for a living.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: "Can't catch me!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Never underestimate an oni!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: "I'm not losing! It's all... part of the plan...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: "It's just a scratch, I swear!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Lemme at 'em!",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Tag me in! I got this!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'See you at the... rematch...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: "At least I'm going down... with style...",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: "My boys... I've let you down...",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'You want some of this!?',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Light Hit Taken: II',
      audio: '900002',
      text: 'Hah! Is that all you got!?',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Okay, that one hurt!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: "Hey! I wasn't ready!",
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Step aside! Itto's back in town!",
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'I am the MAN!',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'And the crowd goes wild!!!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'While walking through Hanamizaka, it is hard not to notice a young man of the oni race named Arataki Itto.\\nNever mind his horns or piercing voice sticking out like sore thumbs — the sight of him enthusiastically joining in to play childrens\' games is enough to set him apart from the crowd.\\nIn any case, his obvious lack of things to do stands in stark contrast to Hanamizaka itself, where craftspeople gather in droves and busy themselves all day long.\\nItto claims to be the "first and greatest head of the Arataki Gang," the responsibilities and duties of which he tried to explain to some Tenryou Commission officials when they came to him to investigate a rather harmless street brawl. Unfortunately, they interrupted him not two minutes into the explanation before marking him down as "unemployed."\\nThat designation is not exactly accurate, of course: other than the Gang\'s activities, which the Shogunate does not acknowledge, Itto does also do some odd jobs to stay solvent, usually working one day before taking three days off.\\nAs such, a more accurate designation should have been "three-quarters unemployed."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Objectively speaking, Itto\'s reputation leaves much to be desired within Inazuma City.\\nEven though he is not considered a villain, he is certainly no law-abiding citizen either. If one really had to assign some sort of hazard level to him, then perhaps the level of being used by parents to keep naughty children in line ("If you don\'t behave, Arataki Itto will come and snatch your snacks away!" for example) might suffice.\\nThat said, unlike threats of "the Great Mujina Youkai grabbing you and taking you deep into the mountains," or "being inlaid upon the Shogun\'s statue," the scenario threatened here can actually occur.\\nStill, "snatching" is, again, not accurate, for the fate of these snacks is decided fair and square by ritual combat!\\nIn the eyes of many, winning snacks off kids in competitions is exceedingly shameless, but Itto believes that every battle must be taken seriously, whether one\'s foe is a 5-year old child or the Almighty Shogun herself.\\nIt is also due to this conviction that Itto can lose to a child without any reservations at all.\\nAnd while the adults have much to say about his behavior, the children find Itto the big oni to be a rather good playmate.\\nHe is knowledgeable about all manner of street games and plays them all with great gusto. He also stands up for any who are being bullied.\\nLately, the children have been very into Onikabuto battles against Itto.\\nThe rules of this game are simple and the fighting is both fierce and very watchable. Most importantly of all, they actually have a pretty decent chance of winning this one, unlike with other games.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'For the longest time, the Tenryou Commission has regarded the Arataki Gang as a group of only occasional troublemakers who do not require that much attention.\\nThis group only has less than 10 regular members and there are many internal disagreements concerning the date of its founding.\\nAkira believes that it all began when Itto saved him from a few two-bit ruffians. That day, Itto persisted even after having been knocked to the ground 7 times, ultimately causing the punks to back off in annoyance. Helping Akira up from the ground, Itto declared: "Well, guess you\'re with the Arataki Gang now!"\\nGenta and Mamoru believe that the Gang was truly founded at the end of a certain year when they all squatted on the outskirts of Inazuma City and roasted Lavender Melons.\\nThat day, not one of them had a single Mora to their name, and they were all very hungry indeed. While gorging himself on a melon, Itto said with a sigh, "We should roast Lavender Melons like this every year!"\\nThat said, neither Genta nor Mamoru thinks that these experiences need much memorializing.\\nFor Kuki Shinobu, the Gang was officially formed the first time she had to drag Itto\'s sorry behind out of Shogunate gaol, for this was the first time any official records had ever made mention of the Arataki Gang.\\nAs for Itto, he believes that the Arataki Gang existed from the first moment those words entered his mind.\\nUnfortunately, he no longer remembers when that was.\\nAnd as for Granny Oni, who has taken care of Itto since he was young, she believes that the Gang was never formed.\\nTo her, these children are just "Itto and his friends."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'The land of Inazuma has been home to the oni race since antiquity.\\nThey existed here alongside the lordly Hakushin kitsune bloodline and the tengu.\\nSuch youkai often have supernatural abilities that humans could only look upon in envy, but the oni lack many special traits in that regard.\\nOther than the horns on their heads, they are mostly remembered for their explosive tempers and penchant for making trouble.\\nAs for their legendary fear of beans, it has a scientific basis.\\nAs it turns out, oni are allergic to beans. However, because the oni bloodline has thinned out greatly over time, most people display only very minor allergic reactions.\\nUnfortunately for Itto, his allergies are still pretty severe. Forget eating beans, so long as he makes skin contact with them, Itto will get itchy all over and even find it hard to breathe.\\nThis thus makes beans the only thing that the usually carefree Itto is particularly wary of in his daily life.\\nFor their part, the Arataki Gang members do not order any dishes made with beans, not even in private, as a mark of respect for him.\\nOf all products made with beans, Itto fears Fried Tofu the most — indeed, he even says that the very sight of it leaves him feeling queasy for three days straight.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "And when one mentions Fried Tofu, a certain pyrrhic victory immediately comes to mind.\\nThe battle that caused that incident began as a rather pedestrian conflict: a fox-eared lady had happened to sit in the chair that Itto would customarily sit on while eating at his favorite food stand... and on his payday, no less.\\nThe two began a contest of words over whom the chair belonged to, culminating in a straight-up (unnecessary) battle.\\nItto, hungry from a hard day's work, chose an eating contest, while the fox-eared lady chose a theme of \"kitsune ramen.\"\\nItto was momentarily at a loss when he realized that said ramen contained Fried Tofu, but with the oni race's pride on the line, he soldiered on gamely en route to victory nonetheless.\\nAnd as for that innocent chair, it was ultimately given to Itto as a trophy by the rather mortified owner of the food stand.\\nRegarding the various contests he has been in, there are two that still weigh on Itto's mind quite heavily.\\nOne of them is the rematch that he demanded of Kujou Sara, who defeated him and took his Vision as part of her duties in the Tenryou Commission.\\nTo this day, the Kujou has not agreed to the street corner sumo match, something that frustrates Itto to no end.\\nThe other incident happened many years ago when Itto was young. Then, he had gotten into an argument with a young tengu, the result of which was a sumo match in the Byakko Plain. Unexpectedly, the ensuing furor sent them both rolling down a mountain.\\nIn the end, it was the tengu who carried Itto, who could not walk after spraining his ankle, all the way home. Of course, the match went unsettled.\\nJust his luck, Itto often thinks, that both such incidents had to do with tengu!\\nAlso, how on earth were these tengu all so strong despite looking so skinny?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Every oni child has probably heard the story of the Crimson Oni and the Blue Oni:\\nThe gentle, helpful Crimson Oni defeated the wicked Blue Oni, thus winning the respect of the humans.\\nThis was Itto\'s favorite story when he was young, and he was proud of his red oni horns and his Crimson Oni lineage.\\nHowever, this simple pride was shaken by a certain incident.\\nWhen incidents of robbery occurred in the village in which Itto lived, the Arataki family fell under suspicion on account of their oni heritage.\\nItto no longer remembers the details of that incident, but he remembers the wary, disgusted stares the villagers gave him and his parents as they left, and the parting words they said, which Itto has heard countless times since:\\n"Once an oni, always an oni."\\nNo matter the time period, all oni are the same as far as humans are concerned. In that case, would it not be better to become the Blue Oni, whom people feared? Surely that was preferable to being like his parents, who were driven out despite having done nothing wrong.\\nAfter his parents died of illness, the young Itto was turned out onto the streets, where he would lay into anyone who spoke ill of the oni race.\\nWell, Itto was mostly the one getting laid into. But he proved quite the pain in the neck, never giving up no matter how many times they knocked him down.\\nStill, he was only a child and eventually collapsed on the street due to exhaustion and hunger after a terrible round of beatings at the hands of some ruffians who had banded together against him.\\nAt this moment of crisis, Itto was saved by an old human woman.\\n"Why did you save me? Can\'t you see that I\'m an oni?" "You must be hungry. Come, I\'ve made some porridge."\\n"I told you, I\'m an oni! Can\'t you see them horns?" "Oh, I can see them. Do you want some of that porridge, by the way?"\\n"Agh, you know what, you\'re not listening to me at all. Oh, alright... One bowl of porridge, please." "Coming right up."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'The Great Singalong',
      title2: null,
      text: 'As the year was drawing to a close, the Arataki Gang met to discuss how they might celebrate the turnover of the year.\\nAs opposed to more reputable organizations, the Arataki Gang did not have any fixed venues to hold their activities, which posed some... logistical issues.\\nThe Lavender Melon suggestion was quickly eliminated. While roasting melons itself was certainly not an issue, eating only that to celebrate the new year certainly was.\\nAn Onikabuto festival was considered, but the year\'s end was not mating season, and so the contestants would not be half as motivated as they usually were.\\nUltimately, lots were drawn, and the "Great Singalong" was selected.\\nThis activity was suggested by Itto himself, and it entailed everyone standing on a cliff and singing against the ocean wind to express their innermost feelings and well-wishes for the future.\\nThe various gang members actually rejected this in their hearts when they found out about it. After all, screaming into the wind was nowhere near as fun as eating melons. Kuki Shinobu even indicated that she would like to take leave to return home on that day.\\nHowever, the event went through nonetheless. The yelling and hollering were indeed quite soothing for the soul — and as things unexpectedly turned out, Itto was quite the good singer as well.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Itto's Vision was something he found under his hip after waking up one morning. By that point, he had already been in Hanamizaka for many a year, and his livelihood was at least somewhat stable.\\n\"Well I never! Dad, Mom, Gramps, Granny, and Granny Oni, this... Now isn't this something?\"\\nThese were Itto's real thoughts as he first looked upon his Vision.\\nThat day, he would excitedly show his Vision to every person he met, even showing people where it had made an indentation on his back until everyone was thoroughly sick of hearing the story.\\nA few days later, however, the story would change a little:\\n\"Now as you know, I wasn't surprised at all when I first saw that Vision. I mean, you'd expect as much out of the first and greatest head of the Arataki Gang, after all!\"\\n\"More importantly, a person's worth isn't something that can be determined by a mere Vision, oh no, sir!\"\\nThe keen-eyed, however, would notice that Itto had bought a very soft spectacle cloth.\\nAlso, a certain question showed up in the advice column of the \"That's Life\" magazine that went like this:\\n\"Ms. Hina, how should I best take care of my Vision and make it shinier? And when I say 'shinier,' I mean shinier than everyone else's, of course!\"\\nWhen gang members read this and excitedly showed the magazine to Itto, they were surprised to see the long-time fan of Ms. Hina just look at the mag casually before laying it aside.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
