export const kachinaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Hello! I'm ___, a member of the Children of Echoes. I adore Grainfruits and would love to become more strong, even though I'm still not much of a fighter. Uh... I should probably save all that for later, right? Then, um... Are you hoping to go somewhere? I'm pretty familiar with these parts, so I can show you the way!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Staying Organized',
      audio: '1101',
      text: "Ah... I just saw a brick that wasn't properly stacked. What should I do? Now it feels like there's a little Saurian scratching away inside my chest...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Can I Do It',
      audio: '1102',
      text: "I can do it... No, I can't... I can do it... No, I... Ahem, it's fine, I can definitely do it!!! ...Right?",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Collectibles',
      audio: '1103',
      text: "If you're bored, why don't we take a look at my collection together? If something catches your eye, feel free to take it!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Rain makes the soil all muddy and soft, so you've got to be even more careful than usual when you're mining!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Aaah!! Um... I—I'm not scared! I was just... caught off guard!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Let's go roll around in the snow together! Hehe, don't worry, I won't hide in the snow before suddenly jumping out at you like Ayo does!",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "Come look at this gem! When you hold it up under the sun, it almost looks like it's got a whole rainbow hiding inside!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'In the Desert',
      audio: '1205',
      text: "Do you think there's any shiny ores underneath all of this sand? We can do a quick dig just to check!",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Good morning! I've already packed everything, so we can head out whenever!",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "I'm not sleepy, so if you want to take a nap, I'll keep watch. There are a lot of things that I'm not that good at, but my ears are still plenty sharp! I can hear trouble coming from a mile away.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Mualani asked me to go into a cave with her tonight in a test of courage, and I—I—I'm... I'm so scared! What should I do? I didn't want to disappoint her, so I closed my eyes and said I'd go... No matter what happens, I should face it together with her! Ehh!? You're coming too? Th—Thank goodness! Phew...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "*sniffle* I don't know how I managed to screw things up again today... Nooo, I don't wanna cry, but I just can't seem to help myself... *sniffle*... Ahh! D—Didn't we both already say good night to each other? Th—Thank you for staying up and comforting me though, it means a lot...",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Turbo Twirly',
      audio: '2001',
      text: 'Ayo and I came up with the name together! I had already decided on the first part, "turbo," and then I chose "twirly" because I noticed it looked a lot like Ayo in action. I often race against Ayo on it, and I\'ve even won!',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Dying',
      audio: '2005',
      text: "Falling in battle during the Night Warden Wars is an honor for the warriors of Natlan. As one of their number, I should feel the same. But while I was down there, even as I kept repeating that to myself, I was still terrified the whole time... I'm really grateful that you took such a huge risk to go to the Night Kingdom and bring me back... *sniffle* Really, I can't thank you enough!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5007,
              chapterId: 1501,
              chapterTitle: 'Black Stone Under a White Stone',
            },
          ],
        },
      ],
    },
    '15': {
      title: 'About Us: Legends',
      audio: '2003',
      text: "There are a lot of legends about heroes in Natlan, and my favorite is the one about Lord Traore! How incredibly cool is it to be able to seal the Abyss beneath the ground as an ordinary mortal? Oh, that reminds me... you've been to a bunch of countries in Teyvat, so you must know a lot of legends, right? I'm super curious... Could you tell me some of them when you can find the time?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Small Gift',
      audio: '2002',
      text: "Please pick one you like! Just think of it as a symbol of our friendship. I've brought all of my best and shiniest ores, so come on, take one! I'll be really happy if you do!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3006',
      text: "When I saw this shiny Vision for the first time, I really thought my eyes were playing a trick on me... It's more shiny than any ore I've ever seen. Even though I'm nowhere near as strong as a legendary hero right now, if one day, my story could inspire someone else, I'd be the happiest person in the world. Really, just one person would be enough...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "Ayo is a very important companion to me! Even though he looks well-behaved now, he really loved headbutting people when he was younger. He's super strong, so even I get knocked over sometimes. Not much you can do about it, though, because it's just how Tepetlisaurs show their affection! Oof, Ayo, stop headbutting me! Alright, alright, I won't say any more!",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'Did you know? Spinel fruit are shaped just like gems! Now, if only they had the same shelf-life as actual gems...',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Mualani',
      audio: '4001',
      text: "Mualani's my first good friend! Before I met her, I never even knew that people as sweet as her existed, or how many fun things there are in the world! Look, this is a photo of us! She said we should jump right when they took the photo... I look a bit stiff? Hehe, you caught me! A lot of people were staring at us when we took this photo, so I was really nervous...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Kinich',
      audio: '4002',
      text: "It was Mualani who introduced me to him! To be honest, I was a little scared of him at first, because his eyes... well, he's got a scary look. It was only later that I found out that he secretly taught my bullies a lesson. But when I tried to give him a gift to thank him, he refused to take it. He said something along the lines of having already received enough compensation...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Chasca',
      audio: '4003',
      text: 'She\'s a famous "peacemaker" in Natlan! They say she can resolve any conflict, no sweat. I guess that she probably does it because like me, she\'s really not a fan of people getting into fights with each other...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Iansan',
      audio: '4004',
      text: "Before, when I wanted to become stronger, I asked Iansan to train me. She had me do all sorts of high-intensity workouts, and I often only managed to get through them by pushing myself to the limit. Luckily, she always knew just the right amount of training for me, so I still had just enough energy to make my way home after each session... I'm really grateful to her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Citlali',
      audio: '4005',
      text: "Mualani told me that you were only able to save me thanks to her invention, so I have to accept my share of the responsibility for the destruction of the Spiritspeaker Stone. I worked up the courage to apologize to her in person, and asked her to pick a few rocks from my collection as repayment. She scratched her head and said, \"Well, it'll become an issue if I don't pick one, won't it? Then... We'll be even as long as I pick something reasonably similar, right?\" In the end, she waved me off after taking the most unremarkable piece of obsidian I had. What do you think? Should I try to get her something else? Do you know the kind of thing she likes?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5014,
              chapterId: 1503,
              chapterTitle: 'The Rainbow Destined to Burn',
            },
          ],
        },
      ],
    },
    '25': {
      title: 'About Xilonen',
      audio: '4006',
      text: "After I received my Ancient Name, Uncle Pacal took me to see her and asked her to make Turbo Twirly for me. Her craftsmanship really is out of this world!\\nLater, we discussed our experiences collecting and storing gems, and even admired each other's collections. Everything in her collection is in top condition, so she must take great care of them. She seems to take a more... casual approach to her own life, though... Once, I went looking for her, and couldn't find her for ages! I eventually found her basking in the sunshine in a big tree, sound asleep...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About the Pyro Archon',
      audio: '4007',
      text: "I never could have dreamed that the Pyro Archon herself would one day call me a hero of Natlan... She's the idol of every warrior in our land, so being recognized by her is like... *sniffle* I just get overwhelmed every time I think about it, sorry... *sniffle* Sorry, sorry! I shouldn't have started crying...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5007,
              chapterId: 1501,
              chapterTitle: 'Black Stone Under a White Stone',
            },
          ],
        },
      ],
    },
    '27': {
      title: 'About Ifa',
      audio: '4008',
      text: "Ifa's a really amazing sauro-vet! Any little Saurian who sees him comes back and starts living a healthy life! They eat right, sleep well, don't cause trouble, and basically don't get sick again! So whenever a Saurian's looking sick, everyone's first thought is to ask him to fly over and have a look!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'More About ___: I',
      audio: '5001',
      text: '"Uthabiti" is my Ancient Name — it means the ability to stay strong in the face of adversity. *sigh* But I often wonder why the Wayob decided to give the name to me. I\'m so weak, and whether at home or among the tribe, few people even know of me... With so many strong and cool people around me, am I really worthy of the name?',
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About ___: II',
      audio: '5002',
      text: "My family, huh... I'm the middle child of my family. My Dad's placed most of his hopes on my older sister, and my Mom has to spend a lot of time taking care of my younger sister. Our life isn't exactly easy, so I've got to be a good girl, and grow up quickly... Or at the very least, make sure they won't have to constantly worry about me.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Uncle Pacal is really nice to me! Whenever other people in the tribe talk bad about me, he always defends me. Still... I feel bad whenever he has to do that. After all, I need to win everyone's respect with my own hands...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "I've always known that crying won't solve anything, and I've never heard a legend talk about the hero crying in front of their friends, either. I really want to hold back my tears, but I just can't... Huh? It's okay? Tears are a good way to let out your emotions? Do... Do you really think so? *sniffle* Thank you, thank you... Oh no, why am I crying again?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About ___: V',
      audio: '5005',
      text: "I've always thought that it was only natural for me to be overlooked because I was weak. Now that I've talked with the Wayob though, I've changed my mind. \"Uthabiti\" is my Ancient Name, and I've... I've decided to become the best \"me\" I can be. There have to be things in this world that only I can accomplish. I will... keep striving. I hope this obsidian will one day hold a record of my deeds and become... even more radiant and dazzling.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5007,
              chapterId: 1501,
              chapterTitle: 'Black Stone Under a White Stone',
            },
          ],
        },
      ],
    },
    '33': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "This is the first gem I found. It's such a pretty shade of green, don't you think? It was originally one half of a pair, but I gave the other one to Mualani. Look, the pattern on it looks just like flowing water! Oh, and this one, too — it might look black at first glance, but put it under the sun, and you'll see all kinds of a rainbow of color! Hehe, I built this collection, one stone at a time!",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "___'s Troubles",
      audio: '6012',
      text: "Mualani gave me a huge hat once. It was super cool, and was perfect for blocking the sun, so I really loved it. Over time, though, it kind of turned into a felt hat... In the end, I had to get this hat instead, just because Saurian fur won't get stuck to it.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'I love Grainfruit Chips! I would love them even more if they could be stacked neatly into a tower.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Huh!? Is this really just one portion? But if I don't finish the whole thing, won't I have let the chef's hard work go to waste? I—It's alright, I'll finish the whole thing! Small bites, ___, small bites...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Whoa, is this for me? It's super delicious! I'm going to eat slowly, so I can savor every bite...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "The taste, the aroma, the presentation... everything about this dish is marvelous! If there's ever a cook-off, I'm sure you'd win!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Thank you for taking the time to make something for me! I—I promise that I'll finish this. Just... give me a few more minutes!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! This is for you. It's a pika carved from Iridescent Opal. Iridescent Opal's quite warm to the touch, but it doesn't really stand out, so it's easy to miss it underground. The more you carry it with you, though, the shinier it gets! It's one of my favorite gems, so I hope you'll like it too.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Are my ears... trembling? No, I'm not nervous... I'm just really happy. Sorry, but I can't really control them, they're way too excited right now. Here, I'll... let me just cover them up.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "You really care a lot about me... *sniffle* Ugh, I didn't mean to cry, but I'm just... so touched by your kindness.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: '"Though the court burned to rubble, the flame never once went out. It shall reignite the next morn, more radiant than afore." This is one of my favorite quotes from Lord Traore. I—I must keep working hard!',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "You've shown me all kinds of new and fascinating things, and really helped me to grow... I have no idea how I could ever repay you, but I want to find the answer by myself. So from now on, please allow me to be the hero... the hero that protects you!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Let 'er rip!",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Sha~bam!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Here goes!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Spin to win!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'Shockwave!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: "Let's go, Twirly!",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Clear the area!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Drilling down!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Get back.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Whoa! Look at all these shiny rocks!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Do you also like collecting shiny rocks? I mean, who wouldn't want to? They're so pretty!",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Need help organizing the loot? I'm an expert!",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: I',
      audio: '410001',
      text: "It's nothing, I can walk it off!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: II',
      audio: '410002',
      text: "C'mon... Pull yourself together, ___!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'I... I can do it! I have to!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Don't forget about me!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I'm here! Just leave it to me!",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Sorry... I pushed myself... too hard.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'My name... I must honor it...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'No... I messed up... again...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: "It's just a scratch!",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: "Oof... I'm fine.",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Whoa! I can... join the team?',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Oh yay! Okay, let's go!",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Another chance to learn from you!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Just like the other progeny of the Children of Echoes, ___ grew up surrounded by adorable Tepetlisaurs, spending her time digging shiny gems out of the bowels of the mountains and listening to her elders passing down the legends of heroes.\\nShe learned the mountain paths like the back of her hand, developing a great instinct and talent for finding minerals buried deep beneath the ground. When she had some time to kill, she\'d be with all the other kids, running off to the music studios where artists were recording their newest tunes to just cut loose and dance freely to the pulsing rhythms.\\nGrowing up in this environment, the occasional bump and scratch was unavoidable, and ___ would cry out in pain when she hurt herself, just like any other child. But long before any other kid would have recovered, ___ would have wiped away her tears and stood back up again.\\nIn the eyes of others, of course she was a good kid. But ___ still struggled to understand why someone as ordinary as herself was given the Ancient Name "Uthabiti."\\nJust what part of her was worthy of the ideals of strength this great name carried? Young as she was, she was unable to puzzle it out.\\nBut having been granted this great honor, she had an obligation to participate in the Pilgrimage of the Return of the Sacred Flame. Moreover, returning triumphantly from the Pilgrimage and rising up like the heroes of legend was the dream of every warrior of Natlan — including ___.\\nAs she experienced failure time and time again, not only was she overwhelmed with sadness, but she couldn\'t even lift her head to face the disappointed looks in the faces of her friends. Nevertheless, she would wipe away her tears, and stand up once more.\\nBut having already failed so many times, could she really achieve success in the Pilgrimage? ___, who always gave everything she had, to fight on, felt doubt creeping into her heart.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Other than the required applicant information on the Pilgrimage of the Return of the Sacred Flame pre-registration form, there is also a page for providing optional information about the candidate. The information it asks for includes, but is not limited to, hobbies, personal experiences, and so on. The original purpose was to make it easy for the promotional team to create materials to hype up participants, but practically everyone already knew all the info on the hottest contestants, so trying to find out that way was completely unnecessary. And so, over time, nobody took the supplemental form seriously. It seems like only ___ would carefully fill in every blank on the supplemental form every time.\\n"Hobbies: Dancing."\\nEvery member of the Children of Echoes knows a thing or two about dancing, and a stereotype the other tribes have about the Children is that dancing is in their blood. The moment music sounds, the children of the Nanatzcayan will start subconsciously swaying. But even among them, ___ is a gifted dancer, with great control over her body even from a young age. Her movements as she shifts her weight to the beat have always been as smooth as a swimming Koholasaurus. Even Pochtli frequently praised her, and Pochtli is not someone given to giving out compliments. Actually, ___ really wanted to write that down too, to prove she did have something to write about, but since she was worried it would look conceited, she let it go.\\nAs for her other hobby, she hesitated for a long time before finally deciding not to put it to paper.\\nDigging.\\nWhat she found embarrassing was that, like most members of the Children of Echoes, her favorite thing to do was dig around in tunnels. Whenever she discovered a vein of ore in a dark tunnel, a warm feeling would well up in her heart. Everyone in the Children of Echoes understood this warmth, but she thought writing "digging up minerals" in the "hobbies" section would only make it look like she lacked personality.\\n"I really don\'t have any strengths." She wanted to sigh.\\nThe next box was about the people closest to you.\\n"Dad, Mom, Ayo..." She began to fill in her family\'s names.\\nOther than her parents, who gave her so much love and warmth, the one closest to her was her Tepetlisaurus companion, Ayo. The one by her side the first time she tried digging alone was none other than Ayo. When her parents were recounting the legendary tales to her, and when she was out causing a ruckus, the one following close behind her was always Ayo. Just thinking of him, ___ couldn\'t help but smile.\\nShe wanted to add a few other names between the lines, like Mualani, who always encouraged her with a smile, and Kinich, who always extended a helping hand when she needed it most, and from her own tribe, Uncle Pacal... But she couldn\'t fit that many names in the space provided, so, she had to let them go.\\nWhen she finally finished filling it all in, and handed the supplementary form to the staff member on duty, they were absolutely flabbergasted that this pocket-sized little girl had actually filled out the entire form.\\n"That page is optional, you know. It\'s okay if you don\'t write anything down," they joked.\\nHer response was: "That\'s fine. Everything I can do well, I want to take seriously."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Tepetlisaurs and the Children of Echoes have been living together since before the time of ___'s grandfather's grandfather. It is the custom of the people to work and live alongside them, and become companions.\\nThis means that for the Children of Echoes, Saurians are not like the livestock whose lives and deaths are dictated by humans, nor are they like pets, beholden to the whims of their masters. They stand as equals to humanity.\\nMost bonds between Tepetlisaurs and humans are formed willingly, just like ___ and Ayo.\\nTepetlisaurus nests are never too far from Children of Echoes dwellings, and this proximity ensures Saurian and human are often running into one another, with the latter considering the former to be friendly neighbors, never thinking it odd to meet one occasionally.\\nFor a time when ___ was quite young, she'd often run into a robust young Tepetlisaur at the crossroads on the way to the mines. To ___, these simple, honest neighbors were a group worth greeting, so she'd always say \"Hi!\" to him.\\nAfter a time, it seemed like the little Tepetlisaur remembered her, and she began running into him more and more different places. Practicing dancing in an open field, gathering grainfruit, catching fish in the river... After so many encounters, the young Saurian and human would not only greet one another, but also sometimes exchange gifts.\\nWinning the little Saurian's friendship wasn't a complicated affair. ___ didn't need to worry about trying to prove her worth to him, or offering him special rewards. They simply felt comfortable hanging out together, so they spent time together.\\nUntil one day, the little Tepetlisaur just naturally followed ___ to her home, after which it became her family's companion, and ___ gave him the name \"Ayo.\" The whole thing was totally normal, no less natural than how fish must swim in water or how birds must soar through the skies.\\nFrom then on, Ayo always showed her the loyalty and affection he shows to friends, unlike some of the playmates she grew up with. They didn't hesitate to start keeping their distance after she failed time and time again in the Pilgrimage of the Return of the Sacred Flame, and some even mocked and ridiculed her. But Ayo has always stood firmly by her side with his sharp horn, never wavering.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: '"Uthabiti" carries the meaning of toughness and tenacity. At first, ___ did not think that she was at all worthy of such an Ancient Name, brimming with honor.\\nAfter consulting the ancient woven scrolls, and learning just what kind of people the ancient heroes who had borne the name before were, she felt even more perplexed.\\nThey all possessed incredible power, and would always remain bold and spirited, no matter what dangers they faced, for which they were revered by later generations; they had maintained their noble character despite enduring the harshest of conditions, protecting their homelands with naught but their own strength, never wavering in their duties or abandoning their responsibilities until their last breath. Looking back at herself, she felt she didn\'t have the strength of warriors of the Collective of Plenty, nor did she possess the agility of the Riders of the Flower-Feather Clan. Even though she didn\'t want to appear weak and easily bullied, in the face of constantly being belittled and even degraded, she couldn\'t help but cry and snuffle.\\n"Do tough people really cry all the time like I do?"\\nShe really was a long, long way from being anything close to "tough." After reaching this conclusion, she was despondent for some time, drowning in despair. But she quickly let go of those feelings. Not because she trained until she became a powerful warrior, or because she suddenly understood some profound truth. And though her friends and family did show her a lot of care and concern, her choice was mostly dictated by her own habits.\\nNo matter how badly you fall, the first thing you have to do is just get back up again.\\nWhen she was even younger, every time she fell, she would already have stood up when any other child would still have been wailing on the ground. Yes, the wounds still hurt, and her tears were still splashing to the ground, but these were just innate physical reactions. She consciously felt she should stand up and look at the rock that had tripped her before carrying on crying.\\nAnd the same is true now. Facing with a future without much hope, she felt intense fear, and was frustrated and lost. Being so young, she didn\'t yet understand how to conceal her own feelings, and so she wore her negative thoughts and emotions on her sleeve. But she would still stand up once more, sobbing and sniffling, her face painted by her tears and bruises, and keep practicing, keep pushing forward.\\nShe herself understood this as being able to take a beating, but in the words of Uncle Pacal, who was both more mature and more eloquent:\\n"Though people are weak, it is through their bravery in facing this cruel world that their greatness is truly revealed."\\nMaybe ___ really is tough.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'After returning from the Night Kingdom, it was as if the other households of the tribe looked upon ___\'s family in a new light.\\nSome who had never spoken to her family before began to take the initiative, greeting them when they ran into them. Those acquaintances that before had only ever politely offered some small talk when they met now actively sought them out to socialize.\\nWhether or not ___ was there, the conversation would — intentionally or otherwise — invariably turn to her. They would laud her bravery and toughness, praising her from the tip of Ayo\'s tail to the points of her ears. In fact, those rather distinctive ears, which had once only been seen as a common "atavistic trait," now became proof of her having been special from birth.\\nHaving experienced so many setbacks, yet in the end finally returning triumphant, she was the epitome of persistence and perseverance against the odds. All her previous failures and defeats became little more than footnotes to her feat, buried amongst the paeans.\\nSomething felt off to ___. Her mistakes and tears were being ignored by everyone, even though they plainly existed, concealed by the light of her success.\\nOthers could forget about all the countless failures she had endured, but she herself could not, nor did she think she should.\\nShe always thought she simply couldn\'t compare to those heroes who were victorious time and time again, and her triumphant return this time was intrinsically linked to the support of her friends. There was no way she could suddenly become the idealized version of herself who existed only in the praise streaming forth from others.\\nShe was still the ___ who couldn\'t stop herself from crying when dispirited, and she still wanted to be that ___ who would always charge forward, getting back up again no matter how many times she falls.\\n"Not getting knocked down is definitely one type of tough, but maybe not losing yourself in all the flowers and praise is another."\\nAnd so, ___ added another footnote to her understanding of the name "Uthabiti."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Every child of the Nanatzcayan has heard fables about raw ore and gems, and ___'s parents related one such tale to her before bed.\\nBefore the raw ore had been unearthed by the Children of Echoes, it had slept soundly in the depths below the mountains, alongside mud in its matrix.\\nAt first, it didn't know it had the potential to become a gem. It only endured the long dark and loneliness, and never called itself as such.\\n\"I'm just a chunk of totally ordinary rock.\" That's what it thought.\\nUntil a great gale had blown away the topsoil, the raging rivers had washed away the silt, an earthquake had sundered the strata, and finally, the drills of the Children of Echoes split it off from its place in the bowels of the mountain... Even then, it still hadn't realized it had a certain splendorous radiance glittering within its own rocky heart.\\nAs it was smashed and polished, the ore felt immense pain. As chisel and grindstone carried away many of its parts, and its ordinary rind was carved off, the patterns that represented its timidity were smoothed away. In the eyes of the Children of Echoes, this was a process filled with joy and beauty, but the ore knew not what was happening, or what would come next. As its tears flowed, it asked the chisel and grindstone:\\n\"Why must this happen to me?\"\\nTo reveal your true nature as a gem.\\nBut those words remained unsaid. Unlike the ore, the chisel and grindstone had participated in the cutting of countless gems and witnessed the moment when the rays of light burst forth, and so they kept their silence.\\nUntil the work was complete at last, and the ore could finally see what it looked like in the eyes of others: a beautiful gemstone.\\nAs she walked alone through the Night Kingdom, ___ kept thinking of this story. She remembered that she had asked her parents: What happened next? What should a gemstone look like? But the chill of the Night Kingdom blurred her memories, and she couldn't remember the rest of the fable. Fortunately, the memories of being with her parents gave her warmth, allowing the fire of her soul to burn on. She decided to stop soul-searching, for whether she was low-quality ore shattered by the chisel or a gem that yet held hope, she had to continue onward. She had many more things she wished to do, and many people she wished to see again.\\nAt the moment she was bathed in sunlight once more, and saw the outstretched hand of the Traveler, she knew what a gemstone should look like:\\nA strong, sturdy structure, capable of holding up the world even in the darkest hour.\\nPossessing unquenchable hope, lighting up the pitch-black world.\\nNow, she has returned triumphant from the Pilgrimage of the Return of the Sacred Flame and proven herself. The day when others gaze at her with admiration has finally come, and she can bring them faith and courage. The Pyro Archon herself told her, the name ___ will be woven into the banners by the Masters of the Night-Wind, as a part Natlan's heroic saga, flowing into the Ley Lines, becoming an eternal legend.\\nThus did tears and courage finally smelt the gemstone named \"___.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'The Banner of Uthabiti',
      title2: null,
      text: 'We recite the names of the ancestors, we sing the names of the heroes.\\nThe brave warriors who inherit the name of "Uthabiti," we record and weave their words.\\nThe first strand of golden thread we offer to the sword-wielder who first created the name, a homely girl no taller than a child.\\nShe once held back the collapse of the cliffs with her own two hands, bearing the people of an entire tribe upon her shoulders.\\nIn spirit and in thought, she was many times greater than the tallest and sturdiest warriors in the entire history of Natlan.\\nThe bright fire of this hero\'s life burned out quickly, yet even at death\'s door, she laughed freely and uproariously, the lingering sounds clear and bright, like a great river breaching a dike.\\nThough her breath ceased and her heartbeat stilled, the weavers could still hear the sound of waves pouring forth from her shriveled body, only fading after seven nights.\\nThe second strand of golden thread we offer to the shield-bearer who lifted the name from the river of concepts once more, he who never once put down his shield.\\nThough he himself was slim as a reed, he stood and fought together with his shield for years after year, and never wavered no matter how time passed.\\nHis body was as silent as his shield, but his soul was wont to bellow over the battlefield.\\nEven within his urn, his ashes still attempted to solidify and burst through the vessel, leading all to declare he could not fit into such a small tomb.\\nFinally, his remains were scattered amongst the mountains, the glittering ashen gravel echoing like thunder as it struck the stone walls.\\nThe third strand of golden thread we offer to the anonymous ones lost between the layered banners, whose deeds have been hidden by history.\\nWere it not for the Wayob\'s revelations, it would be difficult for us to clearly see the traces of the blood and tears they left behind.\\nThe final moments of the great heroes were peaceful, and we offer our sincerest prayers that they burned themselves out in happiness and contentment.\\nThe fourth strand of thread is woven with Saurian feathersilk, and we offer it to the spear-wielder who held the name high above the Pilgrimage of the Return of the Sacred Flame once more.\\nIn the Night Kingdom, she traveled with the souls of the warriors who battle eternally, traversing the creeping dark and returning in triumph.\\nTears do not lessen the glory of the name "Uthabiti," and her return was inseparably linked to the start of a new age.\\nWe recite the names of the ancestors, we sing the names of the heroes—\\n"The one that dares stand firm as a mountain, their bones like battlements, and hold the sun\'s gaze — it is they that shall be given unto eternity."\\n"Fear itself should instead fear me, for my body is like a roaring blaze; destined to melt down all that is mean and lowly, then cast it once more as an epitaph."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "It was after her first Pilgrimage of the Return of the Sacred Flame. ___'s first Pilgrimage had ended in failure, all the lofty expectations from before having come to nothing. Everyone around her doubted her ability, but more painful still was that she began to find it harder to control her doubts about herself.\\nMaybe even the Wayob occasionally got it wrong? Could she really \"melt down all that is mean and lowly\" like in the poem? Or maybe she was actually the kind of mediocre child who should be melted?\\nIt was then that she rediscovered what digging meant to her.\\nShe had always loved drilling to the depths of the mountains, seeking out treasures, but this time, she didn't dig with any kind of particular goal. She just carried her drill and bored forward, as though as long as she just kept going, disappointment and sorrow would be unable to bore a hole into her heart, but instead became the drill in her hand, punching a hole into the heart of the mountain.\\nShe felt much happier moving forward endlessly through the darkness, where she might still turn up something good, rather than just enduring doubt and defeat. But in the world aboveground, that Pilgrimage would not be erased, and her defeat would march forward alongside time, a stamp ___ could never rub away. Whether hiding down in the darkness, or standing upright in the sunlight, she was still completely dejected, and if she had to choose, the former was harder to bear. Because there, the word \"failure\" constantly echoed in her head, and it was far more painful for her than any of the tears and sweat she had shed in her training for the Pilgrimage.\\nThe people of Natlan have a saying, that the Children of Echoes are a stubborn lot, and their lives are like the horns on a Tepetlisaur's head, soft yet sharp, and always charging forward. And much like the saying implies, stopping was never an option in ___'s mind. All she knew was moving onward.\\nPerhaps the heavens had decreed she could never become a towering hero, so all she could do was trudge on forward, shifting and testing and trying to take one step, then another.\\nOf course, what she didn't understand then is that while thrusting out your chest, holding your head high, and shouting your certainty of victory while charging forward is certainly something people aspire to, setting your jaw, gritting your teeth, and inching forward, bit by bit, one leaden step at a time, is also something truly awesome.\\nWhile underground, that was precisely what she was pondering.\\nBut at the same time, she would also occasionally dig something interesting up.\\nLike her Vision.\\nWhen she received a Vision of her own, she was naturally quite happy, but she had already experienced a similar feeling of excitement before, and that was when she had received the Ancient Name \"Uthabiti.\"\\nNeither the acknowledgment of an Archon nor of the Wayob meant that she would definitely accomplish some great deed, she had learned at least that much from reality, but what she hadn't learned was:\\nWhen the legends of heroes are in their embryonic state, they aren't the least bit noteworthy, nor are the tales very encouraging, being dark and gloomy instead. But all the initial motivation they need to achieve greatness is already present, and as long as the protagonists keep on moving forward, the future will shine brightly for them.\\nBut those in the stories can never know the ending beforehand, so as they run forward with everything they have, come what may, the tears they shed are all the more beautiful.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
