export const nilouVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Nilou_Hello',
      text: "Hello, I'm ___ from Zubayr Theater. We have one dance scheduled for today, and it's about to start — keep your eyes peeled!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Practice',
      audio: '1101',
      text: "First get into position like this, then move like that... Yep, that's it.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Sleepiness',
      audio: '1102',
      text: "Take a deep breath, as if you're about to blow up a huge balloon. Exhale all your sleepiness into it, and then, poof — it's now flying away!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Rest',
      audio: '1103',
      text: "Relaxing days like this are nice... Let's take it easy.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Nilou_When_It_Rains',
      text: "The weather and our moods are the same — they can both get gloomy. It's all right, though, because the sky will become even brighter after the rain.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Nilou_When_Thunder_Strikes',
      text: 'Thunder is kinda scary. Are you afraid of it? If so, I can share a nifty method to help with that.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: 'VO_Nilou_When_It_Snows',
      text: "Huh? Wow, it's snowing. You can really hear the snow falling. Add in the swirling snowflakes, and it feels like the spirit of nature is dancing.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: 'VO_Nilou_When_the_Sun_Is_Out',
      text: 'Sunny days are so warm and cozy... *yawn* They make me sleepy...',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: 'VO_Nilou_When_the_Wind_Is_Blowing',
      text: 'Are you all right? Watch out for sandstorms.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: 'VO_Nilou_Good_Morning',
      text: "Good morning! Huh, why are you staring at me? ...M—My hair's sticking up? Ahh, don't look! I'll go fix it right now.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: 'VO_Nilou_Good_Afternoon',
      text: 'Uhh... Mmm... Should I eat some baked goods, or should I get something with rice? Or maybe... I can have some hummus instead?',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: 'VO_Nilou_Good_Evening',
      text: 'Good evening! I have a performance at Zubayr Theater tonight. Want some tickets?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: 'VO_Nilou_Good_Night',
      text: "Remember, let out all your frustrations before bedtime for a better night's rest. If you want, I'm more than happy to be your audience.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Body Language',
      audio: '2001',
      text: "Sometimes, you can convey more with dance than words. If you don't know what to say, then just dance.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Dance and Wisdom',
      audio: '2005',
      text: "You need an extreme amount of talent to pursue knowledge and wisdom. Many people throw their entire lives into it, only to end up burned out and depressed... Dance isn't like that. You don't have to understand what you're seeing to enjoy watching it. If I can use my movements to demonstrate the beauty and meaning of dance, then I'm happy.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Dealing with Anger',
      audio: '2003',
      text: "Are you sulking? That's no good — c'mon, follow my lead. First, use your right hand to draw a biiig circle in front of you. Then, use both hands to take all those negative feelings off your chest and into the circle. Next, push it away as hard as you can! So? Feeling better now?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Going on Adventures',
      audio: '2002',
      text: "I've never left Sumeru City, but... I want to go on adventures with you. Going to new places will be fine as long as I can adjust... Umm, quick question: Inazuma's beaches won't have huge Wenut that'll suddenly jump out at us, right?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: 'VO_Nilou_About_the_Vision',
      text: 'I received my Vision when I debuted on stage. If even the goddess was willing to watch my performance, then that must mean she had acknowledged the beauty of human-made art.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: 'VO_Nilou_Something_to_Share',
      text: "It's normal for hard work to produce no results. For example, no matter how hard I try, I can never understand the Rtawahists' teachings. When you're stuck, shake up your mind, flip your brain around, and change the direction you're going in.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things: Dance of the Crystalflies',
      audio: '3003',
      text: "Crystalflies come in all sorts of colors. They're so pretty that you can't not be curious. When you quietly reach out to one, it instantly steps into an elegant and nimble dance, and flies away from you. Hehe, if I could fly, I'd take dance lessons from them.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things: Padisarahs',
      audio: '3004',
      text: "When the Goddess of Flowers danced, real Padisarahs would bloom underneath her feet. That sounds like such a beautiful scene. I'd love to see it.",
      tips: 'Complete "The Morn a Thousand Roses Brings."',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3012,
              chapterId: 1302,
              chapterTitle: 'The Morn a Thousand Roses Brings',
            },
          ],
        },
      ],
    },
    '21': {
      title: 'About Cyno',
      audio: 'VO_Nilou_About_Cyno',
      text: "I don't really like interacting with people from the Akademiya because they don't view the arts too kindly. I often wonder what they do when they're bored... Huh, Cyno plays Genius Invokation TCG? I can't believe it...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Tighnari',
      audio: 'VO_Nilou_About_Tighnari',
      text: "I hear he's a really talented botanist. He must be good at telling apart mushrooms. At least, he would never have to worry about eating a poisonous one... I'm so jealous.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Collei',
      audio: 'VO_Nilou_About_Collei',
      text: "She sometimes comes to watch my performances. She's a really hard-working Trainee Forest Ranger. One time, she warned me about getting lost. What did she mean by that? It's not like I've gotten lost before...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaveh',
      audio: 'VO_Nilou_About_Kaveh',
      text: "I heard he was the one who built the magnificent Palace of Alcazarzaray. He must have had a wonderful time making such a masterpiece, like when I'm in the middle of dance practice. Just thinking about dancing for everyone gives me so much happiness and motivation.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Dehya',
      audio: 'VO_Nilou_About_Dehya',
      text: "It's hard to believe that so many things have happened recently... I wanted to pick out a good present for Dehya and Dunyarzad, but I just can't make up my mind. Everyone at the Grand Bazaar has given me many suggestions, but if I took them all, it'd be too much... What should I do...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3012,
              chapterId: 1302,
              chapterTitle: 'The Morn a Thousand Roses Brings',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Dori',
      audio: 'VO_Nilou_About_Dori',
      text: "The big-spending merchant Dori has watched me dance before. I remember that she talked with Mr. Zubayr once, and then never came back. Did something happen? ...Huh? She wanted me to go on tour around Teyvat? No way, Mr. Zubayr definitely would've refused for me! ...Ahh, please tell me he has...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Lesser Lord Kusanali',
      audio: 'VO_Nilou_About_Lesser_Lord_Kusanali',
      text: "The people of the Great Bazaar love Lesser Lord Kusanali. I'd love to hear her thoughts on my Dance of Sabzeruz... Oh, no, no, forget it... If she were in the audience, I'd get stage fright...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3012,
              chapterId: 1302,
              chapterTitle: 'The Morn a Thousand Roses Brings',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Aaagh! Sorry, I'm trying to decide what to eat, and I got lost in thought. Hee-hee, do you need help with anything?",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'My teacher taught me everything there is to know about dance, but she said that the most important thing is putting feeling into your movements. Only then can you move your audience and convey emotion. To express beauty, I must first become the embodiment of beauty.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Sometimes, I receive letters from showgoers who say that my dancing has cheered them up. I always share this kind of happy news with everyone at Zubayr Theater. Even though I'm the one the audience sees on the stage, it's because of everyone's collective efforts that I can stand up there in the first place.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "The Grand Bazaar occasionally hosts other kinds of performances, such as juggling showcases. I've tried juggling before, but I always end up catching the balls with my head... Mr. Zubayr and everyone else just laughed at me. They probably thought I had really good hand-eye coordination. Hee-hee, I've been exposed.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About ___: V',
      audio: '5005',
      text: 'Someone once told me that I was like a shining oasis that restored life and happiness to others with its warmth. That was nice of them to say, and I was happy to hear it, but... what I want to show people is much more than that. After spending so much time with you, though, I finally understand how it feels to have someone care for and look after you. Now... Now, I feel like that comparison is a far better one for you.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "___'s Hobbies",
      audio: '6001',
      text: '"My life is dance," or "Dance is my life"... Which phrase is the better way to describe it? Agh, I\'m no good at logical things like this. Anyway, I\'ll just keep on dancing. I want to use my performances to show the beauty of art to more people.',
      tips: '',
      tasks: null,
    },
    '34': {
      title: "___'s Troubles",
      audio: '6002',
      text: "I still can't tell poisonous mushrooms apart from non-poisonous ones... Apparently, color doesn't mean much — poisonous mushrooms can be bright or dull. Mmm, I feel like I understand, but I also don't...",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: 'VO_Nilou_Favorite_Food',
      text: "Sweets always make you feel better! Most people in Sumeru love them. Wanna try some? I'll get some for you!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: 'VO_Nilou_Least_Favorite_Food',
      text: "I have a hard time eating mushrooms, mostly because I'm scared... Not the type of scared that makes you want to run away, though! When I was little, I once ate a poisonous mushroom and was bedridden for days... If you want to eat any of Sumeru's mushroom dishes, please make sure to check that the ingredients are all edible!",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'This must be what it feels like to have flavors dancing on your tongue... How wonderful!',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Thank you. You must have put a lot of love and effort into this dish, just like I put so much of me into my dance practice.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Sorry, my appetite's been a bit off lately. Please don't take offense.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: 'VO_Nilou_Birthday',
      text: "Umm... Happy birthday! I learned a new dance, and I want to show it to you. Uh, am I nervous? *sigh* You saw right through me. It's because... I wanted to incorporate my feelings into the moves, but then the choreography just got more and more difficult... Anyway, I just wish that your life will always be full of wonder and happiness.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Huh? What's this feeling...?",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I'm done warming up. I can do even better now!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "I feel like I'm lying down on the back of a massive Anemo Slime. Ahh, it's so light and comfy~",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I really like being with you. I don't know why, but it feels like a butterfly is trying to burst out of my chest... Anyway, how about I show a new dance to you?",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Here!',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Positions!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'With all my strength!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Dance with the waves!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'All eyes on me!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'This dance is for you.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'For you~',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Let me help you pack this up.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Wow, what a lovely surprise!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Ah, don't worry about me...",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'How troublesome...',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Deep breaths...',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Don't worry, I'm here.",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I'll stand in for you!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: I',
      audio: '500001',
      text: "It's time for the curtain... to fall...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: II',
      audio: '500002',
      text: "The show... can't go on...",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Beauty... Don't leave me...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ah, I gotta keep my balance...',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'That... hurt a little.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Where are we dancing today?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Anything I can help you with?',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "...Oh, you're calling for me? Coming!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "\"Since you're in Sumeru, you must not miss ___'s performances.\"\\nThis is a fact that most people in Sumeru agree on.\\nThere is no threshold for ___'s dances, so everyone can come and enjoy a most fascinating and engrossing time there.\\n___'s audience comes from all walks of life. Be it a knowledgeable researcher or a mercenary who's seen true brutality — everyone is attracted here by ___'s gorgeous, dancing form.\\nEvery time ___ takes the stage, a press of people crowds the Grand Bazaar until all are standing shoulder to shoulder.\\nRational sense and wisdom are the mainstream in Sumeru, while art, which stands for sensibility, does not enjoy the same popularity and respect.\\nYet if wisdom is meaning bestowed upon Sumeru by the goddess, then art stands for meaning that human beings seek for themselves.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Unlike other dancers across the continent who hail from artistic families, ___ came from an ordinary family in Sumeru.\\nThe life that the family of three once lived was no different from that of many who lived in downtown area.\\nThe knowledge they gained from the Akasha was enough for their common day-to-day lives.\\nIf there was anything special about ___'s family, it was that ___'s parents' loved and cared for her very much.\\nAlthough the pursuit of scholarship is prevalent in Sumeru, ___'s parents never compared ___ with other children, nor did they expect ___ to become a researcher.\\nGrowing up happily and living a stable life was all that they wanted for her.\\n___ thus grew up surrounded by love and respect.\\nLater, even when there were differences of opinion and occasional arguments between her parents, ___'s thoughtful and considerate mediation would permit no harm or grudge to ever linger in their family.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Every inch of the Grand Bazaar has been measured by ___'s footprints, and she keeps everyone at Grand Bazaar in her heart.\\n___ can introduce anyone in the Grand Bazaar in detail, as if they were a family member.\\nMr. Jut usually gets up early to make tahchin, so if you want the privilege of having the most delicious bite of freshly cooked tahchin, be sure to get up early!\\nMr. Afshin's storytelling skills are simply divine. His wonderful ingenuity always makes people want to buy his merchandise.\\nMr. Hushang, who sells toys, has very dexterous hands. With them, he fashions the most fascinating little toys, and they are very popular amongst children.\\nAnd, of course, everyone has long regarded this smart red-haired girl as a family member too.\\nEvery time ___ goes grocery shopping, she always ends up carrying more items than on her purchase list just by making a single trip through the streets, and the weight of the groceries shows exactly how much people like and take care of ___.\\nOf course, ___ also takes care of them in return.\\nHushang and Farhad may have a quarrel over a bet, about as long as ___ shows up, the two will surely be reconciled.\\nIf Afshin's Sumpter Beasts have stolen someone else's food, ___ will come forward and help make amends.\\nIf you ask ___ why she is so enthusiastic, she will answer with a smile:\\n\"Because family is supposed to help each other, hehe.\"\\nFor ___, her mom and dad are her small family, while everyone in the Grand Bazaar is her big family.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: '___ remembers clearly that she met her teacher at the Sabzeruz Festival when she was eight years old.\\nBack then, the Knight of Flowers gave her a lot of Yalda Candies, and so little ___ passed by the Zubayr Theater with candies in both hands.\\nThe Sabzeruz Festival is a celebration that features dance, but before, only dance groups from abroad were invited to sing and dance at the festival — and on a temporary stage, to boot.\\nNow that the Grand Bazaar finally had its own theater, excited people were flocking to the new stage.\\nLittle ___ managed to squeeze through the crowd to the front of the stage and saw the teacher dance for the first time.\\nEven though there were no flowers on the stage, at that moment, ___ felt as if she was watching thousands upon thousands of flowers blooming all at once.\\nThe candies in her hands fell to the ground unnoticed, and she couldn\'t help but dance along.\\nIt was only when the dance had ended that little ___ realized what she had done, and hurriedly apologized to the people around her who had made room.\\nIt was at this moment that her teacher also walked down from the stage in an elegant manner and helped her pick the Yalda Candies back up.\\nShe reached out her hand to little ___, and asked gracefully—\\n"Would you like to join me for a future dance?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Although she has lived her entire life in Sumeru, the city of wisdom, ___ has never shown any talent in the field of "knowledge." However, she always knows how to soothe the emotions of others in her own way.\\n"This is probably a generous gift to me from Lesser Lord Kusanali."\\nAfter learning to dance with her teacher, ___ became deeply aware of the power of body language.\\nCombining her talents and knowledge of body language, she created her very own form of "body movement therapy."\\nFor example, when Mr. Zubayr is angry, everyone in the theater would be walking on eggshells.\\nBut ___ would keep a warm smile, drawing wonderful patterns one after another in the air with her arms and fingers.\\n"Imagine that we are in the rainforest that has just rained, and that you are following me as we walk onward, saying hello to every animal that passes by, waving, leaving everything else behind..."\\nPerhaps this may seem childish and funny to a bystander, but for those who are wrapped up in the moment, ___\'s gentle voice can cause the anger that clouds their minds to disappear before they even know it.\\nWhat\'s even more amazing is that, according to Mr. Afshin, this body movement therapy has been trending recently — and it even works on his two stubborn Sumpter Beasts...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Be it in day-to-day life or her performances on stage, ___ has always maintained a simple attitude —\\nTo melt everyone\'s worries away and let comfort and ease waltz in.\\nBut when "trouble" comes to her, she is often distressed due to her inability to make the call.\\nTahchin sure is delicious, but Pita Pocket is also good, and I also saw someone holding a Potato Boat that seemed really yummy. Which one should I eat tonight?\\nI\'ve heard people talk about places outside Sumeru City... the pure white snowy mountain and windmills the size of giants... Should I also consider going out for a trip?\\n___ can often find good reasons to go with any of the options she is considering, and so they are like Forest Tree Frogs sitting across from one another with bellies out, not one able to win the others over.\\nBut if there was a person who could make a decision at this time and tell her with confidence and calm:\\n"Why not have half the amount of each and share them with me?"\\n"And as for those places you have never been to, I have already set foot there. I can assure you that they are safe."\\n...___ would dismiss her hesitation in an instant and raise her arms in a dance-like graceful gesture of thanks, before indulging in the joy of having solved a great problem for a long time indeed.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Letters from the Audience',
      title2: null,
      text: 'Refusing to accept gifts on stage has been a long-standing rule in the Zubayr Theater.\\nSometimes, the audiences do still get too excited and may insist on giving various kinds of gifts to ___. That said, such givers will definitely receive a gift in return the very next day, along with a note that has been left at their doors...\\n"Thank you for your kindness. If you would like to express your love for ___\'s dance, you may write a letter to the Zubayr Theater instead of sending gifts."\\nAnd so it came to pass that like snow flakes dancing and falling in the air, letters filled with the audience members\' passionate praise have been sent in batches and droves by the Dusk Birds to the theater\'s mailbox.\\nDuring her free time when there are no shows or rehearsals, ___ will read every letter carefully, share this joy with the other members of the Zubayr Theater, and then carefully preserve these letters.\\nEvery word and every expression of recognition and fondness in the letters is worth remembering and appreciating.\\nAs ___ bettered her dancing skills, more and more people came to watch her dance, and in time, the letters have added up to quite the stack indeed.\\nBut if someone cracks a joke, saying that ___ is the most valuable treasure in the Zubayr Theater, she will definitely shake her head with a sweet smile.\\n"Our most valuable treasure is our audience\'s love, and it is all carefully stored in one mysterious box."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '___ has heard her teacher talk about the meaning of dance more than once. From her teacher\'s perspective, dance is born from human life and has belonged to everyone from the very beginning.\\n"As a dancer, you should convey emotions on stage, and your audience\'s smiles are their response to the emotions conveyed in your dance."\\n___ was well aware that she was nowhere near as good at thinking about the "meaning" behind things as Akademiya researchers. But still, she practiced diligently each day under the direction of her teacher and planned to continue following in her footsteps.\\nWhen she finally first took the stage, she quickly became completely immersed in the performance, holding nothing back.\\nShe thought of the wind, the moon, the gentle sound of the rose blooming, the feeling of stroking the tail feathers of Dusk Birds, and a myriad of beautiful things that existed in this world.\\nShe wanted to display the beauty she perceived in her heart to the entire audience through her dance.\\nSlowly, splashes of water ran together, converging into a lake on the stage. Like a Crystalfly dancing on a lake\'s surface, ___ gently fluttered back and forth, and the lake-mirror rippled slightly in time to her steps.\\nLike a water lily, her body swirled in the middle of that lake. Amazed at such pure and flawless beauty, the audience almost forgot to breathe.\\nAfter the curtain fell, ___ flopped down on the backstage chair and took deep breaths.\\nLike dewdrops on a lotus leaf, a Hydro Vision had appeared at her waist.\\n___ thought then that she had perhaps found the purpose of dance at last — \\n"To become beauty, and then to convey the beauty and value of art."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
