export const tartagliaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Tartaglia_Hello',
      text: "I'm No. 11 of the Fatui Harbingers, codename ___, but I also go by ___. And you... Hmm, you too like to cause quite the stir, don't you? Something tells me we're going to get along splendidly.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Idleness',
      audio: '1101',
      text: 'You know, there are better ways to seek out our enemies than... well, standing here.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Test of Skills',
      audio: '1102',
      text: "This place is pretty dead... By which I mean, there's nothing to kill.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: The Fatui',
      audio: '1103',
      text: 'I wonder what the rest of the Harbingers are up to? Plotting and scheming on an ever-grander scale, no doubt.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'Chat: Snezhnaya',
      audio: '1104',
      text: "Where I'm from, if we didn't keep moving, we'd freeze to death. Literally.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: 'VO_Tartaglia_After_the_Rain',
      text: "Ah, perfect weather for fishing! The sound of the rain scares them away, but once it stops, they're yours for the taking.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows: Foreign Country',
      audio: '1202',
      text: 'Haha, ahh... could it be snowing in Snezhnaya too?',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Snows: Snezhnaya',
      audio: '1203',
      text: 'The world looks glorious in the snow. Pure white, like the light of the moon. A perfect backdrop for bloodshed.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: "When It's Windy",
      audio: '1204',
      text: 'The wind is picking up. There is conflict in the air.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'When the Wind Is Blowing: Foreign Country',
      audio: '1205',
      text: 'Just look at that wind blow!',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'When the Wind Is Blowing: Snezhnaya',
      audio: '1206',
      text: 'The wind permeates all, cleansing both mind and body. Excellent.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Morning',
      audio: 'VO_Tartaglia_Good_Morning',
      text: "Morning, comrade! You're raring to go today, I see.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Afternoon',
      audio: 'VO_Tartaglia_Good_Afternoon',
      text: "You look well. What's your secret? Care to exchange notes?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Evening',
      audio: 'VO_Tartaglia_Good_Evening',
      text: 'Whew, dinner was quite the feast. A spot of exercise is in order.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'Good Night',
      audio: 'VO_Tartaglia_Good_Night',
      text: 'Today was great. See you tomorrow, comrade!',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About ___',
      audio: 'VO_Tartaglia_About_Tartaglia',
      text: 'A warrior must always be ready to face any challenge with his blade. The outcome of the battle is irrelevant — what matters is that you learn from the experience.',
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Comrades',
      audio: '2002',
      text: "Ah, I'm sure the Harbingers must know of my dealings with you by now. Oh, I'd love to see the look on their faces... Hahaha...",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'About Us: Weapons',
      audio: '2003',
      text: 'I am the least adept with a bow. And that is precisely why I must master it.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About Us: Survival',
      audio: '2004',
      text: "You wield such powers without owning a Vision... I really am excited to see what you have in store for us... Let's see how far you can go. Just don't go dying on me before you lay it all on the line in our final battle! I won't allow it!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '19': {
      title: 'About Us: Invitation',
      audio: '2005',
      text: "Comrade, how would you like to join the Fatui? ...Actually, scrap that. With your capabilities, you and I could go head-to-head with the Harbingers and win. Wouldn't want to miss an opportunity like that.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '20': {
      title: 'About the Vision',
      audio: 'VO_Tartaglia_About_the_Vision',
      text: "If it makes me stronger, I'll take it. Vision? Great. Delusion? Don't mind if I do. Heretical teachings from the Abyss? Sign me up.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'Something to Share',
      audio: 'VO_Tartaglia_Something_to_Share',
      text: 'The skeletal-white snowscape devours life without leaving any trace. It is the invisible enemy we fight against each day.',
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'Interesting Things',
      audio: 'VO_Tartaglia_Interesting_Things',
      text: "I once ventured deep into the abyss and came face-to-face with an enormous beast. I don't know its name, all I know is the sight of it chilled me to the bone. But mark my words, one day I will march back in there and behead that beast, and you, comrade, will be my witness!",
      tips: '',
      tasks: null,
    },
    '23': {
      title: 'About Skirk',
      audio: 'VO_Tartaglia_About_Skirk',
      text: "It's been years since I last saw my master. I should hope that next we meet, I'll at least be able to force her to use both hands to beat me...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Zhongli: Pondering',
      audio: '4003',
      text: "There's far more to that man than meets the eye. As for the extent of his power... lots to look forward to, I think.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Zhongli: Challenge',
      audio: '4004',
      text: "Tell me, how has Mr. Zhongli been lately? Not bad, you say? Seems he's had no problem acclimating to \"mortal\" life. Hmph, he sure had me fooled. Such a fiasco mustn't be so easily forgiven! The only way to reconciliation is fierce combat! What do you mean I'm no match for him? Hahaha...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About the Tsaritsa',
      audio: '4005',
      text: "Her Royal Highness the Tsaritsa is actually a gentle soul. Too gentle, in fact, and that's why she had to harden herself. Likewise, she declared war against the whole world only because she dreams of peace. And because she made an enemy of the world, I had the chance to become acquainted with you.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Varka',
      audio: 'VO_Tartaglia_About_Varka',
      text: "Varka? Just the thought of one day going head-to-head with him in combat, the fabled Knight of Boreas himself, titan of the Knights of Favonius... It makes me buzz with excitement. It's a beautiful life we live in this world.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About The Jester',
      audio: 'VO_Tartaglia_About_The_Jester',
      text: "He was the first ever Fatui Harbinger, and today he is our leader. He only appears on important occasions. As for his accomplishments... To be honest, I don't really care. I owe my loyalty and devotion to the Tsaritsa, no one else.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About The Captain',
      audio: 'VO_Tartaglia_About_The_Captain',
      text: "I've seen him in battle before, and oh what a sight it was. Perhaps I'm ranked too low for him to notice me right now. Well, he may not recognize my strengths yet, but one day, I'll show him what I'm made of.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About The Doctor',
      audio: 'VO_Tartaglia_About_The_Doctor',
      text: "I heard that he took segments of himself at different ages, made prostheses out of them, and assigned different tasks to each one. I know... all my comrades are a little weird. Well, come to think of it, if I met another version of myself... Hah, we'd have to fight then and there to decide which one of us gets to survive.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Damselette',
      audio: 'VO_Tartaglia_About_Damselette',
      text: "The Fatui Harbingers are ranked by strength, and I have no idea why that girl is No. 3. I'd test my skills with every Harbinger who ranks above me if I had the chance, but when it comes to her... something just doesn't feel right. Anyway, you should be careful around her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About The Knave',
      audio: 'VO_Tartaglia_About_The_Knave',
      text: "Look, I've got nothing against people who have their own agendas — I myself joined the Fatui to get more experience in combat. But I don't like her at all. If she stood to benefit from betraying others, she'd turn against the Tsaritsa in a heartbeat. There isn't a sane bone in her body.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'About The Rooster',
      audio: 'VO_Tartaglia_About_The_Rooster',
      text: "I don't know what his motivations could be, but he seems genuine about wanting to help me. He treats me just like family. Oh, and speaking of family — Tonia and Teucer are always telling me about the pastries and other gifts he brings them when they write. So while I've been away from Snezhnaya, he's kept his promise to take care of my family.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'About Marionette',
      audio: 'VO_Tartaglia_About_Marionette',
      text: "She always seems engrossed in her research. Hmm... I wonder if those machines have anything to do with her? Anyway, I've only met her a few times, but every time she looked like she wanted to murder me. I have no idea what I possibly could have done to annoy her, though.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '35': {
      title: 'About Regrator',
      audio: 'VO_Tartaglia_About_Regrator',
      text: "Oh, now that guy has a head full of grandiose plans fueled by raw ambition. I don't understand a word he says once he starts talking about his theories... Eh, but as long as he keeps our cash reserves stocked up, I'm not complaining.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '36': {
      title: 'About The Fair Lady',
      audio: 'VO_Tartaglia_About_The_Fair_Lady',
      text: "I never got along with her, you know that. I guess there's not much more worth saying about her at this point. When you're a harbinger, you have to accept that death could come at any time... But don't worry about me. No matter what happens, I'll do whatever it takes to keep myself alive.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '37': {
      title: 'About The Balladeer',
      audio: 'VO_Tartaglia_About_The_Balladeer',
      text: "After he took the Gnosis, we lost all contact with him. Now comes the task of trying to hunt it down and get it back... I actually don't mind it — it means I get to travel all over. Wonder if I'll run into you somewhere along the way?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '38': {
      title: 'More About ___: I',
      audio: '5001',
      text: 'Remember, comrade, one day I will conquer the world!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Face me in person, man to man, and I'll always have a chance of beating you. Same goes if you're a deity or a monster from the abyss. But the Harbingers? They are more enamored with their intangible methods, spending their days scheming and maneuvering. This is why we cannot get along.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '40': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'However far away my motherland may be, we all live under the same sky. That snow-white moon... My family must be able to see it too. I hope my siblings... *sigh* I hope that they have turned out to be formidable warriors as well.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '41': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Comrade, a word of advice: Don't go yelling stupid things in the heat of battle. They might sound good in your head, but if you think about it, they make no sense at all. I'm talking about things like, \"I'm on fire!\" That's the last thing we want. Fire leaves behind nothing but ashes. And you must survive at all costs.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '42': {
      title: 'More About ___: V',
      audio: '5005',
      text: 'Ah, how time flies. One day, you will see how I conquer the world and crush the thrones of gods beneath my heel. In the meantime... no dying, comrade! Keep yourself alive! Hahaha.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '43': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'Ice fishing and combat follow the same principle. Patience and decisiveness are key. Though having said that... I suppose the same is true of everything in life.',
      tips: '',
      tasks: null,
    },
    '44': {
      title: "___'s Troubles",
      audio: '6002',
      text: "My pet peeves? Hmm, well, to be honest, I'm far too busy journeying with you and slaying powerful enemies to dwell on such trifling matters.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Favorite Food',
      audio: 'VO_Tartaglia_Favorite_Food',
      text: "There's plenty of delicious food to sink your teeth into in this world... and plenty of fights to sink your teeth into as well. Life is beautiful.",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Least Favorite Food',
      audio: 'VO_Tartaglia_Least_Favorite_Food',
      text: 'Food is like weaponry. A true warrior never deliberates unduly over their choice of weapon, nor do they do so over the food they eat. Neither should you.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Eating delicious food really has a way of taking all your cares away. Now, how should I repay you?',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Your cooking skills seem to have improved quite a lot. Does that mean you're getting stronger all the time, too?",
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Um, I'll admit the taste surprises me a little. Hmm? Okay... I'll try one more bite.",
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Birthday',
      audio: 'VO_Tartaglia_Birthday',
      text: "Happy birthday, comrade! Anyone you need knocked off their perch today? Let me know. I'll happily oblige...",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Hohoho, I feel like I've gotten stronger! Now, who shall I use as my guinea pig...",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '52': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: '"A warrior\'s strength is like a dome. The bigger the dome, the more opponents he can challenge inside it." Hmm, who was it that said this again?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '53': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Bravo, comrade! Thanks to your help, I am one step closer to my goal of conquering the world. I doubt even the Tsaritsa herself ever expected I would make it this far.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '54': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'Comrade. Make sure you keep training too. Otherwise, who will be left to fight me to the death when the world lies defeated at my feet? Hahaha.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '55': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "You're mine!",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Ha!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Tidal wave!',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Bring it on!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: "Who's next?",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Hah...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Riptide!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "You can run, but you can't hide!",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "Shouldn't let your guard down!",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Elemental Burst: IV',
      audio: '200004',
      text: 'Brace yourself, this is gonna hurt!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'No time to lose.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Deploying Wind Glider: I',
      audio: '800001',
      text: 'I could get used to this.',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Alright, now we're talkin'!",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Not bad... Not bad at all!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Now I just need to get my hands on the rest!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Heh, this is getting interesting.',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Low HP: II',
      audio: '410002',
      text: "You're pretty good!",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Death looms. My time to shine!',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "What's the matter, out of practice?",
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Step aside, it's my turn!",
      tips: '',
      tasks: null,
    },
    '75': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'How... I had only just...',
      tips: '',
      tasks: null,
    },
    '76': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Drat!',
      tips: '',
      tasks: null,
    },
    '77': {
      title: 'Fallen: III',
      audio: '500003',
      text: "I'm... quite impressed...",
      tips: '',
      tasks: null,
    },
    '78': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Amateur mistake.',
      tips: '',
      tasks: null,
    },
    '79': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Need to end a few enemies?',
      tips: '',
      tasks: null,
    },
    '80': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Keep your eyes wide open!',
      tips: '',
      tasks: null,
    },
    '81': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "C'mon, don't keep me waiting!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Despite holding one of the most senior positions in the Fatui as one of the Eleven Harbingers, ___ very much looks like the young adult that he still is.\\nHe is a wolf in sheep's clothing, however, for under the cheerful and confident appearance lies a deadly swordsman.\\nHe is the youngest among the Harbingers, but one of the most dangerous among their number.\\nThat said, ___ doesn't seem to fit in well with the others.\\nAs a fighter first and foremost, he is quite at odds with this organization of deceit and treachery.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "As the youngest Harbinger in the history of the Fatui, ___ is hardly bound by convention, and plays by his own rules accordingly.\\nThough this lone wolf is not so well-received by his peers and is also at odds with their methods, his cavalier demeanor hides a responsible, watertight meticulousness.\\nHe is a proud man of his word. Even if the promise he makes is absurd, he will never break it.\\nBe it exterminating all the dragons inside their lairs, venturing into a domain of extreme danger, or single-handedly overthrowing the territory of a nobleman...\\nHe not only keeps his promises, but does so with finesse and surgical precision. As the Harbingers' vanguard, ___ always appears in the vulnerable underbellies of Snezhnaya's enemy states, striking as a conflict is about to erupt.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Many myths in Snezhnaya say that ___ has been on the battlefield since he was 14 years old.\\nOddly enough, at that young age he already seemed to be a skilled slaughterer with mastery of many forms of martial arts.\\nBut more terrifying than his skill in combat was his passion for it.\\nPerilous battles would only excite him, and terrifying foes would exhilarate him all the more.\\n___'s arrogance and conceit are derived from honing himself across countless battles, and from unmatched combat experience.\\nOn the other hand, because they fret about the way his quarrelsome personality tends to invite unwanted trouble, the other Harbingers constantly try to get him sent on missions to places as far from Snezhnaya as possible, so that they can avoid the fallout.\\nThe man is incomprehensibly ever in the eye of the storm, and these unusual experiences have also made him quite the show-off who revels in the praise of others.\\nUnlike other members of the Harbingers, who prefer to keep a low profile, ___ will often go to watch public performances — occasionally even becoming part of the show himself.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Ice fishing has been one of ___\'s hobbies since childhood.\\nIn those days, he was known neither by the names ___ nor "___," as the Fatui call him, but as Ajax, named by his father after some hero\'s tale. He and his father would cut holes open upon frozen lakes before sitting beside them and tending to their fishing lines.\\nThis was no easy task, and would sometimes take the entire morning.\\nBut whether it was chiseling away at the thick ice or the long waits in between catches, he was always accompanied by his father\'s unending tales of adventure.\\nThese were stories of his father\'s adventures from when he was young, and they became the future that ___ secretly envisioned for himself.\\nSo he would pay close attention, putting himself into the shoes of the protagonist of those tales, immersing himself fully in them even as they waited for a fish to bite.\\nEven after leaving home, Ajax, later to be known as "___" ___, would keep up that hobby of his.\\nNo longer accompanied by the stories of bygone days, fishing instead became an opportunity to train — to hone his endurance, and reflect on combat techniques.\\nSuch long periods of meditation to refine his skills swiftly relegated the question of a successful catch to irrelevance.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Unlike what the rest of the world may think, ___ was not born with his exceptional skills in battle.\\nBut he would never speak to anyone about that critical, fateful encounter of his...\\nWhen he was 14, he fled his monotonous life at home with nothing but a shortsword and a bag of bread in hand.\\nThat 14-year-old boy got lost in the snowy forest.\\nPursued by bears and wolf packs, he lost his footing and fell into a bottomless crack in the earth's surface.\\nThere, he witnessed the endless possibilities of another ancient world. There, he would meet a mysterious swordswoman...\\nOr perhaps one should say that this dark realm had sensed the burning ambition in this boy's heart.\\nThis darkness was something that the Harbinger ___ could never again delve into.\\nIn those three months, the swordswoman taught ___ how to pass through the Abyss unhindered, and more importantly, nurtured the ability to stir up endless havoc from within Ajax's trouble-mongering nature.\\nNo one knew what happened within that darkness during those three months, nor would Ajax ever speak of this to anyone.\\nWhen his worried mother and sisters finally found him in that forest, only 3 days had passed in this world.\\nThus did Ajax's first adventure end, with his now-rusty shortsword in hand.\\nThis would mark the end of his youth and the beginning of his days as a warrior.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'By the time he returned home, the young man was no longer the same.\\nHe was no longer frightened and hesitant but had become frivolous and confident. He acted as if this world revolved around him, and as if battle existed for his sake.\\nConflict often brings about change, and this capricious, incalculable change attracted Ajax like a revolving kaleidoscope.\\nIn the eyes of his father, that third son that he had so worried about had changed for the worse, bringing much uncalled-for havoc to the seaside village of Morepesok.\\nOr perhaps it would be more accurate to say that Ajax had become a nexus of strife, for no matter where he went, fights and squabbles would follow — and he reveled in it.\\nUltimately, after a huge brawl was pacified with some difficulty and with some near-fatal misses, his father had no choice but to hand his beloved son over for conscription into the Fatui.\\nHe hoped that the strict military training of the Fatui could hone his son\'s temper, but wound up watching fully-armed troops getting the stuffing beaten out of them by a mere child.\\nThis was a great disappointment to his father, but it also caught the attention of Pulcinella, the 5th Harbinger.\\nShocked by Ajax\'s great strength and curious about how he invariably became the eye of a vortex of discord, Pulcinella inducted Ajax into the Fatui under the pretext of meting out punishment, ordering him to start from the bottom and take up the duty of serving the Tsaritsa.\\nHis insatiable desire for conquest would thus be constantly satiated in fighting for the Fatui, and his ever-burgeoning ego would gorge upon the elation of vanquishing mighty foes...\\nUntil at last, Ajax was chosen to be one of the Fatui Harbingers, donning the mantle of "___" ___ and becoming one of the most powerful people in Snezhnaya.\\nBut becoming ___ was far from his end goal. To someone who sought to conquer the world, this was but a tiny step in his journey.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "___'s Letters to Home",
      title2: null,
      text: "\"Dearest Sister, are you all keeping well at home? Has the old man's headache gotten any better?\\nPlease send my regards to our parents and our siblings.\\nI've sent some wind chill medication over from Liyue Harbor. It's very effective, and will probably keep him from nagging for a while. It should reach you after a few days.\\nApart from our father's affairs, I naturally haven't forgotten about gifts for you all.\\nThis letter should come with two kites from Liyue, a rattle drum, two porcelain dolls from Inazuma, and a crate full of various snacks.\\nAnd please break it to Anthon that the residents of Liyue are just boring old ordinary humans, like us.\\nThey're not made of stone, and they don't even eat stones.\\nDo not fret for my sake, Tonia, and refrain from making trouble for anyone at home. I will be home soon. When I have seized the seven stars of Liyue and laid them at the feet of Her Majesty the Tsaritsa, I will take the first ship home, just as I promised — and you know how I always keep my promises.\\nYours faithfully, Your loyal knight.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Delusion',
      title2: null,
      text: '___\'s Delusion is his old badge of honor and the proof of his strength.\\nHe still remembers with perfect clarity the day when he received his Delusion and ascended to become a member of the Harbingers.\\nAs he stood before the cold, stern Tsaritsa, The Jester, the very first of the Fatui, personally pinned this insignia onto him.\\nIt was his reward for slaying many terrible beasts, and a memento of countless battles.\\nBut it was not this that brought ___ joy, for honor is the natural reward of the warrior.\\nNor did he pay any mind to the odd looks his new "colleagues" gave him, for the opinions and bellyaches of others meant nothing to him.\\nThe sight of the Tsaritsa on her lofty throne alone stirred the young man\'s heart with respect and admiration, not merely because she opened the way for him to find an abundance of looming battles, but also because of the way she looked upon him.\\nHer gaze was cold but pure, arrogant yet sharp.\\nShe was not only the sacrosanct Cryo Archon but also a true warrior.\\nThus did ___, having received his Delusion, swear an oath of fealty to the one and only Tsaritsa of Snezhnaya.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
