export const xingquiVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Xingqiu_Hello',
      text: "___ at your service, my liege! I humbly trust that even one such as I, a mere bookworm, may yet prove to be of some utility under your wise leadership. Nice, I don't often get a chance to speak with such formality. It felt pretty good!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Night of Solitude',
      audio: 'VO_Xingqiu_Chat_-_Night_of_Solitude',
      text: "'Twas on a deserted moonlit night that the hero approached the vile dragon's limpid lair...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Literature',
      audio: 'VO_Xingqiu_Chat_-_Literature',
      text: 'I never embark on a journey without a good book to accompany me.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Taking a Break',
      audio: 'VO_Xingqiu_Chat_-_Taking_a_Break',
      text: 'Now this is what I call, "a moment of solitude."',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'Chat: Reading',
      audio: 'VO_Xingqiu_Chat_-_Reading',
      text: 'Oh my goodness... Oh my gosh... Wow— Huh? "All will be revealed in the next volume"? Aw, drat...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'Chat: New Books',
      audio: 'VO_Xingqiu_Chat_-_New_Books',
      text: 'If my calculations are correct, Wanwen Bookhouse is due to receive a batch of new releases today. Might we add a small detour to our adventure?',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Rains',
      audio: 'VO_Xingqiu_When_It_Rains',
      text: 'My family makes ornate umbrellas that block neither rain nor shine. Their sole purpose is for decoration upon a wall.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'After the Rain',
      audio: 'VO_Xingqiu_After_the_Rain',
      text: 'Good, the rain has stopped. Any longer and my books would have gotten wet.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When It Snows',
      audio: 'VO_Xingqiu_When_It_Snows',
      text: 'Only when it snows like this would I prefer to be at home than in a book store. For there is a well-stocked fireplace at home, while there is no fire allowed in book stores.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'When the Sun Is Out',
      audio: 'VO_Xingqiu_When_the_Sun_Is_Out',
      text: "Great weather for practicing martial arts, but perfect weather for reading. Hey, what's that ridiculous look for? You look as if you're trying to decipher some strange text written on my forehead.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Morning',
      audio: 'VO_Xingqiu_Good_Morning',
      text: 'Morning! The morn hours are precious. Spend them on that which matters to you.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon',
      audio: 'VO_Xingqiu_Good_Afternoon',
      text: "I am uninclined to eat a heavy meal this luncheon, but instead indulge in some baked treats. As long as I eat in the study, my father and brother never have to know! Oh, you want to join me? Well... As long as you don't get crumbs on the books, I suppose it's fine.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: 'VO_Xingqiu_Good_Evening',
      text: "What say you we snatch a few fireflies and read in the light they give? Hehe... Hey, I'm joking. Seriously, don't, it's bad for your eyesight.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: 'VO_Xingqiu_Good_Night',
      text: "You will find me in the same place as ever tomorrow. So I'll see you then. Unless you manage to get lost on the way.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___',
      audio: 'VO_Xingqiu_About_Xingqiu',
      text: "I always have to put on an act around other people, because they see me only as the second son of the Feiyun Commerce Guild. It's a relief that I can just be myself around you. I think it's because you don't see me in the same way.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '15': {
      title: 'About Us: Reading Buddies',
      audio: 'VO_Xingqiu_About_Us_-_Reading_Buddies',
      text: "I would say we are book buddies. Huh? Combat? Guhua Clan? Comrades in arms? ...What on earth are you talking about? I told you that's our little secret!",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Swornship',
      audio: 'VO_Xingqiu_About_Us_-_Swornship',
      text: "We should become sworn siblings, let's go to the altar at Jueyun Karst. Nope, no ifs, no buts, you know too much about me! You know the real me, the one I normally have to hide. I simply can't let you go until you promise me you will go through with it!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision: Ancient Books',
      audio: 'VO_Xingqiu_About_the_Vision_-_Ancient_Books',
      text: "There aren't many records on matters concerning Visions, but I do have a passage dedicated to the topic in my collection of ancient texts. I can lend it to you if you want.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '18': {
      title: 'About the Vision: Realization',
      audio: 'VO_Xingqiu_About_the_Vision_-_Realization',
      text: "I've come to an epiphany based on some things I've been reading — ultimately, the arts of both the polearm and the sword are just the art of hand-eye coordination. Ugh, it's a little difficult to explain... If you want to know more, come with me to Wangshan Hall. But first, you have to promise me you won't laugh.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '19': {
      title: 'Something to Share',
      audio: 'VO_Xingqiu_Something_to_Share',
      text: "Must-see places in Liyue? That's a tough question. Hmm... The place I would miss the most if it disappeared would be the Wanwen Bookhouse, first and foremost. The Guhua Sect would be in the top ten, too.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: 'VO_Xingqiu_Interesting_Things',
      text: "I used to like rabbits, but I'm more a fan of stags now. To me, the saying \"May my final stand be a monument to chivalry\" is about abandoning worldly possessions and reaching enlightenment. But the stag's final resting place represents the hope for life anew. Oh, how I'd love to see it again.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Beidou',
      audio: 'VO_Xingqiu_About_Beidou',
      text: 'I have great respect for Lady Beidou. I just wish she wouldn\'t call me "kid" and ruffle my hair each time she sees me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Ningguang',
      audio: 'VO_Xingqiu_About_Ningguang',
      text: 'In her capacity as the Tianquan, I am obliged to respect her. Otherwise, it could create issues for my father and brother. On a personal level? Let me think... I think I will go with "no comment." I shan\'t speak ill of others.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Chongyun',
      audio: 'VO_Xingqiu_About_Chongyun',
      text: "Ah, dear Chongyun. Though he understands me quite well, one has to exercise caution when teaming up with him to go on a quest. He is making good progress in the martial arts, but I would say he hasn't quite internalized the chivalric code yet... He needs more practice. Especially at eating spicy food...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Yun Jin',
      audio: 'VO_Xingqiu_About_Yun_Jin',
      text: 'When Yun Jin drinks a beverage she is fond of, she will be inspired to write a new play. So, I keep a jar of tea leaves under my bed at all times, ready to deliver to her on the day that her inspiration dries up. This way, I shall never run out of heroic tales to listen to!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Hu Tao',
      audio: 'VO_Xingqiu_About_Hu_Tao',
      text: "Ah yes, the young lady who is now the Master of the Wangsheng Funeral Parlor. If you're asking what I think about her as a person... Well, there are all sorts of rumors about the way she works. But I think if you really want to understand someone, you need to find out what they are really after.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Qiqi',
      audio: 'VO_Xingqiu_About_Qiqi',
      text: "I've always thought there is more to Qiqi than meets the eye. But it's impossible to have a conversation with her when Baizhu's around. Hmm... We could wait till Baizhu makes a home call to one of his other patients and corner her...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Xiangling',
      audio: 'VO_Xingqiu_About_Xiangling',
      text: "When you first spot Xiangling out and about, the first thing you should do is check the look on her face. Especially when she's just coming back from collecting new ingredients — the more excited she looks, the more dangerous it is to approach. Because if she sees you, she'll force you to taste-test her latest concoction... I usually get Chongyun to handle these situations, hehe...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Xinyan',
      audio: 'VO_Xingqiu_About_Xinyan',
      text: 'Where does Xinyan perform? Anywhere from Chihu Rock to Yujing Terrace — no spot is untouched by her disruptive presence... A quiet day when I can curl up with a good book is a rare treasure indeed.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Albedo',
      audio: 'VO_Xingqiu_About_Albedo',
      text: "I've thought of all the illustrations I want for each major event in the next three volumes! I should write my thoughts down before I forget them, and send them to Mr. Kreideprinz...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '30': {
      title: 'About Zhongli',
      audio: 'VO_Xingqiu_About_Zhongli',
      text: 'My father and brother entertained that gentleman as a guest once. From the way they were acting, he must be a very high-profile figure indeed. I also heard that he directs funerals for the adepti, so he must surely have great depth to his character. We should do some digging and see what we can find out about him!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1016,
              questTitle: "Zhongli's Treat",
              chapterId: 1102,
              chapterTitle: 'Farewell, Archaic Lord',
            },
          ],
        },
      ],
    },
    '31': {
      title: 'About Shenhe',
      audio: 'VO_Xingqiu_About_Shenhe',
      text: "I find that Miss Shenhe seems to look at me somewhat fiercely, so I daren't approach her lightly. Bizarre, did I inadvertently upset her? Or maybe... upset someone close to her?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Yelan',
      audio: 'VO_Xingqiu_About_Yelan',
      text: 'Have you heard the expression "same person, different face"? Ms. Yelan gives me precisely this feeling. When she came to visit my family, my father and brother treated her with respect, and she was pleasant and polite in return. She seemed like a kind and mature young lady to me. But when I saw her elsewhere, she gave a completely different impression.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'About Gaming',
      audio: 'VO_Xingqiu_About_Gaming',
      text: "Gaming's work has all the trappings of a chivalric hero. Picture the scene — on a dark and moonless night, a lone young figure clad in black stands fearless on a secluded country road. They say his mastery of the martial arts is unparalleled, and the mythical beast by his side always does his bidding... Bandits and brigands beware, for none who challenge him come away unscathed... When he has the time, I'd love to hear more about his experiences as a guard. You should come along too.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About ___: I',
      audio: 'VO_Xingqiu_More_About_Xingqiu_-_01',
      text: 'Are you keeping well, my liege? If you have no other matters to attend to, might I recommend a trip to the Wanwen Bookhouse?',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'More About ___: II',
      audio: 'VO_Xingqiu_More_About_Xingqiu_-_02',
      text: "You ask why I enjoy reading in solitude? ...Studiousness can hardly be considered a bad habit. There's not much more to it than that. Really.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '36': {
      title: 'More About ___: III',
      audio: 'VO_Xingqiu_More_About_Xingqiu_-_03',
      text: 'Your schedule is free today? Wonderful. I am ready to leave whenever you are. ...My book? Oh, never mind that! I can always pick up where I left off when I get back. But those in distress who need our assistance cannot afford to wait.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '37': {
      title: 'More About ___: IV',
      audio: 'VO_Xingqiu_More_About_Xingqiu_-_04',
      text: "You feel inspired, you say? You want to write a martial arts detective novel based on our adventures together? And you want to call it the \"Chronicles of Wanwen\"? Hahaha... It's a good idea, it really is. But I'll have to decline, I'm sorry. Yes, really...",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '38': {
      title: 'More About ___: V',
      audio: 'VO_Xingqiu_More_About_Xingqiu_-_05',
      text: "\"A weaver of verses who draws from an ocean of expression...\" That's the reputation I aspire to. But you're the only person I can share that with. I am actually writing a novel... but I can't let you see it. Not yet. The time will come, though... You'll be able to read it when it's on sale in book stores all over Liyue.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '39': {
      title: "___'s Hobbies",
      audio: 'VO_Xingqiu_Hobbies',
      text: "Evidently, my hobby is reading. I'll read anything and everything. ...What's that mischievous grin for? Oh. That's between the two of us, okay? It's not appropriate to discuss it out loud. There's no point in bringing it up anyway.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: "___'s Troubles",
      audio: 'VO_Xingqiu_Troubles',
      text: "What annoys me? Hmm... Well, one day my brother will inherit the family business. What will happen to me then? I fear my current carefree existence would... Oh — no no no, it's not about my status or anything like that. I don't care for that kind of thing. I just think my brother is something of a simpleton and I would probably end up having to do most of his job for him...",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Favorite Food',
      audio: 'VO_Xingqiu_Favorite_Food',
      text: "I like baked goods and Yue-style seafood. Probably because I'm used to quite a bland diet at home.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Least Favorite Food',
      audio: 'VO_Xingqiu_Least_Favorite_Food',
      text: "I hate carrots. When I was young, my mother would mash them up into... Ugh, I can't go on. Just thinking about it makes me feel sick...",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Xingqiu_Receiving_a_Gift_-_01',
      text: 'I need only sample this delight but once for its aroma to remain forever in my memory.',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Xingqiu_Receiving_a_Gift_-_02',
      text: "With cooking skills as good as yours, it'd be a waste not to open a restaurant, wouldn't you agree?",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Xingqiu_Receiving_a_Gift_-_03',
      text: "I couldn't possibly. But please, you eat your fill. I insist.",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Birthday: Wishing',
      audio: 'VO_Xingqiu_Birthday_-_Wishing',
      text: 'May this day of your birth be filled with much mirth!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Birthday: Customs',
      audio: 'VO_Xingqiu_Birthday_-_Customs',
      text: "According to historical records, Tiancheng's stone bridge was formed by a fallen rock spear thrown by the Geo Archon Morax in battle. If you walk along the bridge on your birthday and throw some Mora into the sea from both sides, you will be blessed in the coming year... Your birthday only comes once a year, so be quick about it if you wanna go... I'm not kidding, it's true! Go try it and you'll see!",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Xingqiu_Feelings_About_Ascension_-_01',
      text: 'Were it not for my capability, the cause that so inspires me would remain confined to the pages that extol its virtues.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Xingqiu_Feelings_About_Ascension_-_02',
      text: 'Had I no moral compass, my efforts would have been misguided. Doomed to grasp at shadows while missing the substance, I would have become a philistine that seeks only violence.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '50': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Xingqiu_Feelings_About_Ascension_-_03',
      text: 'There is a cause that I seek to champion, yet few in Liyue share my aspiration. This I have known for a long time, for it is a path I have walked for many years.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '51': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Xingqiu_Feelings_About_Ascension_-_05',
      text: "I am most grateful for your company on my journey. I am proud of my achievements, both in the martial arts and in championing the cause so dear to my heart. ...Ah, I guess there's no need to euphemize any longer. Chivalry! That is the cause that inspires me, and that I seek to champion. Why should I shy away from it? I am sure my father and brother are under no illusion as to what I stand for by now. ...But of course, I still need to be somewhat discreet in the way I go about my business.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Every merchant in Liyue Harbor knows of ___ from the Feiyun Commerce Guild.\\nAll see him as a kind and well-mannered young man who is an excellent student, a top talent in every sense.\\nAs the second-born son of the family, ___ is not required to shoulder the burden of managing the Guild's affairs. However, ___ possesses a unique scholarly talent among his peers — that is, the offspring of Liyue's wealthiest merchants — and was often praised by his tutors as a young student.\\n___'s elder brother, while learning the family business from their father, firmly believed that ___ would become a great asset to the business one day.\\nHowever, little did he know that ___, after finishing the dauntingly thick volumes on commerce and philosophy, would hollow them out and sneak martial art novels into them, which he read incessantly thereafter.\\nSometimes, ___ suddenly disappears for hours at a time with no explanation. When asked why, he simply replies: \"A moment of solitude.\"",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'To ___, "a moment of solitude" can mean all sorts of things.\\nExamples include visiting Wanwen Bookhouse to peruse the latest novels and going to Heyu Tea House to sample Yun Jin\'s latest drink.\\nSometimes, it means that he is off to fight for justice in the name of chivalry.\\nDefeating bandits on the road, driving away monsters, helping distressed children by fetching their kites from the tree tops... there are all manner of responsibilities that fall into the category of chivalry.\\nInspired by tropes from his beloved martial arts novels — such as the king who wears a disguise and mingles with the common folk — ___ does not hesitate to leverage the power of the Feiyun Commerce Guild to resolve more complex issues when violence isn\'t the answer.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "One day, ___'s older brother came looking for him, only to find he wasn't around. When ___ later returned, he came across his brother in the hallway.\\n\"Your room was a mess, so I cleaned it up. Listen, both you and I are responsible for the reputation of Feiyun Commerce Guild. We have to act the part. If you can't clean up a room, how will you clean up the world? An adeptus once said...\"\\nAfter half an hour of lecturing, ___ was finally let go, but his brother said something strange at the end:\\n\"I'll not enter your room without permission next time... I'll make sure the maids do the same.\"\\n___ had no idea what he was talking about. However, as his brother turned away, with a despondent look upon his face, he muttered to himself:\\n\"Those books under his bed... No. No, I shouldn't go looking at what kind of books they are... ___ is growing up after all... Don't want to be lecturing him all the time... Puberty perhaps?\"\\nAfterwards, even ___ found it odd. Expecting that one of the maids would have something to say about the stash of martial arts novels under his bed, he had long since prepared his response, but in the end, no one ever bothered to check his room again.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "To keep ___ from spending his whole day at Wanwen Bookhouse in Feiyun Slope, his father agreed to let him learn martial arts from the Guhua Clan. Much to his dismay, ___ quickly discovered that Guhua was a dying art that had been in constant decline for years. There was no proper tuition and it turned out the luxury dojo he had signed up in didn't even belong to the clan — they had just rented it temporarily to keep up appearances.\\n___'s father was, of course, fully aware of this state of affairs in advance. To him, the whole thing was just for fun. He thought ___ would be content to learn a spot of bladework for show, not for serious self-defense.\\nHe hadn't counted on the prodigiously intelligent and extremely well-read ___ being as outstanding a talent in Guhua as he was in every other discipline he had turned his hand to. A combination of his own intuition and extensive knowledge of ancient literature meant he was able to completely revitalize the dead art.\\n___ was disappointed by Guhua's martial arts program at the beginning, but he found the other tricks they taught to be exactly what he had hoped for.\\nQuicklime, smoking sand, paper fish, sword-swallowing, fire-breathing... ___ was spoilt for choice.\\nHe decided on the spot that he would learn them all, no matter how long it would take him. He reasoned that they would be useful to have in his repertoire during his future exploits as a chivalrous hero.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'There are two sides to the swashbuckling ___\'s personality. While quiet and unassuming in front of strangers, he is gregarious and chatty in the company of close friends and family. Though more restrained than his elder brother, he even has a playful and mischievous side.\\nThe one who usually bears the brunt of his bizarre sense of humor is someone named Chongyun, an exorcist usually found on one of the forest trails around Liyue.\\n"Chongyun... I found a haunted house for you to practice in..."\\n"Chongyun, you have to believe me... It wasn\'t me who laid the traps inside that haunted house— What? It\'s not haunted? Well... I, uh, couldn\'t have known that, could I?"\\n"Chongyun... Don\'t glare at me like that... Look, you\'re injured. You\'d better just lie there and get some rest."\\n"Tell you what, Chongyun, we have a maid who learned the art of essential oil therapy in a nobleman\'s house in Sumeru... How about I ask her to tend to your wounds? You owe me for this, though..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "The notion of chivalry means different things to different people.\\nChivalry means listening to your conscience calling you to action when you see an injustice, right? Or is chivalry simply about knowing right from wrong? No, that's not enough — it must have something to do with being a righteous person...\\nTo ___, chivalry simply means: be good, and do good.\\nAs a son of a wealthy merchant in Liyue Harbor, he was born to ride the waves in the world of trade. Notions of chivalry should have gradually left him as he grew up.\\nHowever, obtaining a Vision changed everything — it meant he was finally able to accomplish those legendary deeds he could only dream of as a child.\\nOf course, there is no way he can completely divest himself of his duties in the Guild, but so long as he gets to go out and be the hero even occasionally, he is perfectly content with his life.\\nThe only thing that can wipe the smile from ___'s face is when cynics question the true motives of chivalrous heroes.\\nRank, reputation, reward, shadowy deals... Whenever ___ hears people smearing the names of true heroes, the expression on his face may not change, but he will be sure to add that person to the special section of his blacklist reserved for people he despises even more than carrots.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: '"A Legend of Sword"',
      title2: null,
      text: '___ once wrote a martial arts novel named "A Legend of Sword" based on his own experiences, intending to publish it in Liyue Harbor.\\nTo his surprise, his manuscript was rejected by local publishing houses, who believed that no one would have any interest in a story with "a setting as wildly unrealistic as the plot is banal."\\nUndeterred, ___ had a few copies printed privately, and sneakily placed them on the shelves of Wanwen Bookhouse during one of his many trips there. But just as the publishers had suspected, it failed to garner much interest from readers. This was quite a blow to ___\'s confidence.\\nUnbeknownst to him, however, a passing merchant from Inazuma did purchase a copy to bring home, where it received rave reviews. Writers the region over attempted to copy the success of "A Legend of Sword," but none succeeded — it maintains permanent residency in the number one bestseller spot to this day.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'The martial arts school known as the Guhua Clan has been in decline for several hundred years now. In its heyday, the name of the Clan rang like steel throughout the harbor. It was said that the Clan harbored three great secret arts — the ways of the "Light Piercer" for polearms, "Rain Cutter" for swords, and "Life Ender" for those who excelled in both. The three arts would be refined over the generations, and with time would reach their apex. Yet the Clan\'s strength would continue to wane, leading to them losing their influence... The three arts became diamonds hidden in the rough, quietly awaiting a successor.\\nAfter many years, the Guhua Clan would finally get one in ___. It was he who successfully grasped the ancient "Martial Principle" after merely four years of study.\\nThe Guhua weapon arts stress using the weapon as an extension of your body, and indeed this is a common idea amongst the various schools of martial arts in Liyue. But the way ___ saw it, the basis of the polearm and sword was the use of a Vision. Martial artists were meant to see a Vision as an extension of themselves, and see their weapon as an extension of the Vision. Hence, he says: the arts of both the polearm and the sword are just the art of the "eye." \\nHaving come to this epiphany, ___ took up a quill and penned a verse on the Martial Principle. Reading it, the Guhua head was shaken with tears, declaring that "it is not ___ who needs the Guhua Clan, but the Guhua Clan that needs ___." Since then, this verse has been sealed up at the Clan headquarters at Wangshan Hall. Disciples are proscribed from reading it, much less outsiders.\\nThe verse reads thus:\\nGuhua\'s arts I have studied long, in its secrets I am trained, now its long-lost depths fall upon me like the coming of blessed rain.\\nThe beating heart of Guhua\'s sword art is as a shower of floating flowers. One amidst may seize a bloom, but those without read only doom.\\nThe Guhua lance is a lantern\'s dance, like flames in night\'s deep glooming. Like sparks, they scatter with ease in the dark, then join like the daybreak looming.\\nThey say the sword is as your arm — I say its glint is the beholder\'s eye, a light like the bright dawn coming.\\nThose who wander are burdened not. Freely they cut rain, and enlightened they pierce light. Like a snaking dragon, they cannot be subdued. In their right eye the blade, and in the other the spear.\\nThis text should have been free for all to read. The only reason why it was sealed is the dreadful handwriting.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
