export const alhaithamVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "I'm Alhaitham, the Akademiya's scribe. If you wish to access an archived file, please submit an application according to the prescribed format.\\nOh, your form isn't ready? Not to worry. You can come again on the next working day. My work hours are posted outside the office.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Work',
      audio: '1101',
      text: "The scribe's work is simple, which is exactly why I took the position.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Reading',
      audio: '1102',
      text: 'Book learning alone is not enough to cultivate intelligence. All those scholars in the Akademiya are prime examples.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Thinking',
      audio: '1103',
      text: "Hmm, there have been many poorly written applications lately. I guess I'll just have to reject them all.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Going out on a rainy day is the worst.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "It's just a natural phenomenon, so there's nothing to be afraid of... unless you're beneath a tree.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "It's getting cold, you say? I feel fine.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'This weather is perfect for doing nothing at all.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'In the Desert',
      audio: '1205',
      text: "Curses, there's sand in my shoes.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "It's a little early for me... Let me get a cup of coffee first.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "If there's nothing to do, then I'll just put on my soundproof earpieces and nap for a while.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "I'll be taking some time for myself now. Goodbye.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "I hope my roommate won't be hammering away on another one of his projects in the dead of night... Actually, I'd prefer if he wasn't home at all. I really don't want to wear my soundproof earpieces to bed.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Alhaitham: Facts',
      audio: '2001',
      text: 'Rather than lacing my words with rhetoric, I prefer speaking factually.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Alhaitham: Rumors',
      audio: '2005',
      text: "Oh? You're concerned about all the rumors you've heard about me?\\nDon't bother, because I don't care whether you believe those rumors. Just don't throw extra trouble my way, and we'll be fine.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Greetings',
      audio: '2003',
      text: "Don't be offended if you try to greet me on the street and I don't respond. It's simply because I'm wearing my soundproof earpieces, that's all.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Helping Each Other',
      audio: '2002',
      text: "It seems you're perfectly capable of taking care of yourself, so much so that you even look after that little companion of yours. I don't have any suggestions to offer you, and frankly, you probably don't need my help.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "To be completely honest, this Dendro Vision isn't of much help to my research... However, there's no denying the effectiveness of elemental powers when settling a physical dispute, so it still proves useful at times.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: 'Truth serves no master. Humankind is not a vehicle for knowledge, nor is knowledge the aim of humankind.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "There are many things in this world that may catch our eye, but don't always believe what you see. If what we see in the world were all there was to it, then there'd be no need to think, would there?",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Lesser Lord Kusanali',
      audio: '4001',
      text: "One should neither dismiss nor overly revere the divine. Gods require followers, and they are also part of a biological hierarchy. That's why I don't take any pride in the fact that I helped rescue a god. I hope Lesser Lord Kusanali doesn't take offense.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '21': {
      title: 'About Kaveh: Overly Sensitive',
      audio: '4002',
      text: "Kaveh tends to be overly sensitive about everyone and everything he crosses paths with, and he's constantly making a fuss about nothing. Maybe it's because he's too emotionally fragile...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Kaveh: Getting Duped',
      audio: '4003',
      text: "Someone set up a stand on the street saying that for each handmade keychain they sold, a child in poverty would be given a meal. Kaveh bought at least a dozen.\\n...This is Sumeru, where even healthcare is free. I needn't say more.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Tighnari',
      audio: '4004',
      text: "Apparently, a lot of people think he has a bad temperament, but I don't think they're giving him a fair chance. When Kaveh built a house right over a Withering Zone and created a huge mess, it ended up being a real headache for the Forest Rangers. Even so, this Forest Ranger didn't hold it against Kaveh. He even invited Kaveh to his house for a meal. Hmm, maybe it's good people like him who allow people like Kaveh to survive.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Dori',
      audio: '4005',
      text: "She's sharp and always keeps an eye out for herself. She knows how to take life by the reins and make her dreams a reality. I'm not condoning her actions, but just because we stand on different sides doesn't mean that I can't appreciate her attitude towards life.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Cyno',
      audio: '4006',
      text: "The hivemind case certainly added to the matra's workload, but my conscience is clear. The root cause of what ultimately transpired actually has nothing to do with me at all. I'm sure Cyno appreciates that, as he hasn't once approached me about the incident.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 13022,
              chapterId: 2035,
              chapterTitle: 'The Illusions of the Mob',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Nilou',
      audio: '4007',
      text: 'The strengths and weaknesses of a performing artist are quite clear. Nilou knows how to play to her strengths, which enables her to live a happy and simple life.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '27': {
      title: 'About Dehya',
      audio: '4008',
      text: "It's a waste for such a capable person to remain among the Eremites. If only she'd consider my suggestion to join the Akademiya... Our work would become a lot easier with someone like her around, but a predictable life isn't exactly her cup of tea — I can understand that. *sigh* What a pity.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'More About Alhaitham: I',
      audio: '5001',
      text: "Most people are wary of interacting with me. Perhaps they're afraid, or maybe they think I'm difficult to get along with. I hope to keep things this way.",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About Alhaitham: II',
      audio: '5002',
      text: "I've never been interested in social interactions, and as you can see, my life is more comfortable than most. I'd say this is proof enough that being social is not one of life's necessities.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About Alhaitham: III',
      audio: '5003',
      text: "Every person should have something that they believe in and hold on to from beginning to end. Otherwise, it's easy to succumb to the vicissitudes of life and find yourself being led astray.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Alhaitham: IV',
      audio: '5004',
      text: "Once order is disrupted, the consequences spread like wildfire. I'd like to avoid such a scenario, so I can keep my life intact and uninterrupted.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About Alhaitham: V',
      audio: '5005',
      text: "I'll occasionally go to the tavern for a drink after work.\\nThat's not what you needed to know about? Huh, I was under the impression that sharing what you do in your free time is more personal than telling someone your thoughts or opinions. After all, you can get those from anybody on the Message Board.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "Alhaitham's Hobbies",
      audio: '6001',
      text: "I like reading difficult and abstruse books, and seeing others scratch their heads in confusion.\\nI'm only joking. I don't delight in others' misery, and rarely do I encounter a book that's difficult for me.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "Alhaitham's Troubles",
      audio: '6002',
      text: 'Based on my observations, many people inflict trouble upon themselves. Life already has enough hardships — no need to add to them.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6005',
      text: 'Taste supersedes presentation, else you risk overcomplicating the purpose of food. I think this is simple enough to understand.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "It's difficult to eat soup-like dishes while reading.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Mmm, I can taste your mastery of the seasonings.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Hmm, a contemporary flavor. Not bad.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Let's not eat here. Mind if I... take it home?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday. I've always thought people are a little too enthusiastic about celebrating the day they were born. Wouldn't it be better to apply all that enthusiasm towards their daily lives and improve their standards of living? But you seem to have done well for yourself. I didn't know what kind of gift to get, so I'll just set up a special application channel, reserved for your submissions alone.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Thank you.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Ah, so it wasn't a one-time-only thing.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "I think you're more excited than me about this progress.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "We mustn't let those lazy Akademiya scholars know about the progress I'm making. If they catch wind of this, they'll stop at nothing to make my life even more of a hassle. I'll reject anything they send my way, of course, but the communication required to do so is a huge waste of my time.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Here you are.',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Flicker.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Hmph.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Scatter.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Diffract.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'A process of elimination.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: I',
      audio: '300002',
      text: 'Here you go.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: II',
      audio: '300003',
      text: "Don't let any of it roll away now.",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: III',
      audio: '300001',
      text: 'Huh.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'What a drag.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: II',
      audio: '410002',
      text: "The plan's changed.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'I need more time.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Allow me.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'As expected.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: I',
      audio: '500001',
      text: "I didn't... foresee this...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'I... miscalculated...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'A grave... oversight...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Tch, how bold.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Well now...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Yes?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Let's get down to business.",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'How long will this require, exactly?',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'A capable person who keeps a low profile for too long is often perceived as someone with a mysterious identity and ulterior purposes. Alhaitham himself is a powerful rebuttal to all these cliché views: He is a brilliant man, but he is only an ordinary employee of the Akademiya, with a stable job and a cushy house in Sumeru, leading a carefree and comfortable life.\\nSometimes, people find it next to impossible to catch the current scribe in his office. Little do they know about the scribe, other than his name, "Alhaitham," and that he is supposed to be present during work hours. The fact is, no one knows his whereabouts, and all they can do is leave documents and files on his desk.\\nAlhaitham couldn\'t be more satisfied with how things are. The man might be at home or in the library, but he\'ll never appear where people wish him to be.\\nHaving an entirely unpredictable schedule affords undisturbed freedom.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'The title of a "scribe" may sound impressive to most Akademiya students, but this fancy name is just a product of the Akademiya\'s culture to use unnecessarily high-flown titles.\\nIn truth, the scribe does not have to be present at all major meetings, nor does he participate in core decision-making. The scribe is simply responsible for classifying and archiving important documents. However, in Sumeru, where books and manuscript documents were once managed as a resource, the scribe is one of the most "in-the-know" people in the entire Akademiya. One can say that this position is rather similar to that of the Grand Conservator — after all, the person who manages texts will have privileged access to profound wisdom.\\nAs the current scribe of the Sumeru Akademiya, Alhaitham acts in perfect compliance with his role: He does not attend any non-essential meetings, and when he is required to be present, he only records key points, jotting down other minute details based on his mood. If the meeting does not affect his personal interests or fails to pique his curiosity, he will not be bothered to give any comments. He does make comments, however, when someone has come up with something offensively foolish — and one should expect these comments to be more blunt than necessary.\\nSuch is Alhaitham\'s life philosophy: Whenever the need for his judgment arises, one must be ready to accept any means and privileges he might require to make that judgment. Fortunately for everyone, Alhaitham notes that he is too lazy to possess too many ambitions.\\nAll scholars seek knowledge and the truth. Some do so for fame, while others, for ambition. And some others enjoy conquering knowledge and the truth, transcending them, and savoring the sense of superiority in the process. Alhaitham isn\'t any one of them. He is only driven by what intrigues him. He believes that many scholars have already become lost in their pursuits, taking the truth as a tool or even a shortcut to self-realization.\\nHowever, whether one seeks it or not, the truth is always there, hanging high above the sky like an illuminating star. It is not the end of a trip or the destination of a match. It is and shall remain constant, regardless of human existence. Also, human pursuits will not simply end after certain knowledge has been acquired — though people never doubt that they can claim the fruit with joy and are prepared to sacrifice everything for it, their desire for knowledge will keep them going.\\nThose who fail to see through the truth set themselves on an endless path, while those with clear minds will say: The truth did not come into being to serve anyone, and whoever is unable to harness their desire for knowledge will be destroyed by it. Such is the rule of the Nation of Wisdom. Of course, if you want to blend in, you are welcome to fake such a posture.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'To the people of Sumeru, those who played a part in the operation to save Lesser Lord Kusanali are deemed to be heroes. However, a great many who make such compliments don\'t really know the full story. They simply repeat a fragment of a tale that they find inspiring. As one of the protagonists in their stories, Alhaitham has no opinion whatsoever about being a "hero," nor does he believe that these stories are worth talking about.\\nMeanwhile, Alhaitham has declined the Akademiya\'s offer to become the Grand Sage multiple times. But given the chaos in Sumeru, Alhaitham eventually agreed to serve as Acting Grand Sage temporarily.\\nIt already defied common logic for someone to refuse the titles of Sage and Grand Sage, and yet Alhaitham went further still, resigning and returning to his humble role as Scribe at the agreed-upon time instead of clinging to power.\\nIf he did manage to gain anything from it at all, it was the financial benefits: His salary stayed the same after his resignation, not to mention the several high-quality research projects that he was able to complete on his own. There is no doubt, then, that he will lead a well-off life. In addition, his interpersonal relationships have also improved, as he has more or less befriended the other participants in the archon-saving operation — they have gotten close to the point where Alhaitham might greet these people with a nod or two when he sees them.\\nSometimes, Lesser Lord Kusanali will also invite Alhaitham to the Sanctuary of Surasthana to discuss various matters. He has met many people there: the General Mahamatra Cyno, the mercenary Dehya, and Nilou, star of the Zubayr Theater. Nilou even once asked him: "How did you manage to come up with such a bold plan? When I think back on it, we were all quite lucky to not get hurt..."\\nNilou hesitated before she continued, and Alhaitham understood her confusion, for anyone would have wondered how he could have stayed unscathed despite the influence of the Divine Knowledge Capsule. But in Alhaitham\'s eyes, he was never in danger, for he had never used any capsules.\\nAs for how he had managed to do that, it was all thanks to his role as the scribe. As a scholar lucky enough to have read the Akasha\'s system manual, he had studied the headset and Canned Knowledge, such that he knew how to alter the status signal of the Akasha. He had even once thought of reversing the holographic shield of the Akasha Terminal and projecting it to the back of his head to offer protection from attacks on that front.\\nIt has been proven that a plan lays the foundation for everything, and that prior research lays the foundation for a plan. Alhaitham, who had no interest in boasting about how he remained unscathed, answered Nilou\'s question with another: "As far as I know, Cyno and Dehya are also curious about this, yet you are the only one who has raised this question. Were they just too shy to ask me themselves?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Alhaitham seldom discusses personalities or dispositions with others. He believes that the prevalent theories about them are wrong. Suppose someone insists that one\'s character has nothing to do with their abilities and opinions, the person with such a view will find themselves unable to judge any aspect of another person. A smart person will often hold different attitudes towards a foolish person and another smart person, and the foolish often think differently when facing success and failure. People\'s views on Alhaitham are proof of this point — given his superb talents and egocentric personality, no one wants to get too close to him, but still, they see him as an outstanding scholar.\\nThis is exactly the public image Alhaitham desires. Many scholars are rigid and inflexible, but Alhaitham is not one of them. As a matter of fact, his occasional sarcasm in part reflects his philosophy. Society (or the collective) relies on rules to regulate individuals, and language is one of these regulative tools. Turning language against its original design serves to challenge unreasonable rules, and one can thus stay out of trouble.\\nThe word "talented" is abused within the Akademiya, and so are "born differently," "touched by the archon," and such... In Sumeru, one\'s talents are a trial. Outstanding talent is not necessarily seen as a perfect gift, but it also divides people. For instance, to compliment someone with unimaginable achievements, ordinary folk often call them a "genius," or "superhuman," or a "prodigy"... But upon reflection, one will soon notice another layer of meaning that even the speakers themselves have not realized: That the talented and the ordinary are categorically different.\\nIf someone is capable of things that others aren\'t, they must have been endowed with some special abilities and gifts. Excessive compliments for and wild imagination regarding outstanding people only serve to alienate them. "They are successful because they are different" — such is the typical excuse favored by underachievers. These ignorant notions mean nothing to Alhaitham. Though he does know his way around people, he will not waste his time on such trivial matters.\\nRules define borders and set limits. Yet these rules should not be judged solely on the number of people they limit. Therefore, Alhaitham has come up with his own set of rules with which he perceives everything and challenges the world. It is the crystallization of his philosophy. To maintain these rules of his own fashioning, Alhaitham acts on his own will and deals with anything that appears harmful in his eyes.\\nOnly with objective judgment can one see the truth. By acknowledging the differences between individuals and recognizing differing levels of capabilities and mental capacities, one will discover the answer right away: Judgment from others is inconsequential, but to leave the right of judgment in others\' hands is equal to denying oneself. To be "different" should not simply be a label given to you by others. Rather, the talented should have long understood that their uniqueness is also a gift.\\nTo put it another way, when a talented person truly understands that they are different and that they are indisputably ingenious, only then can they truly understand the value of their abilities. And as for cowards who remain blinded by perspectives advocated by the great majority, they have not yet found their true selves.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "To live a peaceful and comfortable life, one must meet a few requirements first: Congruous personality and logic, adequate fighting prowess, a slow-paced job, and a cushy house in the vicinity of one's office.\\nAlhaitham has checked all the boxes above. He would never deny that no place suits him better than the Nation of Wisdom, where social capital is linked to one's academic abilities.\\nHis current house, which is located near the Akademiya, is one of the academic resources that he gained through promising research projects. This house's story dates back to Alhaitham's student years. If his classmates still remember him, they will recall that he was not one to mingle with the crowd. As a result, he has only participated in one joint research project. Despite its eventual success, the project resulted in a huge quarrel and a parting of ways. Little do people know about Alhaitham's part in this story, though they might be acquainted with the other protagonist: The Kshahrewar architect Kaveh.\\nThis academic incident is not very widely-known — and in truth, the tale of two geniuses falling out due to differing perspectives is an all-too-familiar one in the Akademiya. But even though their collaboration did fall through, neither of them will deny the other party's exceptional brilliance. As for their research, the Akademiya would later transfer the relevant assets to the researchers involved as per regulation.\\nAlthough the two did not continue that research, its great success in the early stage still serves as compelling proof of Alhaitham's academic ability. Later, the Akademiya even used this project, which they had forgotten to cancel, as a reference for allocating housing resources, and as such, Alhaitham was given a very decent house befitting his participation in this ingenious project. But the other contributor, Kaveh, had never approached Alhaitham regarding that allocation. It wasn't until later that Kaveh had someone inform Alhaitham and the Akademiya that he was not in want of a house and thus had no use of this property.\\nWhen next they met, Kaveh had gone bankrupt. According to Alhaitham, this former friend of his possesses a personality and values that are not congruous with his abilities. The two differ on too many things and cannot reach a consensus even today.\\nAllowing Kaveh to stay in this house provides Alhaitham with an interesting research topic: Legally and socially speaking, since Kaveh has previously forfeited the right to his half of this house, he should pay the landlord during his stay. However, paying rent would, to some extent, deny his contribution to the research, which contradicts the academic spirit.\\nAn intriguing matter to consider, but Alhaitham has no interest in the answer. Thus, he has taken his broke former colleague in, collects rent as the rightful landlord, and gives his colleague some household chores. He is well aware of the dissatisfaction Kaveh might have, but it matters not to him. As far as Alhaitham is concerned, Kaveh is a familiar face, similarly lacks familial attachments, and is the polar opposite of himself as a scholar — that is to say, an excellent mirror. Human vision is limited, but it can be perfected through the presence of another genius. Taking this opportunity, Alhaitham will be able to observe other aspects of this world and thus understand more things that may have otherwise been unfathomable.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "The Nation of Wisdom places academics and knowledge above everything else. As such, a scholar acknowledged by others within the Akademiya usually possesses a higher social status. Alhaitham was born to just such a family of well-received scholars. His parents died very early in an accident, and he was raised by his grandmother, a Kshahrewar scholar.\\nAlhaitham doesn't have many recollections of his parents. He learned from his grandmother that they were both employed by the Akademiya, with his father being a mentor in Haravatat and his mother, a renowned scholar in Vahumana.\\nAlhaitham has inherited his parents' intelligence, and he was always the sharp kid amongst his peers, so much so that he started reading abstruse academic journals at around the age of seven. Having noticed his exceptional talents, Alhaitham's grandmother suggested that he attend school early. However, it only took half a day in the Akademiya for little Alhaitham to report this back to his grandmother: Everyone he met there was boring and he preferred reading alone to listening to their meaningless courses. Alhaitham's grandmother saw his parents' talents and personalities in him, and agreed to let him stay home to be self-taught.\\nTo Alhaitham, \"to be self-taught\" means to read, break down, reorganize, and question. Due to his family background, he was lucky to be exposed to books made of paper. Interestingly enough, he takes more pleasure in reading his grandmother's hard-copy collections than obtaining knowledge from the Akasha directly.\\nAs opposed to the Akasha, books are inflexible and rigid, and there is no guarantee that their contents are error-free either. To use such a medium of knowledge is to dance with potential misinformation. The majority of people in Sumeru hate this, but Alhaitham derives great enjoyment from it. It was from reading that he acquired the ability to learn, analyze, and even rectify, and ultimately, he has learned to question. If the rustic and primitive method known as reading is ever any trouble, it is trouble that Alhaitham appreciates.\\nAlhaitham's grandmother told him: \"You and your father both like reading. Now, I can't say if the two of you have been given too much share of wisdom or not, but always remember that being different is a gift.\"\\nKnowledge is to be recognized, pursued, and trusted, but one should never forget to question it. Perhaps only those who come to such an understanding will not be easily moved by Canned Knowledge and other convenient knowledge media. And only someone who had already met these prerequisites would have casually read the Akasha manual sealed deep within the House of Daena.\\nAs Alhaitham's grandmother had said, books contain useless information, and sometimes in large amounts, but his sharp mind will sift through them — and if a book he has read lingers in his memory, it will come in handy one day.\\nAfter his grandmother's passing, Alhaitham managed her funeral on his own, inheriting her properties and her small library. Before she passed away, Alhaitham's grandmother gave him this earnest blessing: \"You are such a smart child. Many such people have large egos and a propensity to act on their own. You are outstanding and possess a broader horizon than ordinary people. This is not a bad thing, but you must take care to have a clearer mind than others. You must understand that vain pursuits are but dust, and that you must discern your path with the greatest of wisdom.\"\\nLater, Alhaitham applied for the Akademiya and was immediately admitted, scoring high marks in the Haravatat entrance exam. He was informed that his grandmother had also applied for him to be able to attend classes in other Darshans. Following his late grandmother's advice, Alhaitham has always kept a low profile and a clear mind, and always makes decisions for himself.\\nYears later, when Alhaitham moved into his new house, he brought all those books over. While sorting through them, he flipped through a few that he had read long ago. The journals that had well-wishes written on their title pages were from his mother's collection, and the ones with reference materials inserted between pages and notes on the margins had once belonged to his father. On top of them, there was a thick book with an exquisite, emerald-colored cover. On the title page, his grandmother had written thus: May my child Alhaitham lead a peaceful life.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "The Doer's Belt Pouch",
      title2: null,
      text: "A sturdy and durable green belt pouch.\\nPeople often mistake it for a wide belt, an impression perhaps reinforced by its color being in perfect harmony with Alhaitham's outfit.\\nThere are only a few things in this pouch: Keys, some recent read of Alhaitham's, and a portable music player that goes with his headphones.\\nAlhaitham personally made the music player when he first became the scribe, and it is connected to the headphones via cables of the same color. He sometimes uses the gadget to play music, and other times, to block noise.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "\"The value of language is not limited to words. A unified language helps to govern thoughts. Language is the bottom line, rules, weapons, and violence. By making our language unique, we can open up a special path to the relative completion of minds.\\nGoverning thoughts may appear meaningless to some, but to others, it has a very significant meaning. Individuals' pursuit of uniqueness gives rise to various languages and media. People are controlled by language under many circumstances.\"\\nAs Alhaitham flipped through these pages, reaching the end of the book and its back cover, he realized that an intricate ornament had been underneath the tome this whole time.\\nOf course, he knew what it was — a Vision, the proof of one's power. However, this item did not mean much to him.\\nA believer might have perceived this divine item to be a thing most lofty, but to him, it was no more than a useful tool.\\nAlhaitham was out on a research trip when he was given the Vision.\\nHe didn't plan to dwell too much on it. It belonged to him, after all, so what difference would it make if he checked on it tomorrow, as opposed to today?\\nAnd just like the knowledge he has acquired, what he has obtained shall always remain in his possession.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
