export const collieVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Trainee Forest Ranger Collei, reporting for duty! I will ensure your safe passage through this forest. ...Phew, I think I've finally got that line down! ...I—I didn't get any of it wrong, did I?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Forest Patrol Route Map',
      audio: '1101',
      text: "According to today's forest patrol route map... we need to head here first, then make our way over to there... Hmm... There's a loooot of writing...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Status',
      audio: '1102',
      text: "Ah, I'm feeling alright today. I'll take the chance to try and get some more done than usual.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Memory',
      audio: '1103',
      text: "When I don't have much to keep me occupied, old thought patterns start to creep back in, and— Soon as I start talking about it, the flashbacks start...",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'After the Rain',
      audio: '1201',
      text: 'Even though the rain has stopped, you still need to watch out for puddles. Just like how the past stays in the memory, long after... Ah, ahem, sorry!',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "When you hear thunder, it's best practice to stay away from tall trees. Rangers must also be on the lookout for any signs of a forest fire.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: "The weather's not bad. Let's get some sun! Hehe, after all, it's excellent for your health.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: 'Ahh, the wind is perfect. Not too light, not too strong... Hehe, I bet Amber would be itching to test her limits in this weather.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning! *yawn* Sorry, I was catching up on my studying again last night...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "It's quite normal to be out until midday on the longer patrol routes. I brought a few extra Pita Pockets — would you like one?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "It's getting dark out. You need to be extra careful if you're going through the forest at this hour.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Are you ready to get some sleep? Okay. The campfire's lit — I'll keep watch tonight.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Collei: Forest Ranger',
      audio: '2001',
      text: "I wandered the wilderness for quite a long time before arriving in Sumeru, and I've eaten everything out there countless times — edible or not. Since I'm familiar with the wilderness, the work of a Forest Ranger seemed a natural fit for me when I arrived here. If they did courses in wilderness survival, I'm pretty sure I could pass... well, as long as there was no written test.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Collei Herself: Cram',
      audio: '2005',
      text: "Hmm? You wanna know what it is that I'm studying every day? ...Y—Yes, my master is a brilliant intellectual, but no, he's not teaching me anything heavily academic at the moment. It's, um... heh, \"Basic Literacy in Teyvat\"...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Old Friends',
      audio: '2003',
      text: "Amber's mentioned you before in her letters. I can't believe how much has happened in Mondstadt since I was there. Too bad I had to skip the words I didn't know, so I missed out on a lot of details... Oh, but since you're here now, would you be willing to tell me the whole story?",
      tips: 'Complete "Song of the Dragon and Freedom"',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 396,
              questTitle: 'Ending Note',
              chapterId: 1003,
              chapterTitle: 'Song of the Dragon and Freedom',
            },
          ],
        },
      ],
    },
    '15': {
      title: 'About Us: New Friends',
      audio: '2002',
      text: "I used to think that I'd never make a single friend in my whole life, but things changed when I went to Mondstadt... Then after that, I met Master in Sumeru. Now I've met you, too. All in all, I think I've been really lucky.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: "I never thought there'd come a day where I get my own Vision. In the past, I used to think that the gods only cared about people who were born popular... Um, but I was in a bad place back then. Sorry.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share: Skill Names',
      audio: '3002',
      text: "Master is always reminding me that practice makes perfect, so I sometimes try reading some light novels to improve my reading ability... Because they're at least easier to read than Master's essays. But recently, I was reading this book where the main character has loads of different skills. Each one has a name, and I didn't know a single word in any of them... Hmm? The title? I think it was, um... \"Onibudou\"? Have you read it before?",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Sealed Power',
      audio: '3005',
      text: 'Ugh... Here we go again: "The power sealed within me grows restless"... and "You\'d be wise to stay away from me"... Why are people in Inazuma casually coming out with lines like these all the time? Doesn\'t it embarrass them when they think back on it later? Aaah... no, it\'s too cringey. I can\'t read any more of this!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Well, there's plants and animals, there's ones you can eat and ones you can't, but beyond that it's all much of a... uh, muchness really? ...Shh, don't tell Master I said that. Although... personally, I guess I quite like trees that have a hollow in it? Especially in those moments where I just want to curl up in a ball and hide away. Everyone must have moments like that, right? ...No?",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Tighnari',
      audio: '4001',
      text: "Although Master can be quite stern and is always criticizing adventurers for carelessly eating poisonous mushrooms, he is actually a gentle soul. He's so patient when he tutors me, and he even reads out letters from Mondstadt for me. I've always been very grateful to him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Dori',
      audio: '4002',
      text: 'I ran into her once on forest ranger duty. She pulled out a bottle of fruit juice from her bag that looked really tasty, as if she somehow knew I was thirsty... Fortunately, Master was there, and he stopped me from spending all of my hard-earned Mora in a moment of weakness...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Lesser Lord Kusanali',
      audio: '4003',
      text: 'The Dendro Archon... When I was a kid, there were so many times when I just wanted to scream out to the gods and ask them why, why did I have to go through so much pain...? *sigh* But, for all I know, maybe the gods feel just as helpless about everything they have to endure as I did back then.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Cyno',
      audio: '4004',
      text: "Um... I'd rather not talk about him, if that's okay? Oh, no — the General Mahamatra isn't a bad guy or anything. Matter of fact, I have him to thank for bringing me back from Mondstadt to Sumeru and finding me a safe place to stay. It's just that... whenever I'm reminded of the sealing process just before leaving Mondstadt... ooh... the back of my neck starts hurting again...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaveh',
      audio: '4005',
      text: "The General Mahamatra once brought him to our place for a meal. From the moment the fruit arrived on the table, he ranted non-stop about his difficult and stubborn roommate for the entire meal. We didn't get a single word in the whole time. We just nodded along and tried to stifle our laughter. It took a lot of effort.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Nilou',
      audio: '4006',
      text: "She seems a little absent-minded. If she ever comes to perform around Gandharva Ville, I'm worried she'll end up wandering off into the forest and getting lost... So I'll have to watch out for her, as a responsible trainee forest ranger should.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Amber',
      audio: '4007',
      text: "Amber is amazing. She's friendly and has tons of enthusiasm, plus she's really brave and always does the right thing... She's the person I admire most of all! She's like a cozy fire that makes everyone around her feel warm. There's no way I'd be where I am today without her... So much time has gone by — I bet she's even more cool and confident than ever these days! Who knows if I'll ever be able to match her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Kaeya',
      audio: '4008',
      text: "How's everyone in Mondstadt, are they good? I caused so much trouble back then, I sometimes wonder if I should make some time to go back there and apologize... Hmm, but what if I ran into the Cavalry Captain, and he started teasing me? ...Yeah, there's no rush, maybe I'll leave it a while longer.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Lisa',
      audio: '4009',
      text: 'After all this time, Lisa still calls me "Little Collei" when she writes to me. I feel like by now she... hmm? She calls you "cutie"? Hahaha... Sorry, I don\'t mean to laugh, um... but I must say, that makes me feel a lot better.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Fischl',
      audio: '4010',
      text: '..."Prinzessin der Verurteilung"? ...Mmm, nope, sorry. I wasn\'t in Mondstadt for very long, so I didn\'t hear of her. That name, though... *grimace*... Ahem, nothing.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Faruzan',
      audio: '4011',
      text: "Um... To be honest, I don't really know how to handle people like Madam Faruzan... She's always saying that I'm a hardworking student and eager to learn, but that's because I have to be! I'm a slow learner, so I have to put in the extra effort. Oh, there was a time when I accidentally saw her research journal — only for a second, though. It was all written in old script, and I couldn't even make out half of it... Definitely the scariest book in Teyvat!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Collei: I',
      audio: '5001',
      text: "You wanna know more about me? If you mean about before I came to Sumeru, then, um... M—Maybe you could write to Amber and ask her about it? Wait wait wait, no, not that. If Kaeya found out, that would be a disaster. What am I saying — of course he'd find out! O—Okay, I'll tell you myself, then. Whew... I'm sorry! Please give me a few days to work up to it...",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Collei: II',
      audio: '5002',
      text: "When I ended up in Mondstadt, I said a lot of things to Amber and the others that I shouldn't have. I still feel ashamed whenever I think about it... How could I talk like that to people who were just trying to help me? I shudder to think what they must have thought of me back then... Uhh, sorry, maybe we can leave it there for today? If I go any further than that, I know I'll regret it tomorrow.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Collei: III',
      audio: '5003',
      text: 'I was once taken to someone they call "The Doctor" for treatment for my Eleazar... well, actually "treatment" is the wrong word — it was more... experimentation. After so long in that place, I couldn\'t help but start to wonder, what have I done wrong to deserve this? Why won\'t anyone come to rescue me? Gradually, I went from hating just the Fatui to hating everyone in the world. Thinking about it now... it was quite childish.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Collei: IV',
      audio: '5004',
      text: "Thanks to you guys, my Eleazar has disappeared without a trace. It's the miracle that I never dared to wish for. ...I never held out hope for a cure, I just figured I'd try and just do as much as I could before my body stops moving. First I was focused on revenge, then forest patrol... and now, finally, I am free to live my life.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '35': {
      title: 'More About Collei: V',
      audio: '5005',
      text: "Are you going to keep traveling? Let me do my part, please? I'll study hard... whether it's reading, medicine, combat, or assessing the danger... even something small, like checking the streetlights! I hope that many more people will get the help they need along the way... just like how you saved me.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '36': {
      title: "Collei's Hobbies",
      audio: '6001',
      text: "My hobbies? ...Sewing, practicing gliding, and helping people! Hmm? Sounds familiar? Well, that's because... I want to be someone that gives people that warm feeling, too.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Collei's Troubles",
      audio: '6002',
      text: '"In response to the homo— homogenization of crop species... taken import measures... avoid long-term consumption of fungal foods..." What is the point of all this... They\'re literally saying, "I don\'t wanna eat mushrooms," but because they\'re from the Akademiya, they have to make it sound all complicated!',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6005',
      text: 'Pita pockets are travel-friendly and filling, so they\'re probably the food I eat the most. But if we\'re talking about more than just "filling," my favorite food would be... mmm, Fried Radish Balls, I think.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "During my wandering days, there were times when I had to crack open Wolfhooks and force them down if I didn't want to go hungry, so there aren't really any foods that I especially hate. If I had to pick one thing that I won't touch, it would be mushrooms of any kind. Nothing to do with the flavor — I just don't want to ever be the one on the receiving end of one of Master's stern lectures...",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Mmm... It's delicious! Could you teach me?",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "With skills like this, I bet you never go hungry when you're out in the wilderness, huh?",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Sorry, Master says I'm not supposed to eat anything that looks suspicious.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "Uh, H—Happy Birthday! Here's the cake I made for you, and here are the candles, so yeah... Amber said in her letter that this would do the job... Oh! And, and here's the gift I got for you!\\n...I'm sorry, I don't have much experience arranging birthday parties. I have no idea if you'll like it... Aah, I'm getting all flustered now. If anything's not how you like it, please say, and I'll make absolutely sure to plan a nicer birthday celebration for you next year!",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Does this mean I'm making progress?",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I'm starting to feel like... I'm finally a better person than I used to be.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Even if it's a life-or-death situation, I'll never need to rely on their power again.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "It probably wouldn't even matter if I unsealed that power now — I've come so far, I think I'd be able to control it, don't you? Well — only one way to find out! Hu-uh!\\n...Just kidding. My real superpower is all about the adventure experience I've had with you.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100002',
      text: 'Go!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100003',
      text: 'Fly.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100001',
      text: 'Hai!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Cuilein-Anbar, help!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Try this on for size!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Just like we rehearsed!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "It's important to replenish your supplies often when you're out in the wild.",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Wow, this is so lucky.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Phew, glad there weren't any poisonous mushrooms inside.",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'I—I can keep going!',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: II',
      audio: '410002',
      text: "I've been through worse!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: III',
      audio: '410003',
      text: "Uh... I'm hurt pretty bad...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Don't push yourself!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "You're gonna get injured...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'A Forest Ranger... forever.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'No... not like this...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'I knew... this day would come...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'How the...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: "D—Don't touch me!",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I'll ensure your safety.",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Everything's ready, let's go!",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Trainee Forest Ranger Collei, reporting!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '"Helpful," "bright and sunny," "friendly and passionate"... Just ask around Gandharva Ville, and you\'ll hear this Trainee Forest Ranger praised to the skies in such terms.\\nAs long as her body allows, no matter how busy school gets, Collei will never slack off when it comes to her forest patrol work, and is always willing to lend a warm helping hand to whoever is in trouble, regardless of what walk of life they are from.\\nNevertheless, even as enthusiastic and positive as she is, there seems to be a past and things on her mind that she is not yet ready to reveal to others.\\nIf in the woods where she often patrols, you should chance upon a tree hollow full of strange notes, or hear someone whispering nearby...\\nNo matter what you witnessed or overheard, please kindly take a detour and consider it a silly prank — one played by an Aranara, perhaps.\\nAfter all, there are some things that only a tree hollow can know — for now, anyway.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'If words are the vehicles of wisdom, being literate is undoubtedly the starting point of the pursuit of knowledge. Collei, however, seems to have only barely reached the foot of the mountain of knowledge.\\nWhen she first arrived in Gandharva Ville, even the outspoken Tighnari showed obvious hesitation, making repeated inquiries with the General Mahamatra if she had walked through the wrong door, since he had yet to make any plans to teach preschool level courses.\\nStill, after several twists and turns, Collei did finally become a trainee. To facilitate her learning of words, Tighnari gathered a wide assortment of books and documents, in the hope that Collei would soon master enough words through extensive reading.\\nApart from the literacy encyclopedias for children and the mandatory-reading academic papers that made her head swell, Collei can most often be found reading fairy tale picture books from Mondstadt.\\nThe logic is simple: those books tend to have fewer words and more pictures. Even if you do not know the words, chances are that you can still guess their meaning by looking at the illustrations.\\nHowever, reading only children\'s books hardly sufficed to keep up with her curriculum. Once she had picked up slightly more words, she immediately started to look for new extracurricular reading materials.\\nAccording to some travelers who had passed through Avidya Forest, there was a type of book in Inazuma known as the "light novel," which was easier to read than academic papers, and with fewer illustrations than picture books. To Collei, that sounded like the exact type of book she needed.\\nMore importantly, the plots of these "light novels" were often so incredibly riveting that as soon as they got a copy, many readers just had to finish reading it in one go, even if they had to stay up all night.\\nThat definitely sounded tempting to Collei, since she had to force herself, more often than not, to stay awake long enough to finish her readings.\\nOne day after her forest patrol, Collei excitedly ran back to her dormitory with the newest volume of "Onibudou." She was so ready to pull an all-nighter reading the light novel — and as it turned out, she indeed stayed awake that night.\\n"My sealed power!" "The lonesome avenger!" "You\'d be wise to stay away from me!" "I shall never witness the grace of the gods!"...\\n—Covering her head with the quilt, Collei tossed and turned upon her mattress the entire night. Even as the dawn broke, she had not yet torn her mind away from these words.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'There is a saying in Teyvat that has obscure origins and is often used by people who are feeling extremely ashamed or embarrassed:\\n"I just wanted the tree to open up and swallow me."\\nCollei was pacing in the woods while murmuring the sentence, which she had just learned from a book.\\nBefore she returned to Sumeru, she had promised a dear friend that she would become an excellent doctor with exceptional medical skills so as to save people like her who were in constant agony, both physically and mentally.\\nHowever, it takes only a passing passion to make a wish, and yet it requires years of painstaking training to realize it. In the examination that had just concluded, Collei had hit the barrier between reality and expectations once more.\\n"Ugh... How am I supposed to tell Amber about this..."\\nPlus, she would have to ask her master to write the letter for her. Things like doing poorly on the test and wanting to have someone to talk to were not things she could easily speak out in front of her master, either.\\nIt just so happened that a tree hollow, roughly the size of a person, appeared along her patrol route, as if some god had overheard her mumblings.\\n"Wait, wait... Talking to Aranara about my problems... I mean, I\'ve read about it in the books, but they were children\'s books! I\'m sure I\'ve outgrown that... But now that there\'s no one around..."\\nBefore she knew it, she was already crouching in said hollow.\\nThe darkness turned into a solid fortress, isolating Collei from all kinds of pressure.\\nCollei, being an introvert by nature, found it difficult to present herself impeccably. No matter how hard she strove to be as outgoing and sunny as Amber, she could never manage to ignore her weariness and loneliness.\\nThus did Collei vent her distress to that hollow, emptying herself of all the negativity she had accumulated after getting back to Sumeru.\\n"Did Collei go on patrol in that area again?"\\nA few days later, Tighnari checked on Collei\'s recent forest patrol routes, which she had been taking all too frequently, before looking at her test papers, which featured remarkably higher scores. He could not help but think to himself:\\n"Did she find a way to improve her grades in the forest? Well, that\'s not bad either way. Alright, I\'ll save that patrol route for her and leave her be for the time being. I\'ll have other Rangers take the other routes."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Should written tests be left out, Collei actually does well on her exams, especially when it comes to "surviving in the wilderness."\\nThe jungles of Sumeru suffer no shortage of poisonous creatures and dangerous beasts, while unexpected emergencies lurk around every corner. Therefore, a competent Forest Ranger must be a thoroughly-prepared one.\\nAnd Collei really exceeds in this regard. She may not be as literate as her peers, which hinders her performance in all the written tests. Yet, she is nothing if not practical and creative.\\nWrapping thorny vines around her boots to increase traction, rubbing the toxic sap of poisonous mushrooms onto hunting traps to promote efficiency...\\nSuch ideas have ensured that she can travel in and out of the jungle safely, successfully extracting those unfortunate enough to become lost in the woods, accidentally ingest poison, or get hit by a running beast.\\nThose who have been rescued by Collei are, one and all, amazed by her unique but reliable survival skills — not to mention how they are all moved by her genuine kindness and enthusiasm.\\nBe it surrounded by grave dangers, or lacking food and supplies, even if the rescued traveler turns hysterical, she embraces every circumstance with the warmth of the sun.\\nShe cares little for scars, and hunger concerns her not. She just wants to offer help to whoever is in need.\\nThe only thing about her that is considered unacceptable by many is the recipes she utilizes during times of crisis: as long as they can replenish her energy, she will even gladly swallow fireflies without hesitation — the crushed pits of Zaytun Peaches are even less of an obstacle.\\nWhen people meet her, they simply cannot help but wonder about this young trainee\'s past.\\n—What sort of experiences could make such a seemingly innocent girl see the wilderness as her home?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Before returning to Sumeru, Collei had wandered for a long time.\\nThe decisive difference between wandering and traveling, of course, lies in that the former bears no designated destination.\\nHer wandering started from those charred ruins, or perhaps earlier, when she was afflicted with that disease, and it was long destined to be a never-ending nightmare extending into nothing but total darkness.\\nMost of the companions with whom she had fled from the ruins either lost their way in the endless waves of sandstorms, or corroded to death by divine remains.\\nSick and cursed, they had nowhere to stay, thus turning to uninhabited jungles and wildernesses.\\nMother Nature is both merciful and cruel. She would never reject them because of their illness, nor would she offer whatever they need even if they cried out for it.\\nAs more and more of her companions could walk no further, the lessons they left behind helped the rest become better at surviving in the most desperate situations.\\nAnd when Collei's last companion could no longer continue, she learned yet another lesson: never to reach out to anyone again.\\nAt that time, the two of them had their backs against the cliff, utterly exhausted. Yet, they could still hear the beast roaring from not too far off.\\nPerhaps it was because of the narrow passage, if not for other reasons, but her only remaining companion bumped into her, sending her careening off the cliff.\\nFortunately, Collei managed to grab a tiny twig in her panic, before stretching out her other hand and shouting for help.\\nHowever, that companion merely glanced at her with a complicated look before escaping alone without hesitation.\\nShe did not get far, the beast's howls outpacing her fleeing steps like a raging wind. The beast's pure predatory instinct caused it to overlook the shivering Collei, who was barely hanging onto the cliff.\\nCollei quietly withdrew her hand and held on tightly to the branch that might break at any moment, until all the sounds above her head died down.\\nThe roar of the beast and the screams of that companion had all disappeared.\\nShe could not hate that companion. If she were in that person's shoes, she could not guarantee that she would have made a different choice.\\nAt that moment, there was only one thought remaining in Collei's mind.\\nBe it to offer help or to ask for it—\\n\"I will never reach out to anyone again.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Collei once again touched someone\'s hand during a certain year\'s Ludi Harpastum in Mondstadt.\\nThe city was elaborately decorated with lights and lanterns. The streets were jam-packed with people. The sky was getting darker, and the stage was in full swing.\\nA girl in flaming red just grabbed her hand, took her out of that cramped wooden box, and squeezed into the crowd.\\nPeople gathered around, cheering and applauding the contestants who were playing hoops or with slingshots.\\nCollei could not relate to them. No matter how well they could play these most childish games, what use were they in hunting game out in the wild?\\nYet, the girl with her was extremely passionate about these little games. She would cheer and whoop at every victory, and hand out the prizes she won to the children.\\nCollei was even more baffled. If not for the rewards, why would anyone participate in these activities? Was there really any fun in them?\\nSo she sneaked to a corner and picked up a slingshot to try her hand at it — in the end, one of the more than ten shots she fired eventually hit the edge of the target.\\n"Yay! I hit it!" Collei turned her head excitedly. "Hey! Did you see..."\\nIt was only then that she realized that she had been there for quite a long time and the girl in red had already left.\\nIn the days that followed, Collei had been practicing day in and day out. Gradually, she became more than familiar with the sounds of drawing a bowstring and throwing darts. She practiced for a long time, until she would seldom miss a shot out of ten.\\nEvery time she pulled the bowstring back, Collei remembered the excitement of hitting the target for the first time on that night.\\nAnd that when the girl grabbed her hand and ran towards the crowd, her palm was as warm as the sun.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Cuilein-Anbar',
      title2: null,
      text: 'To grow up is to best one\'s immature past self.\\nCollei often helps the children in Gandharva Ville mend toys, and her Forest Rangers colleagues also occasionally ask her to help patch their clothes when they get torn up by branches.\\nThat said, Collei was by no means born a seamstress. As a matter of fact, her first attempt at sewing was nothing short of a disaster.\\nIt was when Collei was about to leave Mondstadt. Right before she left, she handed a piece of repaired old clothes to Lisa, hoping that she could return it to its original owner, Amber, on her behalf.\\nThe piece was indeed repaired, but also covered in stitches so twisted that one could potentially mistake them for earthworms. In all likelihood, it was no longer possible for its owner to ever wear it out again.\\nShe was afraid that Lisa would laugh at her or criticize her.\\nTo her surprise, Lisa just gently took Collei\'s hands, hidden as they had been behind her back, and carefully bandaged the injuries.\\nShe was not even slightly surprised by all the injuries, deep or shallow, on Collei\'s fingertips. She just casually commented, "Why, it almost looks as if someone\'s been bouncing Wolfhooks across their hands all night, as if they were balls."\\n"Don\'t be this impatient with your studies in Sumeru, little Collei," Lisa said with a smile. "There\'s always a first time for everything, and learning to overcome the difficulties you encountered during that first time is where the meaning of growing up lies."\\nCollei instantly blushed. She had not quite learned how to accept the kindness of others back then.\\nBut she was just a child, and children grow up.\\nThe desperate child would grow up and discover hope once again. A child who could not use a slingshot at all gradually learned how to aim.\\nThat child who was once constantly injured by a needle has also slowly grown up to be an ingenious role model in the eyes of other children.\\nIn Gandharva Ville, children gather around Collei, chittering with envy and excitement.\\n"You\'re so skillful! What a pretty cat!" "Collei, does it have a name?"\\nCollei, for once, felt so proud of herself. She held up the exquisite cat doll, all fine stitches and perfect needlework.\\n"This is — Cuilein-Anbar!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "The rain was pouring. A surge of rock, earth, and debris had blocked Collei's way back.\\nCollei lit a bonfire by the cliff, trying to warm the shivering girl next to her.\\nThis river valley would require a full day's journey from the woodlands that were the domain of her usual patrols. If she were here all by herself, it would not be entirely impossible to get back in this rain.\\nBut now that she had a child with her, wracked by cold and hunger after being lost in the woods for a long time, she had to wait.\\nThe girl looked pale, her forehead boiled, and she kept murmuring her mother's name.\\nCollei still remembered the girl's mother, who had been anxiously and desperately seeking help in Gandharva Ville — she recalled the look on her face, the look of one who wished that she was in suffering instead of her daughter. Collei knew that look.\\nThe family had been traveling with a caravan to cross the river valley. As they were camping and resting, her playful daughter had run off, straying into the deep forest. As soon as the caravan noticed that the child was missing, they tried their best searching for her, but it was all in vain.\\nIn desperation, the mother had to return to Gandharva Ville to look for help.\\nRecently, Tighnari had been attending meetings in the city with other Forest Rangers, and the situation before her was critical — Collei could not wait for any of them to return. Nor could she rely on the search and rescue dogs during such heavy rain.\\nSo she immediately grabbed her pack, bow, and arrows, before diving into the forest alone.\\nAt that moment, the occasional low growl against the sound of thunder and rain told her that there were beasts approaching.\\nCollei could not help but recall some disturbing experiences from her past. Old memories came flooding back, the memories she least wanted to face.\\nBut the rain would pass, and after receiving the news, Tighnari rushed over without taking any breaks.\\nTraces of fighting could be found all the way along the cliff. Several beasts lay fallen in the distance, while Collei and the girl slept peacefully on each other's shoulders.\\nTighnari's heart seized up in his chest. He was well aware that Collei was not capable of doing all this — unless she had wielded power that should not be unleashed.\\nIt was like drinking poison to quench thirst, and it would surely aggravate Collei's condition. He must contact the General Mahamatra right away...\\nTighnari's footsteps awakened Collei. She hurriedly gestured to ask her master to quiet down so as not to wake the girl next to her.\\nTighnari checked upon her worriedly, \"Collei... Did you...\"\\nCollei shook her head. She raised a hand and released the fist that had been clenched all night.\\n\"Master, I've become stronger! I won't let anyone's efforts go to waste — from now on, I'll protect everyone.\"\\nIt was a Vision, silently glowing in her hand.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
