export const laumaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: 'Open your eyes. My name is Lauma, and here in the stillness of these woods, the light of the frost moon shines down generously on all. The gaze of the heavens will fall on you wherever you go. Now, close your eyes... you are no longer lost.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Moonlight',
      audio: '1101',
      text: 'Even when the night is gone, and even when the sky is hidden from view, still the moon shines its light upon you.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Animals',
      audio: '1102',
      text: 'If ever you find that the animals in Nod-Krai behave in ways you do not understand, just ask me, and I will explain.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Journey',
      audio: '1103',
      text: 'Have you decided where you will go from here? If not, why not find a patch of soft grass and rest awhile?',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Ah, the season of verdure draws near once again...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Gone in a flash... A light harder to grasp even than that of the moon.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "I heard that you're not supposed to stare at bright-white surfaces for too long... is that really true? It's so beautiful, I can't look away...",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'In the Desert',
      audio: '1204',
      text: 'When Nefer told me about this place, I could hardly imagine it... But here I am, seeing it with my own two eyes.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning. Come night or day, may the blessings of the Moon Goddess shine down upon you.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1005',
      text: 'Good morning. Come night or day, may the moonlight connect us.',
      tips: 'Complete "Elegy of Dust and Lamplight"',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: '...Oh, I must have drifted off. Sorry. If you need anything, please ask.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: 'The moonlight is so calm tonight. Join me for a walk in the woods.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: 'The stars above have bidden each other good night. Now, it falls to us to do the same.',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Lauma: Responsibility',
      audio: '2001',
      text: 'A doctrine without laws is but a book of tricks, and a leader without conscience is a false god. Wherever communities of people gather, rules are needed. Even for the Frostmoon Scions, who share a common faith, rules are indispensable to guide them.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Lauma: Soothing Troubled Minds',
      audio: '2005',
      text: "As the Moonchanter, I'm supposed to listen while my flock shares their woes, then soothe their troubled minds. But I seem to spend most of my time listening to the chatter of the animals instead... hehe...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Streams',
      audio: '2003',
      text: 'Perhaps fate ordained that our paths would cross, just as it ensures that every stream in the forest finds its way to the sea.',
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Trees',
      audio: '2002',
      text: 'Trees send roots down deep into the earth, towards the unfathomable Abyss, while their branches climb up towards the stars, far beyond the sky. May our future, too, provide endless room to grow and to flourish.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Moon Wheel',
      audio: '3006',
      text: 'This is a sign of the gods\' mercy, which is, allegedly, a measure of human aspiration.\\nWhy "allegedly"? Well... because there\'s no way to verify it.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "Place a dish beneath the moon and fill it with water, then tell it all your joys and sorrows. If a reflection of the moon appears on the water's surface, you have the moonlight's blessing.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'You want to know what the animals think of you? Haha... that tale is one that would take many moons to tell.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Ineffa',
      audio: '4001',
      text: "It's not unusual to come across prosthetically augmented people in Nod-Krai, but a wholly mechanical person from the inside out is quite a different story... And yet, she has far more humanity than many of the errant souls out there. She's gentle, kind, and full of curiosity. You could say she's as human as can be.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Aino',
      audio: '4002',
      text: 'She is a very precocious child, but fate has not given her an easy ride. Her inventions have helped many people — Nod-Krai should feel honored to count her as one of their own. If she ever wished to come and live among the Frostmoon Scions, I would make sure that all her nutritional needs are met, starting with plenty of fresh fruit, vegetables, and spring water.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Flins',
      audio: '4003',
      text: "He comes across as very polite and courteous, but for some reason the animals seem to fear him... I will keep my guard up around him — but since I barely know him and have no evidence of wrongdoing, I will also reserve judgment. Whenever he passes by the Frostmoon Enclave, I will share some of the daily harvest with him.\\n...What? His name's too long, but otherwise he's fine..? Uh... Are you sure?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Nefer',
      audio: '4004',
      text: 'Clearly, we are different people with different ways of doing things, but I have never taken that to mean that we cannot get along.\\nNo matter what, the light of the moon will always fall favorably upon her.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Jahoda',
      audio: '4005',
      text: "I didn't know much about her before we partnered up to infiltrate the Experimental Design Bureau — only that she worked for the Curatorium of Secrets as Nefer's trusted assistant. It can't be easy, being caught between Nefer on the one hand and all manner of clients on the other. I've always wished I could show her some proper Frostmoon Scions hospitality one day... Heh, I'm also a little curious to know what Nefer has said to her about me.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Varka',
      audio: '4006',
      text: "As cosmopolitan as Nod-Krai may be, it's rare to see an outsider integrate as readily as he has. There is a natural warmth to the way he treats people, which I highly admire. I remember the first time we met, he was full of praise for the Frostmoon Scions' delicious food... Oddly enough, I don't recall ever having shared any food with him, and yet I still believe he was being sincere.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Kuutar',
      audio: '4007',
      text: 'No one teaches a newborn god how to live in harmony with their followers. She must have had a very difficult past...\\nIn the hopes of achieving some sort of reconciliation, I made a request of her that must have seemed a little rude. She claims that she prefers living alone, but I still dream of a day that Kuutar and the Frostmoon Scions, the moon and her believers, can come together and share a toast.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'More About Lauma: I',
      audio: '5001',
      text: 'Look at the moon. It is always there, ever still and ever silent.',
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'More About Lauma: II',
      audio: '5002',
      text: 'In many places, a waning moon is seen as an omen of ill fortune.\\nPerhaps people forget that the moons, too, are the victims of misfortune... Their destruction was not a fate that they wished upon themselves.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '29': {
      title: 'More About Lauma: III',
      audio: '5003',
      text: 'Sometimes, it feels like people expect more "godliness" from me than the god I represent. Believers seem to have infinite tolerance for unruly or capricious behavior by their god, but not by that same god\'s emissaries.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About Lauma: IV',
      audio: '5004',
      text: "Fruit start to give off an alcoholic smell when they've been left out for too long. I don't drink, but I always find that scent relaxes me... Probably a sign that I shouldn't take up drinking, don't you think?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '31': {
      title: 'More About Lauma: V',
      audio: '5005',
      text: "Among the Frostmoon Scions, you'll often see kids running around holding a white sheet above their heads. The adults tell them that it protects them from bad luck, since being draped in white cloth looks a lot like being covered in moonlight. Of course, they get to a certain age and stop doing that — instead, they start praying to the moon at nightfall.\\nMe? Of course, it's a rite of passage. We were all children once.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '32': {
      title: "Lauma's Hobbies",
      audio: '6001',
      text: 'I enjoy spending time in solitude in the darkness of night. The birds and beasts quiet down, and the only sound I can hear is the wind blowing gently through the trees... Everything is so peaceful.',
      tips: '',
      tasks: null,
    },
    '33': {
      title: "Lauma's Troubles",
      audio: '6012',
      text: "My head... it's so heavy to carry around.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'Simple food, with minimal seasoning. It has nothing to do with my beliefs or dietary restrictions, I just find that lighter food is what agrees with me.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Anything too greasy, or too dry... It's just not for me.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Such fresh ingredients... I can't imagine the lengths you went to. I will gladly share it with my flock... What? All for me...?",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Thank you for your kind gift. Let us both share it.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'There must surely be those in greater need than I of sustenance. I will watch out for them.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Birthday',
      audio: '7001',
      text: "To you, our honored guest, cherished by the moonlight and our tranquil forest, I give this blessed dagger. For a dagger does not have to be an object of violence — indeed, they are often used as symbolic items in prayer ceremonies.\\nThat said, you're of course free to use it for whatever purpose you wish.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'I seek not to tread the expedient path...',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Nor do I yearn to wield great power...',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'But if our goal in all of this is to find the truth...',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'I shall offer my blood and tears as a truth seeker.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '44': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Forest, protect us.',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'You poor, lost lamb...',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Leave this place.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Lush as the moonlight.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'Branch into song.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Receive my blessing.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'By the Frostmoon of old.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'For the everlasting forest.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'With one heart, we pray.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Take heart. You toil not in vain.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'The world wishes you well.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Perhaps this treasure has been waiting for you all along.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: I',
      audio: '410001',
      text: '*pant*',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I am being tested...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Have I brought this on myself?',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Seek refuge in the shade of the forest.',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Return to the Frostmoon's embrace.",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'O forest, take my broken crown...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'The ebb and flow... is over...',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'A moonless night... approaches...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Stay your hand...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: '...A grave transgression.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Follow me, and bask in the soft light of the moon.',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Even when darkness falls, the faithful shall not stray from the righteous path.',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Do not be afraid, for I am with you.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'When night falls, the Frostmoon Scions dwell within a "tower."\\nAt the top of this tower is a seemingly unchanging full moon, and at its base is the soil of Hiisi Island. Its walls are made of white moonlight, allowing any to pass through.\\nOh, how gentle the Moon Goddess is. Even if not all should believe in her, even if not all should know of her, she spreads her grace without reserve.\\nThus spoke the old priestess of the Frostmoon Scions. As those words hung in the air, the sounds of lowered voices praying could be heard, but Lauma\'s was not among them.\\nShe gazed at the full moon in silence, her eyes fixed upon it alone, like the most devout of believers.\\nShe was undoubtedly in this tower as well, having grown up and lived here since birth in this spire built by the moon, its light, and the adherents of its deity.\\nShe continued gazing at the full moon in the sky, thinking that perhaps there was truth in the saying, "humans could never build a tower to reach the heavens."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '"She descended when late spring\'s first full moon hung in the sky, trees and flowers grew in response to her first cry."\\n"Laugh now, dance now, as the newborn Moonchanter weeps—"\\n"For her horns and blood are bathed in moonlight, for beneath the Moon Goddess\'s gaze shall she sleep."\\n...Lauma closed the Frostmoon Scions\' journal.\\nShe always found herself unconsciously turning to the page that recorded her birth, trying to feel the joy of the faithful through the yellowed notes.\\nJust as geniuses often emerge from among common stock, Lauma, an extraordinary being, was born to an ordinary Frostmoon Scion couple. According to records, "her eyes were like the moontide, her antlered crown grew under the moonlight, and her silver blood flowed like the moon\'s reflection in water" — a "miracle bestowed upon the faithful by the Moon Goddess."\\nAt the fringe of the world, among the "Frostmoon Scions," who had seemingly become forgotten by time itself, Lauma became a beacon of hope, timely yet untimely. The overjoyed followers took her as proof that their Moon Goddess had not abandoned them, and she became a living symbol.\\nFew are chosen at birth to succeed the title of Moonchanter, and as a Frostmoon Scion herself, Lauma should have rejoiced, regarding this responsibility as a supreme honor.\\nJust as it was written in the next passage of the journal, yes, the very words Lauma had committed to memory:\\n"...Sweetly shall she sleep beneath the Moon Goddess\'s gaze."\\n"And when the moon slumbers and the sun rises, she shall speak for the supreme Frost Moon Goddess."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "If one was born early enough, lived long enough, and one's forbidden memories weren't erased by more transcendent beings, they would surely remember (and such beings do exist in Teyvat) that before the war of funerary flame, the Three Moon Goddesses, who served Nibelung, once coexisted harmoniously with the principles of Celestia for a time.\\nOf course, if one were to inquire about this matter with Celestia, the high heavens might respond with ambiguity. The Three Moons were once satellites that guarded Teyvat, and the Moon Sisters were executors of the planet's will. Celestia's principles were once quite \"tolerant,\" not necessarily requiring the exclusion of those divergent from itself.\\nFor the Three Moon Goddesses, their sole duty was to maintain the planet's existence and operation. And so the moonlight continued to illuminate the lands of Teyvat. Alas, even they, who kept to themselves, could not remain uninvolved. Inevitably, conflicts between those in power would affect some of those who were subordinate to them.\\nIf any survivors of bygone golden Hyperborea yet endured to the present day, they would surely have many tales to tell, but alas, the Frostmoon Scions do not understand their ancestors' grievances. They can now only pray to the bright moon in vain.\\nIn this, Lauma was relatively fortunate, even amongst blind believers. She did not know anything of the above, but she could nonetheless sense keenly that the full moon in the sky was bright yet lifeless. Rather, the tides that truly moved her heart and caused her antler-crown to grow were somewhere farther away, beyond her reach.\\nThis feeling had troubled her for a long time, and like how one might feel if made to pray to an apple painted on canvas, beseeching it to satisfy their hunger, she was ever restless.\\nFortunately, this question was now answered at last. Although the sky had suddenly \"become\" fake, she had confirmed the authenticity of her senses.\\nShe had never thought ignorance to be a good thing, even if the truth was more unsettling. Life could never be lived entirely as one wished — indeed, life itself was born of contradictions. But at least it need not be tainted by lies and concealment.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Lauma once set some "precepts" for herself. These might seem irrational to others, so for the longest time, she never mentioned them to anyone.\\nShe believed that she must never lie. Silence, too, was an answer in the face of uncertainty, but one must never fabricate facts to fashion peace papered over. This was especially so for a Moonchanter, one whose every word the believers all too easily took for truth. Thus, lying was an unforgivable sin.\\nBut was praying to a false moon in the sky a lie in itself? She could not be sure of that, and this again left her feeling restless.\\nShe resolved that she must never give herself to wrath. The Maiden of the Grove was to be gentle and loving, just as the Frost Moon\'s goddess was. The lake\'s light beneath the moon was free of ripples — had the goddess\'s envoy any right to be angry? The tides of kuuvahki often disturbed her peace of mind, yes, but surely a leader worth their salt must learn to control their emotions.\\nYet some emotions did not arise from the tidal motions. She was not given to shouting or crying out in rage, but was giving her foes a thrashing anger? She rubbed her fingers together somewhat nervously. With whom could she consult on this matter?\\nShe told herself that she must not change. Over countless years of evolution, the Frostmoon Scions had drifted far from their golden era. Any fluctuation now could snap this precariously perched branch. This was especially so when the faithful viewed her, one born "special," as their hope. She had to maintain an image befitting a Moonchanter.\\nYet she had already revealed the truth about the moon and the sky to everyone. This time, she needed no consultation to know that change had already begun.\\nAt this point, all three precepts now seemed meaningless. Thus, Lauma finally let her guard down, and one night, she confided these unspeakable matters to her animal friends.\\nAs she expected, the little animals warmly welcomed her, and as usual, they all chattered away about life — specifically, her life.\\nTrue friends they proved indeed, first affirming her honesty and reliability, then praising her gentle and caring nature, and finally declaring that Lauma had always been this way, and had indeed remained unchanged. (Hearing this made her quite happy, but she then grew increasingly embarrassed... and came to wish she had two extra legs to run away immediately.)\\nFinally, a little cat who would often play in Nasha Town concluded: "If I, Ashru, had to point out any problems... I\'ve said it before, and I\'ll say it again. Your issue is that you\'re too stubborn!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Lauma once presided over an engagement ceremony.\\nThis ceremony boasted three attendees — a young adventurer who sometimes helped out at The Flagship tavern, a young woman of the Frostmoon Scions who was planning to leave Nod-Krai with him, and the Moonchanter, who had mysteriously appeared in their tavern room.\\nThere the three of them stood, staring at each other. For a time, no one spoke. The man pulled a handkerchief from his pocket with trembling hands, handing it to the nervous young woman to wipe the sweat from her brow.\\nLauma turned out to be the most composed one in this circumstance.\\nShe clearly understood what was happening, but a halting explanation still came spilling from the young woman\'s lips: "...I—I didn\'t mean to leave without saying goodbye. I left a note under my pillow for... W—Well, not that I have family here anyway, so it might never have been seen, but..."\\nThe young man also hurried to add on assurances: "I\'ll take good care of her, and I\'ll bring her back often to visit her friends! I\'m not some irresponsible lout — look, I\'ve even proposed to her..."\\nLauma looked at their clasped hands and the matching rings on their fingers with furrowed brows. The young woman started sweating again, seemingly ready to grab her fiancé and make a run for it, but Lauma stood at the doorway, her impressive height (horns included) barring the doorway as well as any steel-wrought portcullis.\\nLauma thought for a while before finally speaking, just as the two of them had begun considering leaping out through the window: "Firstly, I know you two have been seeing each other for some time now. Secondly, I never said you could not leave. Thirdly, one must have a ceremony to go with an engagement. So please, wait here. I will get things ready."\\n"...Huh?"\\nWithin half an hour, she had gathered everything needed for just such an engagement ritual (including somehow obtaining Nocturnal Blossoms that should only bloom at three in the morning), and in the cramped guest room (with half-packed luggage still scattered all about), conducted a complete engagement ceremony that fully adhered to the Frostmoon Scions\' customs (with Lauma playing all the relevant roles — master of ceremonies, bride\'s family member, and ecclesiast).\\nWhen all was said and done, the young woman heaved a sigh of relief. "So you were concerned about the ritual, Lady Lauma... I must say, you\'re quite, ah, stubborn in the most... unexpected ways..."\\n"Am I being stubborn?" Lauma tilted her head, somewhat confused. "This is something that must be done."\\n"Ah, yes. And one more thing. Sir, please leave your name, family name, middle name, as well as your fixed address. I will need to send you our sacramental victuals."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Lauma once presided over a funeral.\\nThe deceased was quite the long-lived elder, having spent one hundred and two years in this harsh, cold land. Smiling with wrinkles gathered at the corners of her eyes, seemingly never changing — thus had Lauma always remembered her.\\nIn the days following her accession to Moonchanter, Lauma had learned much knowledge from this elder. On the final night before the old dame\'s departure, she had quietly kept vigil at the woman\'s bedside.\\nAccording to the teachings of the Frostmoon Scions, death is not the end, as life is in constant "flux." Friends and family simply return to nature when the time is right, and they shall surely reunite in the future.\\nTo "fall asleep" in peace under the pure moonlight was considered the highest blessing the Moon Goddess could bestow. It should have been just such a night of serenity, the moonlight shining overhead as it had for years unnumbered, the birds and beasts holding silent reverence.\\nUntil the elderly matron softly said: "Lady Moonchanter... the Moon Goddess doesn\'t really exist, does she?"\\nThis was no question, in truth. From the elder\'s steady tone, she seemed to have already concluded this to be fact. For one hundred and two years, the Moon Goddess had never once answered her prayers.\\nMany thoughts crossed Lauma\'s mind at once. She thought of the giant statue on the Light-Bathed Platform. She thought of that young woman who looked exactly like that statue... She wanted to say: No, ma\'am, the Moon Goddess truly exists, just not in the way everyone had imagined.\\nThe Moon Goddess appears to just be a "person" like you, and she has spent these one hundred and two years living through lonely, cold nights, just as you have.\\n"It\'s alright. You need not answer." As Lauma hesitated, the elder gently shook her head. "Whether the Moon Goddess is unwilling to appear or simply doesn\'t exist, the passage of time remains unaffected."\\n"We Frostmoon Scions can live just fine on our own, can\'t we?" The elder held Lauma\'s hand ever so gently, as though she was the one who needed comfort, "So unfurrow your brow and smile, Lady Moonchanter. You have done very well."\\n"There\'s no need to grieve over anyone\'s absence... \'Death may bring forth anger, but anger too is in vain.\'"\\nLauma could not help but smile, even as she held the old woman\'s hand in turn.\\nSo she waited, waiting for the painless and peaceful slumber to carry the elder back to the warm sea of life, where at its center, three full moons must surely be reflected.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Paper Star',
      title2: null,
      text: "Lauma learned how to fold paper stars from the young children of the Frostmoon Scions, who had learned it from outside Hiisi Island in turn.\\nThe children were particularly enthusiastic about teaching something to the powerful Moonchanter. They took the initiative to cut out colorful strips of paper and even brought out some large glass jars.\\n\"The lady in town told us not to get greedy and make the stars too big, or they'll collapse inward super easy, 'cuz there's nothing in the middle,\" a little girl said with a grin. \"Especially that lady with the metal arm. She flattens those stars without even trying!\"\\nLauma listened with exceptional attentiveness, working both quickly and well. She placed her own folded stars together with the children's in the same jar, and suddenly that dull glass container came alive with activity.\\nGiven her current status and age, it might seem childish for her to be absorbed with such small arts and crafts. But then again, none had called her too mature when she read voluminously as a child, either.\\nAnd so, she huddled peacefully with the children in the corner of the room, folding three whole jars' worth of paper stars.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Moon Wheel',
      title2: null,
      text: 'Lauma was very thankful for the existence of Moon Wheels and was delighted to have one, but in truth, it troubled her quite a bit that she couldn\'t remember how she had obtained hers.\\nGrandma Sarakka said that her Moon Wheel had fallen out of her swaddling clothes. Although her parents\' memories were a bit hazy on the matter, being overwhelmed by the arrival of their newborn at the time, they confirmed this account.\\nIf she were to tell others about her troubles, they would surely be confused. Wasn\'t having a Moon Wheel since birth a good thing? What was there to worry about, anyway?\\nIt seemed that besides herself, no one found anything wrong with one appearing next to a baby. "A miracle happening to a Moonchanter... Isn\'t that just normal?"\\nLauma found herself at a loss for words. How natural and human it was to want to know the origins of something, yet despite searching through the entire library\'s records, she could not find a satisfactory answer.\\nShe never let go of this question, so much so that when she later met the Moon Maiden, she couldn\'t help but ask about this.\\nKuutar\'s response was exceedingly simple: "Oh?"\\n...Therefore, the closest explanation must still come from Hyperborea. The history of the golden realm was long indeed, and could even be traced back to the era when three moons rose in the skies. They learned to use the lunar tides to power their magics, but were in turn affected by those same ebbs and flows, and some of them thus had horned crowns akin to deer antlers grow from their heads.\\nHowever, had Moon Wheels even existed in the world back then?\\nLauma frowned in contemplation, and indeed must have accidentally started talking to herself, prompting a passing child to ask loudly: "Lady Lauma, did your horns grow so long because you have a Moon Wheel?"\\nHer frown only deepened: "Well... I suppose... I\'m sorry, I don\'t know."\\nDisappointing children was something she wished never to do if she could help it, but surprisingly, the little one did not seem discouraged by not getting an answer to his question.\\n"Oh!" He said, as if sudden realization had dawned. "Could you have gotten the Moon Wheel because you have the longest horns?"\\nOh, how Lauma wanted to accept this answer from the bottom of her heart at that moment. How clever it was, this cycle of cause and effect that shuttled from front to back, then back to front, which seemed to explain (or rather, gloss over) so many questions.\\nThen she immediately stopped herself from falling into the trap of lies.\\nPerhaps this, then, was the purpose of the Moon Wheel — a symbol, to her, of vigilance, restraint, and responsibility.\\nSo she held that puzzling Moon Wheel in her palm, silently reciting the three precepts in her heart once more.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
