export const yaoyaoVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Hello, I'm Yaoyao, a lowly disciple of the adeptus, Streetward Rambler. It's a pleasure to make your acquaintance! If you encounter any difficulties outdoors... then lemme help you! Oh, by the way, I brought some Fried Radish Balls with me, help yourself! Don't eat too many, though — too much oily stuff is hard work for your body. If you're still hungry, I also brought a freshly washed radish and some vinegar, so I could make you a shredded radish salad if you want~",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Proverbs',
      audio: '1101',
      text: "\"Don't put off until tomorrow what you can do today!\" C'mon, let's get a move on!",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Join In the Fun',
      audio: '1102',
      text: "Ooh, what's happening over there? Can we take a sneaky peek, huh? Can we?",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Adepti-Seeking',
      audio: '1103',
      text: 'Why do so many people make such a big deal out of "seeking the adepti"? There\'s adepti everywhere! Isn\'t there?',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Hey, can you hear the frogs croaking? Hehe, silly frogs! They're singing along to the sound of the rain! Ribbit, ribbit, ribbit~",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Wh—Whaa! I—I'll cover your ears for you, a—and if you're scared, you can hold my hand.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "It's snowing, yay! Uh! First things first: You have to wrap up warm. Put your big fluffy coat on... uh-huh, and your woolly hat and scarf, yep— Ah-ah-ah! Don't forget your gloves. ...Good! Alright, let's go build a snowman!",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "The weather's so nice. Let's go have a walk around the harbor!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "Ooh, it's getting windy. Be careful not to get blown away.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Time to get up! Your breakfast is ready, so you'd better hurry... Uh, huh? You still wanna snooze a while? ...Well, okay — but five minutes and that's all, okay? Five minutes, and I'll be back to wake you up again. *sigh* I knew I should have sent you to bed earlier...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Now, don't forget: You don't wanna nap right away after a big lunch, but you also mustn't go racing off on an adventure. You gotta wait for your food to go down, or you'll get a tummy-ache.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Huh? You're going out again tonight? Hmm, what time do you plan on getting back? *sigh* Well, it's dark out, so be really careful...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: 'Time for your bedtime story... Now, where did we get to last t—time... Ah, yes: "Ever since ancient times... the mighty and illuminated adepti have protected Liyue against evil. Among them, mmngh mmph..."',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Yaoyao: The Liyue Docks',
      audio: '2001',
      text: "You know the docks in Liyue Harbor? There's always loads of people talking, shouting, laughing, it's great! Totally different from back home. It's so quiet there, you can hear the leaves falling on the grass. That's why I go to the docks whenever I'm free — you know, to see the new ships, new sights... and new toys!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Yaoyao: Eat Up, Wrap Up',
      audio: '2005',
      text: 'They say "Give them clothes to wear, and they shall show you decency; fill their stomachs with grains, and they shall fill their minds with righteousness"... And that\'s why you have to eat a decent meal and dress right for the weather when you\'re out in the wild. ...Huh? Is that not what that saying means? Oh, okay, so... what DOES it mean?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Polearm Training',
      audio: '2003',
      text: "It's not that I'm lazy, it's just the spear's too long for me, and it's so heavy that training with it is really hard work... Luckily, Master doesn't push me too hard.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Worries',
      audio: '2002',
      text: "Have you been eating three meals a day? Also, do you have enough warm clothing? This cold spell's only going to get colder, you know. And anyway, are you sure it's not dangerous, adventuring all the time? Any new injuries I should know about? ...Ugh, you know what — forget that, just bring me along from now on. I can't have peace of mind knowing that you're out there braving the elements all day long...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "My Master's a Mighty and Illuminated Adeptus! She once told me that getting a Vision is a sign that the gods are pleased with you, but I don't think I've done anything special... I really wish I could talk to that god and see what she thinks about it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: '"Osial"? Oh, you mean that jumbo-sized octopus from the Sea of Clouds? Uh... not because I wanna eat it or anything, but... if you guys wanted to, you should definitely cook it through on the grill first... Oh, wait! I mean, you don\'t HAVE to grill it, but... I just think it would taste better that way...',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'I love finches! Whenever I go to play with Qiqi, I look out for them on my way there. And when I find them, I say hi! ♪ *whistle*~ ♪ ...Yep! "Good morning!" That\'s exactly what it means, well done!',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Xiangling',
      audio: '4001',
      text: "Xiangling hasn't been, um... looking for strange ingredients lately, has she? She gave me a real fright last time. She said she was about to try some raw octopus from the Sea of Clouds. One of these days, she'll give herself an upset stomach — then what's she gonna do? 'Cause she definitely doesn't like taking Dr. Baizhu's medicine... Anyway, I got Master to try and talk some sense into her, too. Who knows what dangerous thing she'll be trying to eat next... *sigh*",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Qiqi: Friends',
      audio: '4002',
      text: "Qiqi's my best friend! She forgets who I am sometimes, but I know she doesn't mean it... I just have to remind her to check her notebook, and she remembers me right away.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Qiqi: Forever',
      audio: '4003',
      text: "I once asked Dr. Baizhu in private if there's any way to cure her, and, um... But it doesn't matter. I'll probably have to keep reminding her who I am for my whole life, but that's okay.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Baizhu',
      audio: '4004',
      text: "Dr. Baizhu's prescriptions are pretty effective. They're bitter, that's for sure, but they always say that about medicine: \"the bitter the better\"! So I get it. Huh? Too bitter for you? Don't worry, I've got some Candied Dates here. One of these after you finish your medicine will take the taste away.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Ganyu',
      audio: '4005',
      text: 'Ganyu always has a lot of work to do. I heard that one time, she was so tired she accidentally fell asleep on the grass. *sigh* I do worry about her, you know! Hmm, maybe... we could go do a "surprise inspection"! You know, check in and make sure she\'s taking care of herself. Oh! Uh... Wait a minute, I\'ll go get some of her favorite plants for her to eat...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Keqing',
      audio: '4006',
      text: 'Keqing\'s a very thoughtful person, and she always does a good job of everything. She also makes sure to pay Master a visit at every festival... She\'s what you call a "bastion of piety." Or wait, maybe it\'s "paragon of propriety"? ...Well, anyway, I think I can learn a lot from her!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Yun Jin',
      audio: '4007',
      text: "Now, Yun Jin's really good at spear dancing, and her Liyue opera performances are very popular. Master even takes me to go see them sometimes. You won't find an empty seat when she's on stage... but, um... does anyone understand what she's singing about?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Beidou',
      audio: '4008',
      text: "Beidou's ship is amazing! If I hadn't promised Ganyu that I wouldn't go on board anymore, I know exactly where I'd set up my own little bed, hee-hee.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Shenhe',
      audio: '4009',
      text: "Shenhe's been away from the human world for years and years, so it's no wonder that she's still adjusting to life in Liyue Harbor. I'd love to help Ganyu take care of her... But how do I ask her in a way that won't make her feel uncomfortable?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'About Yanfei',
      audio: '4010',
      text: "Yanfei takes that huge legal codex everywhere, even when she comes to pay Master a visit on her days off. She's incredible! I don't know how she carries that heavy thing around all the time, and I can't imagine how much hard work it must be to read it...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Xianyun',
      audio: '4011',
      text: 'When I went to look for Master the other day, I found her chatting with a very elegant-looking lady. She said her name was "Xianyun," but her hijinks didn\'t fool me! I could tell it was Aunty Cloud Retainer right away! I mean, Master looked like she was really happy to see her, so how could it be a stranger? Evidently, she was an old friend!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 11035,
              chapterId: 2045,
              chapterTitle: 'A Thousand Moonlit Miles',
            },
          ],
        },
      ],
    },
    '31': {
      title: 'More About Yaoyao: I',
      audio: '5001',
      text: "You wanna know where I'm from? Well, my parents are hermits who live up in the mountains... Uh, I guess you could say that I'm from Qingce Village?",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Yaoyao: II',
      audio: '5002',
      text: "My family makes a living by growing precious medicinal herbs. My parents often get so busy that they forget about the housework, and sometimes they even forget to eat! Tsk, isn't that awful? Good thing they've got me to look after them.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Yaoyao: III',
      audio: '5003',
      text: "I grew up in the mountains, so the flowers, trees, plants, and animals are all my friends! Oh — would you like to chat with the finches? I can take you to them, and I can also help translate for you. Come on, it'll be fun~! But first, let's get some grains as a gift for them.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Yaoyao: IV',
      audio: '5004',
      text: "There are adepti everywhere in Liyue. I've met loads of them! Aunty Cloud Retainer, Uncle Mountain Shaper... But Aunty Cloud Retainer's my favorite! She's given me all kinds of adepti gadgets, and taught me all about how to use them. I've learned so much from her!",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Yaoyao: V',
      audio: '5005',
      text: "After I met Master, she said that the path of my fate had intersected with the adepti way, and took me on as her disciple. To be honest with you, I didn't even understand what she meant by that. But it's been so much fun, getting to hang out with everybody, listening to Master tell stories, and sneakily slacking off with Xiangling... And we also get to help the people of Liyue Harbor out a lot. I really love it!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "Yaoyao's Hobbies",
      audio: '6001',
      text: "It is said that joy hides just beyond the horizon, and bliss is as fleeting as the setting sun! So, whenever I notice anything fun going on, I always gotta go check it out... and you never know, maybe I'll find something I can help with.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Yaoyao's Troubles",
      audio: '6002',
      text: "Oof, spear training is really kinda boring... Maybe I'll go play with Yuegui for a little bit, then come back and do some more training after I've had a break...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6005',
      text: "Qingce Stir Fry, Come and Get It, boiled fish... Lots of Liyue dishes are not only delicious, they also turn mealtimes into a big event. Hmm? You like them too? That's great! You'll have to come over for dinner sometime, I'll cook for you! Don't worry, I've helped Xiangling in the kitchen before, so it's safe to say that I come from good stock where food is concerned!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "One time, Shenhe ate too many Qingxin in one go and she was sick for days! And that's why I've got to take care of myself and not eat raw Qingxin. Hmm? How did I know about that? Aunty Cloud Retainer told me!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "This is amazing! It tastes just like Xiangling's cooking. It's like they say: The apple didn't fall far from the tree, mmm... Wait, no, two peas in a pod! You two are like two peas in a pod. Hehe, I'm always mincing up my words when I get too excited.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Sooo tasty! Next time you cook, lemme come too! I can help~',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "...Uh, do you always eat this kind of stuff? Maybe you should let me cook for you instead! If you're not eating well and you're still going out adventuring every day, one of these days you're gonna wear yourself out...",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "This is the day of your birth, and as is tradition, this calls for a bowl of longevity noodles. I got Xiangling to teach me how to make it, and I managed to put all the noodles in the water without breaking a single one! I also put a big plump egg in there, hee-hee! Come on, let's go, you've got to eat it before it goes cold. Wishing you a happy, healthy birthday and a long and prosperous life.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Eh? Did my spear just get lighter? ...It'd be great if it could get a little shorter, too...",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Wow! I might even be able to lift Xiangling's spear now! Yay~ Oh, I really wanna tell Master the good news!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Hehe, people always say "perseverance is a virtue," and I guess I know what they mean now! ...Hmm? "Patience is a virtue"? But... isn\'t patience the enemy of progress?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Huh. So that's what it feels like to be fussed over... Well, any growing or changing I've done is all thanks to you! And you know what they say — \"treat other people the way you want them to treat you.\" So it's my turn to keep you safe and sound now!!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Yuegui, you're up!",
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Stay put!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: "Don't be scared~",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Ready... Go!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Pain, pain, go away!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "Go get 'em, Yuegui!",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Pack everything up nice and carefully. Don't drop anything!",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Here you go~ I've packed it all into a bag for you.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Wooow! These'll last us for days!",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Uh-oh...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Gotta keep going...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: III',
      audio: '410003',
      text: "It's okay, I'm fine...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Come to Yaoyao!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Life is a gift, don't throw it away!",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: I',
      audio: '500001',
      text: "I can't look after you anymore...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Sorry, Master...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Spear getting heavy...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Ouch!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: 'That hurt real bad...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I'll take good care of everyone!",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "I'll lead the way. Follow me!",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Don't fear, Yaoyao's here!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'The adepti faithfully adhere to the contract that they have with Rex Lapis, and have thus defended Liyue for millennia.\\nWhen danger arises in Liyue, the adepti are sure to come forth, and they do show up from time to time when the land is at peace.\\nSometimes, they do so to punish those who harbor evil in their hearts, and sometimes they intervene to save the imprisoned. And if they happen to meet someone with a destiny intertwined with that of the adepti way, they will take them as disciples and teach them their arts.\\nAmongst the adepti, Streetward Rambler is among those who interact more with mortals.\\nShe has a great many disciples, the youngest of whom is named Yaoyao.\\nYaoyao is both talented and inquisitive, and while she is still very young, thus limiting her ability to fully take in what she has been taught and causing no small amount of innocuous mistakes in the process, she will in time become a most knowledgeable girl.\\nShe also possesses a gentle and caring nature, and she treats people with earnestness and generosity. Not only does her master favor her, but her senior disciple and other elders in her life, too, very much dote on her.\\nMost will never have the fortune to enter the adepti abodes in Jueyun Karst, but Yaoyao comes and goes between them both freely and often. Indeed, the love she receives from the adepti at her young age is quite an enviable matter.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "As the people of Liyue Harbor see it, Madame Ping is often found with Yaoyao by her side, the two seeming the very image of a loving grandmother and granddaughter.\\nIn truth, however, there is no blood relation between them, and Yaoyao is Madame Ping's — or should we say Streetward Rambler's — disciple.\\nWhen Yaoyao first became the adeptus' disciple, she was still too young to have learned to read and write, and so her master began by teaching her the etiquette of tomes of poetry on a daily basis.\\nAs she grew, Streetward Rambler would gradually add the rites of the adepti, their methods of self-cultivation, and her own spear arts into Yaoyao's curriculum.\\nThe voluminous nature of such teachings makes committing them to memory a challenge for Yaoyao, but her master does not overly fret about such things, for it is apparent to her that Yaoyao has indeed listened to those lessons.\\nWhile her spear's shaft is heavy and ill-aligned to a child's easy wielding, Yaoyao practices every day nonetheless.\\nAnd while books of poetry might be hard to memorize, she reads them daily nonetheless, to the point where she can expound on the relationship between full stomachs and righteousness in her sleep.\\nHaving initially resolved to be a sterner taskmistress, Streetward Rambler was relieved to see Yaoyao's earnest attitude, and thus relaxed her requirements a little.\\nThat Yaoyao genuinely treated her as her grandmother warmed the cockles of her heart greatly as well.\\nIndeed, despite being half the height of an adult, Yaoyao tended to Streetward Rambler's meals and fretted over her health when the hotter parts of the year give way to the cold, as if forgetting that headaches and fevers were not common problems for the adepti.\\nIndeed, Streetward Rambler came to feel as if she really had been blessed with a granddaughter, and from then on, she never said a strict word to the child ever again.\\nWhile she had not begun this relationship with any intention apart from taking a disciple, she now finds herself and Yaoyao inseparable. Which is alright, she supposes. Let the little one stay by her side for some time yet — she still has much to teach, after all.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'This story begins well before Yaoyao was even born. Her parents, preferring life out in the mountain wilds, chose to move away from Liyue Harbor and search for a quiet place near Qingce Village to live, building their own abode and living life in relative seclusion.\\nThere they lived in solitude by the mountains and waters, and their backyard had a small field in which they grew melons, fruits, and vegetables.\\nThe closest settlement to them was Qingce Village, and when they lacked for any daily necessities, they would bring the fruits of their field to the village and trade for what they required.\\nThis was the home to which Yaoyao was born.\\nThus did she gain the birds, beasts, and fish for companions while she was still a babbling babe, and thus did she take her first tottering steps in the radish field behind her house.\\nHer gentle, pure soul was first cultivated in this quiet and cozy garden.\\nLater, she would catch the eye of an adeptus and be taken in as her disciple.\\nAt first, her parents were not entirely willing to let their daughter live long-term in Liyue Harbor with said adeptus, for they feared that their innocent daughter, having long been used to life in the mountains, would find herself led astray by the bright lights of the big city.\\nBut Streetward Rambler\'s counsel ultimately brought them round:\\n"Perhaps solitude in the mountains shall indeed keep one from mortal stain, but such lonesomeness may not be what Yaoyao desires for her future. Let her have the chance to see the myriad faces of the world for herself."\\nOnly then did her parents give her into the care of the adeptus, and time has only demonstrated the wisdom of that choice.\\nIn Liyue Harbor, Yaoyao would become a much more outgoing person with the help of her master and a host of good friends. But when the festive season comes along, she does take leave of her master to see her parents at home.\\nIndeed, if one desired a good teacher for one\'s child, could there be a more ideal pick than an adeptus?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Madame Ping's old acquaintances will sometimes drop by to visit her, and during such times, Yaoyao will accompany her master and her master's guests in roaming the city.\\nHaving come from afar, these guests will often not only visit the stores and food stands, but also attend storytelling sessions or Liyue opera performances at Heyu Tea House.\\nOf course, being the large city that it is, Liyue Harbor has no lack of people who enjoy spending some downtime at the teahouse, including many outlanders who appreciate the cultures of other nations.\\nOnce, three outlanders, first-time visitors to Liyue Harbor, sat at the table beside that of Yaoyao and company. Having heard an opera about the adepti of Liyue, they began to discuss that very topic over tea and snacks.\\nUnable to get a word in lengthwise in the conversation between her master and her guest, Yaoyao succumbed to boredom, listening in on the nearby chat while eating some treats.\\nThe lady from Inazuma seemed to think that Liyue's adepti were not much different from the Guuji of the Grand Narukami Shrine, having charge over matters divine and literary alike.\\nThe visitor from Fontaine was of an obdurate view that the adepti were in the employ of the state apparatus. Had he met Ganyu, the Qixing's secretary before? Or did that nation simply have a similar arrangement?\\nThe adventurer from Mondstadt was for his part very taken with the legends of the adepti, for he had only heard the bards sing songs of the gods, but had never himself met one or any of their familiars.\\nUnable to resist, he asked the tea master if they had ever spoken to an adeptus, only to be disappointed by the reply:\\n\"It is but a story, for we mortals do not daily dwell in Jueyun Karst, and few are the opportunities to meet the adepti.\"\\nYaoyao, finding this statement to be incorrect, could not help but rebut thusly: \"That's not true. The adepti are among us. I mean, Uncle Moon Carver just said that the story was very interesting.\"\\nFor some reason she could not fathom, Madame Ping's guest stopped speaking altogether, and Madame Ping laughed, saying a few words to the tea master to change the topic.\\nYaoyao, however, did not understand: Why did people find the adepti very distant from their daily lives? The adepti were amongst them — they just didn't readily reveal themselves, that's all.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Not all people can be accepted and taken as disciples by the adepti — only those whose destinies are entwined with these blessed beings may become privy to their arts and ways.\\nYaoyao once asked her master: "Why do you say that our destinies are entwined? What does that mean?"\\n"It means that you and I have things in common that led to our meeting."\\nThis answer, of course, was akin to some overarching axiom in a book, crushing much meaning into very few words, and has by no means been easy for Yaoyao to wrap her head around.\\nYaoyao remembers that she had been playing in the mountains as usual when she first met her master.\\nAt that time, she was still living with her parents, and when she went out to play, she would speak to the stones and the clouds about her feelings. In her eyes, the flowers, birds, fish, insects, and the mountains, rocks, and rivers were all her precious playmates.\\nThat day, however, the stones and the clouds replied when she spoke, and thus overjoyed, she chatted with them throughout the entire day.\\nThen the adeptus recalled her mystical arts, and the illusory stones and clouds dissipated, revealing Streetward Rambler to Yaoyao in her true form — and yet, Yaoyao was not startled.\\nIt is the adepti way to protect the world and the people who live in it, and the adepti of Liyue do not merely defend humanity, but cherish also the things of nature. All such things are bound within their own natural cycles, and so long as one acts in concert with these cycles, all things will grow in their time and will not encroach upon one another.\\nYaoyao\'s treasuring of her playmates bore similarity indeed to the adepti and their care for all things, and it was this that drew Streetward Rambler\'s interest.\\nShame, then, that Yaoyao could not for the life of her comprehend the complexities of her master\'s reply, and thus did she lay the question aside for the time being.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "After following her master to live in Liyue Harbor, Yaoyao has packed her daily schedule to the very gills. Her mornings are for readings and lessons, afternoons are for spear training, and afterward, it is time for single-minded play!\\nPlay, her master said, is not to be underestimated, and for a child like Yaoyao, learning and play are both right and proper things to do.\\nIt has been during play time that she has encountered all manner of people, among them the captain of the Crux Fleet, the doctor at Bubu Pharmacy, and his little herb-gathering assistant. As such, she has been steadily gaining a larger pool of people to ask about anything she may encounter that she might not immediately understand.\\nShe also loves to explore the harbor area: Granny Shan's toy stall, the establishment — that is to say, Wanmin Restaurant — run by her senior disciple's family, the dockyards... If it may be explored, she would love to explore it.\\nAs such, she has seen many things that books cannot tell of, such as the sails of embarking ships rippling in the wind, or the full map of Liyue that may be found in Yujing Terrace — each one of these helps her perceive the vastness of the world around her.\\nSometimes, her idea of play will take her alongside her master to visit the Jueyun adepti. There she has heard many an ancient tale, and there she has learned that the truth of the past is far more perilous than any tomes may tell.\\nEach day, she learns a little something more, and each day, things change all around her — nothing remains quite the same as it once was in life.\\nThis is her favorite thing about Liyue Harbor.\\nLife here is like a long river, constantly moving forward at a great pace.\\nBy contrast, the days she spent with her parents are like a peaceful, quiet stream. The stream is wonderful, of course, and its gentle tread and slow rhythm has given her a great many warm memories.\\nThe great river is also good. She will take up its unceasing drive and work hard to become an adult who both her master and parents can be proud of.\\nAnd so wishing, she grows expectant, wishing to grow up.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Yuegui',
      title2: null,
      text: 'Streetward Rambler has acquaintances all across Liyue, and even early on, she had paid many of them a visit, saying that her newest disciple\'s training was not quite complete yet, and asking them to take care of the young girl should they encounter her.\\nHer original intention was simply to introduce her student and ask that they help teach Yaoyao further, that her eventual learning might increase.\\nYaoyao\'s clever and caring manner, however, proved more lovable than Streetward Rambler had expected, and Cloud Retainer would take the request to heart.\\nBefore either master or pupil had realized it, Cloud Retainer had already completed the creation of a wondrous machine rabbit.\\n"Well then, Yaoyao, one purposes to give this to you. Should you encounter any danger, call upon it, and it shall answer."\\nYaoyao was very taken with this cute rabbit, naming it Yuegui and taking it everywhere with her.\\nHaving given this gift, Cloud Retainer would seek out the little girl\'s master to say, and not without pride, that:\\n"One should inform you first that this device has another function. Should you ever be unable to find Yaoyao, you need only call out, \'Yuegui!\', and her location shall be made known to you."\\n"Nonetheless, one counsels you not to overuse this feature, for when the child grows older, she will desire her own privacy, and may yet take umbrage to your constant calling upon her. Now, take one\'s loose relationship with one\'s pupil Shenhe for example..."\\n"Oh, not to worry. I understand, Cloud Retainer."\\n"And it is good that you do. In any case, Yuegui shall alert us if anyone should try to do her ill without our knowledge — any such churls shall soon need all the luck they can get."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "\"Why did I receive a Vision?\"\\nThis question troubled Yaoyao quite a bit in the days that directly followed her receiving one.\\nDid the gods want to reward her for the good deeds she had done? Or was this because she had been a good and respectful pupil?\\nSpeaking of which, her senior Xiangling and Aunty Cloud Retainer's student Shenhe both had Visions as well. So, was this because the gods recognized the adepti, and so they would, as a matter of course, also extend this acknowledgment to an adeptus' students?\\nBut on further consideration, none of these guesses really made much sense.\\nIt was with a sigh that Yaoyao found herself sitting on the slopes behind Liyue Harbor, hugging a dog that had followed her up the incline.\\nThis was hardly the first thing she had found incomprehensible since leaving her parents' side, and she had, by and large, decided that her doubts were unavoidable, and could wait till she got older, for surely they might clear up by then!\\nBut since she now had a Vision, an item that represented divine acknowledgment, she could not betray such hopes.\\nAs a disciple of her master, she would follow her example and protect the people. This meant that she would not only have to care for her master and senior disciple, but also extend care to her family and friends, and extend universal love to all people. Ah, she still had such a long way to go. Nothing for it, then — she'd hang on for a bit longer during spear practice tomorrow, and write one extra page into her calligraphy copybook too.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
