export const kiraraVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "I'm ___, a courier for Inazuma's Komaniya Express. Rest assured, there's no destination I can't deliver to! Huh? My tails? Oh, I have 'em because I'm a youkai — a nekomata, to be specific.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Packages',
      audio: '1101',
      text: "I wonder what's inside this package... No no no, no peeking at my customer's stuff...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Orders',
      audio: '1102',
      text: "Let me see... Okay, let's get going. The next location on my list is really far away.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Work',
      audio: '1103',
      text: "Whoa, the scenery here is wonderful. Hehe, I've landed the perfect job.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Agh...! Now my fur's all wet. Do you want a box to hide in too?",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Meeoww! Phew... I almost forgot how to speak like a human...',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "It's so cold, my tails are turning into ice pops... I should've stayed inside near the fireplace. My fur won't get singed as long as I don't get too close to it, right?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'The sunlight feels really cozy. Napping in a tree would be nice... Ohh, just the thought of it is making me sleepy.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'Oh no! The smaller parcels are gonna get blown away!',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'In the Desert',
      audio: '1206',
      text: "Sand's getting wedged into my paw pads... Feels kinda weird...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Morning',
      audio: '1001',
      text: "Good morning! I saw that you hadn't woken up yet, so I went out and got you some food. Oh, don't worry, there aren't any squirrels or finches in it. Even though they're delicious too...",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "*yawn* Let me sleep a little longer... I can't even lift my tails right now...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening, I'm all ready to head out. Huh? What do you mean it's time for bed? Nighttime's when I'm the most alive! I can travel faster and see better, and there are fewer people on the road, too.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: '1004',
      text: "Good night, sweet dreams! That said, without two tails to bother you at night, I'm sure you have sweet dreams all the time.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Paw Pads',
      audio: '2001',
      text: "My boots? Oh, they're my paws, actually. I can use my youkai powers to turn them into human feet, but I feel way more at ease walking with my claws and paw pads. Um, don't touch them, please! They're ticklish!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About ___: Name',
      audio: '2005',
      text: 'Granny named me ___. Back when I still had only one tail, Granny would give me head pats and chin scratches and tell me how bright and pretty my eyes were.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'About Us: Journey',
      audio: '2003',
      text: "You travel far and wide, and I deliver packages all across the world. That makes us similar, don't you think? But although we both travel from one place to the next, my travel expenses are covered, while you have to pay for everything out of pocket... Huh? N—No! I didn't mean to brag!",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'About Us: Encounters',
      audio: '2002',
      text: "I've met all sorts of people through delivery work. Some have become regulars of Komaniya Express, while others have become my friends... and I feel so lucky for that. Each delivery ends with the package reaching its destination, but our bonds with each other live on. If you ask me, friendships between youkai and humans aren't all that difficult to form.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About the Vision',
      audio: '3001',
      text: 'I still remember the first time I tried shape-shifting into human form using my youkai powers, thrilled at the thought of finally being able to experience the human world for myself. And before I knew it, my Vision had appeared at my waist. Hmm... Did this god have a profound desire to travel to all sorts of places, too?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Hunting',
      audio: '3002',
      text: "Weapons forged by humans aren't bad at all, but I'd rather rely on my feline instincts sometimes. I mean, when there's a little finch right before your eyes, don't you just want to creep up from behind, crouch really low on the ground, wait for the right moment... then pounce right on it? Not even successful package deliveries can compare with the satisfaction I get from hunting down prey!",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Something to Share: Box',
      audio: '3005',
      text: "Granny told me that this was my favorite box to sleep in when I was little. Hehe, it's kinda funny — back then, all I knew about Komaniya Express was that their boxes were big and comfy, and if you'd told me that one day, I'd make a living out of giving all their boxes away to other people, I'd have never believed you. Hehe, although it is definitely more of a squeeze trying to fit inside their boxes these days... What? What do you mean, all the stuff in there already...? Ugh, no, I mean their empty boxes! I'd never open a customer's parcel!",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Interesting Things: Tree Houses',
      audio: '3003',
      text: "Did you know that some houses in Sumeru are built atop trees? Oh, it'd be so nice to bathe in sunlight all day without having to climb down for food. Huh? You already knew? Okay then... do you also happen to know how they're built? I have claws and all, and even so, I felt really exhausted climbing up one of those tall trees to deliver a package. How were the building materials and furniture delivered up there when the people of Sumeru didn't even have claws to begin with... I don't get it...",
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'Interesting Things: Big Houses',
      audio: '3004',
      text: "I got to see lots of big houses while delivering packages, ones that were even bigger than Granny's house! Palace this, temple that... And there were countless smaller rooms in each of them. Wouldn't living in such a huge place make you feel a little empty inside, though? Having a place to eat in the morning, a place to sunbathe at noon, and a little box to rest in at night is more than enough for me. Huh. Does that mean big houses are just larger boxes for humans?",
      tips: '',
      tasks: null,
    },
    '23': {
      title: 'About Yae Miko',
      audio: '4001',
      text: "Lady Miko is a widely renowned kitsune youkai in Inazuma, so it's natural for young youkai like myself to approach her with reverence. But contrary to my expectations, she was surprisingly amiable. She even came to visit me in person and taught me lots of useful stuff about how to survive in human society! Things like proper human etiquette, ways to approach people, and different fried tofu recipes... Huh? That last one was just for her?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About the Raiden Shogun',
      audio: '4002',
      text: "Parcels sent to Tenshukaku are all packaged intricately with multiple layers of wrapping. Maybe that's what they call a package fit for the Almighty Shogun. Some of them smell really good... I wonder what's inside.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Shikanoin Heizou',
      audio: '4003',
      text: 'I crossed paths with that detective a long while back. Once he learned that I was a nekomata, he started asking me to investigate the whereabouts of missing cats. I was happy to help at first, but then I\'d hear the cats say things like "I just want to see the outside world!" or "I get so bored when I\'m at home," I felt bad for them. So I lied, telling him that I hadn\'t seen any cat at all. But it seemed like he could see right through me...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Kujou Sara',
      audio: '4004',
      text: "I've always wanted to have a chat with the Lady Tengu. Maybe it's because she's the general of the Tenryou Commission, but I find her quite intimidating, so I've only ever watched her from afar. I—I'm just curious about her wings, you know? Are they ever an inconvenience? How does she deal with shedding feathers? Mm... Speaking of the feathers, I think lining my box with them would be super comfy.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Arataki Itto',
      audio: '4005',
      text: "He's an oni, but he gets along with humans perfectly — he even has his own gang! Oh, I'm so jealous. Maybe I should go ask him for some advice.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Lyney',
      audio: '4006',
      text: "So I met this magician in Fontaine who could make anything disappear, then make it reappear out of thin air! He must've used some kind of youkai power to make that happen, right? Hmm... Is he a youkai too, then?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Chiori',
      audio: '4007',
      text: "She's really nice to me. I often ran into her in the past when she was out researching ways to make fabrics and develop color palettes. She was always worried that I'd leave claw marks all over her beautiful textiles, but come on, why would I do that to her? She's running a store in Fontaine now and sometimes asks me to deliver stuff to her. Hehe, she even helped me tailor the clothes I'm wearing now.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Granny told me many stories when I was a little kitten. About the youkai of Inazuma, the festivals held in the city, the delicacies of other nations... I would curl up on her lap and listen until I fell asleep. Even now, I still can't tell which parts of the stories were real, and which were a part of my dreams...",
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Being a courier is the perfect job for me. The Lady Kitsune told me that those who don't work can't fit into human society, and I'm not having any of that! That's why I've decided to take every delivery seriously. I—I'm not going back to the boonies, even if it means I get to be a Great Youkai or whatever!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Maybe it's because I look like an easy target, but I often run into bandits when I'm on the road — but I always manage to chase them off! I don't go all out, though, because if the company was held liable for the injuries I caused... Well, I'd get canned!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Whenever I set foot in a new city, I always climb somewhere high up and gaze down at the scenery. Sometimes a breeze will pick up and the petals will float like Crystalflies from one end of the street to the other. And when the sun begins to set, I'll find a nice spot to watch the city lights come on. From high up above, they look like flickering specks of sunlight dancing beneath the forest shade at noon. I could stay up there all day if I wasn't in a hurry to deliver my packages... *sigh* I wish I could take Granny with me and show her all these things.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '34': {
      title: 'More About ___: V',
      audio: '5005',
      text: "It's really important to enjoy your life! In the last few days of a long-distance trip, or on a night when all my work's done, I'll always have a hearty meal at the busiest restaurant, then look for the most comfortable rooftop and feel the breeze on my face until I fall sound asleep... There are so many little joys in the world that deserve to be savored, and it'd be such a great loss if I didn't relish every one of them. Which is why I always pick the bones clean when I'm eating fish!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "I like delivering packages across the world. Whenever I see an address I've never been to before, I get so excited that I can't sleep. I mean, I just wish that I could be there right this instant. I grew up surrounded by forests and shrubs, and it gets boring pretty quickly. But things are different out here. There are so many things I've never seen before, and it feels like there's something new waiting for me around every corner!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: "___'s Troubles",
      audio: '6002',
      text: "The life of a human may be full of surprises, but there are so many rules too. Humans can't sleep on a roof, catch fish from a pond, or find a nice place to scratch and sharpen their claws... But as soon as I revert to my original form, no one bats an eye over any of these things. The trouble is that my nekomata form attracts a lot of attention, so I can't just walk into a restaurant and order food the way a human would...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food',
      audio: '6005',
      text: "When I was still a cat, I loved everything Granny made for me — I could gobble up an entire bowl in one go! As for now... Sashimi Platters are my go-to staple! With tender and fresh fish directly served on a plate, I don't even have to go through the hassle of removing the bones and scales! But the restaurant staff always gives me this strange look whenever I start working my way through the fish heads...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Once, I was catching fish by the ocean when a crab caught me off guard and pinched my tails from behind. It hurt so bad, I thought they were gonna get snipped off! Ugh, why do people like eating crab anyway? They have so little meat, and their shells are so unbelievably thick — I can't even open them with my claws. Oh, and I can't stand anything hot either. I could hardly believe it when I learned there's a dish called \"Butter Crab.\" How do humans manage to eat something so hard AND hot?",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Whoa, this is amazing! I've never tasted anything like this before! You... you wouldn't happen to be the great youkai of cooking or something, would you?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Mm-hm, delicious! Is there more? I wanna take some with me on the road!',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Um, this... reminds me of life in the wilderness...',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! It doesn't matter if you're a human or a youkai, coming into this world is always worth celebrating! If you want, I can take you to the place I grew up in. It's not bustling with people, and it's not all that interesting, but it always makes me feel relaxed. Oh, and I'll let you sleep inside my favorite box, too! Having a nap inside it always feels great!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Ooh! I can feel my youkai powers growing!',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Huh? Are my tails getting longer too?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'My body feels lighter! I feel like I could deliver ten different packages in one go!',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Whoa... With this much power, I think even that kitsune youkai might need to watch out... Hehe, just kidding! It's not a competition, after all. I'm just happy as long as I get to keep every customer's package safe. And you too, for always staying by my side. Oh, by the way, wanna try touching my tails? I'm pretty sure they've gotten longer!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Phew!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Scratch that!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Coming through~',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Express delivery~!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Service with a smile!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Sign here please~ Meow!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Wow! I've never seen half the stuff in here before!",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Did someone drop their package?',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Maybe I could curl up inside this box...',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Gotta watch the packages...',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Gotta find another route...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Meow...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Come hide in my box!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I'll lend you a hand!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Customers... are still waiting...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: II',
      audio: '500002',
      text: "I'll be... in my box...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: III',
      audio: '500003',
      text: "I'm gonna get fired...",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Ow!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'My tails!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Hey! Watch the packages!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Anything you need delivered?',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Thank you for choosing Komaniya Express!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'All-expenses-paid travel? Count me in!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'If you ask anyone in Inazuma which delivery company is the most reliable, the name "Komaniya Express" will surely be mentioned.\\nIf you were to continue the line of inquiry and ask just what about their service left the deepest impression, you would see a smile creep onto their lips as they tell you of a certain special courier...\\nThat adorable, vivacious young youkai with two twin twirling tails. After you thank her for delivering your package, she will bow deeply while wearing an expression of unadulterated bliss, as though she was the one receiving the gift.\\nIf you\'re willing to spend the time to leave a 5-star rating on the feedback board or give her a few snacks, you may even see stars of joy shoot from this youkai\'s eyes as her tails swish back and forth.\\nAh! But the same people who tell you this will also warn you that this nekomata isn\'t some weak little thing you can pick on. If you have designs on packages that don\'t belong to you or get carried away and try to touch her tails... Well, then you\'ll have to face the consequences.\\nAfter hearing all this, it\'s hard to resist going to Komaniya Express...\\n"Excuse me, I have a package to deliver, and I was hoping the neko—"\\nWithout waiting for you to finish, the owner turns around and shouts "___! Another one for you!" as though it were an everyday occurrence.\\nAt that moment, a beaming girl will bound towards you, quickly fix her hair and adjust her clothes, and say with a smile—\\n"Welcome, and thank you for choosing Komaniya Express!"',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '___\'s earliest memories are of wandering the wilds of Inazuma.\\nBack then, she was a nameless kitten with but one tail, and woke every morning with an empty, growling stomach. After a stretch, a yawn, and a single "meow" as though to bellyache about her circumstances, she would begin to hunt for breakfast. The menu often included finches that had let down their guard, or overly curious young fish too near the shore.\\nWhenever she encountered adventurers out in the wilderness, she would lie down at a safe distance and watch intently as they fished out all kinds of marvelous instruments from their packs. Fwoosh! Suddenly there was a fire roaring. Bong! A strange cauldron was set over the fire. And then, with a bubbling sound, an intoxicating scent would occasionally waft over on the breeze...\\nObserving this process with wide eyes, to her it was as if she had witnessed magic. Thus a yearning for human society began to flutter about in her chest, as though a butterfly had flown into her heart.\\nDuring a frigid winter night with the biting winds howling, ___, still a small kitten, was frozen to the point of being unable to feel her tail.\\n"Gotta find a warm place to hide. Even a hollow in a tree will do..." She thought to herself. But when she was able to look up, she saw a cluster of warm lights flickering not too far away...\\nThis was the first time ___ entered a human home, and while she was curious about everything around her, she was also frightened. The owner of the house seemed not to notice the kitten that had found its way into her home, but ___ paid little notice. She found a small square box near the entryway into which she snugly fit, and into it did she sit, falling asleep almost immediately.\\n"I\'ll just rest the night, just one night..." were her last thoughts before dreams took her...\\nYet when she awoke, she found a warm fire crackled away next to her, and beside it was a fragrant bowl of nekomanma. Directly across from her was an old lady in the middle of knitting a woolen sweater. The old lady seemed to be trying to say something, as though encouraging her to eat. With her tail down and guard raised, she cautiously took a bite of that aromatic nekomanma in front of her that she was so curious about...\\nIt was the most delicious thing she had ever eaten, to the point she began to doubt whether or not she was still dreaming!\\nAnd so, she stayed in that cozy little home for one winter after another, and heard story after story from that kind old woman...\\nOn occasion, when ___ thinks back to that first night, she\'ll cock her head and ask herself:\\n"Strange... what was I thinking about before I fell asleep again...?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '___ enjoys human cities, with their fireworks, marketplaces and scattered eaves. There is always something she\'s never seen before, waiting to be discovered.\\nWhen she first became a nekomata, she used her youkai powers to enter Inazuma City in a human form. She eagerly explored every nook and cranny in the city, and not even the roof of the Almighty Shogun\'s Tenshukaku was immune from her curiosity. This is the reason that the Tenryou Commission is one of the addresses she is most familiar with.\\nThough the Tenryou Commission taught her rules like "don\'t climb on other people\'s roofs" and "don\'t eat the ornamental koi", then she learned "how to be a good youkai in human society" from none other than the Lady Kitsune of the Grand Narukami Shrine. ___ has caught the eye of "the greatest and coolest youkai," as she calls her, and Yae Miko, for her part, has been willing to impart all her experience upon her lively and interesting junior. Upon learning that ___ felt the streets and alleys of Inazuma City were priceless treasures, Miko recommended that she seek employment at Komaniya Express.\\n"If you want to blend into human society, then you must work like an ordinary human. This is most important." Thus spoke the Lady Kitsune.\\n"Ah, yes," the illustrious priestess appended, "Packages addressed to Guuji Yae at the Grand Narukami Shrine must be given the utmost priority. This is even more paramount than what I just said before!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Sometimes, bandits with less than honorable intentions will covet those bulging parcels. Hiding beside the paths that the deliveries must take, they carefully eye the passing couriers.\\nIf the delivery person looks tough, or is in a group, the bandits won\'t risk it. After all, it\'s just another day with an empty stomach at most.\\nBut when they chance upon a courier like ___, appearing delicate and traveling alone, their hearts leap with joy and anticipation. They can nearly taste the Mora that has fallen neatly into their laps.\\nWhen ___ passes, the bandits emerge from concealment and surround her, maliciously blocking her way forward.\\n"Huh? Do you need something?" ___ stops uncertainly.\\nUpon closer inspection, this young lady has two tails. Strange, to be sure, but she looks frail and her face is kind — the perfect prey, through and through. Even better, the pack she carries is bursting with thick packages. Truly, this is a good day for a robbery!\\n"Uhm... If you have packages you\'d like to deliver, please visit our Inazuma City offi—"\\nMost bandits don\'t even let her finish before brandishing their blades. The more polite sort will attempt to persuade her to put down her delivery pack willingly for her own safety. The desperate will simply swarm her, hands outstretched to plunder.\\nBut whatever their methods, the result is always the same—\\nThe next morning, several large boxes will have appeared on the doorstep of the Tenryou Commission. Under the "Type of Goods Delivered" section of the delivery slip sealing the packages, a single word will be written: "Meanies."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'When she first moved to Inazuma City, ___ would often lie by the roadside, observing the pedestrians passing by.\\n"Oh! So this is how human girls dress..." Her wish to join human society made her very conscious of her own outfit, and whether or not it was similar to those around her.\\nIn the springtime, girls would often pluck a flower to place behind their ear or in their hair... Soon after, a special accessory became quite popular... Then everyone began flocking to some particular style of bracelet...\\n___ accepted every style without question, imitating every trend as she saw it. She never thought there was anything wrong with what she was doing, just that all those accessories would occasionally restrict her movement and make it hard to climb up and down. It was so different from being a kitten out in the countryside!\\nThis persisted one day, when she was delivering a package to an old customer named Chiori, and she received a serious dressing down...\\nAt the time, ___ had politely knocked on the door before gently pushing her way inside. But she couldn\'t have known that Chiori would glare at ___ as though she were a cat that had fallen into a bucket of paints...\\nThis Inazuman fashion designer who had opened a famous design label in Fontaine was already quite familiar with ___, and so she spoke directly—\\n"Utter insanity! What did you do on the way here? Fight Specters? What kind of garbage have you covered yourself in? How did that garish flower get stuck in your hair? It\'s assaulting my eyeballs. Really, the only thing on your entire body with a speck of taste is those shoes..."\\n"Um, Chiori, y—you know th—those are just m—my feet..." ___ managed to stammer nervously.\\nChiori buried her face in her hands, and immediately picked up her scissors and some cloth before pulling ___ into a changing room.\\n"Now don\'t you misunderstand! It\'s just that I\'d be embarrassed to let anyone see you walking out of my shop looking like THAT!"\\nThe dressing down became a dressing up, and after the sound of snapping scissors and swift needlework faded to silence, ___ had the outfit she now wears today.\\nFrom then on, she had a new task when delivering packages: answering client\'s questions about just where she got that delightful outfit. Thus did the reputation of Chiori\'s shop spread far and wide.\\n"Hmph. I told you my judgment was immaculate." On this delivery run to Fontaine, ___ found her friend in seemingly much better spirits.\\n"Other than the clothing orders, is there anything else?" Inquired Chiori.\\n"Yes, there is, it\'s just that..."\\n"Come on, out with it, stop beating around the bush!"\\n"The customers are asking... if you, that is, your shop... Can you release a shoe design that looks like a cat\'s paw pads?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'To ___, every delivery is a priceless treasure. Each package takes her to different places, and allows her to see all kinds of scenery.\\nAfter work, ___ would go to the "Undelivered Packages" section of the warehouse, and see all the myriad reasons that packages couldn\'t be delivered to their recipients.\\n"Filled in wrong address," "recipient moved," "wrong name"...\\nEach stranded package was like a fish bone lodged in her throat, choking her slowly. Thus, she began to quietly record the details of each package, and used her routes during work and spare time to discover the whereabouts of each recipient.\\nThis resulted in the reputation of Komaniya Express increasing by the day, as customers rushed to praise the reliability and quality of their service: No package was undeliverable.\\nWhen the owner of Komaniya Express heard of this, they spent all night designing a new title to issue to ___: Gold Level Courier.\\n"Actually, when I saw that the \'Undelivered Packages\' section was empty, I thought we\'d been robbed..." confided the owner.\\nFor ___, her greatest happiness is the moment she delivers a package into the hands of the recipient. After a long day making deliveries, she likes to climb to a high place, taking in the sights of the city while listening to the sounds of mirth drifting upward from the markets.\\nThis is when she recalls her days as a kitten, listening to stories on the lap of that old lady. The twists and turns and sudden reveals, the fantastic beasts and monsters, all gently follow ___\'s memories like the cool evening breeze, blowing gently into her heart.\\nAnd just like the old days, she gently closes her eyes as the stories intermingle with her dreams, welcoming the arrival of tomorrow with contentment.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Mystery Packages',
      title2: null,
      text: 'Some clients of Komaniya Express may be surprised to discover a mysterious package at their door. Most of these packages are small and exquisite, and beautifully decorated.\\nCupping the parcel in their hands and shaking their heads, they might think it strange, as they haven\'t bought anything recently, nor is there any writing on the package. But they may have already forgotten that in the not-too-distant past, they gave some snacks to that courier with two tails.\\nEach package usually contains a lovely little gift, such as a dried flower of the Nilotpala Lotus, a Starconch ornament, or if the household has young children, a Scarab with peculiar patterns on its shell!\\nThese are all items that ___ has collected while out on her deliveries. To her, each is a novel and fascinating treasure, and perfect as thank-you gifts. Unfortunately, the rules of Komaniya Express forbid any transactions between employees and clients. Thus, ___ must make each small box herself, adding cute decorations, and quietly placing them on the recipients\' doorsteps.\\nHowever, the beneficiary of by far the most "mystery packages" is a small home in the Inazuman countryside...\\nThough ___ is quick to say she never wants to go back being some "great youkai" roaming the mountains and valleys, whenever she has time, she will always run back to that old house from that frigid winter\'s night. Leaving a present at the door, if she happens to find the old woman sunning herself in the yard, she\'ll immediately return to being a cat. "Meow, meow," she\'ll call, jumping up onto the woman\'s knees, curling up into a ball and pouting for attention.\\n"Ah! Back, are we, ___?" The old woman smiles and laughs. She doesn\'t know that this little cat is already a renowned courier. All she knows is that she often goes out to "play" for ever longer periods.\\n"You really are growing up so fast. I remember when I found you in the box, you were such a tiny little thing..." Scratching ___\'s head, the old woman fishes out a round, shimmering pearl and places it on her paw pads.\\n"See? This is that Sango Pearl from the story. Now, I don\'t know who it\'s from, but there it was on the doorstep, along with some snacks, too." The old woman also quietly observes to herself: "When I wake up, the house is so clean and orderly, and breakfast is already prepared. How very odd..."\\n"Why, you haven\'t grown into a youkai who takes care of me in my old age, have you, little cat?"\\nWhenever ___ hears this, she stretches innocently, letting out a contented yawn as she pretends to have no idea what the old woman is saying.\\nAfter speaking, the old woman falls silent and just smiles warmly. The two of them then continue to enjoy a leisurely afternoon bathed in sunshine.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'One night in the depths of midwinter, ___ was lying down by the coals, taking a nap. But try as she might, she simply couldn\'t sleep well.\\nThe charcoal had long burned out, and even the smoldering embers had gasped their final breath as the chill wind rattled in through cracks in window frames and seeped under the doors. ___ involuntarily curled up tightly, hugging her tail close. Lately, her tail was always itchy and restless, and no matter how much she licked it, it was never enough to calm it.\\n"Strange, Granny left this morning, she\'s been gone way too long..." she quietly mewed to herself.\\nThe final lingering ember became darkened ash, and even the residual warmth it had provided was snuffed out. ___ stretched out and looked out uneasily at the snowflakes falling outside the house, and then quietly leaped out the window.\\nThe snowflakes under her feet were chilly, and her paw pads soon ached from the cold. Climbing onto the roof, she gazed out towards the city. But the moon was totally obscured this night, and the surroundings were pitch black without even a speck of light.\\n"I remember there was a really, really tall tree nearby..."\\n___\'s tail seemed even more anxious than she was. As she climbed, it repeatedly refused to obey her mental commands and nearly caused her to fall.\\nThe tree stretched ever upward, so tall it seemed without end. ___ did not think about just how high she had climbed. Instead, stories of youkai and humans raced across her mind. It seemed as if she wasn\'t climbing a tree but pursuing days gone by, and if she was but a step too slow, all might slip away forever...\\n"Faster, just a bit faster..."\\nFinally, she reached the crown of the tree, and all the world lay spread beneath her. In the distance, a dazzling light suddenly lit the blackness before her eyes like a firefly — the light from the city at night.\\nIn that moment, it was as if something dormant in ___\'s heart was ignited, and all the fantastical stories of the past had finally become reality, a thousand rays of shimmering light streaming into that galaxy of fireworks. The stories that had once seemed so far away were now so close she could almost reach out and touch them, and she now yearned as never before to bask in that glow.\\n"Ah! I see her!"\\nSomehow, an unseen power helped ___ pick out the one person she desired to see amongst the dazzling stream of lights.\\nWhen she safely alighted back on the ground, the clouds parted and the moonlight cast her shadow upon the snow, a shadow that now boasted two tails...\\n"Are you sure you don\'t want to stay the night? The snow has only just stopped, and getting back won\'t be easy," urged the landlord.\\n"No, no, I couldn\'t! I have a little cat at home, waiting for my return, haha..." laughed the old woman as she stood before the entryway.\\n"If that\'s the case, I\'ll take you back!" A young female voice suddenly rang out from outside.\\nThe landlord and old woman peered outside, and there they saw a youthful lady with two restless tails, and a shining Vision dangling from her waist.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
