import { aetherVL } from '../../voice-lines/mc/aether';

const aether_pyro: Character = {
  id: 'aether-pyro',
  rank: 5,
  name: 'Traveler',
  element: 'Pyro',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Pyro Traveler Boy',
  release: 1735758000,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

const aether_hydro: Character = {
  id: 'aether-hydro',
  rank: 5,
  name: 'Traveler',
  element: 'Hydro',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Hydro Traveler Boy',
  release: 1690146000,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

const aether_geo: Character = {
  id: 'aether-geo',
  rank: 5,
  name: 'Traveler',
  element: 'Geo',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Geo Traveler Boy',
  release: 1601244000,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

const aether_dendro: Character = {
  id: 'aether-dendro',
  rank: 5,
  name: 'Traveler',
  element: 'Dendro',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Dendro Traveler Boy',
  release: 1657659600,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

const aether_electro: Character = {
  id: 'aether-electro',
  rank: 5,
  name: 'Traveler',
  element: 'Electro',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Electro Traveler Boy',
  release: 1626814800,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

const aether_anemo: Character = {
  id: 'aether-anemo',
  rank: 5,
  name: 'Traveler',
  element: 'Anemo',
  weaponType: 'Sword',
  region: 'OTHER',
  specialProp: 'FIGHT_PROP_ATTACK_PERCENT',
  bodyType: 'BOY',
  icon: 'UI_AvatarIcon_PlayerBoy',
  birthday: [0, 0],
  route: 'Anemo Traveler Boy',
  release: 1601244000,
  EN_VA: 'Zach Aguilar',
  JP_VA: 'Horie Shun',
  VL: aetherVL,
};

export {
  aether_anemo,
  aether_dendro,
  aether_electro,
  aether_geo,
  aether_hydro,
  aether_pyro,
};
