export const aloyVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Aloy_Hello',
      text: "___ here. I don't know this world, but my arrows are sharp and my bow's ready. If your party needs help, I'll do what I can.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Moving Out',
      audio: 'VO_Aloy_Chat_-_Moving_Out',
      text: "Come on. Enough standing around, let's keep moving.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Help',
      audio: 'VO_Aloy_Chat_-_Help',
      text: "Let's get going. There are people who need our help.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'When It Rains',
      audio: 'VO_Aloy_When_It_Rains',
      text: 'Rain. One way to wash off the grime.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'After the Rain',
      audio: 'VO_Aloy_After_The_Rain',
      text: "Sky's running out of rain for now. Time to dry off.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: 'VO_Aloy_When_It_Snows',
      text: 'The world always seems quieter when it snows.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: "When It's Windy",
      audio: 'VO_Aloy_When_It\'s_Windy',
      text: "Wind's kicking up again. Feels good to breathe it in.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: 'VO_Aloy_When_The_Wind_Is_Blowing',
      text: 'Wind is really whipping now. My face feels raw.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: 'VO_Aloy_Good_Morning',
      text: "Morning. World's starting to stir again. Me too, I guess.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: 'VO_Aloy_Good_Afternoon',
      text: "Day's half over, but we still have a lot to do.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: 'VO_Aloy_Good_Evening',
      text: "Sunset. We'll be under the stars soon.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: 'VO_Aloy_Good_Night',
      text: "Night's here. Time to rest, unless we're going on by starlight.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___',
      audio: 'VO_Aloy_About_Aloy',
      text: "I grew up an outcast, and it wasn't much fun. Even though I'm a stranger here, people are friendlier than the tribe that was supposed to raise me. It's... nice.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Action',
      audio: 'VO_Aloy_About_Us_-_Action',
      text: "Everything I do is in the service of life, not death. That's why I'm here with you.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Oath',
      audio: 'VO_Aloy_About_Us_-_Oath',
      text: "An oath seems like a formality. But if you want mine, you've got it.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About Us: Moving Forward',
      audio: 'VO_Aloy_About_Us_-_Moving_Forward',
      text: "I'll do whatever it takes to finish this with you. I won't hesitate. I won't falter.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: 'VO_Aloy_Something_To_Share',
      text: "If I have to share something, it'll be my bow... in the service of people who need the help.",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: 'VO_Aloy_Interesting_Things',
      text: "This land has a past full of secrets, just like my world. I'll uncover all of it, if I have enough time.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'More About ___: I',
      audio: 'VO_Aloy_More_About_Aloy_-_01',
      text: "I'm not much for talking about myself. The mission is what's important.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'More About ___: II',
      audio: 'VO_Aloy_More_About_Aloy_-_02',
      text: 'I never had parents. But a man named Rost raised me. He was stern, but kind and generous. And he trained me well. I miss him.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '20': {
      title: 'More About ___: III',
      audio: 'VO_Aloy_More_About_Aloy_-_03',
      text: 'I spent my whole life looking for my mother and never found her, not really. But I found ancient messages from the woman I was... cloned from. It felt like she knew me. And how to inspire me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'More About ___: IV',
      audio: 'VO_Aloy_More_About_Aloy_-_04',
      text: "When I grew up, I didn't have any friends. Later in my travels, I made some. But I left that world before we could grow close. That's why I'm glad to have spent time with you.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '22': {
      title: 'More About ___: V',
      audio: 'VO_Aloy_More_About_Aloy_-_05',
      text: "Trust doesn't come easy for me, but I know I can trust you. You're a true friend, and I don't say that often.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '23': {
      title: "___'s Hobbies",
      audio: 'VO_Aloy_Hobbies',
      text: 'Not sure if I have a hobby, unless you count reading things from the past. So, history... I guess?',
      tips: '',
      tasks: null,
    },
    '24': {
      title: "___'s Troubles",
      audio: 'VO_Aloy_Troubles',
      text: "One world needed saving. Now another. There's never time to rest.",
      tips: '',
      tasks: null,
    },
    '25': {
      title: 'Favorite Food',
      audio: 'VO_Aloy_Favorite_Food',
      text: "I'm not picky. Anything's better than traveling on an empty stomach.",
      tips: '',
      tasks: null,
    },
    '26': {
      title: 'Least Favorite Food',
      audio: 'VO_Aloy_Least_Favorite_Food',
      text: 'Had an Oseram stew once that was so thick you could pave a road with it. Ugh.',
      tips: '',
      tasks: null,
    },
    '27': {
      title: 'Birthday',
      audio: 'VO_Aloy_Birthday',
      text: "Never put much stock in birthdays. Where I come from, it's a time to celebrate your mother, not yourself. Even so, I wish you a, uh... happy day.",
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Aloy_Feelings_About_Ascension_-_01',
      text: "All right. Feels like we're making progress, but we can't stop now.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '29': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Aloy_Feelings_About_Ascension_-_02',
      text: 'Getting better. Getting stronger. Always a good thing.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '30': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Aloy_Feelings_About_Ascension_-_03',
      text: 'No matter how good a hunter you are, you can always get better. Never rest. Never stop learning.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '31': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Aloy_Feelings_About_Ascension_-_04',
      text: "When we started out, you were just another stranger in a world I didn't understand. But after everything we've been through, I can say this for certain: My bow is yours, now and always.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '32': {
      title: 'Elemental Skill: I',
      audio: 'VO_Aloy_Elemental_Skill_1_01',
      text: "This'll pack a punch!",
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'Elemental Skill: II',
      audio: 'VO_Aloy_Elemental_Skill_1_02',
      text: 'Got something for you!',
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Elemental Skill: III',
      audio: 'VO_Aloy_Elemental_Skill_1_03',
      text: 'Ever seen one of these?',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Elemental Burst: I',
      audio: 'VO_Aloy_Elemental_Burst_01',
      text: "You're stuck now!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Elemental Burst: II',
      audio: 'VO_Aloy_Elemental_Burst_02',
      text: 'This is a new one.',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Elemental Burst: III',
      audio: 'VO_Aloy_Elemental_Burst_03',
      text: 'The hunt is on!',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Deploying Wind Glider: I',
      audio: 'VO_Aloy_Deploying_Wind_Glider_01',
      text: 'Ha! This thing is fun!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Opening Treasure Chest: I',
      audio: 'VO_Aloy_Opening_Treasure_Chest_01',
      text: 'These things look like they could come in handy.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Opening Treasure Chest: II',
      audio: 'VO_Aloy_Opening_Treasure_Chest_02',
      text: "Let's see, that looks edible... and this looks useful.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Opening Treasure Chest: III',
      audio: 'VO_Aloy_Opening_Treasure_Chest_03',
      text: 'Who put all these things here?',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Low HP: I',
      audio: 'VO_Aloy_Low_HP_01',
      text: "This one's a fighter...",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Low HP: II',
      audio: 'VO_Aloy_Low_HP_02',
      text: 'Come on, gotta find that weak spot...',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Low HP: III',
      audio: 'VO_Aloy_Low_HP_03',
      text: "I'm out of my depth...",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Ally at Low HP: I',
      audio: 'VO_Aloy_Ally_at_Low_HP_01',
      text: 'Watch out!',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Ally at Low HP: II',
      audio: 'VO_Aloy_Ally_at_Low_HP_02',
      text: "Don't get reckless!",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Fallen: I',
      audio: 'VO_Aloy_Fallen_01',
      text: 'I failed...',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Fallen: II',
      audio: 'VO_Aloy_Fallen_02',
      text: "I'm down... I'm sorry...",
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Fallen: III',
      audio: 'VO_Aloy_Fallen_03',
      text: "Can't get up... It's over...",
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Light Hit Taken: I',
      audio: 'VO_Aloy_Light_Hit_Taken_01',
      text: 'Ugh!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Light Hit Taken: II',
      audio: 'VO_Aloy_Light_Hit_Taken_02',
      text: 'I got this.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Heavy Hit Taken: I',
      audio: 'VO_Aloy_Heavy_Hit_Taken_01',
      text: 'Argh!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Heavy Hit Taken: II',
      audio: 'VO_Aloy_Heavy_Hit_Taken_02',
      text: "Should've known this wouldn't be easy...",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Joining Party: I',
      audio: 'VO_Aloy_Joining_Party_01',
      text: 'Where to this time?',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Joining Party: II',
      audio: 'VO_Aloy_Joining_Party_02',
      text: "I'm ___. Ready for the hunt.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Joining Party: III',
      audio: 'VO_Aloy_Joining_Party_03',
      text: "Need help? I'm here.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Outcast, hunter of machines, Seeker, Anointed, Savior... ___ had many identities in her original world, and she was destined on account of her genetics to be the heroine who would heal it.\\nNow, she has arrived in a new world, full of never-before-seen challenges, and once again, she throws herself gladly into the hunt.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '___ was born an outcast, deeply rejected and feared by her tribe. She was raised in the rugged mountains near their tribal dwellings by the experienced Hunter, Rost.\\nHe taught her how to hunt: to have cat-like form and deadly accuracy. And yet, he could not pass the most important thing onto her — the truth of her birth. Who were her parents? Why had she been cast out?\\nUnfortunately, the reasons for this were known only to the very High Matriarchs of the tribe who had exiled her.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "There was only one way to discover the identity of ___'s parents — victory at the Proving, the tribe's annual hunting contest, in which the victor would be free to ask for a reward.\\nShe would train hard all her life for that event, but when the moment of trial came, the ritual would end in tragedy.\\nMysterious assassins slew the participating Hunters, and it was only through Rost's sacrifice that ___ was able to escape.\\nLater, ___ would learn that she was the true target of the attack, for she had almost exactly the same face as an enigmatic, ancient woman.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: '___ knew that she had to find these killers to understand her origins.\\nHer pursuit brought her into a wild and dangerous world far beyond her imagination, bringing strange and powerful tribes, mysterious ancient ruins, and terrifying enemies — whether human or machine — before her.\\nIn the end, the true enemy, HADES, appeared before her. It was an artificial intelligence filled with malice, bent on cleansing the world of all life.\\nThere was only one way to defeat HADES: investigate her link with that ancient woman, that "___ from the past"... Or could she have been her mother?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Hot on HADES' trail, ___ traversed a great many ruins from the distant past, and ultimately discovered her origin: she was not born of human flesh and blood but was the result of cloning.\\nThe genetics of the woman who had saved all life 1,000 years ago had been the basis for her creation.\\nThis had not only granted her the abilities she had possessed since birth, but had also guided her destiny, for this genetic material was the key to preventing the second coming of the apocalypse.\\nArmed with this knowledge, and with the help of allies from many tribes, ___ was finally able to defeat HADES and its human and machine minions in a decisive battle in the shining city of Meridian.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'After defeating HADES, ___ embarked on a new journey, pursuing ancient technologies and cleansing the land that HADES had trampled underfoot.\\nIn her long journey, she found every Old World Ruin that there was to be found in search of the Old Ones\' lost secrets.\\nIn one ancient, dilapidated laboratory, she found something she had never seen before — a gleaming portal. As she drew close, she was enveloped by powerful energies, and she saw her own image within the portal as one looking into a mirror, feeling as if she were in two places at once.\\nWith a flash of light, the "world" that ___ knew completely disappeared from her sight, and she now found herself in a strange, beautiful new world just waiting to be explored.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
