export const ayakaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Kamisato_Ayaka_Hello',
      text: 'Master of Inazuma Kamisato Art Tachi Jutsu — ___, present!\\nDelighted to make your acquaintance.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Stability',
      audio: 'VO_Kamisato_Ayaka_Chat_-_Stability',
      text: 'I only wish life could be as leisurely as this a little more often... How greedy of me.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Sword',
      audio: 'VO_Kamisato_Ayaka_Chat_-_Sword',
      text: 'A blade is like a tea-leaf. Only those who sample it many times can appreciate its true qualities.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Zoning Out',
      audio: 'VO_Kamisato_Ayaka_Chat_-_Zoning_Out',
      text: "So this is a day in the life of the Traveler... Hehe, I'm learning more about you all the time.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'Chat: Famous Sword',
      audio: 'VO_Kamisato_Ayaka_Chat_-_Famous_Sword',
      text: 'A blade embraces its duty as a jeweler cherishes their gems.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Rains',
      audio: 'VO_Kamisato_Ayaka_When_It_Rains',
      text: 'Come with me, let us find shelter from the rain.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When Thunder Strikes',
      audio: 'VO_Kamisato_Ayaka_When_Thunder_Strikes',
      text: 'Her Excellency... What is she trying to communicate?',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Snows',
      audio: 'VO_Kamisato_Ayaka_When_It_Snows',
      text: '"Snow that once adorned the world in silver, thaws to reveal the gleam of the fruit upon frost-laden branches." *sigh* How picturesque! Only some tea would make this setting more complete.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Sun Is Out',
      audio: 'VO_Kamisato_Ayaka_When_the_Sun_Is_Out',
      text: "There's a pleasant breeze and glorious sunshine... So, where shall we go for a walk?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: "When It's Windy",
      audio: 'VO_Kamisato_Ayaka_When_It\'s_Windy',
      text: "Close your eyes and face the wind... It feels wonderful, doesn't it?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Morning',
      audio: 'VO_Kamisato_Ayaka_Good_Morning',
      text: 'Oh, good morning, Traveler. ...Whenever I see you in the morning, somehow, it makes me feel like... today is going to be a good day.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon',
      audio: 'VO_Kamisato_Ayaka_Good_Afternoon',
      text: 'Good afternoon. It is normal to feel drowsy after lunch, might I interest you in a game of Go to stimulate the mind?',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: 'VO_Kamisato_Ayaka_Good_Evening',
      text: 'Greetings. An auspicious breeze blows this evening. Tonight will be peaceful.',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: 'VO_Kamisato_Ayaka_Good_Night',
      text: '"Was it one\'s thoughts that drew him to my dreams? Had I known it a dream, one would not have awakened." Hehe, I love that poem.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Yashiro Commission',
      audio: 'VO_Kamisato_Ayaka_About_Kamisato_Ayaka_-_Yashiro_Commission',
      text: '"Inazuma Shogunate, Yashiro Commission, Kamisato Clan." Widely known as one of the most distinguished clans in all of Inazuma, it is the branch of the Tri-Commission that manages ceremonial and cultural affairs. Since my parents passed, Brother and I assumed responsibility for all clan matters, big and small.',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About ___: Position',
      audio: 'VO_Kamisato_Ayaka_About_Kamisato_Ayaka_-_Position',
      text: 'Many look up to me as the Shirasagi Himegimi and as the daughter of the Kamisato Clan. But the object of their respect has everything to do with my position, and nothing at all to do with me, ___. It makes me think that... maybe, there is only one person I know who is truly able to get close to me...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'About ___: Aspiration',
      audio: 'VO_Kamisato_Ayaka_About_Kamisato_Ayaka_-_Aspiration',
      text: 'Today, as in the past, I aspire to be somebody whom everyone can trust. But what motivates me is no longer the responsibilities I shoulder, or the expectations of other people. Rather, it is the fact that you are this kind of person, too.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: Teahouse',
      audio: 'VO_Kamisato_Ayaka_About_Us_-_Teahouse',
      text: "If you've got time, shall we take a walk to Komore Teahouse? To chat about the art of tea on a pleasant day like this seems like the sophisticated thing to do.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'About Us: Festivals',
      audio: 'VO_Kamisato_Ayaka_About_Us_-_Festivals',
      text: 'If I ever have the chance, I would very much like to experience the festivities of another nation with you one day. Though, I will need some guidance on local customs and etiquette, and advice on what gifts to bring... Could I trouble you to give me some guidance?',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 12008,
              questTitle: 'With You',
              chapterId: 2022,
              chapterTitle: 'The Whispers of the Crane and the White Rabbit',
            },
          ],
        },
      ],
    },
    '19': {
      title: 'About the Vision',
      audio: 'VO_Kamisato_Ayaka_About_the_Vision',
      text: 'Visions are a seal of approval for those who are most ambitious. As for my own ambitions, they shall remain private for now. It is nothing more than an insignificant dream.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'Something to Share',
      audio: 'VO_Kamisato_Ayaka_Something_to_Share',
      text: 'It is said that "the flavor of Zen is that of tea," and it is also said that "the power of Zen is that of the blade." One might then ask: What does that say about the relationship between tea and the blade?',
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Interesting Things',
      audio: 'VO_Kamisato_Ayaka_Interesting_Things',
      text: "Have you ever noticed the withering sakura tree in the city? For me, there is a beauty to the withering, it brings back fond memories of the spring. Most people don't agree — sakura trees that will never bloom again are removed. But when I look at a tree, all I want is to see it blossom again... just one more time...",
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'About Thoma',
      audio: 'VO_Kamisato_Ayaka_About_Thoma',
      text: 'Thoma is a dear friend. He always lifts my spirits with his sunny disposition. In a sense, I think of him as another brother, and as a full member of the Kamisato Clan.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Kujou Sara',
      audio: 'VO_Kamisato_Ayaka_About_Kujou_Sara',
      text: 'Kujou Sara of the Tenryou Commission is... not known to smile, and I have had my fair share of disputes with her. She is, however, a loyal servant to Inazuma, there is no question about that.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Shikanoin Heizou',
      audio: 'VO_Kamisato_Ayaka_About_Shikanoin_Heizou',
      text: 'Mr. Shikanoin belongs to the Tenryou Commission, just like Miss Kujou. He is very... principled, sometimes even more determinedly so than Miss Kujou. The only thing is, when it comes to the question of which matters should be governed by his principles, I believe only Mr. Shikanoin himself knows the answer...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Sayu',
      audio: 'VO_Kamisato_Ayaka_About_Sayu',
      text: "Ah, little Sayu. She hasn't been causing you any trouble lately, has she? Hehe, if you ever notice her slacking off, please let me know.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About the Raiden Shogun: Guesswork',
      audio: 'VO_Kamisato_Ayaka_About_the_Raiden_Shogun_-_Guesswork',
      text: 'The Almighty Shogun? It would be improper of me to comment, given that I am one of her subjects. All I will say is that... I think that Her Excellency must get lonely on the road to eternity.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About the Raiden Shogun: Standpoint',
      audio: 'VO_Kamisato_Ayaka_About_the_Raiden_Shogun_-_Standpoint',
      text: "To witness the Musou no Hitotachi and live to tell the tale is quite a remarkable feat. Even though I recognize her as our true deity with the power to change Inazuma's fate at will, if there is conflict between the two of you, then... I shall choose to side with you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'About Yae Miko',
      audio: 'VO_Kamisato_Ayaka_About_Yae_Miko',
      text: "I have always greatly enjoyed working with Guuji Yae. Organizing festival affairs generally takes a lot of effort and doesn't generate much income, but Guuji Yae's events always come off both elegant and profitable.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Kamisato Ayato',
      audio: 'VO_Kamisato_Ayaka_About_Kamisato_Ayato',
      text: "As the head of the Kamisato Clan, brother always has a full schedule of places he needs to be. I do try my best to share his load, but there is no changing the pressure he is subjected to all year round, and the toll it takes upon him. *sigh* If you see him, remind him to take care of himself, for his sister's sake...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Yoimiya',
      audio: 'VO_Kamisato_Ayaka_About_Yoimiya',
      text: 'The Yashiro Commission and the shrine maidens are responsible for festival affairs, and Yoimiya, as a fireworks expert, knows how to create an atmosphere. So we have become well acquainted with her over the years.\\nHmm? Public order and fire prevention? We factor these concerns in well in advance during the planning stage. To deny people the chance to see fireworks simply for these reasons would leave them feeling very disappointed.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: I',
      audio: 'VO_Kamisato_Ayaka_More_About_Kamisato_Ayaka_-_01',
      text: 'Your request is quite unusual for me. Since I see you as a friend, it would only be fair to be open and honest with you, but if this means sharing secrets of the Kamisato Clan... I would ask that you keep anything I tell you in strict confidence.',
      tips: 'Complete "Stillness, the Sublimation of Shadow"',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '32': {
      title: 'More About ___: II',
      audio: 'VO_Kamisato_Ayaka_More_About_Kamisato_Ayaka_-_02',
      text: "The Kamisato Clan once suffered a major blow when we failed to protect a swordsmith of national significance. We were harassed by the Fatui, we lost many of our people, and we received a great deal of criticism. It all aged Father greatly, and severely damaged the Kamisato Clan's standing within the Shogunate. Brother has worked tirelessly to reverse the trend since he assumed leadership, but although our clan's position is now restored and the Yashiro Commission is unified once more, we still rely on Brother to make the decisions on all matters of any importance.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '33': {
      title: 'More About ___: III',
      audio: 'VO_Kamisato_Ayaka_More_About_Kamisato_Ayaka_-_03',
      text: "The art of blade forging taught by the Shogun varies based on astrology, application, materials used, the furnace conditions, individual personalities, and elemental changes. These differences between smiths is what gave rise to the Raiden Gokaden. Swordsmiths capable of forging renowned blades are seen as spiritual personnel with sacred abilities, and as such they should be managed by the Yashiro Commission, which oversees all cultural, artistic, and ceremonial affairs. So naturally, the swordsmith's betrayal is the fault of ineffectual management by the Kamisato Clan.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '34': {
      title: 'More About ___: IV',
      audio: 'VO_Kamisato_Ayaka_More_About_Kamisato_Ayaka_-_04',
      text: "My mother was the most incredible person. She was always so dignified and elegant, always smiling, no matter what situation she might be facing. She had so much to deal with in the clan on so many levels, but she took it all in stride — it was like nothing could ever faze her. Everything about her was perfect, and I say that without exaggerating. *sigh* But the moment she passed away, I realized... I couldn't hide behind my mother any longer. I wasn't little ___ any more.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '35': {
      title: 'More About ___: V',
      audio: 'VO_Kamisato_Ayaka_More_About_Kamisato_Ayaka_-_05',
      text: "What I want to say next is perhaps not befitting of a member of the Inazuma Shogunate, Yashiro Commission, Kamisato Clan, but... unless I am mistaken, I trust that you will not take issue with this slight departure from convention on my part...\\nThat is to say... I'm a little tired, may I rest my head on your shoulder? Just for a moment.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '36': {
      title: "___'s Hobbies",
      audio: 'VO_Kamisato_Ayaka_Hobbies',
      text: 'I have great affection for the arts: music, song, poetry, shougi, and dancing. And you?',
      tips: '',
      tasks: null,
    },
    '37': {
      title: "___'s Troubles: Concerns",
      audio: 'VO_Kamisato_Ayaka_Troubles_-_Concerns',
      text: "Troubles? Well, I mean... that's life, isn't it? There will always be things that don't go one's way. But I do not wish to worry those around me on account of things that are my concern alone... so, it is best if I keep them to myself.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: "___'s Troubles: Desires",
      audio: 'VO_Kamisato_Ayaka_Troubles_-_Desires',
      text: "Openness is something I find very difficult. I constantly have to remind myself that as a lady of the Kamisato Clan, there are countless people watching and countless expectations to live up to. I must be a model of exemplary conduct at all times. But even so, shouldn't I still follow my dreams? Shouldn't I... share my true feelings with you?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '39': {
      title: 'Favorite Food',
      audio: 'VO_Kamisato_Ayaka_Favorite_Food',
      text: "I'm fascinated by food from overseas. Though I don't get to try it very often... So, if I had to choose something from Inazuma, then probably... Chazuke. But not when anybody else is watching... So I tell you that in confidence.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Least Favorite Food',
      audio: 'VO_Kamisato_Ayaka_Least_Favorite_Food',
      text: 'Though I do not eschew animal fat and organs entirely, they are far from my first choice.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Kamisato_Ayaka_Receiving_a_Gift_-_01',
      text: 'Mmm... Yes, I am truly fortunate...',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Kamisato_Ayaka_Receiving_a_Gift_-_02',
      text: 'Thank you for the opportunity to try this dish. I will always savor it.',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Kamisato_Ayaka_Receiving_a_Gift_-_03',
      text: "Hmm... It's a bit greasy for my taste.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Birthday',
      audio: 'VO_Kamisato_Ayaka_Birthday',
      text: "Come with me! We're not going far away — I promise it won't delay you too much.\\nI managed to find out when your birthday was well in advance, so I could prepare in good time. Hopefully this wasn't assuming too much, but I guessed you might prefer this to an expensive gift.\\nIn honor of your birthday, please allow me to perform a fan dance for you.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Kamisato_Ayaka_Feelings_About_Ascension_-_01',
      text: 'Thank you very much. It has been richly rewarding to learn from you so far, and I believe my skills with the blade can go even further still.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Kamisato_Ayaka_Feelings_About_Ascension_-_02',
      text: 'Thank you for your guidance. With your assistance, I am gaining a more thorough understanding of my capabilities.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Kamisato_Ayaka_Feelings_About_Ascension_-_03',
      text: 'I feel more competent now than ever before. I even have the time outside my work for the Yashiro Commission to try some new things. Would you like to try one of my home-made snacks? I just learned how to make them recently.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Kamisato_Ayaka_Feelings_About_Ascension_-_04',
      text: '"Though I cling to that which has given me the strength to hold on, the weight of letting go is ever-foreboding."\\nMy apologies, it should be a happy occasion, and yet it is such a sad phrase that comes to mind. Our time together has been so pleasant that I am fearful of losing what I have gained. I\'m sorry, I must compose myself.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: I',
      audio: 'VO_Kamisato_Ayaka_Elemental_Skill_1_01',
      text: 'Take flight.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: II',
      audio: 'VO_Kamisato_Ayaka_Elemental_Skill_1_02',
      text: 'My apologies.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: III',
      audio: 'VO_Kamisato_Ayaka_Elemental_Skill_1_03',
      text: 'Whirling snow.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: I',
      audio: 'VO_Kamisato_Ayaka_Elemental_Burst_01',
      text: 'Embrace the ice.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: II',
      audio: 'VO_Kamisato_Ayaka_Elemental_Burst_02',
      text: 'Sakura swirl.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: III',
      audio: 'VO_Kamisato_Ayaka_Elemental_Burst_03',
      text: 'Kamisato Art: Soumetsu!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: I',
      audio: 'VO_Kamisato_Ayaka_Opening_Treasure_Chest_01',
      text: 'Collecting rare and exquisite treasures... Yes, this seems suitably sophisticated.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: II',
      audio: 'VO_Kamisato_Ayaka_Opening_Treasure_Chest_02',
      text: 'Hehe... Today is a lucky day.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: III',
      audio: 'VO_Kamisato_Ayaka_Opening_Treasure_Chest_03',
      text: 'I shall treasure this good fortune.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: 'VO_Kamisato_Ayaka_Low_HP_01',
      text: 'I will not stand for this.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: 'VO_Kamisato_Ayaka_Low_HP_02',
      text: 'A worthy opponent...',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: 'VO_Kamisato_Ayaka_Low_HP_03',
      text: 'We ought to end this!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: 'VO_Kamisato_Ayaka_Ally_at_Low_HP_01',
      text: 'Do not overdo it.',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: 'VO_Kamisato_Ayaka_Ally_at_Low_HP_02',
      text: 'Take care!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: 'VO_Kamisato_Ayaka_Fallen_01',
      text: 'Pardon my indiscretion...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: 'VO_Kamisato_Ayaka_Fallen_02',
      text: 'Much remains... unfinished...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: 'VO_Kamisato_Ayaka_Fallen_03',
      text: 'I have dishonored... our clan...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: I',
      audio: 'VO_Kamisato_Ayaka_Heavy_Hit_Taken_01',
      text: 'So rude!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: II',
      audio: 'VO_Kamisato_Ayaka_Heavy_Hit_Taken_02',
      text: 'Unthinkable...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: 'VO_Kamisato_Ayaka_Joining_Party_01',
      text: '___, present.',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: 'VO_Kamisato_Ayaka_Joining_Party_02',
      text: 'I await your instruction.',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: 'VO_Kamisato_Ayaka_Joining_Party_03',
      text: 'A pleasure to be working with you.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "A pair of siblings have inherited the Kamisato Clan, one of the three most respected and prestigious clans in Inazuma City.\\nThe elder brother, Ayato, is the head of the clan and is in charge of government affairs. While his younger sister, ___, known by all as the Princess, takes care of the clan's internal and external affairs.\\n___ often appears at social occasions and has more interactions with the common folk. As such, she is better known by the people and has gained a higher reputation than her elder brother. This has earned her the elegant title of Shirasagi Himegimi.\\nAs is known to all, ___, the daughter of the Kamisato family, is a figure greatly admired by the people for her beauty, dignified demeanor, and noble character.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Across Inazuma, all affairs of state that do not go up to the Raiden Shogun are largely handled by the Triarchal Council.\\nThe Council\'s executive powers are, in turn, divided amongst three groups known as the Tri-Commission: the Yashiro Commission, the Tenryou Commission, and the Kanjou Commission.\\nThe three clans that hold power over these Commissions are as follows: Kamisato, Kujou, and Hiiragi. These three great clans are known throughout Inazuma.\\n___ is the young lady of the Yashiro Commission\'s Kamisato Clan, known far and wide as the Shirasagi Himegimi.\\nWhen asked the whys and wherefores of such a nickname, many Inazumans have their own explanations...\\n"Lady ___ is as graceful and pure as an egret. And just look at her elegance, her clever yet proper speech — why should she not be named a Princess?"\\n"Lady ___ may be of noble birth, but she is gentle and polite to us. She is kind, loyal, and is willing to help others. She even went against the opinions of others and took in that commoner, Thoma."\\nThere are as many opinions concerning this as there are people, but none can say where the "Shirasagi Himegimi" nickname actually originated.\\nStill, ___\'s popularity amongst the people is quite plain to see.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "As the daughter of the Yashiro Commission's Kamisato Clan, ___ always has to remain alert to the jostling for power between noble families.\\nBeing young, yet already famed throughout the land, she has been the inevitable target of provocation on the part of other noble scions who have grown jealous of the Kamisato siblings.\\nThe creation and maintenance of a public image may be a formality, but for a house of standing like the Kamisato Clan, even meaningless routine has social significance.\\nFailing to take part in the tangled web of Inazuman political relations risks their position as head of the Yashiro Commission. As such, the two siblings came to an accord.\\nThe elder brother, Ayato, preferring not to show his face too often, would busy himself with government affairs, while the act of maintaining the clan's image would be the responsibility of the elegant, socially-adroit younger sister, ___.\\nThrough her dignified, demure, and polite posture, ___ has very much secured a place for herself in the social arena. Whether she is negotiating with potential partners or dealing with difficult nobles, her actions are all well-founded and beyond reproach.\\nThe internal clan affairs are also in her care. Indeed, their estates may have descended into chaos already, if not for her.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'One autumn afternoon, ___ was on her way home from completing certain minor affairs when she happened to hear an old voice singing from within an old house.\\nWithin was an old woman, blind in both eyes, whose stick-thin fingers produced music like flowing water as they plucked at her instrument\'s strings.\\nPerhaps it was due to her sharp ears, but the old lady heard ___\'s footsteps and inquired as to who was outside. Not wishing to trouble the old lady, ___ replied that she was a nearby resident who had gotten lost and entered this place.\\nAs a member of the Yashiro Commission, ___ was well-acquainted with the people\'s lives and quickly recognized this solitary old lady as the very same person who busked in the city streets when the weather was good.\\nThe tune was outdated, and so was the song. As one who could not see, this lady had long fallen out of step with the times. Even in the nation that pursues eternity, some still endured such hard lives.\\nOut of the goodness of her heart, ___, thusly incognito, spent a long time chatting with the old lady. Taking ___ for an ordinary maiden, the old lady spoke of the method of making and playing the koto, and even gave her some tea leaves that she had kept stored up.\\nCompared to the exquisite leaves that the Kamisato Clan had in stock, these rough leaves may as well have been grass, but ___ accepted them while profusely thanking her.\\nThat day, she thought of her parents many times. Had they been around, would they not have grown this old someday?\\nReturning home, she spoke of her encounter with her brother, and the two siblings shared the rustic tea gifted to her by the old lady.\\nAfterward, ___ would come to see that old lady again every few days, each time posing as a person living nearby, and each time bringing with her some daily necessities that were well-loved by the common folk.\\n"The sakura trees in the streets have bloomed again," ___ said to the old lady with a smile, "and they are as lovely as your music."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'In people\'s imagination, the nobility\'s living expenses are orders of magnitude above the common folk. So for someone as noble as ___, surely she too must lead a life of wanton luxury.\\nThis statement is only half right, however.\\n___ does ostensibly live in a much more particular manner than the ordinary citizen.\\nThe costs of studying flower arrangement and tea ceremony, sampling fine teas, and enjoying exotic flowers daily are also by no means small. However, these are all skills that she must master as a young lady of a noble house — such commitments can hardly be called "wanton."\\nThe things that can truly make ___ smile are, in fact, ordinary things that even the common folk can enjoy.\\nThe making of snacks, fishing for goldfish by the ponds, squirreling herself away to read the latest novels from Yae Publishing House... Each one of these is but a tiny matter.\\nAt such times, she is not the adored Shirasagi Himegimi, or Lady ___, mistress of the great Kamisato estates. She is just "___," an ordinary girl like any other.\\nHere, she sets her dignified externalized persona aside and sets her true, casual self free. Only as "___" can she lay down her heavy burdens and do the things that ordinary girls can do.\\nWhen hungry at night, she sneaks past the servants into the kitchen and makes herself some chazuke while humming a little tune. During tea ceremony classes, she might surreptitiously try to use the tea leaves to indulge in some romance-related astrology... The list of her little escapades goes on.\\nThough she has never told anyone this, ___ treasures her time as an ordinary girl above all else, for these moments of freedom are things she rarely ever has.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'The tutors who guide ___ in her various arts once used to say: whether in tea ceremony, chess, the art of the sword, or all other affairs of elegance, ___ is already a master.\\nShe is clearly already a noble lady of superb bearing, skilled with both the pen and the sword. To be able to teach such a pupil is a teacher\'s pride and joy.\\nStill, ___ thinks quietly to herself, does she truly have no regrets?\\nThe essence of tea is peace and quiet.\\nThe heart of the sword is the keenest edge.\\nThe soul of chess is the wisdom to grasp the bigger picture.\\nThese three she has grasped indeed, and the spirit of true friendship also.\\nAnd yet, ___ is still waiting for a friend to emerge who can walk alongside her on equal footing and stand by her side.\\nThat person cannot see her as a member of the Yashiro Commission, or as the Shirasagi Himegimi, nor will their conduct towards her be bound by decorum or status. And if possible, they might also be well-versed in a great many fields of study, and have witnessed all manner of interesting things... and perhaps they might even be able to tell her a story in a pinch.\\nOnly such a person might become ___\'s bosom friend.\\n"Surely, this is not too much to ask... But where might I find such a person?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Moriwakamaru',
      title2: null,
      text: '"Come, come, come,"\\n"Let\'s play Temari!"\\n"1, 2, 1, 2, 3,"\\n"The Temari goes up the Sacred Sakura Tree."\\n"4, 5, 4, 5, 6,"\\n"Woosh, and over Mt. Yougou it flicks!"\\n"7, 8, 7, 8, 9,"\\n"The Temari returns into these hands of mine."\\n"Yes, into little~ ___\'s~ hands~!"\\nThis was ___\'s favorite nursery rhyme back in the day.\\nBack then, she gave her favorite Temari the name "Moriwakamaru," and she would dribble the multi-colored Moriwakamaru about while humming this very song.\\nHearing her song, her parents and brother would be unable to stop themselves from smiling. Indeed, they would often join in the fun, tossing the Temari between them as a family.\\nBut that was a long time ago, and ___ no longer plays games of Temari.\\nShe has become an independent, powerful figure in her own right — and Moriwakamaru, the symbol of her childhood and the bearer of her precious memories, has also been stored away within ___\'s cabinet.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Some years ago, the Clan underwent a huge change, and a heavy burden fell upon Ayato\'s shoulders. At that time, ___ was not yet the mature and capable person she is now.\\nShe was originally a playful child, one who knew nothing of the clan\'s duties, and thus lacked the skill and experience needed for dealing with various kinds of people altogether.\\nBut seeing her mother on her sickbed and her brother hard at work, ___ sensed that she too had to grow up.\\nSo she decided to take up her long-disused sword arts and poetry, both staples of nobility. If she could master these two, she could at least pass for a decent lady of the Kamisato Clan, and thus help her brother show up at some festivals, alleviating his burden.\\nTruth be told, ___ was not preternaturally gifted and would spend much time being troubled by her inability to memorize poetry, write elegantly, or brandish her sword.\\nYet she did not waver — a poem she failed to memorize once would be memorized fifty times, a poorly-written word would be written fifty times over, and a sword technique that failed would be swung fifty times more.\\n"None may deflect a swing that has been practiced a thousand times." — This was something her mother told her.\\nWhen her mother left this world, ___ was no longer "Little ___." She was now ___, the young lady of the Kamisato Clan, one of the Shogun\'s three great clans.\\nSword art training thus became part of her daily life and has remained so to this day without pause.\\nOn one particular day, ___, at last, defeated an opponent in a single strike. In that instant, as she stood in the middle of the dojo, icy flowers condensed all about her. And there, upon the tip of her sword, now hung a Vision, icy and bright.\\n"None may deflect a swing that has been practiced a thousand times" indeed — and even the gods may thus be moved.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
