export const chongyunVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Chongyun_Hello',
      text: 'My name is ___. My family has practiced the art of exorcism in Liyue for many generations. Fate has been generous in allowing my path to cross with that of your distinguished self. ...Oh, no — my services are free of charge!',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: The Art of Exorcism',
      audio: 'VO_Chongyun_Chat_-_The_Art_of_Exorcism',
      text: 'Exorcism uses thaumaturgy and martial arts to conquer evil. There are other means to the same end, but they are not the true way.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Diet',
      audio: 'VO_Chongyun_Chat_-_Diet',
      text: 'I take my meals cold to quiet the spirit and calm my vital energies. Qingxin-infused water with ice is the most effective.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Mantras',
      audio: 'VO_Chongyun_Chat_-_Mantras',
      text: '"Heart be pure, evil be erased. Mind be purged, world be..." Um... Ugh, I always forget that last part.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Chongyun_When_It_Rains',
      text: 'There is no purer form of water than rain. It can aid us greatly in the purging of evil.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Chongyun_When_Thunder_Strikes',
      text: 'Before the resounding thunder, evil must cower in fear.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: 'VO_Chongyun_When_It_Snows',
      text: 'Ah, this weather is delightful.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Good Morning',
      audio: 'VO_Chongyun_Good_Morning',
      text: 'It is unwise to waste the precious morning hours. Time to train!',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Afternoon',
      audio: 'VO_Chongyun_Good_Afternoon',
      text: "One's spiritual energies are at their peak at noon. We must take that time to practice.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Evening',
      audio: 'VO_Chongyun_Good_Evening',
      text: 'As the day winds down and the quiet of evening sets in, the atmosphere is ripe for focusing your mind. There is no better time than this for training.',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Night',
      audio: 'VO_Chongyun_Good_Night',
      text: "Whew. What a tiring day. You should get some rest. Don't forget what we agreed — we will investigate that haunted house tomorrow.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'About ___: Exorcists',
      audio: 'VO_Chongyun_About_Chongyun_-_Exorcists',
      text: 'We exorcists have been protectors of Liyue since ancient times, and our techniques have been passed down from generation to generation. Purging evil is second nature to us.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Commissions',
      audio: 'VO_Chongyun_About_Chongyun_-_Commissions',
      text: "*sigh* I didn't actually do anything. I just walked into that haunted house, and the problem was resolved... Do you think I should still take payment for this exorcism?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Companions',
      audio: 'VO_Chongyun_About_Us_-_Companions',
      text: 'Your skills are impressive. When you finish with a hilichurl— I mean, an evil spirit, it is surely banished from this world for good. How about we team up?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Ghost Stories',
      audio: 'VO_Chongyun_About_Us_-_Ghost_Stories',
      text: "By now, you must be well acquainted with Liyue's supernatural phenomena. Now, about the evil beings you speak of in lands beyond... I would very much like to see them too.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: 'VO_Chongyun_About_the_Vision',
      text: 'Visions are powerful, but one would be foolish to place blind faith in them. Personally, I trust more in thaumaturgy and martial arts. In the end, one cannot become truly proficient without vigorous training.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: 'VO_Chongyun_Something_to_Share',
      text: 'There are rumors abound concerning evil spirits in Liyue, but not all have truth to them. In fact, some strange commissions wind up having nothing to do with them at all.',
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: 'VO_Chongyun_Interesting_Things',
      text: 'I have heard there are many strange and rare things sealed within the amber from Mt. Hulao. Could some of them be the fabled demons of which the ancient legends speak? I would love to investigate.',
      tips: 'Complete "A New Star Approaches"',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '18': {
      title: 'About Zhongli',
      audio: 'VO_Chongyun_About_Zhongli',
      text: 'That Zhongli from the Wangsheng Funeral Parlor seems to be quite an incredible man. Just think, common folk might gang up to commit a murder, we exorcists vanquish demons — but he alone buries the bodies of the adepti.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1016,
              questTitle: "Zhongli's Treat",
              chapterId: 1102,
              chapterTitle: 'Farewell, Archaic Lord',
            },
          ],
        },
      ],
    },
    '19': {
      title: 'About Xingqiu',
      audio: 'VO_Chongyun_About_Xingqiu',
      text: 'I do admire Xingqiu for his devotion to chivalry and his martial arts proficiency. However — I must warn you that he definitely has a mean side, too. If you find that you fall foul of any of his antics, come to me and we\'ll form a "Victims of Xingqiu" alliance. There is strength in numbers.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Xiao',
      audio: 'VO_Chongyun_About_Xiao',
      text: "The Conqueror of Demons himself has defended Liyue side-by-side with we exorcists for generations, day after day, night after night. I have the utmost respect for Adeptus Xiao. It's just... Why must he be so disparaging toward us? He says our repertoire is lacking and our power is trivial. I'm sorry, but I just can't accept that.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Hu Tao',
      audio: 'VO_Chongyun_About_Hu_Tao',
      text: 'The Wangsheng Funeral Parlor is a reputable institution that acts with integrity. But whenever I see that cheeky smile that says, "It\'s nothing you exorcists need to worry about," it just makes my blood boil... Whoa, deep breaths, ___. Stay calm.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Qiqi',
      audio: 'VO_Chongyun_About_Qiqi',
      text: "She looks like a zombie, but as an exorcist, I feel there's... something different about her. Hmm, her name is also absent from all the praised names I've seen... Where exactly does she fit in among the deities?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Xinyan',
      audio: 'VO_Chongyun_About_Xinyan',
      text: "I avoid Xinyan's performances like the plague. That heated atmosphere... Even if you don't intend to get involved, it still... Let's just say that it gets me all hot and bothered.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Xiangling',
      audio: 'VO_Chongyun_About_Xiangling',
      text: "Xiangling's cooking is universally praised, but I personally don't touch any of her spicy dishes. Why? Oh, you know — just, uh... personal preference, that's all. I mean, come on, Mushroom Slime Stew... Does that sound appetizing to you?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Shenhe',
      audio: 'VO_Chongyun_About_Shenhe',
      text: "The elders in my clan have mentioned her before. The fate of her family... *sigh* It's something we can all sympathize with. I originally thought we would be able to bring a long-lost relative back into our clan. The elders were overjoyed, too, when they heard she was still alive — they even prepared gifts for her, and picked an auspicious day for a grand reunion. What we hadn't counted on was that most of the time, she's extremely difficult to track down. Wait a minute, based on our relative positions in the family tree, does that mean that I... There's no way I'd have to call her \"Auntie Shenhe\"... right?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Yelan',
      audio: 'VO_Chongyun_About_Yelan',
      text: "I met her once, back when I'd just become an exorcist. I'd taken a commission to perform an exorcism in someone's home, and was just leaving at the end when I ran into her. She wrote my name down in a booklet — I guess she just wanted to confirm I wasn't doing anything suspicious... Anyway, it was just that one time, I never saw her again after that.\\nNow that I think about it, it's probably because the sight of me meditating motionless must be pretty boring to watch. Not exactly suspicious.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'More About ___: I',
      audio: 'VO_Chongyun_More_About_Chongyun_-_01',
      text: "Discipline is everything. Unbridled passion can have disastrous consequences. Trust me, I would know. ...Oh, no no no, not from personal experience, of course. Haha... Uh... I'm just stating my observations from what I've seen in my travels around Liyue.",
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'More About ___: II',
      audio: 'VO_Chongyun_More_About_Chongyun_-_02',
      text: "I was born with a pure yang spirit, meaning I have too much positive energy... Apparently it's so rare it only happens once every thousand generations or so. It means I repel all evil for miles around... *sigh* Actually, that's a bad thing. I must be the only exorcist in history who can't get within ten miles of an evil spirit.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '29': {
      title: 'More About ___: III',
      audio: 'VO_Chongyun_More_About_Chongyun_-_03',
      text: 'One of the main consequences of having a pure yang spirit is excess passion, something which has gotten me into many embarrassing situations. In an effort to alleviate these symptoms, I have to abstain from eating chilis and all hot food. I also have to take a parasol with me everywhere, and I avoid listening to rousing music. I wonder, will I ever find a way to work around my condition?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About ___: IV',
      audio: 'VO_Chongyun_More_About_Chongyun_-_04',
      text: "Waiting for evil to show up at the doorstep will get you nowhere — you have to go out and hunt it down. By purging Liyue of evil spirits, I bring peace of mind to people and also broaden my horizons. If an evil spirit ever bothers you, just let me know. I'll come and help you out right away.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '31': {
      title: 'More About ___: V',
      audio: 'VO_Chongyun_More_About_Chongyun_-_05',
      text: "To permanently banish the forces of evil from the world is my ultimate goal as an exorcist. If that grand day ever comes, I suppose I should be able to consider trying many new things, such as hot springs, Jueyun Chilis, and... partaking in other activities of a more passionate nature. Ugh, what am I doing... Ugh, I shouldn't be dwelling on these things, even thinking about them is too stimulating for me...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '32': {
      title: "___'s Hobbies",
      audio: 'VO_Chongyun_Hobbies',
      text: "I like listening to Tea Master Liu's stories. His narration really brings the hair-raising tales of the supernatural to life. Why not come with me some time?",
      tips: '',
      tasks: null,
    },
    '33': {
      title: "___'s Troubles",
      audio: 'VO_Chongyun_Troubles',
      text: 'After making numerous inquiries and putting in an enormous amount of effort, I finally tracked down the location of an old haunted temple. So I camped out there for four whole days, ready to exorcise the hell out of that place... and nothing happened. Not even the faintest glimpse of an evil spirit. *sigh* Sadly, this is a regular occurrence for me.',
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Favorite Food',
      audio: 'VO_Chongyun_Favorite_Food',
      text: 'Nothing makes me happier than sitting down to an authentic Inazuman meal, ingredients imported of course. After training hard all day, the ice-cold freshness of Inazuman cuisine takes the exhaustion away.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Least Favorite Food',
      audio: 'VO_Chongyun_Least_Favorite_Food',
      text: 'Anything piping hot and laden with chilis is an absolute no-go for me. The mere thought of a Jueyun Chili gives me hot flashes.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Chongyun_Receiving_a_Gift_-_01',
      text: "Cold dishes are just to my liking! I'll save some for after my training.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Chongyun_Receiving_a_Gift_-_02',
      text: "I'm sorry, I know you mean well, but I really need to wait for it to cool off before I eat it.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Chongyun_Receiving_a_Gift_-_03',
      text: 'Oh no! Did you put Jueyun Chilis in this?',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Birthday',
      audio: 'VO_Chongyun_Birthday',
      text: 'On the anniversary of your birth, please accept this gift of a flower, made of ice crystals. I carved it myself. If you ever encounter an evil spirit, cast this toward it — the spell I have cast upon it will immediately come into effect and hopefully get you out alive. Also... Happy birthday.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Chongyun_Feelings_About_Ascension_-_01',
      text: "We often use these materials for thaumaturgy during exorcisms — I never knew they could be used to purify one's own spirit, too.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Chongyun_Feelings_About_Ascension_-_02',
      text: 'Martial arts and thaumaturgy are alike in that there are always new dimensions to explore. Thanks to your guidance, I can see myself making progress.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Chongyun_Feelings_About_Ascension_-_03',
      text: 'Never before have I fathomed such lofty heights of martial prowess! For eye and hand, man and blade to act in unity... Truly, I have been enlightened.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Chongyun_Feelings_About_Ascension_-_04',
      text: 'With all the secrets arts that I have learned, my goal of banishing all evil from the world is finally in view. I will never forget how much you have done for me. Maybe now I even have what it takes to face the flames of my positive energy, and see if I can take the heat.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Throughout its long history, Liyue has never had a lack of rumors and myths regarding all manner of evil spirits and demons. And regardless of the truth of such rumors, someone has to do something about them.\\n___ was born into a renowned family of exorcists, and has possessed a natural ability to drive away evil spirits from a young age due to his pure-yang spirit. His powers of exorcism are far beyond the norm: his mere presence is sufficient to scatter evil spirits. \\nHowever, this has proven to be an inconvenience for ___ himself, for though he has undertaken hundreds of successful exorcisms, he has never come face-to-face with a single ghost or demon.\\n___ believes in his heart that a true exorcist should exorcize evil with charms and swordsmanship. This natural ability that he has... is just not orthodox.\\nTherefore, he has dedicated himself to the study of exorcism techniques and martial arts, as well as seeking the haunts of evil spirits to prove himself an able and professional exorcist even without his unique physical condition.\\nYet, when will that condition stop being a stumbling block on his path to self-realization?',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'When ___ first ventured out as an exorcist, there had been much talk of an evil spirit lurking inside Liyue Harbor.\\nThe victim of these hauntings was a woman from a family with a high enough stature to even have a word or two with the Liyue Qixing.\\nFrom a time she knew not when, her sleep began to be harassed by sounds that kept her awake, but every time she tried to follow the sound, it would suddenly shift behind her, and begin ringing again in her ears.\\nThis shock caused her unspeakable distress, and she even lost weight for loss of appetite.\\nHer wealth was enough to hire the best exorcists from all over, but no matter what they tried, they had to retreat empty-handed. And not only did the noises persist, they even grew in boldness.\\nIt was then, just when she had given up all hope, that ___ walked through her door.\\n"I apologize for coming just now, it has been far too sunny lately... I heard that this place houses a very stubborn ghost. Please, leave it to me."\\nThen ___ brought a chair over, and sat upon it in the middle of the house for a time.\\nThat night, the strange sounds were no more.\\nThe wealthy woman finally had a good night\'s sleep, and she came running to ___ the next morning with an overabundance of gold and jewelry as a reward.\\nBut ___, as was his wont, only accepted his usual fee of a few hundred Mora without an ounce of emotion on his face.\\nEver since that incident, ___ has found that his reputation precedes him for miles around. He has become beloved in Liyue for his "style and character," and indeed scholars have given him this appellation: "a heart of clear water, and a face of ice."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'However, calling his mannerisms and style "frosty" couldn\'t be farther from the truth.\\nDue to the abundance of yang energy in his constitution, he is constantly troubled by increased body temperature and sudden urges or impulses.\\nHe has tried everything to alleviate the issues both physically and psychologically.\\nHis methods include not drinking hot water, not eating hot or spicy food, wearing light clothes, not getting into arguments, keeping himself from being angered, staying indoors on sweltering days, and always bringing a parasol when on the job.\\nIn short, he attempted to stay away from everything that might aggravate his condition.\\nDespite all this, his yang energy did not subside a whit.\\nA little depressed, ___ began to wrestle with his own body. When he heard about an evil spirit in Dragonspine, he made for the peak wearing only a shirt.\\nThough it was hard enough to keep himself warm, he still felt this insufficient. Digging a hole in a frozen lake, he jumped in and soaked in the icy water while waiting for the evil spirit to show itself.\\nAfter staying in the lake for half a day, he finally caught a glimpse of his target.\\nHowever, after pursuing it down to the mountainside, he discovered it was only a snow rabbit that had been frightened off by his flying swords and floating charms.\\nThe fever that he ran afterward lasted far longer than it would in a normal person.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "___'s pure-yang spirit is not only a huge obstacle in his path as an exorcist, but a constant daily hassle.\\nHe must be extra careful to stay away from \"heaty\" things, to which he is very sensitive, or risk his yang energy and emotions going out of control.\\n___'s clan once held a celebration party at Wanmin Restaurant. And though he waited until all the dishes had gone cold, he did not expect the tender rice balls to be stuffed with Jueyun Chili.\\nAfter but a single bite... ___ had no recollection of what happened next.\\nHowever, according to the victim, chef Xiangling of Wanmin Restaurant, many unforgettable things happened.\\n___ first jumped onto the reception desk and shouted, \"Everything's on me tonight!\" — never mind that he did not actually have any money on him.\\nHe then began to chat with customers at other tables as if they were old pals, bragging to them of how incredible his clan's exorcist arts were, never forgetting to taste other people's dishes on the tables before he left.\\nLastly, he claimed to have sensed an evil spirit in Wanmin Restaurant. This he did not find, but he did slap a charm on Xiangling's forehead and chase her around with his sword.\\nAfterwards, ___ scrimped and saved for an entire month to pay Wanmin Restaurant back for the mess and any damages he might have caused; he also gave Xiangling an evil-warding talisman that he carved by hand.\\nBut Xiangling, for her part, didn't mind ___'s \"transgressions\" at all. Instead, she felt that the crazy ___ was the real ___, without any personal walls up.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: '___ has had the privilege of meeting a true friend in his long journey as an exorcist: Xingqiu.\\nIn contrast to the hard-working ___, Xingqiu was naturally gifted, and had a more flexible way of looking at problems.\\nAfter learning about ___\'s troubles, Xingqiu came up with a possible solution.\\n"If you can\'t reduce the effects of your yang energy, what if you sought out an evil spirit that is immune to it?"\\nThis was a eureka moment for ___. Since then, ___ has no longer sought to alleviate his condition. Instead, he now tries to get Xingqiu to come with him to find such a spirit.\\n"What? Sightings of the legendary Aoyin near the Sea of Clouds? Leave it to me!"\\n"The old house at Feiyun Slope has been taken over by an evil spirit? My bad. I\'ll attend to it right away."\\n"A master exorcist is staying over at Wangshu Inn? I could learn a lot from him... Hmm, better go with a gift."\\nXingqiu usually just makes these "leads" up as he goes, and thanks to his "advice," ___ often comes back empty-handed, blaming his bad luck.\\n"I tried my best to look for it, and even spent quite a sum purchasing more intelligence on that evil spirit — but I wound up missing it by a hair anyway," ___ says, abashed.\\nIf Xingqiu has time to spare when such an occasion arises, he will encourage ___, treat him to some new cold dishes he has found and then set off to get ___\'s swindled money back.\\nA warm and reliable companion, indeed! — So ___ thinks at such moments. Who could he possibly trust, if not his fine friend Xingqiu?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'In truth, ___ wishes that he could fit in more, but he is often forced to reject the invitations of others on account of his need to control his abundance of yang energy.\\nOf these practices, he finds one particularly incomprehensible: hot springs.\\nBathing and "relaxing" in steaming-hot water? Even the sound of that scares him a hundred times more than freezing in a lake on Dragonspine.\\nHowever, he has also heard everyone sing yearning praises of these hot springs, praising their comfort, and asserting that they become more so the hotter they are, and that one is filled with energy for a whole week afterward.\\n___ still doesn\'t know if this is true or if people are just teasing him.\\nAnd he would have dared to try it out, if not for the ever-present problem of his pure-yang spirit.\\nXingqiu once asked him this:\\n"If you were able to master your yang energy and rid the world of all evil spirits someday...what would you do after that?"\\nThis seemingly off-the-cuff remark troubled ___ deeply.\\nPerhaps he had indeed missed out on a lot in life on account of his condition.\\nBut he doesn\'t regret spending time. If one way of living doesn\'t work, he just needs to find himself another — and in any case, he already has his answer.\\nIf that day comes, well, he\'ll go to the hot springs then.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Field Guide to Demons and Beasts',
      title2: null,
      text: "The tomes that ___'s family has passed down from generation to generation detail every evil spirit they have ever subdued.\\nFrom little critters to the monstrous demons found in tall tales of horror, their varieties are almost dazzling.\\nIt was one such terrifying story that inspired ___'s vow to rid the world of evil spirits.\\nBut as far as he is concerned, inheriting these books has... also proved inconvenient.\\nOther than textual descriptions, the books also contain illustrations of said evil spirits that carefully detail their unique characteristics — even if the artist may not have been the greatest talent.\\nBut ___ has never seen an evil spirit in his life. Unwilling to break with this artistic tradition, he was at a loss.\\nUltimately, he would attempt to use his imagination to draw some suitably strange images.\\n—Thus did the Field Guide to Demons and Beasts grow ever more exotic. Best not to think too deeply about that seven-winged, five-legged chicken-beast or that half-fish, half-hilichurl demon.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '"Those other exorcists at least have the courtesy to wave their swords or tack on some talismans. You just sat here for a while, and now you say you\'re done, and that I should pay you? Who are you trying to fool?"\\n___ faced a great deal of suspicion when he first took up the role of an exorcist.\\nHe immediately faced one big hurdle: it was a lot easier to prove that "evil spirits are present" than not.\\nOf course he would seem a charlatan even compared to "exorcists" who just went through the motions.\\nWith all the ability in the world but no place to use it, looked on with suspicion, and needing to suppress any passionate impulses...\\nThose who eventually apologized to him were also few.\\nBut even so, ___ would not go with the flow, and use some fancy act to cover for his real method of conducting exorcism.\\nEven with his unique composition posing countless obstacles for him, ___ has never once considered giving up.\\nOne day, he will become the greatest exorcist in Liyue, control his abundance of yang energy, and rid the world of evil spirits.\\nPerhaps it was this resolve that earned him the gods\' favor — that said, the Vision granted to ___ was one of "Cryo" rather than "Pyro."\\nAs to which of his goals it was that the Vision responded to, that is also a mystery.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
