export const dionaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Diona_Hello',
      text: "___, bartender of the Cat's Tail! I charge a hefty fee for private events. Huh? You didn't come here for a drink? Hmm... Then I accept your invitation... I suppose...",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Relax',
      audio: '1101',
      text: 'Ahhh... that stretch feels good.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Thinking',
      audio: '1102',
      text: 'Hmm. Lizard Tail, Pepper, Starconch, hmm... what else do I need to create the most dreadfully disgusting cocktail?',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Waiting',
      audio: '1103',
      text: "I—I wasn't waiting for you. I just happened to be resting!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Diona_When_It_Rains',
      text: "Rain! I hate rain! ...Let's go inside... I—I'm not scared of water, I just... hate it when my clothes get wet.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Diona_When_Thunder_Strikes',
      text: "Ahh!!! Uhh, um... I'm not shaking, I'm not... Ohhhh...",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows: Playtime',
      audio: '1203',
      text: "Ooh, it's so cold to touch. Wow, it's so much fun!",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Snows: Viewing',
      audio: '1204',
      text: "Ooooh, look at the little white snowflakes dancing in the wind, to and fro, and... whew, isn't it... beautiful! C'mon, c'mon c'mon, sit with me... Watch...",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Sun Is Out',
      audio: 'VO_Diona_When_the_Sun_Is_Out',
      text: "Come on, let's go bask in the sun a bit~ ...If you aren't coming, I'll just go by myself~ ...Last chance! Are you coming or not!?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: 'VO_Diona_Good_Morning',
      text: 'Morning~ Can you hand me that can of salted loach from the cabinet? Time to destroy the wine industry!',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon: Strange Noises',
      audio: '1002',
      text: 'Wha— Ugh, no! You heard nothing!',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon: Canned Food',
      audio: '1005',
      text: "Uh, I was saving this can of fish for when I was really hungry. Stop looking at it like that! ...Mmm, okay, I'll let you have a little taste, but nothing more!",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: 'VO_Diona_Good_Evening',
      text: "Aw, I failed... Ugh, again... Everyone loved my drinks! Gah... Don't try to comfort me. I—I don't need comforting!",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: 'VO_Diona_Good_Night',
      text: "Without cat vision, will you be okay walking home in the dark? If you need me to escort you... What? Th—There's lights? Pff, well who said anything about escorting you? Go on now.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___',
      audio: 'VO_Diona_About_Diona',
      text: "My ears and tail are no prop, they're real. Proof of my Kätzlein bloodline. It's only weird to you cause you've never seen it before. Wh—Why are you looking at me like that? Fine. You can touch my ears for a second, but the tail is off limits!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Drinks',
      audio: '2002',
      text: "You want a non-alcoholic drink? No, that's not difficult, but it's meaningless! It doesn't have anything to do with my grand plan of destroying the wine industry of Mondstadt. I won't waste my time on such a drink, hmph!",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: VIP Channels',
      audio: '2003',
      text: "Here! I call this Fantastic Summer-Serendipity Coral Sparkling Tea, I just made it one day when I was bored... Huh, you say it's popular? People are lining up to buy it? Don't be ridiculous.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: The Need to Chat',
      audio: '2004',
      text: "Well, if you ever feel lonely, you can chat with me. I know lots of cool things~ I'm a good... what's that called... chatting partner! Yeah! A good chatting partner, come chat with me... lots... ...okay?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About Us: Curiosity',
      audio: '2005',
      text: "What's that!? What's that!? Let me see! Maybe I can add it to my next cocktail to give it a dreadful taste... Huh? It's just a strange-looking mushroom, how boring...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '19': {
      title: 'About the Vision: Heirloom',
      audio: '3001',
      text: "How did I get my Vision? Simple — everyone in the Kätzlein lineage gets one. ...Huh? Then why doesn't Draff have a Vision? Uhh... Oh no, the cat's out of the bag! Eek!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '20': {
      title: 'About the Vision: Origin',
      audio: '3002',
      text: "Why should I tell you!? Hmph! ...*sigh* Since you won't stop asking... and since we are friends, I'll tell you: One time, my daddy went missing on a hunt in a big storm. All I could think of was finding him, saving him... That's it, are you happy now?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '21': {
      title: 'Something to Share',
      audio: 'VO_Diona_Something_to_Share',
      text: "Hey, do you think there are any exotic plants on Dragonspine? Maybe something with a deadly bitterness, or something that numbs your mouth upon contact? I'm going to pick a lot! And then... hehehe-hee-hee...",
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'Interesting Things',
      audio: 'VO_Diona_Interesting_Things',
      text: "When it comes to butterflies, I'm the best at pouncing on— err, catching them. Hey, not in a fun way! I catch butterflies to add a nasty taste to my cocktails. I'm not a cat! Meow! *hiss*",
      tips: '',
      tasks: null,
    },
    '23': {
      title: 'About Diluc',
      audio: 'VO_Diona_About_Diluc',
      text: "Diluc... I can't stand him! If there was no Diluc, there would be no Mondstadt wine industry; if there was no Mondstadt wine industry, Daddy wouldn't drink; and if Daddy didn't drink... he would keep me company. Ohhhh...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaeya',
      audio: 'VO_Diona_About_Kaeya',
      text: "How is it that even a captain is a disgusting boozehound! You know, that guy who's got that laugh! He downs drink after drink. Ugh!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Venti',
      audio: 'VO_Diona_About_Venti',
      text: "Venti? I'm not familiar with him... He's a bard? Oh, he must be that guy who sings tunes to entertain the drunkards. Well, then I don't like him, no no no...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Barbara',
      audio: 'VO_Diona_About_Barbara',
      text: "How come all my fans are drunk middle-aged men, while Barbara's are all young people...? Hmph! So stupid. Forget it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Jean',
      audio: 'VO_Diona_About_Jean',
      text: "Acting Grand Master of the Knights of Favonius... A rare, mature adult who doesn't drink... But perhaps a little too earnest, cause is it just me, or are the Knights overdoing it a bit on protecting me?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Albedo',
      audio: 'VO_Diona_About_Albedo',
      text: "Alchemy genius? Hmm... I wonder if he knows of a way to finally help me make a drink that people don't like?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Lisa',
      audio: 'VO_Diona_About_Lisa',
      text: "Lisa is so nice and gentle! But... how can such a gentle person also be a regular drinker!? Ohhhh... Why!? ...There's really no hope for Mondstadt, is there?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Xiangling',
      audio: 'VO_Diona_About_Xiangling',
      text: 'Xiangling once gave me a "so-awful-it-goes-with-nothing" food combination she came up with, saying how it tasted absolutely terrible, blah blah blah... It didn\'t work, no use at all. All my little cat ears heard that night was "One more cup of that good stuff!" *sigh*',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Klee',
      audio: 'VO_Diona_About_Klee',
      text: "Every time Klee wants to play with me, I take her somewhere far from the tavern. Alcohol and explosives... yeah, that's a dangerous combination! I mean, do I want to destroy the wine industry of Mondstadt? Yes, but not in that sense!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Her Father',
      audio: 'VO_Diona_About_Her_Father',
      text: "I adore my daddy more than anyone else! He's the greatest! But... Daddy after he drinks, ugh... Argh! I must bring an end to the wine industry of Mondstadt, and soon! No time for chit-chat!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Life as a mixologist is very busy! When I'm not at the tavern, I'm out collecting ingredients for new recipes. So... So unless something is urgent, don't bother me.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'More About ___: II',
      audio: '5002',
      text: "You wouldn't ask me to meow like a cat, like those boozehounds at the tavern do, would you? I wouldn't do it, no way! I'm not some little house pet that just shakes my ears real cute and stretches my back! I'm... I'm ___, Destroyer of the Wine Industry!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '35': {
      title: 'More About ___: III',
      audio: '5003',
      text: "\"How did the Destroyer of the Wine Industry become the Cat's Tail's mascot...?\" Y—You're asking this just to make fun of me! Ohhh, you're awful! I won't be giving YOU any more drinks, not even water.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '36': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Don't, don't make me angry. I'm pretty tolerant, but don't even try to mess with me. I'm warning you, I bite when I get angry! Meow!!! ...But maybe I'd let you off easy, no bites...",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '37': {
      title: 'More About ___: V',
      audio: '5005',
      text: "You and me... we're good friends now, right? I kind of remember having a friend like this before, but maybe it was a dream... Here, give me your hand. Ahh... Hmm, nice and warm... Very nice... please don't leave me, and become another dream.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '38': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "I enjoy hunting. I'm especially good at tracking down prey! But Daddy says that the wild is dangerous. One should only go deep into the forest with a reliable adult. ...You're a reliable adult, right?",
      tips: '',
      tasks: null,
    },
    '39': {
      title: "___'s Troubles",
      audio: '6002',
      text: 'How, oh how can I make awful-tasting drinks...? I had high hopes for the soy sauce, milk, Jueyun Chili, and Dandelion Seed cocktail — my most nightmarish combination to date! But even that was met with praise at the tavern. "This is Little ___\'s best drink yet..." Grr! But I won\'t give up...',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: 'VO_Diona_Favorite_Food',
      text: "I like, no, LOVE to eat fish! The fish Daddy cooks is the best, a purrfect main course! ...But eating fish as drunk food, that's absolute blasphemy!",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: 'VO_Diona_Least_Favorite_Food',
      text: "Carrots, potatoes, onions, tomatoes... I don't like the taste of any of those vegetables. ...In fact, I don't eat vegetables at all!",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Mmm! I just wanna ask you this... Will you bring more of it next time?',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "I'll admit, that was pretty sweet... but that doesn't mean I haven't had sweeter.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Hey... What do you take me for, some sort of stray cat!?',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: 'VO_Diona_Birthday',
      text: "Here you go — fried fish with my special sauce! ...Relax, I didn't add anything strange! My cooking is actually really good when I want it to be — stop talking and try it already! Hmph... that's better... Oh, and uh, happy birthday.",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "A cat's eyes can see even the most elusive prey in the dark.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "A cat's ears can hear even the softest footsteps on the ground.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "A cat's legs can climb even the tallest tree in all of Teyvat.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "A cat's nose can smell those people they are familiar with and like... Ahh!? You're mistaken, how could I say something like that... Ohh...",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Hey-yah!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Pew-Pew~!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'On the rocks!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Shaken and stirred!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'Scratched ya!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Think you can bully me?!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: '___ Special!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "Can't handle your drink? Hmph!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Look at you, boozehound!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: "Ha, I'm here.",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: "Let's go, let's go!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Sprint End: I',
      audio: '710001',
      text: 'Phew.',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Sprint End: II',
      audio: '710002',
      text: 'Phew, hoo.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Deploying Wind Glider: I',
      audio: '800001',
      text: "I'm flying!",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "If it doesn't ruin a drink, it isn't treasure!",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'So glittery... Must... control... urge to pounce...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Potential treasure... *sigh* Alright curiosity, you win again!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Low HP: I',
      audio: '410001',
      text: "I won't accept defeat!",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Meow...!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Low HP: III',
      audio: '410003',
      text: "It's not over yet!",
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Be more careful!',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Take a breather!',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Bleugh... I smell wine.',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Fallen: II',
      audio: '500002',
      text: "Spring fairy... ugh... Don't leave me...",
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Can't keep my eyes... open...",
      tips: '',
      tasks: null,
    },
    '75': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Got me that time...',
      tips: '',
      tasks: null,
    },
    '76': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: "Where'd that come from!?",
      tips: '',
      tasks: null,
    },
    '77': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'The hunt begins!',
      tips: '',
      tasks: null,
    },
    '78': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Huh, need my help as usual?',
      tips: '',
      tasks: null,
    },
    '79': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Hehe, leave it to me!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Whenever a guest walks into the Cat\'s Tail, they will immediately glance in the direction of the bar.\\nBehind it often stands a girl with mildly-twitching cat ears, cocktail shaker in hand, and an unhappy look on her face.\\nThis is the mixologist ___, ascendant star of Mondstadt\'s wine industry, and the greatest challenger to its traditional powerhouses.\\nHowever, she does not make these wonderful cocktails on purpose — indeed, quite the opposite.\\nHer mixing methods can seem a little "inscrutable" to an outsider. To herself, ___ tries nothing less than her hardest to ruin that hateful grog.\\nBut no matter the drink, it will turn out to be an unimaginably sumptuous brew so long as it passes through her hands.\\nThis is a "blessing" she has received, though that blessing is a huge headache for her.\\nFor this mixologist proclaims herself to be the "Wine Industry Slayer," and her final objective is the utter destruction of Mondstadt\'s entire wine industry.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Coming to the Cat\'s Tail to serve as its bartender was really a prank on ___\'s part, the first step in her master plan.\\nWhen patrons came in, they would "enjoy" her look of disgust as they got ready for the "___ Special"...\\n"Hmph. Here, drink this Sea-Salt Lizard, and kiss your life as an alcoholic goodbye..."\\nSo she would say, thus ruining these boozehounds\' appetites.\\nAnd yet...\\n"*glug*... *glug*... Wow, I have never had such a wonderful drink! Can I get a refill, miss?"\\n"...You want a refill!?"\\nTo this day, ___ has struggled with her unbroken record of mixing fine drinks. Unable to accept defeat, she has yet to give up on her dream of producing something truly disgusting.\\nHowever, the results are always the same, and the Cat\'s Tail remains a popular watering hole, with its pleased patrons singing praises unending of her skill.\\nAll poor ___ can do is puff up her cheeks, tears forming in her eyes as she grumbles:\\n"Just you all wait!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "___'s father, Draff, is the best hunter in Springvale.\\nWith a resolute face, honed hunting techniques, and calm judgment calls, he fully deserves to be the leader of the huntsmen of Springvale, and is an example to them all.\\nIn ___'s young mind, her father was her shining, perfect idol, the person she wanted to be.\\nAnd that was also why she cried her heart out the day the pedestal she had put her father upon abruptly shattered.\\n\"When he's drunk, he's like a wild boar rolling about in the mud!\" So she said, her eyes ringed red.\\nBut ___ was not ready to blame this on her father's terrible drinking habits, for how could such a great father have such faults?\\n\"It's the wine's fault! It bewitches people and makes them stupid!\"\\nThis is the source of ___'s hatred for alcohol, and the beginning of Cat's Tail's turn in fortunes.\\nThat said, Margaret, the owner of Cat's Tail, had never expected any of this to happen at all. Rather, she had a much simpler reason for hiring ___.\\n\"What choice did I have? She's just too cute.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Many patrons believed that ___\'s feline ears and tail were part of her uniform as a bartender.\\nThis persisted until one day, when one particularly plastered fellow tugged her tail out of curiosity... only to find it unexpectedly warm and soft.\\nThat day, ___ turned the tavern upside-down.\\nThese feline features are the hallmarks of those with Kätzlein blood in their veins, and it is an exceedingly rare sight in Mondstadt.\\nOther than such aesthetic similarities, ___ and her father Draff also owe their prowess on the hunt to this ancient bloodline.\\nInfiltration, archery, climbing, and dodging... ___ required no teacher for such skills.\\n"Ah, yes, and she also has a pair of eyes that can see well in the dark."\\n"As for weaknesses... She bites when piqued, so please be careful."\\nThus did Dr. Edith write of ___ in her notes for "Studies Into Bloodlines Strange and Unfamiliar."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: '___\'s appearance did indeed have an impact on Mondstadt\'s alcohol industry.\\nThe Dawn Winery\'s long-held monopoly was broken overnight by this unexpected ambush from Cat\'s Tail, and the man put in charge of the winery\'s business, Elzer, found this unacceptable.\\nA calculating veteran of many industrial battles, Elzer considered poaching this key figure, never realizing that ___ considered the Dawn Winery a sort of "final boss" to be defeated in her quest.\\n"This marvelous and bold method of preparation must be the secret of these flavors, yes?"\\n___ simply looked at the white-haired man who had just sat down in front of the bar, rank displeasure in her eyes.\\n"Ah. Simply exquisite. I can just feel your incomparable passion and love for wine."\\n___\'s hand started to tremble as it held on to her cocktail shaker, and detecting the change at once with his sharp gaze, Elzer understood immediately.\\n"If a brilliant bartender as yourself were to grace the Dawn Winery with your cooperation, we shall be able to bring Monsdtadt\'s alcohol industry to heretofore unseen heights!"\\n...When Diluc questioned Elzer as to the story behind his bandaged hand later, he was uncharacteristically hesitant to say anything.\\n"I... I was bitten by a cat."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'There is a legend about a "spring fairy" that circulates in ___\'s hometown.\\nThe fairy once saved a mother and son who had despaired beside a well, filling the barren hole with rushing waters that pooled and formed a spring. The child, deathly ill, was miraculously healed by those spring waters.\\nMany people came to catch a glimpse of these blessed waters, and built a settlement around it, and left it not thereafter. Over time, this gave rise to the small town known as Springvale.\\nNowadays, few are left who believe that this is any more than a mere legend, and some even dismiss it as myth-making for tourism\'s sake.\\nOnly little ___ believed in the existence of the spring fairy, and on nights when her father was in a deep stuporous sleep, she would speak to the moon reflected in the spring water\'s surface.\\nThese were her earnest feelings, innocent and wonderful — feelings worth answering.\\nThat was what the spring fairy believed.\\nSo, ___ would make a curious friend, a companion whom she could bare her feelings to and sometimes assuage her loneliness.\\nOn the night of ___\'s seventh birthday, as the moonlight reflected off the spring and upon her face, she heard the soft voice of the spring fairy.\\n"I will bless you, daughter of hunters, for your days ahead, and as a farewell. May your cup always run over with the sweet wine of celebration. May it always be refreshing as springs of ever-melting snow."\\nFrom that day on, the spring fairy would never appear before ___ again, and she left those memories behind, consigning them to her childhood dreams.\\nTill today, she has yet to realize that her troublesome constitution has anything at all to do with that dream.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Cold Cocktail Shaker',
      title2: null,
      text: "___'s father Draff is also interested in mixing the occasional drink.\\n___'s tail would wag from side to side of its own accord as she watched her father rocking the shaker back and forth at night.\\nBut young ___ also found that her father would wind up particularly drunk on such nights, becoming dead to the world before he could even finish her bed-time story.\\nThus, when Draff went out to hunt one day, she hid the shaker, squirreling it away in the deepest place under her bed.\\nUnexpectedly, her father didn't bother looking for the lost shaker at all. He simply brought a new one back the very next day.\\nWhen ___ went to Cat's Tail to try out for the role of bartender, Margaret noticed how the cocktail shaker ___ had with her looked wholly unsuited for her style.\\nEver skilled with handicraft, Margaret would give ___ a cocktail shaker equipped with a lovely cat's tail as an induction gift.\\n\"Now, this suits you far better,\" Margaret said with a satisfied nod.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '___\'s antipathy towards alcohol is not "hate" per se. Instead, it can be considered a form of "avarice."\\nShe wishes for her father to always be the man that she admires, and she treasures every moment that she spends with her family, unwilling to "share" her happiness with the wine.\\nThere was once a storm that lasted for three days, and for those three days, her father, who had been out hunting, did not return.\\nThe awful weather prevented the search parties sent by the Knights of Favonius from making much headway, and soon the dread of "loss" began to hang over ___ like a shroud.\\nIf she could not even stand to "share," how could she bear having something utterly "stolen" from her?\\nShe burst out the door and into the tempest, and the waters that stood in her path were frozen by some power she did not recognize.\\nUsing her superlative tracking skills, she found her father under a broken gorge.\\nWith the help of the other hunters, she returned home with her father, and only once she realized that he would be fine did she finally smile again.\\n"Do you... want me to mix you a drink? It\'ll numb the pain a little..."\\nThat was probably the first time she ever mixed a drink in a normal fashion.\\n"Ooh, it\'s so refreshing. It\'s wonderful! Hahaha—Ouch..."\\nGetting to drink a cocktail that his daughter had made was probably a better anesthetic by far than the alcohol itself.\\nStill, ___ gaining power over Cryo did not help reconcile her to wine at all.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
