export const freminetVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Freminet_Hello',
      text: "Hello, my name's ___, I'm a diver... Oh, no need to shake hands. I mean, no need to be so formal. Ahem, if you need help surveying underwater ruins or salvaging materials, I can be of some use to you. But for anything else... You might find me a disappointment.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Ocean Depths',
      audio: '1101',
      text: 'I want to spend some time at the bottom of the sea... In peace and total silence.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Principles',
      audio: '1102',
      text: "It's easy to fix a machine when you know how it's built and how it works. But people... they're much more difficult.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Home',
      audio: '1103',
      text: "Wherever the tide takes me, so long as the light of the hearth still shines, I'll always have a home to return to...",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Freminet_When_It_Rains',
      text: 'I always get so gloomy when it rains...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: 'VO_Freminet_After_the_Rain',
      text: "The rain's stopped? Okay, that's good.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When Thunder Strikes',
      audio: 'VO_Freminet_When_Thunder_Strikes',
      text: "Don't be scared, Pers. I'll keep you safe.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Snows',
      audio: 'VO_Freminet_When_It_Snows',
      text: 'Maybe I should put on my diving helmet to... keep me warm...',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: 'VO_Freminet_When_the_Wind_Is_Blowing',
      text: "I'd rather be diving in the sea.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: 'VO_Freminet_Good_Morning',
      text: "Morning. Do you have an assignment for me today? If not, I'll head out.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: 'VO_Freminet_Good_Afternoon',
      text: "All the components look intact. Maybe it's just a worn-out spring? If so, that's an easy fix... Oh, sorry, I was... Did you say something?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: 'VO_Freminet_Good_Evening',
      text: "Want a bowl of seafood soup? It's made with shrimp and shellfish caught earlier today. I'm no cook, but the ingredients are fresh, so... it shouldn't taste too bad.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: 'VO_Freminet_Good_Night',
      text: "You go ahead, I'm gonna stay up and read for a while. Hmm? What am I reading? It's, um... it's about diving. There's a bunch of skills that I still need to... Anyway, night!",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Diving',
      audio: '2001',
      text: "As you know, diving is one of the few things I'm any good at. I spend more time among the Tidalga than I do talking to people. They don't ask you questions or act disappointed, they just float there quietly with you... The underwater world is much simpler than the world of dry land.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Clockwork Penguin',
      audio: '2005',
      text: "Whenever I feel lonely at night, Pers is the one who's always there for me. I thought that maybe some other kids might want a toy for company too, so I made a bunch of clockwork penguins and took them to Leschots's workshop to put on sale... Apparently, the customer feedback was good, but they didn't sell too many of them. And most of the buyers were adults...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Orders',
      audio: '2003',
      text: "Orders to me are like a clockwork spring driving me forward, and I don't know what to do with myself without them. So if there's anything you need me for, please don't hesitate to ask.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Companionship',
      audio: '2002',
      text: "Tell me a bit more about yourself. Your hobbies, favorite food, favorite color, what animal you'd like to have as a pet... If you and I are companions, it means we're connected, more closely than gears in a machine.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: 'VO_Freminet_About_the_Vision',
      text: "After I got my Vision, I didn't need my helmet to go diving anymore. But... I can't bear to be without it. It cuts me off from the noise of the outside world, and makes me feel safe. My Vision, Pers, and my helmet... I draw my strength from them every time I take a breath.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: 'VO_Freminet_Something_to_Share',
      text: "If you look up at the sky from far enough underwater, even the sun is soft on the eyes. That's why I like it down there.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things: Beryl Conches',
      audio: '3003',
      text: "I've seen lots of Beryl Conches down in the depths. The patterns are so intricate, I often lose track of the time just staring at them. These fossils are all that's left of these beautiful creatures... I wonder how long before the rest of the world becomes part of this underwater museum, too?",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things: Lumitoile',
      audio: '3004',
      text: "Lumitoile attach themselves to many things. Sometimes on the reefs or docks, but most commonly on large underwater buildings. Do you think they're drawn to humans like Cicins are drawn to the light?",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About "Father": Tears',
      audio: '4001',
      text: '"Father" doesn\'t like it when children cry. "Father" says tears are the product of emotion and weakness. So when "Father" scolds me, I hold it in until I\'m underwater, where no one can hear me cry. At least I have the Romaritime Flowers to keep me company.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About "Father": Teaching',
      audio: '4002',
      text: 'When I was little, I was taught that we should be ready to give our lives for our family. But when "Father" took control, this philosophy changed. "Father" said that every one of us is important, and we have to value our own lives, be our strongest selves, and stand on our own two feet in this world... But actually, all of that\'s much harder than just following orders.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '23': {
      title: 'About Lyney: Magic Shows',
      audio: '4003',
      text: "At home, Lyney's always showing me his magic tricks. Whenever I smile, he grins excitedly and says the audience is definitely going to love this one... Do I really smile so rarely?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Lyney: Mask',
      audio: '4004',
      text: "Lyney is our team leader, and acts like everyone's older brother... But I can tell that he puts on a brave face sometimes. I tried to talk to him about it once — told him that he doesn't need to wear a mask all the time. But he denied it, and we ended up having an argument... Since then, I've never brought it up with him again.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '25': {
      title: 'About Lynette',
      audio: 'VO_Freminet_About_Lynette',
      text: "If you assigned Lyney and Lynette with the same mission, they'd both do an outstanding job. But not me. Lynette is always comforting me, saying that everyone has their strengths, and how everyone relies on me to fix things around the house when they break down... If only I was half as good at anything else.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Neuvillette',
      audio: 'VO_Freminet_About_Neuvillette',
      text: "One day when I surfaced after a dive, the Chief Justice was just standing there alone on the beach. I don't know whether he had something on his mind, or was just enjoying the view... Obviously, I didn't ask. I only locked eyes with him for a split-second before disappearing back underwater. Thinking back, I must have looked so guilty... *sigh*",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Furina: Avoiding the Question',
      audio: '4007',
      text: "Uh... I'm in no position to give a well-rounded opinion on the Hydro Archon, so... I'll pass. I mean, I've only seen her a few times... so I'm sure I have a somewhat skewed view of her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Furina: Verdict',
      audio: '4008',
      text: "...Okay fine. I've seen what the Hydro Archon's like when she's sitting in the audience. In my view, she's a very charismatic speaker, but it's her silences that intrigue me more. Her eyes... they're like the darkness at the bottom of the ocean. Hiding a deep secret, afraid of anyone ever getting close to her... Ah! Sorry, I... I let my imagination get the better of me.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '29': {
      title: 'About Navia',
      audio: 'VO_Freminet_About_Navia',
      text: "Lyney told me everything. I'm so grateful to you and Navia for your warmth and generosity. Please pass on my thanks when you see her... Huh? Tell her myself? ...Uh, I, uh... Ooh, I've suddenly got stomach cramps — sorry, gotta dash.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '30': {
      title: 'About Charlotte',
      audio: 'VO_Freminet_About_Charlotte',
      text: "For some reason, Charlotte never believes me when I say I'm just an ordinary diver. She's convinced that my past is full of news stories waiting for her to dig up... Am I really that bad of a liar?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Clorinde',
      audio: 'VO_Freminet_About_Clorinde',
      text: "I owe Clorinde my life, but she says she doesn't want anything from me in return... It's not a nice feeling, having put someone out so much, and only being able to offer empty thank-yous in return.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '32': {
      title: 'About Chevreuse',
      audio: 'VO_Freminet_About_Chevreuse',
      text: "I hear that Chevreuse is a regular customer of Beaumont Workshop. She always purchases the most expensive and advanced components for her musket. If I make enough Mora, maybe one day I can afford to upgrade Pers's components.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: I',
      audio: '5001',
      text: "I'm sorry, I can't really think of any good stories to share... the ones I do know will just bring down your mood.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'More About ___: II',
      audio: '5002',
      text: "My past... If you promise not to look at me, or you'll let me wear my diving helmet... Maybe then I could try to tell you a little more. Personality's one part of it, but... the bigger reason is that I've been avoiding my past for so long now, it might be hard to talk about...",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '35': {
      title: 'More About ___: III',
      audio: '5003',
      text: "I read in a book that when people die, they turn into stars and watch over us from the sky... I hate my real father. He abandoned my mother and me, so I don't care about him. But... if my mother looks down from the sky and sees that, after all this time in his new home, the child she protected with her life is still so timid that he can't fend for himself... Will she be... disappointed in me?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '36': {
      title: 'More About ___: IV',
      audio: '5004',
      text: 'I don\'t like thinking about my time in the House of the Hearth under the previous director. All I\'ll say is... My habit of retreating into the sea started back then. "Father" changed not only me, but my view of our family, too. Then Lyney and Lynette joined the family... and for the first time ever, I gained some genuine companions.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '37': {
      title: 'More About ___: V',
      audio: '5005',
      text: "I once swore an oath that I would do whatever it takes to protect this family, and never look back. Now, I stay true to this oath not because it's the previous director's orders, or because it's what \"Father\" expects of me, but because it's my own desire. Please keep our family's secret safe... so that I can keep my promise.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '38': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "Apart from diving, my main hobby is dismantling mechanical things and modifying them. I also collect spare parts, and sometimes I build new clockwork toys out of them. ...Pers? No, Pers is more like family to me. We grew up together... No, I'm serious. I'm always tinkering with it to add more functionality... I truly hope that a day will come when Pers can fly free into the sky.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: "___'s Troubles",
      audio: '6012',
      text: "...That's a tough question. I don't have any critical issues that need addressing, but at the same time, there's a long laundry list of minor things which all take their toll. If I was a clockwork toy on the shelf, I wouldn't even know where to start trying to fix me up... But at the end of the day, I guess it all comes down to one thing... I'm just too weak.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: 'VO_Freminet_Favorite_Food',
      text: "Seafood. Mainly fish and shrimp, crab's okay too. I'm really glad that Lyney and Lynette share my tastes, because it means we can eat meals together... I don't mind how the ingredients are cooked, though. I leave that decision up to them.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: 'VO_Freminet_Least_Favorite_Food',
      text: "I can't handle coffee. More than half a cup and before long, my heart starts racing and I can't calm my breathing down. Everyone says that coffee can boost your energy levels, but to me, it's torture...",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "It's good. So good, I don't want to eat all of it in one go.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Is cooking one of your hobbies? It shows. I can taste how much care you put into these delicious meals.',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Sorry... For a moment there I had the urge to run for my life. But that wouldn't be fair to you.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: 'VO_Freminet_Birthday',
      text: "Would you be willing to come with me somewhere? There's this place I know where the scenery is spectacular. I think it's even more magical than a fantasy novel. I have a secret hideout there, and I keep some glowing sea creatures as pets... I just want to give you a birthday experience like you've never had before, and then give you my birthday wishes... Will you give me the chance to do that?",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Are... Are you sure?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "You didn't have to do this for me, you know. I'd obey you regardless.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Your time and energy is a precious resource. Shouldn't you... spend it on someone else?",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "How can I ever repay you for this? I don't know what to say, I... I don't have much practice at this, and right now I'm terrified of saying something stupid and upsetting you... and making you regret this whole thing... I'm sorry, is it okay if I just... say nothing, and just stay here with you for a while?",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Pers!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Get in gear.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Frost is coming.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Going under.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Commencing cleanup.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Dead reckoning.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "If there's any scrap metal or parts you don't want, I'll take them.",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "There's a lot of treasure here.",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Sort the items by type and store them for future use.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: "I've had worse.",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I can take it...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Just keep breathing...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "You're wounded...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Um, maybe... You should...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'No home... to return to...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Sinking... feeling...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: '"Father"...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Oh no...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Please, no...',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Yes, take me with you.',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'At your command.',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Well, I've got nowhere to go...",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Whether you're a tourist visiting Fontaine for the first time or an adventurer who's set their heart on finding legendary treasures, you're sure to be captivated by the enchantments of the underwater world. But those who attempt to explore the depths without first undergoing rigorous training or making the necessary preparations are gambling with their lives. Treacherous underwater currents, unexpected bodily reactions, and monsters lurking in the deep... Peril always comes without knocking. Seeking the help of a professional diver is always a wise choice.\\nIf you ask people who's the most talented diver around, you're likely to hear the name of ___. Even old veterans, bronzed and toughened by long exposure to the elements, never tire of lauding his skills. They speak not only of his familiarity with Fontaine's complex hydrological systems, but also of his prowess in coping with different underwater environments and seasonal conditions, as well as his expert control over his breathing. He seems to swim wherever he pleases — even through caverns deep down on the ocean floor, where no one else dares to venture...\\nWhen many people hear this, they suddenly think of something or other that ___ could do for them. But no matter how great the promised rewards, the veterans always respond the same way — with a shake of the head and a regretful sigh.\\n\"The boy wouldn't hear of it... He's a nice lad, just a bit too shy.\"\\nThe conversation usually stops here.\\nAs ___ sees it, other people's compliments are as capricious as the weather. He finds it hard to fathom their true intentions, and is constantly worried that he'll put his foot in it by saying something wrong.\\nPerhaps his true friends are the Tidalga and Romaritime Flowers that he spends so much time with. They hold a much dearer place in his heart than do reputation and reward, which float around on the surface. When he dives, he stays silent for long periods of time in the company of his old friends, and lets the silence swallow up his fears and anxieties. In so doing, he lets out all the things weighing on his mind, all the things that he can't say to anyone else.\\nThe reason he chose to dive was that simple — to find some peace and quiet, and escape everything happening in the world above.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Even before he received his Vision, ___ used to love wearing his diving helmet and exploring the underwater world like a penguin.\\nHe was never a very talkative child, and whenever something upset him he would plunge into the ocean, leaving his worries on the dry land far above. Over time, the quiet seabed became like a cradle to him, somewhere where he could curl up and feel safe. As the rings of a tree grow outward with each passing year, so too did his curiosity for the underwater world. He listened to the ocean currents with his body, and with each breath grew closer to the water around him. He committed every aspect of Fontaine's hydrology to memory, as if he were memorizing roads around a new home, albeit with far more relish. Eventually, he discovered a place of extraordinary beauty which captured his heart, and built a little secret underwater base nearby. Here, he could let his sunken emotions shine forth with a radiance akin to that of a Lumitoile.\\nTo this day, when faced with a particularly thorny problem, ___'s first thought is to escape to this deep blue sanctuary — so vast and magnanimous that it could embrace all things.\\nFree, tranquil, safe, and content... If ___ were to tell others how the underwater world makes him feel, he would most probably be met with more than a few raised eyebrows.\\nBut ___ would never do this. In his mind, this is his ocean, and his alone. These feelings, hidden deep in his heart, are like sunken treasures buried in the depths.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "In the eyes of an onlooker, ___ doesn't have much of a presence, and comes across as cold almost to the point of being pessimistic. He's always silent, alone, and doesn't seem to enjoy the company of his peers. Compared to his older brother — the legendary Great Magician Lyney — ___ seems as dull as a piece of old, soon-to-be-forgotten jewelry. But he doesn't care what they think.\\nA long time ago, ___ began trying to strip away excess emotions to prevent his being affected by external pressures.\\nAs if building an igloo in his heart, he piled up block after block until he had constructed a translucent refuge, and curled up inside. Clutching his knees, the only thing that gave him solace was reading fairytales.\\nIf diving underwater was a way to steal a moment of peace, then sealing himself in a sanctuary of solid ice was actually a way to stay warm.\\n___ would only ever invite his closest \"kin\" in, and even then, he'd insist on tidying up first, making sure to lock his fairytales away.\\nBy the time ___ left, he'd already turned into a clockwork toy — exquisitely made, yet silent as ever.\\nHe once found himself floating on his back upon the waters, unconcerned with his own safety, listening to the unknown songs of Violetgold Angler Gulls circling overhead. In hindsight, it was fortunate that they hadn't mistaken him for a fish...\\nIt was in that moment that he discovered how easy it was to just let the currents carry him away.\\nNo matter who was asking, and no matter what they wanted, as long as he followed orders unquestionably without a thought for the consequences — like an angler bringing home their catch — he would no longer have to face the endless cycle of castigation and punishment.\\nIn the years that children from ordinary families ran about laughing, showing off the latest clockwork toys or picking up phrases from The Steambird, ___'s heart was gradually becoming numb. Orders filled the void and became like a clockwork spring driving him forward.\\nHe used to fantasize about turning into a cold, cruel machine, driven only by the imperative to execute commands. But as he matured, he became increasingly aware of his essential weakness. He wanted to leave emotions behind, but there were too many feelings that he couldn't just cast aside. They would always come back in the dead of night, suddenly gripping him like seaweed wrapping around his limbs. His habit of avoiding problems, his worry that he would not complete his tasks well, his fear of annoying people with his lack of enthusiasm, and his dread of disappointing others — those who meant something to him, most of all...\\nHe wasn't an outstanding child, but he simply became hypersensitive to everything in the world he grew up in.\\nHe hid himself within a thick shell and yielded to his timidity, until he could only express himself underwater.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "___ was born in the Fleuve Cendre region of Fontaine. Each night he would fall asleep to the sound of drunkards belting out off-key shanties, and wake up to the shrill cries of neighbors cursing outside his window.\\n___ never met his own father, but he heard from his mother that the man was knee-deep in debt. He had little idea what all these numbers meant, and they were as hard for the little boy to conceive as a dinner in the Palais Mermonia. What he did know was that they were the reason his mother worked from dawn till dusk, day in day out.\\nWhen he was home alone, ___ would often quietly fiddle about with the few devices there were in the house — a portable lamp that never lit up, a wall clock that never ticked, and so on...\\nThese things had been lying around for as long as he could remember, as if they were guests who had stopped by for a quick rest after a long saunter, but had never woken back up. ___ found some tools and, one by one, carefully took them apart. To him, the inner structures of these mechanisms were like mysterious labyrinths. Turn this part here, and another would move as a result. Tap that bit there, and something else would spring out...\\nWhen he was with these machines, ___ felt the same way he did when he read fairytales — like he had taken a magic potion that shrunk him down to the same size as the components. He was moving through a world of cogs and clockwork parts where time seemed to pass without his knowledge. These friends of his, silent yet intriguing, kept him company through many a lonely day.\\nOne day, when his mother returned home, she suddenly heard a strange noise that stopped her in her tracks. It was the sound of their clock, which ___ had unwittingly fixed, ticking away almost as if to celebrate the new lease on life he had given it. She caressed his head and praised him, filling his heart with joy. But when he woke up the following morning, the clock was nowhere to be found. When his mother came home that evening, she brought him two slices of a type of bread he'd never had before. He still remembers the taste to this day.\\nFrom that day forth, his mother brought back all kinds of different devices for him — everything from clockwork toys to miniature clocks. ___ liked his new friends a lot, and would spend a long time \"waking\" them from their slumber, even though they always vanished the following day.\\nBut one day, when ___ ran over excitedly to greet his mother at the door, he had something very special with him — an exquisitely-made music box pendant, about the size of a person's thumb. It had been in such a terrible state when she had found it by the roadside that it was to their great surprise to discover that it still worked.\\nA beautiful melody jingled away between them, and seeing ___'s innocent face light up with pure joy, a rare smile broke out on his mother's, too.\\nThis pendant would not leave him, for every evening, his mother would carefully take it off her neck, and together they would listen to its sweet lullaby as night fell.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'One day, without uttering a word, ___\'s mother took him by the hand and led him away. As he tried to keep up behind her, little ___\'s palm began to hurt from the strength of her grip.\\n"Mom, where are we going?" He asked. She didn\'t reply.\\n"Mommy, why are you crying?" He asked her again. She suddenly stopped and let out a sob, but only a single one.\\nAfterwards, as if resolved to plunge into the freezing depths of the ocean, she took several deep breaths and continued onward. Not another tear fell, but in the oppressive silence ___ had a vague sense that an ominous current was about to crash against the reef of his future.\\nFinally, they arrived in front of an unfamiliar house. As the thick door opened, it let out a harsh creak. It was the type of door that you intuitively knew that, once closed, could never be opened again.\\nStill, his mother remained silent. It was as if her expression, weighed down by her heavy heart, had sunk into a bottomless ocean.\\n"___, correct?" Said a woman as she stepped out. "Come with me."\\nConfused, ___ looked up at his mother. He could feel the tide surging beneath him.\\nCalling herself the "director", the woman took his other wrist and began to pull him in.\\nAll of a sudden his mother\'s grip tightened, becoming even tighter than when she had led him over. ___ felt like a boat caught between two waves, completely helpless as they each pulled in opposite directions and showed no sign of letting go.\\nAt last, his mother slowly bent down, half-kneeling before him. This was what she would do each day when she said goodbye to him before leaving the house.\\n"Be a good boy," she said, kissing ___ on the forehead in the way she always did.\\nThese tender words rose up like a barrier before the jagged reef, instantly turning the raging current into a soft, warm flow.\\nSo that\'s all this is, ___ thought to himself. Perhaps, like ever and always, this was just to be a brief parting after all.\\nHe nodded to set her at ease.\\nThe director continued to pull him inside, and this time, his mother didn\'t try to stop her. Just like that, she let go...\\nFor a long time after, ___ truly believed that as long as he behaved and performed well enough, his mother would come to bring him back home. That her kind face, disappearing behind that thick door, would someday reappear. And parting his fringe, she would kiss him on the forehead once again to tell him how well he\'d done.\\nBut that day never came.\\n"Still haven\'t figured it out? You were sold to settle a debt."\\nAs he grew up, ___ started to have doubts about where his mother had gone and his own fate. After he finally plucked up the courage to ask the director, this was the heartless response she gave him.\\n"You were abandoned, child. This is the only home you have." "If you don\'t follow orders, your mother\'s safety can\'t be guaranteed..." Such were the words of the previous director, callous as spiked shackles, locking his wildest hopes inside that door forever. These invisible fetters left a mark of utter abjection on ___. In those days, the ocean depths were his sole escape.\\nEngulfed by icy-cold seawater, he always felt that little bit closer to her. After all, when those events had transpired all those years ago, had she not sunk to the bottom of the ocean herself? Yet those waters must have been far colder than any he had ever dived in.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'After "Father" replaced the previous director, ___\'s thoughts began to turn to finding his mother once again.\\nAt first, ___ assumed that she would rile up a still greater storm of brutality, for he knew that her methods were brutal, and he expected new orders to be given just as pitilessly as they had been in the past. But he soon discovered that "Father\'s" way of doing things was utterly different.\\nWith "Father," the home was a place of refuge for all the family\'s children, and as such required a collective effort to maintain. It was up to each of them to complete their tasks in the way that best suited them. Even if they failed, they wouldn\'t be subjected to the searingly painful punishments they had been previously.\\nThis taste of freedom finally gave ___ the chance to breathe deeply, and he started searching for his mother\'s whereabouts in his free time.\\nBut a long time passed and he still wasn\'t any closer to finding her.\\nPerhaps I really was abandoned, ___ thought, trying to convince himself to accept reality as he strained to summon the already vague memory of his mother\'s face.\\nBut just as he was thinking of giving up, "Father" threw him a pendant.\\n"I found this at the base of operations of those scum. Keep it." said "Father."\\n___ looked back at her, perplexed, which in turn seemed to confuse her.\\n"What it is? I\'m talking about those usurious scoundrels. It belonged to your mother..." She frowned, seeming to suddenly realize something. "What were you told about her?"\\n___ told her what the previous director had said to him, about how he had been abandoned. As he did so, she said nothing, but her eyes began to burn with wrath.\\nAfter ___ was finished, "Father" fell silent for a rare moment. "Do you want to know what really happened?" She asked, fixing him with a piercing stare.\\n___ nodded almost unconsciously. But once he had heard what she had to say, he wasn\'t sure which story he\'d rather believe.\\n"Father" told ___ that his mother hadn\'t abandoned him, but on the contrary, had acted to protect him...\\nThat year, the debt that his family owed finally reached the point where they would no longer be able to repay it. Those greedy moneylenders had not only forced ___\'s mother to hand over the house that they lived in, but had also demanded that she hand over ___ as well. But she was his mother — how could she let this happen? In the end, she had no choice but to entrust ___ to "that orphanage" — somewhere they could never get at him — and then face them alone.\\n"This was all I found. As for your mother..." As she looked at the young boy in front of her, still gripping the pendant tightly in his hands, "Father" trailed off and left the ensuing silence to speak for her.\\n___\'s head hung low, but knowing his personality, "Father" slipped out of the room without another word. The boy was left standing there, shaking as he gazed down at the pendant in his hands. It had long since rusted and could no longer produce sounds, and the clockwork components seemed to have been stained dark brown by dried blood. She must have been holding it at the very end, he thought. In his despair, ___ continued to stare at the pendant, desperately looking for even a thread of his mother\'s warmth.\\nThat evening, ___ dived down to the bottom of the ocean and let it all out. He couldn\'t remember the last time he had cried like this. Other than the Romaritime Flowers that wept alongside him, not a soul heard the sound of his sobbing, for the ocean smothered it utterly.\\nFrom that day on, his grip on his greatsword tightened. He made an oath to himself that he would never again let another member of his family meet with misfortune.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Tales of a Snow-Winged Goose',
      title2: null,
      text: '___ has been captivated by fairytales since he was a child.\\nIn contrast with the real world, the little world inside a picture book is always full of color. Castles can be made from candy, rivers from the juice of Bulle Fruits, there can be talking Hydro Crystalflies, and Redcrown Finches and ragdolls can become the best of friends...\\nWhen he closes his eyes, takes a deep breath, and then opens a storybook, ___ is able to dive into a magical fairytale world — a world where he can push the boundaries of what exists through a combination of reading and his own imagination.\\nAs he goes, he picks up on scattered phrases or illustrations tucked into the corner of the page and turns these over in his mind. He learns something new every time he reads, and loves the variety of dazzling colors and textures that different subject matters seem to evoke for him.\\n...\\nWhen ___ starts to feel lonely, "Pers the Penguin" waves to him with his black and white wings and slides around on his round little belly as if it were a skateboard. He skids along the surface of the ice until he plops into the sea, challenging ___ to a fish-catching competition.\\nWhen he\'s feeling timid, "Princess Marcotte" with the long, pink hair stares out at him through the window. He knows that when the princess was but a seed, she rode across the ocean on the claws of a crab, abandoning her birthplace for the promise of a better life...\\nWhen he\'s feeling troubled, the inimitable adventurers "Mr Fox and the Clockwork Guardsman" appear there in front of him, standing side-by-side. Mr. Fox\'s great big bottle-brush of a tail raises a cloud of dust as it sweeps the floor, causing the Clockwork Guardsman\'s nose to become all itchy, but he keeps standing there, as straight and tall as ever. "Everyone faces challenges," they say to him. "Don\'t let them win. You\'re a brave, brave kid."\\n...\\nEven as he matured and grew older, ___ still stubbornly held on to the fairytale world of his childhood.\\nHe truly believes in these beautiful stories and the friends he met in his books.\\nIn ___\'s heart, they really do exist in that poetic dreamland of his. There is a place where sadness and worry cease to exist, and all that remains is the unending sound of joyful laughter. It\'s a place where dreams come true, and justice always triumphs.\\nBut of course, he can\'t actually reach out and touch the things in this imaginary world. Perhaps he\'ll find a way someday though...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "That day, ___ and some other children were out on an underwater mission. At first, everything went perfectly smoothly, just like it had done on countless other occasions.\\nAll of a sudden, however, ___ noticed that something was off.\\nCreatures that know their own weakness always seem able to stay focused in places of great peril, and ___ is no exception. He has always been skilled at self-reflection, even to the point of picking up on minute changes in his breathing. Without them even being aware of it, his unique powers of perception have helped them evade all kinds of danger.\\n___ made an emergency gesture to his friends telling them to surface. He still didn't know what the actual peril was, but his nerves had taken hold and his heart began to beat faster and faster.\\nHis friends didn't object and, with ___ at their center, the group began to ascend.\\nFor these children, who had yet to receive the gods' favor, ascending was something that had to be done slowly. But at the same time, the feeling of unease in ___'s heart was becoming unbearable. His vision grew hazy, and he couldn't tell whether it was the reflection of some monstrous leviathan or a sign that he was on the verge of fainting.\\nNo. Wait. The diving equipment was malfunctioning! Was it just him? If not, how many of the others were affected?\\nHe tried hard to open his eyes, but he was gradually and uncontrollably slipping out of consciousness.\\nNo, I have to lead them back, he said to himself. As long as my arms and legs keep working...\\nHe began to feel sleepy.\\nHis thoughts were becoming sluggish... If this carries on, he thought, I'm never going to make it to the surface.\\nEven if I make it, what good would it do? That thought suddenly flashed through ___'s mind. I'd just go back to living day after day after day, eternally devoid of hope.\\nHe felt tired. Tired of forcing himself to keep going.\\nHe was unsuited to having so many \"family members.\" There was no real warmth or feelings between them. They were simply a motley crew of clockwork meka, each of a slightly different model and outward appearance.\\nPerhaps the seawater was where he belonged after all. To drift off into blissful sleep... Was it really so bad? He gradually let his eyes fall shut.\\nA sound suddenly jerked him back awake. ___... ___. The voice was slow, solemn, and seemed to be coming from the other end of the earth. It also carried a slight stutter.\\nPers?\\n___ stretched out his arms to a blank landscape in front of him, opening his eyes in puzzlement.\\nThere was no Pers the penguin in this underwater realm. The children had all slipped into a dreadful torpor.\\nI must save them all! ___ screamed without making a sound. So what if we're not all of the same mind? I won't abandon anyone in my family! No matter what hazards lie ahead, only with the courage to put life itself on the line will I live to see the blue sky that comes after the storm.\\nIn that moment, his body seemed to be imbued with power, and even his breathing grew easy once more. He quickly swam over to his companions, who were each of them drowning...\\nIn the midst of a tempest, he saved all of his friends — a miracle of heroism worthy of the legendary Pers from the stories he so loved...\\nIt was only then that he realized that a Vision as clear as crystal now hung from his divesuit.\\nHe never told a soul what really happened that day. After all, true heroes aren't in it for the recognition.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
