export const ganyuVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Ganyu_Hello',
      text: 'Copy that! Here is a draft Service Agreement for your review and consideration. Effective immediately, if all is in order... Ah! Wait a sec, wait a sec, I forgot to sign it... Gan... Yu... There. Right. Now... What was it you needed me to do for you exactly?',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Relaxed',
      audio: '1101',
      text: "It's so nice to de-stress.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Attentive',
      audio: '1102',
      text: 'If you lie on the grass, you can feel the heartbeat of the world.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Anxious',
      audio: '1103',
      text: 'Should we really be off work this early? There is still a lot left to do...',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains: Worries',
      audio: '1201',
      text: 'Oh good! I was just thinking that the Silk Flowers at the Feiyun Commerce Guild needed watering. The transport co-ordinators will probably moan about the muddy mountain roads again, though...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Rains: Listening to the Rain',
      audio: '1202',
      text: 'It is something of a luxury, but I love listening to the rain from the courtyard.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'After the Rain',
      audio: 'VO_Ganyu_After_the_Rain',
      text: "Oh, the sun's out. When did that happen?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: 'VO_Ganyu_When_the_Sun_Is_Out',
      text: 'Ah, the air is just right.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: "When It's Windy",
      audio: '1205',
      text: 'Ah, I love the smell of Glaze Lilies.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: 'VO_Ganyu_Good_Morning',
      text: "Morning! What's wrong, is there something stuck in my hair? ...Oh. Please don't stare at my h—hairpiece.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: 'VO_Ganyu_Good_Afternoon',
      text: "*yawn* Ugh... I need a nap. If there aren't any urgent matters, I'll excuse myself.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: 'VO_Ganyu_Good_Evening',
      text: "Look how brightly lit the city is at night! Amazing. I wonder what it's like for all the people down there... Hmm? Umm... No thanks, I think I'll pass on the night market. Sorry...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: 'VO_Ganyu_Good_Night',
      text: 'May Rex Lapis watch over you. May your dreams be peaceful and sweet.',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___',
      audio: 'VO_Ganyu_About_Ganyu',
      text: 'My job is to honor my contract with Rex Lapis by looking out for the interests of all living things in Liyue.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Work',
      audio: '2002',
      text: "I finished all my assignments early today. ...O—Overtime? I understand. I'll get right on the case.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Requests',
      audio: '2003',
      text: "I want to understand more about humans... And I especially wish to hear what you think of them. Why, you ask? Because you're... you're a bit different from most people in Teyvat, just as I am... Please, tell me what you think.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Evaluation',
      audio: '2004',
      text: "Um, so, yeah, uh, I was, uh... I was wondering what your opinion is on my work so far? Would you say I'm... more of a Common Chest or more of a Luxurious Chest? I—It's fine. I—I can, uh... I can take it.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: 'VO_Ganyu_About_the_Vision',
      text: '"With authority over a thousand comes responsibility to a thousand." Rex Lapis knows the meaning of hardship better than anyone else in Liyue — he has seen everything that has happened from ancient times to the present day, and yet he was forced to give up his entire life. Compared to him, I\'m just an everyday Vision holder with everyday responsibilities. I can\'t complain about my workload.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: 'VO_Ganyu_Something_to_Share',
      text: '"Where merchants flock and all ships dock, and over the oceans flows its stock." People say this in praise of Liyue\'s prosperity. But a city only becomes this successful through everyone playing their part diligently. That\'s the attitude I take to my work — I want to be worthy of what we enjoy here.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Facts: Name',
      audio: '3003',
      text: "I've named every single doggie living in Liyue. But they're so funny. Some of them still respond even when you call them the completely wrong name. How fascinating is that? Like, if people were to call me \"Bantu,\" how am I supposed to know they're talking to me? No way would I respond.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Facts: Qingxin',
      audio: '3004',
      text: "Qingxin flower petals are pretty tasty. Incredibly tasty, actually. The only reason I don't plant any at Yujing Terrace is because they taste so good that I worry I wouldn't be able to control myself... Huh? Bitter? Yes, they are... Isn't that what they're supposed to taste like?",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Morax: Trust',
      audio: '4001',
      text: 'I have absolute faith in Rex Lapis. It was only through his leadership that we were able to repel the monsters and subdue the sea creatures, and thus protect the peace of Liyue. The sight of him protecting the masses, and the memory of our centuries of camaraderie... I shall never forget it.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Morax: Follower',
      audio: '4002',
      text: "All of Rex Lapis' decisions prioritize the welfare of all life in Liyue. That's what I admire about him the most. I want to live up to the same standard... but it seems that the harder I try to follow in his footsteps, the more overwhelmed I get and the more mistakes I make...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Ningguang',
      audio: 'VO_Ganyu_About_Ningguang',
      text: 'Each Tianquan adds their own interpretation and amendments to the founding laws of Liyue. The current one, Ningguang, does it with unmatched efficiency, but that efficacious manner of hers draws a great deal of criticism. I suppose it is always simpler to criticize than to tolerate.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Keqing: Estrangement',
      audio: '4004',
      text: 'I cannot stand her disrespectful attitude towards Rex Lapis! But he says to me, "___, this is just the kind of person Liyue needs in this day and age." I guess I\'m not smart enough, because I simply do not understand what he means by that. I think I need more life experience to become wise enough to comprehend his words.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Keqing: Changing Perspective',
      audio: '4005',
      text: 'She came to me recently to discuss the reopening of the Bishui trade route. She even asked me what Rex Lapis would do if it were him. Admittedly, what we came up with was not quite on par with what he would have chosen. But... seeing the way she kept starting her plan from scratch over and over again, I think I started to understand her a little bit.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Xingqiu',
      audio: 'VO_Ganyu_About_Xingqiu',
      text: "You mean the boy in the blue jacket from the Feiyun Commerce Guild? He's nothing like his father and brother, doesn't seem to care about the textile business at all. Seems it's because as far as he's concerned, there are more important things for him to be doing. Of course, I'm merely speculating...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Xiangling',
      audio: 'VO_Ganyu_About_Xiangling',
      text: "Xiangling is a celebrity! Um, but... I try to avoid her restaurant. Just... because. No reason. ...Okay, fine. It's not a big secret anyway. It's because you can smell her cooking all the way from the other end of the street. And once you get a whiff, I mean, that's it. You're gone. Next thing you know, you're ordering your second, maybe third round... You just can't control it. Even though I only eat the vegetarian dishes, I don't know what it is. But that is not a road I want to go down again... Not after...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Beidou',
      audio: 'VO_Ganyu_About_Beidou',
      text: "Recently, everyone in Yujing Terrace has been saying nasty things about The Crux Fleet. But in my personal opinion, Beidou's contribution to Liyue Harbor goes far beyond what those miserable, rumor-loving heathens could even contemplate! ...Oops! I'm sorry, I... I'm not quite sure how that one slipped out...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Yaoyao',
      audio: 'VO_Ganyu_About_Yaoyao',
      text: "Yaoyao... Someone I know at the Ministry of Civil Affairs tasked me with keeping an eye on her in the city, making sure she doesn't try and sneak aboard The Crux... Oh, you want to know what the Ministry of Civil Affairs does? ...Who knows, am I right!? Heh... Who knows what they do? ...Not me...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Xiao',
      audio: 'VO_Ganyu_About_Xiao',
      text: "He seems like a bit of an outsider, socially. Probably just his personality... I can understand that, to be honest, but I'm not really about to try and get close to him. I mean... all the people he's ever agreed to team up with are no longer with us...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Yanfei',
      audio: 'VO_Ganyu_About_Yanfei',
      text: 'Ah, Yanfei... Even back when she was an innocent little girl, she would tell me that "you have to keep your promises to live a happy life." Now, she\'s grown up to be a beautiful, graceful, and highly successful young woman.\\nAlthough the work of a legal adviser is complicated, she always seems so carefree. This puts my mind at ease.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Shenhe',
      audio: 'VO_Ganyu_About_Shenhe',
      text: "I actually don't know her all that well — I've only heard bits and pieces from Cloud Retainer. From what I've heard, she can be quite ferocious. Whenever her temper gets the better of her, she is likely to start obliterating her surroundings. I wonder if maybe she's just... bored. Should... Should I recommend some work to keep her occupied?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'About Yelan',
      audio: 'VO_Ganyu_About_Yelan',
      text: "Even though Ms. Yelan is absent from work for the majority of the year, I'm sure Lady Ningguang must have her reasons for making exceptions for her. Of course, it wouldn't be my place to ask, so I don't know the details of their arrangement. I remember seeing her one day on my way back to Yuehai Pavilion, she was having breakfast with a group of people — they were all talking and laughing, eating, drinking tea... I must admit, I found myself feeling a little envious in that moment.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'About Xianyun',
      audio: 'VO_Ganyu_About_Xianyun',
      text: 'Cloud Retainer... Oh, I mean, Ms. Xianyun — we went shopping together a while back, but we ended up stopping at every single stall, and she wanted to inspect every item they sold before we could leave. When we finally remembered to get something to eat, it was already dark out. It really reminded me of the time I used to spend training in the mountains with her... Back then, time also seemed to pass in the blink of an eye...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 11035,
              chapterId: 2045,
              chapterTitle: 'A Thousand Moonlit Miles',
            },
          ],
        },
      ],
    },
    '35': {
      title: 'More About ___: I',
      audio: '5001',
      text: "You have a last-minute job for me? Okay, uh... Sorry, please don't try and explain it all verbally... Write it down, leave a note here. I'll get to it as soon as possible.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'Let\'s see... "I want to understand ___ better..." Wh—What sort of request is that!? I\'ve never done this before... Um, um, um... Okay... I can, ah... run you through my annual review from last year? That should bring you up to speed on me... No good? Oh, okay then...',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '37': {
      title: 'More About ___: III',
      audio: '5003',
      text: "I've had a long, hard think, and I've realized that so long as it's for a work-related matter, there's really nothing for me to be embarrassed about. So if you really need to understand me more... This, uh, hairpiece... it's actually my horns. That's right. I'm part illuminated beast, qilin to be exact. Okay, so, now we've got that out the way... Please sign this non-disclosure agreement for me. And don't tell a soul.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '38': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Even though I'm part qilin, I'm still part human, too. Still, all these years I've been asking myself the same question: Do I really belong in the human world? Maybe I'm just like a Dendro Slime hiding in the earth, burying myself in numbers and reports in order to escape reality.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '39': {
      title: 'More About ___: V',
      audio: '5005',
      text: "Thank you for always making time to chat with me. I feel like I must have spoken more after meeting you than I have in the last ten years put together. If I keep going like this... Maybe one day I'll be able to move on to something other than secretarial work. Now that I've got a few hundred years of experience under my belt, I should be able to avoid any more major mistakes.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '40': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "My hobby... I would say... my job. What? Why don't jobs count as hobbies? I thought hobbies are supposed to be things you look forward to doing, and that make you feel good when you've done them. That describes my job perfectly. So what's the issue?",
      tips: '',
      tasks: null,
    },
    '41': {
      title: "___'s Troubles",
      audio: '6002',
      text: "I don't understand why people insist on going all out to try and prove how their existence is more valuable than everyone else's. To exist in the first place is a beautiful thing, and that's enough... isn't it?",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Favorite Food',
      audio: 'VO_Ganyu_Favorite_Food',
      text: '"Drink only spring water, eat only whole grains," that\'s my motto. So I would be grateful if you could please remove that treacherously enticing-looking plate of delicacies from my field of view. Much obliged!',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Least Favorite Food',
      audio: 'VO_Ganyu_Least_Favorite_Food',
      text: "Qilins are strict vegetarians, so please do not take offense when I decline meat dishes. Yes, that includes your vegetable fritters since they have been fried in animal fat. Thanks, but I can't. I'm afraid I really can't. I don't mean to argue, it's just I have a keen sense of smell, so I know how they've been cooked.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Such authentic delicacies... Oh no! I think I might have eaten too much...',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "I'm somewhat of a picky eater, sorry you went to all this trouble...",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "I appreciate the thought, but... meat's not really my thing.",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Birthday',
      audio: 'VO_Ganyu_Birthday',
      text: "Many happy returns! After all the times you've looked out for me, I didn't even remember to get you a gift — whoops! Silly me, I... What's that behind my back? Ah. You saw it then. It's a failed attempt at making a Qingxin flower cake... I wanted it to be perfect, but... Oh, you think it tastes good? Do you really?",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Power? ...Now there's a key performance indicator I haven't needed in a long time.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Could we maybe... find a peaceful resolution instead...? Never mind, doesn't matter...",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '50': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "I suppose this is the new way of life, then. I'm not going to complain. I'll try to embrace it.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '51': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'I remember reading in an ancient text that "Only when days be darker than the darkest night, may a qilin be compelled to fight." That\'s a massive exaggeration, but... should the time come for battle, and should you need me, then I will give it every ounce of my strength.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'No touching!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Access denied.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Born of ice and frost.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'All hail!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Glaze over!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'This is long overdue.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Elemental Burst: IV',
      audio: '200004',
      text: 'For Rex Lapis!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: "We're way behind schedule...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: 'Next on the agenda...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Sprint End: I',
      audio: '710001',
      text: 'Healthy body, healthy mind...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "There's nothing wrong with reaping a reward every now and then.",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Beautiful treasures are a cause for great happiness.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Perhaps whoever left these behind was... also fulfilling a contract?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Low HP: I',
      audio: '410001',
      text: "I'm just way out of practice.",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Did I miscalculate?',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Low HP: III',
      audio: '410003',
      text: "I'm a little low on energy.",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Please step back!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Uh... "Don\'t try to rush your enemy"!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Rex Lapis... I am sorry!',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'My contract goes... unfulfilled...',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Must... press... on...',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: "Ngh... Didn't see that coming.",
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'I can fix this!',
      tips: '',
      tasks: null,
    },
    '75': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Time to begin work?',
      tips: '',
      tasks: null,
    },
    '76': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'What are my orders?',
      tips: '',
      tasks: null,
    },
    '77': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'As per our contract.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Though many in Liyue are fascinated by life in Yujing Terrace, its day-to-day operations and rules are a mystery to them.\\nThey are aware that the Liyue Qixing are the cream of the crop who hold the fate of the city in their hands, but the calculations and data behind the Qixing's every decision are far harder to grasp.\\nThe people understand that the new policies announced each year will change the dynamics of the market, yet none can comprehend how policy is plucked from complex meeting minutes and compiled into something easier on the human eye.\\nAs the secretary of Yuehai Pavilion, ___ undertakes many tasks that ordinary folk do not see.\\nFor those that have witnessed her standing by the dock at daybreak, enjoying her breakfast in silence, it is difficult to imagine her in such a post.\\nEven still, by the time the sun has fully risen, she will have returned to Yuehai Pavilion overlooking Yujing Terrace, to continue to fulfill her contract.\\nA contract that she signed three thousand years ago with Rex Lapis.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "___ is not the secretary of any one leader in the Liyue Qixing but is instead the general secretary for the entire organization. Under her gentle exterior, ___ is as persevering as stone itself. This was something that Rex Lapis, the leader of the adepti, noticed very early on. Thus when the Liyue Qixing first emerged ages ago, ___ was their secretary. Through the years and the changes in the Qixing's roster, ___ has remained by their side as a constant. This has also meant that the mountainous piles of paperwork from the various departments and bureaus in Liyue have fallen upon ___'s shoulders. But though her workload has increased seven, a hundred, or even a thousandfold, her sense of responsibility has never wavered. Someone once queried as to the source of her motivation and received an answer that was not quite congruous with the question. \"What I've done... is nothing compared to what Rex Lapis has accomplished.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '"I work for the well-being of all living things in Liyue."\\nUnder almost all circumstances, ___ is a very trustworthy secretary.\\nIt is hard to imagine anyone outperforming her in the face of such an enormous workload, especially given her unique and penetrating insights into all of Liyue\'s matters.\\nNevertheless, her reliability can only be guaranteed under "almost all circumstances."\\nThe more important the matter, the more ___ strives for perfection, and the more nervous she becomes. Under pressure, her nervousness does result in the occasional error.\\nOne such incident occurred during the Rite of Descension, without doubt the most important annual event in Liyue\'s calendar.\\n___ was three minutes late for the Rite and had to squeeze through the crowd in full view of all.\\nLater on, with a face as red as a tomato, she stammered her way through an unconvincing explanation, all the while apologizing profusely to Rex Lapis in her heart.\\nHer colleagues guessed that there must be some reason for the mistake.\\nThose who did not know her well saw that Rex Lapis did not mind, and thus paid the incident no attention.\\nThose closer to her worried in private, and asked if she needed a workload adjustment or a short vacation, but ___ refused.\\n"I spent two hours making sure that I wasn\'t wearing anything too similar to last year\'s Rite..."\\nNeedless to say, ___ was not about to admit to this being the real reason for her tardiness!',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "How long is a thousand years?\\nLong enough for the Glaze Lilies that once teemed throughout Dihua Marsh to be wiped out by floodwaters, and long enough for the thriving settlement that sprung up upon Guili Plains to come to ruin in war.\\nHow short is a thousand years?\\nTo ___, it has felt shorter than the blink of an eye.\\nThroughout a passage of time unimaginable to mortals, ___ has been working on all manner of things at Yujing Terrace.\\nShe recorded the raising and demolishing of every building, and witnessed the rise to prosperity of every industry.\\n___'s sense of objectivity towards the passage of time comes from the endless reams of data she must trawl through, and from the ever-increasing number of colors she finds that she needs to categorize it all.\\nAll this time, her mindset has never changed — she constantly wavers between her human and adeptus halves.\\nOn one hand, ___ the qilin finds it difficult to comprehend mortal squabbles.\\nBut on the other hand, her human blood reminds her always to hold out hope that she might someday be able to fit in.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Outside the confines of her work, ___ very quickly shows how different she is from most other people.\\nShe has a habit of taking afternoon naps and has a shockingly accurate internal clock. When lunch hour arrives, no matter where she is, she will simply curl up into a ball and fall asleep on the spot. Even the raucous dancing of hilichurls will fail to wake her.\\nThese habits were at first just a running joke within the Liyue Qixing.\\nBut once, after accompanying the then-Tianxuan to lunch outside the city, a well-fed ___ simply crawled into the nearest roadside haystack. She ended up being transported all the way to Dihua Marsh, awakening only after bumping her head during the unloading.\\nUnable to find ___ anywhere over the subsequent three hours, and knowing that she would not depart unannounced, the Tianxuan almost filed a missing person report.\\nAfter receiving a stern admonishment to "only take afternoon naps where it\'s safe," ___ retorted:\\n"Well... isn\'t everywhere in Liyue safe?"\\nPerhaps, with the mixture of human and illuminated beast blood flowing through her veins, ___\'s understanding of the world\'s affairs is a little different to that of most humans.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "___'s qilin heritage is little-known in Liyue Harbor.\\nWhenever she is asked by someone walking along Feiyun Slope as to the obvious protrusions in her hair, she says that they are ornamental heirlooms.\\n\"If I told them the truth, they would distance themselves from me...\"\\nDespite never having been on particularly close terms with Liyue's citizens in the first place, ___ would still not consider distancing to be a good thing.\\nHer more important reason for hiding the truth is to prevent curious onlookers from touching her qilin horns.\\nAfter all, a qilin's horns are a sensitive part of their body, both physically and mentally speaking.\\nAnother secret that ___ is anxious to keep hidden is the fact that she is watching her physique.\\nThe qilin are strict vegetarians, but Liyue is a veritable powerhouse of gastronomical delights, one in which even vegetarians struggle to control their appetites.\\n___, who has grown accustomed to city life, is thus very vigilant in matters concerning her weight and physique.\\nWhenever she finds herself being drawn towards some delicious dish, she will attempt to reassert her self-control. For ___, the difficulty of such a challenge is second only to finding a Flaming Flower atop Dragonspine.\\nBut she is not one to give up half-way through the ascent.\\nDuring the Archon War, she once choked a giant monster to death with ease after getting lodged in its throat when it tried to eat her, said monster having fatally underestimated quite how wide her waistline was.\\nFor ___, avoiding any similarly embarrassing episodes in the future is an absolute must.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'The Flora of Yujing Terrace',
      title2: null,
      text: 'Handwritten notes detail the morphological features and behaviors of the plants in Yujing Terrace, with each beautiful stroke penned by ___\'s own hand.\\nThe notes are succinct, comprehensive, and well-categorized, and even offer some insights that one would be hard-pressed to find elsewhere on the market.\\nThese include pointers on caring for Glaze Lilies and methods for grafting Silk Flowers.\\nIn readability and scientific accessibility, they come close to the standard of official publications.\\nOr rather, this is the experience if one starts reading from the front.\\nSkip to near the end, however, and one may well be left dumbfounded.\\nThe final few pages are a shocking rash of black ink and frantically scribbled-out text.\\nReading patiently and painstakingly between the lines, one might just discover that these notes were, at one time, various methods for vegetable cultivation.\\n"But if I learn to grow vegetables, I\'ll be even less able to control my appetite."\\nHer hands balling into fists, it was with much difficulty that ___ erased the results of her research.\\nLater, whilst watering the plants on an empty stomach, ___ found herself plunging her head into a thicket of Silk Flowers, fantasizing that they were Sweet Flowers in an effort to comfort herself.\\nMany more fantasy Sweet Flowers followed shortly afterward during her afternoon nap...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Qilin are paragons of benevolence among the adepti, drinking only freshwater and eating only plants. Flies they will not hurt, and a bruised reed they will not break. They do not travel abroad, do not gather in herds, and no trap will hold them. They are leisurely yet composed, active but reserved — a gentle and elegant race. Yet when a wicked beast from the sea arose and threatened the land beneath their feet, that peaceful life ceased to be an option. Three thousand years ago, ___ answered the call of Morax the God of Geo, aiding him in the Archon Wars. And when the war was over, she chose to stay in Liyue and help the humans build a better polity there. The first Liyue Qixing would need support, and she took this task up as a matter of course, becoming their secretary. The moment she made that decision, a Vision appeared at her hip, granting her power to resonate with the world to a degree beyond her natural abilities. Whether she would grow strong enough to no longer need it, or whether she would use it as a last resort in Liyue's defense... Regardless, she chose to serve as the bridge between adepti and humans. Her Vision, then, was proof and witness of her new duty.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
