export const kaeyaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Kaeya_Hello',
      text: '___, Knight of Favonius. Please allow me to join you on your journey. Guarding you on your journey sounds far more entertaining than any of the usual Favonius stuff.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Nothing to Do',
      audio: 'VO_Kaeya_Chat_-_Nothing_to_Do',
      text: "I didn't know you were such a slacker.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Knights of Favonius',
      audio: 'VO_Kaeya_Chat_-_Knights_of_Favonius',
      text: 'Hehe, seems all the other knights already have their hands full.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Laziness',
      audio: 'VO_Kaeya_Chat_-_Laziness',
      text: "Come on, let's get moving. We're not frozen in place, after all.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Kaeya_When_It_Rains',
      text: 'Cryo is always far more effective in the rain. This is going to get interesting...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows: Anecdote',
      audio: 'VO_Kaeya_When_It_Snows_-_Anecdote',
      text: 'How about a ghost story to go with the snow?',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows: Cold',
      audio: 'VO_Kaeya_When_It_Snows_-_Cold',
      text: "What's wrong? Can't handle the cold?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: "VO_Kaeya_When_It's_Windy",
      text: "What a pleasant breeze. I wonder how long it'll last?",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: 'VO_Kaeya_Good_Morning',
      text: 'Seize the day.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: 'VO_Kaeya_Good_Afternoon',
      text: 'Hey, fancy joining me at the tavern for a bit?',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: 'VO_Kaeya_Good_Evening',
      text: "You're not scared of the dark, are you? That's... interesting.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: 'VO_Kaeya_Good_Night',
      text: "Leaving already? See you next time, then. Don't make me wait too long, though.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___',
      audio: 'VO_Kaeya_About_Kaeya',
      text: "Is the Abyss Order causing you trouble? If there's anything bothering you, you know you can talk to me.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Employment Relationship',
      audio: 'VO_Kaeya_About_Us_-_Employment_Relationship',
      text: "If you ever need me, let me know. Let's not make this a transaction relationship.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Strength',
      audio: 'VO_Kaeya_About_Us_-_Strength',
      text: "Oh? Well, if you're concerned about keeping things professional, maybe you can find more use for me on the front lines. How 'bout it, boss? Haha, just don't feel intimidated by what I can do.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: 'VO_Kaeya_About_the_Vision',
      text: "Still struggling with how Visions work? Let's see... How can I explain it... The apparatus that allows us to see is our eyes. A Vision is the apparatus by which we control the elements. Simple, is it not?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: 'VO_Kaeya_Something_to_Share',
      text: "Do you drink wine? Dandelion wine has a unique body to it. Oh, you're underage? You should try Mondstadt's apple cider vinegar. I know just the place.",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: 'VO_Kaeya_Interesting_Things',
      text: "Have you ever seen the owl of Dragonspine? If you look directly at it, it seems to see right through you, while letting go of none of its own secrets... Quite fascinating, don't you think?",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'About Jean',
      audio: 'VO_Kaeya_About_Jean',
      text: 'What? The Acting Grand Master? You need to give her your full support.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'About Lisa',
      audio: 'VO_Kaeya_About_Lisa',
      text: "Oh Lisa. Hmm... You'd better not forget to return your books on time. I made that mistake once and boy was she angry. My arm is still numb from last time...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Amber',
      audio: 'VO_Kaeya_About_Amber',
      text: 'That Outrider is a clever and righteous knight. Be careful not to step out of line in front of her.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Diluc',
      audio: 'VO_Kaeya_About_Diluc',
      text: 'Diluc? He was cute as a young lad. But nowadays he just seems to be in a world of his own... Overall, not much fun to hang out with.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Klee',
      audio: 'VO_Kaeya_About_Klee',
      text: "Klee. Seems she has failed to elude the Acting Grand Master's investigative skills, despite the pointers I gave her... Haha, I'm kidding, no need to go reporting me or anything.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Albedo',
      audio: 'VO_Kaeya_About_Albedo',
      text: "Albedo, eh? Calm, collected, and incredibly talented. He's the type everybody likes, some even more so than others. What, you into him as well?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Diona',
      audio: 'VO_Kaeya_About_Diona',
      text: "Have you tried one of Diona's drinks? Oh right, you're still underage. Haha, such a shame, it truly is — to not be able to revel with you in such bliss. Hehe, I guess all we can do is wait for you to be old enough.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Varka',
      audio: 'VO_Kaeya_About_Varka',
      text: "Now that you mention him, it is a shame there is no one in the Knights of Favonius to inherit the Grand Master's approach to his work. *sigh* I must say I really do appreciate people like him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Fischl',
      audio: 'VO_Kaeya_About_Fischl',
      text: "Hmm? You think Fischl having one eye covered is very fitting given her title of Prinzessin der Verurteilung. Hahaha, if that's the case, that must also make me a descendant of some kind of former royal lineage, no?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Noelle',
      audio: 'VO_Kaeya_About_Noelle',
      text: "I was entrusted by the Acting Grand Master to work in the background to support Noelle. But there hasn't been much for me to concern myself with — she has a good head on her shoulders. Quite the relief.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Rosaria',
      audio: 'VO_Kaeya_About_Rosaria',
      text: "Ahaha, you want to know about the secrets of Sister Rosaria? That... I cannot tell you. Though my impression of her is not bad — certainly better than a certain someone whose name I won't bother to mention. She's honest with herself. She casts off that which she has no time for and she doesn't feign motivation for affairs that do not interest her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Sucrose',
      audio: 'VO_Kaeya_About_Sucrose',
      text: "Sucrose may not be much of an extrovert in public, but as they say — it's always the quiet ones... Apparently, her laboratory is home to quite the eclectic range of implements and her experiments are more than just intellectually stimulating... All hearsay, of course. You don't seriously think I would go snooping around a fair lady's private quarters, do you?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Collei',
      audio: 'VO_Kaeya_About_Collei',
      text: "Oh, Collei? Oho, now there's a name I haven't heard in a while... You came to the right person! Let me tell you her whole story, starting right from the very beginning, with all the delicious details!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Mika',
      audio: 'VO_Kaeya_About_Mika',
      text: "When I first met Mika, he seemed like the nervous type, so I decided to joke around with him a little. I didn't count on that making him even more nervous... His smile looked as if it were plastered onto his face, and in the end, he even wrote me a letter of apology. Tsk-tsk. Does taking everything so seriously run in the Schmidts' blood?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Dahlia',
      audio: 'VO_Kaeya_About_Dahlia',
      text: "Do you know if he drinks a lot of wine as part of church ceremonies? Because his alcohol tolerance is through the steeple. The first time we got to know each other was when I lost to him in a drinking contest. Well, the Anemo Archon loves his wine, so it's fitting that his spokesperson is such a devoted advocate for the wonders of alcohol... Things like that are what give the City of Freedom its charm.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: I',
      audio: 'VO_Kaeya_More_About_Kaeya_-_01',
      text: "The title of Cavalry Captain is nothing to get excited about. Now that I think about it, the Grand Master took all the cavalry from Mondstadt so there's none left for me to captain...",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'More About ___: II',
      audio: 'VO_Kaeya_More_About_Kaeya_-_02',
      text: 'There are a total of ten captains within the Knights of Favonius. But truth be told, not all of them have what it takes to be leaders.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '35': {
      title: 'More About ___: III',
      audio: 'VO_Kaeya_More_About_Kaeya_-_03',
      text: "My eye? My eye is fine. There's nothing unusual about hiding one's body parts from view. It's the same reason I wear pants... or any other item of clothing, for that matter.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '36': {
      title: 'More About ___: IV',
      audio: 'VO_Kaeya_More_About_Kaeya_-_04',
      text: "Khaenri'ah, huh? You sure know a lot! The legacy of Khaenri'ah is long gone. The sinners are all that's left, and they're not worth mentioning.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '37': {
      title: 'More About ___: V',
      audio: 'VO_Kaeya_More_About_Kaeya_-_05',
      text: "I didn't realize we'd known each other for so long now. Time flies! You know, following you on your journey might just be the most fun I've had in my whole life. I hope it stays that way.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '38': {
      title: "___'s Hobbies",
      audio: 'VO_Kaeya_Hobbies',
      text: "Wine tasting is an art form. Mondstadt's wine is a gift from the Anemo Archon. It's only right that one should learn how to appreciate it.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: "___'s Troubles",
      audio: 'VO_Kaeya_Troubles',
      text: "Lonely? Me? Not with someone here nagging me all the time, that's for sure.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: 'VO_Kaeya_Favorite_Food',
      text: 'Sparkling wine is a specialty of Mondstadt. Mix it with three parts Dandelion Wine and the bitterness disappears completely. This concoction is known as "Death After Noon." Delectable.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: 'VO_Kaeya_Least_Favorite_Food',
      text: "I can't believe that some people actually drink grape juice... If they had a little more patience, they would find it ferments into the most exquisite wine. Hmph. So unromantic.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Kaeya_Receiving_a_Gift_-_01',
      text: 'Ho! This is quite exceptional... You are full of surprises.',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Kaeya_Receiving_a_Gift_-_02',
      text: 'You should serve this with wine, it would really add the finishing touch.',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Kaeya_Receiving_a_Gift_-_03',
      text: "Ew... *Ahem* I'm just a slow eater... I'll finish it, don't worry.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: 'VO_Kaeya_Birthday',
      text: 'Today is a day worth celebrating, I hope this day can bring you true happiness.',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Kaeya_Feelings_About_Ascension_-_01',
      text: 'Hmm. Not bad.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Kaeya_Feelings_About_Ascension_-_02',
      text: 'You always seem to be around to give me a hand. Thanks.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Kaeya_Feelings_About_Ascension_-_03',
      text: "Hmm, seems I'm getting stronger. I say, how is it you seem happier than me about it?",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Kaeya_Feelings_About_Ascension_-_04',
      text: "We were just traveling partners. I never thought I'd have you to thank for getting me to this point. Seems I really should respond in kind. Let us carry on, partner. The road ahead is still long.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '___ Alberich is an adopted son to the Ragnvindr Family, the renowned wine tycoon.\\nIt has been a long time since he last called Diluc Ragnvindr "brother."\\n___ currently serves as the Cavalry Captain of the Knights of Favonius, and is trusted by Jean.\\n___ is often the one wrapping things up in every incident that occurs in Mondstadt\'s vicinity.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'It is a curious fact that your best chance of finding ___ is not by visiting the Knights\' headquarters, but by frequenting the taverns at night.\\n___ is often found sitting at the bar, gossiping with the city folk, and sipping the famed Mondstadt beverage, Death After Noon.\\nHe is surprisingly popular among the elderly of Mondstadt, even earning himself the title of "top candidate for grandson-in-law."\\nIt\'s hard to imagine someone as mischievous, amiable, and wine-loving as ___ being the Cavalry Captain of the Knights of Favonius.\\nHunters and bandits alike are often among ___\'s drinking buddies. As wary of him as they may initially be, all are ultimately disarmed by his smooth talking, and end up telling him everything he wants to know.\\nDepending on what they then make privy to ___, their night may turn into an uncontrollable nightmare or remain one of harmless banter.\\n"Everyone\'s got a secret, but not everyone knows what to do with it."\\nSays ___, with his usual arrogant smirk.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "\"Justice is not an absolute principle, but is the result of striking that fine balance between strength and strategy. As for the details of how it's done... Don't worry yourself too much about that.\"\\n___ once said these words in front of Grand Master Varka.\\nAs long as everything falls into place the way he expects in the end, ___ doesn't care all that much about how it's done.\\nThis cavalier attitude is what defines his character.\\nNot that different from Death After Noon's wild and explosive taste, one might add.\\nHowever, his reckless approach to things is not uncontroversial.\\nOnce, in order to force a bandit leader into facing him directly, ___ triggered the Ruin Guard at an ancient ruin to cut his opponent off, putting his own men at risk in the process.\\nIt's times like these when even Jean, who puts a lot of trust in ___, finds herself shaking her head in disapproval.\\nNot that this bothers ___, of course. On the contrary, he actually enjoys putting people into the difficult position of making tough decisions.\\nHe takes pleasure in seeing the hesitation in his comrades' eyes in the moment just before they dive into battle with him, just as he takes pleasure in the look of fear in his enemies' eyes as they face off against him.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'The flourishing winery business in Mondstadt has been a great source of prosperity in the region over the years. This prosperity often entices greedy bandits and monsters to the area.\\nThey are a motley bunch who hide in the shadows, and their backgrounds, motives, and allegiances are varied and complex.\\n___ battles against this threat to Mondstadt not only with his sword, but also with his smarts and his wit.\\nA young knight once dedicated years of his life to studying threats in and around Mondstadt, and reached an astounding conclusion:\\nWhen Death After Noon is out of season due to lack of supply, the number of reported incidents inside and outside the city show a drastic decrease, and this remains the case until Death After Noon returns to the market...\\nThe young knight showed his findings to Cavalry Captain ___ in hopes of getting some advice from him.\\n"Interesting. I\'ll look into it." ___ answered, with a wry smirk on his face.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Generally speaking, ___ is an easy person to have a conversation with. The only topic that you will never hear him discuss is his past.\\nEven when the Grand Master demanded information on his background, ___ skirted around the issue and gave only vague answers devoid of details.\\n\"One afternoon near the end of summer a decade ago, my father and I passed by the Dawn Winery.\"\\n\"'I'll go get us some grape juice for the road,' he said, but he never came back.\"\\n\"If Master Crepus hadn't taken me in, I doubt I'd have made it through the storm that night.\"\\nThis matter-of-fact description hides a carefully constructed lie.\\n___ has never once spoken the truth about what happened that afternoon:\\n\"This is your chance. You are our last hope.\"\\n___'s father squeezed his son's lean shoulders as he spoke, seemingly looking right through ___ to some place far beyond.\\nOn the other side of the horizon sat their distant homeland of Khaenri'ah.\\n___ would never forget the look of both hope and hatred in his father's eyes as he uttered those words.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Many citizens still remember the two most eye-catching young gentlemen in all of Mondstadt a few years ago.\\nOne of them was the dapper Diluc, an elegant swordsman who always had a warm smile and a confident posture.\\nThe other was the eccentric ___. He was Diluc's friend, supporter, and sounding board, ensuring he got through every challenge he faced smoothly.\\nThey were almost like twins, knowing each other's thoughts and intentions without a word, protecting Mondstadt in both light and dark.\\n...Until that fateful day, now ingrained deep in ___'s memory, when the convoy that Diluc was escorting was attacked by a huge monster.\\nIt was the first and only time that ___ failed in his duty.\\nBy the time ___ finally reached Diluc, it was all over.\\nThe power their father had used to successfully fend off the attack backfired, taking their father's life.\\nBoth ___ and Diluc were shocked by what they had witnessed, losing the calm composure a knight should retain.\\n\"Even someone like Master Crepus would submit to such a dangerous and evil power...\"\\nSinister thoughts flashed through ___'s mind, and he simply smirked:\\n\"This world is truly... fascinating.\"\\nAll while their father lay dead in a pool of his own blood. It was on that night that the two sons' paths diverged.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'A List',
      title2: null,
      text: 'Between the pages of "The Adventures of Angelos," you find a list of names written on a sheet of official Knights of Favonius letterhead paper.\\nIt meticulously records the details of bandits in the city and further afield, as well as mercenaries and mid-to-senior-level Treasure Hoarder members, listing for each entry a name, position, area of activity, and personal profile.\\nA dozen or so names are circled, with a note in the margin saying "Otherwise, things would get too boring."\\nWhen questioned about it, ___\'s response is "I suppose I must have gotten drunk and started scribbling nonsense."\\nYour gut feeling is that ___ purposely let you see this list, but you have no way of proving it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "It was raining heavily in Mondstadt on the night that ___ Alberich received his Vision.\\nEarlier that day, Crepus Ragnvindr had wielded the power of a Delusion — only to become its victim when it backfired. To set his father free from the unbearable agony, Diluc Ragnvindr took his life.\\n___ was Diluc's brother by adoption and was always by his side, but on this occasion ___ did not partake in the final moments shared between father and son.\\nThe torrential rain that set in on Mondstadt that night seemed to be a sign of the heavens' grief at the passing of Master Crepus.\\nThere was a side to ___ that he kept hidden from the world: in truth, he was an agent of Khaenri'ah, placed in Mondstadt to serve their interests. His father had abandoned him in this strange and unknown land to fulfill this mission, and it was Master Crepus and the city of Mondstadt that had welcomed him with open arms when they found him.\\nIf Khaenri'ah and Mondstadt went to war, which side should he support? To whom should he offer his assistance: his birth father, who had ruthlessly abandoned him? Or his adoptive father, who had loved him and raised him?\\nFor the longest time, ___ had agonized over these impossible questions, caught between the opposing demands of loyalty and duty, faced with an impossible choice between truth and happiness.\\nBut now, Crepus' death upset this delicate balance. He felt liberated, but also ashamed of how selfishly he was responding. As an adopted son, he should have saved Crepus, but he had arrived moments too late. As a brother, he should have shared in Diluc's grief, and yet as their father lay dying on the ground, he had hung back behind his brother, that ancient plot running through his mind.\\nConsumed by guilt, ___ knocked on Diluc's door. As the rain poured down, the shroud of secrecy was washed away and all lies were revealed. ___ had finally come clean.\\nHe had anticipated Diluc's anger. The brothers drew their blades, this time pointing them at each other. ___ felt that this was his punishment for a lifetime of lies.\\nBut as the two crossed blades, ___ was overcome by the sensation of great elemental power surging through him. For years, he had stayed out of the way in his brother's shadow. But now, for the first time ever, he was facing his brother as his true self.\\nBitterly cold and brittle elemental energy burst forth from the tip of his sword to meet Diluc's searing flames head-on. The clash of crimson fire and azure ice created a sudden swirl of wind that stunned them both. This was the grim moment at which ___'s Vision appeared.\\nSince that day, ___ and Diluc have gone their separate ways. But he never discusses it, just as he never discusses the origin of his Vision.\\nThough it is a reminder of a hard-fought battle, and the prize that he earned in exchange for revealing the unadulterated truth, ___ sees it as a stern reminder that he must live the rest of his life under the heavy burden of lies.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
