export const qiqiVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'I am ___. I am a zombie. And I... forgot what comes next.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Talking to Herself',
      audio: '1101',
      text: 'Hey, do you know what? Uhh... neither do I. I... already forgot.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Afraid of Heat',
      audio: '1102',
      text: "Let's go somewhere cooler.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Training',
      audio: '1103',
      text: 'One, two, three, four. Two, two, three, four...',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'I forgot my umbrella again.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: '1202',
      text: 'I want to build a snowman. Will you help?',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: 'I should have stayed indoors today.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: 'The wind is... frigid. I like it.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'Hold my hand please. This wind could blow me away.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning means it's time to check my diary. Because my diary reminds me what I'm supposed to do in the morning.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'I just remembered something. I forgot to help Dr. Baizhu prepare medications.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. How was your day? My day was... fine, I think. But I can't remember.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "It's time for you to sleep now. I will do my stretches. ...Do not watch me, please.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___',
      audio: '2001',
      text: 'Did you ask me something? Sorry... I forgot.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Memory',
      audio: '2002',
      text: "I have a poor memory for most things. But as far as I know, that doesn't matter.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Memory Training',
      audio: '2003',
      text: "I started memory training exercises recently. So don't worry, I won't forget who you are.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: "My Vision can't turn back time. But at least it gives me the power to protect the people that matter most.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: 'I may be a corpse, but I am in a much better physical condition than Dr. Baizhu.',
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'Sometimes I see finches near the pharmacy. A nice little group of finches.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Baizhu',
      audio: '4001',
      text: "I can never remember Dr. Baizhu's face. But I don't mind.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Hu Tao',
      audio: '4002',
      text: 'Warm. Fake smile. Death. I despise Hu Tao.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Xiao: Name',
      audio: '4003',
      text: 'Sounds like a historical artifact to me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Xiao: Memory',
      audio: '4004',
      text: 'Remind me, have I met him before?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Xinyan',
      audio: '4005',
      text: '...Who?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Yaoyao',
      audio: '4006',
      text: 'Cute. Like a nice little finch.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Dusky Ming',
      audio: '4007',
      text: 'On some nights, I almost feel like someone is doing stretches together with me. But maybe I just have an overactive imagination.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'More About ___: I',
      audio: '5001',
      text: "What's going on?",
      tips: '',
      tasks: null,
    },
    '27': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'I perform stretches regularly to help me maintain the same range of movement as a normal human being. But as soon as I stop doing them, the rigor mortis starts to set in again.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '28': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'Some people want to take advantage of me. Others are terrified of me. But you... You are not like any of those people.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About ___: IV',
      audio: '5004',
      text: 'Since we first met, I have had a warm feeling inside. Not the kind of warmth that makes me feel rotten. The other kind of warm. The one that happens inside my heart. Thank you. I am happy. Sadly I only recognize the current you. If I forget you... No. I will order myself to remember you.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '30': {
      title: 'More About ___: V',
      audio: '5005',
      text: "In the past, my only thought was: I must stay alive. Even though I didn't know what to live for. But now, I think I know. I want to live with you. I want to ask, can we always stay together, for the rest of life, until death? Yes or no? Yes? Is that your real answer? Good, excellent. I promise to always protect you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '31': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'I want to have a pet. For example, a nice little finch.',
      tips: '',
      tasks: null,
    },
    '32': {
      title: "___'s Troubles",
      audio: '6002',
      text: "I don't know why, but high temperatures make me feel... disgusting.",
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'Favorite Food',
      audio: '6003',
      text: "I like coconut milk... But, I don't know what it tastes like.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'Sorry, I have no idea.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Cold. I like it. But, no flavor...',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Huh...',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "It's burning my tongue...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Birthday',
      audio: '7001',
      text: 'Many happy returns. Here is a bag of herbal medicine for you. You must be very surprised that I remembered? Let me explain. Last time you told me, I wrote your birthday down on a piece of paper. If I look at something once a day, it eventually goes into my long-term memory, and it will stay there forever.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Now, I have more power. But... what does that mean? Please explain. Thank you.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Ah, I understand. When I get stronger, I need to put more effort into controlling my strength.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'In the past, I did not understand the idea of being stronger than I already was. Now that I understand it well, I wish I was just a little stronger still.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'All of this is because of you. Thank you very much. Can you make me a promise? From now on, please, let me protect you. Do you accept? Yes or no?',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Due to being a zombie, ___ lacks facial expression. She hopes that's okay.\\nShe may look like a zombie, but she's surprisingly limber due to a strict calisthenics regimen.\\nHer memory is poor. She forgets easily, and that is partly why she can seem cold to others.\\nHer appearance is forever frozen at the point of her passing, so estimates of her age are unreliable.\\nZombies require orders to act, but due to some reason or another, ___ is presently giving herself orders.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Usually, zombies are cold and stiff, which forces them to locomote by hopping about.\\nAs such, ___ keeps up a calisthenics regimen to retain a human-like form.\\nThe 77th-generation Director of the Wangsheng Funeral Parlor, Hu Tao, doesn't see the point of all this. Whenever she meets ___, she will say: \"It would be easier if you just let me bury you.\"\\n___, of course, has no wish to be buried, and so conducts her exercises at night when no one's about.\\n___'s memory falls far behind those of non-undead disposition.\\nIf she does not continue to reinforce her impressions of someone, she will completely forget them in three days tops.\\nBut who knows, this might be a good thing — for a person with painful memories, forgetting may, in fact, be a form of release.\\nThe person ___ must remember most... not only does this person have a very punch-able face, but she also shows up every single day.\\nAs such, ___ isn't too concerned about her poor memory.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '___ is very petite indeed, but is in fact a very powerful zombie. Her short stature is hardly any impediment, but is instead good for high-speed movement.\\nIn combat, ___ will unleash the self-control that she usually maintains, allowing her body to return to an undead state, increasing her strength and speed.\\n"You\'re dead."\\nOnce she has stoically defeated her enemies, ___ will once again get her muscles under control, returning to her normal state.\\nShe has been threatened in the past by Treasure Hoarders while picking herbs by herself.\\nNow, a little girl, all by herself, seems like an easy target, no?\\nWho would have thought that this girl could send a whole crew flying?\\nThis is why we should always remember never to judge a person based on appearances. Or a zombie, for that matter.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Zombies mostly require orders from the person who awakens them to move. But strictly speaking, ___ has never been awakened.\\nAs such, she counts as a very rare case of a zombie that gives itself orders.\\nIf these orders are simple ones like "defeat the enemy," ___ has no problem fulfilling them.\\nBut when faced with complex instructions such as "go to Jueyun Karst, climb the sheer rock faces and pick herbs," ___ sometimes winds up stuck below the cliffs, unable to give up no matter how many times she tries and fails to scale the cliff.\\nThe method to cancel her orders is very simple — hug ___ from behind, tell her something like "I love you the most," and the orders will dissipate, just like that.\\nUnfortunately, there\'s just no element of sincerity when Baizhu does it, leading to greatly reduced results.\\nPerhaps someday, someone will come along who understands that such words cannot be spoken lightly, and who slowly but carefully releases the hold that ___\'s orders have over her...\\nWhat will ___\'s response be then?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'This ancient story has long been forgotten by mortals.\\nAn ordinary herb-picking lass named ___ lost her way and trespassed the realm of the adepti. Injuring her right leg in a fall, she hurriedly hid in a cavern to rest.\\nEven occupied as she was in bandaging her wound, she could hear sounds that did not belong to the mortal plane. But she could have never expected that with a huge crash, she would forever be trapped between life and death.\\nWhether adepti or demons, just or wicked, all understood that she was an innocent mortal caught in the crossfire.\\nOr perhaps it was by the will of heaven that she received a Vision in her dying moments, and so ended this contention between adepti and demon.\\nThe adepti could not bear to let her die, and each imparted to her a portion of their strength, meaning to breathe life back into her body.\\n___ did indeed awaken and live again, but went into a berserk state, unable to control the adepti energy raging through her.\\nSeeking to end the disturbance, Mountain Shaper had no choice but to seal the hapless maiden in amber.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'After hundreds of years, ___ was discovered by humans, still trapped in the amber, and was brought to Wangsheng Funeral Parlor for burial.\\nThe mountain roads were treacherous, however, and the amber was bumped about. Coupled with the passing of many years, the seal on ___ was all but spent.\\nShe awakened in the middle of the night, broke the amber in secret, and fled.\\nFollowing the herb-picking habits of her previous life, ___ headed right for the hills.\\nBy chance, she met Baizhu, the boss of Bubu Pharmacy, on the way, and he took her in.\\nNow, Baizhu was a doctor of great skill, but he was hardly a man of high caliber or great courage.\\nEven so, he took her in, never mind that her memory was so poor that she could not even sort herbs out.\\nIt does seem that his acceptance of ___ has something to do with his own personal pursuits.\\n___ is stiff, but not slow, and has long realized this. However, she does not take it to heart.\\nPerhaps she has seen too much, or been alone for too long... But what remains true is that she treasures his concern, even if there is some other motive behind it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'A Home-and-Away Handbook of Practical Wisdom for the Undead',
      title2: null,
      text: '___ carries something with her that looks like a notebook.\\n___\'s memory is very poor, so it is an object of irreplaceable importance if she is to smoothly go about her daily life.\\nThe words within are written in a centuries-old style, and are very elegant indeed.\\nThe first page is an instructional on calisthenics.\\nMoving past that, one finds the descriptions of various herbs and some "orders."\\n___ needs to give herself orders, so she has very precise instructions to ensure smooth transition.\\nShe has also dutifully written down all the things she needs to do in a day.\\nRecently, she has also added a section on "brain training" and "mnemonic methods."\\nAt this point, it has become a true "dummy\'s guide" on just about anything.\\nBut if the day ever comes when ___ also forgets to look at her notebook... there would truly be nothing for it then.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '___\'s Vision was given to her in the last moment of her life.\\nShe wanted to stop the clock from turning. She wanted to live happily again.\\nShe feared death. She wanted to live. She missed her family... These feelings coalesced at last into "ice."\\n"If only I could freeze time... How wonderful would that be?"\\nAs she thought thus, tears fell from the moribund girl\'s eyes upon the Vision that had appeared before her.\\nThe mighty and illuminated adepti all acknowledged this as a legitimate form of "illumination" — the yearning of humanity for bygone days is, after all, a desire to protect that past.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
