export const wriotheslayVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Wriothesley_Hello',
      text: 'Hello, please try to quickly summarize your intents and goals for this meeting. Oh? You\'re not here for business? Well, that just makes me even more nervous.\\nAlright, then perhaps we should sit down and discuss things in a little more detail... Oh, and you can call me "Your Grace." That\'s what they all call me down in the Fortress, and... well, I kinda got used to it.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Stickers',
      audio: '1101',
      text: 'If you ever see any stickers on my back, do me a favor and take them off... Melusines like to play pranks sometimes.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Pets',
      audio: '1102',
      text: "I once considered keeping some pets in my office, but soon gave up on the idea. It's just not right to keep small animals where they won't be able to see the sun.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Words of Advice',
      audio: '1103',
      text: "Word of advice: Don't break the law. Hmm, is there anything else? Oh, yeah... Seriously, don't break the law.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Wriothesley_When_It_Rains',
      text: "Oh, it's raining? That's alright. A real problem would be if we could feel water dripping on our heads in the Fortress of Meropide.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Wriothesley_When_Thunder_Strikes',
      text: "You know, they say if you're scared of the thunder, it's really because you've got something else to hide.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: 'VO_Wriothesley_When_It_Snows',
      text: "Hmm... This is a different kind of cold than what I'm used to.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: 'VO_Wriothesley_When_the_Sun_Is_Out',
      text: "They say there's nothing new under the sun, but somehow a picnic in the warm sunshine never gets old.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: 'VO_Wriothesley_Good_Morning',
      text: "Morning. What do the papers have to say about today's weather forecast?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: 'VO_Wriothesley_Good_Afternoon',
      text: "The Coupon Cafeteria is probably crowded right now. I'll have someone deliver the food straight to my office.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: 'VO_Wriothesley_Good_Evening',
      text: "Huh, is it evening already? Could have sworn I'd just had my afternoon tea.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: 'VO_Wriothesley_Good_Night',
      text: "Good night. I'll be staying up for a little while yet — want to run some numbers while everything's nice and quiet.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Misunderstanding',
      audio: '2001',
      text: "People have this tendency to see me as an all-knowing figure with mystical powers. In reality, I'm just one man with two eyes and two ears. How can I possibly know everything that's happening in the Fortress of Meropide?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Small Breaks',
      audio: '2005',
      text: "I finished serving my sentence long ago, so there's nothing stopping me from taking an occasional breather in the overworld as a free citizen.\\nAh, there's no need to worry... The Fortress of Meropide doesn't currently have any problem so big as to require my round-the-clock presence to operate effectively.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14006,
              chapterId: 2042,
              chapterTitle: 'Reborn in the Land of Grievances',
            },
          ],
        },
      ],
    },
    '14': {
      title: 'About Us: Committing to Jail',
      audio: '2003',
      text: "I form my first impressions of many people based on the contents of their inmate registration papers. Seems like you're no exception to the rule.",
      tips: 'Complete "Cataclysm\'s Quickening."',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '15': {
      title: 'About Us: Finishing the Jail Term',
      audio: '2002',
      text: "They say it's best to begin a friendship when there's no conflict of interest. Seems like the appropriate time has come.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About the Vision',
      audio: 'VO_Wriothesley_About_the_Vision',
      text: "Some inmates once taught me a way to wield the elements by throwing around chemical potions. I guess whoever's in charge of handing out Visions doesn't care too much about a little rule-bending.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: 'VO_Wriothesley_Something_to_Share',
      text: "Want a tip on how to escape from the Gardes? Just give yourself a name that's really long and difficult to pronounce. They'll be stumbling over your name as soon as they try to announce that you are under arrest.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: 'VO_Wriothesley_Interesting_Things',
      text: '"If a man will not work, he shall not eat." This phrase has been on the walls of the Fortress of Meropide for as long as anyone can remember. I don\'t know who first came up with it, but it\'s been pretty useful in the underworld.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Neuvillette',
      audio: 'VO_Wriothesley_About_Neuvillette',
      text: 'I was once summoned by Neuvillette to discuss some matters with him in his office. When I approached the Palais Mermonia, I saw him standing by the road, completely drenched in the rain. I held out an umbrella for him, and while he thanked me politely, his expression was a little... distressed, I guess. I can only assume that I had disturbed him in the middle of something.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Furina',
      audio: 'VO_Wriothesley_About_Furina',
      text: "Miss Furina displayed a severe lack of interest in my trial and excused herself early, probably because I pleaded guilty to all charges as soon as they were announced. Disappointing the Hydro Archon is a big deal, so... suppose I've got no choice but to keep gifting her copious amounts of the highest quality tea.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14006,
              chapterId: 2042,
              chapterTitle: 'Reborn in the Land of Grievances',
            },
          ],
        },
      ],
    },
    '21': {
      title: 'About Sigewinne',
      audio: 'VO_Wriothesley_About_Sigewinne',
      text: "Sigewinne the head nurse possesses all the virtues associated with the medical profession and genuinely cares for the well-being of everyone around her.\\nShe seems to have picked up some bad habits from me, though, like frequently betting with her Melusine friends over who'd be able to put more stickers on my belongings. Hm? No, I'm not actually bothered by it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Clorinde',
      audio: 'VO_Wriothesley_About_Clorinde',
      text: "Clorinde is the best Champion Duelist you can find. Her combat prowess is already the stuff of legend. I've never fought her myself, but that's because there's never been a need for it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Lyney',
      audio: 'VO_Wriothesley_About_Lyney',
      text: "I'll admit that when I removed the House of the Hearth's spies in the underworld, that was kind of an intentional provocation to the Fatui. But their only response was to send down a bunch of children... Was it because they truly saw those kids as disposable? Or because they knew I wouldn't have it in me to let them come to serious harm? *sigh*",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '24': {
      title: 'About Navia',
      audio: 'VO_Wriothesley_About_Navia',
      text: "The Fortress of Meropide works with Spina di Rosula on some matters regarding supplies and logistics, but we don't have any other dealings. This isn't because I don't trust Navia or her abilities, in fact, I hold her in quite high regard. The only reason we continue to stay out of each other's way is because I wanna honor the agreement I made with the late Mr. Callas.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Emilie',
      audio: 'VO_Wriothesley_About_Emilie',
      text: "The Fortress of Meropide doesn't need her services. Yet some things are best preserved the way they are, warts and all, so people don't make the same mistakes twice... I say warts, but yeah. I mean the smell.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Chevreuse',
      audio: 'VO_Wriothesley_About_Chevreuse',
      text: 'Most inmates seem to gain a new level of respect for the rules after receiving attention from the Special Security and Surveillance Patrol. As the captain, Chevreuse is an instrumental part of that team.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'More About ___: I',
      audio: '5001',
      text: 'As a general rule, the less a person sees of me, the happier their life is.',
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Hmm? Oh the scar on my body? It's from a gash I got while battling a gigantic undersea monster that tried to take over the Fortress of Meropide. ...Hah, just kidding.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '29': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Did you know, many similar models of handcuffs can all be unlocked using the same master key? Except mine, of course. They're different.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Honestly, my personal abilities are pretty limited. I got no talent in medicine, inventions, or ship-making. But what I do know how to do is find those people with those talents, and get 'em to come work for me.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '31': {
      title: 'More About ___: V',
      audio: '5005',
      text: "I've managed to get myself to a pretty comfortable place in life, but there's still some things I want that are outside my reach, like a peaceful and happy childhood, or the ability to trust other people. Maybe some people would see those feelings as shameful or contradictory, but I don't see a problem with sharing them. After all, why should anybody be afraid to admit what they want?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14006,
              chapterId: 2042,
              chapterTitle: 'Reborn in the Land of Grievances',
            },
          ],
        },
      ],
    },
    '32': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "Boxing? To me, that's more of a necessity than a hobby. You got some suggestions for actual hobbies?",
      tips: '',
      tasks: null,
    },
    '33': {
      title: "___'s Troubles",
      audio: '6012',
      text: "While I do possess some stereotypical Fontainian looks, when you're an orphan, you can never really be sure where you're from. Who knows, maybe I'll take a dip in the Primordial Sea one of these days just to check...",
      tips: 'Complete "Reborn in the Land of Grievances"',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14006,
              chapterId: 2042,
              chapterTitle: 'Reborn in the Land of Grievances',
            },
          ],
        },
      ],
    },
    '34': {
      title: 'Favorite Food',
      audio: 'VO_Wriothesley_Favorite_Food',
      text: 'I usually take some milk with my coffee and two cubes of sugar with my tea.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Least Favorite Food',
      audio: 'VO_Wriothesley_Least_Favorite_Food',
      text: "Have you ever had one of Sigewinne's milkshakes? The taste that comes to mind is... what's that flavor... desolation.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'What a perfect blend of flavors. I could have never made this myself.',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Lovely. I'll be sure to treat you to something next time.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Please excuse me, I'm... I'm gonna brew a cup of tea.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Birthday',
      audio: 'VO_Wriothesley_Birthday',
      text: "Our tradition says that all children of Fontaine are born amid their parents' wishes and blessings, but I'd like to think that all children are born from such wonderful feelings. Anything that I can say to celebrate your birth would feel a little trivial next to that, right?\\nUnfortunately, I won't be able to reduce your prison sentence if you were to commit a crime — the only thing I would be able to pull off would be a special Welfare Meal for your birthday dinner. With all that in mind, why don't you try to respect the law a bit more around your birthday, so we'll be able to celebrate somewhere nice on the surface?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'It is my honor to win your trust.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Uh oh, looks like I'll owe you a favor now.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Ha, why do you look even more pleased about this than me?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I like signs of strength and hope. They give me reassurance that tomorrow will be better than today. This isn't to be pessimistic, but it's impossible for the present to be without its doubts and troubles — that's just the truth. But come hell or high water, if nothing else then at least we'll be able to figure it out together, right?",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '44': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Let's begin.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: "Don't run away now.",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'A moment, please.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Have a safe trip.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'This could get a little chilly.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Stay cool and face your guilt!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Oh, this wasn't locked? How convenient.",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "I'd take it if I were you. I'm sure it'll come in handy.",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'All unclaimed articles should be turned in, so... neither of us saw anything here, right?',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'No need to fear.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'No backup, huh? Fine by me.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Time to improvise.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Step back.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Get to the infirmary.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Fallen: I',
      audio: '500001',
      text: "Sorry... I couldn't protect...",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: II',
      audio: '500002',
      text: "Instead of going big, guess I'm going home...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'I have... no objections.',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Going easy on me?',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: '...Not bad.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Let's get to work.",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Got a side job for me? Sure thing.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "I'll do my best, but I can't guarantee you victory.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'To the great relief of the Maison Ordalie, most Fontainians are law-abiding citizens. As such, the Fortress of Meropide is not a place that they will ever visit in their lives.\\nAt the same time, there is an easily understood yet rather tragic truth, which is that those who have served time often find it difficult to reintegrate back into the "overworld," and few will actively speak of their experiences in the "underworld."\\nRather than a specific place, the Fortress is more like an idea, a warning, a symbol of misfortune and castigation — a byword amongst Fontainians. As for who controls this idea, that is unimportant.\\nThanks to this state of affairs, ___ has been able to lead a secluded and private existence, living and traveling in Fontaine in a manner quite unbefitting of his status as the "Duke."\\nIndeed, even as pedestrians are saying things like "fool around any further, and I\'ll punch you straight into the Fortress of Meropide," or "this job is garbage, I\'d rather be tightening screws at the bottom of the sea," this administrator of said underwater fortress might be walking the same stone-paved road to the café, on his way to grab some takeout for his afternoon tea.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "___ does not, in fact, leave the Fortress often. Using the network of information and connections that he has personally built up over the years, he can gain any intelligence or resources he needs from the comfort of his office.\\nHowever, he is also aware of one principle, which is that he cannot be imprisoned in that office by the host of duties that assails him, or he will either never get a good night's sleep, or soon find himself sleeping forever beneath the waves.\\nOnly two things are necessary for him to run this place comfortably: Mora and manpower.\\nFortunately, the Fortress itself is a giant factory, and he has quite the knack for making money — why, even the Palais Mermonia is one of his valued customers. Very importantly, giving the Palais some extra care is not considered to be hankering after power, and the Court of Fontaine for its part has little power of oversight over the Fortress, and thus simply represents valued customers and Mora — the more of both, the better. As such, ___ is happy to comply with the Maison Gestion's exhaustively strict demands for proper documentation.\\n(The Fontaine Research Institute of Kinetic Energy Engineering's incredible demand for Arkhium might have once made it a match for the Palais, but ever since the Institute became a mid-air tourist attraction, it has been forced to withdraw from the partnership. Till we meet again for another big contract, valued customer.)\\nOne of the most common pitfalls for the immensely wealthy is over-valuing money and undervaluing people. This is, again, where ___ is a fortunate man, for he was not born rich, and thus knows how important it is to get along with others.\\nHe treats all who live at the Fortress equally. Be they criminals, guards, or ordinary staff, so long as they do what they should as they should, he will not nitpick.\\nBut as for those who overstep their station — well then, words must be had. The underwater space they dwell in is quite enclosed, and for most, there is nowhere else to go. If possible, of course, ___ would prefer everyone to be reasonable, but where reasoned words fail, he will use even more persuasive means.\\nOccasionally overlooking the trivial, meaningless, but inevitable clashes between people is fair enough. Most people know better than to raise a real stink, while as for those who don't... there are places where they can go. Just as flowing water can cleanse itself, so can a functioning society get rid of its rot.\\nAs such, not only has ___ not been worked into oblivion, he has even found himself significant amounts of free time.\\nOnce, the famous Champion Duelist Clorinde paid him a visit, and said this in passing: \"Why does it feel like you have even more free time than me? Your title wasn't bought, was it?\"\\n\"One moment, please.\"\\nSo saying, ___ rifled through three drawers before producing several thick documents with a flourish. \"Now, let me see... 'excellent management'... 'leading tax contributor'... 'specially granted this title...' Well, what do you know? Good guess, that's pretty much what happened after all.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "No titles may be bought in Fontaine, which prides itself upon impartial justice — certainly not with Mora. That idle exchange between ___ and Clorinde was pure nonsense, just a bit of verbal horsing around to liven up an otherwise bone-dry business interaction.\\nHowever, while the title of \"Duke\" itself was not bought, ___'s accession to administrator of the Fortress of Meropide cannot be separated from \"money.\"\\nCredit Coupons serve the role of currency within the Fortress. Here, Coupons are the medium of exchange, and this has been the case for a very long time, with only the details differing. When ___ was incarcerated here as an inmate, trade in Coupons was much freer, and the range of items that could be bought more comprehensive. So long as you had enough of them in your pocket, you could obtain harmful drugs, know the winner of fixed matches, buy the hearts of people sitting on the fence, and even take away the right of others to continue breathing.\\nMany of these were extralegal trades, but even the official channels had their various special tricks, too. If you lacked private connections, you could only buy food and water at exorbitant prices, and your fortune slip would not be some adage of unknown providence, but real, practical, extra work you had to finish by the end of the workday. Coupons in those days resembled nothing so much as the previous administrator's tool for controlling inmates.\\nHurling lawbreakers into a lawless chaos to fend for themselves was indeed one way of doing things, but ___ could not approve of it. He was perfectly willing to adapt to his environment, but if the environment was not suited for survival in the first place, then he certainly wasn't going to take this lying down.\\nHe spent a great deal of time accumulating capital in the underground arena and used that money to make still more. He was always the observant type, and was quite persuasive, too, not to mention humble and reasonable — so before anyone knew it, he had already accumulated more Coupons than everyone else in the Fortress combined.\\nThis accumulated wealth made him a man of high repute amongst his fellow inmates. And just as ___ expected, the hammer of punishment soon came swinging down. In a single night, his Coupon account was emptied in one cruel stroke by the Fortress's administrator.\\nBut as noted before, ___ had a knack for convincing others. Words have the power to incite, and so long as all residents of the Fortress, rich and poor, understood that they could suffer a similar fate under such management, they would speak up for him. And if he acted in a sufficiently upright manner in a sufficiently impressive setting, others would join with him to fill the void in their hearts.\\nAs such, he challenged the Fortress's previous administrator to a duel, in the name of fairness, justice, and order. Of course, their respective standings made poor grounds for this fight even at the best of times, but on that day, not a soul, inmate or guard, said a word in protest.\\nVery fortunately, said administrator's last-minute flight saved ___ from having to get another person's blood on his hands. But unfortunately, that day was also the day he would have finished serving his sentence, but with the administrator missing, there was no one to sign his exit papers.\\nAnd so, he walked into the office in the middle of the Fortress, and took over all relevant duties.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "After he obtained access to old court documents, ___ pulled out his own case file. There wasn't much in it, but even that was already all that the Fontaine authorities had been able to uncover at the time. According to the accounting ledger of his host family, he had been taken in as an abandoned infant — beyond that, there was no more relevant information.\\nWhile browsing through his file, ___ encountered some names that he had vague impressions of, and some other foggy faces briefly floated into view before fading to the sound of turning pages. Had he been willing, he could have used his connections to discover how these old companions were faring, but he dismissed those thoughts even as they entered his mind.\\nTo them, he must represent a past they no longer wished to recall, and to him, these names no longer constituted any part of his life. He had a new identity, a new home, and new friends.\\nThis was a strange experience for him. He'd met and known many people, and of all of them, very few could be considered friends — and he even knew quite a few who weren't human at all, something he puts down to Melusines really enjoying hanging out with humans. Their appearance belies their age, but the goodwill they show humans truly does have an innocence that only one's elders may have, a belief that these young human souls are good-hearted to begin with, and thus worthy of all care and faith in the infinite possibilities their futures hold.\\n___ himself has benefitted from this many times. When he was out on the streets with only the clothes on his back, it was a passing Melusine who gave him some hot soup. When he did not return completely unharmed from his bouts in the ring, Sigewinne would be waiting to greet him cheerily in the infirmary — not to mention how the officers of the Marechaussee Phantom have always been, within legal limits, his greatest help in investigating certain secret affairs.\\nAs such, he tacitly permits their visits to the Fortress, even if this can sometimes mean unneeded trouble. As for anything they might need to know, the Head Nurse warns them, and there's no need to go into details. In any case, anyone so capable of pasting stickers everywhere while he's not looking is hardly someone whose well-being he needs to worry too much about.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Watching the crimson stain spread across the floorboards, a wildly inappropriate thought entered ___\'s mind. How many Melusine officers would it take to investigate all the traces of blood in this place?\\nHis thoughts then immediately leapt elsewhere. To think that his blood was so like that of those who had deceived him that they could run together, melding effortlessly. How revolting.\\nBut he had lost all capacity to vomit. Indeed, he could not move a muscle if he tried. Thought and warmth had both faded, and his mind had begun to fill with a seeping, murky fog — there was nothing in his life till now worth remembering.\\nBut he did not die. Fate, it seemed, wanted him to live with the burden of sin, and so when he woke up in his hospital bed, both of his hands had been cuffed to the metal rails. A well-dressed woman was looking at him nervously from her distant chair. No doubt, she considered him to be some manner of young psychopath.\\nProducing pen and paper, she asked for his name, and he paused for a good long time. His thoughts drifted to an obituary he once saw in the papers, in which there was a person who had lived to a ripe old age bearing a long and complicated name. He didn\'t particularly like it, but he no longer wished to use the one his foster parents had given him.\\nThus did the woman write "___" down, and inform him of his trial date (which was, would you know it, the day the doctors expected him to be able to get out of bed), before hurriedly taking her leave.\\nThe trial itself went very smoothly, which he was grateful for. The blood he had spilled had stained his hands and taken root in his heart, driving him to yearn for a just conviction. He told all present of the full circumstances around the killing, and even added some details, such that there was no real room for argument in this case. Argue they still did, though, first on the matter of past cases related to orphans in an inconclusive search for any precedent patterns, and then somehow for clemency, believing that the people he\'d taken vengeance on were villains themselves in the first place, and that he should thus not have to bear the burden of guilt.\\nThis background noise did not change the ultimate result of the trial, and no sooner was it over than he was sent beneath the sea to serve time. Before he was to depart, the Gestionnaire in charge of recording his sentence asked him once again for his personal particulars.\\n"You\'re... ___, then? Your birthday, please."\\n"...Today."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "___'s mechanical gauntlets have gone through a great many iterations.\\nTheir origin can be traced back to his escape from his foster home. Given his age and constitution then, it was impossible for him to deal with a single adult, let alone more. As such, he was forced to try his luck on the streets, picking up odd jobs and doing apprenticeships, learning the art of lockpicking and the creation of small gadgets. He wanted to make sure that he would be well-equipped when he finally returned to destroy that accursed place.\\nHe fashioned a wrist-mounted device that could launch iron nails at high speed, penetrating any sufficiently soft surface. Unfortunately, it had limited uses, and lost all ability to function after a battle, just like him — and unlike him, it could not be saved.\\nIn the past, the underground pankration fights of the Fortress of Meropide had neither a fixed venue nor set rules. To win and keep earning, he had to constantly modify his gauntlets, because a trick you used once could be used against you the next time. Furthermore, even if he didn't render them scrap on the field, they could still be stolen or wrecked in some other way by others. He certainly had to start over countless times.\\nOnce he had the ability to garner better materials, his progress began to accelerate. He no longer needed to rely on chemicals to power the mechanism, and he would gain the support of professionals hailing from the Fontaine Research Institute. Those researchers enjoyed explaining the principles of mechanics to him even as they bellyached about all sorts of outrageous matters that occurred at the Institute. This, ___ found fascinating — technological development increased the number of crimes that were committed, but they could also aid in solving them. Was that development then good or bad? That was hard to say.\\nAt that point, he no longer participated in matches all that often, with the gauntlets being saved for dealing with the trickiest of problems. They no longer took life, and instead brought him great praise and respect.\\nBut the people of the Fortress also know little of the crime he once committed. The only one who still remembers it like yesterday is ___ himself. And no matter how much glory or repute he has earned, he still considers himself to be the same old ___ he's always known.\\nNeither a good person, nor a complete villain. He's just another soul, still living on in this world.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'The Wingalet',
      title2: null,
      text: '"But thusly do the ancient writers concur — \'Oceans will rise, empires will fall, and the only constant is change.\'"\\nAfter dealing with the spies that the Fatui planted, ___ took a bit of a swim in the seas around the Fortress. He spent very little time in there, finding afterward that his skin had flushed a slight red tint, though it returned to normal shortly afterward. He did not go to the infirmary for a checkup, nor did he intend to reveal this to anyone. All manner of recent signs had indicated that the prophecy was gradually coming to pass, and all people, regardless of whether they believed in it or not, had their own views on the matter, and did not really need this extra information.\\nHe had encountered some inmates with academic research backgrounds, though their numbers were relatively few, and they were prone to mad babbling even when clear-headed. They called this a malady common to all historians, and begged his forbearance in the matter. ___, of course, did not mind, and indeed, he was very interested in their arguments. And according to some schools of thought, if rising and falling were common in this world, then that great sea that once swallowed Remuria may perhaps return someday. In that sense, the prophecy was not really a prophecy, then, but was instead the expression of a rational pattern.\\nAs with many other things, he was somewhat on the fence about this reasoning. The Fortress was no stranger to issues that needed "mediation," with eyewitnesses often giving different testimonies. As such, he would reserve judgment on all records, and especially historical chronicles, for was poetic exaggeration not common practice in such writing? "Even the great dragon beneath the abyssal depths submitted to his power..." And how was anyone to know if this so-called great dragon was not just some very large vishap?\\nOnce all embellishments were removed, what still remained were the actual things he needed to take note of.\\nThroughout his as-yet unfinished life, ___ has always seemed to be preparing for something. No matter what, he does not wish for people to be ruled by terror. And once the personal element of fear has been removed, what remains is something more akin to a sense of danger. He would like to make some preparations in response to the crisis, even if it might prove futile in the end.\\nHistory is, after all, vast and terrible, and humanity is no more than seashells to be smashed upon the seashore by its great waves. Thus, he began to prepare for the creation of the Wingalet, expending vast resources and employing much manpower, though he did not put more stock into its success. It was a ship designed for fleeing disaster — an insurmountable chasm lay between it and golden Fortuna, bringer of civilization and glory.\\nNonetheless, if it could indeed serve its purpose, Jurieu and Lourvine\'s many quarrels would not have been for naught.\\n"Thusly do the ancient writers concur — \'Oceans will rise, empires will fall, and the only constant is change.\'"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Standing before the registration counter at the Fortress, ___ reached into his pocket to produce the sheet of paper that had his name and the length of his sentence on it.\\nBut out with that sheet also came a glass ball about the size of his palm.\\nNo, wait, this wasn\'t just some random glass ball. ___ blinked. When had he come into possession of this?\\nThe person at the desk — a stern-looking lady with a wrinkled face — gasped, before steadying her shocked expression, gripping her pen tighter. Her lips moved, and moved again, but at last closed.\\n"She must have a lot of experience about living here," he immediately thought, and so he did his best to hold the Vision in his palm, before asking in a small voice, "Miss, may I ask..."\\nThe senior registrar did not reply. She took the slip of paper from him and looked coldly behind him, as if sizing up the next criminal who\'d come to register. However, when she had finished filling the necessary information in, she had written something unnecessary in the margins of the documents she passed back to him. "Hide it well."\\n___ realized immediately that life at the Fortress would be even harder than roaming the streets.\\nHe felt fortunate that he had blocked everyone behind him from seeing what had happened, and more fortunate still that this kind-hearted registrar had been willing to give him a reminder. Sadly, he would not see her again, though this was no surprise, since staff turnover at the Fortress was quite high in those days.\\nThe first thing he did upon officially entering the Fortress was to quietly unravel a few threads of his clothing before using fine wire to sew his Vision into the space between the layers of fabric.\\nHe knew a thing or two about being homeless — certainly, that the biggest problem was never getting a hold of resources, but keeping them. People could not avoid sleeping, and occasionally being defenseless. The things you owned could be taken away with ease once you were asleep, and no one would call it a robbery.\\nAnd a Vision was no ordinary treasure. There were sure to be those who would be interested in it for various reasons, and Vision wielders were often magnets for ill-intentioned gazes.\\nIn the days that followed, his suspicions would be verified, for in gossip alone he heard of two to three Vision thefts. As for what happened afterward and the fate of the victims, various inconsistent rumors existed that ___ pretended to pay little mind to.\\nHe still felt quite fortunate, of course, but it was hard to feel genuine happiness at staying safe off the backs of other peoples\' tragic fates.\\nFor a long time afterward, he would pretend that he had not been favored by the gods, and in truth, it was not hard — merely a return to his scrappy past. He could handle that much.\\nThis persisted until a time when his age had nearly doubled, and he received an official invitation from the Palais Mermonia.\\nCommon practice dictated that citizens who were to receive an honorary title must attend an investiture ceremony, and said ceremony was said to be far more involved for the granting of a title such as "Duke."\\n___ tactfully declined attending the ceremony on the grounds of his unique duties, expressing the desire to simply sign and take the relevant certificates. Quite un-Fontainian of him, really, to dislike the spotlight and prefer to just muddle along.\\nMany workdays and much correspondence later, the Palais finally agreed.\\nBefore leaving the underwater stronghold, ___ took his Vision up once more, for the first time in many years. Weighing it in his palm, he found it lighter than before, and smaller to boot. Finding a good spot on his clothes, he hung it there.\\nThe first to comment on it was the Iudex, who was to bestow the title upon him. Neuvillette\'s smile was suitably polite, but he somehow seemed more pleased than ___ himself. "Congratulations," said the Iudex. "You have found something you wish to do at last, I see."\\n___ smiled back by way of reply, but made no further comment.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
