export const barbaraVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'Tada! *giggles* Barbara is here~ Leave the healing to me, I will not disappoint you!',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Sleepiness',
      audio: '1101',
      text: '*yawn* All this standing around is making me so sleepy...',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Encouragement',
      audio: '1102',
      text: 'Everyone is working super hard, we should be too!',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Keeping One Refreshed',
      audio: '1103',
      text: "Are you tired? Try my new spicy energy drink, I'm sure it'll wake you up!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Don't stay out in the rain for too long, you'll catch a cold!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Whoa!',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Ooh, snowflakes! Look at them dance!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'This weather is so amazing! I could burst into song.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "Don't worry! I will not... be blown away!",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning~ Let's do our best today.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Oh? You want to hear me sing...? Sorry, the show is... It hasn't started yet.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: 'I really want to eat some spicy squid at Good Hunter... but my stomach, er... Never mind...',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: 'We had a great day today! Get some rest.',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Barbara',
      audio: '2001',
      text: '"To the wind that guides me: When I\'m exhausted, bless me with the strength to keep going forward. When I\'m uncertain, bless me with the wisdom to distinguish good from evil. When I suffer from injustice, bless me with the courage to fight back..." ...Oops, my apologies, I was just doing my prayers. *giggles* You need something?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Hopes',
      audio: '2002',
      text: "My dream is to bring a smile to the faces of all the people in my life! As long as I can help you on your journey, I'm happy~",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Dreams',
      audio: '2003',
      text: "Thank you for being with me for all this time, I can feel that I'm getting closer to my dream. Hope we can keep this up in the future~!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: 'Everyone has their own desires. To bring together and fulfill those desires and make everyone happy — that is the purpose my Archon has bestowed upon me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "I could never get bored of the breathtakingly beautiful nature that surrounds Mondstadt. I've heard that there are blue trees that exist by the sea shore near Inazuma City. I just need to save up a little more, and... What's that? You want to know what I'm saving up for? *chuckles* That's my little secret.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Sunflowers always face the sun. They're so bright. In fact, my mother sent me a sunflower-style dress... I wonder when I'll finally get to wear it on stage?",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Jean',
      audio: '4001',
      text: 'Acting Grand Master... Leader of the Knights of Favonius... Everyone seems to like her a lot. Oh? Me? I... Of course I have nothing but admiration for her!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Lisa',
      audio: '4002',
      text: "I always take good care of Lisa. If she ever wants to become a star, she'll have my unconditional support, I'll cheer at the top of my lungs until my voice goes hoarse... Hmm, that might scare off her other fans though...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Amber',
      audio: '4003',
      text: "I've seen Amber rushing out of Mondstadt on a mission countless times. Being an Outrider doesn't look easy.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Diluc',
      audio: '4004',
      text: "Oh, Master Diluc? Last time, when I was performing at Angel's Share, he kept frowning... Maybe he doesn't like my singing?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Venti',
      audio: '4005',
      text: "Venti's voice is amazing! But all the songs he sings and the ones I'm good at are very different. I tried to learn them but... the melodies are just so complicated.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Bennett',
      audio: '4006',
      text: 'Bennett always comes to the cathedral covered in scrapes and bruises... Though it clearly never bothers him a bit, given the big grin he always has on his face. He really should take better care of himself.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Varka',
      audio: '4007',
      text: 'My father left on the expedition with Grand Master Varka... I hope they are okay. Oh, what am I worried about? The Grand Master is none other than the Knight of Boreas, of course they will be fine! Still, I will be sure to pray for their safe return.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Rosaria',
      audio: '4008',
      text: "Sister Rosaria is hard to get to know, especially given she never joins in on prayers, but... Oh, I'm sure she believes in the Anemo Archon! Although, I still don't really have the courage to try to talk to her...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Noelle',
      audio: '4009',
      text: "Noelle is just the cutest! She's so kind and patient, you just feel totally relaxed when you're around her. ...Oh yeah, and she makes the tastiest snacks! Best part is, they're also healthy. Hehehe!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Dahlia',
      audio: '4010',
      text: "I really look up to Dahlia. We rely on him to share the word of Barbatos, and it's always a great help to us all. He never sticks around long at the Cathedral, though. Maybe it's too quiet for him? He seems to love the markets and the taverns. And he can be hard to find sometimes... same as Rosaria.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About Barbara: I',
      audio: '5001',
      text: "Knights look so cool when they swing their sword in combat! Don't you think so? I tried using a sword before but... *sigh* Uh, let's just say I have zero talent with a sword.",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About Barbara: II',
      audio: '5002',
      text: "I want to heal everyone. This simple thought was all the motivation I needed to become a Deaconess. As long as I'm able to help everyone, I'll be content.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About Barbara: III',
      audio: '5003',
      text: 'Being an idol, I learned from Alice that "A true idol should always try to heal the soul of the people..." Yes, I completely agree.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About Barbara: IV',
      audio: '5004',
      text: "I'm doing my best everyday... I hope my efforts earn the trust of the people of Mondstadt.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About Barbara: V',
      audio: '5005',
      text: "Every time I get on stage I always start to doubt myself — can I really heal every person in Mondstadt? But I look at you now, and I feel that as long as we keep marching forward, maybe one day I might just— Huh? I've already healed you? Well, one's not enough! I've already healed a lot of people? I suppose...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "Barbara's Hobbies",
      audio: '6001',
      text: "The smiles on the faces of the people I've helped keeps me going.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "Barbara's Troubles",
      audio: '6002',
      text: "My companions keep getting injured, but I'm unable to share the burden of their pain. The only thing I can do is my absolute very best to heal their wounds! I'll make sure that everyone is healthy.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'Do you like spicy dried fish? I have two in my bag. Here, have one!',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I don't like anything bitter, especially... ugh, bitter gourd.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "It's a rare pleasure to eat food that suits my tastes so well. Today is a blessed day! Hehehe.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Thank you for cooking these for me. This time around, you are the one healing me!',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Oh, uh, oh dear...',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: "Here you go! This is the gift I got for your birthday, along with my exclusive autograph! Hehe, when my next song comes out, I'll make sure you're the first one to hear it! Happy birthday!",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'A dance from Barbara, to bring you more healing!',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Aw, thank you so much for your support! Oh no, I'm too excited, my heart just can't stop racing!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Please, tell me how I can be stronger! Just leave it up to you? No, no, that won't do! I want to help too!",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Traveling with you, I have discovered that the world is my stage! Thank you so much! *giggles* Ok! Let's shout it out one more time! Three, two, one — Go Barbara, go!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "I'll protect us!",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: "Let's dance!",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Let the show begin!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: '♪La la-la-la-la~',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Ready, steady, go!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Come on, we can do it!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Go Barbara, go!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Sprint End: I',
      audio: '710001',
      text: "*pant*... I'm fine!",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Sprint End: II',
      audio: '710002',
      text: '*pant* Keep going...',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'This is the kind of surprise I could sing about.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Oh, look at it sparkle!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Hmm hmm hmm♪ Things are going so smoothly today~',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Don't worry about me!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: "I can't stop now, they need me!",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Gotta keep trying!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "I don't want to see you hurt...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Please, let me tend to your wounds!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'I feel... a little weak...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Why has everyone stopped singing?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Sister...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Ouchie!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Oh no!',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I'll take care of it.",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Wish me luck!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'We can do this!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Barbara is the Deaconess of the Church of Favonius, as well as the shining idol of Mondstadt.\\n"The sight of Barbara makes all my problems disappear." This is quite a common saying among the citizens of Mondstadt.\\nIn fact, Barbara can do much more than just put people in a better mood: Her healing powers extend to flesh wounds and other physical ailments.\\nBarbara is known to have access to miraculous healing powers through her Hydro Vision.\\nHowever, Barbara herself knows that hard work is the most miraculous magic of all.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Every citizen of Mondstadt adores Barbara.\\nHowever, this has not always been the case. At first, Barbara's songs sounded strange to the citizens of Mondstadt, and many struggled to see the appeal.\\nThis was because for the longest time, the folk songs of bards were the only popular songs known in Mondstadt.\\nFortunately, Mondstadt stayed true to its reputation as the City of Freedom, and the people ultimately embraced the new while continuing to cherish the old.\\nPeople accepted Barbara's songs, and over time her positive energy rubbed off on them. Soon, they could be heard humming her tunes all around Mondstadt.\\n\"Albert, would you stop please! You're completely out of tune!\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Barbara's feelings on her own success are mixed.\\nTo the extent that an idol's duty is to make everyone adore her, she has done a fantastic job.\\nThere is no doubting that she has made the right choice.\\nHowever, an idol is also expected to spread joy and relieve people's spiritual fatigue... Has she really accomplished that?\\nShe sang for blind Glory, encouraging her to believe that her lover would one day return. She sang, too, for sick Anna, promising her that her illness would one day be cured.\\nYet, the smiles on their faces never last long after the songs end.\\nThis has led Barbara to become somewhat disillusioned and doubtful.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Barbara has always been a bright and optimistic girl since she was young. Though at times she can be a bit clumsy and mess things up, she always bounces right back and has another go.\\nBarbara is the complete opposite of her sister, who is seen by all as the pride of her family.\\nUnlike Barbara, her sister has always been the very definition of success in all aspects.\\nInitially, all Barbara had ever wanted was to surpass her sister in at least one thing, even if only once.\\nHowever, be it swordplay, her grades, or anything else, she was never able to compare.\\nEven for someone as optimistic as her, she found herself to be upset and down.\\n"Hard work is the most miraculous magic. But when even that doesn\'t work... what then?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Barbara has never once considered giving up.\\nHer determination and resilience even surprised her father, Seamus Pegg, the Cardinal of Daybreak.\\nBarbara only allows herself to be depressed for 30 seconds.\\nAfter that, she forces herself to brighten up, no matter what.\\n\"I'm not so good in combat, so I'll be sure to support those who are.\"\\nUnder her father's counsel, Barbara became a healer.\\nShe is as radiant as the sick and injured are pained.\\nHer desire to be recognized gradually transformed into a simple desire to help others.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: '"Thank you" are the two words that Barbara hears most often.\\nWhen she feels lost, she will suddenly find that there is someone wanting to hold her hand.\\n"Thanks for being here with me. I feel so much better."\\nTo Barbara, the greatest reward is seeing the smiles on people\'s faces.\\nTherefore, whenever she is massaging her swollen calves or drinking tea to care for her sore throat, Barbara recalls all those who have been kind to her.\\n"It\'s the encouragement I receive from others that keeps me going."\\nJust maybe, the smiles she receives are proof that her songs really can heal people.\\nHer ambition to surpass her sister and become the most popular person in all of Mondstadt hasn\'t been abandoned by Barbara, it is simply buried deep inside her heart.\\n"If only I excelled more, perhaps I could be of help to Jean."\\nThis is what she believes.\\n"Okay... Go Barbara, go!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "Alice's Idol Magazine",
      title2: null,
      text: '"...Idol?"\\nThe first time that Barbara heard this strange word, she was visibly confused.\\n"But... aren\'t The Seven the ones that people are supposed to worship?"\\n"Yes, but not exclusively..." replied Alice, an elder of the Hexenzirkel, as she groomed the young girl for stardom. "Read this, it contains everything you will need to know."\\n"Idol Magazine" was the name of the assigned reading material. Barbara had no idea what world this magazine had come from, but by reading it she found out that there was indeed such thing as an "idol," and that it mainly involved working hard at getting everyone to like you.\\nShe also discovered that an outstanding idol is capable of not just bringing joy to themselves, but also bringing spiritual healing to others through the power of song and dance.\\nBarbara set about learning one new song after another, dancing to the beat as she went. Finally, she found happiness, and she found it in the smiling faces of others.\\nSome time later, when Alice anxiously relayed to Barbara that plans for "Teyvat Idols!" were falling through, Barbara was starting to make a name for herself through her performances in Mondstadt.\\n"Hmm... Well, if I\'m the only one left... I guess you can leave it to me to define what it really means to be an idol!"\\nDriven by this ever so slightly selfish ambition to spread joy and healing to others, Barbara is slyly swotting up on new tunes behind the scenes to this very day.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'The story of how Barbara obtained her Vision is hardly the typical tale of high-stakes heroism.\\nShe had just joined the church and was looking after a little boy with a high and persisting fever.\\nNothing Barbara could think of would console the boy and bring an end to his relentless tears.\\nSomeone remarked that while the boy had already taken his medicine, there was no way to cure the pain of missing one\'s family.\\nAnother suggested that Barbara sing a song for the boy to raise his spirits.\\nBarbara had never sung a song in her life up until this point, but how could she shy away from it in a moment like this?\\n"Never having sung before is no reason to abandon a child in their time of need," Barbara thought to herself.\\nAnd so, Barbara took the boy in her arms and sang him a song: a lullaby, the only song she knew.\\nIt was an unceremonious beginning to her singing career. After quickly realizing that she barely knew any of the words, she had to resort to humming the tune instead.\\nNevertheless, her voice began to soothe the child, and so she kept singing. She sang the same song, over and over again, until her throat was dry and her voice was hoarse. Finally, the boy fell asleep. Exhausted, Barbara lay down by the wall and fell straight asleep herself.\\nEarly the next morning, Barbara awoke to discover that the boy\'s fever had come down. Perhaps it was because she had sung for him, or perhaps it had something to do with the Vision which had mysteriously appeared next to her hand at some point during the night.\\nBarbara was not preoccupied with the Vision, however. It was the sight of the boy smiling once again that filled her heart with joy.\\nBarbara received her Vision for the simple but beautiful wish that took hold in her heart that night: A dream of healing the sick through the power of song.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
