export const furinaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Why are you just standing there with your mouth gaping? Ah, you must be stunned and at a loss for words... Understandable, it is I after all... Fontaine's most beloved star, Furina. I'm on a very tight schedule, so you're lucky to even get an appointment with me.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Tea Party',
      audio: '1101',
      text: "Tea parties are a must for the well-mannered. If you'd like to learn the proper etiquette, I'd be happy to teach you.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Fun',
      audio: '1102',
      text: "Boring... Isn't there anything else more interesting to do?",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Popularity',
      audio: '1103',
      text: '*sigh* Being too popular can be such a hassle. Who knew the people would adore me so much?',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "It's pouring out here! Wait, the water levels aren't rising, are they?",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: '1202',
      text: 'Wow, this would be the perfect location for shooting a film.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: "The sun feels almost as hot as those studio lights I'm in front of all the time... Good thing there can only be one sun.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: '"Listen, there is a disturbing growling in the wind. That\'s the sound of a long-forgotten sea monster having a nightmare." Huh? Why is it having a nightmare? Uh... I dunno, because fear has to manifest itself somehow?',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'In the Desert',
      audio: '1205',
      text: 'What a wild and desolate sight... Allow me to grant you the blessing of water!',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning... Must I really get up this early? Just let me sleep a little longer...',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Good afternoon! Where's my cake? What? I just had cake for breakfast? Well, I think it's been long enough!",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. *sigh* Mademoiselle Crabaletta has been muttering about getting in shape lately and even said that she wanted to drag me along with her. Hmph, I'm already eating much healthier than last month. I work very hard to maintain my figure. Hey, you can tell, can't you!?",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "Whew, I'm getting sleepy myself. See you tomorrow. Remember to wake me up on time...",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Furina: Besties',
      audio: '2001',
      text: "Hmm? Who are these people at the tea party? Why, they are my loyal followers of course! *sigh* Alright, I suppose I'll introduce them to you. This is Mademoiselle Crabaletta, my most adorable maid... although she accidentally cuts my outfits from time to time... This is Surintendante Chevalmarin, my reliable housekeeper who keeps my busy life in order. And finally, the one keeping everybody in line is Gentilhomme Usher, my loyal conferencier. Hehe, I may have allowed you to participate in my tea party, but you'll still need to work hard to gain their approval!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Furina: Singing',
      audio: '2005',
      text: "I'm very confident in my singing skills, but there aren't many pieces of music that are worthy of my vocal prowess. I hope the creatives in the theater troupe get their act together and don't keep me waiting in vain...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Relationships',
      audio: '2003',
      text: "*sigh* Given that we know each other, you may relax a little and needn't act so respectfully in my presence. Wait, what's that expression on your face? Don't tell me that you've never respected me from the very beginning!?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Our Story Together',
      audio: '2002',
      text: "My story has already come to an end, and so the next act shall be about OUR story... In which case, we should probably start charging double for public appearances... Oh, I'm so happy!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14012,
              chapterId: 2043,
              chapterTitle: '"The Little Oceanid"',
            },
          ],
        },
      ],
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Once the ancient prophecy came to an end and everything was over, I fell into low spirits for a very long time. People who stand on the stage basking in the adulation of their audience must also bear the pressures of being in the public eye and living up to everyone's expectations. But I knew very well my person wouldn't be enough, and that putting on the act of a god would be the only way to satisfy their adoration... And at the end of the day, all I ever experienced was loneliness. So there came a point when I loathed the very thought of acting and locked myself in my room. It wasn't until the moment I stood on stage and faced the audience again that I realized the anxiety in my heart had dissipated. The reason I can now stand before the crowd's watchful gaze is perhaps because... I have finally started to act as myself.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14012,
              chapterId: 2043,
              chapterTitle: '"The Little Oceanid"',
            },
          ],
        },
      ],
    },
    '18': {
      title: 'Something to Share: Opera',
      audio: '3002',
      text: 'Fontaine\'s opera house has seen several reforms, and with each reform, opposition was to be expected. As I remember, crowds would often gather in the opera house making a ruckus... That one time, it became so loud my ears were ringing. I frightened them by stating, "I forbid anyone from discussing such pointless matters!", I clearly remember Neuvillette tapping his cane on the ground at that precise moment while the whole place immediately fell silent. Sometimes I can\'t help but inadvertently show my intimidating side... I hope my people understand.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things: Lumitoile',
      audio: '3003',
      text: 'I really like the Lumitoile. Those creatures can glow and shine even in places where no one sees them... That\'s what I call a true "star." Ah, if only there were an opera about the Lumitoile, then I could literally play the role of a lovely rogue starfish on stage.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Lyney and Lynette',
      audio: '4001',
      text: "Of course I know Lyney and Lynette. I used to frequently attend their magic shows. Though they're very popular, they're still much less popular than me. Only my performances would draw a completely sold-out crowd... even standing tickets would be out. But now... Uh... I've already decided to hang up my acting career, so it's perfectly normal for my popularity to decline!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '21': {
      title: 'About Neuvillette',
      audio: '4002',
      text: "I'm very grateful to Neuvillette for all the hard work he's done for Fontaine in the past few centuries. It seems he doesn't intend to investigate my crimes of deceiving the people. Anyway, we're no longer working in tandem, and it's been a long time since I've been to the Palais Mermonia. I imagine that this is good for both of us, right?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '22': {
      title: 'About Navia: Desserts',
      audio: '4003',
      text: "Have you tried Navia's macarons? I have to admit that her skills in dessert-making are comparable to mine. The design she paints on the macarons is so cute, don't you think? Not to mention the texture and sweetness... They truly are a work of art! How does she do it? Does it really all boil down to talent? Ugh, I can't believe I'm feeling a little jealous... I'll have to ask her for some tips next time!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Navia: Inner Thoughts',
      audio: '4004',
      text: "She's a very strong person. Strong people will always manage to keep themselves together no matter what happens, acting like everything is fine. Doing so prevents other people around them from needlessly bearing additional pressure. I saw the duel between Callas and Clorinde... and I can say that in this respect, Navia is becoming more and more like her father.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '24': {
      title: 'About The Knave',
      audio: '4005',
      text: "The Knave? Wh—Who's that? Oh... Uh, I'd already forgotten about her... Keeping such a terrible figure like her in your mind will only give you nightmares.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '25': {
      title: 'About Charlotte',
      audio: '4006',
      text: "I've often seen Charlotte busily running back and forth lately. She still seems to be hoping to arrange an exclusive interview with me. No matter how many times I refuse, she still hasn't given up. To be honest, her persistence made me angry at first... but then she told me with a resolute look in her eyes that she wanted to let people understand the real Furina, and that she believed people would understand my troubles. I don't know how to respond to her kind intentions... I suppose she might be right, but I'm just not ready yet...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Wriothesley',
      audio: '4007',
      text: "I haven't communicated with him much, but Neuvillette claims he's trustworthy, so I suppose he must be a good person. Oh, come to think of it, I've received some tea from Wriothesley before and it was exquisite!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Clorinde',
      audio: '4008',
      text: "As I remember, Clorinde isn't very talkative, but she has stood by me and protected me on several occasions, so I trust her very much. Hmm... I do miss her ever so slightly, but I don't have any real reason to see her now. Oh, right! I should invite her to my next tea party!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'About Escoffier',
      audio: '4009',
      text: "Oh? You've met my Patissiere Supreme? Thanks to Escoffier, I used to have my pick of delectable confections, even beyond Gateau Debord. Unfortunately, after everything that happened, I can no longer afford what the Palais Mermonia was paying her. Hm? Oh, don't worry, we're still in touch. I like to send her homemade dishes of my own. I even invented a new one not too long ago — \"Harra Fruit Fish Jelly Macaroni\"... Sounds good, right? I'll make it for you sometime.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'More About Furina: I',
      audio: '5001',
      text: "You're interested in hearing about me? *sigh* I suppose there's no helping that... After all, I was once the biggest celebrity of all Fontaine! Every day, countless journalists would come flocking around me, trying to get the inside scoop on my personal life, so I have loads of experience rejecting them. Of course, I don't intend to use this experience on you. With the right delicacies, I might be willing to exchange some of my secrets.",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About Furina: II',
      audio: '5002',
      text: "Someone recently recommended me to try surfing, so I went and gave it a shot. Keeping balance on the rolling waves was a little tricky at first, but I managed to get the hang of it pretty quickly. Maybe I'm just a natural surfer... Anyway, feeling the wind and waves up close and riding along the horizon was rather amazing. You should give it a try!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About Furina: III',
      audio: '5003',
      text: "If you have time, could you tell me more about your journey? I would love to hear all your fantastic stories. How should I put it... I easily feel interested in all kinds of things, but it isn't long before I feel bored again. Perhaps the more easily enthusiasm sparks, the more quickly it fades. But, when I'm with you, I seem to constantly feel happy... Such an amazing feeling!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About Furina: IV',
      audio: '5004',
      text: "Recently, I've been wondering if I've been a little too hard on myself in the past. In my efforts to maintain the reserved manner of a deity, I never got the chance to enjoy my life, which is why I've become obsessed with shopping lately. I've bought many new precious things... like dazzling rainbow-colored tea bags, fully-automated extendable cutlery, and a saddle specially made for riding Seahorses... But in the end, I realized that most of the stuff I bought was useless, so I sent them all to the troupe to be used as props in performances. Strange... before I bought those things, I was certain they would all be of good use to me...",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 14012,
              chapterId: 2043,
              chapterTitle: '"The Little Oceanid"',
            },
          ],
        },
      ],
    },
    '33': {
      title: 'More About Furina: V',
      audio: '5005',
      text: "People love talking about the past and often regret the beautiful things that have now faded into history. They also love to talk about the future, as if they're willing to sacrifice everything for an uncertain tomorrow. I don't agree with their way of thinking, yet I also feel very envious... I once lived in a world without a past or a future. To cope with that anxiety, I tried to create and act out a stronger, more god-like version of myself. Over the centuries, the stronger role I tried to play gradually merged with my real self. Even I can't separate the two now... but perhaps there's no need to distinguish them. Experiences of the past have formed who I am now, and that flawed performance has also become the most important part of me.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '34': {
      title: "Furina's Hobbies",
      audio: '6001',
      text: "The Queen's Crown still doesn't have a sequel yet? Pity, a classic like that where justice overcomes evil never gets old.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "Furina's Troubles",
      audio: '6012',
      text: 'Hmm, what sauce should I pick for my macaroni tonight?',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6003',
      text: "No one complains about exquisite confectioneries, but it'll take a lot of effort to make some that I like. Listen carefully, desserts are like operas... Everything from choosing the characters to imagining the setting requires a lot of effort in order to make the final performance a hit!",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'Simply put, I detest most of those "creative" dishes. I have tasted many wonderful dishes throughout the years which did nothing but leave me with some moments that I never want to look back on.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Oh? What a rich aroma and delicate texture... I didn't expect you to be such an accomplished cook... with refined taste, as well!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Too ordinary! Hmph, such an uninspired dish will never have my approval!',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Ugh. Is this what you usually eat? *sigh* Seems I'll have to share some of my macaroni with you.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy Birthday! Here, please take this ticket as your gift. It's a VIP seat to see Happy Day, just don't forget to show up to the performance! Hmm? What's \"Happy Day\"? *sigh* Well, I wanted to keep it a surprise... But it's an opera that I've rehearsed personally. It's about a big group of people that gather together to celebrate a certain very important person. You understand now, right? Just don't forget to come!",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "I'm really not accustomed to using a Vision. Why don't you teach me? Ah, I nearly forgot... you've never used a Vision either.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'The strength gained through my own hard work is truly fulfilling. Hehe, thanks for your support.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "That's more like it! As expected, my dazzling side comes through in any situation.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I didn't know you cared so much about me. Does that mean that you still need my power? But given the way I am now... there's a chance I won't be able to give you everything you need. Hmm? All you really care about is... me? In that case, then let us act out our future journey together!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Shower me with praise!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Strike a pose!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Yoo-hoo~!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'The show begins.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'How brilliant.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'May I present...!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Let the world come alive, hehe!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Time to shine!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Let my name echo in song!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'What a pleasant surprise, truly an extra slice of joy.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Take it... *sigh* Go on, you have my approval!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Splendid! More interesting trinkets for me.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Let's call a ceasefire...",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'This is trouble!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Ah! Someone help me!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Witness my power!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'My turn to take the spotlight!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Am I... free?',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: "I still... couldn't do it...",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Don't look at me... like this...",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'How dare you!?',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Stop that!',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I knew you'd miss me.",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'I have high hopes for this journey!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Witness my magnificence!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'It is unlikely that travelers from other nations will understand why the god of this land is regarded as a "superstar" unless they set foot in the Opera Epiclese.\\nWhether at performances or trials, she will always be in the seat reserved for her above the audience, laughing, scolding, falling into hysterics, to the point where more often than not she makes a stronger impression than the action onstage.\\nPeople buy tickets to indulge in new sensory experiences, and in this regard, Furina is by far more popular than the absolute justice that Neuvillette represents.\\nThe forms respect can take are not limited to just lifting one\'s eyes up to a being above, and the unique form of respect Fontainians have for Furina is perhaps described better as "affection and fondness."\\nShe is not perfect, and may not even be very powerful, but while onstage, she is the personage the people trust the most, for she never disappoints.\\nAmong Fontainian literary circles, there is a popular saying that Furina is a memory of spring never-fading, present in the hearts of all. And who does not wish for an eternal spring?\\nSpring is transient, but she is ever there — follow the stage lights, and you shall see her.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'As the icon of the Opera Epiclese, Furina has the right to speak freely during all stages of a trial.\\nMost of her questions are born from her curiosity and often have tenuous logical connections with the case at best, which at times can provoke raucous bursts of laughter from the audience.\\nBut just as one might begin to suspect that Furina is just there for laughs and gags, and lacks even the capability to grasp the case in its entirety, she throws out opinions worth their weight in gold.\\nOf course, there are also times when she will express little interest in the whole process due to having earlier eaten snacks ill to her liking or missed some parade, but it is said that audience members lucky enough to be there are still pleased with this, as a god who speaks in anger is equally enchanting.\\nThere is but one circumstance in which she will not appear to act quite so willfully, and that is when she takes the stage as an actress in a musical.\\nFontaine has a great many musical theater classics passed down from antiquity that are, from time to time, performed at the Opera Epiclese, with key roles being played by the most popular actors of the day.\\nBefore such productions are put on, there is a phase during preparations that resembles nothing so much as a lucky draw, where the troupe will send Furina an invitation. Should the mood strike her, she will agree to appear, resulting in a stage shared by a god and humans.\\nOnce Furina has agreed to participate, the performance date for that show becomes a Fontainian festival in its own right, so popular that the Opera Epiclese couldn\'t possibly meet the fervent demand even if they sold nothing but standing tickets and were filled to capacity.\\nAnd when the music sounds and a god takes the stage, the audience will see not their lovable deity, who does as she pleases, but the character in the script.\\nWhether majestic or valiant, conniving or covetous, Furina is a dab hand at playing them all, perfect down to the last gesture, as if she were born to act.\\nAnd it is because of her record of wondrous performances that she very much deserves to be called "superstar" by her people.\\nEven a famous reporter from The Steambird who had barely squeaked their way backstage was completely awestruck, such that it was a long while before they remembered the interview questions in their notebook.\\n"Lady Furina, might I ask how you were able to attain such great mastery acting as an Archon, though no one has ever seen you practice?"\\nFurina\'s reply was proud, albeit uncharacteristically simple. "Why, because I am a god. Next question!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Cases and performances take up a great deal of Furina's time, and even without these two things, she still shows up for all kinds of social activities and dinner parties related to government business and diplomacy.\\nOf course, social engagement is usually the limit of her remit, while the real behind-the-scenes work, and sometimes even certain important speeches made during these interactions, are handled by others.\\nFurina is quite thankful for these proxies, for she has heard that her life of leisure is a rare privilege in a world where most other gods have an endless parade of duties large and small to attend to.\\nShe once considered that it might be right to set a... godly example, so to speak, and so she attempted to take part in the Palais Mermonia's day-to-day work when she had an excessive amount of free time on her hands...\\nHowever, her offers were respectfully yet consistently declined by both humans and Melusines, who insisted that \"there are no great duties at present that need to be handed over to our god.\"\\nThough these words did make her glad, of course, after a few attempts she quickly realized how impractical it would be to use the work of the Palais Mermonia to escape her boredom.\\nFurina actually has another hobby, known to very few, and that is playing with little animals.\\nFontaine's waterscapes are vast and beautiful, as well as blessed with innumerable adorable creatures. For one who always finds herself interacting with humans like Furina, this serves as an excellent change of pace.\\nHowever, animal habits are inconsistent and unpredictable, and Furina's carefree attitude always seems to rub them the wrong way. As in the \"if she's not being blasted in the face by Hat Jellyfish, then she's being pursued to the ends of the ocean by Hunter's Rays\" kind of wrong way.\\nIt can be argued that the underwater world is more primitive and wild than the surface world, considering how little respect the animals here give a god on account of her status alone.\\nNonetheless, Furina did eventually discover the animal for her ministrations — the sunbathing, beach-loving, horizontal alignment-enjoying Blubberbeasts.\\nCheek squeezes, belly rubs, and even flipping them over, then over again, gets at most a turn of the head and noiseless protest.\\n\"Hmm? You like it? Hehe, so do I!\"\\nA few mild miscommunications aside, they have since become the best of friends.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Although Furina does tend to give people the impression of one prone to wandering thoughts and only tangential concern for the rules, she does have strict standards — in certain circumstances, anyway, especially before or after performances.\\nEverything must be to her satisfaction, be it the make or color of the props, the timing of the brightening and dimming of the lighting, or the pace and rhythm of the music.\\nAs such, sharing the stage with a god is not some shortcut to glory, but one paved with blood, sweat, and tears, to the point where even the stories of a hard-to-please superstar prima donna fond of shows and with theatrical swagger to spare has reached even the lowliest street stalls.\\nIndeed, there was once a famous troupe that won the chance to perform with her, and pretended to agree to her exacting demands, only to default to methods they were more accustomed to during real rehearsals and performance prep.\\nThe troupe director was confident in this method, believing that given Furina\'s personality, she would be most willing to back down on said demands if she were appropriately flattered and saw that everything was already complete and thus too late to change — a most excellent way to save effort and trouble.\\nBut when the director began moving their props to the Opera Epiclese, he found Furina there, directing another troupe as they set up the stage rigging.\\n"Why, hello. You didn\'t seem interested in my opinions, so I arranged to perform with a different troupe."\\nThe director was stunned. He had planned for Furina to discover the "flaws" in her view only after setup was complete.\\nBut he could already tell that the stage sections that had been constructed precisely in accordance with her directions were significantly superior. Ordinary audience members couldn\'t necessarily tell, of course, but to professionals, the difference was always in the details, and these were obvious at a glance.\\nStill, this director was unwilling to simply turn back, criticizing Furina for not adhering to the spirit of contractual obligation by not informing them beforehand of her contingency arrangements.\\nFurina would not let this villain cast the first stone, instead scrunching her face into an expression of disbelief.\\n"You don\'t really think I\'m that much of a gullible fool, do you? Guards! Send them on their way."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Round and round the interminable performance went, the day of the curtain call ever beyond reach, but so long as the prophecy loomed, the tale of this god must go on.\\nThough Fontainians found no real reason to doubt Furina over the years, she knew that the collapse of trust could begin with a single crack. No matter how small, once it appeared, it would be irreversible.\\nAnd the consequences of being exposed would be to reduce all her long years of work to dust, to allow Fontaine to fall — that was unconscionable!\\nSo she did her best to laugh loudly when she should be glad, and weep bitterly when she should grieve, and display the divine bearing of an Archon when it was time to show off, all without fail, all without rest.\\nShe knew that this was a performance. If she could endure until the danger had passed, she could finally take off her mask and regain the freedom to express her feelings.\\nYet, she slowly began to realize that the godly role she was playing was eating into her.\\nA horrifying doubt began to creep up on her — how should she react when glad, if not to laugh loudly?\\nPerhaps she was once a girl who did not much enjoy laughter. Perhaps she had once been the sort to give up on herself at the first sign of difficulty, but such emotions had already slipped away, bit by bit.\\nThose in the performance arts often say that one must become a character to play them.\\nFrom that perspective, Furina's performance as the Hydro Archon has been flawless. Her painstaking perseverance produced the perfect product.\\nBut no one has ever spoken of what might transpire once the last light had dimmed, for to them, the stage is fleeting.\\nFor one such as Furina, who has acted for far too long, even the path back offstage has faded into dust, buried by the sands of time.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "The crisis of original sin was resolved, and Fontaine came under a new order. The affected areas were gradually rebuilt, and the people held high hopes for the future.\\nFurina was the only one with no place in this new world. She was quick to pack her bags and leave the Palais Mermonia, nor did she return to the Opera Epiclese.\\nShe simply wanted to leave the memories that brought her so much pain as far behind as possible, and she was uninterested in the debates surrounding her — the Hydro Archon's tale was over, as it should be.\\nBut where should an actress who had finished her part and fulfilled her duty go? None could say, and the concept of \"freedom\" rang hollow.\\nFurina's luggage remained piled up in her new rental apartment, and she lacked all will even to tidy up or get moved in. All she could do was lie in bed and stare at the bare ceiling.\\nThose she knew had very quickly found their place in the new order. Whether due to their strength, duties, or friendships, their importance made them irreplaceable.\\nIn circumstances such as these, didn't \"free\" simply mean being someone who no one needed?\\nJust as she had reached this conclusion, her new residence received its first guest — Clorinde the Champion Duelist.\\nThe duelist was shocked at Furina's living conditions, quickly expressing her willingness to pay for better accommodations, a notion Furina expended no small amount of effort disabusing her of. Despite this, she was dragged, however reluctantly, into at least properly unpacking and tidying up the room.\\nClorinde then explained that she was here to invite Furina to a gathering. The duelist rarely took part in social events, but this gathering was one of old friends, who, as it happened, also knew Furina, and whom Clorinde had not seen in a while, anyway, so she thought she'd extend an invitation.\\nIn days past, Furina would certainly have refused, for the greater the intimacy of her association with others, the more difficult it would be to conceal her true identity.\\nThe duelist smiled as Furina guiltily lifted her eyes, having seemingly already guessed the latter's feelings as well as her old reasons for snubbing such events.\\n\"I don't suppose you have any reason to refuse now, do you?\"\\n\"Well... I'm not very good at this sort of thing, so, um... Don't you think I'd, you know, be a bit of a wet blanket?\"\\nThat night, Furina finally got to experience what it was like to revel and drink with friends. In truth, she was cautious at first but was restored to her normal self within two cups — indeed, so much so that at one point Clorinde had to restrain her from leaping onto the table.\\nFor someone as reticent as the duelist, the real Furina's explosiveness was quite the surprise.\\nAs for Furina, she still knew not where to go, but if nothing else, she now knew that \"freedom\" did not mean solitude.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Salon Solitaire',
      title2: null,
      text: "Furina once found a relatively unknown book in a library of Fontaine, and the story's main character was a servant working in an opulent mansion.\\nThe idealistic young Mademoiselle Crabaletta, following a newspaper advertisement, came to a remote manor in the mountains to apply for employment, and despite her clumsiness, became a maid there all the same.\\nThe Master of said mansion did not appear often, and though his loquacious surintendante and etiquette-minded gentilhomme managed it in his absence, she led a carefree life there.\\nNone of the manor's attendants had been to the city in quite a long while, and so the maid taught them to sing the latest songs, play the latest tabletop games, and thus the servants grew closer and enjoyed one another's company.\\nThere was but one ironclad rule, which was that none should approach the heavy wooden door that led three floors underground, behind which was locked a secret that only the Master of the mansion was privy to.\\nThough the maid was curious, she treasured her vibrant life there too much to pry. Time passed quietly, and one day, they were told by the gentilhomme that the Master was about to visit, and so the servants hurriedly began to prepare.\\nThe banquet was akin to a festival, and laughter and cheer filled every corner of the mansion — at least, until the Master was late the second day, and upon investigating, the maid was to discover his already-cold corpse.\\nThe Gardes narrowed the suspects down to the servants, but the maid, convinced that the Master's death had something to do with the mansion's secret, at last decided to open that forbidden gate.\\nTo her surprise, what awaited her on the other side was the mansion's main hall, upon the central stairs of which stood the all-too-familiar surintendante of the house. The words she spoke, too, were bizarrely known to the maid.\\n\"Ah, you must be our newest applicant. Crabaletta, I believe?\"\\nFurina was quite dumbfounded when she read that, for the story here recalled similar events in her memories.\\nShe admired the happy lives of the maid and the other servants, and the maid's courage in facing down the ancient secret to defend that life.\\nLater, Furina dreamt of that same mansion. In her dream, she was Crabaletta, huffing and puffing as she ran to that door of secrets, and, with one deep breath, pushed it open.\\nBehind it was a torrent of seawater that drowned the mansion in an instant, dissolving all in its wake — the Gardes, the surintendante of the house, the gentilhomme, and even herself.\\nFurina woke with a start, looking around her to gather her wits, and the rest of the story sprang to her mind, unbidden...\\nCrabaletta made use of the time loop triggered by opening the door to solve the mystery of the Master's death and discover the mansion's secret, freeing all its inhabitants from an ancient curse.\\n\"Thank you, Crabaletta.\"\\nShe thanked the brave, stalwart girl for giving that tale a happy ending.\\nAnd as for several vivid figures from the story, they would eventually be given lovely forms, that they might be by Furina's side.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: '???',
      title2: 'Vision',
      text: '',
      text2:
        '"If you become human, you can reveal your secret to no one. You will face suffering and loneliness... Is this still what you want?"\\nBy a twist of fate, the musical "The Little Oceanid" which nearly died before it could live, got the chance to be performed, and proved a resounding success at the Opera Epiclese.\\nFurina, standing in for the real actress, played the heroine Clio, who sacrificed herself to guide the freshwater upon which human survival depended back to them.\\nAccording to the script, she was not to take up the Vision that would appear before her as she disappeared, but instead allow it to fall into the ocean depths alone.\\nBut during the actual performance, a real Vision appeared, and it belonged to Furina.\\nVisions are usually objects that appear in response to humankind\'s most fervent wishes, but this one, in particular, seemed more like a reward for her past deeds.\\nAs Furina grasped it, its reflected radiance seemed to contain her heart, filled once again by this performance.\\nPerforming had, in the past, brought her much pain, to the point where she had turned her back on the stage, but she indubitably understood the glory and brilliance of the stage best of all, and could give those who chase their dreams on the stage her matchless guidance and support.\\nAs to the question of what to do next, which had plagued her for so long, she now had a clear answer:\\nTo see this world from the perspective of the audience, and create the greatest performances without stepping onstage.\\nNo longer would her attention be focused only on musicals — as long as it\'s related to performance, Furina is interested in taking part from behind the curtain.\\nAlso, it is worth mentioning that though she seemed quite calm upon receiving that Vision, so much so that she even managed a few fine words, upon leaving the theater troupe, Furina immediately set off afterward to avenge herself on the "Local Legend" she had once angered by accident... which ended quite poorly for her.\\nShe returned home, dejected but not defeated. She spent all night studying her Vision, which ended up causing the entire building to flood.\\nAnd once she had finally cleaned things up together with the Salon Members, she received a final missive from the apartment manager.\\n"No pets allowed in these apartments — not even if they are a Gentilhomme or Surintendante."',
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
