export const yelanVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Hello, Traveler. Call me Yelan. I think you may need my help, and I just so happen to be interested in some information you have. In other words — you scratch my back, I'll scratch yours.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Tip-Off',
      audio: '1101',
      text: 'I got a new letter from an informant. Looks like the situation has changed again.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Truancy',
      audio: '1102',
      text: "Good roll... Alright, maybe I'll take one more day off, and knock out the rest of the work once I'm feeling up to it.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Identity',
      audio: '1103',
      text: 'Navigating the world is a whole lot easier with a few different identities to choose from. Need me to come up with some for you?',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "It's raining again? Oh, this isn't good... If the rain washes away the traces, it's gonna set us back a long way...",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Only innocent children and timid adults are scared of thunder. But you're not either of those... are you?",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "It's getting a little cold... Time to bundle up.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'This blinding sunlight is such a pain... No way I can get a nap in this weather.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "There's a restlessness in the wind... Hmm...",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Mmm~ So early... I usually get up at noon if I don't have any urgent work.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Ah, I'm getting sleepy. Think I'll take a nap... Don't wake me. I'll wake up naturally when it's time to work.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. Have you had dinner? What did you have, how was it? Oh... Just making conversation. Don't think anything of it.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "Come on now, drink your milk and go to sleep. What? You're not a kid? Hehe... Alright, well, I'll just leave it right here, it's yours if you want it. I usually fall asleep well after midnight. Full disclosure — if you're a sleep talker, I can't promise I won't take notes, kay?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Yelan: Duties',
      audio: '2001',
      text: "The Qixing know Liyue like the back of their hands. But there's certain information out there that can only be obtained using more specialized methods. That's my area of expertise, so I generally take care of all those assignments myself.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Yelan: Rumors',
      audio: '2005',
      text: "Some say the boss of Yanshang Teahouse is a young entrepreneur who got rich overnight; some say there's a sickly and frail senior employee of the Ministry of Civil Affairs living as a hermit outside the city; others say you should stay away from restricted areas, or you'll get haunted by a blue ghost... Obviously, most civilians have never heard the name Yelan before. So you can safely laugh off all these rumors.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Relationship',
      audio: '2003',
      text: "Huh? What's that look on your face for? You don't have to be on guard around me. I never scheme against people who have my stamp of approval.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Deception',
      audio: '2002',
      text: "Don't be too ready to believe people when they cross their heart and hope to die. Sweet talkers only say what you want to hear. And think twice before meeting someone else's gaze — your eyes speak volumes about what you're thinking. When it comes down to it, we're friends, and if somebody ever conned you, I'd feel like I'd been cheated, too.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Wherever there's important information to be found, the stakes involved in extracting it are often fatal. It doesn't matter how big or reliable the team under you may be, you can never completely rule out the risk. The bottom line is, have enough force at your fingertips to control the situation. I got lucky — I got my Vision just a few days after realizing that. Otherwise... you'd probably be talking to a very disheveled-looking ghost right now.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Anything to Share: Blocking Out Noise',
      audio: '3002',
      text: "If you grind Loach Pearls down to size, they make excellent earplugs. They're very sound-proof — you can sleep away blissfully even when there's someone screaming right in your ear... Of course, I hope for your sake that you don't ever need them for that kind of reason.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Anything to Share: Fascinating Bracelet',
      audio: '3004',
      text: "The bracelet on my right hand? I suppose there's no harm in telling you... It contains a kind of magic used by our clan, and it can send simple messages. The meaning of those messages is buried in the blue light, and only I can decipher them.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Anything to Share: Pursuing the Target',
      audio: '3005',
      text: "When I'm tracking a target, I like to put psychological pressure on them. In the process of trying to shake me off, they will start to panic, bring in reinforcements, alter their plan... they keep going like this until eventually, they've exposed everything I need to know. Heh...",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Do you know much about Weasel Thieves? They're not especially intelligent creatures, but once you tame them, they can be trained to steal things and even pick locks. Pretty clear-cut case, isn't it — if even animals can be used as pawns with the right methods, the same has to be all the more true of people, who are constantly plotting and scheming against one another to begin with.",
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'About Ningguang: Relationship',
      audio: '4001',
      text: "I got to know Ningguang a long time ago, before she was a Qixing, and we worked together for a while. Maybe I'm partly to thank for the fact that she became a Qixing so quickly. Hehe, who can say? Anyway, she was the one who recommended this job to me. It was a good choice, I'm very well-suited to it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Ningguang: Expectations',
      audio: '4002',
      text: 'Ningguang is good to work with. But I have to be mindful of our identities when I\'m out in public. When I meet a Qixing as an employee of the Ministry of Civil Affairs, they\'re "Sir" or "Lady" to me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Ganyu',
      audio: '4003',
      text: 'Ah, the secretary... I could never work non-stop like she does, certainly not at that level of efficiency. I guess being half-adeptus must have its perks. Imagine not needing sleep to regain your energy levels...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Keqing',
      audio: '4004',
      text: "I don't really like people who cram their schedules full, because it doesn't leave any room for negotiation. If something happens that they didn't anticipate, it throws their plans into oblivion, impacting not just themselves but their coworkers, too. But the Yuheng is different. She works in a very methodical way. I always enjoy working with her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Yanfei',
      audio: '4005',
      text: "I like Yanfei a lot. And I'm not talking about our friendship — as a high-profile legal consultant, important intel in Liyue Harbor is constantly flowing in her direction. Whenever I help her out, I always get some invaluable leads in return. I gotta say though, sometimes I think she respects me a little too much.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Xiao',
      audio: '4006',
      text: 'The elders in my clan once said that we must always show the utmost respect to the Vigilant Yaksha. Apparently, the only time that our ancestor would gain some temporary relief from his insanity was when passing by the Wangshu Inn. It must have been the comforting effect of his presence that wards off evil spirits. That said, if I ever have the honor of fighting side by side with the Conqueror of Demons, I will focus only on the mission. I cannot let myself be distracted by concerns about his status.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Xiangling',
      audio: '4007',
      text: "Ah, Xiangling, the lovely little chef. Her ingredients are always top quality, easily as good as Liuli Pavilion and Xinyue Kiosk. Sometimes I go to her for dried Jueyun Chilis... She doesn't seem to understand why I eat them in the way that I do, and I don't feel like trying to explain it to her, either. It's just a family tradition.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Xingqiu',
      audio: '4008',
      text: "Of course I remember him — the young master of the Feiyun Commerce Guild. I have dealings with his family all the time. Who knows... maybe one day, he'll be outsmarting everyone around him, too.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Tartaglia',
      audio: '4009',
      text: "The Fatui harbinger? He helped me out once — unwittingly. I was planning a deep-reaching investigation into the former owner of the Yanshang Teahouse, but our harbinger friend got to him first. He showed up demanding payment of his debt, and also exposed his accounting fraud, which got him thrown in jail. That made it very easy for me to take over Yanshang Teahouse myself, and it's proven to be a very useful base.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Yelan: I',
      audio: '5001',
      text: "The reason I'm willing to bet on you is because of your special status. I think it'll bring me a lot of leads that can get me closer to the truth... Heh, so, got any news for me today?",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Yelan: II',
      audio: '5002',
      text: "Exchanging information has to be a two-way thing, so I guess I can tell you something about my past. Thanks to my family's connections, I learned some useful skills from the Millelith scouts very early on. Although there are things working against you every step of the way when you're gathering intelligence, as long as I keep myself alive, I'll always emerge as the winner in the end...",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Yelan: III',
      audio: '5003',
      text: 'Clues are links in a chain. You have to trace them all the way back to where everything began before there can be a resolution. To that end, I need to keep my eyes and ears on every part of society, and often, that means having to be more than one person. People sometimes describe me as "one person, many faces" and so on... I take it as a compliment.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Yelan: IV',
      audio: '5004',
      text: "Someone once warned me to be careful about digging up certain things from the past. Dig too deep and you might find yourself standing in your own grave, they say... Well, I'm not about to stop, least of all because of anything anyone else has to say. Sure, I can't change the facts, but if it's a choice between the cold, hard truth and blissful unawareness, I'll take the former. What about you? Which would you choose?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Yelan: V',
      audio: '5005',
      text: "Tell me something. If I'm gonna stay around, what kind of person do you want me to be to you? Someone you work with? A competitor, who challenges you to sharpen your game? Just another name on your long list of acquaintances, or... somebody more important than that? Depending on what you're hoping for, I can either play that part or become that person.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "Yelan's Hobbies",
      audio: '6001',
      text: "In my free time, I live life completely at random. It's quite simple: I make a list of things to do, then I roll the dice to decide which one I'm going to do next. It's a surprisingly fun game, and it's really broadened my mind... in that sense, it's been quite helpful where my job is concerned.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Yelan's Troubles",
      audio: '6002',
      text: "My physical fitness isn't actually that great compared with some trained martial artists. It's a hereditary thing that runs in my family. So before getting into really important work, I adjust my schedule to make sure I get enough rest, wait till I have built up enough energy, then strive to finish everything that needs doing in one go. Outside of work, I try my best to live life at a calm and carefree pace. So I'll always decline to take on any strenuous physical labor.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'I like to grind dried Jueyun Chilis and Violetgrass stamens into powder, mix them in with some Yunlai White Tea leaves, and then brew a strong pot of tea. It has the most powerful fragrance that makes you instantly fall in love with it. I prefer drinks like this with a long-lasting aftertaste to things like coffee and spirits.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "You have to be very careful with sweets. That powerful sense of satisfaction... it weakens your willpower and makes you relaxed. It only takes a few bites to get addicted, and with long-term consumption, you'll slowly but surely lose your edge.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Hm, not bad. Almost good enough to bribe me with.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Once you get accustomed to spicy food, everything else tastes bland. That's just the way it is.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Shall we roll some dice? Whoever gets the lowest number... gets to eat it.',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "If I was to tell you that maybe you shouldn't celebrate too hard today, because you'll let your guard down, and someone out there might just be waiting for that moment to make their move on you... it probably wouldn't go down very well. So, relax and take it easy today. Oh, and you should stop by the Yanshang Teahouse — I whipped up some treats especially for you. Not sweet ones, of course. Just the tiniest little hint of chili.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'In my line of work, combat skills are essential.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Sometimes, you have to strike hard and fast at just the right moment to expose the lies while avoiding any unwanted interference.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Finding the truth might sound simple, but it takes perseverance to stick to the trail of clues and it takes strength to follow them deep into dangerous territory.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I have long regarded you as my most important informant. Naturally, I need to be fully prepared to face whatever risks come with the final answer when you bring it to me. Come on, let's go get it!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Busted.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Gotcha.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Quietly now.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Game's up, fun's over!",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Here comes the catch.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Things are about to get dicey.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Take it easy.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Easy money.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Treasure... one way to draw your target out of hiding.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'A chest full of valuables... and a trove of potential clues.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'What a drag...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: "Winging it wasn't the best idea...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: "I didn't factor this in...",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Get back, I'll finish this job.",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "You're running cold, allow me.",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'What are... the odds?',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'How was I... so wrong...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'But the truth... is still unknown...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Gutsy.',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'No...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Who's our target this time?",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "It's time to pull the trigger.",
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Let's go get ourselves some answers.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Liyue's Ministry of Civil Affairs is an organization marked by transparency — from ordinary staff members of the Eight Trades to prominent officials of Yujing Terrace, every employee has their basic information documented in the Ministry's lists.\\nYelan, despite claiming to work for the Ministry, is the sole exception. Most of her colleagues have never heard of her, nor is her name anywhere to be found on any rosters.\\nThis does say something about her character — elusive, enigmatic, and erratic.\\nShe is a ghost who walks in the middle of many crises under various names. But before the storms can come to an end, she has already disappeared without a trace.\\nSometimes, she will pick a side in some conflict to offer her help, but those who receive her aid would be fools to celebrate prematurely, for they soon find that the same help has been extended to their opponents.\\nHaving stepped into her trap, many have vowed to take revenge, yet none are able to tell what she is planning, let alone know where she stands.\\nMany believe that she is a spy who works for some mysterious organization, and that her forte is stirring things up in the dark, which she then relies on to attain what she wants.\\nSome even go as far as saying that she is a frenetic follower of disorder who neither serves any organization nor holds any meaningful purposes.\\nEven if she does, all she wants is to add fuel to the already spreading flame and drag everyone down into a world of madness created by her.\\nWith so many theories and guesses circulating, she has become a mystery. As for the truth, you could only hope to get an answer from Yelan herself.\\nBut unfortunately, this is no easy task either — for it is always she who finds you when she wishes to, not the other way around.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Pharmacies in Liyue Harbor occasionally receive curious patients.\\nOn some days, it might be a Sumeru mercenary, on other days, a Fontaine adventurer, and there might even be some Mondstadt fisher who accidentally fell into water and bumped her head against a rock...\\nThese people are of different ages, statuses, and origins, but there is something equally peculiar to them, that is, they all share a slight addiction to pain.\\nThey like the stinging sensation when pharmacists apply herbal remedies to their wounds and enjoy the dull pain caused by pressure on their bruises.\\nThey even seem to care little if anesthetic is used or not when they are put through painful therapies.\\nSurprised by their extraordinary endurance, novice pharmacists are sufficiently distracted, such that they fail to notice that all their patients are actually the same person.\\nThey are, all of them, Yelan in disguise. A master in this art, she always manages to avoid attention.\\nAs for the wounds on her person, these are the inevitable result of her constant exposure to danger from mission to mission.\\nDespite the curious job, Yelan herself is not very curious about the world.\\nShe eats, sleeps, and lives just like everyone else, but few things can really pique her interest.\\nShe is well-read, but she is no avid reader. She always knows what to say to achieve the best result, yet she takes no pleasure in playing mind games.\\nShe travels far and roams the lands, yet the traveling and roaming are bland to her.\\nIn Yelan\'s eyes, these things are not hobbies, but a means to an end.\\nShe even prefers to roll the dice to decide how she will pass the time.\\nJust as someone who is so used to spicy food might lose the ability to enjoy ordinary dishes, Yelan finds that only spicy cuisine can bring her satisfaction.\\n"Blandness is synonymous with blindness, while thrills afford clarity."\\nActing upon said philosophy, she chooses an acute style of life, venturing into many places while hiding in the shadows.\\nShe dances with danger, secrets, and a strong sense of achievement — these are the vivid proof of her existence.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Shorn of her masks, Yelan is a special intelligence officer who reports directly to the Tianquan Ningguang.\\nThe title itself is not entirely accurate, for it only covers the scope of her work but not her relationship with the Tianquan.\\nDeep in her heart, Yelan does not think of herself as anyone's subordinate. The way she sees it, she is not so much working for Ningguang as making good on her end of the deal, or rather... she is honoring a certain pact.\\nShe plucks the fruits of intelligence from the tree of danger for Ningguang, and in return, all she asks for is danger itself and the sense of achievement.\\nNone know when their collaboration began.\\nThe only thing certain is that Yelan has long made her presence felt in lands outside Liyue.\\nFrom other nations in Teyvat to even the perilous Abyss...\\nEvery secret and perilous demesne shall become a garden where orchids bloom.\\nStealthily she roams the night, stars shining upon her in the skies.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Yelan spends much of her time patrolling and roaming The Chasm, where she often stares into the darkness deep below.\\nHer family's history dates far back into an ancient age, and her ancestors once fought in The Chasm against a great cataclysm.\\nWanton death was dealt during that battle, and even a yaksha met their end there. Only a few survived the grueling bloodshed.\\nOne of her ancestors died, while the other went insane, constituting a huge blow to her family.\\nYelan has always wanted to find out what happened back then. Despite her better judgment, she can't help feeling attracted to The Chasm.\\nIt almost feels like something that runs in her blood — something inexplicably ominous — has been summoning her to The Chasm.\\nPerhaps she will plunge into that darkness one day, and the ill fate that once befell her ancestors shall find her too.\\nThe ominous calling that runs in the family shuts down her fear and turns on her craving for danger. This may be the reason for the peculiarities in her character, Yelan presumed.\\nShe had never doubted it until she came of age, until the seal on The Chasm was lifted.\\nWith the help of her companions, she unveiled the hidden past of her ancestors.\\nThat moment marked a new chapter in her life:\\nIn the past, she was a wild beast driven by pure instinct. Drawn to danger, she walked into darkness.\\nFrom that moment on, she has found the true meaning of her instinct.\\nThat which hides inside her, that constant calling, is not only a source of worry but also a light of guidance.\\nIt is the blood of heroes which has been howling for 500 years.\\nShe has no fear, for the courage within her makes her strong. She craves danger, for the heir of heroes is meant for a great adventure.\\nSome day, she will embark on the path her ancestors once took.\\nShe is the descendant of heroes, and she shall become the hero for many who will come after her.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "The Ministry of Civil Affairs has a Special Attention List.\\nThe list isn't long, but everyone on it is truly extraordinary:\\nFor instance, the unbound and forthright leader of the armed fleet and the capable outland traveler with a broad range of skills.\\nThe list even includes some reclusive adepti in Liyue whose names still bear great weight today...\\nThese people could easily bring storms upon Liyue, their intentions notwithstanding.\\nAs such, the Ministry of Civil Affairs, ever on guard against risk, still watches them closely.\\nOn top of that, there is also a more classified Secret Intelligence List.\\nThose on it are the real threats to Liyue.\\nSo who are they exactly?\\nThe Fatui Harbingers? Figures from the Abyss Order?\\nOr perhaps, are even the names of gods listed there?\\nOther than the Qixing, Yelan is likely to be the only one who can answer these questions, for she is the very person who compiled the two lists.\\nThe results of such work please her greatly, and day after day, she perfects the lists, as crows embellishing their nests with shining trinkets.\\nThat said, while both are equally obsessed with collecting, Yelan must sweat and even bleed to secure what she is after, while crows need only flap their wings to achieve their aim.\\nFortunately, this does not bother her at all, for she believes that the intelligence is worth whatever cost she is going to pay.\\nOne day, the information will come in handy — Liyue will never plunge into disaster without any clue of the danger like it once did 500 years ago.\\nShe will see to it that Liyue is not caught unprepared.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Don't play dice at Yanshang Teahouse.\\nIf you can't help yourself, play with someone you know.\\nIf a lady whom you've never seen before invites you to a game, just ignore her.\\nHeed this earnest advice from veteran gamblers.\\nDo not try your luck with that terrifying woman unless you want to have a gloomy day.\\nThe invincible lady of Yanshang Teahouse is none other than Yelan herself, and one of her guises is that of the owner of this teahouse.\\nA while ago when she came back from abroad, Liyue had just weathered the Osial crisis, and the Fatui who had occupied Yanshang Teahouse were now largely out of the game.\\nYelan seized the opportunity to take it over, turning the teahouse into a secret base.\\nOn the one hand, with people from all walks of life to be found here, the teahouse serves as an ideal source of intel. On the other hand, as Yelan has no issue with occasionally giving herself a break, she will pretend to be a regular customer, drinking some tea and playing a few rounds of some game.\\nEvery round of finger-guessing is a tiny adventure, and every roll of dice sends sporadic thrills down her spine. Even the smallest challenge is something she can never get enough of.\\nAs an intelligence operative, Yelan takes pride in her skills — she is confident that she can read her opponents' eyes and roll the dice such that they fall outside the rules but well within her designs.\\nIf there is a draw, that could only mean one thing: Her opponents are cheating too.\\nDon't try to reason with her. The very concept of \"reasoning\" is simply foreign to the Yanshang Teahouse, nor does it exist in Yelan's vocabulary.\\nBe good and choose between the pain of losing and the disgrace of cheating.\\nYou want to have neither, huh? Then why don't you turn the clock back to the very beginning? \\nDon't play dice at Yanshang Teahouse!",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'The Fascinating Bracelet and the Whitesilk Mantle',
      title2: null,
      text: 'Throughout Yelan\'s intelligence career so far, there has been one memorable operation that fuses both failure and success together.\\nOne could say that it was a failure because she lost a family heirloom named the "Fascinating Bracelet" during that operation.\\nThe inside of the jade bracelet is engraved with a spell passed through her line that turns the heirloom into a simple communication device. However, the spell requires a pair of such vessels to work. Now that only one bracelet is left, it is no more than a mere accessory.\\nHowever, the operation also proved a success for Yelan because her enemy did not get the upper hand, either. And this enemy of hers was no ordinary character — it was none other than "Regrator," Ninth of the Fatui Harbingers.\\nYelan infiltrated a secret trade route that was run by Regrator behind the scenes, intercepting the goods and picking the most precious one of them as compensation for her bracelet.\\nNow, there once existed a strange mystical beast in times of old. A robe made from its fur would be worth a fortune, and due to its rarity, such a robe is exceptionally hard to procure.\\nIn fact, the beast is so powerful that although it died centuries ago, its body remains intact today, and its fur still emits a mysterious fragrance.\\nRegrator had intended it as an offer to the Tsaritsa, yet Yelan unexpectedly intercepted it.\\nNot only that, she also rejected the style that Snezhnayans had chosen for their Tsaritsa — she yanked the fur off, combined it with Liyue\'s Ramie yarn, and made a rather fashionable sleeved mantle for herself.\\nThis series of happenings could be seen as significant or insignificant — depending on one\'s perspective. Ultimately, it all boils down to three words: gains and losses.\\nThe cycle of gaining and losing is a rather accurate summary of Yelan\'s life.\\nNone of that really bothers her though. Instead, she takes immense pleasure from it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Yelan wasn\'t always on her own. Many years ago, she once had a team who watched each others\' backs.\\nThere were a small group of people who for various reasons chose to tread a path in the dark with her.\\nBut back then, Yelan had not yet realized that her clever tricks and ingenious traps, the skills that she took pride in, could not solve everything for her.\\nEnemies with a strong sense of self-control would not bite her bait, opponents with cunning and calculating minds would not fall for her schemes, and those with overwhelming power would simply strong-arm their way out of her traps.\\nTherefore, Yelan and her team paid the price — one by one, they perished along the way, though they had long foreseen and prepared themselves for such a fate...\\nStill, after a mission to investigate the Abyss, Yelan eventually found herself left alone. For the first time in her life, she stopped, for a long, long time.\\nThis state of affairs persisted until one day, when Ningguang visited her in her wood hut personally.\\n"You haven\'t been back to Liyue Harbor for a while. Something must\'ve happened. I can understand if you want to quit."\\nNingguang stood outside the door, with a serious look on her face but her voice still casual and relaxed.\\n"But it\'s alright. I work with those I trust, and I trust those I work with. I\'m willing to believe that you\'re here trying to find a way out. All postures, aggressive or defensive, are all means to an end, anyway."\\nThere was no response, but only a suffocating silence. A long time passed before Ningguang finally heard an answer from behind her:\\n"We both made a mistake: We shouldn\'t have involved ordinary folk in what we do."\\n"Ordinary folk?"\\nEven as Ningguang was formulating thoughts, a flash of blue shot towards her, stopping as it passed her by.\\nIn a display of great control from the archer, the arrow quickly shattered into pearls of water and broke into glistening shards of light before touching the ground.\\nNingguang turned around and saw Yelan walking up, a bow in hand, blood dripping down from her fingertips.\\nOne could only imagine the days and nights of grueling training in archery Yelan had gone through for all her fingers to bleed.\\nKnowing Yelan well, Ningguang also understood that she must have been through an uncommonly tough situation. Only that could explain Yelan\'s uncommon determination to lock herself up for this grueling re-training.\\nYelan aimed at the mountain in the distance, a gesture that was also an answer to Ningguang.\\nShe released the arrow. Like lightning it shot into the skies, piercing through clouds with might that could shatter the dome of heaven itself. As if responding to the call of an unknown power, waters in the mountains growled and howled, then swirled their way upward in the form of countless arrows.\\nWhen they met halfway in the sky, they exploded into a curtain of water, bringing down a squalling shower like those that adorned summer nights.\\nAs the sky cleared, there was no rainbow, no butterflies to be seen, only a faint pillar of light that fell into Yelan\'s palm.\\nAccording to Ningguang, the Vision carries a message: "From today onward, leave all matters to the extraordinary Yelan."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
