export const charlotteVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Hi there! I'm Charlotte, a journalist with The Steambird. It's a pleasure to meet you. If you've got time, would you be open to doing an exclusive interview? My journalistic instincts tell me that there's a treasure trove of news in you just bursting to get out!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: News',
      audio: '1101',
      text: "If you keep your eyes peeled and your mind engaged, you'll find there's always a news story nearby just waiting to be discovered.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Journalists',
      audio: '1102',
      text: "There are lots of journalists in the Court of Fontaine, but not all of them hold themselves to a high professional standard. If you're ever looking to do an interview... I'm your best choice.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: The Steambird',
      audio: '1103',
      text: 'The Steambird is an excellent publication. They have many outstanding journalists and the Editor-in-Chief is always open to new ideas. But most importantly, they pay their writers on time.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Uh-oh, I better find a way to keep my Kamera dry!',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Drat! Missed it again. I never quite manage to get a shot of the lightning strike...',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Brrr! My fingers are frozen stiff. I can barely manage to press the shutter button.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "Perfect lighting for a photo! C'mon, strike a pose. Don't forget to smile!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning! Did you read the paper yet? No? ...No worries, I'll read it for you...",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'Lunch time! Come with me — I know a great place!',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Time for an evening chat. Any stories you're willing to share? I'd love to hear them. ...Oh, don't worry, I won't print any of them without your permission. You have my word.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: 'Good night. You go get some rest — I gotta head to The Steambird offices to do some final proofreading of some articles. See you tomorrow!',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Charlotte: Career',
      audio: '2001',
      text: "People aren't always very fond of journalists. You know what they say — lies are soft and malleable, but the truth is sharp and inflexible.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Charlotte: Photography',
      audio: '2005',
      text: "I can't take a good photograph without an interesting subject. I really have to force myself to press the shutter button if I'm not excited by what I'm snapping.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Exclusive Feature',
      audio: '2003',
      text: 'Alright, the time has come for your interview. Ready to be a star? Just follow my lead and try to look good for the Kamera! You too, Paimon — you have the power of flight! Could you try to make it look a little more exciting?',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Headliners',
      audio: '2002',
      text: "Good news — I've convinced Euphrasie to make you the next headliners of The Steambird! You'll be right up there on the front cover, there'll be a whole feature about you that I wrote myself, and— Huh? What do you mean, \"no need\"? C'mon, I've been pushing Euphrasie for ages on this! Can't you reconsider? I'll make it up to you, I promise! I'll treat you to a huge meal, pleeease?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: "To be honest... I'd prefer to have an Anemo Vision. Being able to fly around freely would make getting to interviews sooo much easier! A Cryo Vision's not too bad, though. At least I don't need to worry about my Kamera overheating.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: '"Your credible source of the unbelievable truth!" That\'s my journalistic motto. Hmm? ...Haha, yep, exactly — "credible" and "incredible" at the same time! What\'s that? ...Oh, if I had to choose, then obviously being credible is much more important! But most readers would sooner pay money for sensational stories than mundane facts... So we have to focus on the most incredible true stories to keep our readers engaged.',
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Allow me to introduce the one and only Monsieur Verite. He's not just any Kamera — he's my trusty companion and assistant. See his little hat and bow tie? I had those custom made by Chiori. Pretty neat, huh? I've got loads of other outfits for him too, all in different styles. He comes dressed to impress for every interview, whatever the occasion!",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Navia',
      audio: '4001',
      text: "Now that her father's name's been cleared, and the case of the serial disappearances of young women is resolved, I guess Navia must be able to finally breathe a little easier. I don't know why, but somehow, she's found herself at the epicenter of all sorts of bad news lately... Luckily for her, I've been snatching up all the articles that mention her and doing whatever damage control I can before they get published. Heh, and uh... then getting told off constantly by Euphrasie for interfering... But y'know, I think Navia deserves a break, so I'm happy to take one for the team. Also, she agreed to do an in-depth exclusive interview, which definitely sweetens the deal!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '20': {
      title: 'About Lyney',
      audio: '4002',
      text: "Surprise, surprise — Lyney refused an interview with me once again. Do you know how many times that is now? ...Uh, actually, I've lost count. But never mind! Evading me only further confirms my suspicion that he's hiding the news story of a lifetime! As long as I keep digging, I'll find it — and when I do, it will shake the world like no other news report in history!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Lynette',
      audio: '4003',
      text: "No matter what question you pose to her, Lynette just calmly lowers her eyes with an expressionless look on her face. It's like she's some sort of... clockwork doll. I'm really tempted to write an article titled something like: \"The Genius Magician's Puppet Assistant: Magic's Best-Kept Secret\"... but I have a sneaking suspicion that even that wouldn't get a reaction out of her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Clorinde',
      audio: '4004',
      text: "Clorinde is one of the most well-known Champion Duelists in Fontaine, but she's also the most mysterious. I have a source who tells me that she uses some sort of mystical ritual to keep her weapon as good as new... Could this be the secret behind her famously undefeated track record in the Duelists' Ring? Ah, I'd love to spring that question on her one day... but I don't think I'll get the chance. She's publicly stated that she doesn't accept interviews.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Wriothesley',
      audio: '4005',
      text: 'So... Did you get to meet the Duke in person? Yeah? Any nuggets of information that I should know about? Never mind the Credit Coupons, the Coupon Cafeteria, "If a man will not work, he shall not eat"... That\'s all just generic filler. I\'m talking about personal anecdotes about the man of Meropide himself... What do you mean, "confidentiality"? Aw, not you, too! We had a deal! That does it — remember that gigantic feast I treated you to? I want my money back! Get your butts back to prison and do your time, you swindlers, you!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4019,
              chapterId: 1404,
              chapterTitle: "Cataclysm's Quickening",
            },
          ],
        },
      ],
    },
    '24': {
      title: 'About Emilie',
      audio: '4006',
      text: "Emilie makes the best perfume in the whole Court of Fontaine. She introduced me to this amazing one the other day that works as an insect repellent, anti-perspirant, and deodorant all in one! It's a total life-saver for someone like me who spends so much time zooming around all over the place. I actually sprayed some on my wrist today... Go on, take a whiff, it's heavenly!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Chiori',
      audio: '4007',
      text: 'I did a little snooping around at Chioriya Boutique once. Aside from the wealthy housewives of Fontaine and the box-ticking tourists from overseas, some of the regular customers there look like really rough characters! Big muscly types with scars on their face, guys in masks and hats with their swords drawn... But they always come bearing gifts and acting like humble servants. Uh... Well, mostly. Anyone with a bad attitude is literally sent flying back out the door. Seriously! I snapped a photo of a guy being thrown out once, he was like four feet in the air!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Freminet',
      audio: '4008',
      text: "I've met Freminet a few times since being introduced. He quickly took an interest in Monsieur Verite — that's my Kamera-slash-assistant — and even made a few improvements to my lenses. I gotta say, though, my heart was in my mouth watching him completely dismantle Monsieur Verite in a matter of seconds... Amazing he managed to reassemble it just as swiftly. He seems very experienced — I was convinced he must have graduated from the Fontaine Research Institute, but he denied it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '27': {
      title: 'About Neuvillette',
      audio: '4009',
      text: "If you want to interview the Iudex, you have to provide all the interview questions in advance and get them reviewed by the relevant department at the Palais Mermonia, who decide which questions to approve and which ones you're not allowed to ask... It's their way of making sure the interview goes off without a hitch. It's such a rigmarole. I'm losing the will to live just talking about it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Furina',
      audio: '4010',
      text: "Lady Furina has a very captivating presence. She was born to be a star. Euphrasie once assigned a journalist to shadow her, but he quit not long into the assignment... From what I've heard, the reason he left was that Furina insisted on seeing every photo he took of her right away, and she'd make him redo it if she wasn't happy with how it turned out. Apparently, she was so picky that the poor guy once had to take 127 shots of her in the same pose before she was content...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Escoffier',
      audio: '4011',
      text: "I've tried so many amazing dishes thanks to her! Between her work, the other chefs at her Hotel, and her apprentices, I can almost call myself a food critic at this point. I feel a little bad, getting to eat the finest food in Fontaine for free... But, I'm not complaining, either!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About Charlotte: I',
      audio: '5001',
      text: "I'm well aware that following the truth wherever it leads is risky business. But buried truths make exclusive news, so good luck trying to keep secrets from me when we need a good story... telling journalist like me in this world with a strong sense of journalistic integrity! Ahem! I make it my goal to provide the public with only the best exclusive news, through powerful, engaging, and honest reporting!",
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About Charlotte: II',
      audio: '5002',
      text: 'When I first started working as a journalist, I didn\'t know anything about how to write the news, so I had to figure it all out for myself by reading articles by other people. As well as The Steambird, I also looked at some other independent publications out there, which tend to be more specialized. For example, there\'s "The Observer" for celebrity gossip, "Leisure Weekly," which focuses on competitive sport and other entertainment news, "Top Chef" for those who like to read... all the food critiques in one place, and "Bedazzled!" which is just sort of a glorified rumor and speculation mill. I learned a whole lot from reading all those papers. Or... Well, I at least learned how to master a bunch of different writing styles.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About Charlotte: III',
      audio: '5003',
      text: "I once spent six months working undercover for an exposé piece about a merchant who was selling shoddy food products. I disguised myself as a vagrant, infiltrated the back kitchen, took a job as a kitchen hand, and stuck around until I'd gathered enough solid evidence about their misdeeds. Then, I put it all in an article and had it published in the paper. The backlash was intense. They were punished for their crimes, sure, but that didn't stop them from launching a vicious campaign of vengeance against me almost immediately. I was coming home to threat letters sitting on my bedside table on a daily basis, and we'd also find mud slung on the front door to our office... The Steambird quickly filed a report to the Gardes, and I was sent to Mondstadt to report on Genius Invokation TCG. It took a while before I could safely return to Fontaine. These kind of things happen all the time. I honestly don't know Euphrasie deals with it...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About Charlotte: IV',
      audio: '5004',
      text: "I've always been a very curious person. Even as a kid, long before I ever thought about going into journalism, I was always convinced that secrets and mysteries were lurking in every corner... To me, the world is a giant hoard of hidden treasure, with countless stories waiting to be uncovered. Every time I see something where I think a secret might be hiding, I snap a photo with my Kamera and add it to my collection. These photos are like my own personal treasure map... and I'm constantly going back to them, trying new ways to decipher them and expose the truth.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '34': {
      title: 'More About Charlotte: V',
      audio: '5005',
      text: "I don't really care whether these hidden truths are significant, what they mean, or what the wider ramifications are... I just want to bring them into the light of day. To put it in adventurer terms, I guess for me... it's all about the thrill of the chase, and not the treasure at the end. I've also met a lot of people along the way: all my Fontaine friends, Euphrasie, who believes I was born to be a journalist, and people like you, who join me in the search for the truth. Without everyone's help, I'd probably still be that nosy kid who runs around furiously snapping photos like a lunatic... Anywho... It's not often that I get to be the interviewee, but... this has been a real pleasure.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: "Charlotte's Hobbies",
      audio: '6001',
      text: "I love collecting different Kamera lenses. They all have different strengths — some might have an incredible range of focal lengths, others might have a really wide field of view. Oh, and there's also more novelty ones that can apply special effects to the image. Take this one, for example — when you take a portrait photo with this, it turns their face all chubby... C'mon, I'll take one of you! And you, Paimon!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: "Charlotte's Troubles",
      audio: '6012',
      text: "I've ended up with a less-than-favorable reputation in some people's eyes — I think it's because I can sometimes be a little bit, um... intense in interviews. Now, whenever I show up to interview someone, they're always really wary of me... *sigh* But in my defense, with some people, you really have to put the pressure on or they won't open up...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Hehe, sweet things are my weakness. However big the main meal, I can always manage a dessert or several. Or as my mother puts it... There's always a special place reserved in my stomach for dessert!",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Spicy food doesn't agree with me at all. It's like my stomach is fitted with a super-sensitive spice detector or something, 'cause even the mildest hint of chili will set it off. One small bite and the stomachache begins... and it always lasts for like an entire day, ugh...",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "You're a good chef! Any interest in starting a culinary column in our paper? I know just how we could slot you in.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Hey, not bad... Would you mind teaching me to make this some time?',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Whewee... This is uh, a juicy news story... with a gut-wrenching conclusion...',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy Birthday! Did you read today's Steambird yet? I put a birthday greeting in there for you, hehe... Wait, you still haven't bought a copy? No problem, I picked one up before leaving the office. Look — here it is! I fought pretty hard to get it on this page.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "What a strange and wonderful feeling... I've gotta write this down for my records.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "So this stuff really does boost people's strength, huh? I thought it was all rumors, but now here I am, experiencing it for myself...",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Have you done this for other people in the past, too? Were the materials you used different, and if so, how? Also, I'm wondering... Uh, sorry. Force of habit.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Holy smokes! My mind can think faster, my body has more energy... There's not a news story out there that can escape me now! But first things first — let's take a photo to commemorate this beautiful moment.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Say cheese!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Smile!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Hold that pose!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Truth bomb!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Breaking news!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Hard-hitting exclusive!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Ooh! This looks alright.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'I wish I could interview whoever left this stuff here.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "I doubt anyone's still looking for these...",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: I',
      audio: '410001',
      text: "I'm getting this all on Kamera...",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: II',
      audio: '410002',
      text: "There's still news to report!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: III',
      audio: '410003',
      text: "My Kamera's still working!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Careful!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I'm not writing your obituary!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Take these photos to The Steambird...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'At least I documented everything...',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Headline... Still needs a headline...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'How rude!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: 'My Kamera!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Let's get this interview started!",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "What's the news?",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Nearer to the action is closer to the truth!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'In the Court of Fontaine, a new "story" is born every minute.\\nFor example, Romaritime Harbor might suddenly swell with new ships, crewed by sailors of obviously non-Fontainian origin. Some fishmonger in Poisson might suddenly buy three months\' worth of fish in a single month, or countless flyers boasting of a certain place where especially delicious fish can be found might suddenly appear in the Court...\\nIn the eyes of a mediocre reporter or ordinary city folk, these are "independent" tales, just like there will always be waves rippling across the sea\'s surface — such ordinary events are barely worth paying attention to at all.\\nClumsier journalists might even chase these waves, and dispiritedly end up merely following the wave\'s patterns, constantly pumping out "surface-level stories" of little interest.\\nBut in Charlotte\'s eyes, these waves are but the superficial representation of other forces. What is causing them to crest and break? That is the story she seeks.\\nPerhaps it is the wild winds wailing over the surface, or perhaps they are due to the Thalatta Submarine Canyon\'s complex seabed topography. Of course, you can\'t rule out the possibility of tremors from the Elton Trench either...\\nThese stories are the "deep dives" Charlotte desires.\\nA reporter should be an agile "seeker" — not a mere gauche "recorder."\\nThis, then, is Charlotte\'s "work doctrine."\\nAs to how she avoids being swept up in her "deep dives"... well, that\'s up to Euphrasie and her fellow citizens!',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Charlotte was fascinated with the world around her from a young age.\\nThe first Rainbow Rose that bloomed in the yard come spring, exceeding all others in vibrance. The children gladly padding about in puddles on the leaf-strewn streets after a storm and their hapless laughing families. The beauty of a solitary shell on the seashore, and the tiny crab surveying the world from underneath. The Blubber Profiterole she had with her family on her birthday, and the ever-so-slightly-too-deep color of the cream...\\nTo most, a flower is a flower, a shell is a shell, and a Profiterole is still a Profiterole even if it is a bit too sweet — that\'s just how the world is.\\nBut to Charlotte, these hidden "details" — only visible out of the corners of her eyes — are essential to understanding the world.\\nCharlotte\'s father, a seasoned reporter and professional nature photographer, noticed his daughter\'s interest in and knack for "observation." Thus, on her tenth birthday, he gave her a custom-made Kamera, its dimensions and the positions of its buttons built specially for her.\\n"Not all people are attentive enough to seek out and observe subtle differences, but this, Charlotte, is your unique talent."\\nThose were the words of her father, the "Reporter of the Idylls," Galanopoulo.\\nFrom then on, there was a little junior reporter by the senior reporter\'s side. This father-daughter tag team could be found on streets wide and narrow, forests and rivers alike, raising two Kameras, one large and one small, taking countless still images of moving beauty.\\nEven though their "interviews" always caused the gentle yet strict Mrs. Gagnepetit to nag them incessantly, Charlotte\'s laughter never failed to be the quickest way to make her mother stop. And as for her soiled clothes and dirtied hat, those were left to the ever-capable Mr. Galanopoulo.\\nTo her, the whole world is a giant treasure trove.\\nAnd those pictures, for their part, are her special treasure maps.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'Galanopoulo always emphasized one thing to Charlotte:\\n"A picture of sufficiently great beauty cannot be ignored."\\nWith her consent, he sent the photos they\'d taken to The Steambird. The editors were quickly taken with their photos — especially Charlotte\'s — and profusely praised Galanopoulo\'s ever-improving photography skills, reserving, just as before, prime placement for them in their publication.\\nThose pictures caused quite a stir in the Fontainian photography space when they were published, with critics stumbling over each other to flatter them, and newspaper hobbyists fighting to get copies to make their clipping collections yet more colorful and vivid.\\nBut when both critics or fellow journalists came calling and asked how Galanopoulo advanced his aesthetic sensibilities by leaps and bounds...\\nThe veteran reporter lightly pushed Charlotte forward, saying calmly: "Ah, such pictures are beyond me. It\'s all my daughter\'s handiwork!"\\nThe experienced, learned ladies and gentlemen who had come knocking could not but fall silent first, before expressing surprise, and then beginning to whisper amongst themselves and even venturing a few questions.\\nCharlotte blinked. The bewildered adults before her seemed every bit like little insects searching for shelter in a storm, waving their antennae this way and that, crying "Where are the leaves? Where are the leaves?"\\n"Hey, everyone, look this way!"\\nThe young child\'s cry caused them to collectively leap out of their worn skins, and everyone turned to look, only to be greeted by a custom-made Kamera and the click of a shutter.\\nIn that moment, all of it was captured on film — the furrowed brows, quirked lips, red faces, tangled hair, and waving arms, perfectly encapsulating those panicked bugs in the storm.\\nThe little reporter patted her Kamera and smiled toothily.\\n"I\'ll call this one... \'No, No, That Won\'t Do!\'"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'After Charlotte\'s extraordinary photography skills had made her famous, she began receiving frequent visits from manuscript writers, magazine editors, news clipping collectors, and her father\'s reporter colleagues. Even Euphrasie, the Editor-in-Chief of The Steambird, was amongst them.\\nEuphrasie was straightforward about her intent. She hoped that Charlotte would agree to become a "special correspondent" — someone who would conduct interviews and write articles in addition to taking photographs.\\n...However, her father, despite his usual mild temperament, was strongly against it. He did not wish for his daughter to associate with those kinds of people, either full of ulterior motives or hypocrites.\\n"Nature is fierce, but it is honest. Storms don\'t loose their fury without reason, nor do beasts bare their fangs without cause."\\n"But people lie — they always do. A Kamera can only capture their faces, but the lens cannot target their hearts."\\nHe would respect Charlotte\'s decision, of course, but he preferred that Charlotte live a simpler, happier life, without sinking into the morass of humanity.\\nTo Charlotte, this world was a treasure trove, and pictures her treasure maps.\\nBut for the first time, she came to realize that this trove still harbored undiscovered "truths."\\nThese truths were not themselves treasures, but were more akin to a procession of dark memories. Intentionally hidden, discarded, disguised, and then abandoned, with those having done so wishing that they would never be discovered, and that all events connected to them would simply end right there.\\nCharlotte knew that she could find them. She could dig up these truths, like digging tulip bulbs in a garden, like leading hermit crabs out of their shells, like finding pinecones hidden by squirrels.\\n...But she also felt like a bird glimpsing an onrushing flash flood, a cave rat foreseeing an earthquake, or a fish sensing a coming tsunami.\\nWith great ability comes great responsibility.\\nOne with the talent for uncovering "truth" was also responsible for bringing the "truth" to light.\\nThe only question was, did she have the courage to do so?\\nHer parents responded with silence, for they knew that their daughter had already made her choice. Charlotte was old enough, and all birds are destined to spread their wings and leave the nest someday.\\nThe next morning, Euphrasie went to work as usual, and there, waiting for her at the entrance to The Steambird, she saw Charlotte, ready with her Kamera and notepad.\\n"Welcome to The Steambird, Charlotte."\\nEuphrasie extended a hand.\\n"I believe the next La Verite Prize is yours to win."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'The La Verite Prize, established and funded by The Steambird, is the most prestigious prize a Fontainian reporter can win.\\nOnly the best of the best have ever won it: Hirailles and her tireless reporting on the investigative work of the Maison Gardiennage, the solitary Hobereau and his marine life photography honed over decades living by the sea, and of course, Dieuleveux, famed for his unbending, straight-talking nature, to the point where all threats and criticism simply bounced off his hide, never causing his quill to waver in the slightest.\\nAnd of course, the renowned genius reporter, Charlotte, has long since joined their storied number. In fact, her reporting stands out so far above the rest that she has won the prize several times in a row.\\nCritics have lavished her with praise, lauding her "unequaled sense of composition," "incomparably fresh angles," "unquestionable impartiality," and "unparalleled flair"...\\nDetractors, on the other hand, believe that her successive triumphs are the result of collusion between The Steambird and the prize selection committee. How could such a young and unorthodox reporter be showered with glory, if not so the newspaper employing her could also bask in that glow? And why else would she be so close to the committee members, anyway?\\nEven so, her talents are beyond doubt. As another round of selection for the La Verite prize drew near, all her colleagues believed that she was guaranteed to emerge victorious once again.\\nThey\'d seen how she infiltrated the haunts of criminal rings alone and secretly visited illegal sweatshops... For report after report, Charlotte had braved unspeakable dangers and endured unimaginable hardships to bring the truth to readers... Whether it be in her professional dedication to the profession, her masterful manuscripts, or her attitude toward reporting, Charlotte was worthy of the committee\'s favor.\\nThe question on everyone\'s minds, really — especially those of the sponsors — was "Which one of her reports will she submit to the committee?"\\nIt would, after all, be her ticket to the La Verite Prize, and that would make it a collectors\' item of... considerable value, surely.\\nBut to everyone\'s astonishment, Charlotte unexpectedly declared that her submission would be a brand-new, never-before-published report, one that would reveal some heretofore unrivaled "truth."\\nDear readers, to find out, please subscribe to The Steambird and look out for tomorrow\'s headline!',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: '"Prestige Prize Proved Perniciously Partial — The Real La Verite."\\nThis was the headline on the day the award was to be announced.\\nIn it, Charlotte detailed the various monetary dealings that the long-serving members of the La Verite Award selection committee had engaged in over the previous decade, various inequities in their judgments, and provided an exhaustive list of reporters and reports who had been done dirty in the process.\\nHer report caused an uproar in the Court of Fontaine, with countless reporters surging to the committee offices — Charlotte, of course, among them.\\nAmidst a broadside of shutter clicks, Charlotte unleashed a barrage of meticulously-prepared questions from a thick notebook at the dumbstruck committee members, one after another. Red and shame-faced, the gentlemen flapped their clumsy lips as best they could, only to produce explications akin to porous cheese. In the end, they had to declare the questions out of order and in violation of normal procedure, before fleeing right before the gathered reporters\' eyes.\\nCharlotte\'s "report" had barely begun, though.\\nShe continued publishing articles concerning the La Verite Award in The Steambird, even directing her pen against certain figures in the newspaper itself who had been connected to the La Verite selection committee, laying out the manner in which they had recommended reporters with whom they shared beneficial arrangements for awards, and how those reporters had returned the favors...\\nCharlotte\'s articles swept through the Fontainian media world like a tidal wave, and in response to public outcry, the Maison Gardiennage declared an official inquiry into the Award, suspending its activities and investigating all suspicious awardees.\\nCharlotte, for her part, temporarily lived inside The Steambird\'s offices, with all prospective visitors "wanting a word with her" being turned away by Euphrasie with extreme prejudice. It reached the point where the Maison Gardiennage even dispatched a guard detail to the newspaper\'s office entrance.\\nWith her own hand Charlotte had lifted a huge stone that none had wanted to peek under, and the creepy crawlies that had lurked in its cracks and crevices now had to face the searing sunlight of the "truth."\\nThe Maison Gardiennage\'s investigation concluded three months later. Judges who had given unjust judgment, contestants who had contended to win glory undeserved, and editors who sought to edify themselves all received their just deserts.\\nThe La Verite Award selection committee was also wholly reorganized, now under various forms of new oversight. Once this was complete, the first thing they did was to give Charlotte the now utterly discredited award.\\nOf course, the trophy was but dead dross to her.\\nThe real honor she had received was that the "truth" she had revealed in her report — and the ones that followed in its wake, of course — now shone in the sun.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: '"Monsieur Verite"',
      title2: null,
      text: 'A gift to Charlotte from her father that she carries with her to this day.\\nThough he still didn\'t wish for her to take on such complicated work, her father respected her decision to formally accept the job of being a special correspondent for The Steambird.\\nHe commissioned a friend skilled with machinery and modifying Kameras, and made extensive modifications to that small Kamera.\\nFor example: Making it easier to switch out the film canisters such that Charlotte could swap film with only one hand, or making the photographic compartment water, fire, impact, and explosion-proof, to the point that the Kamera\'s exterior casing could be utterly destroyed, yet the compartment containing the film would remain intact and unharmed...\\nHer father insisted on numerous modifications to which his friend initially opined, "This isn\'t necessary, is it...?" with a bitter smile. Nevertheless, in the end they agreed to make the modifications, including a high-powered loudspeaker that, when activated, unleashed an ear-splitting alarm, as well as a hidden self-defense system on the Kamera\'s side that ejected a concealed knife outward at high speed when the right button was pressed...\\nThey also included "a shutter delay device," a "lens self-coupling setup," and more...\\nAll the concerns and worries of her father were installed into the device along with all manner of contraptions, transforming it into an ever-reliable, unequaled super Kamera that reflected its owner perfectly.\\nAnd when the modifications were finished, Charlotte gave it a new name — "Verite."\\nMeaning, of course, "truth."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Charlotte does not, in fact, really know just when she obtained her Vision.\\nPreviously, she had been penning a new piece about problems in how salvage divers were treated, and had gone to interview Dollander, who employed a great number of said divers. The chubby-faced man did not seem keen on speaking the truth, and indeed was only interested in answering any questions insofar as he might redirect them. The divers he employed, too, proved quite tight-lipped.\\nDespite the serious damage that had been done to their lungs and eardrums, the long work hours exhausting them utterly, the decrepit divesuits they used, and the inedible food, they held their silence in front of Dollander. Their smug boss smiled triumphantly at her lack of progress.\\nBy the next day, Charlotte had procured a divesuit through personal connections and was ready to get close to the divers in secret as they worked, and use her Kamera to capture Dollander\'s ill-treatment of them firsthand. They were in a titanic undersea rift, a place where it was completely forbidden to work according to Fontainian diving regulations.\\nAfter that, Charlotte did not appear at work for a good long while. All the other Steambird reporters saw was a stream of Maison Gardiennage officers coming in and out of the office, with Euphrasie uncharacteristically ruffled, working late into the night every day.\\nSome reporters said that they saw someone dressed in outmoded clothes, drenched and shivering as they squatted at the office entrance.\\nSome said that an undersea earthquake had occurred in the Thalatta Submarine Canyon, where divers employed by some fellow named Dollander had been working, and that they had avoided injury by the skin of their teeth.\\nSome other reporters even said that this Dollander had secretly put out a bounty for a Kamera that was said to contain pictures important to him.\\nStill, Charlotte did not emerge.\\nBut reporters are most certainly not a passive lot. The Steambird\'s reporters began to act quietly and surreptitiously. Some utilized their personal connections to look into Dollander\'s business, while others followed the divers, and others still wrote pieces implicating Dollander...\\nWith The Steambird working at full steam, it was fearsomely quick indeed, and before long an extensive report on Dollander\'s illicit employment practices was complete.\\nHowever, without any photographic evidence to corroborate the article, the reporters felt it was...\\nJust then, the doors to the main entrance were suddenly flung wide open, and in strode Charlotte, clad in rags and sans spectacles and shoes. Placing Monsieur Verite on the table, she grinned.\\n"I have the pictures right here!"\\nNo questions were asked about what she\'d been through. Instead, all worked as one, focusing on slotting each image into the report.\\nThe next day, The Steambird headline was this — "Dollander: Undersea Scrooge," detailing his illegal employment practices, salary deductions, the harm done to the health of his employees, and other vile conduct. As for the article\'s author, it was listed as "The Steambird Reporters."\\nThe night before that edition was to be published, Charlotte was, as always, in the printing room doing some final proofreading work.\\nWhen she finished reading the final word and put the manuscript down, she suddenly noticed that an icy-blue Vision had appeared beside her hand.\\nScrutinizing it, all she could manage was to mumble a few words:\\n"I think we\'ll have to leave out this little detail..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
