export const mikaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Mika, Front-Line Land Surveyor, Knights of Favonius Reconnaissance Company, reporting in. It's an honor to fight alongside you. If there's anything I can do to support you, just let me know and I'll get to it right away. Anyway, I'll make every effort to navigate us safely and report accurate intel on the enemy!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Staying on Target',
      audio: '1101',
      text: "We'd better stay battle ready... Our next mission could start at any time.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Situation Report',
      audio: '1102',
      text: "Verifying our current position, measuring distance to target area... Alright, I've recorded the terrain conditions.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Establishing a Route',
      audio: '1103',
      text: 'No matter what kind of environment you may find yourself in, with thorough reconnaissance, you should be able to establish a safe route.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Ahh, the rain is really coming down... let's just hope the conditions out here won't get too muddy. Otherwise, I'll need to help everyone clean their boots, and there won't be enough time to prepare a meal...",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Thunder can mask the sound of movement, which is why it's our friend.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Freshly fallen snow may be beautiful, but it masks the more nuanced features of terrain, which can be a pain.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "The sun is out and visibility is excellent... Perfect conditions for observation. Couldn't ask for anything better!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "Huh... Could this wind be a sign from the Anemo Archon? Or is it just a result of the terrain's effects on the atmosphere...",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Oh, good morning! ...I prepared the breakfast we usually eat in the expeditionary force. If you don't mind, maybe you could tell me our plan of action for today while you eat.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Oh, please wait a moment, our meal's almost ready! Field ration no.3 — it's the Reconnaissance Company's favorite. I'll check the nearby area again shortly to see if there are any suitable places for a short rest.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Dinner's served! Although it's just some basic field rations, it should still have all the nutrients you need. Please, dig in... If you have any equipment that needs maintenance, you can also give them to me.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "It's getting late, and I need to get the day's survey records in order. The camp beds are ready, so why don't you have a rest? After you've recovered your energy, our midnight snack should also be ready, and we can trade posts.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Mika: Work',
      audio: '2001',
      text: "Hmm? What's a Front-Line Land Surveyor? Well, my duty is to scout ahead into unknown territory, survey the terrain, and identify key locations. Sometimes, we also have to deal with enemy sentries, so in addition to being able to map out the terrain, I also have to stay combat ready, know first aid, and have strong survival skills...",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Mika: Mundane Tasks',
      audio: '2005',
      text: 'Making camp, starting a fire, cooking food, and maintaining equipment... these are all essential tasks that must be done. If the others dislike such duties, and if I can uh, manage them to a satisfactory degree, then the least I can do is to help out... That way, everyone can have a breather and relax a little...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Rumors',
      audio: '2003',
      text: 'Ah, sorry... I heard all about you when I first arrived back in Mondstadt. Super powerful people like you and Paimon usually have some kind of strict personal code. Since many super powerful people would also have a bad temper, I was afraid that if I misspoke, you might get upset. But luckily, you two are really nice, and I have nothing to worry about!',
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Speaking in Code',
      audio: '2002',
      text: 'Some forward scouts will use the word "Octave" to indicate that they\'ve run out of arrows and are returning to camp... Or "Vera" to mean "the conditions are good, we should engage the enemy"... Hey, why don\'t we also come up with some code words? It\'ll come in handy, especially if we\'ll be working together long term. Go ahead, I\'m good with any of your ideas!',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "To be honest, even I was amazed that I managed to receive a Vision. It's really come in handy, but I shouldn't completely rely on its powers. Instead, I prefer to think of it as a sort of safeguard to use in case something happens. As a member of the Knights of Favonius, I should place more importance on team cooperation, and come up with ways to overcome difficulties together with my teammates.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "Here's a simple survey trick that you might find useful... Stretch out your arm, and raise your thumb towards the target area. Align your right eye's line of sight and your thumb to the left side of the target, and your left eye to the right side of the target, and multiply the distance between the two sides by the right multiplier... You can use this trick to estimate the height of a mountain and whether it's climbable, or the width of a river and whether you can swim across.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "I heard Klee mention that there's a type of plant that can relay sound... if only we could somehow carry this plant with us in the field. That way, I could instantly report back about the terrain... I could even stay near the front lines and guide our rear forces to attack enemy targets from afar with volleys of arrows.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Kaeya',
      audio: '4001',
      text: 'Before joining the Knights, I had to take a number of exams. Captain Kaeya was the main person in charge of all the testing. He was really supportive, and gave me all kinds of tips, but sometimes, I would struggle to understand what he was saying... I would get worried that I was not keeping up with his pace, and that I was letting him down...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Varka: Instruction',
      audio: '4002',
      text: 'Grand Master Varka is not only a strong leader who commands respect, but also my personal combat instructor. He taught me to think on my feet and avoid engaging enemies at close combat to make up for my small stature and relative lack of stamina. Following his advice, I learned how to fight with a polearm and crossbow, and I must say, this fighting style is far more suitable to me.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Varka: The Captain',
      audio: '4003',
      text: "The Grand Master said that I need to set higher goals for myself, and strive to achieve them. I've always had that kind of attitude, but it wasn't until I was on the expedition that I realized how serious things can become... One day, I met the Fatui Harbinger known as The Captain. I can't even begin to imagine how I can deal with an opponent like him. I just... Such powerful people are really on a level of their own, I'm not even remotely close...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '23': {
      title: 'About Jean',
      audio: '4004',
      text: "The Deputy... I mean, the Acting Grand Master is a strong and considerate leader who always makes me feel at ease. She's always out there looking after all of us. Whether it's organizing work, rendering first aid, or cooking delicious meals, there's so much I can learn from her...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Amber',
      audio: '4005',
      text: "Oh? Amber the Outrider? She's the most reliable vanguard, and has amazing reconnaissance skills! The roles of Front-Line Surveyors and the Outriders are similar given that we both operate ahead of the main force. Amber has a lot of experience, and I've learned a lot of survival skills from her, as well as how to better maintain my crossbow strings and arrows.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Eula: Tasks',
      audio: '4006',
      text: "Captain Eula is a strong fighter with a combat style of her own, and she's always looked out for me. When I first joined the company, she assigned me a variety of tasks, way more than what other members had, and that quickly improved my ability to adapt. Once I grew accustomed to the way she expresses herself, I was able to work together with her just fine!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Eula: Daily Conduct',
      audio: '4007',
      text: "Actually, I really admire Captain Eula. She is friendly and free-spirited, and her mental fortitude is out of this world. If other people gave me strange looks all the time and talked behind my back like they do about her, I don't think I'd be able to leave my room...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Lisa',
      audio: '4008',
      text: 'Our librarian Lisa had always offered her help when I was first teaching myself how to draw maps. She even found a bunch of useful books for me to study. *sigh* If only I could be as well-learned as she is... After all, it never hurts to have more knowledge, and you never know when you might need it...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Klee',
      audio: '4009',
      text: "Oh? Klee? She's super cheerful, and I've heard that... she's as strong as the Grand Master himself. She's invited me to go on adventures with her before, and we always had a great time together! Although she would experiment with dangerous weapons from time to time, which means I've had to revise my maps on several occasions... But I still feel it's worth it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Venti',
      audio: '4010',
      text: "I really like that bard... He's a very talented performer, and his melodies always seem to make me feel at home. If I had to pick a tune that best represents Mondstadt, it'd definitely be one of his. It's too bad that I'm not often in the city, otherwise, I could bring him some gifts every day...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Albedo',
      audio: '4011',
      text: "The Chief Alchemist has been very kind to me. He helped me make all the survey equipment I use in the field... I even have some pens he made that will work even when I'm hanging upside down from a tree. But it seems that making artistic sketches is quite different from making maps. I've tried to make some sketches of a target area as supplemental intel before, and word has it that Captain Albedo went silent for a long time when he saw them...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Mika: I',
      audio: '5001',
      text: "Hmm? You want to know more about me? Well, I'm just an ordinary person, so I don't really have any interesting stories... I guess all I could talk about is my experiences, would you be willing to hear about that?",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Mika: II',
      audio: '5002',
      text: "Ever since I was a kid, I've wanted to become a cartographer, and map out every corner of Teyvat. It's only later on that I discovered the Knights of Favonius actually have that kind of role. Thanks to my father and brother's support, I was able to make it through the selection process and become a Front-Line Surveyor. This job has let me live out my dreams, and it's already brought me lots of fulfillment.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Mika: III',
      audio: '5003',
      text: "Everyone in the Knights of Favonius is really strong, and I feel like there's something I could learn from each member. After gaining new skills from everyone, I should also do my best to return the favor. So if there's anything the others need help with, then I'll do my best to make that happen.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Mika: IV',
      audio: '5004',
      text: "It seems like... after I assisted the Grand Master and Captain Eula a few times with their errands, some members of our group have begun to see me as their official messenger. If I ever misspoke, it would cause trouble for our leaders, and the blame would be all mine. So, whenever I am around others I'm unfamiliar with, I often try to only comment on things I'm absolutely confident in, which makes everyone think I'm timid. But would you say this whole situation is just a sort of misunderstanding?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Mika: V',
      audio: '5005',
      text: "You know, one good thing after coming back from the expedition is that I don't feel so worried anymore. As long as I'm not causing trouble for anyone else, then I don't really mind what anyone might think of me. The Knights of Favonius is like my second family, and I've got to master my work as a Front-Line Surveyor. My hard work can let everyone finish their tasks more smoothly and end their days with just that much less to worry about...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "Mika's Hobbies",
      audio: '6001',
      text: 'Oh? My hobbies? ...I guess my favorite thing would be camping out in unknown territory. Just taking in the fresh scenery, making a cozy little camp, starting a bonfire and making some food. It really brings me happiness!',
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Mika's Troubles",
      audio: '6002',
      text: "To be honest, I'm not too good at dealing with people I'm not familiar with. Maybe it's because I'm not really good at holding a conversation. Can you give me some pointers in that area?",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6005',
      text: "The Grand Master said that a youngster like me needs to eat more meat, which will build more strength and physical stamina. Even though there's little chance I'll ever get really buff. I do like eating meat dishes. The others in the Reconnaissance Company seem to share this taste as well.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Unlike my brother, I can't stand the taste of alcohol. All it takes is one sip and I'd be out cold, and the others would have to go out of their way to take care of me. Even just the smell of a strong drink being opened is enough to make me dizzy.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Thanks so much... this is such a marvelous dish, I would feel terrible using it just to fill my stomach! Can I put it away for storage?',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'The taste and portions are both incredible. You really went the extra mile for me.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Ugh... well, since you went to the trouble of making this for me. I promise I'll finish it.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: 'Oh, what should we do for an occasion like this? Hmm... Today is your most special day, so we should really live it up! I\'ve prepared "A Tour of Mondstadt\'s Most Stunning Spots." It contains information on lots of beautiful locations that are hardly known to anyone else. I wish you happiness every day until this day arrives again next year.',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Even though I'm still miles behind you, I'm feeling a little more confident now. At least, I won't end up dragging you down again.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I hope I'll be able to provide more useful intelligence, and help take some weight off of your shoulders!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Please allow me to always travel alongside you, and survey the land around us!',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'Thank you so much! With this, I am now so much closer to my goal — allowing everyone to advance safely and navigate through rough terrain without any fear of fatigue or potential danger!',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Providing cover fire.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Engaging.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Final warning.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Precision strike!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'You had your chance!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Neutralizing threats!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Let's keep going, team!",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Leave the wounded to me!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "Now's our chance!",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Deploying Wind Glider: I',
      audio: '800001',
      text: "I'll be the eyes above...",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Scouting ahead has its benefits!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'What do we have here?',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Treasure located. Good work, everyone!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'This is... a tight spot...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Should we reconsider our tactics?',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'The enemy is... quite strong.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Fall back, I'll cover you!",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'You need medical attention...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Should have... tried to flank them...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Fallen: II',
      audio: '500002',
      text: "I'm sorry... everyone...",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'No... I blew it...',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Hang in there!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Light Hit Taken: II',
      audio: '900002',
      text: "I'll be alright!",
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: "I'm fine... really!",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Keep your cool...',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Let me double check our equipment... alright, everything's ready.",
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'My lance and crossbow are prepped and ready.',
      tips: '',
      tasks: null,
    },
    '75': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "I—I'll take point and scout ahead!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Whenever he shows up at the Knights of Favonius headquarters, Mika always swiftly finishes any discussions to be had with his fellow knights, then quietly slips away to avoid becoming a hindrance to others' work.\\nMika always gets nervous when someone strikes up a conversation with him, frantically scampering away right after politely putting an end to the idle chatter.\\nThe knights know that the young man's name is Mika, and that he is Huffman's younger brother and the second son of the Schmidt family. They also know that he is a member of the Reconnaissance Company, but nothing much beyond that.\\nFew are aware of what Mika's job entails, nor do they know that the widely-promoted, updated version of their military map is the fruit of his labors.\\nThe new map consists of detailed statistical data regarding almost every corner of Mondstadt with practical markers indicating road conditions, areas with heightened monster activity, high ground that can serve as temporary strongholds, and the distribution of natural resources... The amount of detail could almost make your head spin.\\nAll of this is the result of Mika's own labor throughout the two years he has spent traveling all across Mondstadt and investigating every inch of terrain he set foot on.\\nKnights who have fought alongside Mika know that he finds using both lance and crossbow at the same time the most convenient, and his unique fighting style has left a lasting impression.\\nHowever, they have also been solemnly \"warned\" by Mika to never speak of him to others unless absolutely necessary.\\n\"Mika's terrified of drawing the attention of others — he'll get nervous if you so much as stare at him, to say nothing of showering him with compliments. He's been a great asset to the Knights and helped us out a lot, so respecting his boundaries is the least we can do as seniors!\"",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Mika comes from a loving family. His mother works as an author writing about local conditions, his father is a retired Knight of Favonius, and his older brother Huffman is a current member in the Knights' ranks.\\nWhen Mika began learning to read, his mother went inspiration-gathering abroad with his father accompanying her. During that time, the responsibility of looking after little Mika landed in Huffman's hands.\\nHowever, Huffman had already made the Knights of Favonius his second home — he was preoccupied with work during the day and indulged in drinking with his friends night after night. With his own life lacking organization, how was he expected to take care of his little brother?\\nSo it was little Mika who learned to take care of both himself and his brother whenever he'd return home drunk at night. When other children his age were enjoying their childhood without a care, Mika had already learned to stick to an organized schedule, sometimes even helping Huffman with his everyday chores.\\nWhile they were away, Mika's parents always made sure to send a letter back to Mondstadt every week to keep their children from worrying. Mika's mother, being an excellent writer, could somehow describe the scenery she's seen in a mesmerizing way akin to fairytales. Mika loved to read his parents' letters before looking for their exact location and marking out their travel route on a map. Picturing his parents' wonderful adventures was Mika's favorite pastime.\\nBefore long, Mika developed a passion for reading maps, and even committed the terrain of many locations to memory.\\nUnfortunately, Huffman had to ruin the mood when he broke the bad news to Mika: \"I'm afraid your efforts have been wasted on the map Mom and Dad left us. It's very outdated, and it wasn't very accurately drawn in the first place.\" But that was to be expected. After all, those who with the ability freely explore the wilderness would likely have all become adventurers with nothing but commissions and Mora on their minds. To them, just about any map would do.\\nOn the other hand, most of those who knew how to draw decent maps were not skilled in combat, so it would be much too dangerous for them to survey the wilderness themselves. Not to mention their limited income, which wouldn't allow them to afford bodyguards. Perhaps the time would come when the Knights of Favonius finally had sufficient budget to hire experts to deal with matters like these, but with Mondstadt as peaceful as one could hope for, no one knew for sure when something as trivial as cartography could be put on the schedule. So little Mika thought to himself: If he could reach every corner of the world just like his parents, and record every detail of the terrain beneath his feet... That would be the most fun ever.\\nFrom then on, Mika set a clear goal for himself.\\n\"I'll become Mondstadt's expert cartographer.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'When Mika\'s parents returned to Mondstadt, they were delighted to hear of Mika\'s new-found goal and promised to do whatever they could to support him.\\nFrom that day on, Mika dedicated most of his time to poring over geography books and assiduously honing his drawing skills in the library.\\nLisa took a liking to this polite, gifted yet hardworking child and often recommended books to him, guiding him towards the most efficient path.\\nAfter some time, Mika gained Lisa\'s recognition — "With your current skills and abilities, you just might qualify for studying at the Akademiya."\\nIt was then that Mika began looking for opportunities to put his knowledge to the test. As it happens, Ella Musk, whom he had gotten acquainted with while studying at the library, happened to be looking for a guide for a language exchange trip to the secluded wilderness.\\nAnd that became Mika\'s first real expedition. Though they did safely arrive at their destination, due to an error in Ella Musk\'s word choice, the pair ended up getting beaten by the hilichurls.\\nMika concluded that this setback was due to his lack of combat prowess. "I need to learn how to protect myself," he thought, "or I won\'t be able to guarantee the success of my expeditions to unfamiliar areas."\\nThereafter, Mika rode the momentum from his time spent learning in the library and began to learn fighting techniques from his brother. Luckily, Mika had a strong constitution and quickly grasped the basics.\\nIt happened that the Knights of Favonius had just drafted their plan for an expedition set to depart three years later. They were still looking to recruit a few more members to fill some positions, and "Front-Line Surveyor" was among the open spots.\\nThis role had strict prerequisites: those applying for the position should have some level of expertise in cartography, and due to potentially dangerous conditions, they would be leading the team from the front lines, making combat skills a must.\\nThis was Mika\'s chance, but it all felt too much like a dream...\\nMika initially believed that he would be invited into the team as an external consultant, but the position of Front-Line Surveyor would no doubt make him a full-fledged member of the expedition — and one crucial to the entire team. He was daunted by the thought at first, afraid that he wasn\'t worthy of such an important role that according to him, "only the strongest would qualify for."\\nHis doubts were soon dispelled by his father and brother\'s encouragement, and he remembers their words to this day:\\n"You don\'t have to ask too much of yourself. Doing your best to help will be more than enough."\\n"Most of the knights are just ordinary people like us, but once we put our strengths together as a team, even the strongest of adventurers would struggle to prove our equal."\\nThus, Mika seized the opportunity and signed up for the position.\\nHe felt reassured that he would, at least, be dedicating his time to what he loved.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Word of Mika signing up for the expedition spread like wildfire throughout the Knights of Favonius.\\n\"Huffman's little brother will be joining us! The little kid who always takes care of that drunkard will be joining the Knights!\"\\nThe anxiety from unexpectedly becoming the center of attention made his breaths quicken as his heart pounded — Mika was afraid of failing the Knights' assessment and disgracing his father, ruining his brother's career, or worse, ruining the reputation of his family name.\\nConsidering that many members of the Schmidt family had already joined their ranks, the Knights of Favonius decided to raise the bar for entry and make the whole assessment process public in order to make the selection as fair as possible.\\nTaking real-life scenarios into consideration, lead examiner Kaeya came up with a series of challenges that strictly assessed the participants' abilities:\\nHiking up Dragonspine while wearing full armor and carrying a heavy load;\\nMapping out a monster-infested region without the aid of any reference material...\\nLuckily, Mika came well-prepared and gave it his all, eventually passing the most difficult challenge and becoming one of three successful candidates.\\nThe other two candidates had both received Mika's aid along the way as well — to him, they were more like future teammates than competitors, in any case.\\nMika's excellent exhibition of teamwork gained the recognition of Grand Master Varka, who allocated the two other new recruits to the Cavalry Company and Investigation Team, while personally taking Mika in to go with him on his expedition.\\nEvery week, Varka would teach Mika combat techniques and give him assorted \"homework\" to complete.\\nMika would later join the Reconnaissance Company. Communicating with its rather unusual Captain further strengthened his communication skills, which would help him greatly when working with the elite knights of the expedition team.\\nAfter joining the Knights, Mika honed his cartography skills while investigating dangerous locations as a Front-Line Surveyor while receiving pointers on how he might improve his other skills from Varka.\\nThe diligent young recruit quickly became a calm and reliable knight — though it seems as though he has yet to realize that himself.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "As Mika continuously refined his skills in real-life combat, he became a core member of the Reconnaissance Company in less than two years, completing countless missions alongside his teammates.\\nThe scheduled date drew near, and the expedition team was soon about to depart.\\nAt the send-off party, Grand Master Varka was pleasantly surprised by the shiny new Vision on Mika's right wrist. But after personally inviting Mika to spar, he concluded that Mika's current abilities were \"remarkable, but far from enough.\"\\nMika didn't figure out what that meant until the expedition team entered a dangerous restricted area, where he finally saw with his own eyes the monsters Grand Master Varka had used as a reference when judging his powers.\\nThose unnamable, wandering creatures could become a nightmare for any knight unfortunate enough to stray away from the team.\\nThe speed of their scouts in the vanguard determined how fast the whole expedition team proceeded, so during the days when the team was the busiest, Mika could only rest for half an hour a day.\\nIt was Mika's first time working under such high pressure, and he did so with great difficulty. Not to mention that apart from dangers of the unknown, the expedition team was under the watchful gaze of another party...\\nOne day, when Mika was getting ready to call it a night, he received a warning from another scout that the Knights had encountered enemies.\\nWhen Mika hurried on scene, Varka had already drawn up battle lines with his trusty subordinates.\\nIn the depths of the pitch-dark night, Mika could vaguely make out a line of soldiers, silently standing there as if they were lifeless war machines.\\nAnd right in the middle of the enemy formation was a dark, distinct silhouette. Even though torches lit the area, Mika could see nothing but their eerily dark blue eyes that seemed to glow with an uncanny aura.\\nAt his teammate's reminder, Mika learned of their identity — the Fatui Harbinger known as \"The Captain\" and his direct, elite subordinates.\\nAs it turned out, their vanguard had bumped into Fatui scouts and an altercation had ensued, resulting in both sides getting jumpy and continuously requesting reinforcements, eventually alerting their respective commanders.\\nThe scent of gunpowder was thick in the air, the sense of crisis turned Mika's limbs numb and cold.\\nHe couldn't help visualizing the confrontation escalating into an armed conflict, and what he should do if such a thing were to happen...\\nThe Harbinger, in particular — Mika knew that he would be utterly helpless to parry a single half-hearted swipe from this person.\\nHis jumbled thoughts and exhaustion made it difficult to breathe or focus.\\nVarka, however, seemed completely unfazed. He greeted the Harbinger from afar and walked towards him with his weapon in hand. The Captain, too, signaled his men to stand by as he began slowly stepping forward.\\nAs the tension between the two parties reached its peak, Varka and The Captain briefly conversed and seemed to reach an agreement.\\nThe dark silhouette raised his arm, and the ghostly shadows of the Fatui soldiers silently turned and departed with him.\\nThe Knights all heaved a sigh of relief, and some were even trembling with fear. But when Varka returned to the Knights' formation, he looked as relaxed as ever.\\n\"Well, that was a surprise! If it weren't for our unique circumstances, I would've loved to invite him for a duel!\"\\n\"And it's not like he's a stubborn fellow. He's well aware that engaging in battle in a strange and foreign land would've been disadvantageous for both of us.\"\\nIt was only then that Mika realized they had been on the precipice of war, and conflict had been avoided only because the Grand Master had been there to prevent it.\\nThe Captain's overpowering presence and the calmness with which Grand Master Varka handled the crisis both left a profound impression in Mika's mind.\\nMika reflected on this experience for a long time and concluded that although he had been improving in strength, he still had a long way to go when it came to dealing with situations like that.\\nThere was more to be done than just doing his best to help the team. He had to work harder to become a reliable Knight who could handle all manner of incidents...",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Fortunately, Mika would not run into anything exceedingly dangerous during the expedition and smoothly made it past that most difficult period.\\nDuring Mondstadt's Weinlesefest, Mika returned to Mondstadt with Grand Master Varka's letter and resumed his post in the Reconnaissance Company.\\nThe members of the Reconnaissance Company were both excited at his return and surprised at the astonishing progress he had made — for he could now easily complete tasks that usually required three forward scouts.\\nAnd considering that the Grand Master's letter had vaguely mentioned the Fatui, and that Mika had been a key member on the expedition under Varka's direct command... His teammates quickly connected the dots and a strange chain of logic emerged:\\n\"Mika fought against the Fatui! Mika might've fought against Fatui elites! Mika must've fought alongside the Grand Master and won a battle against a Fatui Harbinger!\"\\n\"How else could he have become this strong all of a sudden? Mika's our hero! He can now do anything for us!\"\\nTruth be told, Mika had simply accrued a great deal of experience — the other Knights who had gone had also made progress to varying extents. They simply had yet to return, and thus no valid comparison could be made.\\nMika didn't know how to deal with all the absurd rumors, and so he consulted Jean and Kaeya for advice.\\nJean informed the leader of each company to remain rational and refrain from spreading rumors based purely on speculation. Besides, many matters regarding the expedition were considered highly confidential and should be treated with discretion.\\nKaeya, on the other hand, seemed to enjoy joking about the rumors. Members of the Knights of Favonius all more or less held some sort of dislike for the Fatui, and a rumor that says \"Mika gave the Fatui a good beating\" could very well boost morale.\\nWhatever the case, Mika felt greatly reassured now that the Acting Grand Master had been made aware of the situation and was comforted to know that he hadn't caused any trouble for anyone.\\nHe reported to duty as usual and made sure he did all he could to help others.\\nBut the exaggerated rumors couldn't be un-spread, and Mika has found that gaining too much trust comes with its own fair share of difficulties...\\nRecently, more Knights have been coming up to him to borrow a new map, ask for help maintaining a weapon, or request a share of the Reconnaissance Company's field rations.\\nAll of them seem to hope that some of his powers might rub off on them so that they can become stronger quickly, just like him.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Multipurpose Front-Line Surveying Device',
      title2: null,
      text: "An intricate book-shaped device Mika carries with him wherever he goes.\\nIt was developed by Mika and technicians from the Investigation Team, and its key components were made using Albedo's latest alchemical creations.\\nA notebook is embedded in the device's interior that can be used to record information. Designed to facilitate the quick production and use of maps, each of its pages can be conveniently removed and replaced.\\nAn elaborate pattern is carved on to the back panel of the device. Channeling elemental power into the carving will activate the prism-shaped component outside said panel, which will in turn fire a \"wavebeam\" towards a fan-shaped target region.\\nThe distance between the device and the target region can then be accurately calculated using the time taken for the beam to bounce back. By increasing both the frequency and amplitude of the beam, the device will generate a sketch of a small area of terrain.\\nThis function can greatly improve the accuracy of a map, but regrettably, everything else — including the statistical information and calculations regarding the terrain in question — has to be computed in the user's mind.\\nOnly those with excellent spatial reasoning skills and an extensive knowledge of the target terrain are capable of making full use of this function.\\nThus, Mika became the only Front-Line Surveyor who could use the device without difficulty, and its overall usage rate is not very high.\\nThere had been other improved devices originally planned for distribution to other teams, but they have been put into storage, to be used as spare parts for Mika's device.\\nThe device is Mika's trustiest helper in his work and a symbol of honor for being the best surveyor, but Mika has never once mentioned its impressive features to others.\\nTo Mika, that feels too much like bragging, not to mention that it could potentially give Albedo extra work... Troubling others is the last thing Mika ever wants, after all.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Mika was once in a life-or-death situation.\\nThis was not long after he joined the Reconnaissance Company — the information on a certain area was no longer valid, and Mika had taken up the task to update the details of its terrain on his own.\\nHe slowly crept into the ruins, only to accidentally knock off a piece of stone from the broken wall, alerting two Abyss Mages lurking in the dark.\\nAs the flames intertwined, a rush of elemental power instantly engulfed him as if it was about to crush him into pieces and turn him into the monsters' next meal.\\nPain and panic flooded his senses, and only one thought remained in his consciousness — he needed to escape and warn others.\\n\"These monsters... They'd be a threat to even the most experienced members in the company...!\"\\nIt was the responsibility of a front-line land surveyor to keep their teammates from dangerous situations like this.\\nThe Abyss Mages shrieked in glee and were about to command other monsters to come out of hiding when a spinning spear tore the curtain of flames apart. An icy mist burst across the ruins, clearing the unbearable heat in an instant.\\nWhen the Abyss Mages finally made sense of the situation, Mika had already fled far away, though still apologizing loudly enough for the monsters to hear:\\n\"I'm sorry! I'll remember to knock before entering next time. That way, my seniors can fight you fair and square!\"\\n\"Next time\" soon came — the Reconnaissance Company's main force were notified of the monsters and swiftly but cautiously eliminated the threat.\\nThey were surprised to find that both of the Abyss Mages' Elemental Wards had already become quite badly battered, and gazing upon the radiant glow from the Vision on Mika's right wrist, they seemed to realize something...\\nThat day, the Reconnaissance Company's dinner was especially sumptuous. Everyone raised their glass to celebrate, while Mika himself seemed to be in shock, unable to wrap his head around what was happening.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
