export const rosariaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Listen disciple, if you've got a problem you can't handle, then I'm the one for the job. But if you're looking for prayer, you'd better find some other Sister\\n...Huh? You're not a disciple?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Boredom',
      audio: '1101',
      text: "Don't we have a job to do?",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Overtime',
      audio: '1102',
      text: 'Everything is negotiable, except overtime.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Life in Mondstadt',
      audio: '1103',
      text: "Work hard and live each day to the fullest. That is what life in Mondstadt is all about, isn't it?",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'This will slow things down.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: '...What a nuisance.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'We should keep moving, but watch your step in the snow.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: "Blessings from the Anemo Archon Barsibato? Wait... no, it's Bartobas...?",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "*yawn* Good morning... I've missed morning mass, haven't I? Ugh, it starts too early anyway.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "I'd say I sleep even better in the afternoon sun. You should try it sometime.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. Don't expect to see me at prayer tonight... And don't ask why.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Go ahead, take a break. I'll handle things here.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Rosaria: Sister',
      audio: '2001',
      text: "Me? I'm just another ordinary person. Church, work... I just do what I have to do.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Rosaria: Troubles',
      audio: '2002',
      text: "Each of the Sisters is worse than the next. If it's not about prayer, then it's about choir or some other thing I'm supposed to participate in... I'm trying to stay out of sight, so don't you dare tell them you saw me here.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Beliefs',
      audio: '2003',
      text: "Perhaps a god has the power to protect everyone if they would choose to do so, but that would never happen. Otherwise, people's suffering couldn't ever be taken seriously.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Prayer',
      audio: '2004',
      text: 'Pray. Not for the gods, nor the betterment of others... but for yourself.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Battle',
      audio: '2005',
      text: "Don't overdo it. Let me take care of the dirty work.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "A Vision... Could be proof of strength, or a medal for having survived... who knows? There're two sides to every coin. I won't limit my Vision with ceremonies and definitions. It witnesses me, and I witness it, that's all.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "You don't always know why good things happen, or why we should be happy about them. Heh... But if you ever face a problem too big to handle, don't give up hope. You never know, someone may be there to help, even if you can't see them.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'I take no interest in plant life and the sort, but the dandelion is an exception. How such a simple flower could turn into such a delectable wine is beyond me. A glass of dandelion wine after work is even better than sleeping in on Sunday.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Diluc',
      audio: '4001',
      text: "Isn't it obvious? There's more than meets the eye to that rich tycoon. He's confident, yet discreet... and even a little bit dangerous.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Kaeya',
      audio: '4002',
      text: "Wine has its uses... like revealing someone's true colors, for example. Smooth talk is Kaeya's veil, but being me, I can see right through it. Hah, you should see him when he's drunk.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Venti',
      audio: '4003',
      text: "There's something extremely interesting about this bard... I can't quite put my finger on it. There's something that makes him different from the others in Mondstadt.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Barbara',
      audio: '4004',
      text: "Barbara is like a thorn in my side, always nagging me about mass and choir practice. I wouldn't be surprised if Sister Victoria specifically asked her to keep an eye on me.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Jean',
      audio: '4005',
      text: "She's not only competent in her own work but also somehow manages to clear up various matters for others... Huh. Now that's a woman who deserves admiration.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Albedo',
      audio: '4006',
      text: "He's like an oil painting you find hanging on the wall in some ancient hall, profound and mysterious... hard to see through. But what can I say, I find people with stories... interesting.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Lisa',
      audio: '4007',
      text: 'Although I deplore those who play truant on a job, I respect her punctuality when it comes to closing up for the day.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Klee',
      audio: '4008',
      text: 'Trouble, and lots of it. Although, it is sort of a cute kind of trouble...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Varka',
      audio: '4009',
      text: "I'm sure Varka means well, but his long-winded conversations get real old real quick. Although, he does really care for those around him, doesn't he?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Her Father',
      audio: '4010',
      text: "Father? I'm not familiar with the word. You could say that I don't have one — could also say I have many, too. What's it to you?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Dahlia',
      audio: '4011',
      text: "I like that he's in the habit of always offering to pick up the tab. In fact, his tavern etiquette in general is very good: He knows which questions he can ask and which ones to avoid. But since we figured each other out, I don't need to be too guarded around him anymore. It's so much easier to get along with people when they're smart like him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Rosaria: I',
      audio: '5001',
      text: "Let's forgo the formalities. I'm here to finish a job. Just leave the dirty work to me.",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About Rosaria: II',
      audio: '5002',
      text: "What's weird about a Sister without reverence for the gods? There are hunters who don't eat pork, and fisherman who don't eat fish, aren't there? Just because you do something doesn't mean you love to do it. That's how every job goes.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About Rosaria: III',
      audio: '5003',
      text: "This year's Dandelion Wine is sinfully good. Care for a glass?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About Rosaria: IV',
      audio: '5004',
      text: "Mondstadt is a beast of light, both old and young. Old in the sense that it constantly requires someone's protection, yet too young to ever survive on its own. That's why there's people like me. I care for Mondstadt just as the other Sisters care for the believers, we are all guiding that which we love onward on the path towards freedom. Huh? Why do I call it a beast of light? Because people like myself can only be found in the dark...",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About Rosaria: V',
      audio: '5005',
      text: "I sometimes feel that my former selves from years past still exist alongside me, urging me on. I'm sure you know the feeling, too. Even if you decide to venture down a new path, don't just abandon the former you. For that is the foundation upon which you now take footing. Do not fear your past, and do not be scared to come to grips with it.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "Rosaria's Hobbies",
      audio: '6001',
      text: 'There are some troubles that only a stiff drink can take away. That being said, I never get drunk.',
      tips: '',
      tasks: null,
    },
    '37': {
      title: "Rosaria's Troubles",
      audio: '6002',
      text: "Ugh, definitely skipping next month's choir concert, but I bet Sister Victoria will be personally taking roll... What a nuisance.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Have you ever tried Beef Bourguignon? Big chunks of meat with the smooth taste of alcohol... Mmm, it's delectable.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "You mean I'm supposed to dip this hash brown in jam? Ugh, this is sacrilege!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'It seems that our tastes are aligned when it comes to food.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "At least I'll be able to eat my fill with this.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Do you really like this food?',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "Today's your birthday, so if you have any dirty work that needs taking care of, I can give you a hand... Just don't tell anybody, got it?",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Hmm, just what I needed.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "You have a job for me? I've got time.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Good. Getting stronger means finishing jobs quicker.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I'm no stranger to spilling blood, but never have I possessed such power before. For such blessings, I give you thanks.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Hyah!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Judgment!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: "You can't run!",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Punishment!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Shiver!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Lights out...',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: '...Hm, there are a few interesting trinkets here.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "I suppose it wasn't too much trouble.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'That felt... pretty good.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Hmph. Things are getting interesting...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Looks like overtime today.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'So you know your stuff, huh?',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Let me handle this!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Don't try to be a hero!",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'At least... no more... work.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: II',
      audio: '500002',
      text: "Maybe this is just... fate's dark design.",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Is this... my final job?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'I see how it is.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ugh, what a nuisance!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I hear you've got a job for me.",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Make sure to keep up.',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Sooner we're done, the better.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Rosaria is one of the sisters of Mondstadt's Church of Favonius.\\nThough she is just as much a woman of the cloth as the likes of Barbara and Jilliana, people tend to make a mental distinction between Rosaria and other members of the clergy.\\nWhile she might dress the part — at least, to a certain extent — her speech and actions do not reflect her office in the slightest.\\nFurthermore, she displays even less reverence towards the gods than the ordinary citizens, and she routinely skips her various church engagements.\\nShe comes, goes, and acts in solitude, and if she were ever to make an appearance in the Cathedral, it would be to smoke in the rearmost pew.\\nSuch a lone wolf is Rosaria that perhaps she should be considered a clergywoman in name only.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'If Rosaria has been lectured once, she has been lectured a thousand times before concerning her unorthodox behavior.\\nFor some reason, however, she has never faced any serious consequences for her transgressions. She does not work together with her church colleagues and only rarely shows up to celebratory events in the city.\\nThe strange and mysterious Rosaria moves about almost like a wisp of black smoke — blink, and you\'ll miss her as she disappears into thin air.\\nHer social interactions are never more than superficial, and the rest of the time she keeps herself to herself.\\nHowever, Sister Victoria would say that the ever good-natured Barbara is one person who has always made the effort to get close to Rosaria.\\n"Please don\'t smoke in the Cathedral..." "Could you try to attend the ceremony on time next time...?"\\n"And... Hey, come back, I\'m still talking to you!"\\nBarbara is forever anxiously chasing after Rosaria, urging her to complete her various daily tasks.\\nYet even when faced with Barbara, the beloved idol of Mondstadt, Rosaria remains completely unmoved.\\nSurely her heart can\'t be completely made of stone?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'Rosaria\'s movements are unpredictable. She often leaves without notifying anyone and can be gone for up to several days on end.\\nDuring these times, none of her church colleagues know where to find her.\\nOne of the sisters who took it upon herself to observe Rosaria once groused that "even a stray cat should at least give you notice before running off..."\\nRosaria uses these disappearances to do work that only she can do in corners unseen by others.\\nAn unfamiliar merchant, a suspicious traveler — are these people threats to Mondstadt?\\nShe investigates, shadows, and if necessary, interrogates.\\nIf they must disappear, then Rosaria shall be the last person they meet.\\nSuch dark work, which cannot see the light of day, is to be done by her hand alone.\\nShe always sets out after the sun has set, finishing her work in one fell swoop. Sometimes, if she makes it back by the crack of dawn, she gets to usher in the day ahead with a glass of breakfast wine.\\nThe people of Mondstadt live in the golden sunlight, but Rosaria dwells under the silver moonlight.\\nIt is a cold, piercing light... just like that of the ice she forms with her Cryo abilities.\\n"There are some things that young people need not know," Rosaria thinks.\\nThough, in her eyes, "young people" means all citizens of Mondstadt who live in the light of the sun, regardless of their age.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Like a puff of smoke, the lackadaisical Rosaria is impossible to pin down.\\nNevertheless, once she takes on a job, she can be relied on to handle it with the utmost professionalism.\\n"Lazy" is the last word that anyone would use to describe her ruthless interrogations of suspicious individuals.\\nShe also possesses exceptional strength and knows the weaknesses of the human body like the back of her hand — and has no reservations about using this knowledge to kill.\\nPeople know her as the lazy, chain-smoking sister, but behind the scenes, she is a formidable purveyor of justice.\\nA strange fate for one who ostensibly basks in the light of the gods.\\nWhat led her to become a blood-soaked slayer? Why does she stay silent while others praise the gods for their protection?\\nPerhaps it should come as no surprise that Rosaria was not born and bred in Mondstadt.\\n"A city that is fortunate enough to be boring always needs someone to do the dirty work..."\\nRosaria stubs her cigarette out as she speaks in her characteristically languid manner.\\n"And as far as I\'m concerned, the things I deal with are far simpler than living the life of a traditional sister."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Rosaria may not be one to attend prayer meetings, but that does not mean she doesn't have her own theological viewpoints.\\nIn her view, freedom is the spiritual pillar of Mondstadt's people, and it is the very thing that caused her to end up here in the first place.\\nRosaria was born in a remote mountain village, but was taken from her home shortly after birth by the very same bandits who drenched it in blood.\\nRaised by those crooks, she learned how to fight, sometimes thieving, other times doing odd jobs for the crew.\\nShe was their servant, but also their tool, a crook, yet still a child.\\nShe fought against outsiders and her comrades alike, and growing up was a constant battle for survival against the hunger and cold.\\nRosaria's youth was just like Mondstadt's sunset — blood-red from horizon to horizon, and so fleeting that night had fallen before she'd had the chance to stop and take in the view.\\nUltimately, the bandit crew was wiped out by the Knights of Favonius. As their youngest member, Rosaria was judged to have a chance of rehabilitation.\\nGrand Master Varka brought her to Mondstadt. Sincerely hoping that she might someday fit in here, he advised her:\\n\"Go to the Cathedral and be cleansed by the light of our archon. You still have the chance to turn your fate around and live a normal life.\"\\nBut Varka had not counted on Rosaria constantly skipping classes and dodging hymnal.\\nShe would rather hunt in the wild than settle into a life of dutiful service as a sister. As far as she was concerned, the golden sunlight was not so much cleansing as blinding.\\nFor Rosaria had long since come to understand that she was a child of the moonlight, and it was inevitable that she would someday return to the embrace of darkness.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Rosaria, the Church\'s number one truant, became infamous for her absence very early on.\\n"Miss Rosaria, please, show a little more circumspection in your actions! You are a member of the Church. How is it appropriate that you simply never turn up for hymn practice?"\\n"Please calm down, Sister Ophila. Miss Rosaria, I\'m told that you have never attended a single one of your compulsory classes. Is that so?"\\n"Yes."\\n"Mother Maria, please look at this... Rosaria\'s theological essay is an utter mess!"\\n"Miss Rosaria, if I may ask frankly... do you intend to do any work at all here at the Church?"\\n"No. I\'ve already found other work."\\nRosaria never showed so much as a hint of anxiety in any of these exchanges. What\'s more, it was true — she had indeed found other work for herself, and much darker work at that.\\nThe unexpected twist was that she would ultimately end up doing this work under the aegis of the Church.\\nRosaria the novice did not leave the clergy, but instead became Sister Rosaria without much incident.\\nNevertheless, when she\'s not on a mission, she does everything she can to avoid attending church activities, instead heading to the taverns to drink or scaling the city walls to view the scenery.\\nAnd when she simply cannot escape a church engagement, you can be sure that she will be the first to leave.\\nThe instant the workday is done, Rosaria vanishes.\\nWhether by bright day or dark night, there is one principle that she will never transgress: no overtime.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Church-Issue Journal',
      title2: null,
      text: 'A journal with a white cover. The words "Church of Favonius" are inscribed on the cover.\\nThe handwriting is beautiful, but the content is the most of the most banal variety imaginable.\\n"Dandelion Wine — now eighty percent off!"\\n"Fisherman\'s Toast — an incredible flavor at an unbelievable price!"\\n"Crazy discounts on Wheat — ask at the counter and we\'ll grind it into Flour for you."\\n"Buy three Tomatoes and get one free!"\\n"Fresh Small Lamp Grass! Use it to light up your bathroom! Come on, Sir, have a look!"\\nThere is something incongruous about a random assortment of marketplace cries and advertising slogans having been penned by such a graceful and elegant hand.\\nThis journal is a relic from Rosaria\'s novice days.\\nClearly, she must have skipped class and headed to the rooftops on the merchant street, bathing in the sun, listening to the eclectic cries of the street vendors, and committing them to paper.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Rosaria's Vision came to her on a particularly frigid night.\\nThings were getting desperate for the bandit gang — people were starving and the food supplies were dwindling.\\nNever able to eat her fill, Rosaria was driven by hunger to flee into the freezing wind rather than continue another second with the hard labor she was forced to endure.\\nOne of the elders of the gang pursued her and brought her back.\\nHe was the very person who had taken her from the village of her birth, and the one who had taught her how to kill.\\n\"Fleeing makes you a traitor, and traitors can only earn their freedom through victory in combat.\"\\nThe old bandit tossed Rosaria an old dagger.\\n\"Well, come on then! Kill me, and you can leave this place. I'm long in the tooth now, while you've got youth on your side. You can do this, can't ya?\"\\nNo one thought that she would be able to kill him — and yet, the old lion would indeed fall by the newborn cub's claws.\\nThus did the bandits lose an old member and welcome a new one that very night.\\nThe bandits were reluctant to accept Rosaria at first since she had slain one of their own, but they quickly had a change of heart after seeing the Vision in her hand.\\nSurely, a Vision wielder had to be far stronger than some old coot who was about to kick the bucket right? And she ate less, to boot... They could save some food this way.\\nMeanwhile, a question crept into Rosaria's frozen heart:\\nDid he let me replace him on purpose? ...Could a false father have harbored genuine affection for a child he stole so arbitrarily?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
