export const shenheVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'My name is ___. I was born fated to bear the curse of calamity, so I am prone to bring harm to the people around me. The adepti urged me to bind my soul with red ropes to keep my homicidal nature at bay. If you are able to walk alongside me without fear... Hah, very well. Now, give me your hand.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Home',
      audio: '1101',
      text: 'The assumption that every person has somewhere to call home is naive. I got used to living in the mountains alongside the birds and beasts a long time ago.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Motto',
      audio: '1102',
      text: 'Mind be purged, world be saved.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: A Blind Polearm',
      audio: '1103',
      text: "My polearm doesn't distinguish friend from foe, and there is clearly a limit to the red ropes' power. That's why I loathe crowded areas.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'In the mortal world, at times like these, is it not customary to... use an umbrella?',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: '1202',
      text: "The sky is clearing up, and so is my mood. I just hope no one shows up to bother me... If they do, I'll just make them disappear.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When Thunder Strikes',
      audio: '1203',
      text: 'In this weather, I can freeze monsters in place and simply let the lightning bolts take care of the rest. A good way to not get my clothes dirty.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: 'Yes... This reminds me of Master. She loves to ride the swift winds of Qingyun Peak.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning. The dew is very sweet today, would you like some?',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "If you feel fatigued after lunch, you should try meditating. It's very effective.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Do you prefer the artificial light of the cities and towns, or the moonlight in the mountains?',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Feel free to rest. I'm a light sleeper, if I hear anything in the vicinity, I'll investigate it for you.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '12': {
      title: 'About ___: Instinct',
      audio: '2001',
      text: "For all the training I've had — honing my body and mind, learning the adepti arts — I've mostly been guided by my own instincts. It just comes down to self-preservation. I'm not trying to save the world, so if I wipe out some evil presence and it happens to benefit you, don't thank me. It's just a force of habit.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Different',
      audio: '2005',
      text: 'If I treat people kindly, they call me an adeptus, and if I put them in their place, they call me a witch. Heh... The one thing you\'ll never hear them call me is "human." They all seem to agree that I\'m fundamentally... different from them.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Manners',
      audio: '2003',
      text: "I rarely leave the mountains, so I was never taught proper manners. When a conflict arises, I just take care of it the way that comes naturally to me. But if you don't approve of my methods, please do let me know. Even if I don't fully understand your reasoning, I will always defer to you.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Red Ropes',
      audio: '2002',
      text: 'My master gave me these red ropes in order to restrain my impulses. But during our journey together, I feel I have finally grasped the key to all of this. Somehow, controlling my strength — knowing when to restrain myself, and when to unleash — it comes more naturally to me now. I think that what saves me from myself is not my red ropes... but you. If you understand what that means to me, please stay by my side.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: 'So this shiny gemstone is called a "Vision"? Heh... the gifts that fate brings, fate can just easily take away. If one day my connection to this Vision comes to an end, that\'ll be it, and the light inside of it will go out.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "Driving evil spirits away comes easily to me. Getting rid of my inner demons, however... Unless you can find a way to let go, all the adepti arts and exorcism techniques in the world can't save you.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'Why do I always hear people say, "The first snow of the season is a sight for sore eyes"? We have snow every single day in the mountains. So which instance counts as the "first snow"? I don\'t understand what they mean. Please explain this to me.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Ningguang',
      audio: '4001',
      text: "I have no use for the wealth that ordinary people desire. But in the hands of Lady Ningguang, wealth becomes a means of solving complex issues of the kind that no weapons could ever hope to resolve. She understands the unwritten rules of human society, she knows what's in people's hearts... Master once told me that even the adepti aren't able to achieve this. I hold her and her work in high regard.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Beidou',
      audio: '4002',
      text: "I find I don't need to worry about etiquette with her, and unlike with some people, I don't need to rely on non-verbal cues to discern the true meaning of what she's saying. That makes me a lot more comfortable. The only problem is... Well, there are too many people around her all the time, and I heard there's also many crew members on her ship... I need you to go with me. It's the only way I can cope with so many people.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Yun Jin',
      audio: '4003',
      text: "Yun Jin performs... It's called \"Liyue opera,\" isn't it? I like this particular type of social interaction. You can get to know about the other person's background without having to actually interact with them one on one. If she ever includes your story in one of her performances, I'm sure the result will end up being quite incredible. I'm looking forward to it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Ganyu',
      audio: '4004',
      text: "I've heard many stories about her from my master. She's really quite different from how I originally imagined her... But don't worry, I'll be keeping this to myself. Speaking of Ganyu, her work in Liyue Harbor is unbelievably busy... It seems that there is a price to pay for those who want to integrate into the mortal world.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Chongyun',
      audio: '4005',
      text: "It's hard for me to believe that... I still have living relatives in this world. If he has any difficulties with his training, I am more than willing to help enlighten him. However, he will need to meet me alone in the mountains. Their family is too... sociable. I wouldn't know how to turn down their invitations without being impolite.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Xingqiu',
      audio: '4006',
      text: "I've seen him lean over to you and whisper things in your ear. If he dares threaten you, I will make sure he... Hmm? You mean it's just an in-joke between friends? Genuinely...?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Zhongli',
      audio: '4007',
      text: 'That gentleman claims to be a mortal, yet is very familiar with my master, who is an adeptus. Master once said: "If you see him drinking on a stone stool in front of my abode, do not disturb him. Let him sit quietly for a while." And that\'s precisely what I did.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Baizhu',
      audio: '4008',
      text: "The quality of his medicinal herbs is as good as it gets, he is also easy-going and considerate of others. By comparison, the little snake on his neck has no filter at all... Haha, don't worry, I didn't lift a finger against it, I won't go as far as getting into a quarrel with a snake.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Hu Tao',
      audio: '4009',
      text: "I often see her wandering in the woods singing strange songs. Actually, I must have heard all of her songs several times each by now. I'm used to her singing, but I still find it strange. That being said, I don't hate it either.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Xiao',
      audio: '4010',
      text: "My first impression of him was that he's not one to smile. After meeting him again more recently, however, he's still as reserved as ever, but... he seems a lot more relaxed now. Maybe he... met someone special.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'About Xianyun',
      audio: '4011',
      text: "The last time Master and Shuyu came to dine at Wanmin Restaurant, I noticed that Shuyu seemed to have adopted a number of Master's mannerisms. It gave me pause for thought... I grew up under Master's care, too. Is it possible that I have subconsciously picked up a thing or two from her as well...?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 11035,
              chapterId: 2045,
              chapterTitle: 'A Thousand Moonlit Miles',
            },
          ],
        },
      ],
    },
    '30': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Please don't pay any heed to the way most people refer to me. I am not an adeptus, and don't possess any divine abilities. I was born in a branch family of a clan of exorcists, and grew up in the mountains far away from Liyue Harbor. I am but an adeptus' disciple, nothing more, nothing less.",
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'When faced with delinquents who are just out to cause trouble, most people will try to reason with them. This course of action perplexes me. Removing the root of the problem and disposing of these ill-intentioned fools seems like the obvious course of action. Why do common folks prefer the labor-intensive route?',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About ___: III',
      audio: '5003',
      text: "I am the apprentice of multiple adepti and have trained alongside them. After a certain point, however, they stopped teaching me new techniques and started focusing on how to control my intense homicidal urges. Oh, don't be nervous... Yes, craters have been left in the ground, and giant trees have been uprooted. But these things only ever happen in the mountains, far away from civilization, and certainly have never affected innocent lives. Besides, I can control myself now.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "My father's intent was to trade my flesh and blood for my mother's life. After he abandoned me in that cave, I still held out hope that he'd come back to rescue me. One day went by. Then two days, three days... I used every ounce of energy in my body to fight off that monster. But as I collapsed on the ground, I finally realized that the day I was waiting for would never come. To this day, I don't know which one it is... Was I abandoned because I'm cursed, or is it the way I've been treated in life that has cursed me?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '34': {
      title: 'More About ___: V',
      audio: '5005',
      text: "Once, I secretly left the mountain and returned to my childhood village without telling my master. But it was deserted, and my father had long since passed away. I suddenly realized that the bond between my relatives and I had been completely severed. And nothing that I'd ever cared about in the past could ever have a future. Ever since then, I have abandoned everything related to the mortal world... That is, until I met you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '35': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'The most important aspect of meditation is stillness. Let go of all agitation, and let the air around you flow into your body. This technique allows me to quickly focus in on myself. I heard from my master that after meditating beyond a certain point, there is no need to adopt the meditation posture anymore. Adepti can meditate even when standing up... I still have much more to improve on.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: "___'s Troubles",
      audio: '6002',
      text: "The fear of losing the people most important to me, and the desire to save them... This kind of feeling makes my heart ache, I've never experienced anything like it before. It's a burden, yes, but it's also... something to hold onto.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food',
      audio: '6003',
      text: "I've sampled numerous dishes during my time away from the mountains, but the truth is that I don't really remember how they taste. The only dish I can never forget the flavor of is that bowl of noodles I ate at home, so long ago... I shouldn't have to remember that. Why do I have to remember that?",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'Chew medicinal herbs for long enough, and you can only taste the bitterness... In all the years I trained under the adepti, I had to abstain from all kinds of things, and to a point, I got used to it. But them... "The common delights of the mortal realm pose no hindrance to the adepti, thus, we may indulge in all manner of dishes as we please"... These are the exact words my master said.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Mmm, this taste... Is it really meant for me?',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "The food you cook is indisputably delicious. I can't refuse it.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "No matter. I'm used to this kind of flavor, after all.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Birthday',
      audio: '7001',
      text: "I've been told that birthdays are important occasions for most people. They give presents to celebrate the anniversary of the other person's birth. Material possessions aren't really my thing, but... The view of the starry night sky in the mountains is the most beautiful thing I've ever seen in my life. I've frozen this lake and turned it into a mirror, so you can appreciate the reflection of the fleeting clouds and distant stars right up close. This is my way of celebrating your birthday... Hope you like it.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'The power I harness... It grows stronger.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "If my master were to learn about this, she'd probably have me add some more red ropes...",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "I haven't been training as single-mindedly lately, and yet it's as if I'm growing stronger and stronger without making a conscious effort... I'm left to assume the only way for me to achieve this is by your side.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I once believed that freeing my mind from all agitation was the only way to overcome. But after everything I've experienced recently, I finally understand... Only when the right things weigh on your mind can the desire to protect awaken inside of you. And that turns your power into something... meaningful.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Obey!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Manifest!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Unleash!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Transfiguration!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'My will embodied!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Take your true form!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'By ordinance divine!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Cryo incarnate!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "Do your master's bidding!",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'So this is what the world considers to be "treasure"?',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Adepti treasures have special powers... Hmm, what about mortal ones?',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'These things... What are they used for?',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: "You'll regret that...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I shall not yield...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'I will wipe them out!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Don't push yourself.",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Allow me to finish this.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'No escape... from fate.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'My time has come...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'My curse to bear...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Feeble!',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'In your dreams!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'You will regret this!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'What exactly is teamwork?',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Understood. I just have to stand here, right?',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'I will do as you command.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '___ was originally from a branch family of exorcists, but due to a series of coincidences, she became the disciple of an adeptus.\\nShe is a student solely of Cloud Retainer in name, but her impressive constitution and intelligence quickly won several other adepti over.\\nShe would go on to learn from them all, eventually becoming a master of adeptal arts in her own right as a mortal.\\nShe very much looks the part as well in her unique temperament and manner of carrying herself — indeed, it would be no understatement to name her a true adeptus upon meeting her for the first time.\\nHowever, it is precisely due to the long years of tutelage that she has lacked company save for the adepti and odd passing illuminated beast.\\nThis isolation has caused her to grow distant and indifferent.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Sometimes, a few rumors will escape from Liyue\'s small community of pilgrims to make the rounds in the city\'s back streets.\\nThese tales often depict someone being in a hopeless situation in some desperate place, when suddenly—\\nA wandering white-haired adeptus comes to their rescue in the nick of time...\\nMost such stories are a collection of lovely, intoxicating clichés, little different from the oft-told street-tales of fated marriages and the like.\\nBut if one were to ask that white-haired adeptus to tell the story, it would take a vastly different shape:\\n"Some annoying creatures worm their way into the mountains from time to time. I simply get rid of them to prevent them from disturbing my master\'s meditations."\\n"If some people did wind up getting caught in the crossfire and injured... Well, it was their decision to come here. There isn\'t much I can do about that."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '___ is in all likelihood the least accustomed to mortal life amongst those who take on an adeptal appearance.\\nHaving been sequestered in the mountains since a young age, she lacks experience and common sense, which makes it difficult for her to relate to people normally.\\nTo ordinary people, there are many solutions to any given problem. But to ___, any solution that is not the simplest and most direct one may as well not exist.\\nFor example, she almost never considers "negotiation" as a solution to being at cross-purposes with others, mostly resorting to "threats" instead. After all, it is simple and efficacious. A good solution, no?\\nShe has also spent much time ruminating on problems that are truly esoteric.\\nFor example: Why do we need to pay for food?\\nIs there any difference between intimidating civilians and intimidating bandits?\\nShe even truly believes that her master, Cloud Retainer, is a most brilliant and eloquent conversationalist.\\nIn a certain sense, she can be considered very pure.\\nMuch like a child, she relies on her chaotic yet straightforward intuition and logic to get her through life.\\nMountain Shaper once had this to say about her:\\n"Little ___ is not only stronger than most — she also possesses a unique character."\\n"She knows not the world, understands not common sense, distinguishes few cuisines, and acknowledges no hierarchies."\\n"It may not be such an easy thing for Cloud Retainer to tutor her."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Liyue has no lack of folktales about meetings with the adepti, and many of these concern relative nobodies whom an adeptus took under their wing, thus elevating them greatly.\\nHowever, the circumstances under which ___'s fate became tied to the adeptal abodes was no such glorious thing. If anything, it was an experience characterized by anguish.\\nWhen she was five, her mother passed away, and her father, having loved his wife dearly, found that agony hard to bear.\\nOver time, this agony turned into resentment, and this resentment birthed obsession, by which he was driven wandering throughout the land like a man gone mad.\\nHe left for close to a year, never stopping, never able to sleep soundly, ever searching for some technique that might bring his wife back.\\nAt last, when the year was almost out, he returned in joyous frenzy.\\nHer father had brought with him a secret art known as \"Fate Transference\"—\\nBy making a ritual sacrifice to the seelie summoned by this art, a living person's body could be exchanged for a dead one's life.\\nAt that time, ___ was yet utterly unaware of the disaster that would befall. She was only an ordinary child, overjoyed at her long-absent father's return.\\nHe claimed that he had a surprise awaiting her in a cave in the mountains behind and that he would take her there immediately. She was ecstatic...\\nBut the scene that followed would be burned into her mind forever.\\nHer father summoned that hideous, horrifying black \"seelie\" into that cave, its blood-red eyes craving her delectable life-force.\\nStupefied, ___ knew not from whence it had come, nor what it wanted from this place.\\nCrises often paralyze people. One thought only, however, crept into the young ___'s mind.\\nThis creature wanted to eat her, but she did not want to die. She wanted to live!\\nGripping her mother's keepsake, an exorcism dagger, she faced that dark \"seelie,\" trembling yet resolute...\\nSeveral days later, an adeptus following the trail of great evil would investigate the cave, only to find the little girl collapsed inside — spent, famished, parched, her life hanging by a thread.\\nTaking pity on the lass' ruinous fate, and seeing that she possessed great talent, having repelled some terrifying force on her own, the adeptus would bring her back, heal her, and instruct her in the adeptal path.\\nIf not for that, ___ would not be as she is today.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Even the most diffident heart, cooled from living and training in the mountains for over a decade, might sometimes experience strange surges.\\nSo it was with ___. On impulse, she came down from the mountains one night to return to what was once her home.\\nShe did not know how she felt about her home or her family. She was merely driven by some nebulous desire:\\nTo live in the house that was once hers, and to see what became of her father, lost in his obsession.\\nShe learned from neighbors that he had passed away several years prior only when she got there.\\nHer childhood home had also been demolished by pawnbrokers — and thus had all the traces of her memory dissipated.\\nShe did not care about the attention she was attracting, and did not answer a single one of the questions asked by those in the vicinity.\\nShe simply stood there, listening to the howls that swept through the depths of her heart.\\nWas it hatred? Mania? Relief?\\nThey were all there, and yet none tarried for even an instant. It was as if her heart were an old well without ripples.\\nNo, like a barren well with no water upon which there might be ripples.\\nShe stood there for a long time, before departing again before the astonished eyes of all.\\nEach step was slow indeed, but she never once turned back.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Liyue has its own fortune-telling, destiny-reading methods, similar to astrology.\\nOf these, there are two fates that people seek to avoid at all costs.\\nOne is that of the "solitary star," which dictates that one will be separated from friends and family, living alone all one\'s days.\\nThe other is "disastrous evil," which means that one will face many hardships and perils.\\nWhen the adepti rescued ___, Moon Carver did once read her fortune.\\nThe signs showed that she was marked by both the "solitary star" and "disastrous evil," and that she was also plagued by intense homicidal urges — she was thus a person of supremely ominous destiny, doomed to harm both herself and others.\\nTo ensure that she could grow up safely and not harm any innocents, the adepti bound her soul using red ropes.\\nThis binding had the effect of restraining both her evil fate and her violent tendencies, but also shackled many emotions that should have originally belonged to a human.\\nFrom then on, she became more and more disaffected by trivial matters, and even things most might consider important were but dust to her.\\nShe became ever less human, and ever more like a lovely yet cold statue.\\nBut surprisingly, she felt something stir within her when she encountered that Traveler from a distant land:\\nLong-dormant emotions, now strangers to her, came loose all at once from the depths of fate\'s tableau.\\nPerhaps it really was as Moon Carver once said: that heaven might dictate fates, but destiny\'s tale is written by mortals. The tale of ___ and the mortal world had not yet ended...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'White Jade Comb',
      title2: null,
      text: "Once upon a time, ___ had a full head of black hair.\\nWhen she was first brought to Mt. Hulao, she would not say a word. The only thing she proved willing to do was to climb the mountain and watch the sea of clouds.\\nIt was well, however, that she would sleep when tired, drink the dew of the mountains when thirsty, and would chew on a few stalks of Qingxin when hungry.\\nCloud Retainer took this all in, but did not disturb the girl, instead making this comb of white jade from a sacred stone and giving it to her.\\nThe adeptus said that if she ever wished to sever her ties with the mortal world and enter adeptal tutelage, she should brush her hair thrice with this comb, and it would be counted as a rite of apprenticeship.\\n___ did exactly as the adeptus said without any hesitation. And something strange happened then — for as the jade comb brushed through ___'s hair once, a layer of her black locks turned a frosty silver from root to tip.\\nOn the second brush, but half her hair remained dark.\\nWhen the process was complete, only a flowing curtain of snow remained.\\n...\\nToday, ___ still keeps this comb on her person as a symbol of her connection to the adepti.\\nThrough her years of training, she has long since come to understand the meaning behind those three brush strokes:\\nThe first to uproot useless anxiety, the second to forsake joy and sorrow, and the third to walk this path into old age without regret.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Few people know how the young girl in the cave, intended as a sacrifice by her own father, had been able to stand against the monster for days and nights on end by herself.\\nThough ___ was born into an exorcist family, her maddened father had not taught her a single thing about exorcism.\\nAnd like many at that innocent age, she was also wholly unused to facing life's perils alone.\\nBut in that aphotic cave, bereft of parental protection — indeed, betrayed by kin — ___ underwent a metamorphosis.\\nJust as Moon Carver's readings had shown, the sleeping calamitous fates, violent urges, and unyielding spirit within her burst their bonds all at once.\\nThose things served as an unseen shield and invisible blade, arming the girl's frail form.\\nThey gave her strength, gave her claws and fangs, allowing her to attack that wretched creature before her, to swear to tear it to shreds — to prove that she, and not it, was the cruelest evil that stalked the darkness.\\nTheir life-and-death battle across the next few days was one without end. Hunter and hunted switched places many times, the conflict locked in stalemate...\\nAs the shadow of death loomed large, the gods looked upon the extraordinary girl with favor.\\nWith the bright, crystalline object falling into ___'s hands, the balance tipped irrevocably in her favor and the victor was decided.\\nThe vivid icy light pierced through the dark like skyglow, showing the path to the future.\\nIn the past, it had guided ___ from her miserable fate. In the future, it would also lead her back to the mortal realm.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
