export const kukiVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Oh... Hey there! I'm ___, deputy leader of the Arataki Gang. We offer a wide range of services, including but not limited to transport and logistics, security, home repair, and musical performances. Please feel free to contact me if you need anything. Here's my card.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: In a Pinch',
      audio: '1101',
      text: 'Just let me know if you ever find yourself in a pinch. I can help you out.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Certificates',
      audio: '1102',
      text: "The criteria for certificate exams are straightforward enough, what it really comes down to is whether you are willing to put in the time. If you study and practice, then it's really not all that difficult.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: The Arataki Gang',
      audio: '1103',
      text: "If the Arataki Gang stirs up any trouble, I'll drag every last one of them back to apologize.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "We don't need an umbrella, just pick up the pace.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Be careful. No one wants to get struck by lightning.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Let's just finish the job and leave. There's no need to waste time.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "It's a nice day, but I can't seem to shake this strange feeling... Huh, let's just hope it's my imagination.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'Hmm... what a pleasant breeze.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning. Going out to train? Huh, I didn't know you were so diligent.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Hey, what would you like to eat? I've been saving up lately, so lunch is on me.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Some commissions are better done by night. I can't trust the gang with such tasks though, so I usually do them myself.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "Go ahead and take a rest if you need. Don't worry about me.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: "About ___: Gang's Deputy Leader",
      audio: '2001',
      text: "My primary responsibilities are to bring in business and maintain a stable team... uh, as well as bailing out the gang from the Police Station, returning snacks and toys to kids, and catching anyone secretly slacking off during a job... I guess you could say all this extra work comes with being part of the Arataki Gang. I suppose that leaders of other groups wouldn't have to put up with that kind of stuff. But then again, no one else could do the job like me.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Backup Plan',
      audio: '2005',
      text: "Hmm? What would happen if the gang ever disbanded? First of all, that would never happen. Secondly, even if that did happen, I've got nothing to worry about. I've always got a way to make ends meet.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Notes',
      audio: '2003',
      text: "Come find me if you ever suddenly want to become certified in anything. I'll lend you all my notes for the exam. Believe me, my notes are detailed enough to help anybody pass.",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Cleaning Up the Mess',
      audio: '2002',
      text: "Whether you are in the Arataki Gang or not, I'll never treat you as an outsider. Just go ahead and leave the logistics and planning to me. Trust me, I'm an expert. I can handle anything, no matter how complicated it might seem. Huh? You're concerned about my safety? Hehe, don't worry, all these years of experience aren't just for show.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Just like a certificate, this Vision is solid proof of my capabilities. The only difference is that I'm still not certain about a Vision's assessment criteria.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Face Mask',
      audio: '3002',
      text: "I wear a mask because I don't want to be recognized by anybody, especially when I'm working with the Arataki Gang. If someone I know manages to recognize me, they're sure to make a big fuss about it... It gives me a headache just thinking about it. I won't ever let it happen again! Ahem, never mind...",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Gang Bylaws',
      audio: '3005',
      text: 'I came up with the Gang Bylaws so everyone would have a set of guidelines to follow. Huh? Why are they willing to follow my rules? Because both my words and my fists are very persuasive.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "There is a saying circulating among the shrines claiming that if you weave Naku Weed into a ring and wrap it around your body, it can dispel disaster and bring good fortune. So, do you believe that? I, however, personally find the plant's paralyzing effect a little more practical.",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About the Raiden Shogun',
      audio: '4001',
      text: "After the Sakoku Decree was lifted, the Raiden Shogun issued many decrees aimed at supporting the development of various industries. All those certificates I received during the Sakoku Decree are coming in real handy now, and the gang is finally out of the red... Fate really does have its ways. Who would've thought after all that, I'd still have her to thank?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 12042,
              questTitle: 'Radiant Sakura',
              chapterId: 2027,
              chapterTitle: 'Transient Dreams',
            },
          ],
        },
      ],
    },
    '22': {
      title: 'About Kujou Sara',
      audio: '4002',
      text: "Madam Kujou? Yes, she's a friend of mine. Hmm? You're surprised that I know her? Oh, you must've misunderstood, I knew her from before I joined the Arataki Gang. Heh, in fact, it's hard to tell who's the winner whenever we spar.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Yae Miko',
      audio: '4003',
      text: "You can't imagine how boring it is to be a shrine maiden. Even Lady Guuji from the Grand Narukami Shrine has her publishing gig to break up the monotony. I will never go back to being a shrine maiden. Never.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Arataki Itto',
      audio: '4004',
      text: "The boss has a lot of unpleasant memories from his past, but he still manages to stay positive. I'd say that kind of resilience is pretty rare. He treats us well and his character has a good effect on everyone in the gang. Of course, it's never an excuse for him to run amok with no consideration for others. Just let me know if he ever causes you any trouble and I'll be sure to make him regret ever being rude to you.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Yanfei',
      audio: '4005',
      text: "Back then I had an argument with my family and I only wanted to run away as far as I could. So, I went to study law in Liyue, but thanks to this experience, I got to meet Yanfei. She's like a walking law encyclopedia. Huh? Me? I have a certificate but there are a lot of restrictions for practicing law... It's not really the right field for me.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Shikanoin Heizou',
      audio: '4006',
      text: "He's different from the other Doushin of the Tenryou Commission. I have yet to see him on patrol or apprehend anyone, and he occasionally comes to me to buy intelligence. In exchange, I asked him to put in a good word for me whenever I'm bailing people out of the Police Station. He gladly agreed. I'd say that's a pretty good deal... After all, getting the boys to keep their eyes and ears open on the streets is easy enough.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'More About ___: I',
      audio: '5001',
      text: "I've worked many different jobs and I'm certified in a variety of fields. In terms of management, I've led a small team and have been responsible for delegating tasks and allocating resources according to... Uh, sorry, don't mind me... Sometimes I still slip into interview mode.",
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'More About ___: II',
      audio: '5002',
      text: "I come from a family of shrine maidens but I'm not cut out for that kind of work at all. When I ran away from home, I immediately thought I should learn as much as possible to support myself. I studied everything from cooking, tailoring, and fighting, to legal consulting, publishing, and editing... It wasn't until I really settled into society that I realized I've learned everything I need.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '29': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Hmm? You think I've got good social skills? Well, you could say I've seen a lot of the world by now. I've learned how to read people based on their expressions and body language. Besides, nine times out of ten, it's the gang getting in trouble. I don't mind putting on a face to get us out of a sticky predicament, but I still prefer not to smile.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "When I first joined the Arataki Gang, the boss told me to teach the others how to fight. So the first thing I did was beat them up, one by one. I was a little surprised that even in their bruised and swollen state they still respectfully called me ___ and asked me to lead them. Hmph, at that moment, I knew they really were a big bunch of idiots... But that's fine, even a group like this won't slow me down, I'll just take care of everything myself.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '31': {
      title: 'More About ___: V',
      audio: '5005',
      text: "It's my own decision to stay in the Arataki Gang. It can be pretty annoying having to clean up their mess all the time, but in return, they treat me with a sincerity that is irreplaceable... They always save the best things for me and never leave me feeling down. When I announced my decision to stay in the gang, they all cheered for me. I know outsiders don't think very highly of the Arataki Gang, and the members themselves don't really care what others think. But, I still want to strive to change the impression we leave. I might complain about them from time to time as my family, but I'll never let anyone badmouth them.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '32': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "Being in the gang means having lots of free time. I often finish reading a whole book or even pass a certificate exam before I even realize it. Kinda nice, wouldn't you agree? When my family asks about me, at least I can tell them I don't waste my time, and when I go job hunting, I have lots of qualifications to rely on. In this ultra-competitive society, a misfit like myself with all these certificates will never go hungry.",
      tips: '',
      tasks: null,
    },
    '33': {
      title: "___'s Troubles",
      audio: '6002',
      text: "Back then, I wanted to avoid getting dragged back to the shrine at all cost, so I had to find a way to stand on my own two feet. So far, I think I'm doing alright.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Favorite Food',
      audio: '6005',
      text: "Even after eating something really filling like ramen or gyoza, I still always want to finish my meal with a small bowl of rice. Rice is just delicious, that's all. Is there a problem with that?",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'There\'s a saying I heard in Liyue: "There is no bad food, only bad cooks." After getting my license as a chef, I became even more convinced that this is absolutely true.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "This is truly exceptional. Ehem... I'll just have another bite.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Did you make this? Hmm... you're more than qualified to be a chef.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Honestly, did you use the wrong seasonings?',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! Here, take this special dart made from Naku Weed. Be careful, yep, that's the way to hold it... Make sure you predict the trajectory before you throw it... Hehe, I'm happy that you like it. Oh, don't treat it like a toy, it's still quite dangerous. If you want to practice a little more, I can teach you.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "If you haven't mastered the basics, then there's no point in even trying to discuss it. That's the purpose of a basic-level certificate, to show you actually know something.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I have an intermediate certificate, which means that I'm qualified to handle most problems. Is there anything I can help you with?",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Earning an advanced certificate is not easy, it requires both talent and actual combat experience.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'Certificates are useful for judging professional skills but they fail to measure the amount of effort or emotional investment involved. Our friendship has gone beyond something that can be expressed with a simple "thank you." Let me express my feelings by always giving the very best of my abilities.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '44': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Our bond is strong!',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Dissipate!',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Stand with me.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "I'll settle this!",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Lightning... purifies!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Out of my way.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Every little bit counts.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Alright, this'll do.",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "It's all yours.",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Stop right there.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: II',
      audio: '410002',
      text: "Now I'm mad...",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: III',
      audio: '410003',
      text: "Alright, it's my turn...",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "I'll clean this up.",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I'm qualified to handle this.",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Sorry... for the trouble...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Take care of... the gang...',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'What a humiliation...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Again.',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Just you wait!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Looking for a fight?',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Wait for my signal.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "What'd they do this time?",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Don't tell me they did it again...",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "In the Arataki Gang, where swaggering commotion is something of an aesthetic, the ever-masked and low-key ___, the gang's second-in-command, stands out all the more against the backdrop of the other, more clamorous members.\\nNo matter what sort of mess the others have gotten themselves into, this deputy is often able to solve their problems in a manner that is both professional and highly efficient.\\nMaking some snacks for children who had theirs snatched away, giving scratched lacquerware a new coat of paint, and serving as an advocate for detained comrades...\\nSuch are her skills that onlookers often wonder if there is anything that she cannot do.\\n\"I wouldn't say that I'm certified for everything. There are some industries that just don't have standardized assessments, so there's no way to sit for any such tests.\"\\nHer displeasure finds eloquent expression even behind her mask.\\n\"Also, how can there be lines of work where you can find employment without the right qualifications? It boggles the mind.\"\\nEqually mind-boggling, perhaps, is the fact that her deep puzzlement is just as contagious.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'People often say that a namecard is one\'s door into society.\\nOf course, the act of embroidering such cards in gold and silver confounds comprehension, but it is true that giving another party a small card that contains your name, position, and contact details is a very efficient thing to do.\\nWhen ___ first entered society, the details of her namecard were a matter of serious concern.\\nEx-Grand Narukami Shrine Maiden? She strangled that thought in its mental crib the moment it was born.\\nJust "___"? No, no, that would make her seem like some unemployed bum with neither skill in word or deed.\\nPerhaps she should go get a certification, then. That was common wisdom, after all.\\nCertifications serve as excellent proof of one\'s efforts, and are convincing ways of scoring points upon introduction — very useful things indeed.\\nAfter easily getting a couple of such certificates, ___ finally reckoned that she could add a little color to her presently-blank namecard.\\nUnfortunately, this process proved to feature pitfalls of its own: out of curiosity and in an effort to test herself, she had gotten a whole load of certifications in one go, causing the prefix section of her namecard to balloon uncontrollably.\\n"Junior Chef, Tailor, Actuary, Health Manager, Human Resource Manager..."\\nHaving lots of skills is not a bad thing, but there is such a thing of having too many skills, lest one struggle in the snare of figuring out one\'s titles, like ___ did.\\nTo this day, ___ cannot remember how many namecards she has made.\\nBut ever since she joined the Arataki Gang, her very first title has always been "Deputy."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "After tasting ___'s very own Roasted Lavender Melon, the Arataki Gang all wept and exclaimed that they never knew that Lavender Melons could be so delicious when roasted.\\nAnd the flavor, too, was most different from that which had been produced by any other method they had ever tried. Could it be that high-class culinary exams also taught people how to cook Lavender Melons a certain way?\\nFaced with such a question, ___ put the melon she was grilling down before slowly telling a story.\\nAt that time, she had gone to far-off Liyue to study law, and would visit this place known as Wanmin Restaurant in her free time.\\nThe food there was incredibly diverse and made in unique ways, with ingenious ideas that surprised her, despite the fact that she had already obtained a high-level culinary license at the time.\\nFrom slivers of stir-fried meat immersed in sauce to boiled cabbage with the fragrance of chicken soup... Indeed, the world was wide and full of wonders.\\nAnd though one might be acquainted with every profession and be certified highly in every one, it is never wise to rest on one's laurels. Indeed, it is only by daring to try and make breakthroughs that one can surpass the limits set down by those who came before.\\nThe Arataki Gang did not understand this in full, but they cheered all the same, for there was no harm in that — and their cheers certainly did the melons' flavor little harm.\\nSeeing how they greatly enjoyed their meals, ___ kept the ending of the story to herself.\\nBack then, the sous chef of Wanmin Restaurant had heard her say these words, and had urged Chef Mao to bring out the Salt and Pepper Slime...\\nSuch food, she knew, would never appear in any culinary exam anywhere in the world.\\nNor would the Arataki Gang want to learn that ___ had slathered slime ooze onto Lavender Melons as sauce before grilling them...",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "The ___ Clan is a family of shrine maidens, a tradition that spans generations. Members of that family regard service to Narukami as a great honor.\\nThis too was the case with her generation. After her sister Miyuki was sent to the Grand Shrine, she was also sent there from a young age as an understudy.\\nOf course, a great store of rules and regulations came with this time-honored tradition: for example, how many days to fast to show one's sincerity and resolve, or how many ablutions were to be performed to avoid profaning the divine...\\nNo one ever explained where these rules had come from or how they had been decided. She was simply told that they had existed since way back, and thus were to be followed.\\nWhen ___ first arrived at the shrine, she would sometimes catch a chill from staying on the mountain at night. At this time, her family lived far from the shrine and her sister was out on an errand far afield.\\nA strong-willed child, she did not ask the other shrine maidens for help, but would instead pluck thorned plants one by one, alone, before twining them around her body.\\nAccording to a traditional saying, this deed would earn you the protection of Narukami and remove the illness from you. So she went on twining that loop of thorns, even as she whispered prayers to Narukami for protection deep into the night, shivering all the while.\\nHowever, when the night was over, her chill was not cured. All she had earned instead was a tingling red mark around herself.\\nAs the days passed, ___ would find again and again that the rules were not as foolproof as the ancients might have made them out to be, nor was the role of a shrine maiden quite as indispensable as they had claimed back home.\\nWell then, didn't that mean that the very necessity of the ___ Clan to become shrine maidens was also up for renegotiation?\\nSome years later, ___ had already left the shrine for some time now, and with time to kill, she would flip through a book on herbology.\\nWithin its pages, she found that it clearly, indeed vividly, described how the mountainous thorns had paralytic properties that could render birds and beasts unable to move, and that it was this property that led the ancients to include them into medicine to ameliorate topical aches and pains.\\nShe was, well... speechless.\\n___ thought to herself that yes, perhaps rules did have rhyme or reason behind them, but to treat the rules as reason in themselves must be treated as an obsolete practice.\\nOn further reflection, she could not help but feel that she was happier living her current life.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'To find work through which she might truly have freedom, ___ once declined all manner of respectable job offers, only agreeing to being hired as part-time outsourced staff.\\nOne of these commissions came from an old lacquerware professional who had accidentally thrown his hip out of whack. The job itself was no challenge to ___, bearer of an advanced certification in this field, but the address of the client was... well, a little special.\\nWhen she brought the newly-maintained figurine to the Police Station, she ran into a petty thief who was making their escape from that site who, fleeing at all speed as they were, rammed right into her, sending the doll sailing into the air.\\nSeeing that several days\' work was about to go down the gutter, ___ struck out like lightning, seizing the figurine with one hand before whirling about and tripping the suspect.\\nAll at once the surrounding people surged forward, subduing the crook. Afterward, Kujou Sara — seemingly the person who had placed this order — would come and thank her personally.\\nAs for the goods, they were perfectly unharmed, much to Sara\'s surprise — to think that someone in the lacquerware business could have such martial skill!\\nAfter learning of ___\'s circumstances and her desire to "find a job that gives her real freedom," Sara would consider for a moment before inviting ___ to join the Tenryou Commission.\\n"Hmm... No, I think I\'ll pass. The civil service seems a bit too limiting for me..." At this point, ___ hesitated. "But if those legal lectures and martial arts training could be done part-time, I will definitely consider the offer."\\nFrom that day on, ___ would begin a new slew of part-time work.\\nOne thing did surprise her, though — the general of the Tenryou Commission would always attend her lectures and demonstrations.\\n"It is only right that those who enforce the law should better understand it," so Sara said with perfect earnestness.\\n"The opportunity to test myself against similarly-skilled warriors is also not one I get often," ___ replied.\\nSara\'s straightforward personality and decisive behavior were things ___ greatly approved of, and it was through this — and through Sara hiring her often to maintain figurines — that the two would quickly become friends.\\nSara would also repeat her offer of employment several times, only for ___ to decline each time. Yet, this "job that brings true freedom" was not something she would find, either.\\nThat is, until one day, when Sara wound up arriving late to the izakaya where they had arranged, as they often did, to meet and have figurines change hands, leaving ___ to drink till midnight.\\n"That\'s unexpected. I didn\'t think you could be late at all, Sara."\\n"Sorry. I was held up by a really rowdy gang..."\\n"A gang? And what gang could have troubled you that much?"\\n"Well, I wouldn\'t call them \'trouble\' exactly. They call themselves the Arataki Gang..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "The news that the Arataki Gang now had a second-in-command raised a decent (though ultimately small) stir in Hanamizaka.\\nIt was rumored that this deputy was well-versed in etiquette, law, and was quite the dab hand physically as well, bringing the other members to heel within a few days of arriving.\\nThose who had witnessed this deputy's actions first hand were full of praise for them, saying that at long last, the Arataki Gang had someone polite and reasonable added to their ranks.\\nSome did worry about this development, however: the Arataki Gang was, after all, not a proper organization by any measure.\\nThe little hullabaloos they had caused in the past were nothing, really, but with the arrival of someone who could be the \"brains\" of the organization, who might put some discipline into them... Could this not also be the harbinger of worse incidents to come?\\nNot to mention the Gang's daily operations... Other than logistics and transportation, home repair, and performance, they now added tax agency, legal consultation, event management and various other operations that both involved sizable capital investments and a not-insignificant air of danger to them.\\nSurely they weren't intending to do all these things without the right licenses... right?\\nAnd never mind the licenses, first — if they were to commit fraud in any of these newly-added businesses, they would surely be arrested by the Tenryou Commission!\\nHowever, these wild guesses and ill-omened rumors would quickly be dispelled. The Arataki Gang's actions afterward were more than enough to show that they were still a gang of their word.\\nThose who have attempted to enlist their new financial services have indeed seen their situations turned right around, and the transparency and uprightness of their processes have been stunning.\\nOf course, it is also a pity that the Gang remains the Gang. The children of Hanamizaka still live in fear of Arataki Itto coming to win their snacks off them come dinner time, and often still return to their homes fuming.\\nIn any case, it seems that even this legendary second-in-command will take a long time to reform the Arataki Gang's more... unbound ways.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Oni Mask',
      title2: null,
      text: '___ had yet to wear her mask when she first joined the Arataki Gang.\\nWhile pursuing a certain business prospect, ___ was busy engaging in some serious talks. The other members of the gang were arrayed behind her in a single row, hands behind their backs and unsmiling.\\n"Just stay like that and don\'t say anything," ___ had instructed them to do so on short notice. "This is the most effective way of negotiating... For you guys, anyway."\\nThe talks were going exactly as ___ expected, until a passing child suddenly pointed at her, exclaiming:\\n"Mama, mama, look! That\'s the shrine maiden who never smiled back at the Grand Shrine! Wow, she looks so cool!"\\nThe child was whisked away by her panicked mother, but the quick departure did not change the mottled embarrassment and resignation on her face, as if she could not wait to flee for the hills and forests right that instant.\\nAs for Itto\'s face, it was as if two onikabuto were wrestling for dominance upon it. Genta and the others, try as they might, ultimately lost their poker faces amidst gales of guffaws.\\nThe next martial demonstration would, of course, see their faces beaten so hard that they were redder than ___\'s was at that moment. If only they had known their fate, perhaps they might not have laughed quite so hard.\\nFrom that day on, ___ would sport that mask. Pitch-black and claws bared, it lent her a positively demonic aspect.\\nBy the way, it was also that martial demonstration that served as the origin of her moniker "the demonic deputy".',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'The day she left the shrine, ___ left all the things that she possessed while serving as a shrine maiden behind at home, starting over from the most basic of belongings.\\nAs such, she knew immediately that the bag she lifted was not the right weight. Hadn\'t she only left towels inside it?\\nReaching into the bag and fishing about, she pulled out, of all things, a glittering Vision, its loveliness so striking such that her sister, Miyuki, could not help but gasp.\\nAn irony it was indeed that the shrine maiden who was fleeing her duties would receive a Vision for doing just that.\\nThis, of course, was the very first "certification" that ___ would receive — from a god, certifying her freedom.\\nIndeed, Miyuki, who had intended to stop her at first, had a change of heart upon witnessing this sign, agreeing to help convince their parents.\\n...It was also due to this that she would willingly surrender her Vision while the Vision Hunt Decree was ongoing.\\nFor one thing, she did not intend to make life difficult for her friend in the Tenryou Commission, but for the other, the Vision was but one of her many, many certificates.\\nMost things in life could, in any case, be settled without the use of a Vision, nor could the truly obdurate problems be dismissed simply by the dint of that device.\\nRemoving generations worth of prejudice, for example, or searching for true, unbound freedom.\\n...Or, you know, stopping those dolts in the Arataki Gang from chomping at the bit to "help" her win her Vision back.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
