export const beidouVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Beidou_Hello',
      text: "I'm ___. You've heard of my ship, The Crux and its crew? If you too love adventure, then join me. I've got your back.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Sparring',
      audio: 'VO_Beidou_Chat_-_Sparring',
      text: "If you ever want to trade tactics, I'm always ready.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Drinking',
      audio: 'VO_Beidou_Chat_-_Drinking',
      text: "Ah! A cold beer after a hard day's work... Nothing like it!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Land',
      audio: 'VO_Beidou_Chat_-_Land',
      text: "It's hard to remain on dry land for so long. Can never seem to quite get my land legs back.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Beidou_When_It_Rains',
      text: "When stuck on a deserted island, rain is a precious source of drinking water. There's no need for it now though.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Beidou_When_Thunder_Strikes',
      text: "Hey, it's just a little lightning. No need to fear it on the open ocean, so there's even less need to fear it on dry land.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: "When It's Windy",
      audio: "VO_Beidou_When_It's_Windy",
      text: 'This weather would be great for setting sail.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: 'VO_Beidou_When_the_Wind_Is_Blowing',
      text: "Wind's picking up. If sand gets in your eyes, be sure not to rub them.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: 'VO_Beidou_Good_Morning',
      text: "Yo, good morning. I'm about to head off, coming with me?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: 'VO_Beidou_Good_Afternoon',
      text: "Let's get Xiangling to whip us up something for lunch. Believe me, a hot meal from her is far better than the salted fish we eat out at sea.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: 'VO_Beidou_Good_Evening',
      text: "Alright, I'm off for a drink. Hahaha, no one willing to sell you a proper drink, huh? Perhaps I can...",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: 'VO_Beidou_Good_Night',
      text: 'Time moves quickly. Haha, go, may the wind be at your back.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___',
      audio: 'VO_Beidou_About_Beidou',
      text: "We're setting sail! Men, to your posts! A new adventure is about to begin!",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Titles',
      audio: 'VO_Beidou_About_Us_-_Titles',
      text: "I'm the captain, so you can be my first mate! Deal? Ha? Such names are too outdated for you huh? We'll call each other whatever you wish then.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Eye for People',
      audio: 'VO_Beidou_About_Us_-_Eye_for_People',
      text: "I tend to be a good judge of character. When you've learned to read the open ocean, reading people is a cinch. Haha, and that's how I knew you're the good sort the second I laid eyes on ya!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About Us: Choices',
      audio: 'VO_Beidou_About_Us_-_Choices',
      text: 'I chose you as my crewmate, as my comrade on the sea. It gives me great pride to be able to say that.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: 'VO_Beidou_About_the_Vision',
      text: "To those that don't have a Vision, it must seem that those with Visions are like flagships from the Archons to follow. As such, I make sure to fly my flag with pride. That is my motivation.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: 'VO_Beidou_Something_to_Share',
      text: "At a loss? When you don't know what to do, just take the first step. The rest will figure itself out naturally.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: 'VO_Beidou_Interesting_Things',
      text: "Every time I return from a long journey and I see the lapis gledes, I'm reminded that I'm almost home. The scenery out on the open ocean gets familiar real quick. Sure, they're birds of prey, but seeing them fly so freely is heart-warming.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Ningguang: Liyue Qixing',
      audio: 'VO_Beidou_About_Ningguang_-_Liyue_Qixing',
      text: 'Ningguang, eh? As far as Liyue Qixing is concerned, she seems to be doing a good job. But for me, my responsibility lies with my ship and my men, and not with Liyue Qixing.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Ningguang: Attitudes',
      audio: 'VO_Beidou_About_Ningguang_-_Attitudes',
      text: 'Ningguang is never really one to speak frankly, but she has been very direct with her criticism of me in the past. Haha... But hey, whether she likes me or hates me is her choice, nothing I can do to sway her.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Xiangling: Culinary Skills',
      audio: 'VO_Beidou_About_Xiangling_-_Culinary_Skills',
      text: "When we're out on the open ocean, the one thing we do all miss is Xiangling's cooking. When spirits are low, just thinking of her fried jueyun chili, bursting with flavor... It gives everyone just that little extra kick.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Xiangling: Food Tasting',
      audio: 'VO_Beidou_About_Xiangling_-_Food_Tasting',
      text: "Xiangling huh? She sometimes uses some... interesting ingredients in her dishes to bring about some, ah... intriguing flavors. Though... there's no way she can improve without having someone to taste-test — a role that I am more than happy to fill.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Zhongli',
      audio: 'VO_Beidou_About_Zhongli',
      text: "You mean the gentleman from Wangsheng Funeral Parlor? My men sometimes speak of the rumors surrounding him — he sounds interesting. Yes, if I get the chance I'd like to meet him someday.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Xiao',
      audio: 'VO_Beidou_About_Xiao',
      text: 'One year on the eve of the Lantern Rite, we ran into a storm as we were returning to port. Try as we did, we only made it back to Liyue Harbor in the dead of night, long after the lanterns had all been released. As I looked towards Guyun Stone Forest, I saw an adeptus, floating in the air, in the form of what appeared to be a young boy. I guess it is like the legends say — there really must be those that watch over Liyue, even if they cannot be seen.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Ganyu',
      audio: 'VO_Beidou_About_Ganyu',
      text: "Privately, Ganyu and I get on like a house on fire! But as you know, she's the secretary to the Liyue Qixing... and I'm not exactly in their good books right now! Doesn't bother me, but I wouldn't want to put Ganyu in a difficult position. So just keep what I said between us, yeah?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Xinyan',
      audio: 'VO_Beidou_About_Xinyan',
      text: "She's got a great personality, that one! The guys in the crew love that rock and roll of hers. Me? We have common ground, just... not when it comes to taste in music.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Yaoyao',
      audio: 'VO_Beidou_About_Yaoyao',
      text: "Yaoyao always comes on board to play when we're in the harbor. Trouble is, when it's time for her to go she gives you the puppy eyes, and no one has the heart to send her away... Means we're always cutting it quite close by the time we manage to set sail.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Kaedehara Kazuha',
      audio: 'VO_Beidou_About_Kaedehara_Kazuha',
      text: "Kazuha? That scallywag actually blocked a strike from the Raiden Shogun outside Tenshukaku! Easier said than done... After the battle he came to the Crux Fleet — said he'd voyage with us a while longer. I was more than happy to oblige. If the day comes when he decides to set off again by himself on the next stage of his journey, I'll send him off with a drink, haha...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'More About ___: I',
      audio: 'VO_Beidou_More_About_Beidou_-_01',
      text: 'Before you step foot on The Alcor, you need to answer one question. When the sea is full of perils — why is it that you still wish to come aboard my ship?',
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About ___: II',
      audio: 'VO_Beidou_More_About_Beidou_-_02',
      text: "You want to know of my legendary tales? Hahaha, that's just my men exaggerating, adding in their own little details. Although, if you were to ask me if I'm afraid of what monsters lurk in the deep, I'd tell you I have no fear of them.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About ___: III',
      audio: 'VO_Beidou_More_About_Beidou_-_03',
      text: "You wanna know why I help the common folk? Why not? Everyone has their low points in life. I don't really do anything, other than help steer those who are truly lost towards a brighter future.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About ___: IV',
      audio: 'VO_Beidou_More_About_Beidou_-_04',
      text: "I've been through some hard times. When I was a child we had little money, so nothing to eat, and lived for years by stealing fruit off of people's trees. Even after I got my own ship, I was cast out by pompous merchants. But me telling you such stories is merely for your amusement. I have no intention of making you live through it too.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About ___: V',
      audio: 'VO_Beidou_More_About_Beidou_-_05',
      text: "I have many brothers that sail with me. I have asked, and remember, why each and every one of them came on board. You, however, are special. I know you still have your own things to deal with, and as such, I won't try to rope you into coming onboard permanently. But remember, there is always a place for you onboard The Alcor.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "___'s Hobbies",
      audio: 'VO_Beidou_Hobbies',
      text: "My hobbies...? Eh, lemme think... Well, there's adventure, sailing, making friends, drinking, eating... more than I can count on one hand.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "___'s Troubles",
      audio: 'VO_Beidou_Troubles',
      text: "If you can change something, change it. If you can't, don't waste time thinking about it. That's how I go about things. But really, if you get stuck, come find me. I'll help you deal with it.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: 'VO_Beidou_Favorite_Food',
      text: "I like food with robust flavors. Spicy fried meat or spicy tofu are my favorites. Sitting down to a big hearty meal together, where everyone can fill their bellies — now that's when things get lively! Haha, alright, alright, all this talk is making me hungry!",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: 'VO_Beidou_Least_Favorite_Food',
      text: "I'm not a fan of anything cold, it does nothing to fire up my appetite. I'd rather fry up a few fish.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Beidou_Receiving_a_Gift_-_01',
      text: 'Tastes good, I like it! Mind giving me a bowl of rice with this?',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Beidou_Receiving_a_Gift_-_02',
      text: "Your cooking skills aren't bad at all, eating your food has me in a good mood.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Beidou_Receiving_a_Gift_-_03',
      text: "You know, at the end of the day, food is food, and that's fine by me.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: 'VO_Beidou_Birthday',
      text: "Come, board my ship. I've gathered the crew. The food and drink are all prepared. Today is your birthday, so you are the captain. Haha, so: where should we set sail?",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Beidou_Feelings_About_Ascension_-_01',
      text: 'Great! I feel much stronger.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Beidou_Feelings_About_Ascension_-_02',
      text: "We're making progress. Let's crack open a bottle to celebrate!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Beidou_Feelings_About_Ascension_-_03',
      text: "A prime example! It is an honor to have you aboard. I need to keep up if I'm to keep the respect of my crew.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Beidou_Feelings_About_Ascension_-_04',
      text: "After all this training, I feel like I'm finally at my best. Thank you... But please, I'd still like for you to keep me on my toes.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '___ is the leader of The Crux — an armed crew based in Liyue Harbor.\\nAn armed crew means exactly what it sounds like: a crew of sailors armed to the teeth.\\nWithout getting into too many details, everything The Crux does is approved by the Qixing... more or less.\\n___ is a trusted leader, so much so that her crew believes her capable of taming the storms and billows on the sea.\\n"It\'s ___! Even the mightiest of storms must bow its head to her might!"',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "___ is something of a cultural icon in Liyue.\\nThough her fame does not quite reach the same lofty heights as that of the Liyue Qixing, one can be certain that every merchant in the city knows her name — and that of her crew, The Crux.\\nNaturally, there are rumors abound regarding someone of her status. People love to tell epic tales of her earth-shattering (or rather, sea-splitting) feats. Tales in which her abilities are exaggerated to almost superhuman levels.\\nOne rumor is that she can channel Electro energy with her sword. It is said that she once used it to cut a formidable sea monster from the depths of the ocean abyss in half with just one hit.\\nBystanders who overhear such tales generally dismiss them as drunken ramblings. But to anyone who has ever voyaged with ___ themselves, these stories are no joke. In their view, if this world really were home to a giant sea monster from the ocean abyss... ___ would certainly be capable of cutting it in half.\\nIn summary, ___'s abilities are every bit as impressive as her reputation in business circles. So if you hear her lauded as the Uncrowned Lord of the Ocean — suffice to say that there is no smoke without fire.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'Business people tend to put profit before their humanity. This is just accepted as the way of the world. At most, it makes for some light verbal sparring at the dinner table.\\nBut things are different in Liyue, where everyone is involved in business. They reject the notion entirely, claiming that Liyue Harbor is a special place where humanity is sacred.\\nForeign merchants will retort that the only thing special about Liyue is that "They\'ve managed to commodify humanity, too!" To this, Liyue locals respond, "Then how do you explain The Crux?"\\nWith The Crux having made a name for itself over many years, its services are extremely expensive to charter. And yet, on one voyage when The Crux encountered a strong storm, ___ noticed a small private boat nearby. Seeing the way it was tossed about by the waves, she ordered her crew to tow the boat to safety — despite the risk that her ship\'s keel might give way. What little food and water the fleet had left, ___ shared with the rescued crew as she navigated her vessel onward through the raging storm.\\nFinally, after several days, The Crux delivered the rescued boat to a safe mooring spot. Grateful to ___ for saving their lives, the crew of the rescued boat became her loyal trade partners thereafter.\\nAfter Liyue locals recount this story, they smile and insist, "When you have someone risking their life like that, you can be sure that it takes far more than commodification to explain their actions! Would you really dare to look ___ in the eyes and talk about the commodification of humanity?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Word has it that The Crux's boss behind the curtains is none other than the Qixing's Tianquan, Ningguang, herself.\\nBoth of the people involved deny this outright, though they do so for different reasons.\\nAs a member of the Qixing, Ningguang often needs someone else to do her dirty work for her. Of the many candidates available, she picked ___.\\nNingguang would emphasize that she picked ___, not The Crux. Ningguang's collaboration with The Crux is, therefore, purely incidental.\\nMeanwhile, when ___ hears the rumors about her dealings with Ningguang, she furiously insists that she collaborates with Ningguang on an equal footing: ___ is her own boss and no one, not even Ningguang, is sitting in the background pulling the strings for her.\\n___ is certainly unique among Ningguang's collaborators.\\nShe does not tread carefully or show reverence in the way that most of them do. In fact, one could even say ___ is sometimes at odds with Ningguang.\\nNingguang's advisers worry constantly that ___ is too unpredictable and too much of a maverick. But Ningguang simply smiles and dismisses their concerns.\\n\"On the contrary, ___ is the most reliable person in Liyue,\" she replies. \"Just tell her the truth, as well as what's in it for her, and she'll come around in her own time.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Once, after disembarking from a long voyage, The Crux held its customary three-day celebratory banquet. The autumn was like any other before it — except for the new chef in town. This was Xiangling, the head chef-to-be of the Wanmin Restaurant.\\nLooking to keep costs down, they lured Xiangling onboard after meeting her on the streets, by hook and by crook. When she saw ___, Xiangling was dismayed, and let ___ know this in no uncertain terms: \"If you want to have Yue-style seafood, then I can't agree to help you. I'll have you know that I intend to transcend Liyue's two warring culinary styles with my cooking...\"\\n___ merely smiled and gestured to the chest of gold coins beside her: \"Just do what you're good at. We made quite a bit on our last run. How does a retainer of fifty thousand Mora sound?\"\\nNot one to shy away for a chance to prove the worth of her cooking, Xiangling took the job.\\nWhen the day was done, ___ was indeed won over by Xiangling's skill. She declared in front of her crew that Xiangling would soon be a renowned chef throughout Liyue. She also insisted that they refer to her as \"Madam Xiangling.\"\\nHaving only begun to make her name, Xiangling admired ___ for her generosity with money and her direct personality. Thereafter, Xiangling would sail with ___ often, looking for new and exotic seafood ingredients. She found herself surprised by ___'s vast knowledge of seafood and their culinary preparation, given how far she usually was from any kitchen.\\nOf course, that didn't mean Xiangling would necessarily heed ___'s advice on whether something was edible or not...but that is a story for another time.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Some say an object takes after its master.\\nThough it may not be a suitable description, The Crux crew does indeed take after ___, exhibiting the same qualities.\\nHowever, there are still secrets among the crew, spreading in places unnoticed by ___.\\nHer First Mate always takes new sailors out after their first safe return for drinks and fills them in on the details of an old story:\\nIn the past, the crew went on a journey to brave the unknown seas and found itself at death\'s door in a horrific storm.\\nAt that time, ___ stood on the deck behind the wheel, singing a Liyue fishermen\'s song in the storm.\\n"...all the way until the waves died down and dawn broke on the far horizon..."\\nThe First Mate often ends the story with this final line and a look of longing on his face.\\nAs business grew and the crew expanded, more and more outrageously incredible details were added to the story, making the rookies worship ___ like a goddess.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "Pier Laborers' Gossip",
      title2: null,
      text: "1. Facing a three-headed hydra of unrivaled girth, ___ hurled forth her greatsword. Spinning in the air, it sliced clean through all three of the hydra's vertebrae, before returning to her waiting hand.\\n2. ___ has beaten Ningguang at chess. Twice. The important part is not so much that she did win Ningguang's money, but more that she dared to.\\n3. Since the day she slew the sea monster Haishan, ___ has never sung a fishermen's shanty ever again.\\n4. Yes, ___ knows shanties. But don't you dare ask her that to her face. I mean, you know how that hydra ended up, don't you...",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Liyue and Inazuma share a common saying: "Its fins formed the ocean deep, its tail the mountains high." The fishermen learned this phrase while ashore long ago, and sang it over and over, spreading the tune far and wide till it became the much-loved song people know today. Whenever the mists gather over the sea\'s surface, one can hear the distant song of the fishermen hidden in the white shroud: "its fins formed the oceans deep, its tail the mountains high..."\\nThis was ___\'s childhood lullaby. The tale of Rex Lapis smiting the sea monsters had become legendary among the people of Liyue. As a child, ___ loved tales like this, and in her dreams, she thought: One day, I want to see this big fish too.\\nThis day, however, she sang this song with a different emotion in her heart. Her entire crew sang along as they sailed.\\nHaishan was in the waters with them — at once like a dragon and a fish, it was larger than any could have imagined in their worst nightmares, and mighty as a deity, raising waves dozens of meters high with ease.\\nAll who ply their trade on the high seas are destined to meet Haishan eventually. ___ had longed to do so since she was nine, dreaming of slicing its head off in a single blow.\\nMany times she had challenged the creature, and many times she had failed. But this day was different. This day she charged at Haishan with her best greatsword in hand, and crack sailors at her back.\\nThe battle would rage fiercely for four days. With cannons and harpoons, arrows and ropes the fleet would assail Haishan, while ___ battled the thusly tied-down creature for ten hours, well into the night.\\nNow, nighttime was when Haishan was in its element, and in their vigilance not a single member of the fleet dared sleep a wink. ___ stood upon the prow, listening to the wind.\\nOne strike. Just one strike. That was all she needed. And so she waited, unmoving, in the freezing wind.\\nThen, at the crack of dawn, having neither eaten nor drank throughout the night, ___ heard a change in the sound of the waves.\\nWith one almighty strike that sounded as if it could have sliced the moon in two or ripped a mountain from the face of the world, she chopped the leviathan\'s head clean off!\\nThe sound of thunder filled the heavens, and a single bolt of purple lightning struck the ocean right in front of ___, even as she bathed in the blood of her nemesis.\\nThus descended a Vision to the slayer of the sea monster, its violet glow as stunning as lightning, and its immaculate, jeweled form a treasure more precious than dragon blood. A suitably divine gift for the hero who subdued Haishan.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
