export const fischlVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Fischl_Hello',
      text: '___: I, ___, Prinzessin der Verurteilung, descend upon this land by the call of fate an— Oh, you are also a traveler from another world? Very well, I grant you permission to travel with me.\\nOz: She means, "Nice to meet you."',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Whispers of Destiny',
      audio: 'VO_Fischl_Chat_-_Whispers_of_Destiny',
      text: 'I hear the voice of fate, speaking my name in humble supplication...',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Creation of the World',
      audio: 'VO_Fischl_Chat_-_Creation_of_the_World',
      text: 'Hm-hm, may the glory of the Prinzessin bring light to this world.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: One From the Beyond',
      audio: 'VO_Fischl_Chat_-_One_From_the_Beyond',
      text: "___: I do worry about the well-being of my retinue during my impromptu absence...\\nOz: I'm sure the good people of the Adventurers' Guild are absolutely fine, mein Fräulein.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'After the Rain',
      audio: 'VO_Fischl_After_the_Rain',
      text: "Oh, the sun's out— Oh, um... This meteorological transformation is most splendid! Like a felicitous twist of fate in the face of certain doom.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Fischl_When_Thunder_Strikes',
      text: "___: Hark! 'Tis Thundering Retribution, an omen of dark times ahead...\\nOz: That, and mein Fräulein's laundry is still on the line...\\n___: Wha... Seriously!?",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: 'VO_Fischl_When_It_Snows',
      text: '___: A wonderful sight indeed. Why, it reminds me of my home world, where at the sight of the Prinzessin der Verurteilung, the very blood and tears of sinners turn to ice! ...Achoo! Achoo!\\nOz: Not only their blood and tears, but also their saliva and mucus, mein Fräulein.\\n___: Oz— Ahh—Achoo!!!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: 'VO_Fischl_When_the_Sun_Is_Out',
      text: "___: Ozzie, my dear familiar...\\nOz: \"Ozzie?\" What's gotten into you...\\n___: Her Majesty beseeches you to unfurl your blessèd wings, and with them blot out the heavens, plunging the world into eternal night...\\nOz: If you didn't bring your parasol with you, that's your own fault, mein Fräulein!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning: Greet ___',
      audio: 'VO_Fischl_Good_Morning_-_Greet_Fischl',
      text: 'Dusk and dawn but fleeting shadows are. Once more, the twists of fate have led you into my everlasting night.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning: Greet Oz',
      audio: 'VO_Fischl_Good_Morning_-_Greet_Oz',
      text: "Oz: Good morning. Mein Fräulein heard you'd be dropping by, so she's preparing breakfast.\\n___: Oz! ...Ahem. To what do I owe the pleasure?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: 'VO_Fischl_Good_Afternoon',
      text: 'Even one of royal blood finds oneself susceptible to drowsiness at this hour.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: 'VO_Fischl_Good_Evening',
      text: "___: The stars of firmament are naught but rifts, thrust open by Oz's beak into the boundless tapestry of darkness.\\nOz: You do say the strangest things, mein Fräulein.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: 'VO_Fischl_Good_Night',
      text: '___: Sweet shall be thy sleep, spared of the Mares of the Night! For no Night-Mares would dare draw near to those who are blessed by the Immernachtreich!\\nOz: She means, "Goodnight."',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Prinzessin der Verurteilung',
      audio: 'VO_Fischl_About_Fischl_-_Prinzessin_der_Verurteilung',
      text: "___: Me? Hehehe. Remember thou this, that I, ___, am the Prinzessin der Verurteilung, Sovereign of Immernachtreich, omniscient and eminent judge of all the world's iniquity!\\nOz: She's an investigator for the Adventurers' Guild.\\n___: ...Ahem. That is but one of my many royal engagements.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Beings Who Descended Upon This World',
      audio: 'VO_Fischl_About_Us_-_Beings_Who_Descended_Upon_This_World',
      text: 'Huh, you and I are both travelers from another world. That our paths have crossed here is no accident, but the will of fate.',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Shooting Down the World Beast',
      audio: 'VO_Fischl_About_Us_-_Shooting_Down_the_World_Beast',
      text: 'You seem... troubled. Traveler, do not lose heart! For with my left eye, the Auge der Verurteilung, which sees the threads of fate, I will surely keep you from harm. And Oz, the raven that has witnessed the demise of countless worlds, will watch over you on your journey. Should this world, like a beast prowling in the night, covet your dreams, then I, Prinzessin der Verurteilung, shall fell it with my ensorcelled arrows of judgment!',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Ones Dear to Heart',
      audio: 'VO_Fischl_About_Us_-_Ones_Dear_to_Heart',
      text: '___: Oz, my loyal companion. That we should have met this person, one who hails from another world as I do... Perhaps even cruel fate has deigned to smile upon me, though sin courses through my veins. If I am indeed destined to remain here, in this inescapable prison that is reality, at least—\\nOz: I understand, mein Fräulein! In this traveler, Fräulein has found one who will never forsake her.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: Standing Watch',
      audio: 'VO_Fischl_About_Us_-_Standing_Watch',
      text: "___: Ozvaldo von Hrafnavins. I, the Prinzessin der Verurteilung, sovereign of the Immernachtreich, do hereby call upon thee to do all within thy power to deliver the traveler from the claws of fate that would seek to snatch them at every turn, and to ready thy mind lest thou be required to make the ultimate sacrifice in the performance of this noblest of duties.\\nOz: ...You'd place my life in danger so easily, mein Fräulein?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About the Vision',
      audio: 'VO_Fischl_About_the_Vision',
      text: 'Oh? You inquire about my Edelstein der Dunkelheit? It is a royal heirloom, a ceremonial ornament that displays the majesty of the Prinzessin der Verurteilung before the unworthy. Even here, in this fallen world, I have been reunited with my rightful inheritance as one of royal blood and noble spirit, for the majesty of a true princess shall draw her royal heirlooms unto her wherever so she may roam.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share',
      audio: 'VO_Fischl_Something_to_Share',
      text: '___: If one must reckon time as this world does, I, ___, have already seen three thousand winters. Not that the illusory passage of time has any bearing on one such as I, to whom the causality of three thousand universes has been unveiled.\\nOz: Be that as it may, mein Fräulein, you are not yet considered to be of drinking age in this world, and no bartender can ever be convinced otherwise.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: 'VO_Fischl_Interesting_Things',
      text: "Oz's full name is Ozvaldo von Hrafnavins. Where I hail from, he holds dominion over star and sky across three universes, and the souls of the mighty, fallen in battle, rest in the shadow of his wings. One should add that the penalty for mispronouncing his name is to have one's tongue torn from one's mouth. However, as I am a princess and you are one who has my favor, we are at liberty to simply call him, \"Oz.\"",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Bennett',
      audio: 'VO_Fischl_About_Bennett',
      text: '___: Ah, the ill-starred young man... My Auge der Verurteilung has seen with unmistakable clarity how his heart ails at being forsaken by the world—\\nOz: Someone needs to keep an eye on the unlucky fellow.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Lisa',
      audio: 'VO_Fischl_About_Lisa',
      text: "___: The magus-custodian of books, gatekeeper of universal knowledge... Win her trust, and one may yet gain access to a vast repository of wisdom...\\nOz: She means as long as you return your first few library books on time, you'll never have any trouble borrowing a book again.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Kaeya',
      audio: 'VO_Fischl_About_Kaeya',
      text: "___: His nature is obscure, his fate a mystery, and his speech a vexing tapestry woven of both fact and fiction... Perhaps he and I share the burden of mystical sight...\\nOz: Or perhaps he's secretly an actual pirate?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Mona',
      audio: 'VO_Fischl_About_Mona',
      text: '___: Aha, yes, Mona, the mighty astrologer... Mona, who once had the vanity to probe the fate of the Prinzessin der Verurteilung herself! She wound up a trembling wreck, overborne and overmastered.\\nOz: The poor lass was trying desperately not to laugh. It was no easy task.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Rosaria',
      audio: 'VO_Fischl_About_Rosaria',
      text: '___: One finds Sister Rosaria to be a most devout believer in the Anemo Archon.\\nOz: ..."Devout believer," mein Fräulein?\\n___: Indeed! One night, I heard her invoking the name of the Archon thus in another\'s presence: "May you be struck down in the name of Lord Bartabos!" One presumed that she was leading a prayer.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About ___: I',
      audio: 'VO_Fischl_More_About_Fischl_-_01',
      text: 'To condemn the guilty, to sanctify the just, and to draw all castaway dreams into the embrace of the infinite Immernachtreich. This is the birthright of the Prinzessin der Verurteilung, and her burden. None may gainsay it.',
      tips: '',
      tasks: null,
    },
    '27': {
      title: 'About ___: II',
      audio: 'VO_Fischl_More_About_Fischl_-_02',
      text: 'My left eye? It is the all-seeing Auge der Verurteilung, which reveals all that is true in the world. As to the question of why I conceal it... Well, would you willingly bear the agony of piercing to the heart of all truths? Furthermore... the world would lose much of its appeal if wholly stripped of delusion and falsehood.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '28': {
      title: 'About ___: III',
      audio: 'VO_Fischl_More_About_Fischl_-_03',
      text: "___: Stormterror? Why, one never would have thought that a being that one might have kept as her pet could, in this world, be capable of causing such calamity. *sigh* Pitiable are the incompetents of this world...\\nOz: That said, mein Fräulein, were you not beside yourself with worry for everyone's safety during said calamity?\\n___: Th—That is because the Prinzessin der Verurteilung has the solemn duty to safeguard the souls of all, be they petty beings or not...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About ___: IV',
      audio: 'VO_Fischl_More_About_Fischl_-_04',
      text: "Oz: Some people address her by other names. But to me, the one who gave me life and bestowed my powers upon me is ___, and none other. All things considered, ___ is the name that most aptly captures her identity. Seriously, don't call her anything else, or—\\n___: Oh, how one's royal ears do burn! Pray tell, what is the matter which you discuss so furtively?\\nOz: Mid—Midnight Phantasmagoria, mein Fräulein! And... the majesty of the Verurteilung name!",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '30': {
      title: 'About ___: V',
      audio: 'VO_Fischl_More_About_Fischl_-_05',
      text: "Why must the Prinzessin der Verurteilung punish sin? Because sin defies fate's rightful decree, of course! ...And of course, fate brought you here, so, so... Ahem! It was fate that saw to your descent upon this world, destiny that saw our paths intertwined. I, ___, shall always protect you. Because... because fate has revealed to me that this is what has been decreed!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '31': {
      title: "___'s Hobbies: Ask ___",
      audio: 'VO_Fischl_Hobbies_-_Ask_Fischl',
      text: 'I, ___, have roamed the galaxy and traversed countless worlds. I have learned the fate of ten thousand universes and have had revealed unto me the destiny of every living soul.',
      tips: '',
      tasks: null,
    },
    '32': {
      title: "___'s Hobbies: Ask Oz",
      audio: 'VO_Fischl_Hobbies_-_Ask_Oz',
      text: 'Oz: Mein Fräulein reads a lot of novels. *sigh* My name, "Oz," is from one of her favorites.',
      tips: '',
      tasks: null,
    },
    '33': {
      title: "___'s Troubles",
      audio: 'VO_Fischl_Troubles',
      text: "What does it take to rile a princess? ...If you must know, it is those who cannot recognize my true identity. But it is no great loss, for solitude is the noble's lot, so long as I do not lose the nobility of my soul...",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Favorite Food',
      audio: 'VO_Fischl_Favorite_Food',
      text: '___: Hmph! What is food but the shackles of mortal flesh? ...But if the Prinzessin der Verurteilung should reckon any morsel worthy, then it must be the tears of sinners and the tongues of liars.\\nOz: Has mein Fräulein lost her appetite for the Mitternachtsbrot des Sommernachtgartens?\\n___: ...Uh— That is merely to provide mine earthly vessel with such sustenance as it doth require to perform its royal duties!',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Least Favorite Food',
      audio: 'VO_Fischl_Least_Favorite_Food',
      text: 'Oz: I believe I know the answer to this one...\\n___: Indeed you do, Oz! Ah, that poor mortal coil, mutilated by bondage unnatural...\\nOz: It will never again fly as I do...\\n___: Deprived of the humble coif with which it was born to gaze in awe at the majesty of its monarch... Surely it is a glimpse of my homeworld\'s hell, in the flesh. Hmm, the name of the dish escapes me...\\nOz: Something something "Madame," isn\'t it?',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Fischl_Receiving_a_Gift_-_01',
      text: '___: Such an exquisite delicacy is worthy of being served in the Garten Sanssouci.\\nOz: Mein Fräulein says that she thoroughly enjoys your delicious cooking.',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Fischl_Receiving_a_Gift_-_02',
      text: '___: To vanquish the Beast of the World, one must first rise above mundane desires, thus weaving the path that leads to destiny.\\nOz: And yet, on this occasion, you appear to have eaten your fill, mein Fräulein.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Fischl_Receiving_a_Gift_-_03',
      text: '___: Why dost thou insist on raining down chaos and destruction in the presence of your Prinzessin?\\nOz: Mein Fräulein does not care a great deal for this dish. My apologies.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Birthday',
      audio: 'VO_Fischl_Birthday',
      text: '___: Well! If today is truly the anniversary of your birth, it shan\'t do for me not to mark the occasion. You have my full attention. Speak! Speak to me of your wishes, that which you most desire to fulfill during your fleeting and harsh existence in this wretched world. Whatever that wish may be. Even if, perchance—\\nOz: She means, "Happy Birthday, and if you want, she can—"\\n___: Silence, Oz.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Fischl_Feelings_About_Ascension_-_01',
      text: "___: My magic arrow cries out my holy name as it streaks through the night, praying that the violet lightning of retribution shall strike the enemies of fate down from the skies!\\nOz: Quite awe-inspiring, mein Fräulein! Since it's nearly dinner time, perhaps you might shoot a pigeon down while you're at it?",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Fischl_Feelings_About_Ascension_-_02',
      text: '___: With this, I may more fully manifest my majesty as Prinzessin der Verurteilung, and defeat that sworn enemy of fate named "reality."\\nOz: It will also be of use in your work for the Adventurers\' Guild, mein Fräulein.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Fischl_Feelings_About_Ascension_-_03',
      text: 'Rejoice! Else, tremble in fear! Whenceforth springs this call to mirth and misery, you ask? Let it be known that I, the Prinzessin der Verurteilung, sovereign of the Immernachtreich, have peered forth with mine leftmost eye into the tapestry of fate that doth make up the universe, and beheld its every warp, weft and dangling orphaned thread!',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Fischl_Feelings_About_Ascension_-_04',
      text: 'I appear to have now regained most of the strength I lost in my transition to this world. Mwuhahaha, the day of judgment is nigh! ...Ah, worry not. Even at the last, when I bring the lightning of retribution upon this world, you shall come to no harm, for thou art blessed by the Prinzessin.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '___ is the Prinzessin der Verurteilung who arrived here after being exiled from the otherworld, "Immernachtreich."\\nShe "observes and weaves the threads of fate" together with her talking night raven familiar, Oz.\\nOwing to reasons she cannot and Oz will not explain, ___ now serves the Adventurers\' Guild as an investigator.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "As an investigator for the Adventurers' Guild, the single biggest advantage ___ has over her peers is Oz.\\n\"Milady, please stop sending me out to spy on Stormterror. That chap could eat me for breakfast! Well, I'm so puny I probably wouldn't even get caught between his teeth, but... Anyway, I don't want to die!\"\\n\"Hmph! You are supposed to be my familiar. Not everyone gets to be the Prinzessin der Verurteilung's familiar, do you understand? Consider it your honor to dedicate your life to serving me!\"\\n___ is able to see through Oz's eyes. Whenever she wants to, she possesses Oz and looks down upon the earth from the sky.\\nWhether she wants to inspect the flora on the Stormbearer Mountains or observe a disturbance in Wolvendom, through Oz she can see anything and everything.\\nThanks largely to her unique ability — and, to a lesser extent, to her own effort and peculiar personality — ___ quickly went from the rookie investigator of the Adventurers' Guild to a respected rising star of the organization.\\nShe's certainly done well for herself. She only landed the coveted position of Investigator at age fourteen in the first place because her parents managed to persuade the guild master.\\nThen again, would they really have had to do much persuading? If she's the Prinzessin der Verurteilung... one can only assume that would make them the Kaiser und Kaiserin der Verurteilung.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'It\'s said that there is currently a "___ Dictionary" in circulation among the adventurers.\\nNamely, a book that aims to translate ___\'s peculiar way of speaking into something more understandable.\\nFor example:\\n"I hear... echoing in the abyss of time, the burning winds of the old, all of which shape the spire forgotten in the torrents of karma" would translate into "Stormterror\'s Lair";\\n"Servants of the Verurteilung name! As you have requested, prepare to receive the great wisdom of the prinzessin" would be "I\'ll look into that and let you know ASAP";\\n"Rejoice! O, ye servants who long for the blessing of the prinzessin; venture now deep into the battlefield with hearts of the tiger" means that the initial investigative work has been completed;\\n"All has been written in this tome of dark prophecies" simply means that her journal has been updated with the latest reports.\\nHowever, the "___ Dictionary" is actually just an in-joke, not a real book.\\nThose who are familiar with ___ concentrate on what she means to say, not the way in which she says it; she notices this and takes it as a sign of true respect.\\n"Aha! So you do understand. Then fate does indeed bring kindred spirits together."\\nThose who manage to adopt her speech mannerisms when they respond to her will find she is both delighted and bashful, and praises their language-learning ability.\\n"A prinzessin should always give praise where praise is due... Now, let us converse some more. Do not be mistaken; these are to be the foundations of the new world..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Oz and Princess ___ are not only close friends but also servant and master, with a shared soul and fate.\\nTheir first encounter was mentioned in "Flowers for Princess ___ (I): End Time Zersetzung"\\nWhen the lone pilgrimaging princess reached the kingdom of eternal twilight, the fate-resisting royals chose to deny everything in their desperation.\\nThey refused to recognize ___\'s noble stature and mission as the princess of the Immernachtreich; denied their 13,000-year lineage as a branch of the royal family; and forsook their own nobility and restraints as humans... devolving into clumsy and vicious beasts.\\nIn the palace of Twilight and amidst the teeth of the beasts, the princess shed her sacred blood on the ancient emblem.\\nAt the moment of her peril, the dark wings of the night ripped the trapped, wounded princess from her despair and took her under its wings.\\nFollowing the scent of her noble blood, Ozvaldo Hrafnavins, the King of Ravens came to the princess and pledged his eternal loyalty.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'There is a story that goes as follows. A long time ago in a place far, far away, there was a tiny little girl.\\nThe girl\'s parents were busy adventurers. She spent most of her childhood in the library, traversing the countless universes that were contained in the pages of the library books.\\nShe became the ruler of the Immernachtreich, summoned Thundering Retribution as a royal princess, and formed a soul bond with a Raven...\\n...\\n"███, what books did you read today?" Her parents asked her on one of the rare occasions that they were home between adventures.\\nShe proceeded to tell them the story she had read from her favorite series.\\n"...And then he said, ___ von Luftschloss Narfidort, you are the Prinzessin der Verurteilung, my proud daughter. You shall never surrender your nobility and dreams.\'"\\n"Oh, that\'s a lovely story. Since you like it so much, ███, how about I call you "___" too?" Her father smiled, put his hand on her head and repeated the words from the story to her.\\n"___, you are my wonderful princess and my proud daughter. You shall never surrender your nobility and dreams."\\nThese kind and loving words lit up her world.\\nHowever, the time with her busy parents was always fleeting.\\nUnable to fit in with her peers due to her obsession with fantasy novels, she often felt lonely and sad. At these times, she would remind herself:\\n"I am ___, my daddy\'s wonderful princess. It\'s true, because Mommy and Daddy said so..."\\n"Never will I surrender my nobility and dreams, for they are... a princess\' rite of passage."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Just like in the universe of "Flowers for Princess ___," entropy begot destruction.\\nIn other words: The girl who loved to dream grew up.\\nOn her fourteenth birthday, those of her peers who refused to accommodate her quirks belittled her once again.\\n"This is but a minor setback for the noble princess. My parents will understand," she thought to herself.\\nFor if she knew one thing, it was that as a princess she could never surrender her nobility and dreams.\\nBut when she threw herself into her parents\' arms in need of comfort, she was met instead with gentle words of exasperation.\\n"███, you are fourteen years old now. It\'s fun to make-believe, but eventually you need to grow up and put your childish dreams behind you..."\\nAnd with that, the same voice that had once lit up her world now tore it apart.\\nThat day at midnight, she hid herself in the library she knew so well. She had a strange feeling that she was being watched... Suddenly, she heard an otherworldly flapping of wings.\\nSure enough, she looked up and her red, swollen eyes met with those of a night raven from another world.\\nWhat transpired afterwards is another story...\\n___ doesn\'t much like this story. Thinking about it causes her to feel suffocating pain and soul-devouring loneliness.\\nMaybe one day, this story will be written. But that would be ███\'s story, not ___\'s.\\n___ has but one identity: she\'s the Prinzessin.\\nAs long as she remembers this simple and perfect logic, with a little bit of nobility and a touch of kindness from others, nothing can ever hurt her.\\nThings are looking up for Prinzessin ___ these days — not only does she have Oz, but she has finally met a traveler who, just like her, comes from a different world...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Flowers for Princess ___: Phantasmagoria',
      title2: null,
      text: 'The novel series "Flowers for Princess ___" is available as a collectible set.\\nDue to the tiny numbers in circulation, it is a priceless commodity amongst loyal fans of the author.\\nBut no matter how elegant these works are aesthetically, their worldview remains incredibly bleak:\\nEvery good, bright and noble thing must eventually fall to inexorable entropic destruction, and the final destination of the universe is the realm-in-waiting of the Prinzessin, Immernachtreich.\\nThis is the fate of all worlds, of the universe, and all who live in it.\\nAnd the Prinzessin and her loyal companion, the "Night-Severing Raven Oz," Ozvaldo Hrafnavins, are the World Beasts who will swallow all dreams.\\nAt the very end, at the end of karma itself, she will grant all the gathered souls her benediction, and use her Thundering Retribution to cleanse all that is ugly and wicked.\\nThe Prinzessin will then set her own heart ablaze, and the universe shall be born anew in its immortal light.\\nBut before all this can come to pass, the Prinzessin must first roam many universes, and see countless new sights.\\nThus it is perfectly within the spirit of the original work that the Prinzessin should be stuck as an investigator for the Adventurers\' Guild in a slightly backward world. Just a little twist of fate, nothing more.\\nThe Prinzessin will come to understand someday that each moment of her life, no matter how insignificant their little twists could be, is to be treasured.\\nAfter all, the Prinzessin\'s very own Phantasmagoria is made out of ones such as these.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'So, is Oz just an imaginary friend who only exists as a figment of ___\'s subconscious?\\nOur story begins with the royal heirloom, Edelstein der Dunkelheit — that is to say, ___\'s Vision.\\nWhen her wish was acknowledged, the raven Oz and her Vision both appeared before her eyes.\\nThat night, at dinner, Oz got on most well with ___\'s parents:\\n"Ah, mein Kaiser und Kaiserin der Verurteilung, forgive mine overstep, but the beans in your house are too delicious."\\n"Oh, then please, help yourself. This is the first time little ███ has met a friend she can bring over for dinner since she turned fourteen. This is a special occasion."\\n"Wh—What are you saying! I... One does not simply cavort with the plebeians!"\\n—And that\'s what happened.\\nFor all intents and purposes, it seems that the Kaiser und Kaiserin der Verurteilung could both see Oz, and both believed Oz to be the Prinzessin\'s first friend.\\nAs for the "Adventurer Who Bears the World\'s Curses," the "Visitor From Outer Worlds" and the "Strange Fae-shaped Emergency Sustenance..."\\nThey would become the Prinzessin\'s new friends, though that would happen even further in the future.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
