export const lisaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Lisa_Hello',
      text: "Hi darling, are you going to be ___'s little helper? What? Me, a grand mage? That was a long time ago, I'm just a humble librarian now. *chuckles* Don't worry darling, I'll take very good care of you. So...",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Afternoon Tea',
      audio: 'VO_Lisa_Chat_-_Afternoon_Tea',
      text: "It's nearly time for afternoon tea.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Quest',
      audio: 'VO_Lisa_Chat_-_Quest',
      text: "Why not keep me company for a while... There'll be plenty of time for work later.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Better to Stay In',
      audio: 'VO_Lisa_Chat_-_Better_to_Stay_In',
      text: "Today's no good for going out... Hmm... Did I say that yesterday as well?",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Lisa_When_It_Rains',
      text: '*sigh* Perfect weather for sipping a cup of tea while gazing out the window.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Lisa_When_Thunder_Strikes',
      text: "When I practice my spells in weather like this, I can do half the work for double the impact. Haha, I'm just teasing.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: "When It's Windy",
      audio: "VO_Lisa_When_It's_Windy",
      text: "Such a calming breeze... Perfect for taking a nap, don't you think?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Good Morning',
      audio: 'VO_Lisa_Good_Morning',
      text: "*yawn* Good morning, Jean... Oh, it's you! Sorry, dear.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Afternoon',
      audio: 'VO_Lisa_Good_Afternoon',
      text: 'It must almost be time for a nap...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Evening',
      audio: 'VO_Lisa_Good_Evening',
      text: "You're still up? I'm getting sleepy...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Night',
      audio: 'VO_Lisa_Good_Night',
      text: "I can see how hard you've been working today. Let me think of a way to reward you...",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'About ___',
      audio: 'VO_Lisa_About_Lisa',
      text: "I'm not lazy, I just know to save my energy for when I need it most.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Us: Relationships',
      audio: 'VO_Lisa_About_Us_-_Relationships',
      text: 'I can be your teacher, your master, or your friend... or all three if you want...',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Capabilities',
      audio: 'VO_Lisa_About_Us_-_Capabilities',
      text: 'Let me show you a thing or two, lest we let your efforts go to waste. *chuckles*',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '14': {
      title: 'About Us: Ceremony',
      audio: 'VO_Lisa_About_Us_-_Ceremonies',
      text: "Wait, one last thing... A kiss on the forehead from master to follower. Now you're my star pupil.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: 'VO_Lisa_About_the_Vision',
      text: "Visions? Ah, they're a necessary device in controlling the elements — with you being the sole exception, of course. Hmm... As for why that is, perhaps... we can find the time to experiment a little?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: 'VO_Lisa_Something_to_Share',
      text: "Feel free to use the alchemist's upstairs from the library whenever you want. But make sure you knock first... we wouldn't want you seeing anything you're not supposed to, now would we?",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: 'VO_Lisa_Interesting_Things',
      text: "Calla Lilies are a medicinal flower with antidotal properties. With them in hand, there's no need to worry about the side effects of any potions... Hehe.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'About Jean',
      audio: 'VO_Lisa_About_Jean',
      text: 'Jean is a gifted and dedicated leader. Seeing how hard she works makes even me want to help her out.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'About Amber',
      audio: 'VO_Lisa_About_Amber',
      text: "Amber was just a young girl when she joined the knights, and in the blink of an eye, she's turned into such a strong young lady. I'm curious to see what she'll be like a few years from now.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Barbara',
      audio: 'VO_Lisa_About_Barbara',
      text: 'Have you heard Barbara sing before? Her angelic voice contains a magical healing energy. A different kind of magical energy from the one in my potions, of course. I wonder which one you prefer?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Diluc',
      audio: 'VO_Lisa_About_Diluc',
      text: 'You want to know about Diluc? Haha, in that case, I know someone else you should talk to.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Razor',
      audio: 'VO_Lisa_About_Razor',
      text: "Come on Razor, that's it, good boy! Let's do some combat practice — I've found you the perfect partner. Hey! Come back!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Klee',
      audio: 'VO_Lisa_About_Klee',
      text: 'Last time little Klee wanted to use my workshop for her experiments, I had to say no, and she was angry at me for the rest of the day. *sigh* What happened the next day, you ask? She went off happily to play outside of course.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Mona',
      audio: 'VO_Lisa_About_Mona',
      text: "As for Mona? She seems to be an excellent mage, but I'm not a part of their Hexenzirkel. The idea of Irminsul exploration and formal tea parties just leaves me cold.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Albedo',
      audio: 'VO_Lisa_About_Albedo',
      text: "Albedo is quite the alchemist. Just say the word and he'll come up with a good solution. He's easy on the eyes too, just like you.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Fischl',
      audio: 'VO_Lisa_About_Fischl',
      text: "Fischl, yes, she's always in the library looking to borrow fantasy novels. She always returns her books three days early and looks after them very well. She's a good kid.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Noelle',
      audio: 'VO_Lisa_About_Noelle',
      text: "Every time I ask Noelle to dust off the bookshelves, I'm always left with the sense that the more exhausted I make her, the happier she becomes. Yes, who knows what's going on with her... *chuckles*",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Sucrose',
      audio: 'VO_Lisa_About_Sucrose',
      text: "Try not to bother Sucrose if you're at a loose end, you'll only startle the poor girl. She's gifted at interacting with all sorts of exotic creatures — just hopeless when it comes to humans.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Cyno',
      audio: 'VO_Lisa_About_Cyno',
      text: "I've barely kept in touch with anyone from the Akademiya since leaving Sumeru, except for the occasional letters to my teachers out of basic courtesy. Fortunately, not every promising student turned out as lazy as I am... I heard that one of my juniors, Cyno, now leads quite the action-packed life.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Collei',
      audio: 'VO_Lisa_About_Collei',
      text: "Ah, dear little Collei. Every time she writes to me, she tries out new words and expressions she's learned recently... Hehe, no wonder she's improving so quickly. That wonderful and warmhearted master of hers must have helped a lot too.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Mika',
      audio: 'VO_Lisa_About_Mika',
      text: "I do rather envy Huffman for having such a caring little brother. Mika takes care of everything around the house and even looks after him when he's drunk... Ah, how nice it must be to lounge around all day without a care in the world... Hmm? What do you mean, I already do that? You're getting quite bold these days, aren't you, cutie?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About ___: I',
      audio: 'VO_Lisa_More_About_Lisa_-_01',
      text: 'So, which element would you like to learn about today?',
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'More About ___: II',
      audio: 'VO_Lisa_More_About_Lisa_-_02',
      text: "My past? So, you want to get to know me a little better, huh? *chuckles* That's a story for another day. But I'm touched that you asked.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '34': {
      title: 'More About ___: III',
      audio: 'VO_Lisa_More_About_Lisa_-_03',
      text: "When I taught Razor how to utilize Elemental Energy, I never expected him to master the technique so quickly. Come to think of it, you're talented too. Maybe I could teach you a few tricks...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '35': {
      title: 'More About ___: IV',
      audio: 'VO_Lisa_More_About_Lisa_-_04',
      text: "What's that? You want to learn some Sumeru Akademiya magic? I'm afraid it might be a bit too much for you to handle right now... Hmm, though I suppose it can't hurt to teach you some of the basics. Here, start by reading the beginner's guide, it's only 800 pages or so.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '36': {
      title: 'More About ___: V',
      audio: 'VO_Lisa_More_About_Lisa_-_05',
      text: "A Vision may seem like a great tool, but one day, the power one accumulates always finds a way to turn back on you. Should such a day come for me, so long as you're around... Ah, never mind.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '37': {
      title: "___'s Hobbies",
      audio: 'VO_Lisa_Hobbies',
      text: "Hey darling, would you like to try one of my magic potions? There's no knowing what it will do to you until you try it, though... Don't say I didn't warn you!",
      tips: '',
      tasks: null,
    },
    '38': {
      title: "___'s Troubles",
      audio: 'VO_Lisa_Troubles',
      text: "The interrogation room upstairs has sat there unused for two years now... It would be a much more lively place if Hertha would agree to let me use it as my private workshop... *sigh* She's such a spoilsport.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Favorite Food',
      audio: 'VO_Lisa_Favorite_Food',
      text: "I like making my own vegetable soup. I put a big bunch of vegetables into a cauldron and stir it with a long spoon. What does it taste like? Here, why don't you try it for yourself. Open wide!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Least Favorite Food',
      audio: 'VO_Lisa_Least_Favorite_Food',
      text: 'I suffer from extreme pumpkinphobia. The fall harvest is a difficult time of year for me, as you can imagine. I wonder if it would be worth the trouble to make all the pumpkins in the world disappear...',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Lisa_Receiving_a_Gift_-_01',
      text: "Oh aren't you just the sweetest? Thanks, cutie, you just made my day.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Lisa_Receiving_a_Gift_-_02',
      text: "Hehe, you've really got a knack for this, haven't you?",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Lisa_Receiving_a_Gift_-_03',
      text: 'Eugh... Oh my... This is really... hmm...',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Birthday',
      audio: 'VO_Lisa_Birthday',
      text: "Here, take this amulet, it will bring you good luck. It's my birthday gift to you. I spent a long time making it, so don't lose it now!",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Lisa_Feelings_About_Ascension_-_01',
      text: "Surely you don't want me working overtime... That would be no good.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Lisa_Feelings_About_Ascension_-_02',
      text: 'Chances to practice should be left to you newcomers, no?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Lisa_Feelings_About_Ascension_-_03',
      text: '*chuckles* If I were to recover my full power, who knows what kind of things might happen?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Lisa_Feelings_About_Ascension_-_04',
      text: "I've already tried to persuade you every way possible... *sigh* Have it your way, cutie. I can no longer go on pretending at this point — even a Hilichurl would see through the act. So be it, let me introduce you to the true Witch of Purple Rose.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "The librarian of the Knights of Favonius. In addition to her elegance and charm, ___ is also highly educated.\\nShe is said to have been the most talented sorceress to study at the Sumeru Akademiya in the last two centuries.\\nIt is known that ___ chose to return to Mondstadt after two years of advanced study in Sumeru, but the reason for her decision is not. At present, ___'s job is to oversee the book collection in the library owned by the Knights.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '___ is tasked with managing and maintaining the vast collection of books in the Knights of Favonius library, as well as ensuring that their potions are always fully stocked.\\nThe only time that the citizens of Mondstadt see ___ is when lending or returning library books.\\nIn both scenarios, they tend to encounter ___ sitting at the counter like a languid cat, yawning as she signs books in and out.\\nAt times, her behavior causes people to doubt whether she is really up to the task of being librarian for the illustrious Knights of Favonius.\\nNevertheless, it appears that she performs every task flawlessly, as her work consistently stands up to scrutiny.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'The fact that Cyrus of the Sumeru Akademiya frequently refers to ___ as their "best student in two hundred years" is all that needs to be said about ___\'s accomplishments in her studies.\\nFrom outlandish forbidden knowledge, to the handling of elementally infused flora, to the most efficient methods of distilling wine... where there is a body of knowledge, the chances are that ___ is acquainted with it.\\nThis, paired with her ability to explain things clearly and concisely, makes ___ the sensible person to approach for young knights and alchemists with burning questions.\\nThat is, provided they go and see her at an acceptable hour.\\nTo visit during unacceptable hours — such as in the morning while ___ is sleeping in, or in the afternoon while she\'s enjoying her tea — can spell disaster for unsuspecting visitors.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'When people meet ___ for the first time, they often find themselves overawed by the famous alumna of the Sumeru Akademiya.\\nHowever, though her attitude to life may appear at first to be one of ruthless efficiency, it is in fact better understood as a product of her incorrigibly lazy nature, which drives her to avoid troublesome issues at all costs.\\nBy negotiating with Kaeya, she offloaded the job of restocking and dispensing medication to Huffman and Swan, and had Flora start sending Donna over to deliver herbs on a daily basis.\\nThe only tasks that ___ handles personally are the categorization and management of books and other documents.\\nThis is the one area where ___ feels more comfortable handling the work herself rather than delegating it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'When ___ first joined the Knights of Favonius, the Grand Master sought to appoint her as Captain of the 8th Company.\\nThis was much to the consternation of the company\'s Field Officer, Nymph, who resented the idea of an academic coming in at such a high-ranking position.\\nAt Kaeya\'s suggestion, a practice combat session was arranged in which ___ and Nymph would both display their magical proficiency.\\nTwo minutes into the session, ___ graciously declined the captaincy on the grounds that "Nymph manifestly possesses the requisite ability to fulfill the role."\\nFor the whole year following, the Grand Master received a constant stream of referral letters from Nymph in relation to the captaincy, and the only person ever named in them was ___ Minci.\\nEventually, the Grand Master began turning over the referral letters to ___ directly, but every time, ___ would come up with an excuse to decline the offer.\\nUndoubtedly, the 8th Company would have been far stronger under her lead, but she deemed that such a level of power was not only superfluous to requirements, it would also be risky for her in a way that most people could never appreciate.\\nTo be clear, ___ is quite confident that she could handle any situation she came up against. However, additional danger means an additional workload — and that is something that she would never be able to accept.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Having personally witnessed raving-mad scholars in the forests of Sumeru and powerful sages sitting underutilized on advisory councils, ___ realized what uninhibited erudition can really do to a person.\\nIt seemed such a high price to pay... How much did one have to sacrifice to attain the profoundest knowledge of all?\\nPut off by this realization, ___ decided to leave Sumeru.\\nSince then, ___ has always stopped short of taking things too seriously.\\n"Before demanding too many miracles from the gods, first consider if you are willing to pay the price they ask."\\nThese words she has spoken to just three people since arriving in Mondstadt. In each case, it was because she knew it was what they needed to hear.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Special Heating Cauldron',
      title2: null,
      text: "The Special Heating Cauldron is a purpose-built cauldron made to a design that no one in Mondstadt could understand. It features time-delay heating, semi-automated ingredient insertion, and temperature regulation functions.\\n___ spent an enormous budget and commandeered the alchemy workshop for two full weeks in order to build this extraordinary piece of equipment.\\nShe boasts that the cauldron is capable of completing any precision heating task to perfection with a maximum of just two pulls of a lever.\\nBut her most common application for it is to brew tea and keep it at the optimal temperature while she is managing her books.\\nAfter all, a relaxing afternoon tea session is by far the most important part of ___'s day.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'A Vision is a sign from the gods: a sign that you are one of those whom they have chosen to change the world.\\nOr, maybe it\'s just one of the many hoops that one has to jump through on the path to unearthing the secrets of magecraft.\\nAfter all, understanding the elements is essential to the study of magic, and practical experience is a far more useful means of acquiring this understanding than trying to assimilate the knowledge contained in dusty old books.\\n"Hmm... I suppose I shall need a Vision, then."\\nAnd just like that, as that thought popped into her mind, her Vision popped into her hand.\\nWith the aid of her Vision, ___ acquired the knowledge that she sought. But she also sensed the deep secret hidden in the shadows of that knowledge.\\nFor whatever reason, the gods gave humans the key to changing everything, but they did not explain the cost involved. ___ grew fearful of the truth.\\nThe Vision that hung from her neck became to her a bottomless pit filled with sweet delights, lingering at the back of her mind.\\nSo, from time to time, when somebody whom she finds interesting comes along, ___ will pass onto them her understanding on all kinds of matters.\\nPerhaps she is secretly hoping that by doing so, one day someone will come along who has the ability to understand the ultimate truth behind Visions.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
