export const amberVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Amber_Hello',
      text: 'Outrider ___ reporting for duty! Just say the word if you ever need my help!',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Hobbies',
      audio: 'VO_Amber_Chat_-_Hobbies',
      text: 'I feel like running.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Longings',
      audio: 'VO_Amber_Chat_-_Longings',
      text: 'Jean will be upset if she catches us lazing around like this.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: New Discoveries',
      audio: 'VO_Amber_Chat_-_New_Discoveries',
      text: "Hey, there's something strange over there... C'mon, let's take a look!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains: Worries',
      audio: 'VO_Amber_When_It_Rains_-_Worries',
      text: "Oh no, it's raining... now my uniform will get all wet...",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Rains: Reminder',
      audio: 'VO_Amber_When_It_Rains_-_Reminder',
      text: "It's raining again... This will hinder our vision, we must remain vigilant!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'After the Rain',
      audio: 'VO_Amber_After_the_Rain',
      text: 'Wow~ This weather is awesome!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: 'VO_Amber_When_the_Sun_Is_Out',
      text: 'If only the wind was a little stronger...',
      tips: '',
      tasks: null,
    },
    '8': {
      title: "When It's Windy: Pleasant",
      audio: "VO_Amber_When_It's_Windy_-_Pleasant",
      text: 'This breeze... so refreshing!',
      tips: '',
      tasks: null,
    },
    '9': {
      title: "When It's Windy: Relax",
      audio: "VO_Amber_When_It's_Windy_-_Relax",
      text: 'I love this kind of weather, ahh... so relaxing~',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Morning',
      audio: 'VO_Amber_Good_Morning',
      text: 'Morning! Want to go on a jog?',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon',
      audio: 'VO_Amber_Good_Afternoon',
      text: 'Can I get lunch with you?',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: 'VO_Amber_Good_Evening',
      text: "It's getting late, should I light a torch?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: 'VO_Amber_Good_Night',
      text: "Agreed, getting rest is essential! Let's meet here tomorrow then. See ya!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___',
      audio: 'VO_Amber_About_Amber',
      text: "Mondstadt Gliding Champion, yep, that's me! Gliding Champion!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Contests',
      audio: 'VO_Amber_About_Us_-_Contests',
      text: "Remember that I don't go easy on anyone, even you!",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Gliding',
      audio: 'VO_Amber_About_Us_-_Gliding',
      text: "When I'm teaching you to glide, I feel like I can go even faster than usual... Huh? What are you laughing at? I'll prove it! We can race — right now!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: 'VO_Amber_About_the_Vision',
      text: 'My Vision... Is a sign that the Archons believe in me. Yes, I must become the best Outrider I can possibly be!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: 'VO_Amber_Something_to_Share',
      text: "The view from the Cathedral's clock tower is amazing! You should check it out.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: 'VO_Amber_Interesting_Things',
      text: "Look, there's a pigeon over there! *giggle* I wish I could fly alongside them.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Jean: Help',
      audio: 'VO_Amber_About_Jean_-_Help',
      text: 'After the Grand Master left on his expedition, all the affairs of the Knights of Favonius, both big and small, have been left up to Jean. If only there was more I could do to help her...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Jean: Care',
      audio: 'VO_Amber_About_Jean_-_Care',
      text: "Jean might still be working? We should invite her for coffee... Let's go.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Lisa: Listening to Stories',
      audio: 'VO_Amber_About_Lisa_-_Listening_to_Stories',
      text: "When you have time, we should go see Lisa! Last time I saw her, she was telling me about a story involving a treasure in the Dragonspine area. But, we got cut off before she could finish. I can't wait to hear the rest of her story!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Lisa: Admiration',
      audio: 'VO_Amber_About_Lisa_-_Admiration',
      text: "If Lisa's not sleeping, she'll be reading! I don't know how she does it, I wouldn't be able to sit still for that long.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaeya: Concerns',
      audio: 'VO_Amber_About_Kaeya_-_Concerns',
      text: "...I'm feeling uneasy all of a sudden! Was that Kaeya with you earlier? Did he give you any trouble?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Kaeya: Culprit',
      audio: 'VO_Amber_About_Kaeya_-_Culprit',
      text: "There's something weird-looking about the dandelions in the garden... Hmm, I bet Kaeya had something to do with this!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Bennett',
      audio: 'VO_Amber_About_Bennett',
      text: "Hmm? Bennett... I feel like I've heard that name before... Oh! Yes, he's that hot-blooded guy from the Adventurers' Guild, right! I tend to come across him way out in the wild from time to time, he seems to really love treasure hunting.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Klee',
      audio: 'VO_Amber_About_Klee',
      text: 'Klee? She can be a bit cheeky sometimes, but everyone in the Knights of Favonius likes her. Although... I really ought to keep a closer eye on her if I wanna keep her from getting put in confinement by Jean again.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Albedo',
      audio: 'VO_Amber_About_Albedo',
      text: 'Albedo spends most of his time in his workshop, tinkering away with all of his awesome stuff. But, when you see him in person, you can never quite tell what he is thinking, not a clue at all.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Noelle',
      audio: 'VO_Amber_About_Noelle',
      text: "You wanna know about Noelle? She's super resilient. Still, since she's younger than us, we should look out for her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Eula',
      audio: 'VO_Amber_About_Eula',
      text: "Eula is a great friend of mine! You just need to get used to her sense of humor and you'll get along fine! The only reason she's misunderstood by so many people is her family name. How can I get them to see her for who she really is?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Collei',
      audio: 'VO_Amber_About_Collei',
      text: "Collei wrote to me saying that her Eleazar has been completely cured... I'm so happy for her! I wish I could fly to her side right now and give her the biggest hug! She also said she misses everyone in Mondstadt, and that once she's ready, she'll come visit us in person and tell us all about her progress... Oh, it would be great if she could make it in time for the next Ludi Harpastum. Aaah I can't wait to see her again!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '32': {
      title: 'About Mika',
      audio: 'VO_Amber_About_Mika',
      text: 'Oh! Mika\'s a veteran of Eula\'s team. When he first arrived, it was always "Yes, Commander!" every time he spoke to me — I guess it must have been because he saw how close I was with Eula. But then, even after I told him I was actually an Outrider, he still called me "Ma\'am"... It was so embarrassing. We have completely different responsibilities, after all. I definitely could never match his expertise in cartography.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: I',
      audio: 'VO_Amber_More_About_Amber_-_01',
      text: "I'm a pro at hunting, you know! How about I show you some of my skills? Or even better... how about a little competition?",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'More About ___: II',
      audio: 'VO_Amber_More_About_Amber_-_02',
      text: "I'll share my ultimate Gliding Champion secret with you! The most important thing to remember, is to have courage!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '35': {
      title: 'More About ___: III',
      audio: 'VO_Amber_More_About_Amber_-_03',
      text: "I'm really not that good with riddles. I always try to avoid the riddles stand during Ludi Harpastum... What about you?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '36': {
      title: 'More About ___: IV',
      audio: 'VO_Amber_More_About_Amber_-_04',
      text: "I joined the Knights because of my grandpa, I stayed because of Jean. And now, you're the one that showed me the world beyond Mondstadt. I couldn't be happier.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '37': {
      title: 'More About ___: V',
      audio: 'VO_Amber_More_About_Amber_-_05',
      text: "I would like to explore the other worlds beyond. I wanna see how deep the rabbit hole goes! You'll keep me company, right?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '38': {
      title: "___'s Hobbies",
      audio: 'VO_Amber_Hobbies',
      text: 'Baron Bunny, today is another squeaky clean day!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: "___'s Troubles",
      audio: 'VO_Amber_Troubles',
      text: 'Oh... Do you have any idea how to make a decent Moon Pie?',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: 'VO_Amber_Favorite_Food',
      text: "Jean makes the most amazing cup of coffee! You'll have to try it sometime.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: 'VO_Amber_Least_Favorite_Food',
      text: "I can handle anything and everything! As long as it isn't cold Wolfhook juice... Ugh, yuck...",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Amber_Receiving_a_Gift_-_01',
      text: "Wow! This is delicious, you're an amazing cook!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Amber_Receiving_a_Gift_-_02',
      text: 'I wish I was as good at cooking as you...',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Amber_Receiving_a_Gift_-_03',
      text: "Uh, I'm just not used to this taste, sorry! Nothing to do with you of course!",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: 'VO_Amber_Birthday',
      text: 'Hey, happy birthday! Here, I have a gift for you: an exclusive, custom-made version of Baron Bunny that I sewed for you myself. Uh... don\'t worry, "custom-made" means that it won\'t explode!',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Amber_Feelings_About_Ascension_-_01',
      text: 'Yeah! As fast as riding the wind!',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Amber_Feelings_About_Ascension_-_02',
      text: 'At this speed, no one can keep up with me!',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Amber_Feelings_About_Ascension_-_03',
      text: 'The skies over Mondstadt seem to have gotten smaller... or is it that my sight reaches further than ever before?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Amber_Feelings_About_Ascension_-_04',
      text: "It seems that now... I've improved so much compared to when we first met! Hehe, thank you so much! Let me treat you to a Sticky Honey Roast! Let's go, let's go!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "___ is an Outrider of the Knights of Favonius. In an age where Outriders are becoming obsolete, she continues on with her responsibilities.\\nIt takes a newcomer only a few days to feel right at home with this passionate girl.\\nWhether it's before the Good Hunter's signboard, the banks of Cider Lake, or the tree tops at Windrise, one can find traces of this vigilant Outrider in red anywhere. \\nOnce spotted by her, no suspicious individual can ever escape her interrogation.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "From a young age, ___ has always had boundless energy and a positive outlook on life.\\nEach day, she burns with a fiery enthusiasm that sees her go about her life like a whirlwind, smashing through any obstacle that stands in her way.\\nAt times, however, her excessive energy can make her quite the troublemaker.\\nNeedless to say, she was quite a handful when she was young. Her infamous deeds include accidentally dropping a bird's nest on her grandpa's head while trying to steal the eggs from it and setting a Dendro Slime's leaves on fire, causing it to scurry about like a wild animal. These minor offenses gained her some notoriety among hunters' camps.\\nSomehow, ___ was always able to escape the scene of the crime whenever she caused an incident, and not even a veteran Outrider could catch up with her. Invariably, it was ___'s grandpa who ended up on damage control duty each time his granddaughter's misbehavior caused yet another incident.\\nTo ___, her grandpa's silent, unconditional love was like a warm breeze that wrapped around her like a blanket. She knew that it was because of this love that he accepted her and took responsibility for her deeds, and she embraced it silently.\\nBut it was only on the day that her grandpa resigned from the Knights of Favonius that she finally understood the full extent of the responsibility he had borne all those years.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "___'s grandpa was once the leader of a mercenary group. He came from Liyue Harbor and was tasked with protecting merchant caravans as they traversed Teyvat. One day, on a routine escort job, the caravan fell prey to a savage monster attack. He was the only survivor, saved by a doctor from the Knights of Favonius.\\nToo ashamed to return home and anxious to repay the debt, ___'s grandpa joined the Knights of Favonius.\\nBefore long, he single-handedly founded the Outriders, trained each one of them personally, and began leading them on missions.\\nIt also wasn't long before he found love in the foreign land of Mondstadt and started a family.\\nYears later, ___ was born into that family. During the day, she would crouch by the window and secretly watch him training the Outriders. At night, she would sneak into the yard and practice the moves he had taught that day.\\n___'s grandpa was touched by her enthusiasm, and decided to teach her everything he knew.\\n\"When Mondstadt accepted me, it became my homeland. Then, I decided to watch over this new home of mine. Maybe one day, you will inherit this responsibility... Hah, but then, who knows what the future holds?\"\\nAs the coarse skin of her grandpa's palm rubbed against her head, a bewildered but earnest ___ nodded energetically in response.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Something happened one day four years ago that profoundly changed ___.\\nThat day, her grandpa left his coat of arms and sword in his office and simply disappeared, leaving no note and telling no one he was leaving.\\nHe had been the beating heart and the backbone of the Outrider division, and without his leadership they rapidly became undisciplined and lost their edge.\\nA few failed operations later, the Outrider division was facing obsoletion. In the end, it was preserved as a part of the Knights' organization, but in name only. Experienced members either transferred to another detachment or resigned, and so few outriders stayed that they simply did not have enough people to fulfill their daily patrol duties.\\nOn top of this, rumors that ___'s grandpa had defected made recovery even more difficult for the struggling Outrider division.\\n___ personally experienced this entire episode, having just been admitted to the Outriders before it all began. With the decline of her squad, she experienced true loss and disappointment for the first time in her life. No longer her carefree former self, she was filled with a new determination: She was going to grow up and become a true outrider as quickly as possible, no matter what it took.\\nShe had never made an actual plan before, and lacked the maturity to know where to start. But what she did have was confidence and courage — and lots of it.\\nShe wanted to show she had inherited her grandpa's determination, and she wanted to find out where he had gone.\\nBut more importantly, she wanted to inherit her grandpa's former role and become a loyal protector of her homeland.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Life in the Knights of Favonius was not easy for ___ in the beginning.\\nBeing as young as she was and having just lived through the trauma of losing her grandpa, the senior knights made a point of taking special care of her.\\nHowever, for a girl as desperate to excel as she was, being taken care of by others implied that she wasn\'t yet mature enough to stand on her own two feet.\\nAccordingly, she voraciously sought out extra responsibilities and made this as visible as possible to her seniors.\\nFinally, during an intense engagement with some monsters, the seniors noticed her bravery and resourcefulness in the heat of battle.\\nThat was the moment when they realized that their little girl was growing up.\\nAs she matured, she also became more at ease with herself. Whatever feedback she met with, be it praise, rebuke, silence, or taunting, her response was always the same.\\n"For sure, I may still have a way to go before I catch up with my seniors. But one day, I\'m gonna be the best Outrider ever!"\\n___ is not prone to too much deliberation, preferring instead to speak her mind, truthfully and frankly, at every occasion.\\nShe firmly believes that she will not disappoint her grandpa.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Today, ___ is still the firecracker she always was, burning with endless passion and energy.\\nNow that she\'s all grown up, ___ holds firm to her grandpa\'s teachings as she spreads her Wind Glider\'s wings and watches over the City of Freedom with the eye of an eagle and the cautious cunning of rabbit.\\nThe "Crimson Knight" is known throughout Mondstadt.\\nThe people are delighted to see the mischievous little girl they remember growing up to be a guardian they can rely on.\\n"Never fear, Outrider ___ is here!"\\nHer self-confidence is simply unshakable:\\n"I am Outrider ___, the one and only Outrider — which makes me the best one out there!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "___'s Journal",
      title2: null,
      text: "___ doesn't make writing a daily diary a habit, only electing to write special or memorable events down in her journal.\\n\"I finally caught that magical bird! It's called a Rami... something. I don't remember. But I've been chasing it for three days, and I've only been able to sit down for a proper meal today. That magical bird was a really cunning one, burrowing in the thick forest like that. Good thing I didn't give up! Best of all, Master Jean gave me special permission to pluck a feather plume from it as my reward. Hehe, I'll wear it at my side every single day!\"\\n\"I'm sure I followed the cookbook to the letter and grilled the meat for six minutes. But while the outside is charred, the inside isn't cooked yet... Did I not control the heat properly? But I really am hungry, so I'll just have to try again tomorrow. One day, I'll make the best steak, and I'll call it... the Outrider's Champion Steak!\"\\n\"I met a strange outlander today. I was suspicious at first, but as it turns out, this outlander is both reliable and capable. Ugh, come to think of it, what would I do if an enemy that strong showed up? ...I musn't fall behind. I must train harder!\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '___ once believed that if she took on her grandpa\'s post, she would understand why he left Mondstadt.\\nHowever, even when she officially became an Outrider, she was no closer to unraveling the mystery behind his wordless departure.\\nHer grandpa had left nothing for her to find either, indicating that she would have to forge her own path.\\n___ floundered for a while, until she flipped through an old book of fables that she would eventually come to treasure.\\n"What you lacked was not wind, but courage. It is courage that has allowed you to become the first flying birds of this world."\\n___ realized that she shouldn\'t wait for directions from someone else, but that she should be like those courageous birds that spread their wings and flew into the blue skies.\\n"There must be something that only I can do. There must be."\\nThe moment she realized this, a Vision began to shine brightly at her hip.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
