export const dilucVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: '___, of Mondstadt. Not interested in idle chit-chat. If you have things you want to get done, let me know.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Relax',
      audio: '1101',
      text: 'Guess we can rest a bit.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Knights of Favonius',
      audio: '1102',
      text: 'You should really bring the Knights of Favonius with you next time.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Wine Guild',
      audio: '1103',
      text: 'I still have a lot to do at the Guild. How about you take a rest while I go back?',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'Chat: Preparation',
      audio: '1106',
      text: 'We should prepare while we can, then make a preemptive strike against the enemy.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'Chat: Planning',
      audio: '1107',
      text: "Let's take a moment to rest and plan our next move.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'Chat: Warning',
      audio: '1108',
      text: 'Every course of action has its risks. Be careful.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Rains: Umbrella',
      audio: '1201',
      text: "I don't need an umbrella, but you can use one if you need.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When It Rains: Cleansing',
      audio: '1202',
      text: 'Rain... If only it could cleanse the corrupt souls of this world.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: "Listen, as long as you stick to your own path, it doesn't matter what Mother Nature throws at you.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: "Some use the wind's whistling to drown out the sound of their crimes.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Morning',
      audio: '1001',
      text: 'No need for small talk. All that matters is that you were safe last night.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'Would you like to try the secret menu?',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Night has fallen.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'Good Night',
      audio: '1004',
      text: "Alright, see you next time. I'll make sure you leave safely.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About ___',
      audio: '2001',
      text: 'The legend of the "Darknight Hero"? An interesting rumor.',
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Needs',
      audio: '2002',
      text: 'Just say the word if you need anything. For reimbursements, ask Elzer.',
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'About Us: Proof',
      audio: '2003',
      text: 'You have already proven your determination. Well then, it is now time for you to witness my resolve.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About the Vision',
      audio: '3001',
      text: 'Visions are a light in the sea of darkness that surrounds those who have lost their way. But for those who have faith, they are little more than badges of conviction.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share',
      audio: '3002',
      text: "Occasionally I'll work the bar at Angel's Share. The tavern is known for being the center of information in Mondstadt.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "What? Why do you ask? ...It's an owl, quietly watching its prey from the darkness, waiting for the perfect moment to strike... Flawless.",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Kaeya',
      audio: '4001',
      text: 'Kaeya? You can only trust half of what he says... at best.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Lisa',
      audio: '4002',
      text: "I believe Lisa has the potential to become the most reliable of the knights. If she's willing.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Jean: Enemies',
      audio: '4003',
      text: "Trifling matters can become Jean's greatest enemy.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Jean: Responsibilities',
      audio: '4004',
      text: "Her unparalleled sense of responsibility is the sole reason why she still hasn't found her true calling.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Mona',
      audio: '4005',
      text: "The land of Mondstadt, by the Anemo Archon's grace, is bountiful. I see no need for the harvest forecasts of astrologers.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Diona',
      audio: '4006',
      text: "Diona's attitude towards me is... how should I put it? Rather rigid. I've yet to find the opportunity to speak with her properly. I'm not sure if it's an issue with my family line or— Oh? It's not? She simply despises alcohol? Huh... I never thought I'd come across another bartender like myself in Mondstadt.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Varka',
      audio: '4008',
      text: "Grand Master Varka... While I understand his disposition, I can make no sense of his actions. ...I—I've said too much already. I've long since left the Knights of Favonius. Forget I said anything.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Eula',
      audio: '4009',
      text: "Ah, yes... I've heard about her. She has her own convictions. Her determination to liberate herself from the shackles of her clan is praiseworthy. But, she's... joined the Knights of Favonius.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About ___: I',
      audio: '5001',
      text: 'You have business to attend to?',
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'Huh? Knights of Favonius? ...I have nothing to say about them. We have different views is all.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About ___: III',
      audio: '5003',
      text: "It's been a long while since I played chess with anyone but my butler. I just so happen to have a moment. Care to play a round?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Checkmate! ...Still, it's been a while since someone tested me this much.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About ___: V',
      audio: '5005',
      text: 'Not bad. Be it chess or combat, you always seem to surprise me. Hm, working with you is quite the novelty. So... I look forward to continuing to work with you, partner.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "The artwork in the manor? It's not mine. It's a collection that belonged to my late father.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "___'s Troubles",
      audio: '6002',
      text: 'The darkness that seethes with evil, full of demons that must be vanquished, will take more than a blade to be torn asunder.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6003',
      text: "You want to know what's in my glass? It's... grape juice. My drink of choice.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I don't like alcohol. It's just... I don't like how it feels in my mouth...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Exquisite. Unforgettable flavors.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'I can see the chef put their heart into this one. A fine dish.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: '...Umm, thanks.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: 'Happy birthday. This is an important day for you. So tell me, what is it you wish for? If it is within my power to bestow it upon you, I will give it my consideration.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Power is necessary if we are to meet our objectives.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'What lies in wait for us? I rarely stop to think about it.\\nNo matter what dares to stand in my way, I must press forward.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "I've become stronger... Though it is still not enough, I will always face the darkness.\\nFor dawn to come, there must be those who dare to pierce the darkness with their light.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'I used to believe... if I was to stamp out evil, I would have to walk alone in darkness. However, seeing your perseverance, I know I was wrong. Friend... I owe you my thanks.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Hmph.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Hah!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Haah!——',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: I',
      audio: '100010',
      text: 'Huh!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: II',
      audio: '100011',
      text: 'Hyah!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: III',
      audio: '100012',
      text: 'Haah!—',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Your verdict is...!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Burn!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Time for — retribution!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: I',
      audio: '200010',
      text: 'Flames, purge!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: II',
      audio: '200011',
      text: 'Lay waste to the wicked!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Elemental Burst: III',
      audio: '200012',
      text: 'Dawn, break forth!',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Hmph, better than nothing.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'I suppose this will do.',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "We'll need more where that came from.",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Is that all you've got?",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Darn you!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'You will pay for that!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Careful!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Don't burn yourself out! Retreat!",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Where did I go wrong...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'There can be no excuse... for defeat...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'My flame... has been... extinguished...',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Urgh!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Let's go.",
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "What's our objective?",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Let's finish this, swiftly.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "As the city of ballads and wines, Mondstadt's alcohol industry is renowned all over Teyvat.\\nAs owner of the Dawn Winery, ___ is essentially in charge of half the industry. This means he has a huge stream of revenue and an entire network of information, in the form of tavern patrons' gossip, right at his fingertips.\\nIn a way, he is the uncrowned king of Mondstadt.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'The scent of wine always lingers in the air in Mondstadt.\\nIf one were to follow the scent to its source, one would invariably arrive at ___\'s Dawn Winery.\\nA wooden plaque proudly announces the winery\'s name, and beneath it is written the winery\'s motto:\\n"Shine True."\\nMost interpret this to mean that the wines are brewed for consistency of taste, with time-honored techniques and that same healthy dose of sunny optimism that the dawn brings.\\nMeanwhile, the more pragmatic Knights of Favonius are reminded of the long history of mutual support between the winery and the city.\\nThe winery holds festivities from time to time. These events are routinely attended by enthusiastic fathers, eager to introduce their wonderful daughters to the young and single winery master.\\nThis is all highly entertaining to the other guests, who watch on and comment, mockingly:\\n"We\'d much rather Master ___ stays married to the winery, given how good this wine is!"\\n___ deals impeccably with all situations, no matter who or what comes his way.\\n___ is a fine young gentleman in every conceivable respect.\\n',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "___ avoids talking about the past.\\n\"If only ___ were still a member of the Knights...\"\\nAfter a few drinks, senior knights will say words to this effect with a sigh.\\nThey refer to events from a long time ago, back when ___'s father, Master Crepus, was still the owner of the winery. Master Crepus' wish was for his son to become the most esteemed knight of all and safeguard Mondstadt, the City of Freedom.\\nAs per his father's wishes, ___ trained rigorously to make himself worthy of the Ragnvindr name. Sure enough, he passed the Knights of Favonius' trials, swore the oath of protection to Mondstadt, and entered their ranks. Before long, he received an early promotion which saw him become the youngest-ever Cavalry Captain.\\nOver the course of his missions and patrols, the denizens of Mondstadt gradually came to know this young and passionate Cavalry Captain.\\nNo matter what the missions demanded from him, he always maintained his composure and his passion. No matter how big the challenge before him, his boundless courage always led him to the front line. The praise he received from his comrades and citizens spurred him on.\\nBut the words of praise he valued most of all were:\\n\"Good job. Now, that's my son.\"\\nHis father's words fueled the fire inside his heart and served as his greatest motivation.\\nHis faith was an unquenchable fire that burned strong and bright inside him.\\n___ was so young back then.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "\"Sometimes, life can change in an instant.\"\\nThe day that Crepus spoke these words to ___ would turn out to be the latter's last as a Knight of Favonius.\\nFor on that day, a horrific monster attacked the transport fleet he and his father were traveling with.\\nThere was no time for ___ to send for help. The monster was stronger than any foe the young Cavalry Captain had ever encountered, and overpowered him.\\n___ could never have anticipated the way this battle would end: His father, who had been denied admittance into the Knights and who was shunned by the gods, defeated the monster with an unknown evil power — before that same power backfired, mortally wounding Crepus himself. Crepus died shortly after in his son's arms.\\nWith a heavy heart, ___ returned to the Knights' headquarters, only to receive an unthinkable order from Inspector Eroch: \"Conceal the truth.\"\\nEroch insisted that the incident must be portrayed as an unfortunate accident in order to maintain the reputation of the Knights of Favonius in the eyes of the public.\\nSuch was the sheer outrageousness of this request that ___ did not think it was even worth trying to argue.\\n___'s father had once said to him that the world would never turn its back on the faithful.\\nBut now, the Knights of Favonius trampled on his faith like it was nothing. He couldn't help but wonder: What was his father's view on faith in his final moments?\\n___ resigned from the Knights that day and left everything behind, including his Vision.\\nHe swore to avenge his father's death, and to find the source of that occult power which had caused his father's demise.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "After ___ resigned and discarded his Vision, he handed the running of the Dawn Winery over to the head housemaid and left Mondstadt altogether.\\n___ traveled all across the seven nations of Teyvat in search of the truth.\\nAll clues pointed toward a behemoth of an organization: The Fatui. He learned that they made counterfeit Visions in secret, calling them \"Delusions.\" A Delusion could amplify the power of its bearer to its extreme, but also carried the risk of backfiring. That was what had caused his father's death.\\nWas it possible that his father could have obtained such a sacrilegious item in order to do good?\\n___ knew he may never know the full truth, but that could never stop him from pursuing it.\\nLike an eagle scouring the wilderness, he set off on his hunt for the truth. Determination burned like fire in his heart, unfathomable enigmas and unending battles could not sway him from his course. He pressed on relentlessly, scarred but undeterred, like a fiery tornado burning through the dense fog of mystery.\\nThe Fatui's rulers, the Harbingers, monitored ___'s progress from the shadows. The prowess with which he laid waste to numerous Fatui strongholds caught their attention and forced them to take action.\\n___ narrowly escaped death at the hands of the Harbingers thanks to a third-party observer from the north, who was part of a vast underground intelligence network. The observer claimed to have been watching ___ for some time, and approved of his methods.\\nAfter his close encounter with death, ___ took a long hard look at his past and the anger he had harbored for so long. Acknowledging his shortcomings, he decided to join the underground intelligence network.\\nJust like when he first joined the Knights of Favonius, ___ committed himself fully to his work. His talents and skills saw him rise steadily through the ranks into the upper echelons of the network.\\nThe network was made up of volunteers, and many of its members had willingly given up their prior positions and reputations to join. Some had even abandoned their names.\\nCould working with these new comrades finally restore the faith he once clung to? The faith that had been all but destroyed in the events surrounding his father's death?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: '"Shine True." The background to this motto is hotly contested, but to ___ it has one simple, clear meaning.\\n"Evil cannot go unpunished.\\nNever settle for mediocrity. Never forget that the dawn will one day come."\\n___\'s solitary sojourn lasted for three years.\\nFour years on, ___ had returned to Mondstadt and taken over as head of the family winery, now a young man.\\nIn the space of these four years, Eroch had been purged from the Knights of Favonius after being shown to be a traitor, while Grand Master Varka had left on an expedition, leaving Master Jean to assume the role of Acting Grand Master.\\nThe return of the Dawn Winery\'s master should have been a momentous occasion for Mondstadt, but strangely it went completely unnoticed.\\nThe reason? Mondstadt\'s citizens were far too busy pondering the mysterious case of an unknown "Guardian of Mondstadt."\\nAll that was known about the anonymous guardian was that the smell of burning would follow in his wake, and that a flash of red flames would reveal his silhouette for but a moment in the darkness of the night, before he disappeared in an instant.\\nThe bodies of monsters that had plagued Mondstadt for an age now lay dead in the wilderness... Mondstadt\'s most wanted thieves suddenly appeared bound and gagged, hanging from their feet in the statue plaza... All the Knights of Favonius were dispatched to reckon, once and for all, with the Abyss Mage behind countless crimes in the city, but they arrived only to discover that he had long since been killed...\\nAided by wine-fueled conversations, word of the mysterious guardian spread swiftly, and he came to be known as the "Darknight Hero."\\nIn public, ___ appeared to hold this hero in contempt, his face curling up in disgust every time the name was uttered.\\nElzer of the Mondstadt Wine Guild was one of the select few who was in the know, and once queried ___ about this: Was his disapproval of the Darknight Hero just an act, intended to throw the knights off his trail and protect his anonymity?\\nBut ___ simply frowned once more, and curtly replied: "It\'s just a stupid name."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "Dawn Winery's Apple Cider",
      title2: null,
      text: "___ may hold the whole wine industry in the palm of his hand, but he himself is not fond of wine.\\nAt ___'s request, the Dawn Winery developed several alcohol-free beverages, a decision which was met with resounding approval from those in Mondstadt who could not drink alcohol but still wanted to partake in the drinking culture.\\nOne of those alcohol-free beverages is Mondstadt's Apple Cider, the success of which is on a par with Dandelion Wine in terms of monthly sales volumes.\\nSome think that ___ must have such high standards when it comes to wine that he is never seen drinking the mediocre-quality beverages that are available to the public.\\nOthers think that drinking wine must surely remind him of his father, and that that is why he does not touch it.\\nWhen pressed about his drinking habits, he responds by saying that alcohol clouds his thoughts, and consuming it would impact his day-to-day work.\\nBut the thing that people don't understand is: What kind of day-to-day work does a winery master do, if it requires him to never touch a drop of alcohol?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Crepus had two regrets in life. One was never becoming a knight, and the other was never obtaining a Vision.\\nFor this reason, in the moment that ___ received his Vision, he took it as a recognition by the gods of his and his father's shared ambition — finally, he could make his father proud.\\nJust a few years later, his father died on a dark and gloomy day. The hopes and dreams that burned bright in ___'s Vision were extinguished in the torrential rain that fell on that night.\\nNo matter how upright and good-hearted a person may be, death will still come to them without warning.\\nIs this where the tale of justice ends? Just like that?\\nIt seemed to him that his Vision and his status as a knight were both equally ineffectual at enabling him to protect the things that he treasured most. It was time to discard them both, he decided.\\nWhen he recognized his own powerlessness, his Vision became but a burden, of no greater service than a Delusion.\\nEmpty titles were of no interest to him. He sought after ardent flames that would burn brighter than any other, and an unshakable resolve. Only a firm resolve can drive the truth-seeker forward, and only ardent flames can vanquish the ice that freezes the hand of justice.\\nOn the day that ___ returned to Mondstadt, he took up his Vision once more. The events of his years away had purged him of his childish immaturity, and turned him into a hero ready to shoulder his father's will once more. Each night, from the shadows, he fought for Mondstadt.\\nHe did not discuss the past. But he did not deny the past, either.\\nTo the lost, perhaps a Vision is a beacon of light given by the gods to help them find the path forward.\\nBut to those with conviction, a Vision is simply an extension of their strength, a medium for channeling their willpower, a tribute to the experiences that have shaped them, and a testament to the story of their life so far.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
