export const jeanVl = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'I am ___, the Dandelion Knight, requesting approval to join your party. From this day onwards, my honor and loyalty lie with you.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Operation',
      audio: '1101',
      text: "It's time to move on, we shouldn't stay here.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Knights of Favonius',
      audio: '1102',
      text: 'I do hope the Knights of Favonius are all working hard...',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Target',
      audio: '1103',
      text: 'Onwards! We have work to do.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "The rain won't slow me down.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: '1202',
      text: 'This weather is perfect, we should move out.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Huh, snow. Remember — tend to your boots when we return.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: 'Such fine weather.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'Legend has it the wind was unusually strong on that day, too...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "A successful day starts from the morning. Let's give it our all today.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "We've still got work to do. Let's keep going.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Huh, it seems I'm immune to coffee now. Perhaps I need to ask Lisa for something... a little stronger...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "Training is finished for today. Great work, you've earned a good rest.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___',
      audio: '2001',
      text: 'Today I had no choice but to cut down five Ruin Guards to protect the people of our city... Ugh, I must continue to work harder. Though hostile, destroying such precious artifacts is still a loss to us all. I must find a less destructive way to bring them down next time...',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Creed',
      audio: '2002',
      text: 'You have my complete and full support. Of course, if your path ever deviates from justice, I will not hesitate to point it out.',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Oath',
      audio: '2003',
      text: 'I swear by this sword, victory shall be yours.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Quest',
      audio: '2004',
      text: 'Our work will not handle itself... But, I suppose the occasional short break is warranted. Let us rest for a couple of minutes.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: 'For Mondstadt, as always is the Gunnhildr family motto. Every time I use my Vision, I am reminded of my mother and the hopes of the people of Mondstadt. For Mondstadt, for freedom — that is what I fight for.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: 'On behalf of the Knights of Favonius, I would like to extend my gratitude to you for all you have done for Mondstadt. Please remember to rest from time to ti... Did I miss something? What are you laughing at? Did I say something odd?',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: '"Dandelion, Dandelion, ride the wind to a faraway land." Who knows, the wind might take it all the way to Celestia.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Barbara',
      audio: '4001',
      text: "Barbara is a hard worker, but I feel she's too hard on herself sometimes... What? You ask me how I know all of this? It's because the order also manages the Church.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Lisa',
      audio: '4002',
      text: 'When Lisa is around, I always have peace of mind.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Amber',
      audio: '4003',
      text: "I must say that Amber's development has impressed me recently. I hope that one day, her deeds will become the words of a bard's tale.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Kaeya',
      audio: '4004',
      text: 'Is that right...? Kaeya also gave you some suggestions. He is an excellent knight after all — this is a fact no one can deny.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Klee',
      audio: '4005',
      text: "Though it may be said that it is in a child's nature to play, the things Klee plays with are far from toys. I can never take my eye off her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Albedo',
      audio: '4006',
      text: 'Sometimes I feel that terms like "genius" were originally created for Albedo.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Varka',
      audio: '4007',
      text: "Grand Master Varka is the legend of his generation. On the day of his triumphant return, I shall be sure to personally introduce you to him. I'm sure you too will be in awe of his greatness.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Noelle',
      audio: '4008',
      text: "Noelle... She puts enormous effort into trying to become a Knight of Favonius. However, I fear she is not quite ready for the dangers that lie beyond Mondstadt's walls.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Rosaria',
      audio: '4009',
      text: 'Some may see Sister Rosaria as one who complains about how bothersome her work is, but she does her job well. Last time I saw her I told her she could come find me should she ever need help, to which she simply replied that doing so would be even more bothersome. I need to work harder to become of more assistance to the people of Mondstadt.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Diluc: Disillusion',
      audio: '4010',
      text: 'Master Diluc has his reasons for being so critical of the Knights of Favonius. I am not proud of the way things went, but I cannot change the past. All I can do is keep working hard, in the hope he may one day see us in a better light... This is my duty.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Diluc: Respect',
      audio: '4011',
      text: 'Master Diluc is my senior, and I have the utmost respect for him. Though we have gone separate ways, I can sense we share the same strong commitment to protecting Mondstadt at all costs.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Sucrose',
      audio: '4012',
      text: "Sucrose is also a rare talent in the field of alchemy. Under Albedo's mentorship, she is sure to flourish. I am sure her future will be bright. The only thing is... Ahem, I was momentarily lost in thought. It is nothing. Nothing bad, anyway.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Eula',
      audio: '4013',
      text: "Eula? Um... Please, do not hold her unfortunate background against her. The Knights of Favonius evaluate each person impartially. Eula has a clear sense of right and wrong and is more talented than most. The controversial statements that she makes from time to time are just a product of her personality. For instance, she always mentions wanting to challenge me, but I don't mind.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'About Mika',
      audio: '4014',
      text: "The Grand Master placed Mika on the front line of the expedition team not simply because he met the requirements of the mission — more importantly, he was impressed by Mika's hardworking and grounded nature. From my own perspective, I feel very honored to work with someone like him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About ___: I',
      audio: '5001',
      text: "I shoulder the knights' trust and the people's hope. It is for this reason, I must stay vigilant.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'Vennessa\'s title — "Dandelion Knight" — has been passed down from generation to generation. Countless great knights were awarded with this honor and I will not bring shame to this name. Thus, I must keep going. I must become the sword and aegis of the people.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '36': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'Only glorious victories are recorded in legends and history books. Surely even the great knights of old must have had their struggles?\\nWind, please show me the path.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '37': {
      title: 'More About ___: IV',
      audio: '5004',
      text: 'When I\'m wholeheartedly devoted to my work, all of my troubles and even my sense of time seem to just slip away. Hmm, Grand Master Varka did say to me: "___, there is no better candidate for this task"...',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '38': {
      title: 'More About ___: V',
      audio: '5005',
      text: "As I walk with you, the path ahead becomes clearer. It's almost as if I have finally found someone I can trust. I wonder if...\\nNo, this must mean that I am still lacking in strength... I must not give up, I will not — I cannot fail the Knights and the people of Mondstadt. Still... thank you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '39': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "Maybe we can discuss the tales of legendary heroes. Have you heard the story of the heroic king of Khaenri'ah?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: "___'s Troubles",
      audio: '6002',
      text: 'If only there was some kind of mysterious potion that could keep me awake forever... I need to have a talk with Lisa tomorrow.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Favorite Food',
      audio: '6003',
      text: "It's been ages since I had pizza at Cat's Tail. If only they delivered...",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "A true knight can't afford to be a picky eater.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Not only is the taste magnificent, but you've also made sure it was healthy. You have my gratitude.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Hmm yes, I feel a lot more energetic now, thanks to you.',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Ahem... all in all, I appreciate the effort.',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Birthday',
      audio: '7001',
      text: "Today is a day worth celebrating. If you must ask why, well, let me remind you that today is when you, the one who is blessed by the wind, came into the world. Since this is your birthday, I'll allow you to take it easy.\\nAhem... ♪Happy birthday to you...♪\\nUh... Please forgive my presumptuousness. I hope this gift is to your liking.",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Good. On to our next objective.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'As the wind continues to blow, so too shall I continue to fight.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Although we have peace, we must not become complacent. As the Acting Grand Master, I must remain vigilant.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '50': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'I am still not good enough. Ever since I met you, I have been indebted to you for your assistance. My gratitude...\\nWind, please forgive my selfishness. Not as the Acting Grand Master, but as ___ — I hereby swear that my sword shall always go with you.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "The Knights of Favonius are the protectors of Mondstadt, the swords and shields of the city.\\nIn addition to keeping the city and the surrounding travel routes safe from the threat of wild monsters, the Knights' most important responsibility is maintaining order among Mondstadt's inhabitants.\\nMondstadt is the City of Freedom, but unchecked freedom without any kind of rules only invites chaos and anxiety.\\n___'s understanding of this is the reason she remains diligent at all times, holding herself to impeccable standards.\\nHowever, she often finds that she exhausts her monthly quota of coffee within the first few days of the month as a result.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'The Gunnhildr Clan is the oldest family of knights in Mondstadt, dating back to even before the very first epic was written.\\nHowever, this long and proud lineage can also be a burden. ___ was raised by her mother to be the successor to the Gunnhildr Clan.\\nShe was trained in all the things a knight must know and all the qualities they must exhibit, from discipline, etiquette and conduct, to knowledge of history and ballads, as well as maintaining peak swordsmanship and physical fitness. Only by upholding this standard can ___ carry the mantle of the Gunnhildr Clan, whose motto is: "For Mondstadt, as always."\\nSome time ago, there was a joke commonly told in Mondstadt\'s taverns: A Gunnhildr learns to say "For Mondstadt, as always" before learning to say "Mommy."\\nAs a child, ___ once lifted her head up from the book she was reading, "Breeze Amidst the Forest - Ballad Selection," and saw the other children her age happily playing with pinwheels outside the window. The young ___ knew in that moment what her family motto meant to her.\\nNow, when she lifts her head up from her piles of paperwork and sees the next generation of children doing the same thing, Acting Grand Master ___ has no regrets about her years of service to that motto.\\n"You have to give your all to do the right thing. Always."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '"Master ___ is so reliable."\\n"If you ever run into trouble, seek ___. She\'ll know what to do."\\nThe denizens of Mondstadt, civilians and knights alike, all rely on ___.\\nIf someone needs help for the right reasons, ___ does not hesitate to render assistance.\\nBe it a quarrel down at the market, a relationship issue...\\nNo matter how unrelated it may be to a knight\'s job... ___ gladly lends a hand whenever she can.\\n"The chance to help someone in need is reason enough for a knight."\\nTo her, her knightly duty takes priority over her role as Acting Grand Master. She believes helping others herself is the best way to assist.\\nShe holds her fellow knights to the same standard.\\nLisa the Librarian once suggested that ___ take a break and "enjoy some afternoon tea, as is befitting of a lady."\\nHowever, to ___, doing that which is befitting of a knight takes priority over doing that which is befitting of a lady.\\n"___ is so reliable."\\nSuch is the reputation ___ enjoys in Mondstadt.\\nHer only gripe is that there are not enough hours in the day. She could never help all of those in need, even by forgoing sleep.\\nThe dedication and commitment required to become someone so reliable is unimaginable.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Given everything ___ has brought to her role as Acting Grand Master, people sometimes forget that there is, in fact, a Grand Master who is her superior.\\nThis does not bother her in any way, though. Her role and title within the Knights of Favonius do not affect her work ethic in the slightest.\\nHer passion, honesty, and meticulousness come from two things.\\nOne is her education and training, which instilled in her a chivalrous spirit from a young age.\\nThe other is the devoted teachings of Varka, the free-spirited Knight of Boreas and Grand Master of the Knights of Favonius, currently dispatched on a crusade.\\nThe effect the relaxed and unruly Knight of Boreas Varka has had on ___\'s growth has been great.\\n"Grand Master, please take your job seriously. All of Mondstadt looks up to you."\\n"Well, you are my second-in-command, so helping me out is part of your job description. This way, I can focus on the really important things, wouldn\'t you agree?"\\n"..."\\nHe is the knight of new frontiers and legendary conquests, while she is the knight of maintaining peace and freedom.\\n___ does not resent Varka; perhaps there is wisdom in his conduct. However, what Varka leaves undone falls on her shoulders, and it is then down to her to do the right thing.\\nHalf a year ago, Varka led the elite knights of Favonius on yet another expedition away from Mondstadt.\\nAn expedition — how typical of Varka\'s character.\\n"I\'ll leave things here to you. I mean, you\'ve basically been doing my job for years now, anyway."\\n"Leave it to me, Grand Master."\\nAfter seeing the Grand Master off, ___ sat by the window and thought to herself:\\nUpon your return, I will show you a kinder, more prosperous, and more peaceful Mondstadt.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "The great tree at Windrise is where the first Dandelion Knight came to the end of her journey.\\nShe was Vennessa, the founder of the Knights of Favonius and the restorer of Mondstadt.\\nShe bade farewell to the city she had vowed to protect, leaving behind her legend and a single sapling.\\nAfter centuries of basking in the bliss of the thousand winds, this sapling grew into a towering tree.\\n___ was conferred the title of \"Dandelion Knight\" at the age of fifteen.\\nThe Dandelion Knight is also known as Lionfang Knight. Passed down through generations of knights, the title is bestowed upon only the most distinguished.\\nOn the day she received the title, ___ excused herself from the celebrations that followed the conferment ceremony. As if following in the footsteps of her childhood hero, she went and stood before the great tree.\\nThe title of Dandelion Knight symbolizes Vennessa's legacy of resistance and benevolence. So how, ___ thought, could one such as herself be worthy of this honorable title?\\nMore than a millennium had passed since Mondstadt's restoration. Did she really have what it would take to continue to protect this ancient and proud land of freedom?\\nBeneath her outwardly mature visage lay the heart of a young girl, who had only just received the title and remained wholly unprepared for the task that lay before her.\\nThe wind blew from far away, and she felt it flow within her as it gently whisked away her doubts and worries, leaving her with an unwavering determination:\\nFor Mondstadt, as always.\\nTo become a warrior as kind and as determined as Vennessa, and to fight for her people and for freedom... Yes, this was the true meaning of her simple family motto.\\nTo this day, whenever ___ feels weary or feels herself beginning to waver, she comes and stands before this tree and lets the wind console her once more. It carries away her fatigue, so that she may once more have the strength to carry on.\\nThe great tree at Windrise marked the end of the first Lionfang Knight's journey.\\nSo too does it symbolize the beginning of ___'s.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Master ___ has a secret.\\nThe Gunnhildr Clan is a venerable knightly house. This prideful blood comes from ___'s mother, Frederica.\\n___'s father on the other hand is Seamus Pegg, an adventurer famed throughout the continent. When he came to Mondstadt, he dusted off his past self and started anew with the Church of Favonius, and ascended to high office within it, becoming known as the Cardinal of Daybreak.\\nThe two lovers eventually parted ways. Young ___, holding her mother's hand, would watch the silhouettes of her father and her sister, Barbara, grow ever more distant.\\nLater, Barbara would follow in her father's footsteps and join the Church of Favonius, becoming a deaconess much beloved by the people.\\n___ has always wanted to get closer to her younger sister by blood, but cannot bring herself to say anything when faced with Barbara's evasive eyes.\\nPerhaps this all-too-similar awkwardness is a sign that the sentiment is shared.\\nMaster ___ has yet another secret.\\nNo matter how many times she has read the historical classics, despite her title of Dandelion Knight, and though she has become the Acting Grand Master whom everyone relies on...\\n___ still loves romance novels.\\nThis is not for the years as a young girl that she missed amid her training and duties, or due to the rift that formed in her parents' marriage.\\n___ simply yearns for the mutual attraction spoken of in such stories, for those emotions as subtle and fragile as spider-silk.\\nAs a knight, she must put Mondstadt and the Knights of Favonius first.\\nBut...\\n\"If I too could...\"\\nIn her office, deep at night, ___ once again finishes reading \"Vera's Melancholy.\"\\n\"If I have the time, it should be fine to go to Cape Oath, just before daybreak... right?\"\\nLowering her head, ___ peeks out her window at the glittering stars above.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "___'s Daily Schedule - Ver. XVII",
      title2: null,
      text: 'This schedule is accurate down to the minute.\\nFrom a morning run with Amber followed a breakfast trip with Lisa on the way, to doing her own laundry by hand and settling her own change of clothes at night — all things great and small pack ___\'s schedule rather tightly.\\nEvery completed item is ticked off, while ones delayed due to external factors list the detailed whys and wherefores.\\nNext to the item "Mondstadt Public Facilities Review" — delayed due to a bout of illness — is written the following "completed at 3 am, end-of-month book purchase award is canceled."\\n___ sometimes thinks that inspiration for this schedule may have been the training program her mother drew up for her ten years ago.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'If one were to go by skill alone, ___ has long become one of the best swordsmen in Mondstadt.\\nBut in ___\'s heart, she would rather be a shield that defends freedom and song than a sword that cuts through corruption and darkness.\\n"Protecting" has always been a tougher task than "destroying."\\nAround the time when she was promoted from Captain of her squad to Master of the Knights, a huge challenge stood before her. From without, the Fatui exerted diplomatic pressure, and from within, there were traitors — comrades of the former Inspector. Regrouping and finding a way to break through was no easy task.\\nBut ___ was able to fend off the external pressure with one hand, and lead the Knights to smash the many plots of the Abyss Order with the other, re-establishing the authority of the Knights of Favonius.\\n___ will never forget the moment she received her Vision. At that moment, all seemed to grow quiet as she felt the breeze flow through her hand. The world seemed to fade away, save for the time-honored motto of the house of Gunnhildr:\\n"For Mondstadt, as always."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
