export const sucroseVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "I'm ___, a researcher of alchemy. I heard you've been to a lot of places, so I was wondering if you... Ah, what am I saying! It's only our first time meeting, I shouldn't trouble you. But... if you're willing, I'd love to hear any stories you have about your adventures. I'd... really like that.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Curiosity',
      audio: '1101',
      text: "What was that? Oh... it's gone. Can I go take a look?",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Organization',
      audio: '1102',
      text: 'I just need a moment to quickly take down some notes.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Deep Breaths',
      audio: '1103',
      text: "Ahhh! I haven't been out in a while.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When the Wind Is Blowing',
      audio: '1201',
      text: 'The windmills are spinning faster than usual today. Hey, do you think if an animal put a propeller on its back and started running... do you think the propeller would make it run faster? Or even, fly?',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: '1203',
      text: "Snow this big only falls a few times a year. If I miss it, I'll have to wait until next year to run my experiments, so please give me some space. Ah-Ahchooo! ...Yes, I know, I should wear more layers...",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'The sun is already out? Oh, ah, okay! Just one last experiment, and then we can get some rest. Last one, I promise...',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Rains',
      audio: '1205',
      text: 'Humidity levels are increasing. Think we could run some tests?',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Good morning. Did you sleep well? According to research, not getting a good night's sleep can have detrimental effects on your cognition and stamina. What? I'm always up working through the night? Yeah, I know... Can't be helped I guess...",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Waaaaa! No, stay back, don't come over here! No, no, it's nothing personal — it's just that this experiment is highly volatile and might cause an explosion.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. Please wait a moment. Experiment 905 has actually produced two light excretions, which, for clarity's sake, should be labeled No. 1033 and No. 1035 respectively... Right, now, what did you need me for?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "No need to wait up for me. Please, get some sleep. Something bothering you? Oh, don't worry about me — I'm right at the end of my experiment. I promise I won't stay up late again...",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Bio-Alchemy',
      audio: '2002',
      text: 'Bio-alchemy, when compared with creation, places more emphasis on transformation. Finding those little secrets that living creatures have and scaling them up, combining them — the results are always such a surprise. Life really is fascinating. Just how much do we really know?',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Fear of Strangers',
      audio: '2003',
      text: "I... um... really don't know how to act around new people. Everyone's personality is different, as are the things they care about. If I slip up and say the wrong thing, I'll offend someone, or sound impolite... Talking is hard, so much harder than alchemy.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About ___: Ears',
      audio: '2004',
      text: "Oh, you, ahh... noticed. My ears are a hereditary feature... quite different from everyone else's. So, I try to hide them with my hair as much as possible.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Observing',
      audio: '2005',
      text: "I'm curious to know about your background. I was wondering... could I perhaps... observe you for a while? I'll be silent, and I won't interfere with what you're doing. Would... that be okay?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Perks',
      audio: '2006',
      text: "To be honest, I was a little afraid when we first met, because you don't talk much... I thought I must have offended you somehow. But then as time went on, I discovered you're really easy to get along with. Hehe, just an unexpected outcome of my observations.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: Requests',
      audio: '2007',
      text: "I heard it was you that dealt with the Stormterror issue. No doubt it was a dangerous fight — it's a good thing you came out unscathed. I was ahh... also wondering — did Stormterror happen to drop anything during the fight? You know, a scale, some skin — even just a little would be fine. There are some tests I'd like to run...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 309,
              questTitle: null,
              chapterId: 1001,
              chapterTitle: 'The Outlander Who Caught the Wind',
            },
          ],
        },
      ],
    },
    '18': {
      title: 'About the Vision',
      audio: '3001',
      text: "My Vision is my most important research tool. Hmm? Why, without it I'd be unable to proceed with most of my elemental research. Combat? Oh, I suppose I use it for that too when I'm out in the field looking for materials.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share',
      audio: '3002',
      text: "This room is where I keep all the bones I've collected. On the table on the left we have lizards, frogs, and grass carp. To the front we have the bones of a wild boar, and then over there in the right corner is a hilichurl... Oh, don't be nervous, nothing to be afraid of. They're really quite cute once you get used to them.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "If you look closely, you'll notice that the Mist Flowers I've planted here are all different. This one is the most powerful, this one blooms the longest... This one? Oh, this one is project 3, version 17, enlargement trial. Its defining trait is that... it's a bit larger.",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Noelle',
      audio: '4001',
      text: "She's... a very willing helper, I can't deny that. It's just... she makes me a little anxious is all. One time, she saw three boxes of materials stacked just outside my laboratory door, and proceeded to move them inside for me. A nice gesture, but the thing is... I'd only just finished putting them outside...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Klee',
      audio: '4002',
      text: "Jean has put her into solitary confinement so many times, but every time she's let out it's not long before she's back in trouble. *sigh* Something tells me she hasn't done much introspection. I told her I'd make her a bouncing, dancing Jumpy Dumpty that is also safe — but to date there are still a lot of problems with the design.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Jean',
      audio: '4003',
      text: "I don't dare talk to Master Jean that much, because she's so strict. I know she's a good person and all — I know that, I do — but... I still find her scary. I don't tend to bother her, and even when I have to... I ask Albedo to go on my behalf.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Lisa',
      audio: '4004',
      text: "She really seems to know a great deal. She's obviously never seen my research, and yet on so many occasions she's given me advice on that which is most core to my studies. Just how does she know? Is it observation, or is it ratiocination?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Kaeya',
      audio: '4005',
      text: "Oh... I know he likes to joke, and isn't trying to make fun of me, but I often struggle to work out which parts of what he says are the truth and which parts are jokes. So whenever he talks to me, the outcome is usually one of two things: morbid embarrassment or unbearable awkwardness.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Albedo: Artistry',
      audio: '4006',
      text: "As his assistant I learn so much each and every day. What's key is not his existing knowledge, but his talented way of thinking. No matter how complex the task at hand, his way of thinking ensures he gets to the bottom of it, and is able to explain it thoroughly. His methodologies are amazing... to me, it's where alchemy meets art.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Albedo: Talent',
      audio: '4007',
      text: "Talent? Let's hypothesize that he and I were to perform the same research — I'd still spend my whole life playing catch up. But, my studying bio-alchemy has nothing to do with evading his line of research, we just happen to have different interests and dreams — nothing more.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Amber',
      audio: '4008',
      text: "I'm curious as to why her doll is called \"Baron Bunny,\" it clearly has nothing to do with a rabbit at all. Oh, the headband makes it look like it has rabbit ears you say? Hmm... That's heavily reliant on the rabbit stereotype, is it not? Many rabbits' ears are floppy.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Fischl',
      audio: '4009',
      text: "I take it you're referring to the book series, Flowers for Princess Fischl? Indeed, the world the author came up with is very creative. If only I could go see it with my own eyes. Oh, you're referring to Fischl herself? I am... doubtful that she could really take me there.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Eula',
      audio: '4010',
      text: "The role of a scout is a hazardous one, and Ms. Eula throws herself into danger all too easily. So, I made a reconnaissance device for her, so that she wouldn't have to infiltrate enemy camps herself. But Ms. Eula has such an imposing manner, she really puts me on edge, and... I was so nervous that I accidentally left out a few important details while explaining how to use it... As a result, there was an accident...\\nAh, what should I do... I hope she won't hold a grudge against me...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: I',
      audio: '5001',
      text: "You... want to know more about me? You... must have an interest in bio-alchemy, then? Whatever you ask, I will be sure to give you the most precise answer possible. Oh, it really is me specifically that you are interested in? I'm... ahh... oh. I'm at a loss for words.",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'More About ___: II',
      audio: '5002',
      text: "The essence of research is the process of finding the answer. Sometimes, working through that process can be tedious, but every time I see the cumulative result of my efforts... I know that I'm doing what I love.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '33': {
      title: 'More About ___: III',
      audio: '5003',
      text: "When I was little, I had two good friends — we kept nothing from each other. I thought I knew everything about them, but then... stuff happened, and we grew distant. As for where they are now, what they're doing, whether or not they remember me... I have no idea. Even though we were best friends, things still turned out this way.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Let me tell you a little secret, something I've never told anyone. The purpose behind my research is to create my own wonderland. Yes... just like the ones in fairy tales. The kind where all your dreams come true and you live happily ever after. Hehe, it's childish, isn't it? But, I still believe in fairy tales.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '35': {
      title: 'More About ___: V',
      audio: '5005',
      text: "If you're busy, please don't let me stand in the way of progress. ...You're not busy? Really? It's fine, I—I get that you have stuff to do. I'm already quite used to working alone. ...You're truly not busy? I—In that case, I don't suppose you could help me with a few things? Or, you know, we could sit and chat about... stuff.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '36': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'I like things that look orderly. See? All of my research notes are compiled in notebooks of the exact same thickness. All my potions are lined up according to effect and hue— Wha—What!? What is this purple potion doing here!? Sorry, I—I need to reassess the order of these potions!',
      tips: '',
      tasks: null,
    },
    '37': {
      title: "___'s Troubles",
      audio: '6002',
      text: "I wonder... What is it that you do in your free time? Every time I get a break, I can never find anything to do. I just find myself staring off into space. Time goes by so quickly when I'm experimenting, so how is it that when I'm not doing anything, the days all feel like years...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'I extract the nectar from Sweet Flowers to make candy. When I get stuck in a rut, I just pop one in my mouth and my focus returns. Retaining optimal blood sugar levels during research is essential.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Once I came to understand more about bio-alchemy, I stopped eating mushrooms. You're no doubt aware? Mushrooms grow on that which has died, which in turn makes me think of other such things, and my appetite just disappears... Blergh...",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'So delectable! Time to finish my research now that I feel at my best!',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'I must admit, this tastes a lot better than my healthy meals. Time for me to make some modifications to my diet.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Sorry, I have some... reservations about this dish.',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: 'Happy birthday! I\'ve been running experiments for months, and finally I can give you this potion. It will allow you to relive your most beautiful memories of the past year. I call it "Bio-Potion No. 3916." Huh? No, no, not 3196, it\'s 3916!',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Finally! A breakthrough in my bio-alchemy research.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "This trip has allowed me to gather a good number of materials. Thank you, I'll be sure to put them to good use.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Recently during my experiments, I've found myself suddenly wondering when I'll next get to go on an adventure with you. So strange... Why do you think that is? I need to do some scientific investigation to find out.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'I have such an abundant array of research materials now! To spend any more time on me would... would really be a waste of your time! At least... let me use my bio-alchemy to make you up some kind of gift!',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "___ may be the assistant of the genius alchemist Albedo, but they could not be more different in research direction.\\nAs opposed to studying the essence of alchemy and the ability to create new life, she is far more interested in using alchemy to modify existing life, all the better to add variety and color to this world.\\nDespite her youth, she has already achieved some brilliant results. For example, she has been able to increase the nectar output of Sweet Flowers by 70% by irrigating them with a special potion. She has also developed a special spray that allows Sunsettias to maintain their freshness for a whole month after being plucked from the branch.\\nEven people who were initially suspicious of her research inclinations have come to acknowledge her exceptional talents in the field of alchemy after seeing such results.\\nHowever, she merely considers these to be incidental steps on the path to a successful experiment, rather than the success itself. Her true aim is much more ambitious than this.\\nIt's a secret, and is also her little dream.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Bio-alchemy explores numerous lines of inquiry, all of which stem from ___'s questions about living things in the world. These questions, in turn, are born out of her insatiable curiosity, a faculty that is far more developed in her than it is in most.\\nFor instance, ___'s curiosity was once drawn to the sweet flower, accepted by most people as simply being a source of sugar.\\nShe wondered: Although sweetness is clearly the most readily identifiable feature of this plant, should that be grounds for limiting its application as we have tended to do? Does it not merit further study?\\nSo, after a careful study of the various features of sweet flowers, she devised thirty-something distinct rearing plans along with numerous control groups to account for temperature and other environmental conditions.\\nAnd yet, her experiment still underestimated just how many variations were possible. After the experiment began, ___ found herself with more questions rather than fewer, and the novel discoveries that her experiment yielded gave her inspiration for further research.\\n___ is incapable of leaving a question unattended to — it makes her restless, even guilty, to ignore it. Spurred on by this quirk of her temperament, her rearing plans grew in number to almost three hundred.\\nThe result was a whole new series of sweet flower strains: Some with thrice the number of flowers, some with heads five or six times the normal size that could even float in the wind, and some even producing a sweet-tasting fruit.\\nMonths of experimentation later, ___ had finally answered every last one of her questions pertaining to sweet flowers. As she finished writing up her research notes, she let out a long sigh of relief.\\nThough she was physically and mentally exhausted, the sight of stack after stack of her bio-alchemical research volumes stretching around three walls of the room gave her a deep sense of joy and satisfaction.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'To the people around her, ___ comes across as a quiet, introverted alchemist with little interest in the lives of others.\\nIn fact, the truth is quite the opposite: ___ is fascinated by absolutely everything that exists in the world. The only thing is, she finds the discipline of social interaction to be far more difficult to master than that of alchemy.\\nIn alchemy, the process of trial-and-error coupled with a determination to get to the truth is sufficient to bring you to your answer eventually. But with interpersonal relationships, there is the added complication of having to factor in manners, moods, and other unquantifiable variables. To make things worse, there seems to be no room for an approach that relies heavily on making errors.\\nHence, ___ decided to avoid such variables at all costs and stick to her familiar methods in satisfying her curiosity.\\nFor instance, ___ had always been curious about whether she and Cat\'s Tail bartender Diona, both of whom have animal ears, had any shared ancestry.\\nIn fact, this was not a private matter, and most people would simply ask the question. But ___ was concerned that it would be a sensitive topic — she, for one, did not like people drawing attention to her ears.\\nSo, she resorted to the method she knew best: observation.\\nFor one whole month, Diona constantly had an unnerving sense that someone was secretly watching her. She assumed that one of the tavern patrons was stalking her, and was none too happy about it.\\n"Similar genome, but ultimately different ancestry. Cat connection merits further study. Note: Unable to obtain bone sample thus far."\\nThis is the conclusion that ___ has jotted down in her notebook based on her findings so far.\\nBio-alchemy aside, ___ made one further discovery from this episode.\\nThat is to say, judging by the pair of cat-ear spectacles she made for herself after the event, it would appear that she has finally come to comprehend a certain uniquely feline variety of cuteness. She is too shy to wear them in public, however, and only puts them on when alone in her room.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Once every three days, ___ ventures out into the real world at dusk. To her, these excursions are rare and momentous events.\\nOne by one, she visits the butcher's, the Adventurers' Guild, and the Springvale hunters, looking for a material of a very specific kind.\\n\"H—Hi... Sorry, I... I'd like, um, the freshest, best-quality b—bones you've got... Yep, the ones with the blood and meat still on.\"\\nPeople found her behavior utterly unusual at first, but once they had gotten used to it, they were eager to oblige, even putting the rarest bones aside for her in advance.\\nThis was a major bonus for her. Not only was she able to acquire an ample supply of the usual chicken and boar bones, but she also got her hands on a complete lizard skeleton and even a chunk of hilichurl leg bone still bearing fresh blood.\\nHer eyes would light up with excitement at the sight of these strange and rare bones. She would thank Katheryne of the Adventurers' Guild profusely, bowing to her over and over.\\nAs well as going some way towards satisfying ___'s curiosity, she also found new inspiration from piecing new bones together\\nMore importantly, collecting skeletons was her hobby, and she was crazy about it.\\nOne day, ___ happened to overhear a mother attempting to discipline her child:\\n\"If you don't do as you're told, the scary old lady with the cloth sack over her back will come to your door, go into your room, pick out every bone from your body, and take them away!\"\\n___'s curiosity compelled her to investigate further. It turned out that this was nothing more than a ghost story used by mothers to shock their children into compliance, and that it had existed long before ___ was even born.\\nShe breathed a sigh of relief when she found out the truth.\\nSoon after this, people noticed that ___ had switched her cloth sack for a leather one. Perhaps she did this just because she was shy. Or perhaps it was to avoid arousing suspicion...",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "As an assistant, ___ does everything she can to support Albedo, and even though his alchemical inquiries tend more towards the abstruse, she finds herself learning a lot every time.\\nAfter an experiment lasting five straight days and nights came to its end, Albedo noticed that ___ was on the brink of collapsing from exhaustion, and organized a mandatory seven-day vacation for her.\\n___ began her holiday determined to take a proper rest and regain her energy, but from the moment that she woke up on day one she struggled to adjust to the vacation lifestyle.\\nFirst things first, let's get some breakfast: fried eggs, sausages, and a cup of coffee. Nothing new to report there. All of these were foods and beverages that she had previously researched, after all.\\nNext, she thought, how about a little rest and relaxation in the sun with a good book? Again, nothing new to report: plenty of research shows this to be one of the most effective means of relaxation. There wasn't a book that she hadn't already read, and there wasn't a query that she hadn't already highlighted, looked into, and later annotated for clarification.\\nSo then she did some household chores: laundry, dusting, tidying. Check. Once again — nothing new to report. There was nothing to dispute about the fact that a clean and tidy environment is conducive to mental well-being.\\nHalf a day in, and ___ had not had the occasion to ask \"why\" or \"how\" even once.\\nShe was bored, restless, and angsty, and she could not calm herself down.\\nShe was desperate to throw herself at a research problem. It didn't matter what it was: She would have happily researched the potted plants on the terrace, even if nothing came of it. Anything just to pass the time.\\nBut wherever she looked — the Lamp Grass to her left, the Sweet Flower in front of her, or the Cecilia to her right — all she found were things that she had previously researched in exhaustive detail.\\nFinally, she gave up and forced herself to go to sleep. The next day, she reported to the laboratory first thing in the morning.\\n\"All day long, you have nothing to research, and nothing to question. That's not rest, it's torture!\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "___'s childhood was no different from anyone else's in Mondstadt. She had loving parents, she had her best friends. Life was simple, and beautiful.\\nHer most enduring childhood memory is a story she once heard about a wonderful paradise.\\nSomewhere in a far-flung corner of Teyvat, there was an undiscovered domain with pretty pink flowers the height of a hundred people, teeny-tiny floating fairies flying over all the place, and beautiful unicorns, the pinnacle of perfection.\\n___ and her two best friends believed that if only they could reach this magical place, they would surely live happily ever after.\\nBut time went by, and one of her friends left on a long journey with her adventurer parents, never to return.\\nThe other suffered a domestic tragedy: Her father fell ill and passed away, her whole personality changed, and she broke off her friendship with ___. The promise that they had once made to reunite some day in the future no longer meant anything.\\n___ felt lonelier then than she ever had felt before in her whole life. They hadn't even set eyes on paradise yet, and already her friends were gone...\\nWell. Even if they were destined to never meet again, ___ was desperate to honor their past friendship in some way. That was when she discovered the existence of alchemy from a book that she was reading.\\n___ realized: Though she had never had the chance to find the entrance to that wondrous place, she now had the opportunity to be the creator of her own paradise.\\nThus began her study of bio-alchemy, and she poured all of her curiosity and passion into it.\\nStill, she has never once mentioned the story of paradise and her bygone friendships to anyone else.\\nPerhaps one day, when that place she first learned of in a children's storybook finally becomes a reality in the real world, her friends will return.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Mist Flower Project 3, Version 17, Enlargement Trial',
      title2: null,
      text: '___ has a set of strict requirements when it comes to the selection of species for her personal paradise. After experimentation, specimens that are up to standard she tags with "pass."\\nAt first, she wanted to give exotic-sounding names to each of her plants, just like in the stories, but whenever she came to try and name something, she found herself completely at a loss for ideas.\\nAfter spending so long as a scientist, she insisted on flawless logic even when it came to relatively trivial matters such as naming.\\nHer earliest batch of names included the following: "Grassflower," a flower that grows on grass;\\n"Flowergrass," a grass that grows beneath flowers;\\n"Multigrassflower," a flower that grows on dense grass, and so on and so forth.\\nEven such un-paradisiacal names as these would take ___ forever to come up with — far longer than the duration of the experiments themselves.\\nIn the end, she gave up on naming altogether and simply used the specimen identifiers from her research notes instead. Yes, this meant the names ended up being much longer, but, but...\\n...But anyway, ___ is the creator of this paradise, so why shouldn\'t she get to name things any way she wants to?',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'It was on an afternoon just like any other that ___ received her Vision.\\nReady to begin her one-hundred-and-fifty-ninth dandelion-seed simmering experiment, she poured her carefully crafted alchemical solution into the cauldron.\\nInstantly, the cauldron hit boiling point, and the entire room was filled with steam. ___ rushed to the cauldron, anxious to see what new transmutation had occurred this time; in her excitement, she even burned both of her hands on the lip of the cauldron.\\nMuch to her disappointment, however, the Dandelion Seeds had once again burned to a crisp. But there was something new there, too: lying there amidst the black Dandelion Seeds was a Vision.\\nAnd yet, rather than pouring out the liquid and taking her Vision, she first thought for a moment and then lit the fire up again to continue simmering the contents of the cauldron.\\nShe was curious to know what further reactions might occur between Dandelion Seeds and Visions.\\nSadly, the experiment ended in failure after three hours of constant simmering.\\nStill, there was no denying that she had reaped a great reward from this experiment, for the elemental energy provided by her Vision would become her single greatest asset in her future bio-alchemical endeavors.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
