export const albedoVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Albedo_Hello',
      text: "I am ___, Chief Alchemist of the Knights of Favonius. You carry the aura of the stars, interesting... I would like to study you, if you do not mind. I'm certain we will have many opportunities to be alone in the future.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Still Life',
      audio: 'VO_Albedo_Chat_-_Still_Life',
      text: 'What a view... How about a quick break so I can sketch this beautiful scenery?',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Investigation',
      audio: 'VO_Albedo_Chat_-_Investigation',
      text: '"The truth of this world"... *sigh* What could it be?',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Reminiscing',
      audio: 'VO_Albedo_Chat_-_Reminiscing',
      text: 'Going out into the world and investigating, turning the "unknown" into the "known." ...Ahhh, I missed this feeling.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Albedo_When_It_Rains',
      text: 'The soil is moist, ideal for collecting the roots of Boom Blossoms. No please, allow me to handle this.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: 'VO_Albedo_When_It_Snows',
      text: 'Master...',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: 'VO_Albedo_When_the_Sun_Is_Out',
      text: 'Ample light... active biological organisms... Yes, this is a good place to sketch.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Good Morning',
      audio: 'VO_Albedo_Good_Morning',
      text: 'Good morning. Are we going to search for ancient relics today?',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Afternoon',
      audio: 'VO_Albedo_Good_Afternoon',
      text: 'Good afternoon. I heard your footsteps. My, it certainly is lively outside of the workshop.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Evening',
      audio: 'VO_Albedo_Good_Evening',
      text: "*sigh* It's gotten quiet outside...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Night',
      audio: 'VO_Albedo_Good_Night',
      text: 'Good night, you go ahead and rest. I will just finish one last experiment before bed... If you are interested in the results, I can discuss them with you tomorrow.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'About ___: Genius',
      audio: 'VO_Albedo_About_Albedo_-_Genius',
      text: 'Genius? ...A number of people call me that. But I don\'t think I\'m any "genius."',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Socializing',
      audio: 'VO_Albedo_About_Albedo_-_Socializing',
      text: 'Relationships are... *sigh* quite troublesome. Once you establish a relation with someone, you must continue to maintain it; if you lose contact, you must reestablish the relation. This taxing cycle requires...a lot of time.',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Experiments',
      audio: 'VO_Albedo_About_Us_-_Experiments',
      text: "You... want to accompany me while I experiment? I'm honored.\\nOh, don't be nervous. My experiments may be dangerous, but no one gets hurt... most of the time.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Assistant',
      audio: 'VO_Albedo_About_Us_-_Assistant',
      text: "Would you oblige me by serving as my assistant? After observing so many experiments, you surely know a good deal about alchemy by now. Relax, we will work together. I don't think you will have any problems. I have faith in my ability to instruct you, and even more faith in your exceptional talents.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: 'VO_Albedo_About_the_Vision',
      text: "My Vision? Ah, that's nothing more than a tool to aid in my experiments, no different from a beaker or crucible. The one thing about it that really intrigues me is the principle behind how it works... One day, I will uncover its secrets. It's only a matter of time.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: 'VO_Albedo_Something_to_Share',
      text: "There's something I've always wanted to ask you, but feared rejection and disappointment...\\nAhem... I am very interested in your... little floating companion. May I borrow her to investigate for a short while?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: 'VO_Albedo_Interesting_Things',
      text: "You would like to know more about petrified trees? Um... ahem. Actually, the petrified trees you have come across in domains aren't that ancient. Truly ancient trees usually grow to around one or two miles in height? Oh, and there's a kind of large spider that lives around their roots — if you tie one up in cape jasmine and lemongrass and sprinkle on some cardamom, smoke it for a few hours — you get a fragrant taste that's simply... unforgettable.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'About Family',
      audio: 'VO_Albedo_About_Family',
      text: 'Family? Although Alice has always asked me to call her "Mother," when I think of the idea of "family," my master comes to mind first. My earliest memories in life are of going on adventures with her. She taught me the art of alchemy and much knowledge about the world. Perhaps... even the words "family" and "master" are incapable of fully expressing her meaning to me.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '19': {
      title: 'About Sucrose: Direction',
      audio: 'VO_Albedo_About_Sucrose_-_Direction',
      text: "Sucrose? I think I more or less understand why she is so dedicated to her research in bio-alchemy... Either way, I'm happy to see her succeed more and more in her endeavors.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Sucrose: Habits',
      audio: 'VO_Albedo_About_Sucrose_-_Habits',
      text: 'Working with Sucrose on alchemy research is quite pleasant, but she has some... stubborn qualities in regards to certain aspects unrelated to research. For example, I have told her numerous times to just call me "___" since we are hardly generations apart, but she insists on addressing me in an excessively formal manner. *sigh* ...Whatever she prefers, I guess.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '21': {
      title: 'About Lisa',
      audio: 'VO_Albedo_About_Lisa',
      text: 'Lisa? I always am impressed by the valuable perspectives she brings to discussions. But is a person with her talents satisfied with such a basic occupation as librarian? There must be some hidden reason for this.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Klee',
      audio: 'VO_Albedo_About_Klee',
      text: 'Indeed, I view Klee as my younger sister. Whenever she gets herself into some explosive sort of trouble, I can only console myself with the fact that her current destructiveness is nothing compared to that of Miss Alice.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Jean',
      audio: 'VO_Albedo_About_Jean',
      text: 'Jean? She has served exceptionally well as Acting Grand Master. One can even say she is more reliable than Grand Master Varka. Perhaps in our hearts, we all eagerly await the day she can become the official Grand Master herself.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Xingqiu',
      audio: 'VO_Albedo_About_Xingqiu',
      text: 'Oh, Xingqiu? I find his written works quite interesting. The Yae Publishing House in Inazuma has been asking that I cooperate with a different author for greater royalties. Hmph, do I seem the type to be swayed by a few extra Mora?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Barbara',
      audio: 'VO_Albedo_About_Barbara',
      text: "Barbara? She's a very earnest Deaconess. I once had the opportunity to sketch her a simple portrait... What happened to the sketch? Ah yes... Albert offered to purchase it, but I rejected his bid and gave it to the Acting Grand Master. Social relations... really require a lot of effort.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'More About ___: I',
      audio: 'VO_Albedo_More_About_Albedo_-_01',
      text: "Have a question for me? Go ahead, ask. It doesn't take too long to ask a single question, does it? I'm about to begin the final stage of an experiment...",
      tips: '',
      tasks: null,
    },
    '27': {
      title: 'More About ___: II',
      audio: 'VO_Albedo_More_About_Albedo_-_02',
      text: 'Oh, by the way. Did you know that without human manipulation, you would need to harness the power of a sun eight times the size of our own in order to naturally create gold?',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '28': {
      title: 'More About ___: III',
      audio: 'VO_Albedo_More_About_Albedo_-_03',
      text: "The time required to sketch portraits closely correlates with one's mood. I could spend half a day sketching Huffman, while I might only need three strokes of the pencil to sketch Kaeya — one for the face, one for the eyepatch string... and one for the eyepatch.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About ___: IV',
      audio: 'VO_Albedo_More_About_Albedo_-_04',
      text: 'What do I do besides sketching and research...? I will occasionally read novels from Inazuma and Liyue. They contain many fascinating ideas which can sometimes provide me with unexpected inspirations for my own creations.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '30': {
      title: 'More About ___: V',
      audio: 'VO_Albedo_More_About_Albedo_-_05',
      text: 'Even now, I find the nigredo processing stage of alchemy passed down by my master to be full of mystery. What did my master want to create using this technique...? My research is far from over. I will require your help to investigate further.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '31': {
      title: "___'s Hobbies",
      audio: 'VO_Albedo_Hobbies',
      text: 'Hmm... Besides research, the activity I spend most of my time on is probably sketching. At first I saw it simply as a way to better study the structure of living things and materials so as to aid me in my experiments, but it eventually became a hobby of mine. Indeed, it is a very good way to relax.',
      tips: '',
      tasks: null,
    },
    '32': {
      title: "___'s Troubles",
      audio: 'VO_Albedo_Troubles',
      text: "There's just never enough time, is there? Even when I remove the most troublesome matters from my schedule, I still can't find enough time for everything.",
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'Favorite Food',
      audio: 'VO_Albedo_Favorite_Food',
      text: 'I really do enjoy having dessert. How can I put it...? When both physical and mental capacity are spent, high-energy materials further provide a kind of primordial, highly-effective boost.',
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'Least Favorite Food',
      audio: 'VO_Albedo_Least_Favorite_Food',
      text: "What food do I dislike? ...Large portions of meat at restaurants. I have a rather small appetite, so a meal like that only ends up in tragedy — either I overeat and the joy of the taste is lost, or I don't finish it and the food is wasted. I decided to simply not go to restaurants, although that has also meant I must spend more time preparing my own food...",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Receiving a Gift: I',
      audio: 'VO_Albedo_Receiving_a_Gift_-_01',
      text: 'If flavors were colors... this one would be gold.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Receiving a Gift: II',
      audio: 'VO_Albedo_Receiving_a_Gift_-_02',
      text: "You're willing to spend so much time on improving your cooking, and that's precisely how you're able to make it taste so good.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: III',
      audio: 'VO_Albedo_Receiving_a_Gift_-_03',
      text: 'This is more than I can manage... maybe we could split it between us?',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Birthday',
      audio: 'VO_Albedo_Birthday',
      text: 'Happy birthday. You look especially happy, would you mind if I sketched you? The capacity of our brains is limited, so we are bound to forget things. But when an image is transferred onto paper or canvas, the sketch becomes an extension of our memory. We can remember that past feeling when we later look at the sketch.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Feelings About Ascension: Intro',
      audio: 'VO_Albedo_Feelings_About_Ascension_-_01',
      text: 'Nigredo is the first step in alchemy, drawing from primordial forms. As beings who live in this world, we must find our own meaning.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '40': {
      title: 'Feelings About Ascension: Building Up',
      audio: 'VO_Albedo_Feelings_About_Ascension_-_02',
      text: '___ is the step in which change begins. Clearing away the excess so we can take on all the knowledge that is available. Would you like to investigate this world with me?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Climax',
      audio: 'VO_Albedo_Feelings_About_Ascension_-_03',
      text: 'Rubedo in alchemy refers to the refining of feeling. I feel the refining of my own emotions is also thanks to you.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Conclusion',
      audio: 'VO_Albedo_Feelings_About_Ascension_-_04',
      text: 'Citrinitas is the final stage of the alchemical transmutation process. The meaning of the object being transmuted has finally been brought to light, becoming gold and revealing its true value... I too have found my own meaning.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Alchemy is an ancient art, and many of its secrets have been lost to history. The few commonly known alchemy techniques of today are but enough to put some broken odds and ends together, saving you the money you would have otherwise spent on glue.\\n"Nay, alchemy is not so ignoble an art!" Or so most alchemists would protest.\\nBut as far as the average citizen of Mondstadt was concerned, that was alchemy.\\nAt least until the day ___ suddenly appeared and decided to stay in Mondstadt.\\nThis young man displayed the true prowess of alchemy to all, bringing with him a massive corpus of wisdom that even the Sumeru Akademiya did not possess.\\n"The universe is heaven reversed, and the earth is a dream lost to time. This is dust, the most basic form of complex life."\\nAs if to provide evidence for this claim, ___ lifted the burnt ash of the flower that once grew atop a Dendro Slime\'s head.\\nSeconds later, a Cecilia sprouted forth from the ash in his hand.\\n"And this... is new life."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "___ has a very important job within the Knights of Favonius but does not often appear in public.\\nStill, he does not have the strange and eccentric temper that people tend to assume of academics. In fact, he is earnest in all his dealings.\\nHe is, however, of the persuasion that it requires more energy to maintain relationships established on excessive enthusiasm.\\nAs a result, ___'s equivalent of friendship involves maintaining an appropriate degree of distance.\\nOn days when he shuts himself away in his laboratory to focus on his work, or heads out into the wild to gather materials, no one in Mondstadt will be able to find him.\\nYet ___'s tendency to avoid social interactions does not make him a cold-hearted person.\\nHe delights in giving guidance to his assistants, Timaeus and Sucrose.\\nHe finds pleasure in giving his sketches to the citizens of Mondstadt.\\nYet he cannot help but feel sincere disappointment that Lisa, for all her great talents, has chosen to remain a mere Librarian.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '"___ got into Mondstadt because of his master\'s recommendation letter."\\nThis statement is technically true. But Monstadt\'s gates are open to everyone, and he would have been quite welcome even without the recommendation letter.\\nIn fact, ___\'s life in Mondstadt may even have been more comfortable without it.\\nThis is because the recipient of the letter was the famed travel writer, Alice, an old friend of ___\'s master, Rhinedottir.\\nAfter receiving the letter, Alice considered its requests.\\n"So, Rhine said that you\'ll need a laboratory... And not one of a size that a civilian could build, either. Hmm... I know!"\\nAnd just like that, she threw him into the Knights of Favonius.\\nThe work of the Knights was actually quite easy for ___, requiring only five percent of his energy.\\nThe rest of his energy could be spent on experiments, with the Knights\' full range of apparatus at his disposal, he thought.\\nAnd yet...\\nAlice has a daughter, named Klee.\\nYes, "that" Klee.\\n"We\'ll be a family from now on, treat her like a real younger sister!"\\nFrom that day forth, cleaning up after Klee would come to take up most of ___\'s remaining energy...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: '___ has no memory of any blood relations. From as far back as he can remember, he was already adventuring deep within domains with his master.\\nOf course, Miss Alice, the Knights of Favonius, and that traveler who had a sense of the stellar depths about them... They are all important people. And yet his master is unquestionably the most special to him.\\nFor ___, she is his only kin.\\nShe was a cold and strict woman who raised him and taught him the secrets of alchemy.\\n"The universe is the sable essence of the true starry sky... Earth is the accumulated memory of time and being...\\nChalk: that is you. Soil is where alchemy derives its name, and is the basis of all life. And this..."\\nShe demonstrated her technique before him as a huge life form burst from its culture tank in a shower of shattered fragments.\\n"...This is new birth."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: '___ once led a simple and content existence.\\nThere was no need for him to contemplate anything. Life was uneventful, its meaning consisted of nothing more than accompanying his teacher, doing what she asked of him, and meeting her expectations.\\nBut one day, deep in the heart of a dungeon, master and apprentice discovered an artifact known as The Heart of Naberius.\\nAnd with that, his master disappeared, leaving naught but a note, a recommendation letter, and a classical text behind.\\nUpon the note was written: "___, go to Mondstadt. Find my old friend, Alice, and give her the recommendation letter. Then, complete your final assignment."\\nThe classical text was one of the last extant manuscripts of the Opus Magnum from his master\'s collection.\\nIf one were to push the definition a little, she had left him another gift — the title of Kreideprinz, and with it, a written acknowledgment that she had nothing further to teach him.\\nIn the past, ___\'s assignments had always been very difficult.\\nHe had always believed wholeheartedly that his master would make good on her threat to leave him, should he fail.\\nBut this assignment she had left to him was far too hard, far beyond the limit of his abilities.\\nDid this mean, then, that he was fated to never complete it, and thus never see his master again?\\n"Your final assignment: show me the truth and the meaning of this world."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'The alchemy that ___ commands is wholly different from any of the arts practiced in the Seven Nations of Teyvat.\\nIts lineage can be traced back to the nation of Khaenri\'ah.\\nKhaenri\'ah was an underground realm, with precious few natural fauna. As such, its alchemy focused more heavily on the creation of life.\\nThis art of creation was known as "The Art of Khemia."\\n___ had learned of this in his youth from reading his master\'s notes.\\n The next stage after "soil" is "chalk," which was also something his master had mentioned.\\n"Chalk is the spotless soil, and was used to make primordial man."\\nNow, ___ understands alchemy in far greater depth than he did in the beginning, and his knowledge on the subject is far more comprehensive.\\n"From soil was birthed chalk."\\nThe profundity of this statement is well understood by ___ now.\\nSuch ineffable secrets are bound up with his fond memories of his master.\\nShe was not his birth mother, but there is no doubt that his life stems from her.\\n"I hope this isn\'t just wishful thinking, but... when parents speak to their children about \'the meaning of this world\'... surely they just mean the pursuit of a happy life?"\\nFrom time to time, ___ finds himself musing on this sentiment.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "___'s Artwork",
      title2: null,
      text: '___\'s interest in drawing and painting began back in the days of traveling with his master.\\nAt first, he would simply illustrate his notes with basic sketches. But he soon noticed that the process of rendering things in great detail helped him to intimately understand their physical makeup, which was of great utility to his alchemical studies.\\nAdditionally, it also allowed him to enter into a pleasant state of clarity, in which he needed only to focus on observation and creating his artwork, and nothing else.\\nEventually, ___ became a master artist without ever having received formal tuition.\\nWhen strolling through Mondstadt, he enjoys sketching and painting all manner of living things, but particularly people in moments of joy.\\nSometimes, he even gifts his artwork to his unsuspecting models, believing that when a work of art captures a transient moment of enjoyment, it is something worth treasuring.\\n___ continued to refine his skills in this manner, going from strength to strength — until one day, when he was taken aback by illustrations from Inazuma.\\nHow was it that drawings of such generality could possess such narrative power?\\nAmazed, he decided to give it a go himself.\\n...Eventually, after collaborating with a certain novelist by the name of Xingqiu, "A Legend of Sword" was printed and published.\\nUnfortunately, it received lukewarm reviews, being lambasted as "a dictionary with divine illustrations."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Gaining a Vision came as no great surprise to ___.\\nWhen he received it, he gave it a single glance before continuing to engross himself in his work.\\nHe barely felt any wave of emotion at all, as if this was something to be taken for granted.\\nAs far as he is concerned, his Vision is merely a tool with which he can more conveniently conduct his research.\\nWhat truly sparks joy within him is turning the unknown into the known.\\nOne day, he will understand all there is to know about this world — and Visions are no exception.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
