export const chioriVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "I am ___, the owner of ___ya Boutique. Feel free to find me if you'd like to commission any tailor-made outfits. As for any other requests, it all depends on whether you have enough to offer in exchange. Just the rules of the \"business\" — you scratch my back, and I'll scratch yours. Also, smoking, drinking, and causing a ruckus are all strictly prohibited within the Boutique. That whole \"the customer is king\" concept doesn't fly here... And even when royalty does come into the shop, if they don't adhere to the rules, they'll find themselves being tossed out and kissing the pavement just like anyone else.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Criticism',
      audio: '1101',
      text: "It's up to me to decide who I want to be and to cut my own path. No one can tell me what to do.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: "Chat: Tailor's Cutters",
      audio: '1102',
      text: 'Who says you have to use scissors to cut clothes? Leave those rigid rules behind. I much prefer using my own cutting tools.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Modeling',
      audio: '1103',
      text: "If you really like standing around like this, then why don't you just model for me? I'll design some wonderful clothes for you.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "It's not so much the rain that bothers me, but the mud. It's always such a pain to wash it out of my clothes.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: '...This reminds me of home.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'The way it comes floating from on high makes you want to reach out for it... But the moment it lands on your hand, its beauty dissipates... Hmm, I suppose there are more similarities between snowflakes and fashion than I thought...',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'In the Desert',
      audio: '1204',
      text: 'Hmm, just how can I market high fashion here...',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning. Don't expect me to make breakfast for you. But if you're going to the café, be a darling and bring me a cup of coffee. Black. No cream, no sugar.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Is it lunch time already? I'm not even hungry yet... I don't plan on taking a break now. You go ahead.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "It's so noisy out there. Has everyone in the entire Court of Fontaine decided to go out this evening?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "I'm going to go relax by taking a nice, long bath. Well, I'll see you tomorrow.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Directness',
      audio: '2001',
      text: "Many have expressed displeasure both publicly and privately about my personality, and have complained that my words can be hurtful. But, if you ask me, all those showy pleasantries, greetings, and compliments are far more of a waste of everyone's time. If simply stating the facts seems hurtful, then perhaps they are too insecure.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Brand Vision',
      audio: '2005',
      text: "When I first started conceptualizing the idea of my brand, I reflected on many of my past experiences, and came up with a lot of phrases for the brand's slogan. It's difficult to pick only one phrase for the brand, especially when you realize that every word reflects on a deeply treasured part of yourself... but you can only choose that which best represents you.\\n\"Never admit defeat.\" That's me. That's my brand.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Fitting',
      audio: '2003',
      text: "Take it from me — this one looks good on you. Hmm? You've never seen a style like this before? Aw, that's because you've never met a designer with taste before.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Exchange',
      audio: '2002',
      text: "I know you probably already know this, but I always just say what's on my mind. Maybe you've already grown accustomed to it, but that's just how I express myself, and I'm not going to change. You should also always act like yourself around me — there's no need to hide anything. I promise I'll never criticize you for who you are. Hmm? Don't believe me? After all this time together, have you ever seen me not keep my word?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3006',
      text: "Because I was born in Inazuma, the people of Fontaine have dubbed me \"The Thundering Seamstress.\" If that's what they want to call me, then that's what they can call me. I have no lingering affection for my homeland. After all, everything, including my Vision, only came to me after I decided to leave Inazuma.\\nOh, but that's not to say that I actively dislike those islands where fabric never fully dries. It's just that I haven't found any reason to go back.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "When I was a kid, my parents would send me to a variety of activities to help expend my energy. One such activity was learning the art of the sword. But after some time, I suddenly felt that a dual wielding technique was really strong and impressive. It wasn't long before the instructor approached me and told me to stop practicing using that technique. When I asked him why, all he said was that it wasn't the standard sword technique, and that it was \"improper.\" After that, I never attended his class again. Now that I think about it, it's fortunate that I insisted on following the way I preferred. Perhaps I'm just the sort who needs to keep both my hands busy.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'Tamoto is my first masterpiece. At the time, I was just thinking to stitch together a puppet girl who looked like me to be my model and assistant. Huh? What about a companion? No, I have no need for that.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Navia',
      audio: '4001',
      text: "She used to beg me to help her design all kinds of strange things. For example, little crowns for every handle on a ship's helm... I couldn't help but roll my eyes at her request, and tell her that the most I would do is design her hat like a boat.\\nThose who say I'm ahead of my time have clearly never spoken to her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Lyney',
      audio: '4002',
      text: "I can't make a hat that could hide secrets, but it seems Lyney can enchant his hat to do just that... I'm a little curious about how it feels to wear a hat full of so many tricks and secrets like his. As for me, I don't need the burden of all that, it's easiest to just say what's on my mind.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Lynette',
      audio: '4003',
      text: "The magician's assistant sure doesn't say much, but I know she trusts me. You know, I sure get a lot of love from cats...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Charlotte',
      audio: '4004',
      text: "One time, Charlotte came into the shop, hoping to do an interview with me. I told her there was no point, because there was nothing new to talk about. But just as she was leaving, a drunkard came stumbling into the shop and started causing trouble. She recorded the whole thing... What a fiasco. I've heard of journalists chasing leads, but now it seems news chases the journalists.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Chevreuse',
      audio: '4005',
      text: 'Working with Chevreuse and talking with her are a cinch. So easy, in fact, that whenever I say goodbye to her and return to tending to my customers again, it takes me a moment to shift gears mentally.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Emilie',
      audio: '4006',
      text: "Emilie's perfumes are very popular. We have a business agreement where I ask her to deliver small quantities of perfume she's working on to ___ya Boutique. I let Eloffe secretly spray the perfume in the fitting room, and then I'll let her know any feedback I get from the customers. Even after all this time, I've never once had a customer ever say that my fitting room smelled strange. In fact, they usually come one after another to ask where they can buy the fragrance. Out of curiosity, I always buy a bottle when she brings them to sell in her shop. I have to say that such fragrances which can always bring a sense of refreshment are truly works of art.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Wriothesley',
      audio: '4007',
      text: 'Yes. Some of my friends and partners have mentioned him to me before. I admire his skills at management and diplomacy, but I certainly have no intention of changing my way of doing things.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Kirara',
      audio: '4008',
      text: 'While I was still in Inazuma, there was a cat with green eyes that always liked to follow me whenever I went out into the wild in search of inspiration. The kitty seemed to be very interested in the colors and patterns of the fabric I was carrying. She would even come up and rub her head against my legs when she was in a good mood.\\nLater, I recognized those green eyes again, but on a girl with two tails. The way she gazed at new and intriguing things still had not changed after so many years.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Kamisato Ayaka',
      audio: '4009',
      text: "If I wasn't always slipping away to go play when I was a child, I probably would never have had the chance to meet the young lady of the Kamisato Clan. There was one time when I climbed my way into the Kamisato Clan's courtyard, and her Temari just happened to roll over towards the wall. I could tell that she was both surprised and happy to see me. We played together and chatted for quite some time, but I was discovered in the end. And so, our brief friendship came to an end as I was kicked off the premises.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'More about ___: I',
      audio: '5001',
      text: "I don't think my temper is as bad as people make it out to be. I just don't like wasting my time on trivial matters, that's all. But for some reason, it's always those trivial things that come back to haunt me. So, over time, I've ended up with a bad reputation. I would say that's completely unjust!",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More about ___: II',
      audio: '5002',
      text: "Ever since I was a kid, I've always had a problem with authority. There was a period when I hated the rules, and would always insist on going against the grain. Thanks to this headstrong character of mine, I've had to go through a lot of suffering. But eventually, I came to understand that rules aren't completely a bad thing. What I really can't stand is the feeling that I can't make decisions based on what I truly think.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More about ___: III',
      audio: '5003',
      text: "When I was little, I used to always look forward to the summer festival in my hometown. Every year, people would take out the most vibrant and beautiful clothes, and carefully put them on before joining the crowd...\\nEvery time the festival came around, there'd be all of these brightly colored spheres hanging from people's belts, goldfish that you couldn't scoop up from the bowl no matter how hard you tried, apple candy so sweet that even the children couldn't finish them all, and fireworks so beautiful that they could have only come from the Naganohara house... I always had a lot of fun at such festivals, but even then, I would always feel like something was \"missing\" when I went home at the end of the night. It was only after I got much older that I realized I must have wanted to become more than just a spectator at such a wonderful event.\\n...It's just like how people will always associate the house of \"Naganohara\" with fireworks. I hope that one day, people will also associate festivals with ___ya clothes.\\nHehe, just thinking about the prospect of that gets me really fired up. Alright, time to go back to the shop and churn out a few more designs.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More about ___: IV',
      audio: '5004',
      text: "Although I can get quite immersed in my work, I also enjoy living in the moment. When I have some free time, I would often pack some food and find a lovely place in nature to take a cozy midday nap, before returning home, relaxing some more, and then finally falling asleep to my favorite music. Oh, and other times, I like to go out for food with my friends, talk about everything that's happening in the world, and party until everyone's completely hammered. Honestly, it all just depends on what I feel like doing in the moment. Just as fashion only exists in the moment, I also love living in the moment. So, what do you think? Want to go out with me tonight and enjoy a whole night of fun?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More about ___: V',
      audio: '5005',
      text: "I love Inazuma's petite desserts, as well as all culinary dishes subtle and light. Similarly, I also like the feel of my homeland's fabrics, as well as the practice of taking a bath after a long working day. But on the flip side, I also adore the soft waves of Fontaine's seas, as well as the beautiful scenery underneath the waters.\\nSometimes, I wonder if everything is in fact predestined, and if I'm still living in the shadow of my past. But then, another question always follows — would the answer to that really change anything? In any case, I'm still me, living in my present. Even if I'm only the way I am due to what has happened in my past, my future is still in my own hands, and no one in this world can really change that.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "I'm pursuing my dream through my work, and exploring the meaning of freedom through my art. What's the point of spending years and years of your life over something that's not near and dear to your heart?",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "___'s Troubles",
      audio: '6012',
      text: "Sometimes, I worry that I haven't made as much progress as I'd hoped, and thus, it'd be hard to know when I would actually realize my dream of making ___ya renowned throughout the world. Still, that's no reason to question or abandon the dream. Rather than worrying or doubting myself, my time would be better spent creating a few more designs.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: "I can never forget the Inazuman desserts I used to indulge in as a child. But rather than the joy of tasting them, I've always been more interested in the process of making them. Had I been less drawn to the fascinating world of fabrics and color, the world would have gained another dessert chef.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I can't handle food with particularly strong flavors, like Haggis, for example. The experience of eating it is kind of like... suddenly getting hit with a faceful of Geo Specter out of nowhere. Does that make sense to you?",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Mm, I do love this dish. Why don't you bring me some more next time. Don't worry, I'll also bring a gift for you in return.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Not bad. I think this would be most enjoyable after a hard day's work in the shop.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Ugh, I'm not fond of this flavor. Bring me something lighter on the palette next time.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "Yeah, yeah... Happy birthday, or whatever. Just tell me if there's a gift you like — I can't be bothered to try and guess what you want. Hm? Too direct? Alright then, why don't you grab Navia, Kirara, and the others, and maybe a few of your friends as well. We can have a party tonight at my place. I'll take some notes on the gifts that the others have prepared for you, and make you an accessory right then and there. Ten thousand mora that you'd like it. Haha, call it the confidence of the owner of ___ya Boutique.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: '...No good. Still feels too ordinary.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: '...Not bad, but it\'s still lacking the "wow" factor that makes it really stand out.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Oho... That's more like it. I think I've got it.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Of course, as a master of my craft, my hands will never shake while cutting fabric, but I'll admit, the excitement and anticipation has my heart really beating right now. Thank you for staying with me the whole time I worked on this piece. It is extremely important to me. I now have far more confidence in myself as I embark on the next step of my journey.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Let's go, Tamoto!",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Next customer!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Lend me a hand.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'I am the cutting edge of fashion.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Delicate as silk.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Scraps of color, scatter!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "The handiwork is alright... though I've made much better myself.",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Ah, so this is what you like?',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Hmm... Let me take note of this.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'My clothes are ruined...',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Are you done?',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Time to teach you a lesson.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Hey, who're you trying to impress?",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I don't make burial shrouds, you know.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: I',
      audio: '500001',
      text: "I wasn't cut out... for this...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: II',
      audio: '500002',
      text: "I'll never... accept defeat...",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'But what about... my brand...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Is that all?',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'How tacky...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: "You've picked the wrong fight.",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Welcome to ___ya Boutique.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Let me guess... Need something tailor-made?',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Let's get out and find some inspiration.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'You push open the doors to the boutique. Situated on one of Fontaine\'s busiest thoroughfares, it is named for its designer.\\nThe crisp ringing of a bell chimes from above as if wishing luck to all customers who step through the door. If the rumors swirling about have even a grain of truth to them, then perhaps such blessings will come in handy.\\n"Welcome to the ___ya Boutique, how may I help you?" The greeting that reaches your ears, while perhaps lacking somewhat in enthusiasm, is filled with assurance.\\nThe owner of the voice shoots you a glance from behind the counter. A striking foreigner with captivating eyes — just like they said.\\n"A personalized, custom job? Or something off the shelf?" Her second question. The tone fills you with a certain feeling — as though the second someone steps through the door, even the highest-ranking aristocrat becomes merely a guest in her kingdom, while she sits high upon her throne, allowing supplicants to choose from among the blessings she offers.\\n"I\'d like tailor-made formal attire." You say. Her expression softens a little. It appears that in this kingdom, customizing the cut of the cloth to the customer and designing a personalized outfit in the Kingdom\'s name is something worth a smile.\\nPerhaps this is the best possible outcome, you muse to yourself. After all, those who recommended the shop to you not only all praised the exquisite handiwork of this designer, but some nearly couldn\'t stop themselves from opening wide their wardrobes to show off the dazzling contents within, as though they wished nothing more than to shove you inside to bask in the clothes\' glory for a day. They even say that the owner of the shop is rarely found within, and if she is on the premises, that means she is in a good mood.\\nBut you quietly swallow all the same, for you know when fortune does not hold you in her fickle favor, then all manner of unimaginable and outrageous things may occur when the owner is in, such as...\\nBefore you can even get a handle on your thoughts and feelings, the bell above the door screams a metallic protest. The boutique\'s door has been kicked wide open by a man swaying and rocking, foul breath reeking of alcohol and language yet more foul spilling out of his mouth.\\n"I—I won! I won the bet, the Boss is in toda—" Though you could not clearly see just what happened, before he even finished speaking, he suddenly flew out the window, drawing an elegant arc through the air.\\n___ brushes her hands and closes the window, before saying to you, as if nothing had happened, "Apologies, the weather has been somewhat inclement of late. All kinds of trash have come blowing into my shop. It\'s been taken care of, so pay it no heed."\\nIt appears this kingdom does not welcome all unconditionally.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '"Ms. ___, what past experiences did you have that forged the success you now enjoy?" — A reporter once asked her this question.\\n___ had hesitated as she searched for an appropriate response in her memories, but simply could not find a good answer. After all, in her own estimation, there was nothing special at all about her past.\\n___ was born into a family of merchants. Though not well-off by any means, she had lacked for nothing in her childhood. Busy with their business, her parents had not been overly strict with her. This, her parents joked, is what had created her carefree and unbridled nature.\\nAt the age when many young girls began to study the art of tea or of flowers, ___ was climbing trees and catching fish with other children... It wasn\'t that her parents never tried to get her to learn. But making ___ sit quietly in front of a tea table for an entire day? Why, that would be the death of her (and of her teacher).\\n—Alright, then let\'s just have her study the art of the sword, said her father.\\nBefore long, ___ was carrying two swords with her to class. "Two is obviously better," she declared, boldly and confidently, dual blades in hand.\\nHer teacher had never seen a student with — his words to her father were tactfully chosen — such personality. And thus a seething ___ was sent back home.\\nSimilar scenes played out many times, yet ___\'s parents were never too harsh with her, only believing "That\'s just how she is."\\nUntil one day, ___\'s mother came home to discover her sitting quietly before the table, staring entranced at a bolt of high-quality fabric. The ___ that was normally bouncing off the walls was nowhere to be found.\\n"Do you like it?" Asked her mother. "It feels so smooth," came little ___\'s blunt answer, "And it\'s so pretty, how was it made?"\\nAnd thus, in the days that followed, ___ sent tailoring teacher after teacher storming off in frustration, just as before. But at the same time, she also learned many tailoring techniques.\\nAlso, in all fairness, it should be mentioned that ___ was already far more well-behaved with the tailors than she had been with all those other teachers.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'When the news of Inazuma\'s Sakoku policy reached Fontaine, the topics of tea-table discussions centered around the "Raiden Shogun" over there, that "Vision Hunt Decree," and those ceaseless thunderstorms on the islands, as though discussing some sort of fantastical anecdotes.\\nAfter all, even the loudest thunderclap cannot be heard across the vastness of the sea to the dome of the sky above their heads.\\nBut the people of Fontaine could never have imagined that a storm that would imminently engulf Fontaine had at that time already left the shores of Inazuma, and was quietly heading for them. And the name of that storm was "___."\\nThe storm took shape on the journey out of Inazuma. From the very beginning, it had decided to let loose its thunder upon the streets of Fontaine — the capital of fashion and the City of the Arts.\\nAt first, it was only a few rumblings from the diverse firmament of the fashion world that nobody paid much heed to.\\n"It\'s just a fad, that\'s all," "It\'ll be forgotten in a few days"... That\'s what they all said at first, as though they were discussing nothing more than a cat of unusual coloration that had appeared on the streets.\\nYet after this storm named "___" struck that year\'s Fontaine Fashion Week, nearly all could hear the echoes of its thunderous fury reverberating throughout Fontaine.\\nIn a flash, the headlines of Fontaine\'s papers were completely occupied with a foreign name.\\nSome critics have opined that quality clothes are not just for looking at, but can also be "heard." In this aspect, ___ had succeeded. Every stitch and thread of her clothes told a story: the echoes of waves, the breathing of a forest, a sweet spring gushing forth in the desert...\\nNaturally, the "old guard" of the fashion world could not tolerate this foreign interloper encroaching upon their territory, and thus raised their banners and declared war upon this "invader," using various methods.\\nYet everyone can see how it ended. Not only did they taste the bitterness of defeat, but some of them — for the first time in their lives — tasted the feeling of falling butt-first into the gutter.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "It is unclear when the ___ya Boutique gained the nickname of \"intelligence boutique.\" Even ___ herself is at a bit of a loss as to how this occurred. It's almost as if all she needs to do is share some of the information she has overheard in her shop with her friends, and it will have a tremendous impact on certain matters.\\nLater, she came to understand that rather than the ___ya Boutique being the source of reams of intelligence, it was better to say that rivers of intelligence flowed of their own accord through her doors.\\nThose impeccably dressed merchants and government dignitaries were a kaleidoscopic flock of butterflies, each scattering the pollen known as \"intelligence\" from their fluttering wings onto that gorgeous flower called the ___ya Boutique. Their actual intention was not to pollinate this flower, but rather to flaunt just how much pollen they had to the other butterflies. They consider the amount of information one had on them to be far more worthy of taking pride in than the quantity of gems sewn into one's garments.\\n—Have you heard? So-and-so has yet another new flame!\\n—Oh, and that one, they seem to have sealed a huge deal with the one from the Maison Gardiennage!\\n—You mean the one in charge of transportation? Now I've heard that what he's really transporting is...\\n—Shh! You can't say that out loud!\\n...\\nIf she really had to choose, ___ would rather not listen to all this. She feels allergic to this sort of pollen, with the primary symptom being difficulty in quietly and wholeheartedly focusing on clothing. Thus, when designing new styles and products, she generally does not show up in her shop.\\nBut after realizing the value of such intelligence, she began to take a certain amount of notice on behalf of others. Should the interests of friends or the safety of Fontaine be involved, she would kindly send a letter to give a friendly reminder, or do so to their face. For her, this is no different from tailoring clothes — sewing each element into its proper place.\\nIn accordance with a businessperson's principles, ___ naturally collects some small tokens of \"repayment.\" After all, as she is wont to say: It's only business if there's an exchange.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'If you truly wish to understand ___\'s designs, then you must witness ___ fashioning clothes with your own eyes.\\nThe first time people see said designs, it\'s as if they cannot comprehend what is before them. Does this designer not know what "rules" are? How can women\'s clothes be tailored like men\'s? How can men\'s formalwear use women\'s fabrics?\\nYet there is some quality within that attracts them, and halts them in their tracks. It\'s as if all of this rejection and resistance to the "rules" is so eminently reasonable that it is plainly saying: You are the ones who are wrong.\\nIt is the same for ___ as she tailors the clothes. From the way she treats the fabric, it is as if she has never seen the material before. Her cuts come from unexpected angles, ignoring the direction of the thread, and sometimes suddenly seizing upon adding a completely new structure halfway through, before upending her own work once again...\\nSometimes, she will even draw her sword and swiftly cut the first-rate fabric before her with a clean slash, as though she were not making clothes, but rather dueling — as though she were fighting with the fabric in her hands, vying for authority, with her emerging as the ultimate victor.\\nNo one makes clothes as she does, much less converses so with the fabric. Her workstation becomes an operating table, and she knows just what the perfect form of the fabric is, with each stroke of her blade excising lesions and sores from her patient...\\nAn employee once complained to ___ that it was too difficult to cut the style she requested.\\n—"Why? Are your scissors not sharp enough?"\\n—"No, that\'s not it... It\'s just..."\\n—"Then you can cut it."\\nShe will make you feel that if you cannot cut and trim clothes exactly as you please, then that is because you\'re simply too foolish to do so. Yet when you see the clothes she tailors, you will feel that if you cannot live exactly as you please, then that is yet more foolish still.\\n"Ms. ___, I would like to ask, just how do you design your clothes?" —Came the reporter\'s question.\\n—"However I want."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Dreams. Such an ephemeral word, far flimsier than even the thinnest silks ___ has laid hands on. Yet when worn, they can be heavier and more suffocating than the thickest fabric.\\nShe chased her dream all the way to Fontaine, and yet when she finally managed to catch up to it, she discovered that it had once more run even farther away of its own accord.\\nSo, what next? Take up the burden of her dream and forge ahead, or just be content with what she had?\\n—No. ___ firmly told herself. I choose neither.\\nShe enjoyed the sweet aftertaste dreams left, the satisfaction that filled her. Yet she hated using dreams of the future to urge herself onward. That was itself a kind of shackle.\\nShe chooses to live in the present.\\nShe will work tirelessly day and night on a piece of clothing, just so that it might grace the stage of Fashion Week. She will also disappear for weeks on a whim, enjoying every sight along the way, the starry sky overhead every night, until finally setting off on the road back home once tired. It all depends on her mood.\\nNone can dictate any aspect of her life to her, no one can tell her what she "should" do; not even her own dreams. It is almost as if she would toss life itself out the window without a moment\'s hesitation, should it prove an obstacle to her.\\n"Never give up" is ___\'s true brand. She has said so herself.\\nStrangely, it\'s as though it is in fact her "dream" that has begun actively trying to draw close to her out of fright. As opposed to her chasing it, her dream is attempting to curry favor with her, like a once-wild tamed beast attempting to cozy up to its new master\'s side.\\n—Ms. ___, you\'ve said that you want your brand to become fashionable across Teyvat. May I ask when you expect to achieve this goal?\\n—Hard to say. Perhaps when I feel like it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "___'s Drafts",
      title2: null,
      text: 'When a Snow-Winged Goose chasing the reflection of the moon leapt into the lake, ___ awoke. She blinked and yawned, gazing at the black evening dress glittering like the star-studded heavens. The shadows of her dream were melting in her mind, leaving inky traces of sadness.\\n"Scissors, please." She pushed herself into a sitting position as her loyal assistant appeared by her side, handing ___ the tool in her hand.\\n"And a pencil." She added, and "Tamoto" pulled out a pencil that seemed to have seen quite some use from who knows where.\\nWhen seeking inspiration, ___ prefers solitude to company, and often sets off on her own with little more than the clothes on her back, disliking burdening herself with this and that.\\nA notebook is something that nags at her, as though begging her to write something down. A map is too confining, as though seeking to draw lines and boundaries through her empire of fashion without her say-so.\\nHer drafts are harder to understand than those of any other designer in the business, for they are often drawn on menus, leaves, or even her own clothing...\\nYet her finished products are also more breathtaking than those of any other designer, as they are the distillation of the scenery she has seen, the characters she has met, and even those melted remnants of dreams...\\n"Done." She looked at the newspaper before her — or more precisely, the tattered remnants thereof — and nodded in satisfaction. She didn\'t even remember how she had picked it up today, but that was irrelevant.\\nHer drafts are born with such spontaneity, and completed with the same free and easy spirit: They are brought back to the ___ya Boutique, copied out onto the toile, and then turned into tea-stained taiyaki wrapping paper before finally being laid to rest in the garbage.\\nAnd as for the essence of the drafts... They are for customers to admire and acclaim, and for being enshrined on the front page of fashion magazines.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'No way forward. Nothing left to do.\\n___ lay prone before the table, eyebrows knitting at her first work. "Tamoto" said nothing, as though sleeping — or perhaps it was that she had simply never awoken. ___\'s habit was to use a small amount of cloth to try out her designs on Tamoto before making an outfit. Should the result prove satisfactory, she would then copy the design onto a full-size model. Yet none of her designs had been able to gain the approval of her teacher.\\nNot long before, yet another teacher had expelled her. She had gradually come to understand that sometimes, it wasn\'t that her teachers disliked her designs, but that they simply didn\'t dare to be the first to adopt such designs. The judgmental gaze of others were threads far harder to snip than the stitches of any clothes.\\n"And what do you think?" She asked the puppet in front of her. "Tamoto" had never complained about her designs, and would happily try on any clothes without protest. But if she could open her mouth, would she say those three words, "I like it"?\\nNot long before, Ogura Textiles & Kimonos had extended an invitation to ___, asking her to work in the shop. ___ appreciated Ogura Mio\'s intentions, for among the children studying tailoring, she was one who seemed to admire ___\'s designs.\\nBut no. ___ shook her head, rejecting the idea.\\nWhen all was said and done, that was someone\'s else shop, someone else\'s name. She didn\'t like the feeling of dwelling within the home of another.\\n"Fontaine..." She whispered softly. The word had been bubbling to the surface of her mind of late, as a hummed tune overheard may linger forever in the ear, unforgettable.\\nThe books said that was the capital of fashion, a city of the arts. The merchants said it was a place that revered entertainment, and that anything interesting would be liked by everyone there.\\nThen, ___ had thought it too far away. It would take months of travel just to get there. Now, she felt that Inazuma was too far away. Her designs would reach few here.\\n"Fontaine... Fontaine..." She murmured the name several more times, as though doing so could pull that faraway country closer to her.\\nAs she thought of "Ogura Textiles & Kimonos," she found herself speaking another name — "___ya Boutique."\\n—It was as though her heartstrings had suddenly been plucked and were now humming. The sounds of "Fontaine" and "___ya Boutique" were two notes that seemed to form a perfect harmonious chord.\\n"Fontaine\'s \'___ya Boutique\'..." She closed her eyes and imagined a sign emblazoned with her name appearing on Fontaine\'s vibrant avenues, and how the people there would sound speaking the strange name. It suddenly all seemed so real to her, as though, at that moment, the real her was already in Fontaine, and the "her" left here was merely a shadow she had carelessly left behind in Inazuma.\\nShe swiftly sat up and left the house without so much as a word to her parents. They were shocked, and looked at each other in dismay, guessing that perhaps she was going out for a walk to unwind. Yet when she next returned, she had already said her goodbyes to some, and left a few others with no doubt as to what she really thought of them. Either way, the name "___" would certainly return to Inazuma\'s shores long before she did. That was the oath she swore.\\n"I\'m leaving tomorrow," She said to her parents. That melody humming internally was urging her forward, and she had to go chase the her that was in Fontaine.\\nHer mother looked at her father reproachfully, as if to say "Of all the traits she inherited, it had to have been your personality."\\nNaturally, her parents didn\'t try to stop her, as they knew very well that once this child said something, it was already set in stone.\\nAs ___ returned to her room to pack her things, the items on her table suddenly shifted, startling her.\\n"Tamoto" slowly turned in circles, as though showing off the clothes ___ had made for her, before happily floating over to ___— and in the puppet\'s outstretched hands was a brilliant Vision.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
