export const noelleVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: 'VO_Noelle_Hello',
      text: "My name is ___, maid of the Knights of Favonius, and it's my pleasure to be joining you on your adventure today. Should you encounter any problems at all at any point throughout your journey, please do not hesitate to call me and I will be delighted to provide you with my full assistance. Yes, starting right now — what do you need?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: A Favor',
      audio: '1101',
      text: 'Leave it to me! All of it, whatever it is! ...What... exactly is "it"? I didn\'t quite catch your request...',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Rest',
      audio: '1102',
      text: "You seem tired. Would you like some tea? I'll brew you some. Do you take sugar? One cube, or two?",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Being Reliable',
      audio: '1103',
      text: "Whenever you need me, I'll be there.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: 'VO_Noelle_When_It_Rains',
      text: "Oh dear, everyone's laundry is still on the line! May I be excused to fetch it in?",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: 'VO_Noelle_When_Thunder_Strikes',
      text: 'Please stay indoors until the storm passes. I will deal with any urgent outdoor business.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: 'VO_Noelle_When_the_Sun_Is_Out',
      text: "Mmm, such fair weather. Why don't we do a bit of sunny work? Oh, what sort of work is that, you ask? Haha, well, anything that makes you feel bright and sunny too.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: "Ahh... Can you hear the Anemo Archon's voice on the breeze? It calms me down whenever I get flustered.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: 'VO_Noelle_Good_Morning',
      text: 'Good morning! Breakfast is served. I will be on hand the whole time. Should you find that anything is not to your taste, please, do not hesitate to let me know.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: 'VO_Noelle_Good_Afternoon',
      text: "Ready for your tea break? Please wait here while I get it ready. Oh yes, I also made Lighter-Than-Air Pancakes! You simply must try one, it's my specialty.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: 'VO_Noelle_Good_Evening',
      text: "Everyone has free time in the evening, and that is when I am busiest. Where have Amber's washed hairbands been placed? How many new eyepatches did Kaeya buy? Keeping track of all these things is a maid's responsibility.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: 'VO_Noelle_Good_Night',
      text: "Please get some rest, you must be tired from today's adventure. I should head back to the Knights of F— Sorry? You want me to watch over you until you fall asleep? I—I... I mean, of course, it's no problem. But, um... You're not just teasing me, are you?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '12': {
      title: 'About ___: Discipline',
      audio: '2001',
      text: "In my job, I do the exact same things every day — a far cry from being a true knight, that's for sure. But ultimately, this is all part of my training, and when it comes to training, actions speak louder than words.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Disagreement',
      audio: '2002',
      text: "I'm a bit useless in an argument because I can't really explain my reasoning clearly. People find that hard to understand, so instead, I try to just get on with my work in my own way. But then they call me stubborn. All I try to do is convince people with results instead of trying to talk them round... Is that really stubborn of me?",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Identities',
      audio: '2003',
      text: "I am devoted to what I do, but make no mistake — I devote myself freely. A maid, to me, is the most liberating job there is. I'm a chef, a gardener, a warrior, a guide... I can be anything you need me to be!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Reminders',
      audio: '2004',
      text: "Even when you're too busy to eat three square meals, never eat something if you don't know where it came from, and always maintain a balance between meat and vegetables. Oh, and no swimming right after a meal. Haha, I do hope you're not thinking, \"that's too much trouble, I'll just leave it to ___,\" are you? ... Oh... but of course, if you are... Well then, just leave it to me.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Welcome Party',
      audio: '2005',
      text: "So I hear you're an Honorary Knight of Favonius? I envy you! I suppose that makes you my senior... Anyway, it's about time someone threw you a welcome party, surely? Leave it to me!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 384,
              questTitle: 'Reunion With the Dragon',
              chapterId: 1002,
              chapterTitle: 'For a Tomorrow Without Tears',
            },
          ],
        },
      ],
    },
    '17': {
      title: 'About the Vision',
      audio: 'VO_Noelle_About_the_Vision',
      text: "To be honest, I'm feeling a little dejected. Sure, this Vision proves that the Archons think I'm worthy, but why is it a Geo Vision? I mean, Geo's the furthest thing from Anemo, and for a Knight of Favonius...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: 'VO_Noelle_Something_to_Share',
      text: "I actually really like the smell of wine, I'm just not of drinking age yet. There've been a few times when I could've had a little taste if I'd wanted, and no one would ever have known... but I resisted the temptation. I feel like the first time you try it is probably really magical, so I want to save it till I'm older.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: 'VO_Noelle_Interesting_Things',
      text: 'A maid is required to keep everyone\'s secrets. That\'s why my favorite flower is the rose. Here in Mondstadt, the rose represents the saying, "As wine bottles are corked, so too my lips are sealed." It reminds me to— What? ...Roses represent love in your hometown? I—I had no idea the rose held such a... passionate meaning.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Amber',
      audio: 'VO_Noelle_About_Amber',
      text: "I really look up to Amber. Not only is she an accomplished knight, but she's a kind person too. She taught me how to make a Baron Bunny. I keep it on my person for luck, and it looks quite alright I think. Oh no, please do not be alarmed. There's no risk of explosion whatsoever.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Klee',
      audio: 'VO_Noelle_About_Klee',
      text: "I've always been curious as to how she managed to become a fully-fledged knight at such a young age. I actually went to ask her for tips once, but I'd barely started talking to her when she grabbed me by the hand and took me outside the Knights headquarters to play with bombs. I thought it was some kind of training exercise at first, but Jean found us, and we both ended up in solitary confinement...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Jean',
      audio: 'VO_Noelle_About_Jean',
      text: "Master Jean has always been my role model, both in terms of ability and dedication. She holds herself and others to the same high standards, so if there ever comes a day when I meet with her approval, it will be the ultimate acknowledgment of all my efforts so far. Until then, there's no room for complacency!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Varka',
      audio: 'VO_Noelle_About_Varka',
      text: "At first I wanted to join his expedition party and do my part as a maid. But the Grand Master said no — it would give him more peace of mind if I stayed behind to take care of things in Mondstadt. It made me so happy to hear how much he values me! ...Okay, so apparently he said the same thing to a lot of people. But that doesn't change the fact he prizes me too!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Kaeya',
      audio: 'VO_Noelle_About_Kaeya',
      text: "He's a mysterious character! He comes and goes like the wind, and is always occupied with important business. I like the fact that he delegates some of the smaller jobs to me sometimes, it's nice to feel like part of the team, you know... What do you mean, \"errand runner\"? I don't see it like that at all! Okay, well yes, technically I run errands for him. But still, I really appreciate it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Bennett',
      audio: 'VO_Noelle_About_Bennett',
      text: "He's asked me to join the Adventurers' Guild more than a few times, saying that life there would suit me better than with the Knights of Favonius. While I could help him take care of his \"dads\" like the other adventurers... the Knights hold a special meaning for me, and I'm not ready to give up on becoming one yet. No, I simply cannot accept his offer.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Fischl: Tea',
      audio: '4008',
      text: "I think she's from another world, but I don't know the details. One thing I do know, however, is that she loves the Knights of Favonius' library. She can always be found there with her nose in a book. I bring her some refreshments whenever I go in there to clean, and she always thanks me profusely. When I say profusely... I mean she goes a bit over the top, to be honest, and... I actually don't understand half of what she's saying.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Fischl: Background',
      audio: '4007',
      text: 'So once when I was cleaning the library, I noticed a book on the shelf called Flowers for Princess Fischl. At the time I assumed it was just a fantasy novel... I was so surprised to find out the main character is a real person. I could hardly believe it! She must be someone incredible to have a whole book dedicated to her.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '28': {
      title: 'About Barbara',
      audio: 'VO_Noelle_About_Barbara',
      text: "We take tea breaks together sometimes. Often she'll start humming a tune, saying inspiration has come to her. I'm not the right person to give useful feedback on anything musical... But I still love spending time with Barbara.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About ___: I',
      audio: '5001',
      text: "How may I be of assistance? ...Oh, you just want to chat? Okay then! Well, if that's how I can help, then please feel free to chat as long as you'd like.",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Not a problem, I'm here to serve in whatever capacity you require. You needn't be concerned about the way I feel. ...Huh? More tool than maid? I disagree! A tool might help you to complete a million tasks to a satisfactory standard, but it feels nothing. I, on the other hand, feel a strong sense of achievement every time I do something for you.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Th—These treats are for me? Oh no, I couldn't, really. Well... Then I'll make some for you too! I'll go right now, right this instant! Half an hour... Ah, okay, maybe an hour, tops. You can busy yourself with other things first, and I'll be sure to deliver them right to you, hot and fresh out of the oven!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "I spend all my days handling the most trivial of matters, but so long as it helps you in your adventure, or makes your life easier in some small way, I couldn't be happier. That's because each time I get a thank-you, it makes me feel like my work at least has some meaning, no matter how insignificant it seems.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About ___: V',
      audio: '5005',
      text: "Even though I mostly work for the Knights of Favonius, I'm always looking out for ways I can help more people. These days, though, I seem to be spending more and more of my time with you... It might be a bit selfish of me... What do you think?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'My hobby? I really like washing all sorts of things... clothes, floorboards, windows, you name it! Whenever I see something dirty, I just want to give it a good old clean! It gives me such a sense of achievement! ...Oh, you mean the things I do in my free time? Hmm... Same answer!',
      tips: '',
      tasks: null,
    },
    '35': {
      title: "___'s Troubles",
      audio: '6002',
      text: "How to get more for your Mora? Last time I went all the way to Liyue, I visited every single shop to compare prices, and then carried everything back myself... I won't be doing that again though. I was on the road for so long that Jean was convinced I'd been gobbled up by Stormterror along the way!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: 'VO_Noelle_Favorite_Food',
      text: "My favorite is easily a Satisfying Salad. The best of Mondstadt's natural produce on one plate — highly nutritious, and a low calorie count. No, I never get sick of eating it — it's delicious! I've been eating it for ten years now.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: 'VO_Noelle_Least_Favorite_Food',
      text: "I'm not a fussy eater, but I really don't like banquets... The reason being, as the maid, I'm expected to sample every single dish on the table to ensure its quality. Just one bite of each, of course, but it all adds up... Oh, the guilt...",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'How can you make such a simple dish taste so good? My admiration towards you just keeps growing!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'This tastes wonderful! Uh, would you mind teaching me how to make this? After all, it is my duty as a maid...',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Hmm... This is more than I normally eat in a whole day...',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: 'VO_Noelle_Birthday',
      text: "Since you're always so busy adventuring, there must be so many little things you never get round to, surely? Well, you need not worry about them adding up, because today, I am all yours — your exclusive maid for the entire day! Just leave it all to me! ...Also, I'd like to take this opportunity to wish you a very happy birthday!",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'What is this... new power!? Thank you! Now I can be of assistance to even more people.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I cannot rest on my laurels. After all, I'm not even formally a knight yet. Until that day, I must work even harder.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Thank you for the opportunity to accompany you on your adventures, it's taught me a lot and I believe I have improved a lot. As a maid, I should be the one serving you, but it seems you have done more for me than I could ever imagine...",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Everyone in Mondstadt is saying that I'm much more reliable now. Some even say that I'm to be made a true knight soon, but I don't think— What? You think so too? Awwww... Thank you! Coming from you, that is the best compliment I could ever hope for!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Steady as stone.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'I must leave no stone unturned.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Leave it all to me.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Time to clean up.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'As a good knight should.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'As a dutiful maid would.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: "I'll catch up.",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: 'Someone needs assistance.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "All in a day's work.",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Oh, wonderful...',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'A little dusty... Best give it a spring-cleaning!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'I can patch myself up.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: II',
      audio: '410002',
      text: "Ugh, that's going back in the wash...",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: III',
      audio: '410003',
      text: "If at first you don't succeed...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Apply continuous pressure to the wound.',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Let me get this. You need medical attention!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'I am a disgrace... to the knights...',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'But they still need me...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'It was my honor to serve you...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ugh... I missed a spot...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Ohhh, how exciting! Ahem.',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'I will protect you.',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'As you wish.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: '___ has much greater dreams and ambitions than other maids in the Knights of Favonius.\\nLike anyone else in this city protected by the Knights of Favonius, she too dreams of donning the honored armor.\\nEven if her skills are not enough to pass the rigorous selection trials, she still wishes to observe and learn from them every chance she gets.\\nAside from her training, she enjoys her current life, helping everyone in need.\\n"You can leave absolutely anything to me!"\\nThat\'s her signature line. If there\'s anything that you need, ___ is glad to be of aid.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '___ is "the maid of all maids" to many.\\nSuch people also tend to say this of her: "She\'s everywhere."\\nFor example, there was a child who once tried to get a plate during a banquet, but found that there was no way to open the cabinet without all the plates falling out...\\n"___!!!!!!"\\nAll the child needed to do was scream, and ___ appeared. She put the cabinet down on its back, took a plate out, and handed it to the child, reminding him not to have cold drinks immediately after having barbecue. Then she righted the cabinet, cleaned up other plates, and then put them back in order.\\n___\'s ability to be everywhere all at once is something miraculous to many.\\nHowever, the job of a maid is no myth or legend. ___ only does her job to the letter.\\n"No more, no less. As it should be, not as it should not be."\\n___ doesn\'t think there\'s anything special about her — she\'s just a little more conscientious, that\'s all.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "___ is always eager to help, sometimes excessively so.\\nIf you were to ask her how to build a campfire as she passed by, she would not only stop and build the campfire for you, she would also put up the grill racks, season the food, cook it for you, taste it herself to make sure it's done, and remind you to put out the fire when you've finished so as not to burn the forest down. Then she would get back to whatever she had been doing beforehand.\\nOf course, most people don't mind at all that she regularly goes the extra mile. But it can sometimes produce unexpected results...\\nFor example, a merchant from Snezhnaya once came to Mondstadt, ostensibly wishing to get into the winery business. In truth, he had an evil plot to ruin the land, destroy the winery business in Mondstadt altogether and then seize the market with wines from Snezhnaya.\\nHe disguised himself as an honest merchant with his family on a business trip to Mondstadt. Naturally, with them being visitors from afar, ___ gave them a warm reception.\\nInitially, the merchant was delighted with ___'s hospitality; it was a cut above the crude etiquette he had come to expect from most peasants in Mondstadt. However, after a while he began to feel that something was amiss.\\n___ seemed to be able to read his mind: She correctly guessed his schedule, cooked his family's favorite Snezhnayan dishes for them each day, and even knew that his daughter liked to go to bed hugging a ragdoll, presenting her with a hand-made doll she had sewn together herself.\\nThis spooked the merchant, and made him hesitant to execute the next phase of his plan. ___'s warm smile now chilled the merchant to the bone. What else did she know, and what was she really planning?\\nIn the end, the merchant fled Mondstadt with his family.\\n___ was upset for a few days, thinking she had somehow insulted her guests. Little did she know that all of Mondstadt was indebted to her for taking her job so seriously.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Most of the time, ___\'s reliability provides a comforting presence, but there are always exceptions.\\nOnce, she learned that an adventurer was trapped on Dragonspine, so she decided to mount a rescue by herself.\\nThe snowstorm that day was terribly fierce, wiping out any tracks left by humans as soon as they were made. It was impossible to find a safe route to proceed, to say nothing of saving the adventurer amidst the snow.\\nHowever, ___ persisted on searching for the adventurer and eventually found him inside a cave, suffering from severe hypothermia.\\nAt the time, her coat was completely soaked, and the water inside her bottle had turned to ice. Thirsty and hungry, ___ still managed to carry the adventurer down on her back.\\nThe adventurer was saved, but ___, having over-exerted herself, laid in bed for three days straight, suffering from a high fever. Everyone in the Knights of Favonius barely slept out of concern for her during that period. Fortunately, ___ recovered.\\nIt was not the first or second time that something similar had happened, and everyone was deeply worried for ___.\\nIn order to prevent ___ from putting herself in harm\'s way again, Jean had to invent some safe jobs to keep ___ busy. If something were to happen, then Kaeya would have to save the day.\\nDuring the Stormterror threat, ___ was also eager to resolve the threat at its source. However, Kaeya managed to arrange quite a few "urgent matters" for her to attend to inside the city until it was all over.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "___'s petite form does a good job of hiding her great strength.\\nThis does not just refer to her resoluteness or her indomitable spirit, but also her physical strength.\\nOnce, Lisa accidentally dropped her experimental apparatus under her bookshelf and troubled over whether she could remain decent while bending over to retrieve it. ___ made it over in the nick of time, lifting the full bookshelf with only one hand — and not a single book fell out between her hefting it and putting it down.\\nThere was another incident in which several cargo-bearing carts were attacked by Pyro Slimes as they tried to pass through Mondstadt's side gate. As the owners were all in a panic, it was ___ again who came to the rescue — hurling the carts — cargo and all, into the Cider Lake, before leaping into the water herself and retrieving every last item.\\nRumor has it that when ___ was studying the blade, she nearly sent Wagner — who prided himself in his forging skills — into despairing seclusion.\\nIn all, he forged over ten different swords with different alloy compositions for ___, but all would lose their edge after a few uses.\\nAt first, Wagner thought ___ unskilled, but eventually found that the problem was more foundational: the swords just weren't strong enough.\\nPutting his reputation on the line, Wagner finally made ___ a sturdy and heavy claymore that was further reinforced by her affinity for Geo. Only then was her weapon issue (barely) solved.\\nBut don't worry, ___ won't use her superhuman strength unless the situation calls for it, as she is a pacifist at heart.\\nThey say, however, that the very day ___ received her custom-made claymore, she was set upon by a pair of drunken Treasure Hoarders in Drunkard Gorge, who thought her a harmless lamb...\\nLet's just hope that no one else will ever be so unlucky.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "___'s greatest enemy, curiously, is not a person, but Ludi Harpastum itself.\\nDuring Ludi Harpastum, long tables arranged in a circular shape and filled with all kinds of food will be set up in the plaza before the Cathedral for everyone to enjoy.\\nThe food is usually prepared by volunteers who can cook. During this time, ___, who always holds herself to a high standard, joins the volunteers in continuously cooking and serving food.\\nIt's not really any additional work; what's difficult is that she insists on tasting every dish to make sure they are up to standard.\\nThe crispy Moon Pies; the sizzling Mondstadt Pork Chops; the towering Pile 'Em Ups — all the fried and barbecued foods, equal parts delicious and fatty, are customary at the festival.\\nThe smiles on people's faces make ___ truly happy. What makes her less so is seeing her bulging belly. She can't help but let out a sigh.\\nFor the entire month following the festival, ___ will volunteer for the Knights of Favonius' city night patrol.\\nThe festival may be over, but her battle is only beginning.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: '"Warning of Roses"',
      title2: null,
      text: 'The maids of the Knights have many "red lines" that are not to be crossed, and one of these is that "the personal information of the Knights must be kept in strict confidence."\\nThis does not only require restricting outsider access to such information — this restriction also applies to other members of the Knights.\\nFor example, what Jean keeps in her private quarters, the contents of Amber\'s Baron Bunny, the number of special eye patches that Kaeya owns, the number of Klee\'s hidden bomb caches... These things are all top secret.\\nTo avoid leaking such information, ___ used red cloth to make a great many roses — in Mondstadt, this flower means "my lips are sealed."\\nShe specially wove one such rose into her gauntlet as an ever-present reminder to herself.\\nRevealing secrets would be a major dereliction of duty for a maid, and those who aspire to be knights cannot afford such errors.\\nSo you can forget about probing ___ for any secrets. She won\'t tell.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "___ did once wish to fulfill her dream before its time. Some years ago, after failing her seventh selection test, which was really a foregone conclusion, she felt somewhat discouraged.\\nThe etiquette, swordsmanship, the lines she had memorized... had they all gone to waste? She remembered all the strong points of every official knight, but who would remember the hard work of a failure like her?\\nShe had never stopped aspiring to become a Knight of Favonius, but her exhausted body wouldn't let her get back on her feet like she normally would. She felt like someone who had spent days and nights traveling through an icy tundra.\\nAt that moment, the main gate of the Knights Headquarters were flung upon, and out walked Acting Grand Master Jean, who had just been in charge of the selection process.\\nWithout a thought, ___ gave a precise knight's salute.\\nImmediately, she knew that this was too abrupt a thing to do, and wondered what Jean might think of her.\\nBut just as she was wishing that there was some hole she might crawl into to flee, Jean stopped in her own tracks and returned the salute.\\nAfter a moment's surprise, ___ gave a strained smile, clumsy but pure.\\nThis was a lucky day that she would always remember, for she would receive recognition from two all-important sources this day: once from Jean, and the other from the gods.\\nHer hard work had been remembered after all.\\nFrom that day forward, Vision in hand, ___ reaffirmed her belief that she would one day be able to don that armor. That she would be gentle and reliable — and yes, everywhere at once too.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
