export const xilonenVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Hello, I'm ___ from the Children of Echoes. If you'd like me to forge some tools for you, just let me know. But I do have a quite the backlog of commissions at the moment, so even if you submit a request now, it might be a while before I get to it.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Potted Plant',
      audio: '1101',
      text: "*sigh* My potted plant on the porch has died again. I was watering it every day... Don't tell me I overdid it this time?",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Break Time',
      audio: '1102',
      text: "We should take a break after all that running around... Yeah, let's rest here for a bit.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Forge Work',
      audio: '1103',
      text: "...How many forging commissions do I still have to finish? Let's see, one, two... Hmm, not so many as I thought. I'll get to them tomorrow.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Perfect weather for a nap in the workshop...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: '1202',
      text: "Achoo! ...Ah, I'm awake now.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: '*yawn* Time for a nap... Ooh wow, where did my sunglasses go...?',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'In the Desert',
      audio: '1204',
      text: "The temperature's just right... Ah, but this isn't the best spot to lie down...",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning. Did you get some good sleep? Here, drink this. Starting your day with something sweet will boost your mood for the whole day.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "It's afternoon now, which means... *yawn* time for a break. I'll go have a nap, just wake me up if you need anything...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Wow, just look at the time... Yeah, let's call it a day. Let's go get some good food together to celebrate a great day of work.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: 'Good night. Remember to fluff your pillow, otherwise, your neck will hurt in the morning.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Work-Life Balance',
      audio: '2001',
      text: "No matter how busy work might get, you must set aside some time to rest. If you don't stop working, your mind and body will go on strike... And once that happens, your ability to perform good work will just go down the drain.\\nHmm? You can't find any time for a break? Well then, just say that I suddenly needed to see you for something important, and come over to my workshop to take a small nap. I'll help cover for you.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Sluggishness',
      audio: '2005',
      text: "Some of my friends have told me that I can be slow at times, and that I rarely seem to get emotional. For example, one time, I was at a friend's house for a party, and we started talking about the topic of marriage. A friend asked if we would cry when she got married, and before I knew it, everyone started crying, and they were all sobbing and saying that they didn't want to lose her as a friend...\\nWell, I didn't get what everyone was crying about. I mean, isn't getting married a happy thing? You know, she's just getting married, not going away. We could still go visit her.\\nOh? What if she was sad and getting married against her wishes? Oh yeah, I've thought about that.\\nIn that case, I would just come rolling into the ceremony and steal her away. You know, I'm pretty fast, you know. Yeah, I'd save her in time.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: The Forge',
      audio: '2003',
      text: "No matter what you are making, the temperature of the furnace is always crucial. If it's too cool, you won't be able to soften or melt the materials, and it'll be impossible to cleanse impurities. If the temperature is too high, some materials will be unusable.\\nThe way most crafters adjust the temperature is by removing fuel from the fire or adding more wood to burn.\\nAs for me, I would usually add phlogiston-rich gems to control the temperature. Phlogiston-aided flames are much stronger than that of a regular fire...\\nWhat do I do with the gems after the phlogiston is used up? I just find a place to pile them up... once the phlogiston is gone, they have nothing but aesthetic value. If you'd like some, feel free to pick out a few.",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Blessing',
      audio: '2002',
      text: "Auntie Tlazolli said she would make you a Blazegem Inscription as a gift, right? Well, given the current circumstances, I don't think she'll be able to do that for you.\\nI'll have to take up the task. Consider it a gift for helping save Nepecha.\\nHuh? I already forged an Ancient Name for you?\\nOh, no no no, that doesn't count. That name contains everyone else's blessing for you, but this inscription will contain my own blessings.\\nAh, no need to thank me, I'll let you know once it's done. As for what words to engrave... I'll let you decide.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5029,
              chapterId: 1504,
              chapterTitle: 'Incandescent Ode of Resurrection',
            },
          ],
        },
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 15016,
              chapterId: 2060,
              chapterTitle: 'Melodious Chant',
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About the Vision',
      audio: '3006',
      text: "Oh, my Vision? Yeah, it's pretty useful. Having it allows me to more accurately identify the concentration and distribution of the Geo element in various ores. That helps me quickly sort good ore from scraps.\\nOh, does it have a meaning? Huh, I've never really thought about it much. As long as it can help me with my work, I don't care about the rest.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "I often try to forge small ornaments with complex structures to hone my precision-crafting skills. For example, a web-like pendant, or woven scroll earrings... Once I finish a product, I usually give it to one of my friends or neighbors.\\nOh? Can I make rings? Of course! Just the other day, I made a ring in the shape of a Brilliant Chrysanthemum. The design schematic alone took me quite a bit of effort.\\nOh, you'd like one? Sure. Let me see your hand. Once I've measured your finger, I can forge one for you in no time.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: "I really don't get how to raise plants... I've watered them once every three days, pulled out the weeds once every five days, and fertilized them twice in a week, just like the instructions said, and even made absolutely sure that they got the right amount of sunlight, yet all of my plants still withered and died.\\n*sigh* Don't tell me that even gardening requires quite a bit of luck?",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Kachina',
      audio: '4001',
      text: "Kachina commissioned me to forge a drill for her that could not only bore into the ground, but also jump around. It wasn't that complicated to make, but adjusting the angle of the seat was tricky. In the end, Kachina took my suggestion to ditch the seat in favor of a manual control system that connects to the power core of the drill...\\nHuh? Why does Kachina bounce around when she's operating the Turbo Twirly?\\nThat's how she wanted it. She said she prefers having direct sensory feedback while she's driving, so I removed part of the shock absorption system.\\nI do wonder if I should make her some mouthguards next, though. The last thing I want is for her to bite her tongue while using the drill...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Mualani',
      audio: '4002',
      text: "Mualani is an amazing athlete. I've never seen anyone make surfing or gliding on the Spiritways look so smooth or easy. In fact, I have yet to see Mualani ever slip up.\\nHmm? What would happen if a person or Saurian got in her way? Hmm, I'm pretty sure she would just scoop them up and keep gliding along.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Chasca',
      audio: '4003',
      text: "To get Chasca's gun up and running in high altitude was no easy task. First, I had to make sure it would remain stable and reliable in high speed combat. Then, I had to develop standard and special ammunition that could be used for combat at high altitudes. And finally, I had to consider how to solve the issues of recoil and accuracy while flying...\\nBut Chasca told me the last two issues were no big deal, and that she'd be able to manage as long as I installed some basic mechanical crosshairs.\\nChasca has definitely proven to be an expert user of that weapon. Goes to show that she really is a flying ace of the Flower-Feather Clan.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Mavuika',
      audio: '4004',
      text: "Mavuika has approached me with quite a few ridiculous commissions.\\nFor example, she wanted me to make her a heat-resistant sword that could withstand her flames and wouldn't melt in her hands. Oh yeah, she also asked me if I could make her a special pair of sunglasses that would let her better see enemies through the flames in combat...\\nBut the most bizarre request was that bike of hers... At the time, she would keep coming to the workshop to talk about it and insist that I make her a phlogiston-powered vehicle. She even shoved a bunch of design schematics in front of me, and yeah, who even knows where she got those... I eventually couldn't take it anymore and gave in. It took me three whole months to complete it. I heard she's been driving it through the Natlan wilderness and that no one can stop her... So yeah...\\nCompared to all of that, I'd say forging an Ancient Name for an outlander is really a relatively reasonable task.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5029,
              chapterId: 1504,
              chapterTitle: 'Incandescent Ode of Resurrection',
            },
          ],
        },
      ],
    },
    '23': {
      title: 'About Kinich',
      audio: '4005',
      text: 'Kinich is nice, but that Ajaw is really hard to be around.\\nSpeaking of, where did Ajaw even come from? If he originated from some kind of device, then there is actually a chance that I could make him shut up forever. Oh, maybe I should find some time to go over and discuss this with Kinich...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Citlali',
      audio: '4006',
      text: "Citlali would occasionally come to my workshop to buy some ore. According to her, some ores can be crushed into powder and taken as medicine to help her with divinations and ceremonies. Hm? Have I ever asked her to read my fortune? No, I'm not interested in knowing the future. I already have enough to worry about with all my present work. Besides, I always get sleepy during divination rituals...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Ifa',
      audio: '4007',
      text: "Ifa has come to the tribe before to heal some Tepetlisaurs. He is very skilled, and knows how to care for his patients. Even the most rambunctious Saurians will sit quietly when he's around.\\nIfa said it's all thanks to the set of Saurian syringes I made for him. Even without the needle on it, it's enough to deter any person or Saurian from misbehaving. Would you like to see it? I still have a sample set if you're interested.\\nWait here, I'll go fetch the biggest one... Huh? Why are you backing away? The needle isn't even attached, it's completely safe.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Ororon',
      audio: '4008',
      text: "If two negatives make a positive, then a weirdo in a group of weirdos should just be normal, but Ororon somehow still seems a little off to me.\\nStill, he seems plenty nice as a person. He even had Ifa bring a bunch of fruit and honey to the Children of Echoes, presumably because he thought he had caused too much trouble for us. I had no idea you could get such sweet honey from Phlogiston Aphids, so he must know what he's doing.\\n*sigh* How can some people be such naturals with plants and animals?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5014,
              chapterId: 1503,
              chapterTitle: 'The Rainbow Destined to Burn',
            },
          ],
        },
      ],
    },
    '27': {
      title: 'About Iansan',
      audio: '4009',
      text: "I once helped the Collective of Plenty make a couple sets of super heavy weight plates and dumbbells.\\nWhen it was time for the goods to be picked up, Iansan came with a group from the tribe to inspect the finished products. She picked up and checked every single weight before placing them one by one into a cart. After lifting all those weights, she was barely winded, and her face was only a little red.\\nTo be honest, I'm a little jealous of them. Not only are they really strong, but they've also got a way with plants...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Even though I'm a Name Engraver, forging Ancient Names isn't my primary work. Helping people in the tribe forge tools and weapons makes up the majority of my work.\\nAfter all, Ancient Names are pretty rare, but there are countless commissions for other kinds of items...",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About ___: II',
      audio: '5002',
      text: "The most exhausting part of taking commissions isn't the forging work itself — it's trying to decipher some of my clients' confusingly worded requests. I spend so much of my time just helping my client get their ideas straight so they can tell me what they actually want. Then I can finally pick up my hammer and get to work.\\nWhen I see my clients having an epiphany where they finally realize what they want, I don't get any joy out of it anymore. In fact, it makes me want to throw up. So much so that it ruins my appetite.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About ___: III',
      audio: '5003',
      text: "When I don't have any commissions, I would usually make some small gadgets. For example, these shoes I'm wearing use the latest phlogiston propulsion systems, and many new types of alloys. And these headphones I'm wearing can be connected to a record player, so I can listen to a record while I work at the forge...\\nSounds complicated? Not really, it's just easier to put a little extra care into things when you're working on something you like.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "The main reason I became a Name Engraver was because both my father and mother, as well as most of my kin, were also Name Engravers. When I was little, my parents would always tell me that of all the tribes in Natlan, only ours could shoulder the responsibility of forging Ancient Names. They hoped that I could also carry on the tradition when I grew older.\\nSo I agreed to take it on — that's really all there is to it.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About ___: V',
      audio: '5005',
      text: "However, before I became a Name Engraver, I put a lot of thought into whether I should really get involved in such troublesome work. After all, there were a lot of easier jobs I could have picked. Even being a regular blacksmith is easier than working as a Name Engraver, and I could earn more to boot.\\nBut, in the end, I chose this path.\\nForging Ancient Names is an important task that someone must undertake, and given I happened to have the right abilities for the job, it became my duty to inherit the craft. It's just like what my father always said — \"When every person in Natlan takes up the responsibility they can shoulder, Natlan will stand strong forever.\" The job is now my duty, and I perform it regardless of my level of personal interest.\\n...And on top of that, I was the most skilled among those who studied the craft in the tribe. If I didn't become a Name Engraver, that would mean someone else would have to take it on in my stead. The other students constantly asked me questions and copied my homework. Had it become their job to forge Ancient Names, I'm sure they would constantly come bothering me with questions. So I figured that taking the job myself would be better than dealing with all that trouble... Yeah, it's more convenient for everyone, and saves me from having to worry about other people's work all day.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "Sleeping, spacing out, and basking in the sun... When I'm not working, even staring at blank paper seems interesting.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "___'s Troubles",
      audio: '6012',
      text: 'When discussing a forging commission with someone, the thing I\'m most afraid of hearing is, "This request is neither urgent nor important. Just get to it whenever you can."\\nIn my experience, that is basically equivalent to saying, "I might come to rush you at anytime."\\n*sigh* It makes my head hurt just thinking about it, I think I\'m going to go back to sleep...',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'Sugar and chocolate. I work at the forge, and sweets give me the energy I need to swing my hammer.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I don't like water without any flavor. Yeah, yeah, I know that drinking pure water is better for you, but I just can't drink that stuff. Can't you at least add a little bit of sugar? Or if all else fails, a squeeze of lemon...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Mm. Delicious, is there more? Huh? When did I finish it? Just now. I eat pretty fast, you know, and even faster when it's good.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Not bad, I'll have to treat you to some of my cooking next time.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Ah, I'm good for now. I get sleepy if I eat too much.",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: 'Happy Birthday. Here, this universal multi-tool set is yours to keep. It has a variety of drills and hammers, as well as three hand saws and five special-shaped prybars, which should come in handy for you in the wild. Oh, and there is also a set of ropes made from woven leather and metal wire. They should be strong enough to lift even a fully-grown Tepetlisaur. Do you know how to tie knots? If not, I can teach now. Here, watch... First, hold the rope like this, then loop it around...',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: '...Meow?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Hmm, real gold must still be refined by fire. Thank you.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'It seems my eyes are getting sharper and my arms stronger for swinging my hammer. Hold on, let me try hammering something... You should stand back.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "You've helped me so much, I can't just let you leave empty-handed. Here, take this gem that I engraved my Name on. You can use it to find me for help whenever you like. Whether you need me to fire up the forge, or accompany you on a dangerous adventure, I'll be ready to help. This promise will stand until both my Name and this stone have eroded into nothing.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Bring it.',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Hmph.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: '*sigh*',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Hear the echoes of the valley!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "Let the mountain's veins boil!",
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Let engraved names echo!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "I'm keeping a lookout. Don't worry, there's no ambush.",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "There's a lot of good stuff in here, wanna split it? Just kidding, you can take it.",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Hmm, these should be worth something. Go on, take it.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'What a pain...',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: II',
      audio: '410002',
      text: "That's enough.",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: III',
      audio: '410003',
      text: '...Hmph!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "I'll take over.",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Leave it to me.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'The flames... have gone out...',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'The forge... grows cold...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Heh, it's time... to sleep...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'This again?',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: '...How annoying!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Is it time to go?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Let's get this over with.",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Alright, after you.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'All in Natlan know ___ for her great forging skills and her fame as a Name Engraver.\\nMany come from far and wide to pay homage to her superb skill. Some hope to commission her to forge them weapons, while others only seek to see the visage of this great smith, such that they might have information of great interest to talk about.\\nBut ___ couldn\'t care less about what all her customers are thinking. No matter what kind of ridiculous, fancy titles others give her, before all the honors and accolades, she is first and foremost an artisan. All she need do is refine the ore, and surely and steadfastly hammer it into its final shape one blow at a time, in accordance with the customer\'s requirements. Reputation will not strengthen the blows of her hammer upon the anvil, nor will slander cool the coals of her furnace.\\nHowever, when a customer steps into her workshop, it is not the heat of the furnace that welcomes them, but rather a long form filled with blanks needing to be filled in.\\n"I\'m happy to take the commission. But first, we need to iron out the details."\\n"Effective communication means efficient work. Come on, let\'s talk about just what you want."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'In the eyes of most people from Natlan, tempering tales and forging Ancient Names is a duty without parallel.\\nThe lofty spirit and innumerable heroic deeds that Ancient Names embody serve as the very foundation upon which Natlan stands.\\nAs those who forge Ancient Names, it is only natural that Name Engravers have been invested with all kinds of fanciful ideas related to these Names in the popular imagination.\\nSome have described them as solitary ascetics who refine themselves through arduous training done in isolation; others as battle-hardened veterans who carry the glory and scars of countless battles; others still as chosen ones of extraordinary talent who, having gleaned their knowledge from mysterious sources, shouldered the burden of forging Names...\\nOh, and not to mention those who speak of one personally chosen by the Wayob — a hero who, blessed by the Wayob\'s guidance, underwent a seemingly endless series of mythical trials, vanquishing powerful foes beyond number, and at journey\'s end, finally uncovered the answer that had long lain buried in his heart...\\n"___, are the stories true? Is that how Name Engravers gain their power!?"\\nWhen a gaggle of curious young Children of Echoes finally managed to track down ___, the current Name Engraver, who\'d hidden herself away in the treetops for an afternoon nap, she yawned and replied in a tone of resignation:\\n"First of all, forging Ancient Names is a matter of technique."\\n"Huh? But..."\\n"Meaning that the key is to study hard, then put what you\'ve learned into practice."\\nBut before she could even finish imparting her words of wisdom, the children had already scampered off, wearing dissatisfied pouts. Their wild yet simple imaginings had been disappointed, dropping to the ground like a balloon weighed down by a basket of obsidian. Until another such idea occurred to them, reviving their fantasies and carrying them off into the clouds, they would continue to learn — whether willingly or not.\\n"Heh, it\'s not like I was lying..."\\nThe Name Engraver lay back down, shaded from the sunlight by a canopy of lush vegetation. This was the perfect place for a nap, and the next half an hour or so would be more than enough for her to recharge, ready to tackle the heavy tasks that awaited her.\\n"The only way anyone can ever hope to make those stories come true is by studying their tail off first..."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'In most of her academic studies regarding Ancient Names, ___ was only ever interested in the purely technical side of things.\\nHow to create the most efficient Phlogiston Engravings, how to power various devices using phlogiston, how to make modifications to existing engraving diagrams...\\nWhenever such technical classes began, her fellow students could not help but begin to doze off, their eyelids drooping as sleepiness set in. One by one, they would lean forward onto their desks and drift off to dreamland.\\nEventually, ___ would be the only student still awake. Under her tutor\'s approving gaze, she would even raise the notebook she was holding and ask questions of her own.\\n"Do Phlogiston Engravings rely on phlogiston flow to operate? If I were to dive into a pool of pure phlogiston, would the engraving diagrams on my body activate, shut down, or blow up?"\\n"Does phlogiston exist in a gaseous state? If so, then imagine I were to fill a chimney with it and drop a piece of meat from the top — how tall would the chimney have to be, and how dense the phlogiston, for the meat to be fully cooked at the exact time it reached the bottom?"\\n"If losing about 20% of their body fluids can have life-threatening consequences for humans, then how much phlogiston would a Candlecap Mushroom need to lose before it withered or lost its heat?"\\nThough these questions may strike some as incisive, even slightly peculiar, they did not annoy Teyiz, the renowned Name Engraver, who did not think in the slightest that ___ was asking them to cause trouble.\\nThe highly respected Teyiz was simply amazed that ___ had the patience to endure such tedious classes.\\nMost children had no interest in such things, preferring classes where the elders told them legends about the heroes of the various tribes. They would imagine themselves as those heroes, skipping right past all the hardship and pain, going straight for fame and glory.\\n___, on the other hand, had no interest in these stories. Yet to ensure that she passed her exams on such subjects, she would "bribe" her classmates with milk candies, getting them to lend her their notes. She would proceed to copy it all down, then force herself to memorize everything, just to get a score that would not raise eyebrows.\\nHer strength and her passion lay not in empty fantasies, but rather in precise axioms and equations. As far as she saw it, these were the only things that would benefit future generations; these were the things that were worth studying.\\nAs for those stories... Well, they were neither accurate nor concise, lacked both definitions and axioms, and were simply too chaotic to follow. They held no value for her beyond the points they were worth on the exam papers.\\nDespite seeing all of this, Teyiz chose not to immediately stop ___, nor did she tell her off.\\nBut when the next class was about to begin, and ___ got ready to roll out one of her usual excuses — like having a stomachache, or feeling dizzy, or catching a cold — Teyiz cut right through them, one and all.\\n"I once thought the same way as you do, ___."\\nThus did the kindly Name Engraver address her student, patting the notebook of equations that she held.\\n"But remember — for us Name Engravers, stories and equations are, in essence, one and the same."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'In their classes, the children would sit in a circle around Teyiz the Name Engraver, listening to her stories about the heroes and their deeds.\\nSundjatta, Menilek, and countless other heroes who rose up to fight for Natlan, laying down their lives in the name of justice and virtue.\\nThe children were utterly captivated. Though they had read similar stories in books before, the way Teyiz told them was much more detailed, and far more vivid.\\nThere was one hero who pulled down a stalactite, using it as a spear to pierce a monster\'s eye; and another who crossed a deep ravine with naught but a single length of rope in solo pursuit of a wicked dragon...\\nLayer upon layer of exciting detail brought these heroes to life, making them flesh and blood in the children\'s minds.\\nBut an abundance of detail creates greater possibilities for contradiction.\\nThe first child to look up and challenge the storyteller was a little boy who had read many books and had many questions.\\n"Excuse me, Ma\'am, I have a question. In the records I\'ve read, this hero went hunting in the company of his companions. But in your story, he\'s alone. Why is that?"\\nTeyiz responded gently:\\n"I\'ve read that version too. So, which one do you think is closer to the truth?"\\nBlinking, the child replied:\\n"I... Uhh... Well, that\'s what I read..."\\nThe elderly Name Engraver laughed, then patiently rejoined:\\n"Then you are questioning the truth on the basis of a single opinion, and have neither proof nor evidence."\\nThe child, still refusing to concede defeat, puffed out his chest and replied:\\n"Stories... How can there be evidence for stories? There are so many out there in the world, it would be impossible to prove them all."\\nAfter all, most stories and legends are passed down from mouth to mouth, so over time it is inevitable that they will change and evolve. Even the same tale, the same hero, might end up being portrayed in entirely different ways by the storytellers of different tribes.\\n___, who had been listening for quite some time now, closed her eyes in boredom and began working out a new set of formulas in her head. The idea that there was no order to be found just about summed up her view on the subject too, and as such, she concluded that it was unworthy of further attention.\\nTo their surprise, Teyiz nodded to show her approval of the child\'s answer, and then said:\\n"You speak the truth. Natlan is an ocean of heroic legends, and perhaps there really is no way to verify such stories."\\n"Through generations of oral tradition, countless stories have been twisted or exaggerated, focusing on one person\'s great achievements, while secretly diminishing another\'s..."\\n"But one day, it will be you that holds the forge hammer, and you will be the one tasked with forging the heroic deeds of those who have gone before into Ancient Names."\\n"When that day comes, if the heroic deeds you are to engrave are likewise the subject matter of countless unverified tales, and the focus of unstemmed controversy and debate..."\\n"How then will you strike the hammer? How then will you know which version to settle on?"\\nDespite having been laughing just moments before, the sudden weight of this responsibility made the children fall silent.\\n"Legends have their patterns, and stories, too, their truths."\\n"You have heard many stories, just as you have read many scrolls."\\n"Now, it\'s time for your next class."\\nVery slightly, ___ opened her eyes.\\nIf stories were to be approached from such an angle, she thought, perhaps there might be more in them than she\'d given them credit for.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'The classes continued.\\nUnder her guidance, the children slogged their way through a sea of books and scrolls, their faces scrunched up in frustration, reading the heroic stories over and over again — the same ones, in fact, that they had already heard a hundred, even a thousand times before. They combed through every detail, hoping to find connections that could link these stories to other records, trying to add a rough but traceable chain of evidence to prove their credibility.\\nThe children, who once found those very same tales to be a source of endless excitement and entertainment, now found themselves thinking of ways to avoid the class.\\n"If we keep studying like this, I won\'t want to read another story... ever again!"\\n"I know, right? Everything has to be so... down-to-earth! It\'s so boring when there\'s no room for the imagination!"\\n"How come you\'re so into this, ___? Weren\'t you the one who used to hate reading stories the most?"\\n___\'s classmates looked at her quizzically, watching as the pile of notes in front of their clever friend grew ever higher. It was like she had become a different person.\\n"It\'s not that I don\'t like reading stories. I just don\'t like reading stories that aren\'t backed up by proof or without any basis in fact."\\n___ replied with an air of nonchalance, lazily propping up her chin in the palm of her hand.\\nImagination is a bit like the breeze that blows through the cliffs — light, cool, and all around. Yet no one can pin down the shape of the wind, nor can they force it to stay by their side.\\nBut if there was a way to bring the wind down and turn it into something dark, hard, and silent as stone; a way to forge formless stories into something tangible... For ___, a thought experiment like that held some appeal indeed.\\nBut in her heart of hearts, ___ did not want to become a Name Engraver. She had no interest in capturing fleeting breezes, nor could she summon up the motivation to haul heavy stones around.\\n"I don\'t want to forge Ancient Names. There are so many people in the tribe — why don\'t you just find someone else to do it?"\\n___ had often observed her father at work. He always wore a big smile on his face whenever he talked business with others, but when the time came to start swinging his hammer, his face would naturally settle into a grim expression. Work always seemed to drain people of their energy, leaving them exhausted both mentally and physically.\\n"Dad, why did you become a Name Engraver? You must have had a pretty important reason."\\n"Not really, nothing particularly important. I just thought that people who listened to stories... They have a responsibility to pass them down to others too." Her father replied as he put down his hammer, wiping the sweat from his brow.\\n"But aren\'t there much simpler ways to do that? You could just write down the stories on a scroll, or carve them into stone."\\n"True. Just passing on stories is simple enough."\\nHer mother took out a comb, getting ready to give ___ a new hairstyle.\\n"But not everyone is willing to pass on true stories."\\n"Then what about Ms. Teyiz?"\\n"She... is one of the few who are willing to do so."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Teyiz\'s funeral was held on a low mountain outside of the tribal settlement. For her tribe, the passing of this Name Engraver did not come as a surprise.\\nShe had grown old, and often told those looking after her that she could hear the whispers of the Wayob in her dreams.\\nBut she said that she couldn\'t leave just yet, as there were still things she needed to pass on — once she had found the right person, of course. She could not answer the Wayob\'s call until that time had come.\\n"...With the blood of this land."\\n"Burn away all impurities, and souls gather in the fire."\\nAnd with that, ___ let go of the torch, and the pyre began to roar.\\nShe stayed there the entire night. The next morning, she gathered her teacher\'s ashes into an urn and placed them in the cave she had always spoken of.\\nYet in the world outside, Teyiz\'s story scattered like a wild wind blowing through the valley.\\nOne person, for instance, claimed that he had been initiated into the true craft of forging Ancient Names by Teyiz herself, producing a signed book from her as proof. Another said that she had left them her workshop, showing the key as evidence. But ___ did not concern herself with such petty bickering, such maneuvering for personal gain. What troubled her more deeply were the more insidious lies.\\n"Apparently, when Teyiz taught the stories of our heroes, she would sometimes question their grounding in truth..."\\n"So you heard that too? Good grief... It all sounds quite academic, but what about the children? Surely there\'s a risk of them being led astray?"\\n"Exactly what I was thinking! And I also heard that when she was young, Teyiz concerned herself with nothing other than technical research. Should someone like that really have been teaching our young ones the right way to go about forging Ancient Names? Hmm..."\\nThrough word of mouth, Teyiz\'s story was twisted beyond all recognition — one moment held up as a paragon of virtue and selflessness, the next as a pernicious schemer driven purely by ulterior motives. In one version, she was the hero; in the next, a petty villain.\\nWhen people fail to grasp the wind, they instead begin to create for themselves a variety of boxes, then claim that the wind is whatever shape they\'ve made.\\nBut the true story will only ever be — can only ever be — that dark, heavy stone.\\nThe next day, the tribespeople were shocked to see that ___, usually so laid-back, seemed like a changed person. As if driven by an endless store of energy, she traveled all over the Children of Echoes\' lands, interviewing everyone and anyone connected to Teyiz, reviewing every document she could find that mentioned her old teacher\'s name. Yet that wasn\'t enough for ___. She left the tribe, consulting couriers from the Scions of the Canopy, meeting musicians from the People of the Springs, requesting access to the woven scrolls of the Masters of the Night-Wind, scaling the cliffs of the Flower-Feather Clan, stepping through the gates of the Collective of Plenty... With the utmost rigor and painstaking care, ___ meticulously recorded every single trace that Teyiz had left out there in the world.\\nNot only were these documents what she needed to refute the slanderous stories and malicious rumors about Teyiz — they were enough to dismiss the strange titles that some had bestowed upon her too.\\nWhat ___ wanted to leave behind was a true, unblemished version of Teyiz.\\nOnly flawless ores of the utmost strength could be refined, forged, and eventually tempered into something worthy of being handed down to posterity.\\n...\\n"___, why did you set out to become a Name Engraver in the first place? It all looks so tiring..."\\n___\'s hammer blows rang out loud as her apprentices watched her, resting their chins in the palms of their hands.\\n___ paused for a moment to wipe away the sweat from her brow.\\n"I never really did. But my father, my mother, my teacher... They all did before me. So what choice did I have?\\n"And besides..."\\nShe raised her hammer once more.\\n"Someone has to shoulder the responsibility of telling stories, right?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: '"Dance-Off Stage"',
      title2: null,
      text: 'Given the choice, ___ would prefer making intricate practical tools over forging Ancient Names any day of the week. Things like compressed phlogiston sprayers that let you create Phlogiston Engravings at range, phlogiston-fueled wings that allow for vertical takeoff and landing, even super-size sniper rifles, custom-made for a certain someone...\\nYet among her many inventions, the one that the Children of Echoes have come to know best is without a doubt her specially modified "Dance-Off Stage."\\nAt that time, the latest Drillbit Dance daily dance-off had just kicked off. Dancers took the stage one after another, the searing intensity of their moves and beats as hot as molten lava, driving both the audience and the performers themselves into a state of great excitement.\\nBut just as the contest reached its climax, the old Dance-Off Stage suddenly went haywire. The rhythm and sound became a total mess, making sharp, piercing noises that almost caused a dancer, who was just getting ready to attempt a particularly tricky move, to fall flat on their face. Below, the audience had their hands firmly clamped over their ears.\\nJust as the stage technician began to scratch their head, at a complete loss for how to claw back this embarrassing situation, the music suddenly stabilized. The Dance-Off Stage was back in action; and hearing a languid voice say "Testing, testing, one, two, three..." the crowd\'s attention turned to ___, who they saw holding a bundle of wires in one hand and propping up her chin in the other.\\n"Testing, testing... Can everyone hear me?"\\nAlmost instinctively, the dancers nodded back.\\n"Good. Well, in that case, let\'s get started." Dropping the wires on the ground, ___ gave the blinking technician a pat as she sauntered past.\\n"Let me handle the next track for you too."\\n"___, you... y—you can DJ!?"\\n"Just listen."\\nNo sooner had she finished speaking than a new melody, more powerful than any that had come before, began booming out from the stage. After a moment of stunned silence, the audience erupted, cheering even more enthusiastically than before.\\nWhen the Drillbit Dance daily dance-off came to a close, the organizer paid ___ an official visit, hoping to convince her to accept the dual role of equipment consultant and special DJ of the Drillbit Dance contest, throwing in a more-than-generous compensation package to sweeten the deal.\\nBut ___ declined both titles and compensation, agreeing only to modify the Dance-Off Stage and any related equipment during her free time.\\nAs the conversation ended, the organizer scratched their head and asked:\\n"___, none of us had any idea you were such a good DJ... Where did you learn to do that?"\\n"I picked up a few things when I went over to the People of the Springs to learn about record pressing, but I\'ve been so busy that I\'ve never had a chance to try them out. Want me to teach you a trick or two?"\\n"No, no, no, it\'ll all just go in one ear and out the other..." came the organizer\'s reply, batting off the idea with a vigorous wave of the hands. "But seriously, don\'t you want anything in return? This is such a big ask, and besides, you\'re always so busy to start with."\\n"Well... I do have one request — if you\'ll consider it."\\n"Please, ask away!"\\n"Once I don\'t have to forge Ancient Names anymore, let me come work for you as an official DJ. How about that?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Where should the first hammerstroke fall?\\nAs ___ gripped the haft, preparing to get started on the first Ancient Name she had ever forged, she hesitated, unsure of how to strike.\\nShe had done plenty of research and prepared everything that was required. Just a few days before, she had followed a mining team from the tribe into the mountains to find ore of the very finest quality. She had also asked her dad to modify the furnace so it could hold even more phlogiston, igniting a fiercer and hotter flame that would be intense enough to melt any ore. She had specially re-engraved all of the phlogiston engraving diagrams in the workshop, ensuring that every spark that flew during the forging process was under her complete control.\\nAlright, ___, everything's ready. Strike while the phlogiston's hot, huh? So... Where should the first strike fall? What pattern should I forge? How many strikes will it take?\\nSilence filled the workshop, and even the flames dared not crackle, lest they disturb the craftswoman at work.\\nPlacing her hammer aside, ___ picked up a comb fashioned from the tooth of a wild beast in its stead. This comb had been polished sleek and smooth, investing the intense fire that reflected off its surface with a mild, gentler warmth.\\nIts previous owner was a kindly old woman. Whenever ___ used to slack off, she would offer to comb her hair as a way of coaxing her back to study.\\nThe old woman would also braid her hair into beautiful, intricate plaits — so complex, in fact, that even ___'s mother could not work out how to recreate them, and eventually had to ask for her help. After all, above all others, those were the plaits that ___ loved.\\nThe story of Teyiz the Name Engraver resurfaced in ___'s mind. That was a story she had hunted down and gathered herself; and now, she would be the one to forge it into a Name.\\nA hammer blow shattered the silence. Each strike was precise and powerful, and no detail of the story was left untold. Even the most fleeting nuances now rose up before her, ready to be wrought by her hammer.\\nAs the final drops of phlogiston were consumed and the furnace began to fade, before her she beheld a brand-new Ancient Name.\\nTeyiz's story had been imprinted into this Name, never to be distorted again.\\nAs for whom the Wayob would bestow it upon... Well, that was the Wayob's concern, not hers.\\n___ stood up, dusted off her clothes, and began to tidy up her workshop. She bent down to toss away a few unused pieces of ore into a basket — they were all of excellent quality, and could certainly be re-used for something else.\\n\"Hmm, wonder what I should eat later? Didn't Mom say we'd be having fish for dinner...?\"\\nOne, two, three... the lumps of ore clinked as they landed in her basket.\\nAbsorbed entirely by her dinner plans, ___ didn't notice that there was something quite special about the fourth, amber-colored \"ore\" in her hand.\\nWith another soft clink, the Vision landed in her basket too, which ___ then carried out of the workshop and casually left outside.\\nHumming a song, ___ went off to eat her dinner. It was only during her next forging session that she would finally notice this special \"ore\" of hers.\\nIt was a gift; but also, a responsibility.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
