export const faruzanVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Here's the Akademiya's Distinguished Scholar Award, this is the Sumeru Puzzlers' League Lifetime Achievement Award, and there's something from the Synopsium on Ruin Mechanisms... What do you think? Got any interest in becoming my student? Ahem, just as a note, I am from the Haravatat Darshan. You'll get lost if you try to find me in the halls of Kshahrewar.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Rules',
      audio: '1101',
      text: "A hundred years have passed, yet there hasn't been any change to those dumb rules at the Akademiya...",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Honorifics',
      audio: '1102',
      text: 'Hm? What did you say? I\'m old now, so every other phrase escapes my ears. Try calling me "Madam ___," and I\'ll see if I can pick that up.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Conducting Research',
      audio: '1103',
      text: "Academic research isn't some kind of fad. Topics don't just go in and out of fashion.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "I haven't been a child for many, many years, so I don't see any reason to be excited about the rain.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Whoa! Wh—What? There's nothing wrong with being afraid of thunder even at an older age!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'How beautiful... How awe-inspiring... Achoo! *sniffle* Yes, and very cold-inducing as well...',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: 'How cozy... A breezy, open environment really is the best.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'In the Desert',
      audio: '1205',
      text: 'Hey, how did we circle back here again...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "Youngster, there's nothing quite like an enthusiastic greeting to start your morning! Try to remember now: What are you supposed to say?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'I\'m starting to get hungry... How about we go get something from the Grand Bazaar? Anything goes as long as it\'s not overly "innovative."',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Don't act so surprised — scholars of every generation pull all-nighters for their research. After all, the night offers a precious opportunity to contemplate ideas and topics in peace.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "This ancient text is making my head spin... Let's call it a night here and get some rest. I'll be heading to bed as well, so good night.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Senior Scholar',
      audio: '2001',
      text: 'What is it that you\'d like to learn more about? Different forms of pressure-based puzzle mechanisms? The base layer design of Elemental Monuments? Huh, wait... Did you forget to call me "Madam ___" just now when you asked your question?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: "About ___: A Mentor's Struggles",
      audio: '2005',
      text: "I want my students to truly enjoy the study of ancient texts. If I can't find anyone like that, then I just won't take on any students! Ah, right, about finding someone to help me with my work... It's pretty reasonable for students to help their mentors when they have some free time, right? I mean, even I did that back in the day...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Student Recruitment',
      audio: '2003',
      text: "Serious question: why don't you become my student? I'll tailor research topics to your needs and thoroughly explain everything you need to know. We can focus on practical ways to unlock modern-age puzzle mechanisms, and build on that with some work on the deciphering of associated texts. I've walked the walk, so I can promise you that everything you'd learn would be a great boon for your future adventures. There's no reason not to trust me!",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Solving Puzzles',
      audio: '2002',
      text: "When I was trapped, I spent so long solving puzzles that I became numb to even the flow of time. Now that I'm free again, I no longer have to face the puzzles of the world all on my own. Maybe we'll be able to spend some fun times together copying inscriptions, deciphering runes, and solving puzzles... Every minute should be savored.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Hmph. My illustrious resume aside, my intellectual capabilities have been acknowledged even by the Anemo Archon himself. As for why I still can't find any students... Well, it's not due to any faults on my part or that of my Darshan. Maybe it's a matter of timing? I also received my Vision at precisely an opportune moment, after all.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Kshahrewar',
      audio: '3002',
      text: '"Going forward, Kshahrewar will be the only Darshan dedicated to the study of mechanisms"... Hmph, if you ask me, the Kshahrewar scholars have gotten way ahead of themselves. When I was cracking puzzles all over Sumeru, they were still playing with rudimentary building blocks.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Haravatat',
      audio: '3005',
      text: "Those geezers at Haravatat love to decline my funding requests with the excuse that my research's become too niche and impractical. By that logic, since we're still the Darshan with the lowest enrollment numbers, we might as well close our doors altogether.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'I\'ve visited numerous ruins of all shapes and sizes and interpreted what scant texts and symbols I could find. Ruin Drakes are indeed mechanisms of the highest order. Hmm... perhaps "mechanism" isn\'t the best word for them. You could argue that they\'re antiquated "living organisms" that have managed to survive until the present day...',
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Lesser Lord Kusanali',
      audio: '4001',
      text: "Knowledge is naturally something that cannot be limited or restrained. It's like how Kshahrewar can utilize Haravatat's research findings. All scholars will be grateful to Lesser Lord Kusanali for releasing the Akademiya— no, the entire City of Wisdom from the shackles of selfish desires. All who thirst for knowledge are now afforded the opportunity to search for treasures in the vast sea of knowledge.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '22': {
      title: 'About Tighnari',
      audio: '4002',
      text: "One of my favorite projects is researching rainforest ruins. Ah right, I should ask Tighnari to come with me next time. It's always fun to travel with the living copy of the Rainforest Survival Guide. I must say, even though I've been around for more than a hundred years, he's seen far more varieties of fungi than I've had the chance to taste...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Collei',
      audio: '4003',
      text: "Ah, Collei... She's respectful toward her elders, diligent, and has a hard-working attitude — truly the perfect student! Children like her deserve all the affection and praise. Tighnari really has no reason to be as strict as he has been. Hmph... I need to find a way to win her over... Ahem! What I meant to say was, as a senior scholar, I should find ways to improve the learning environment of younger students.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Cyno',
      audio: '4004',
      text: "Cyno's jokes are composed using modern words and language patterns, but I still struggle to decipher any hidden meaning from his grammar and prose... Huh? It's all just literal meanings and homophones? Really...? Then, those jokes don't have any substance at all...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Layla',
      audio: '4005',
      text: "Sometimes, she'll lower her head and keep her distance when she sees me. However, she's all smiles and greetings at night... I don't quite get her. Anyway, most kids in Rtawahist are geniuses. A quirk or two isn't anything to concern myself with.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Kaveh',
      audio: '4006',
      text: "Kaveh's a good kid with great potential. I had a casual chat with him once about some principles of mechanism construction. Hmm, how should I put it... He's too much of an artsy romantic, but at least he has some original ideas, which is rare nowadays. I've heard that he's fallen on some hard times, so I'm planning to invite him out for a good meal once my funding gets approved. It'll happen soon, promise.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Nilou',
      audio: '4007',
      text: "I remember her; she's a courteous girl. I've only been to the Grand Bazaar a few times, but she's already remembered my name and face, and she's even tried to get the others to stop arguing with me. She really gets it! All youngsters should be more like her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Sethos',
      audio: '4008',
      text: "Oh? You mean the new arrival? Yes, didn't he show up at the perfect time! I still don't know which Darshan he belongs to, but I seem to run into him all the time these days: out on the streets, in shops, at restaurants... It's like he's everywhere at once. The way he nods his head when he talks, it's like... oh, I don't know, like... a little puppy, yes. Eloquent young fellow, too. Seems like a good egg. Anyway, are you acquainted with him? You must encourage him to enroll in my classes. Tell him Madam ___ will take good care of him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Interested in my story? Well, Madam ___'s life started more than a hundred years ago, and her story covers as much ground as some major academic publications. Still curious? Good, willingness to learn is an indispensable trait for scholars. You've got one foot in the door.",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Solving a truly ancient mechanical puzzle requires deciphering a deluge of ancient texts. I don't mean to boast, but they're probably on a completely different level from the ones you've solved on your adventures. Oh? Don't believe me? Then why don't you pick out some of the hardest ones you've done and show them to me? If I spend more than a half hour on any of them, it's your win.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'If I didn\'t accidentally lose myself in that King Deshret ruin, I could have contributed even more to Sumeru... Thankfully, my manuscripts and treatises were still put to good use. Those freeloading Kshahrewar used them to establish the fundamentals of the study of mechanisms. Haha, I\'m not called "Madam ___" for nothing, you know.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "As a scholar, I should have the courage to accept failure and shoulder all of its consequences. I never wanted anyone to pity me, whether it be back then or right now. Also, don't forget that I eventually managed to solve that final puzzle by my own power, and freed myself from that accursed place... Instead of pity, shouldn't people feel encouragement and inspiration from my story?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About ___: V',
      audio: '5005',
      text: "My field of study is nowhere as esteemed as it used to be, and Haravatat has refused me funding more than once. Every now and then, Kshahrewar will try to invite me to teach under their banner, and the conditions they've offered me are truly out of this world. More students, a higher spending limit... I still turned them down, however. No matter what, someone has to keep studying niche topics, so we can expand the frontiers of humanity's knowledge.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'Some greedy merchants and mercenaries try to hawk "antiques" of unknown origin in Port Ormos at exorbitant prices, but their goods are nothing more than secondhand trash. Hmph, I bust their scams whenever I catch sight of one. My skill in antiques appraisal is probably second only to the gods of the Seven.',
      tips: '',
      tasks: null,
    },
    '35': {
      title: "___'s Troubles",
      audio: '6002',
      text: "A hundred years ago, my greatest source of frustration was my inability to decipher the information engraved on ruin monuments. Now, nothing irritates me more than the struggle to get funding. Ugh, it's making my head hurt again...",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6005',
      text: "You can improve the aroma of batter several times over if you bake it in the oven. Next time we're in the kitchen, I'll make some for you so you can get a taste of the flavors from my time. Since it'll be my super secret ancient recipe, I bet you won't find anything like it in the whole Grand Bazaar.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "There's a new dessert that they call Padisarah Pudding. Who decided to create it? Shouldn't puddings be made with rice? These culinary innovations are really getting out of hand. Thank you, but there's really no need to share it with me, even if you made it yourself.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "*munch* This is tastier than the food at most historic establishments. Could it be that the culinary arts haven't stopped improving?",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'The appearance, smell, and taste of this dish are all excellent. Do you read a lot of professional cooking books?',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Hm? This indescribable taste... Are you trying to get me to figure out what this is?',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! Here's a small toy for you. It's an assembly of a number of miniature puzzle mechanisms — you can find a button and lever here, as well as a roller to the side. Just play with it however you want, and I'll take care of it if it breaks. Hmph, and don't think I'm treating you like a child. Everyone, regardless of age, could use a moment of happiness and relaxation.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Ha, aren't you an energetic youngster? So enthusiastic, even about collecting materials.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Oh? Have you unlocked some kind of mechanism? A continuous current of power is streaming in.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Huh, you're really putting a lot into this... Don't worry, it's my responsibility as your senior to guide and protect you. I won't let you go astray.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "The past one hundred years have only afforded me the glimpse of a spindrift floating upon the endless sea of wisdom. As for the fields and puzzles that remain to be studied and explored... It'll be up to you and I to reveal their secrets.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Too late for regrets.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Dare to mess with me?',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: "We'll see about that.",
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Gears of the storm!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Have fun with this gift!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Truth repeats its course.',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'A historical artifact? Hmph... never mind.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'A find that was worth the trip.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Here you go. "Thank you, Madam ___."',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: I',
      audio: '410001',
      text: "This isn't new!",
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'This setback is nothing...',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: III',
      audio: '410003',
      text: "Don't underestimate me...",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Careful, don't lose your life.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Watch and learn, youngster!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'The puzzle... is still unsolved...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: II',
      audio: '500002',
      text: "A scholar's journey... shouldn't end...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Time... didn't stop for me...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Wretched dastard!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'No sense of respect!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Need the help of an elder, huh?',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Been a while since I've limbered up.",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Sure, I'll hang out with you youngsters.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'If you were to open any Kshahrewar textbook, you will find ___\'s record penned proudly upon the author page.\\n"___, outstanding researcher of the Akademiya, winner of the Sumeru Puzzlers\' League Lifetime Achievement Award, one of the seminal scholars of Ancient Mechanics."\\nBut if you were to talk to Haravatat students about their choices, they frown as they speak of ___\'s current state.\\n"Oh, you mean her... Well, her research is... obsolete, and there\'s no way it\'ll pass review, so you might as well find another mentor."\\nSuch reviews, as disparate as heaven and earth, arouse one\'s curiosity as a matter of course.\\nAnd when asked by her juniors, Madam ___ often wears an inscrutable look.\\n"Hmm? You mean to ask what happened these past hundred years? And how things came to this pass? Ah, but this is a secret most great. Come closer, and I shall tell you. Yes, yes, closer..."\\n—And then she gives them a good conk on the head.\\n"First! That curiosity of yours is best served in your studies. And secondly! You shall remember to call me \'Madam\'!"',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'For many researchers at the Akademiya, ___, who has been one of their number since a century prior, has always been a legendary figure.\\nIn her brief academic career, she was able to analyze over half the ruins within Sumeru\'s borders, thereby greatly lowering the difficulty of various further analyses into them and their machinery.\\nThe manuscripts and theses she left behind have laid firm foundations for all researchers who would come after, lighting the way for the countless Kshahrewar researchers\' pursuit of knowledge.\\nHer "end" would also add several layers of mystique to her legendary life, for she would disappear under mysterious circumstances while exploring some ruins, and would never be heard from again.\\nEach retelling of her tale would grow ever more mysterious with regard to her disappearance.\\nSome claim that she came into contact with King Deshret\'s ancient knowledge and was secretly imprisoned within the Temple of Silence.\\nOthers said that her intellect that had been acknowledged by the gods, and that she had been brought up to the heavens to dwell with them.\\nAfter all, people generally believed that a legendary figure should have an equally legendary end.\\nThus did the tale drift further and further from the truth.\\n"So I made a miscalculation while solving a puzzle, and got trapped in the ruins. What? Is there a rule that says that senior researchers aren\'t allowed to mess up?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'What may come as a surprise to many younger researchers is that though ___ has made great contributions to the study of mechanics, she is in fact a member of Haravatat, which specializes in the study of languages.\\nSimply put, her field of study is "the analysis of the structure of and solutions to various ruin devices via the study of stone carvings and other ancient texts."\\nA century ago, the Akademiya\'s studies into Ancient Mechanics were not yet mature. As such, ___\'s ability to prejudge the operations of such machines was indeed of great benefit to the act of exploring ruins.\\nHowever, as the number of as-yet-unexplored ruins grew fewer and fewer, and the Kshahrewar\'s understanding of mechanics grew more advanced, this field of research would slowly lose the luster of yesteryear.\\nBy the time ___ re-entered the Akademiya a century later, no student in Haravatat could even understand her essays, and the mentors could only look at each other in dismay at the topics she would submit for study.\\nOn the other hand, there are many students in Kshahwerar who, having graduated on the back of manuscripts she had written and hearing of her present plight, have come to persuade her to join their Darshan instead, only to see little success in that matter.\\nA certain researcher even went a bridge too far in their persuasion, making such claims as "in the future, Kshahrewar will be the only Darshan that can do research into machines!" and "the era of interpreting ancient texts is over!" This person wound up being chastised by an irate ___ for as long as it would take to sit through two entire classes.\\nThey say that that evening, this poor researcher would be nursing some alcohol in Lambad\'s Tavern, aghast and humbled in equal measure.\\nA friend of his from Haravatat spent the whole night consoling him, while plotting in his heart to debate this old fogey and show her what for.\\nAlas, Lambad\'s Tavern would have a new inconsolable drunk the very next day.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Apart from having her topics rejected during review, ___\'s other major headache is finding a student after her own heart.\\nEach time she plans a lecture at Haravatat, the students in the audience either scratch their heads or struggle not to fall asleep as they are subjected to a veritable barrage of mechanics jargon.\\nIn a fury, ___ will hurl her pointer and begin lambasting her old colleagues in Haravatat for failing in their duties as teachers and training such a generation of juniors.\\nHer fury only grows when she realizes that the students pay more attention to her criticisms of folk from the previous century than her explanations of the principles of mechanics.\\nAnd when students who have a mind to study mechanics hear that Madam ___ would like them to join her, they often express gratitude initially, only to waffle and claim that they must reconsider when they realize, conflict clear on their faces, that it is Haravatat to which they must go.\\nOf course, ___ never hears these "considerations" — the next time they meet, that student will have already joined Kshahrewar.\\nBut there was once, when ___ had accepted Tighnari\'s invitation to investigate some rainforest ruins, when she happened upon the humblest of prayers as she walked: "Oh, great Dendro Archon, please help me learn words faster!"\\nThose words were spoken sadly yet earnestly, and even ___ was moved: To think that Sumeru still played host to people with such a passion for the written word!\\nThat voice did not seem to belong to a child who had yet to read or write, nor did it sound like a researcher of Satyavada Life. And yet this must have been a person of some skill, for normal folk would not be able to delve this deep into the forest alone. Perhaps this person might even have some experience in dealing with machines in the forest.\\nFollowing a brief moment of consideration, ___ concluded that this was a student of suitable age, fitting direction, and excellent quality — someone worth taking on as a disciple for sure. So decided, she revealed her presence from behind a tree.\\nHaving thought that there was no one about, Collei squeaked in surprise, the sound echoing through the woods.\\nTighnari was quick to the rescue, however, and following a stammering explanation from Collei (supplemented with interjections from Tighnari), this most major of misunderstandings was cleared up.\\nWith time, ___ would reacquaint herself with this young trainee Forest Ranger and get to know her better, even bringing her delicious food every time she visits Gandharva Ville.\\nHowever, Collei has realized, to her consternation, that the resolution of the misunderstanding has only made Madam ___... more eager to take her on as a student.\\nSurely there must be lots of Akademiya students who "respect their teachers and their teachings" and "devote themselves to diligence," no?\\nPerhaps even ___ has not realized that there is one other thing about Collei that has attracted her attention:\\nThat despite having experienced inhuman suffering, she has nonetheless been able to gain the strength to face life.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Even ___ herself cannot speak very articulately about the century in which she was trapped within the ruins, for her memories of it are very foggy.\\nThe ruins' origin? Unknown. Its location? Unknown. All she remembers is that it was related to King Deshret's civilization and filled from wall to wall with mechanisms and secret inscriptions.\\nThe mysterious power within the ruins had kept her body in a state of stasis, knowing neither hunger nor physical fatigue, yet not wholly able to shake off mental wear.\\nShe expended all the writing material she had on hand, yet could not translate a single line of text; used up a lifetime's worth of knowledge, yet could not unlock a single device.\\nLying amidst a mountain of manuscript paper, she stared blankly at the cipher-text on the ceiling.\\nThey mocked her, these legacies of an ancient deity — scorned her ignorance and the pettiness of the modern person.\\nDid all she had studied and prided herself upon, did the painstaking research done by generations of scholars truly matter so little in the face of this ancient civilization?\\n___ got up from the ground, picked up a piece of smashed stone, and continued carving upon the tiles.\\nAs long as there was life, there was hope. What was unknown today could be learned tomorrow. Civilizations that existed could continue to evolve. Solutions unreached by the people of today would be uncovered by those who would come after.\\nEven if this was to be her grave, she would leave some deductions and trial-and-error records behind to grant the next unfortunate, trapped soul some chance of escape.\\nThis was the spirit of scholarship — this was why researchers existed in the first place.\\nAfter who knows how long, the entire floor, as far as she could touch it, had been filled with the symbols of obscure deductions.\\nAfter that indeterminate time, her memories began to grow fuzzy and her consciousness faded, and she began to mutter words none could comprehend.\\nAnd at one point — she knew not when — she finally found a way to solve the enigma.\\nIn her addled state, she did not yet realize that the true struggle still awaited her, beyond the walls of those ruins.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: '___ would have to recuperate for quite some time after her escape to regain consciousness.\\nSeeing Sumeru vastly changed from what she remembered, ___ almost believed that she was still within the ruins, trapped in some kind of illusion-generated device.\\nIt was not until someone from the Akademiya came to confirm her identity using past records within Akasha and explained the changes the world had undergone during this time that ___ began to slowly accept that time had indeed passed.\\nThat researcher brought her a Kshahrewar book, and as she cracked it open, she found this written on the title page:\\n"Much of the content in this book came from Madam ___\'s treatises and manuscripts. We hope that her name will still be remembered by future generations of students when she returns."\\nAs ___ read this text, organized by old friends of hers, she felt as if she could almost see her classmates again, talking and chatting about their futures. Yet this was already something from a century ago.\\nThe people she knew, the people who knew her... they were all no longer here.\\nShe had returned to Sumeru indeed, but it was as if she had drifted to some strange land instead.\\nEven wayfarers adrift may return to their home, but she had been left unmoored on time\'s ocean, and there was no returning to the past.\\nThe poor researcher at her side was trying to pick and choose their words such that they might inquire as to what had happened to this senior from times past without touching any sore spots.\\n___ closed her book in silence before speaking of those past events in an even tone.\\n"—It was just a failed experiment. Such things happen to us researchers, don\'t they?"\\nNo matter the location, situation, or generation, time would never stop for ___ again.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Vairambhaka Gear',
      title2: null,
      text: 'This multi-purpose ruin exploration auxiliary support terminal, code-named "Vairambhaka," is one of the few projects that ___ was able to successfully secure funding for from the Akademiya following her return.\\nThis device can perform escort, monster dispersal, sand-clearing, and various other tasks. As per her usual preferences, it also contains various components that can be pressed interactively to relieve boredom.\\nUnexpectedly, this travel essential actually wound up attracting the attention of a group of matra. They barged into her workshop without explanation and began to look the Vairambhaka up and down.\\nUpon discovering its many seemingly useless components, their suspicions were aroused further, and ignoring ___\'s protests that they "were just for stress relief," they planned on taking her latest work apart to examine it carefully.\\nFortunately, the General Mahamatra, Cyno, arrived in time to stop them.\\nAs it turned out, they suspected that ___ had been reticent about her mysterious disappearance on account of some nefarious secret.\\nThey also believed that she had refused to join Kshahrewar so that she could use Haravatat\'s lack of expertise in mechanics to build something dangerous.\\nAfter all, few are the researchers who have not been seduced by the ominous knowledge that King Deshret\'s civilization had gained access to. As such, they came flocking the moment they heard that ___ was making some machine, as if to fight some terrible foe.\\nCyno, armed with records related with ___, was able to dispel their doubts one by one, before apologizing to ___ for his subordinates\' trespass, leaving one of them to help clear up the mess.\\n___, who was just suffering from a lack of manpower right at that moment, was quite satisfied indeed with that arrangement. Quite liking this General Mahamatra\'s style, she invited Cyno to give this new machine a name.\\nCyno thought for a moment before saying that since it could stir up strong winds and had a connection with the matra, she could call it the "Great Vayuvyastra."\\n___\'s puzzlement at that could easily rival that which she had shown in the ruins belonging to King Deshret.\\nFortunately, one of the matra came to her rescue, mentioning that Kshahrewar already possessed a machine with the same name, thus saving them all what would come if she were to inquire about the "deeper meaning" behind such a name.\\nLater, having done her own independent study into how that name was formed, ___ would come up with her own name for her newest work — and thus, the Vairambhaka Gear was born.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Although she has forgotten how she solved that puzzle, ___ does have some vague impression about what happened to her as she left the ruins.\\nThe first thing she felt was light, stinging her eyes till they shut and causing her to stagger back a little.\\nIt was then followed by wind, whipping about her face and flowing across her shoulders like a searing, welcoming kiss.\\nHer eyes were closed, and yet she felt that she could see everything, and following the wind she took one step, and then another, toward newfound freedom after a century of being lost.\\nSuch a long period of time would have changed the environment and eroded her memory, and she might have failed to find the way home.\\nYet she followed the wind\'s guidance even in her semi-conscious state, and it led her swaying through the wilds, avoiding monsters and hazardous areas alike, until she was assaulted by a familiar yet foreign sensation.\\nAs she collapsed, her stomach began to grumble.\\n"Ah... Is that hunger? It\'s been a while, hasn\'t it..."\\nShe had solved the machine, escaped the ruins, but at the end, she had forgotten the most primal of needs!\\nThe wind died down, and unable to continue on, ___ collapsed, falling into a deep sleep."\\n...\\nA sudden wind whipped about a merchant caravan traversing the lands at a leisurely pace, getting into one Sumpter Beast\'s eyes, causing it to turn away and stop advancing.\\nThe merchant was about to pull it back into line, only to notice something glittering in the distance.\\n"Hey, keep up with the group! What are you looking at, anyway? Treasure?"\\n"No, wait... That looks like a person over there, lying on the ground!"\\nAnd in the distance, a Vision shone brightly at the side of an unconscious ___.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
