export const ifaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Ifa: Hey there. I'm Ifa, a sauro-vet from the Flower-Feather Clan. You've probably heard some things about me already, but it's all good. Whatever impression you have of me, I say let's wipe the slate clean and just get to know each other.\\nIfa: Oh yeah, then there's this little dude... that's Cacucu, my assistant. A... \"sauro-vet\" in a different sense of the word, I guess. I hope the two of you will get along.\\nCacucu: Nice to meet you, bro!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Rest',
      audio: '1101',
      text: "*sigh* Most things in life aren't one and done. Soon as you're rested up, let's make a move.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Snacks',
      audio: '1102',
      text: 'Whenever I get to take a break, I always want a snack... Hmm, I got some candy, fruit, and jerky. You want some?',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Calls',
      audio: '1103',
      text: "Did you hear that? Sounded like an animal call. ...Hmm, or maybe I'm just hearing things.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Watch out for when Cacucu shakes off his feathers, or you'll get drenched... Although, actually, you're probably soaked through already. Yeah, never mind.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Did you know that a lot of saurians are actually scared of thunder? It always takes so long to calm them down, hehe. They're so funny sometimes.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Whew, I can barely open my eyes in this wind, it's so cold... No flying for me in this weather.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: 'Looks like I can either lose my hat or lose my breath... The wind demands a sacrifice.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Good morning. Don't be fooled, I'm not a morning person. But I have to get to the clinic to feed the critters, or they'll start making a real racket.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'Oh hey, I was just about to break for lunch too. Wanna come with?',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "I tend to stay home at night. That way, people — and saurians — know where to find me in an emergency. Or if it's a quiet night, then I can just chill out and rest.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "G'night. There's no predicting what life's gonna throw at you tomorrow, all you can do is make sure you're well-rested by the time it rolls around.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Ifa: Friends',
      audio: '2001',
      text: "I'd say I've got quite a big circle of friends. Some cause me headaches, some relieve my headaches, and some of them kinda alternate between the two, depending on the day. It's a nice mix, though. They're all great people.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Ifa: Fulfillment',
      audio: '2005',
      text: "I dunno if everyone's this way, but me personally, I like feeling needed. I find it fulfilling. Maybe the key to a fulfilling life is just having plenty of moments that make me feel that way. But everyone needs to figure out for themselves what makes them tick.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Reminder',
      audio: '2003',
      text: "Ifa: All set for your next trip? You know where you're going, feeling okay, got everything you need?\\nIfa: Cool, well, you're looking good to me, and Paimon's fed, so I think you're good to go... Actually, wait — there's just one last thing I wanna check first...\\nCacucu: No way, bro!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Making Sure',
      audio: '2002',
      text: "You've known me for a while now, so be honest — do you ever feel like I get naggy or overprotective? ...No? Fine just the way I am? Phew... That's a relief 'cause I have a tendency to double- and triple-check everything, probably because I deal with animals so much, and they can't talk to me. Anyway, just wanted to make sure that I'm not being a bother.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3006',
      text: "This thing is actually pretty useful. Sometimes, if a saurian gets tired from flying, I send a little gust of Anemo to prop them up for a little while. Discreetly, though, so they don't notice I'm doing it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "Bribing animals with food is pretty effective, bro. But if you do it too much, they start wanting more treats for the same behavior, or even demanding the reward without working for it. So, whenever I can, I prefer to try and teach them how the world works instead: If you get caught in a trap, you'll get injured, and if you eat the wrong thing, you'll get sick — that sort of thing.\\nIt takes more effort that way, but I think it's worth it. Especially since, in some cases, animals can actually be smarter than humans.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3003',
      text: "If you really pay attention to the world around you, you'll notice it's full of fascinating things. I could spend the whole day just nature-watching if I had the time. But unfortunately, work always finds its way to my doorstep.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Kachina',
      audio: '4001',
      text: "I can tell that Kachina has a real soft spot for saurians. If she put in the work, I'm sure she'd make an excellent vet. But since she's already proven herself as a warrior, she's probably better off focusing on that than trying to study medicine with me on the side.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Xilonen',
      audio: '4002',
      text: "I love chatting with Xilonen. She's always brimming with all sorts of fantastic creative ideas. Sometimes, her insistence on raw functionality can result in contraptions that look a little... intimidating, but then again, intimidation is kind of a function in its own right.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Kinich',
      audio: '4003',
      text: 'Serious question: Does Ajaw technically count as a living being?\\nWhen he came to see me for treatment, I gave him a very thorough checkup but couldn\'t find anything wrong with him. So I told Kinich, "Just bash him on the head a few times until he starts working again."\\nAnd the moment Ajaw heard that, bro, he was suddenly fine again. Strange coincidence, huh?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Chasca',
      audio: '4004',
      text: 'Her work as a peacemaker is extremely important. She cures a lot of ills that are beyond my reach.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Ororon: Try Not to Overthink',
      audio: '4005',
      text: "That guy has a very peculiar way of thinking. You just gotta go with the flow around him. I wouldn't bother trying to figure him out, because honestly he never makes all that much sense.\\nAnyway, he's not a bad person or anything, and he has his own unique ways of showing that he cares. You'll know what I mean once you've gotten to know him.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: "About Ororon: But I Can't Help It",
      audio: '4006',
      text: "...Okay, even though I'm used to him by now, there are still days when I wish I could get inside his head, just to see what is actually going on in there!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '25': {
      title: 'About Citlali',
      audio: '4007',
      text: "Granny's... Yeah, she's a tough cookie. With a colorful pajama collection, hahaha...\\nI try not to get dragged into her and Ororon's drama, so whenever she gives me a message for him, I just pass it right on, word-for-word, no questions asked. I figure if I wanna stay out of her line of fire, the less I know, the better.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Mavuika',
      audio: '4008',
      text: "The Pyro Archon gave me a ride once when I had to get to an emergency visit. Bro, it was so crazy. We get there, my head's still spinning at a million miles an hour, and somehow, I have to patch up this injured saurian... I pulled it off, much to my own surprise. I guess sometimes we don't know our own potential until we're pushed out of our comfort zone.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Neuvillette',
      audio: '4009',
      text: "...What's that? You want me to take care of him if he ever gets sick? Um... you know I'm a vet and not a doctor, right?\\nHmm... Well, Cacucu's certainly taken a shine to him... Alright, fine, bro. I'll do my best.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '28': {
      title: 'More About Ifa: I',
      audio: '5001',
      text: "Ifa: That painting on the board outside my clinic — wasn't me, I swear.\\nCacucu: Hahahaha!",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About Ifa: II',
      audio: '5002',
      text: "I can't actually remember what Cacucu's first word was. What I do remember is being startled awake one morning at five o'clock to the screeching sound of \"Rise and shine, bro!\" ...Heck of a way to be woken up, lemme tell you.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About Ifa: III',
      audio: '5003',
      text: "I passed the flying trials a long time ago now, so theoretically I could call on any qucusaur for help. But ever since Cacucu came along, he's been a little possessive of me — doesn't like seeing me with another qucusaur, I guess. It's all good though. He's a little young for it, sure, but since he feels up to the task, I'm happy to trust him with it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Ifa: IV',
      audio: '5004',
      text: "I want to be the kind of guy who makes everyone feel safe when I'm around. It's a rare privilege to be trusted by other people — not everyone's up to it.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About Ifa: V',
      audio: '5005',
      text: "Being a vet's pretty cool. There's always gonna be those moments where you have to say goodbye, but nothing's ever made me regret my choice. Animals are a lot like kids — they're rowdy little rascals, and they can be hard to get through to. But when all's said and done, they're the future, and I'll always protect them.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "Ifa's Hobbies",
      audio: '6001',
      text: "Singing's a pretty popular hobby in the Flower-Feather Clan. I like to strum a tune and write a song once in a while, too. It could be a good emotional release.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "Ifa's Troubles",
      audio: '6012',
      text: 'Ifa: I think I have it pretty good, to be honest. Nothing keeping me up at night. ...Oh, but it would be nice if Cacucu learned some more useful phrases.\\nCacucu: The heck are you on about?',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Fresh fruit's the best, bro — staves off hunger and quenches your thirst in one go. Plus, I can give a few little chunks to Cacucu.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Fresh fruit is great, but when people add it to a dish, I'm like dude... why can't I just eat it as-is?",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Cacucu: Hit me up, bro!\\nIfa: Where'd you learn how to call dibs, huh? Alright, alright, you can have half.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Mm, really good. I'm gonna grab some fruit juice to wash it down, what flavor do you want?",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Cacucu: For real, now? Bro, look at the mess you made...\\nIfa: No, no! Cacucu... It looks perfectly edible to me. Thanks, bro.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! Wishing you good health and eternal youth.\\nSure, you can't stop the relentless march of time, but you can always stay young at heart — and besides, dude, a bad mood doesn't do your health any good. So come on, just for today, cast your worries aside and let's have some fun!\\nOh yeah, also, what kind of music are you into? I'll play a song.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Is this, like, a warm-up or something?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'You gotta take care of yourself before you can take care of other people, right?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "The gun least drawn is the one you'd better keep in good working order... Oh, dude, what am I saying — I'm a medic, not a warrior. I leave my guns holstered unless I absolutely need them.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Ifa: Thanks, bro! If you ever need a hand with anything, don't be shy — hit me up anytime!\\nCacucu: Hit me up, bro!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: "Let's go!",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Mind the wind!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Cacucu: Up and away!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Cacucu: Oh dear! Oh dear!\\nIfa: Come on, buddy!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Mind your step!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Nothing personal.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: "C'mere, you little rascal!",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Nice one! You got a knack for tracking these down.',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Guess today's my lucky day!",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "If you need help with carrying this stuff, I'll get Cacucu on it.",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'I can barely breathe...',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: II',
      audio: '410002',
      text: "One last try, c'mon...",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Cacucu: Ifa? Ifa!\\nIfa: I know, I know...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "I'm right here.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'You should get that looked at.',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'I thought the war was over...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Sorry, I tried...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: III',
      audio: '500003',
      text: "I could've saved more...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Quit it...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'No way, bro!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: "*grimace*... Why can't you play nice?",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Long trip ahead?',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'First aid kit at the ready.',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Here's to a safe journey.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'In the eyes of the Natlanese, the Flower-Feather Clan lives in the sky.\\nAlthough the Scions of the Canopy bound between their cliffs, and the Masters of the Night-Wind stargaze from their summits, only the Flower-Feather Clan has the privilege of catching clouds and riding rainbows like true knights of the skies.\\nThe sensation of gazing up is one without equal. No obstacles in sight, only a vast plain of emptiness through which humanity yearns to soar, slaking its thirst for a life free of earthly shackles.\\nBut the fires of war spread ever beneath their feet, followed by cries for help. Even a Qucusaur, once wounded, is forced to descend to the earth.\\nIfa, then, is the knight whose eyes never leave the ground, out of both duty and habit. His sharp gaze is adept at picking out trouble from afar.\\n"Be it human or animal, everyone\'s gotta land sometime," ___says with a breezy smile.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '"If humans can be doctors to saurians, then saurians can be doctors to humans," Ororon once said.\\n"...Not all juxtaposed statements secretly make sense," ___replied after a long silence.\\n"Is that so..."\\n___couldn\'t help but feel a twinge of pity at Ororon\'s tone, for the lad was no fool — just in the habit of sometimes spouting illogical utterances to get some reaction out of him. ___knew this deep in his bones, of course. But he couldn\'t help but look back on his life and wonder: How did he get here?\\nNo one can live a life free of things that cannot be helped. Being a vet, for instance, will always be like running a kindergarten — there is no controlling little \'uns who lack powers of reason. All you can do is comfort them... especially when pain must soon follow. Pain from wounds, cleaning wounds, taking medicine and getting injections... Truth be told, were ___himself one of those pups or kittens, he would scarcely have been able to tell the difference between those many pains.\\nAnd when hurt, they cry and they struggle. Such is the nature of all living things. Indeed, losing the ability to feel pain is akin to losing one\'s natural alarm system — worrying in its own right.\\nAnd as are the living, perhaps so too is life. Perhaps sorrows and partings exist to remind one that life trundles ever onward, that saurians and humans alike will grow up and grow old.\\nFor a doctor, this is par for the course. It\'s the price that comes with the profession. At least, that\'s how ___reassures himself.\\nAnd what he receives in return is love and gratitude from humans and animals alike, along with the bonds he has forged with many a "bro" of all types and stripes.\\nAs long as all joy could wipe away helplessness and sorrow... Then his fight would be well worth it.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Sometimes, ___feels that one doesn't necessarily choose where they end up in life. Rather, they tend to slot into positions naturally over time.\\nFor example, he can't remember when he became someone who looked after others. The neighbors' kids call him bro (or big bro). Saurians, in both sickness and health, follow in his wake, croo-ing and crawww-ing all the while. His juniors and seniors alike tip their hats (where applicable) and call him \"Doc\"... ___can't help but feel fear take root in his heart at such treatment.\\nOf course, this respect is also a source of pride and satisfaction for him. So perhaps what gnaws at him from within is the fear that he may one day lose their trust. This spurs him to sometimes go to extreme lengths: making toys for saurian whelps, putting on guitar performances, hauling back bags of fresh fruit for his neighbors each time he returns from treating a patient... Once in a while, one might even spot him helping the tribe's kids with their homework.\\nIt was as though someone had messed with the passage of time. One day, ___was still vacillating between whether to become a vet or not, his memories of struggling up a saurian's back still fresh as new dew. The next, well, life had happened, and he suddenly realized he'd become a reliable grown-up.\\nNot that this upset him. In fact, ___was very grateful. It was just that, occasionally, the tribe's elders would bring up matters of the past, reminding ___of the boy he used to be.\\nSome young children love to hear these old stories. One of these young 'uns, who hadn't yet wiped the Volcano Cake crumbs off the corners of his grinning mouth, burst out laughing when he heard about how a young ___could barely get a book through his head. \"So big bro ___was once lil' bro Ifa! How crazy is that?\"\\nNobody had called him \"lil' bro\" in ages and ages. ___was stunned for a moment, but recovered quickly. He wiped the kid's mouth with a napkin, chortling, \"It ain't that crazy! How old are you, hmm?\"\\n\"I'm six!\"\\n\"Well, what do you know, little buddy? I'm five! How 'bout I start calling you big bro from now on, mm?\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "If you count his distant relatives, Ifa's family is rather large indeed. Theirs is a household renowned for their veterinary skills, but on closer inspection, not many in the family actually pursue that line of work. In other words, neither sentiment nor logic dictated that he had to become a vet.\\nMoreover, studying for such a career is an exhausting process. ___felt that all he had to read while growing up were books on medicine, and the words and diagrams blew through his brain like a breeze — in one end, out of the other. Little ___angrily thought to himself: I don't have to become a vet, do I?\\nHe didn't have to, but soon enough, he found himself over the phase where books were beyond his understanding. Maybe it was due to their frequent visits to battlefields to tend to the sick, but Ifa's parents were affected by the Abyss, and their health was persistently poor. Although he was still young, some sort of revelation came over Ifa, and he often worriedly thought to himself: I... don't have to become a vet, do I...?\\nEpiphany or not, early maturity or not, ___was not yet full-grown before his parents passed away. After attending their funeral, the seventeen-year-old was overwhelmed by a hollow sensation. Now, he didn't know what to think at all.\\nAnd in the end, he became a vet.\\nPerhaps it was for tradition's sake, or mere force of habit, but ___soon became known as the sauro-vet with the finest skills, the gentlest temper, and the strongest sense of responsibility. Once his heart was set, his mind dwelled on other matters no longer. And as the war raged ever fiercer, his list of tasks only grew, but it was this very burden of work that helped him through a difficult period of his life.\\nNow that the war was finally over, ___found himself with time to sit down and think about his life. But really, was there much to consider at all?\\n\"Everyone's got something they gotta do,\" ___decided. \"And I just want everyone to be happy.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "If he gave himself over to his sympathy and adopted every wounded little saurian he came across, ___would have to leave his clinic for a life in the wilderness. He knows himself best — were he to start walking down this path, he'd walk it all the way. That's why he has an unwritten rule: If at all possible, he is not to take in any animals (or humans, or other miscellaneous creatures) long-term.\\n\"No, no, nooo way...\" ___shielded his eyes from his latest little patient's pitiful gaze, \"I'll definitely find this lil' guy a new home... but I'm stretched way too thin to keep him myself.\"\\nHis discipline over the years has been commendable — which is why he's still loath to admit that Cacucu proved the exception to the rule.\\n\"This lil' bro just doesn't grow,\" ___has a whole laundry list of excuses, ready to go. \"He's small, he's round, and can talk, but doesn't really know what he's sayin'... Might be dangerous to leave him all by his lonesome out in the wild like this. S'why I've taken him under my wing... Y'know, for now at least.\"\\n\"Actually, he's being taken advantage of. He's just too embarrassed to admit it,\" Ororon would say, laying the truth bare.\\nBut though Ororon would then pretend that the matter had nothing to do with him, he had in fact \"contributed\" to Cacucu's adoption by pointing at the vegetables in his field sporting prominent Cacucu-beak-shaped holes in their leaves, the gesture a silent accusation directed at Ifa.\\nUnable to come up with excuses, or shake Cacucu off in the slightest, ___was at last forced to (or so he made it look) adopt the former. He even offered to be Ororon's courier for a month to compensate him for the Cacucu-related crop damages.\\nBut taking a step back, this story actually has two gaps, to which ___has remained none the wiser.\\nThe first: The peculiar case of the field. Cacucu is not some foolish saurian, so why did he start messing with Ororon? In truth, the two had been partners-in-crime the whole time. For Cacucu to realize his lofty dream of becoming an assistant at Ifa's clinic, the first step was to get into the clinic at all. And to do that, they had to back ___into a corner.\\nAnd the second: Although ___believes the first time he saw the roly-poly Qucusaur was when he rescued him out on the road, Cacucu remembers another, older chapter to their tale. None know this, but Cacucu's mother was once badly injured, and she may have never hatched the egg containing this little genius of a saurian were it not for Ifa's intervention. And when said saurian pecked through the shell of his egg, he saw ___for the first time. Sadly, ___does not remember this.\\nOn the one hand, Cacucu lacks the vocabulary to relate the incident. On the other, there was never a need to, and so Cacucu has never attempted to inform Ifa. His mother eventually passed on due to old injuries relapsing, and it was a tall order for a small saurian to survive alone in the wild. Having not brushed shoulders with many humans at all, Cacucu quickly decided that Ifa, who had helped his mother once before, was a prime candidate to follow around. And if he could one day become an assistant in that clinic and repay the favor owed, then all the better. What a wonderful feat in the saurian world that would be!\\nWith the first step now out of the way, now came phase two of Cacucu's master plan: figuring out how to play dumb.\\nConsidering Ifa's personality — someone all too happy to shoulder other's responsibilities — knowing Cacucu's backstory could create in him an inexplicable sense of guilt and make him feel somehow accountable.\\nSo Cacucu decided it was best to skip all that nonsense. If they were to become bros, he wanted their bro-ship to come from a point of sincerity, unclouded by the past.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "In all seriousness, ___considered himself quite athletic. And between getting along well with saurians and passing his flying trials with flying colors, he figured he should be able to easily traverse all of Natlan.\\nSo he decided to swing by and visit the other tribes while he remained unburdened by much responsibility.\\nIn the Children of Echoes, he met the skilled blacksmith Xilonen. She proved quite eager, drawing up designs for Ifa's medical equipment without too much debate. He later learned that the Xilonen he'd met had been one very much burdened by responsibility — that of a commission from Mavuika — and so any work unrelated to it had been a breath of much-needed fresh air. Others said that Xilonen was usually impossible to get ahold of (on account of her making incredibly quick escapes into the mountains), so ___counted his lucky stars.\\nIn the Scions of the Canopy, ___felt a vibe similar to the Flower-Feather Clan's — that of everyone living life at their own pace amidst the clouds. He enjoyed his time there, slinging grappling hooks and scaling cliffs. His only regret was that he didn't get to meet that legendary \"Saurian Hunter\" everyone had kept talking about. It was only later on, when Ajaw swung by to visit his clinic, that he would see that wish fulfilled. It was a happy ending for everyone — well, except for Ajaw.\\nBefore he'd set off, Chasca had told ___about a guide he'd find in the People of the Springs named Mualani. His first two attempts to poke around her watersports shop proved fruitless, unless tripping over a Sharky Surfboard counted. Ultimately, he decided to take part in a surfing competition on his own, and it was at the prize ceremony that he at last bumped into her. Upon learning that he'd managed to score third place on his very first time surfing, Mualani showered him with praise. Such warm words from the reigning champ were certainly worth their weight in gold.\\nAs for the Collective of Plenty, their fruits were utterly divine, though the trip would have been much more enjoyable had there not been people challenging him to arm wrestle at every corner he turned. Sensing slim odds of victory, ___declined dozens of invitations under the pretext that he needed his hands to practice medicine. In the end, this chapter of his journey ended with him signing up for three months of fitness classes with Iansan — none of which he attended, even by the time he bade them all farewell with a hearty wave.\\nAs for the Masters of the Night-Wind... it was the closest to the Flower-Feather Clan, and also the most mysterious. ___wasn't even sure what one would do there as a visitor, so he thought he'd just stop by on the way home. As he walked, he couldn't shake the feeling that he was being watched, and yet every time he turned around, there was no one to be seen. Like an Iktomisaurus chasing its own tail, he engaged in this farcical waltz for a long time, muttering to himself as he did.\\nJust as he was about to leave, a cry of \"Ah!\" stopped him. ___spun around for what he hoped would be the last time. There stood a light-haired lady, one hand on her hip and the other pointed at him in anger. Before ___could begin considering what he'd done wrong, someone else grabbed him and made a run for it.\\nEverything happened so suddenly that the details were rather lost in the sauce. As it turned out, ___had unwittingly been dragged into a great granny-grandson chase, triggered when said grandson had decided to hone his invisibility arts by purposefully standing behind passersby. It'd even worked on the tribe elders.\\n\"My dudes, what are 'invisibility arts'? Do they even exist?\" Ifa's genuine curiosity and good temperament eventually quelled the wrath of Granny Itztli.\\nWhen he finally dragged himself back home, his parents asked how his journey had been. There was far too much to say, and he was far too tired, so ___just replied, \"Had a blast. Met lots of cool bros out there.\"\\nBros that I'm bound to meet again, he thought to himself.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Records',
      title2: null,
      text: '___will take some time almost every day to sort through and tidy up his medical records. He spends these rare moments of peace reading through cases new and old, recalling all the illnesses and injuries he has witnessed. Each lesson from the past is valuable, a gem worth sharing with others who would walk this same path.\\nAt the same time, aligning the corners of each page is also a good way for ___to relax his body and mind.\\nBut heroic legends and precious ancient scrolls they are not. These hastily scrawled notes, replete with bland medical jargon, might never draw the gaze of anyone other than their author.\\nBut ___is not merely "drawn." He is often deeply engrossed in leafing through these old files. As he recalls the details of each diagnosis and treatment, he may even sometimes jot down a few extra notes.\\nFinally, he puts the records back in order and returns them to their cabinet. If necessary, he throws in some pesticide and desiccants as well.\\nThese habits bring him through day after day, just as plants grow and wither from season to season.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "One day, noon came and went without Ifa's clinic opening its doors. Something was up, people were starting to say.\\nAt first, the neighbors thought that he'd gone off on call to another tribe and stayed the night there. It wasn't until someone brought a sick saurian to his doorstep that ___emerged, groggy and suffering from a sudden high fever.\\nBefore the visitor could even open his mouth, ___was already muttering, \"All good, bro,\" and giving the saurian a full-body checkup.\\nBut as they say, it never rains but it pours. Halfway through writing a prescription, someone else rushed in, crying out that an Abyssal incursion was coming from the direction of the Cinder City, and that a doctor was needed to save the wounded Qucusaurs there.\\nIfa, again mumbling, \"It's cool, bro,\" followed that rider to the front lines.\\nThe night after everything blew over, ___drank the medicine his neighbor gave him and passed out for an entire day. When he awoke drenched in sweat, he scrabbled at his bedside table for some water. However, what he found instead was a Vision.\\nDue to his high fever, Ifa's memories were somewhat hazy. To him, what had happened yesterday was little different from his usual routine, and hardly the first time he had forced himself to work while sick. In his eyes, he had done nothing special to warrant the heavens deciding that he totally, absolutely, needed a Vision right now.\\nEveryone else, however, had a different understanding of the matter. The chief believed this was a reward for his selfless work, while the granny next door supposed it was compensation for his spirit of self-sacrifice. \"Hey, hey, ma'am, 'sacrifice' is goin' a bit far!\" ___said to that, hastily waving his hands.\\nA child then said to him with wisdom early-grown: \"They say the wind blows people together. Maybe the gods are reminding you that you can rely on your companions when the going gets tough.\" ___didn't refute the kid. That was a sensible thing to say, after all. But then again, he had just let his instincts lead him to do what he was supposed to when the going got tough. Had there been any other option?\\nThey could have discussed the matter for ages without ever reaching a conclusion. Who could say? Perhaps the heavens thought that a cool breeze was just the right fix for his fever. Shaking his head, ___brought things to a close, letting the matter rest.\\nHe wouldn't even use his Vision most of the time — at least, not before he took Cacucu in. After the latter became part of his life, he insisted on having ___take him flying everywhere, punctuating said excursions with squawks of \"Higher, bro! Higher!\"\\nIn times like these, his Vision proved very handy indeed.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
