export const kazuhaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: '"Come driving rain or winds that churn, I shall return, by blade alone, armed, if barefoot, to my home..." I am ___, a wanderer who roams the land. Since we are both travelers, let us journey together for a time.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Nature',
      audio: '1101',
      text: 'This scenery is wonderful... Surely enough to convince anyone to become a wanderer.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Playing a Tune',
      audio: '1102',
      text: 'There are leaves around — and I know just the tune to accompany them, if you wish to hear it.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Bladework',
      audio: '1103',
      text: 'Wherever in this world I roam, I carry memories of my home... This blade... It is the last link I have to the land of my birth.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Taking a stroll in the middle of a downpour certainly rouses the spirit... but it's best to dry your clothes as soon as possible after the rain stops.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Compared to the storms I've encountered out at sea, this is really quite tame.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'I love it when it snows. The world falls completely silent... and I can sleep undisturbed.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: 'Clear weather all around brightens the heart.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "The birdsong at daybreak is nature's gift to us. Let us go. Our journey begins anew.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: '...The midday sun has a way of making one yearn for a moment of sleep. What say we find ourselves a place to rest?',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: 'I gaze up at the moon and lend my ear to the gentle breeze, with wine in my cup and peace in my heart... Have a wonderful evening.',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: 'The wind has ceased... The world is silent, so now is the best time to rest well. See you tomorrow.',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Sailing',
      audio: '2001',
      text: "In truth, not every night out at sea is filled with wind and waves. When the weather is clear, the moonlight flows over the rippling water, and schools of fish circle the ship's hull. At moments like that, when I look out into the distance from the prow, I feel like this journey is worth it... The only thing that takes away from that feeling is the sailors' singing. They're so loud... don't they need to sleep?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Samurai Nobility',
      audio: '2002',
      text: "The Kaedehara Clan was once a famed samurai clan. It's a pity that by the time the noble name passed to me, the title itself was all that was left. But it is enough for me. A samurai has no need of a lavish life — we find all that we need in wine, song, and the blade in our hands.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Going Out to Sea',
      audio: '2003',
      text: "What say you join me out at sea someday when the weather's fine?",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Frank Speech',
      audio: '2004',
      text: 'I like frank people, because we can freely speak our minds to one another. There is no need to hide anything that you wish to say. I hear the voices of all things in nature, and that includes yours.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: "As I see it, a Vision is the proof of one's strength, not the source of it. It symbolizes the mortal desire to always keep moving forward, but in this endeavor, we samurai place our faith in our blades alone.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share: Bamboo Blades',
      audio: '3002',
      text: "Ah, you'd like to learn the art of the sword? Let me see... Alright — here, take this. It's a bamboo blade I just made. With these, we can practice sparring without having to worry about getting injured.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Maple Leaves',
      audio: '3003',
      text: '"On this mountain path, where the red leaves lifeless lie... My heart calls for a companion, echoing the deer\'s cry..." Hm... I do love maple leaves, but it is a shame that so many goodbyes seem to happen when they turn red.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3004',
      text: 'Farewell, dear gulls, please calm your cries. From this day forth, I am a wanderer once more.',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Beidou',
      audio: '4001',
      text: 'I owe Beidou my life. She took me in when I fled from Inazuma and gave me the courage to return there at the most difficult time of my life. She is a comrade in whom I and all the other sailors can place our trust.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Gorou',
      audio: '4002',
      text: "When I was a wanted man, the resistance gave me a lot of help. The time I spent with Gorou was brief, but he left a deep impression on me. He's the type of person who says whatever's on his mind. He shares the highs and lows of his subordinates, and is never afraid to draw his sword for the sake of a friend. That's the kind of person I can really get along with.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Kujou Sara',
      audio: '4003',
      text: "She defeated my friend in a duel before the throne, which I accept as proof of her great strength. But she uses that strength to serve as an oppressor's lackey, leading the Kujou Clan's troops to relentlessly seek out and confiscate Visions. This... I cannot forgive.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Kujou Sara: Changing Perspective',
      audio: '4004',
      text: 'I see... So she does have her own ideals that she is fighting for. But I have to wonder: can the Kujou family flourish as they did before once this storm has passed?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '24': {
      title: 'About the Raiden Shogun',
      audio: '4005',
      text: "I've asked myself this question many times since leaving Inazuma. Do I simply resent the Raiden Shogun because of what happened in that duel? Because of the lethal stroke she dealt my dear friend? I've thought about this a good long time, and I believe the answer is no. My friend died an honorable death in that duel, and the Shogun was not unjustified in her conduct. My dissatisfaction with her has its roots in the Vision Hunt Decree. No one has the right to rob another of their hopes and dreams — not even a god.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2002,
              questTitle: 'Follow the Wind',
              chapterId: 1201,
              chapterTitle: 'Autumn Winds, Scarlet Leaves',
            },
          ],
        },
      ],
    },
    '25': {
      title: 'About Kamisato Ayaka',
      audio: '4006',
      text: 'I\'m sure everyone living in Inazuma has heard of the "Shirasagi Himegimi." The lady of the Kamisato Clan is as perfect as a person can be, though our paths have seldom crossed. I wonder what she thinks of the state of Inazuma today?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Yoimiya',
      audio: '4007',
      text: 'The last time she commissioned Captain Beidou to ship fireworks to Liyue, I unloaded the shipment myself. They were so heavy! I doubt that anyone besides her could make such huge fireworks.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Sangonomiya Kokomi',
      audio: '4009',
      text: "During my time with the Resistance, there was no one among our ranks who wouldn't look up to Her Excellency. As someone with a great passion for military matters, victory at all costs isn't really part of her ethos. She'd always try to limit the casualties to the minimum while planning her next move. By some accounts, it also seems that she seeks to take charge of both internal and foreign affairs for Watatsumi Island. Wouldn't that be too much to expect of herself though?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'About Shikanoin Heizou',
      audio: '4008',
      text: "Don't be deceived by his happy-go-lucky disposition. As soon as he gets working on a case, that restless energy he carries around turns into a razor-sharp focus. It's quite remarkable to witness.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About ___: I',
      audio: '5001',
      text: "You'd like to know more about me, you say? Well, as you see, I am but a wandering samurai that you could have run into just about anywhere.",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'About ___: II',
      audio: '5002',
      text: "I have a very keen sense of hearing. My ears pick up all sorts of sounds: the wind through the mountain passes, the parting clouds, the sound of foxes chewing on apples in the forest, the sound of crabs blowing bubbles... This is nature's favor, it allows me to sense danger long before it draws near.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'About ___: III',
      audio: '5003',
      text: "I used to love the rain when I was small. The sound of it would lull me into a peaceful sleep. But since I've grown older, my feelings have become more... complicated. I still like to listen to the rain today, but whenever I see the storm clouds start to gather, my heart sinks and I can't help but wonder: \"Hm... will some nice person let me stay the night today?\" Listening to the rain in drenched clothes is hardly peaceful — hehe... nothing can be when you're constantly interrupting yourself by sneezing.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About ___: IV',
      audio: '5004',
      text: 'I never stay in a single place for very long. Stagnancy dulls both my connection with nature and the blade I wield. While I am still able to, I want to travel far and wide and meet all sorts of different people.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'About ___: V',
      audio: '5005',
      text: "Don't worry — even if the day comes for us to go our separate ways, I am certain that we will meet again, in some corner of the world. The fate that brings people together is not a cord so easily cut.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "I like falling asleep on a warm rock that's been soaking in the mid-afternoon sun, then waking up and continuing on my journey with no particular aim in mind. So long as I have my blade by my side, there is nowhere I cannot go.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "___'s Troubles",
      audio: '6002',
      text: "The sounds of nature turn into a clamor of noise during stormy weather. It becomes a constant buzz in my ears. If it happens at night, I end up tossing and turning all night long without getting a wink of sleep. It's quite the headache...",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6003',
      text: "The most easily obtainable food source when you're out at sea is, of course, fish. So it goes without saying that a seafaring adventurer must give careful consideration to how to cook a tasty fish-based meal... If the chance arises, I'd like you to try some of my cooking.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'I am not particularly fond of food that is thrown together in a hurry without much care and attention. The way I see it, if your meal consists of a single fish, you should grill it to perfection. Eating is supposed to be an enjoyable experience, so how can we stand to be so slapdash about it?',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'That you can make fish taste as delicious as this is proof of your outstanding culinary prowess.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Your cooking not only fills the stomach, it also soothes my soul.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Perhaps you should get some rest? A weary mind is a recipe for flavorless food.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: "I heard it was your birthday, so I wrote a haiku for you. Unfortunately, I'm not the most talented in this area, and after trying for several evenings, I was still only able to come up with the first two lines... I guess I'll just share what I've got so far, then. \"Sun and moon rejoice / Birds of dawn sing songs anew\"... Wait, don't say a word, I think the final line is coming to me... Yes, how about... \"Far from home, with you.\" Anyway, Happy Birthday. Let's go and get you some cake, shall we?",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'My blade grows keener.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'The sound of snow as it lands on the ground is so faint as to be practically nonexistent... But now, my senses are sharper than ever, and I believe I should be able to discern it.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'The waves rise high out in the open seas. I, too, must reach new heights of strength.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "As one travels the world, sorrows and frustrations are bound to journey with you. But I find that I've grown since meeting you, both in martial arts and in strength of character. I am confident that I will be more at ease in life from this point forth.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Tch!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Huh!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Wind strider!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Into the wind.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'The wind knows me.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'One with nature!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Clouds hide... the bird's call!",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'As one with wind and cloud.',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Fallen leaves... adorn my night.',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Time to go.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Deploying Wind Glider: I',
      audio: '800001',
      text: 'I follow the wind.',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Brings a smile to my face.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'A fateful offering.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Who says there aren't benefits to a life of wandering?",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Huh, not bad...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I must remain calm.',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Stay focused!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'My turn to aid you!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I've got your back.",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'So many regrets...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Never... again...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'This is... the end...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: "It's...fine.",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'That hurt!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Want me to come along?',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Alright, let's head off.",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Sounds good to me.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Most people who meet ___ for the first time might be inclined to assume that he is just a trainee sailor with the Crux Fleet.\\nAfter all, he is a gentle soul who enjoys reciting poetry when idle, and who speaks to everyone in a leisurely manner. Who could tell that he is a wanted man throughout Inazuma?\\nEven Beidou, ever the good judge of character, could not tell that ___ could wield a sword with the skill of a seasoned warrior when she first decided to take him in.\\nWho knows if it was the storms of life that smoothed out his rough edges, or if his natural restraint has kept his edge sheathed.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'The Crux, an armed fleet from Liyue, spends much of the year on the high seas, and its sailors are quite used to the vagaries of life in other nations. So they were more curious than surprised when an outlander began serving as a sailor on their flagship, the Alcor.\\nThe sailor in question was picked up when the Alcor docked at the Inazuman port of Ritou.\\nBeidou had made friends with this young man, and when he came on board, she told her crew, "This guy\'s gonna be staying with us for a while. Take care of him, now."\\nThe sailors trusted Beidou\'s judgment and admired the newcomer for his martial prowess, not to mention his ability to predict the weather, so they were happy to overlook his reticence to discuss his past, and welcomed him aboard.\\nStill, their curiosity did not abate, and they would often find all sorts of excuses to try and ply him for information about his experiences.\\n"I\'ve heard that they make some sweet blades there in Inazuma and that the bigger the fish you are, the swankier the sword. So, uh... how\'s yours measure up?"\\n"..."\\n___ would remain silent in the face of all such queries.\\nOver time, after countless attempts to garner a response proved futile, the sailors would simply give up asking.\\nEventually, it was an off-the-cuff remark from Chief Mate, Juza, just a few days later that finally managed to elicit a reply.\\n"Hey, Inazuma boy. What are the lads supposed to call you if they don\'t even know your name?"\\nThe young sailor wiped the sweat from his brow with his callused hands.\\n"My name is ___, a wandering samurai. I am in your debt for taking me in, so just call me \'___.\'"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "___ was not born a commoner. He hails from an Inazuman noble house of old, the last son of the Kaedehara Clan.\\nInazuma City is home to many illustrious clans, and the Kaedehara name was once one of the most renowned among them. But fortune is fickle, and the Kaedeharas' fortunes had already collapsed by the time they were ___'s to inherit.\\nAs the young master of the house, ___ could do nothing but watch as his family's future crumbled around him. But as helpless as this made him feel, when the moment came that the home was officially repossessed and the last attendant was finally dismissed, he breathed a sigh of relief: As far as he was concerned, this was a golden opportunity to begin leading a free and wandering life.\\nHe had always longed to roam the mountains and forests, and had held a deep admiration for the beauty and authenticity of nature since his youth.\\nTo ___, nature had never been silent. It had always spoken to him, conveying its feelings in its own unique language.\\nWhen the wind ceases to speak and the world falls silent, that is the calm before the skies begin to weep. When silent springs suddenly leap into activity, it is the omen of a great earthquake.\\nThese are the unique poetics that nature has bestowed upon him, and ___ was never one to be preoccupied with luxury anyway — so if the burden of family responsibility should drop from his shoulders, why not go wandering, and travel light?\\nThus did ___ strike out on his journey, like a falling leaf in the yard carried away by the wind.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'All travelers who outdoors roam need some skill to call their own. For ___, this is his ability to read the sounds of nature.\\nAfter leaving Inazuma City, ___ wandered here and there. Things were different now: all of nature was his treasured home, and the sounds of wind and water beneath the sight of drifting clouds set his heart at ease.\\nAll that he saw on the road filled him with curiosity. It was in this state of mind that ___ arrived at a mountain in the south.\\nIt was early summer, and the frequent and heavy rainfall had turned the mountain roads to mud. Seeing that night was soon to fall, ___ decided to find somewhere to shelter from the rain. No sooner had he had this thought than he turned around to see a small straw hut at the far end of the road.\\nThe traveling merchant with whom he was traveling at that time whooped for joy at the sight of the hut: "___, look! We\'ll have a roof over our heads tonight!"\\nBut ___ did not speak. He paused and listened intently for a long while before he finally replied: "If you were to ask my opinion... it may be best to stay away."\\nBut the merchant did not wish to remain in the rain. He left ___ and made his way to the house.\\nUpon knocking at the door, the traveling merchant was met by a lovely woman who offered him shelter, tea, food, and even bedding for the night.\\nPerhaps it was the excellent food, but the merchant quickly became drowsy and fell asleep immediately after finishing his meal.\\nWhen he awoke the following morning, there was no roof over his head. The bright sunlight pierced his eyes, and all he could see was ___ standing nearby, looking down at him and smiling.\\nBefore the merchant could speak, he vomited a great pile of leaves and mud. And as for the bedding upon which he had slept so soundly, ah, it too was mud.\\n___ smiled and said: "The wind is weaker where there are houses. Yet here stood a hut, and there was no change in the mountain breeze. I think you might have been the victim of a bake-danuki\'s prank. Never mind. Next time, listen more closely to the wind and tread with care."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: '___ made many friends during his travels. One of them was particularly close to his heart, and for a time, the two journeyed together.\\nBut they too would part, for their destinations were different.\\nTo have met merely by chance and then form such a strong bond, there must be a fated connection between them... so, although they would part ways for now, surely they would meet again. Or so ___ thought.\\nBut something happened soon thereafter that would shatter his calm disposition — the Almighty Shogun promulgated the Vision Hunt Decree and swore to retrieve all Visions.\\nAll who wielded them, including ___, were stricken with panic, concealing their identities and going into hiding.\\nIt was then that ___ received shocking news: Someone had dared to call for a "duel before the throne," and that someone was none other than ___\'s dear friend.\\nThe defeated party in a duel before the throne would face punishment at the hand of the Shogun herself. His friend was prepared to risk all to come before the throne, partly for the chance to fight against a strong foe, but also to demonstrate the meaning of courage to all.\\nAnd yet, to call for this challenge now, of all times... ___ feared that his punishment, should he fail, would be absolute: The Almighty Shogun would unleash her lightning upon him in its full fury, and it would surely take his life.\\nEven the normally calm ___ could not restrain himself. He drew his sword and stormed into Tenshukaku like a whirlwind... But alas, he arrived too late.\\nHis friend\'s sword lay shattered in pieces, his Vision now an empty husk. Now a wanted man himself, ___ fled with grief in his heart.\\nFrom that moment on, the days of peaceful wanderings were over, and ___\'s life became an unending series of battles.\\n___ did not fear battle, of course, but the constant fighting left him feeling lost and perplexed.\\nHe did not regret having set out on his doomed rescue mission, nor did he begrudge his friend for leaving him, but he could not help but think...\\n"Is this endless conflict truly the only way to assert one\'s ideals?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'The Crux Fleet became ___\'s new home, and he drifted on the ocean wherever it took him.\\nTrouble still found him from time to time, but no issue was insurmountable with the support of the Crux crew.\\nFrom his vantage point on the Alcor\'s crow\'s nest, gazing out at the azure sea and sky, he finally had the space to think over the tumultuous events of his past and what it all meant to him.\\n"Every samurai wishes to live their life with passion and to claim the greatest reputation possible using the sword in their hands."\\n"But there will always be those whose base desires lead them astray from the path of justice and virtue, and whose blades leave an endless trail of enmity in their wake."\\n"Surely the heavens did not give us fleshly forms and the gods did not watch over our lives all so that we might take up arms against one another."\\n"Then, this sword I wield is not meant to slay, but to save..."\\n"Yes, this shall be my path as a samurai, and I shall defend it all my days."\\nAs he reached the conclusion of his thoughts, ___ was suddenly inspired to pen down a few verses to serve as a maxim for himself thereafter... but before he could get started, he was interrupted by an irate voice from down below:\\n"Hey, ___, quit gawking at the sky — get down here and lend a hand!"\\nIt seemed the maxim would have to wait for another day. Whatever the helmsman, Sea Drake, needed help with clearly couldn\'t wait.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Vision Shell',
      title2: null,
      text: '___ was just as surprised as everybody else when the Vision briefly lit up during that great battle.\\nFor in all the time that he had spent searching high and low trying to find someone who might rekindle it, never had he imagined that he could be the one to cause its light to shine once more. It was almost as if his late friend were lending him his aid from behind the scenes.\\nThis empty shell of a Vision not only proved this, but had also brought him many fateful encounters along the way:\\nHe had been aided by the resistance, saved and taken in by Captain Beidou, and he had even met the fabled Traveler...\\nIn life there were seasons of hopelessness and desperation, but there were also moments of great serendipity.\\nHis journey was like the rise and fall of a mountain path — at times, the struggle was all but too much to bear, but there would always be moments when he would touch the clouds.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "The morning mist covered the mountains like a blanket as ___ trod a small trail alone.\\nThe world was silent. Not a single feather flapped, and not a single cicada sang.\\nEven the roiling waves seemed to have fallen into slumber, leaving just the faint whisper of the wind audible against the silence. ___ stuck out his tongue — the air tasted heavy and gloomy.\\nThis told him that it would soon rain.\\nHe peered into the distance and spotted a plume of smoke up ahead. Below it were several straw huts. Tonight, it seemed, he would have a roof over his head.\\nHe informed the owner of the house that a storm was coming. At first, he was met with skepticism, but come noon the rains arrived right on cue.\\nIn awe of this wanderer's skill, the master of the house eagerly offered him lodging.\\nThe storm raged into the night. ___ held his quilt close, and as he listened to the onslaught of rain against the autumn leaves, his mind began to wander.\\nIn the time since the Kaedehara Clan's fortune had faded away and he had set off on his journey, ___ had traveled across many of Inazuma's islands and had become intimately acquainted with the plight of the wanderer.\\nMoving between islands usually necessitated traveling by sea. ___ would make these trips alone, in a small, slow boat, making things all the more perilous when he had to battle against strong headwinds or violent thunderstorms...\\nAnd yet, there was limitless fascination to be found in this same journey of his, where the vast sky and boundless earth was his home, and all living things that inhabited them were his friends.\\nIf one's heart is empty, all under heaven is empty.\\nBut if one's heart is pure, all under heaven is pure.\\nWith his sword in his hand and his chosen path in his heart, he could go on his way with a song on his lips and with nothing to fear, no matter the perils he may face.\\n___ slept soundly that night, his mind at rest having made peace with his feelings.\\nThe next day, he awoke to the sound of birds... and a shining Vision lying upon his chest.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
