export const lanyanVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "Hello, I'm Lan Yan, from the Chenyu Vale Artisans Association! Can I interest you in any decorations or baskets? Or perhaps a vase or piece of furniture? Ah, I'm almost out of rattan. I should head back to the mountains to get more... Oh, you want to come with me? Hehe, that's so nice of you! I'll throw in a free rattan hat! How does that sound?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Daily Planning',
      audio: '1101',
      text: 'Oh, my plan for the day? Hm... Doing whatever I feel like, I suppose! Same with tomorrow, and the day after that, hehe.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Family Heirloom',
      audio: '1102',
      text: "The best rattan furniture is made from strands that are smooth, thin, and strong like silk. Furniture like that can be just as precious as a silver family heirloom... That's no exaggeration!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Swallows',
      audio: '1103',
      text: 'Swallows nest when skies are fair, but hide when storms are in the air.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Well, since we're already caught in the rain, we might as well enjoy it! Saves us the energy of running for shelter, at least.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: 'Whoa! C—Can I hold your hand?',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: 'Look! Everything the sun touches is coated in gold!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: 'Hear that? Ding a ling... Ding a ling... My silver hairpiece is ringing like a bell! The wind is nice and gentle today.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'Ding a ling a ling a ling... Sounds like the wind is angry this time.',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'In the Desert',
      audio: '1206',
      text: "Need some water? Here, take a sip of mine. It's infused with mint leaves, so it's extra refreshing!",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Morning',
      audio: '1001',
      text: "Oh, did the birds wake you up? Haha, let me have a quick talk with them. We'll see if it works — they don't always listen to me.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'I picked some fresh flowers! I was just about to head back and cook something for my mom... You should come, too! My family would love to see you!',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Evening',
      audio: '1003',
      text: 'The night market sells grilled insects! Wanna give them a try?',
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Good Night',
      audio: '1004',
      text: "So sleepy... I'm gonna turn in for the night. I can't stay up any longer.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Lan Yan: Happiness',
      audio: '2001',
      text: 'To me, happiness is... savoring every bite of rice down to the very last grain, listening to the sound of the wind while taking a nap on the grass, and reading all ten volumes of a supernatural novel in a single sitting!',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Lan Yan: Inheritors of Qimen Arts',
      audio: '2005',
      text: "The legendary Wind Reader is indeed listed as an ancestor of the Lan clan, but my family split from the main branch a long time ago. The Qimen arts are complex and varied, and I've only learned a few tricks so far. Anything harder, and I need to ask my elders and cousins for help. Still, I'm really good at making rattan figures — even grandpa is no match for me! Hehe, I guess it's the one area where I really hold my own.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: "About Us: Let's Shake Hands?",
      audio: '2003',
      text: 'Sit. Friend. Handshake~\\nOh, no, I wasn\'t telling YOU to sit — I was talking to our animal friends! Ahh, I\'m so sorry! Please, get up... I was trying to tell them, "Look over here, everyone! We have a new friend with us today!" Oh, that wasn\'t clear? Well... "Sit" can mean "listen to me" or "stay where you are" or even "stop what you\'re doing." Hm? How are you supposed to know? You just need to come to the mountains more often. You\'ll pick it up in no time!',
      tips: '',
      tasks: null,
    },
    '17': {
      title: "About Us: Let's Shake Hands!",
      audio: '2002',
      text: "Come on, shake my hand! Gimme a hug!\\nHuh...? Well go on, let's shake hands! ...Isn't this how friends encourage each other? ...Oh wait, haha, yes, you this time! Sorry, it's my fault for confusing you. No worries, though! The more we hang out, the more we'll understand each other!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About the Vision',
      audio: '3006',
      text: "#Thanks to my Vision, I can toss my chakram into the air and catch it with ease... Ah, but don't try it at home, kids! The blade is actually really sharp! Although, you could probably give it a go, {NICKNAME}! Just stand still, keep your arm steady, and give a nice, swift throw. I'm sure you can do it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share',
      audio: '3002',
      text: "You can never be too careful when it comes to wild mushrooms. Many are completely inedible, and others have to be stir-fried and cooked fully to be safe. And, if you don't finish them in one sitting, you have to do the same to the leftovers before consuming them — a lot of people forget that step. So, if you eat a few bites, and your dog starts telling you to put away the laundry, or your chickens start ordering you around the house, seek medical attention right away!",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Once, I was resting in a tree after finishing some weaving, and a squirrel stole the rattan pinecones I just made! Thankfully, I was able to get them back by trading for double the amount of real pinecones. Honestly, I didn't really care about losing my work, I was more worried about ruining the squirrel's entire day! Just imagine — you spend all day collecting pinecones only to get home and realize they're fake! All their squirrel friends would probably laugh at them...",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Xiangling',
      audio: '4001',
      text: "Everyone says first impressions are important, and the first time I ate at Wanmin Restaurant, I had so much regret... regret that it took me so long to visit Liyue Harbor! I could have met Xiangling way sooner... In any case, as soon as she heard me talk about all the rare ingredients in the mountains of my hometown, she started planning a trip to Chenyu Vale! I'll make sure she doesn't go home empty-handed!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Hu Tao',
      audio: '4002',
      text: "Director Hu always seems so upbeat and cheerful. Even when the situation was desperate, she was always there with a joke to cheer me up. I haven't known her long, so I was wondering... Is she always like that? Hmm... In any case, starting from today, I hope all her smiles are out of genuine happiness, rather than an effort to reassure other people.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Keqing',
      audio: '4003',
      text: "When will the Yuheng finally take a break? She was running all over the place during the Lantern Rite. I wanted to treat her to a meal to thank her for her kindness, but I never had the chance... I was also hoping she could do my hair into a pair of cat ears just like hers. But... maybe that's asking too much. Although, something tells me she wouldn't mind...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Xingqiu',
      audio: '4004',
      text: "#I've run into master Xingqiu several times in the mountains. He wasn't accompanied by anyone from the Feiyun Commerce Guild, so it never seemed like official business. After those chance encounters, he often brought me copies of the newest supernatural novels, and I promised to never tell anyone. Except... I definitely just told you, didn't I? Please keep that secret for the both of us, {NICKNAME}!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Chongyun',
      audio: '4005',
      text: "One time, I was out with grandpa on one of his house calls, when I saw Chongyun leave the house with a dejected look on his face. Given how helpless he looked, I assumed the situation must have been bad, but I didn't sense an ominous presence within the house. Grandpa's reading didn't predict any misfortune, either. Maybe he spent a lot of energy getting rid of the problem and was too tired to talk... Huh? You think it's possible he didn't do anything at all? That makes me even more confused...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Gaming',
      audio: '4006',
      text: "I've known Gaming since we were kids! He was quite the neighborhood terror back then, haha. Hm? That doesn't sound like him? Well, he's matured a lot since then, just like I have. One thing hasn't changed, though — he still carries snacks with him wherever he goes. He always comes back from his travels with a ton of goodies to share with his friends. And, of course, he never leaves without stocking up on his hometown favorites...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Qiqi',
      audio: '4007',
      text: "Qiqi likes finches, right? I'm thinking of making her one out of rattan! Do you know her favorite color?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'More About Lan Yan: I',
      audio: '5001',
      text: "Hold it! One moment... Almost there... Just need to finish this handle, and... Phew... Done! Hehe, sorry about that. I'm not the best multitasker — I can only focus on one thing at a time. Now, you have my undivided attention!",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About Lan Yan: II',
      audio: '5002',
      text: "Wanna spend some time in the mountains? We can try to dodge Fluff-Fleece Goats as they headbutt us. Or, we can pretend the Red-Beaked Pelicans are bandits and try to rescue Jade Heartfeather Bass from their beaks... Oh, you want to play Windtrace? You'll be the Hunter? Hehe, someone's confident. Alright, if you end up running in circles, I'll ring my silver bell to help you find me. If you manage to touch even the tip of my hair, I'll count that as your win! I'm pretty good at this game, too, you know.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About Lan Yan: III',
      audio: '5003',
      text: "My silver hairpiece is in the shape of a \"Jade-Plumed Silverwing,\" and it's a family heirloom. My silver hairpin, necklace, and brooch are all birthday presents from my parents. Oh, the bracelet is a Lantern Rite gift from my grandpa, and the earrings are from the last Moonchase Festival, I think... There are also others that were given to me when I mastered the wind glider, received my Vision, and managed to down three whole bowls of rice in one meal...\\nHehe, my family believes that silver accessories are auspicious and can ward off evil, so I'm constantly receiving new ones!\\nWearing them all at once is pretty heavy, but... I suppose that's the weight of a family's love!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About Lan Yan: IV',
      audio: '5004',
      text: "When I was little, rattan figures used to creep me out... How should I describe it? I mean, a bunch of misshapen black and gray dolls throughout the house... it's the stuff of nightmares for a kid! When grandpa used to send me to study with the head family of our clan, I thought he was possessed. I thought my cousin was teaching me the dark arts! So, one night, I worked up the courage to burn all the figures I could find. Luckily, their purpose was to absorb evil energy, so they were always meant to be destroyed.\\nBut, that got me thinking — if rattan figures looked cuter, maybe people wouldn't mistake them for some kind of evil sorcery...",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About Lan Yan: V',
      audio: '5005',
      text: "Rattan weaving isn't hard, I swear! Even the most intricate figures are made one strand at a time. All you need is a little patience, and you'll get there in the end! Compared to the technique itself, precision is the hard part, and persistence can be even harder. If you ask me, though, the most important element is happiness. If you don't enjoy the process, you'll never do a good job — that's true for more than just weaving. Happiness is key! That goes for both of us!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "Lan Yan's Hobbies",
      audio: '6001',
      text: "According to folklore, spirits of drowned people exist in haunted bodies of water, so I tried to see if it was true by shoving a stick in a lake... And it actually got stuck! In all the seaweed, I mean. I can only imagine what would happen if you tried to go swimming. Not getting stuck would be more unusual...\\nOh, I also heard that you shouldn't eat sunsettias after sunset or peel an apple in front of a mirror at midnight... Huh, I wonder if there's truth to any of those folk legends...",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "Lan Yan's Troubles",
      audio: '6012',
      text: "I hate removing splinters. You have to squint so hard to see them, and I always end up hurting myself... I've cut all ten of my fingers that way... *whimper*",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Fresh flowers not only look and smell amazing, but they also make delicious pastries! The flavor is refreshing, but not too sweet. Ah, and it goes so well with a pot of floral tea... Ooh, let's go flower-picking right now! No need to bring a basket — I'll just weave one once we're in the mountains!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "As the saying goes, even sugar is only sweet when you're happy. Everything tastes worse when you're in a bad mood. Hehe, luckily, I rarely have that problem.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'This is delicious! Hold on, a dish like this calls for special utensils made of pure silver! Be right back!',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Ah, thank you! Here, try it with this dipping sauce! The flavor is even better!',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Wait, you ate some of this? Is your stomach okay? You're not seeing things, are you?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "#In my family, we always give silver accessories as birthday gifts. So, here, these two figures are for you. The one with the silver swallow on the head is me, and {M#the one with the small silver sword is you}{F#the one with the silver flower is you}. Hehe, looks just like us, right?\\nI infused the rattan strands with incense, so hanging them on your knapsack should repel insects. Oh, and I designed the silver accessories, too. The silversmith polished them once, and I made sure to smooth out the edges a second time, so you don't have to worry about cutting yourself.\\nWell, happy birthday, {NICKNAME}! May luck always be on your side!",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Wait, I barely got two strands in this project, and you already... Either you work super fast, or I'm slower than I thought...",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'If silver needs to be polished to shine, it only makes sense that we need to keep honing our skills to become as light and swift as a swallow.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Let's shake hands! Again! Again! Still remember? It's an expression of happiness and gratitude — a way to express joy at all the good things in life!",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "\"The humble swallow builds with mud, and yet, is never without a nest.\" So, don't underestimate me! With how strong I've become, I should be more than capable of protecting you now. Hehe, it's all thanks to your help, of course! Thank you so much!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100004',
      text: 'Flip and fly.',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100005',
      text: 'Closing in.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100006',
      text: 'Up and away.',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Ills, be gone!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Swift as the swallow.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Dancing in the wind~',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Whoa, can I have some? Spread the luck around!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Score! Let's see what's inside!",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Just a moment, let's tally this up...",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Need some time...',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Little help here~',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'This is tricky...',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Get back! I'll cover for you!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "I've got this! I'm faster than them.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Fallen: I',
      audio: '500001',
      text: "Can't... fall now...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'The bell rings... no more...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Grounded... for good...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Light Hit Taken: I',
      audio: '900002',
      text: 'Stop!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: "Something's off!",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Nasty temper!',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Doesn't matter where, I'll be there!",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Let's hit the town!",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Coming!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "When it comes time for the residents of Chenyu Vale to spruce up their homes, there is more than just the usual panoply of intricately carved wooden beds and tables on offer. They also have a fine selection of wickerwork furnishings to choose from — delicately crafted by their own master rattan weaver.\\nThis latter option provides a distinctive, refreshing, and elegant style and is something the Vale's residents know they can always rely on as a safe choice.\\nWhile fine silk garments imported from Liyue Harbor have an undeniable allure, cloth dyed locally is both durable and functional, and exhibits patterns and colors that exude a familiar charm.\\nYet it is the crafting of silver and jade into objects of great beauty for which Chenyu Vale's artisans are perhaps best known, so much so that the owner of Mingxing Jewelry — a time-honored and respected establishment in Liyue Harbor — regularly dispatches representatives to come looking for wares.\\nSilver-smithing, jade-carving, cloth-dying, rattan-weaving, and countless other crafts — Chenyu Vale is famed as the home of the most outstanding and accomplished artisans in each field. Skilled, dextrous, and creative are but a few words that could be used to describe them.\\nLan Yan is a master rattan weaver and a Chenyu Vale Artisans Association member.\\nShould a wandering traveler get lost in the tranquil valley, betwixt sparkling mountain springs and gnarled and ancient tea trees, and there stumble upon a smiling young woman, adorned in silver ornaments, it might well be Lan Yan, out collecting rattan vines.\\nFeel free to ask her for directions, for she will kindly guide you through the swirling mountain mists of Chenyu Vale and set you on the path to the picturesque hamlet of Qiaoying Village, with its white brick walls and gray tiled roofs.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Chenyu Vale has long been praised as a cradle of artisans, with many a master craftsperson honing their skills in the picturesque surroundings of Qiaoying Village.\\nWith generations of artisans living and working together, the village tradespeople naturally chose to form a collective to protect their shared interests. Now, they proudly announce themselves as members of the Chenyu Vale Artisans Association, spreading prestige for their hometown and their skills everywhere they go.\\nMembers of the association not only look out for each other in crafting and trade, but they form a close-knit, neighborly group who are always there for each other in good times and in bad.\\nAsk any member of the association about rattan weaving, and one name above all you would hear — Lan Yan. Despite her youth, she excels at weaving all manner of rattan goods while also having a grasp on the arcane Qimen arts.\\nIt is said that "skills honed to the highest pinnacle produce art that touches the divine realm." The venerable masters believe that anyone who reaches the apex of their craft will uncover abilities that cut through the spiritual divide. To them, Lan Yan — with her Vision and attunement to the Qimen arts — is a truly remarkable young woman.\\nAs for Lan Yan herself, well, she\'s having none of it. When others shower her with praise, this is her usual, slightly abashed retort: "I\'m really only interested in rattan weaving."\\nA merchant from Liyue Harbor once came bearing gifts of gold and words of praise. He humbly requested that "Lan Yan the Master Rattan Weaver" produce two pieces of furniture for his new home.\\nWhile waiting patiently in the association\'s halls, he had expected to be greeted by a serious, even taciturn face — one perhaps wizened by age. Yet when Lan Yan entered, he was shocked to discover a bright-eyed, fresh-faced young woman.\\nHer joy and exuberance were evident as she greeted all those present with glee. There was no hint of arrogance in her demeanor. When the merchant told her of his request, she simply nodded and said, "Leave it to me!" as though her craft was as simple as pouring a cup of tea. With that, she shouldered her basket and headed out into the hills to pick the necessary vines.\\nThe artisan tasked with greeting the association\'s guests patted the merchant on the shoulder. "Lan Yan\'s a straightforward young craftswoman, there\'s no need to stand on ceremony with her. She agreed to your request, so, the way she sees it, why not get started? Come on, let\'s go and get something to snack on while you wait."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "To Lan Yan's mind, the process of weaving rattan goods is a simple one.\\nThe first step is to gather enough vines.\\nIn the verdant mountains, the first rays of the morning sun are the purest, and as the last birds to rise lend their voices to the dawn chorus, Lan Yan sets off towards the wooded slopes with her trusty bamboo basket and pruning knife in hand.\\nThe vines like to grow where the soil is moist, though whether they prefer to bask in the sunlight or take shelter in the shade appears to be a matter of temperament and personal preference.\\nDifferent vines are suited to the weaving of different objects. A folding screen, for example, requires a certain stubborn resilience. Lan Yan often looks for such vines in old-growth forests, with their ancient trees towering high overhead — to climb and cling on to such imposing trees requires a more rugged constitution.\\nIn contrast, a woven flower basket calls for vines of a more supple nature. These vines are often found by the water's edge, where the thirsty rattan palms send out myriad soft offshoots that cover the ground like a carpet. Such soft vines can be bent to form the shape of a basket without snapping.\\nOnce enough vines have been collected, it is time to return home and process them.\\nThe woody cores can be used to shape and weave a solid frame, while the skin, once peeled away, can be woven into a fabric-like material that helps give rattan goods their finished shape. Both of these materials must first be washed and dried.\\nLan Yan likes to sing while she soaks and stirs the rattan strips — and as she pulls them out of the water, one by one, to dry them in the courtyard. Sometimes her mother and father will join her, and they will talk and laugh while they lay the strips out in the sun.\\nOnce the cores and skins have been processed, then comes the most crucial part of the process — weaving.\\nRattan weaving requires significant concentration — warp and weft, along and across. From a pile of cores and strips of skin, a perfectly sculpted object begins to take shape.\\nLan Yan views the fruits of her labor not so much as products, but as living entities, lovingly birthed by her hands.\\nEven if two of her creations might appear indistinguishable to an outside observer, she can tell them apart by the subtle changes in touch and force applied, the order of her weaving, or the emotions she felt while she made them. Each of her rattan children has its unique feel.\\nWhile weaving, Lan Yan maintains a singular focus on her task. She is not easily distracted by idle chatter, nor the excited cries of her neighbors' cats and dogs, nor graceful swallows swooping beneath the eaves. There are times — perhaps to escape the noise — when she will take her work to a familiar mountainside to sit in silence and weave.\\nUnlike her family at home, the flowers, birds, fish, and insects that roam freely in the forested hills feel no need to leave a quiet space for Lan Yan to weave in.\\nThe most mischievous offenders are the little foxes, who, indulging their natural curiosity, come to watch Lan Yan as she works, nudging and sniffing at her jugs and jars, spilling her varnish and inadvertently waterproofing their paws.\\nThe panicked foxes then trample on the flower basket she has been weaving, leaving shiny paw prints in their wake. Thanks to this unique touch — the innocence of the wilderness — this basket will become one of Lan Yan's favorite creations.\\nThat is how rattan weaving is — simple yet never boring, and this experience is one of Lan Yan's most cherished and happiest moments in a life spent devoted to her craft.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Much like the exorcists who dwell on Mt. Tianheng, the Lan clan, with their affinity for the Qimen arts, have long made Chenyu Vale their home.\\nOne such art requires the use of rattan figures. As a result, such figures — and the skills to make them — are something the Lan clan values highly. What sets Lan Yan apart, is that unlike the rest of her family, who view rattan weaving as a means to an end, she views it as an art in itself, one whose importance far outstrips the arcane and esoteric purposes that fascinate her kin.\\nThough Lan Yan once studied the classic texts of the Qimen arts under the tutelage of her relatives, she did little more than scratch the surface, and her knowledge pales before experienced practitioners. Then again, she does not claim to be an expert, though that doesn\'t stop curious members of the association from asking her to perform rituals or ward off ill omens.\\nAfter receiving too many such requests, Lan Yan can only sigh.\\nBorn into a branch of the Lan clan, Lan Yan does not conform to the typical image of a geomancer that an outsider might have. The only visible sign of her heritage is her silver hair ornament, modeled after the "Jade-Plumed Silverwing."\\nThis heirloom symbolizes the Lan clan\'s connections to the "Eight Adepts" — significant figures in Liyue\'s history.\\nThe term refers to eight great heroes who once fought against the god Tao Dou. Of these eight heroes, the Jade-Plumed Silverwing, Lone Butterfly of the Crimson Flame, and Gold-Eyed Celadon Mare are known as the Three Beasts of Tao Dou.\\nOf the remaining five, Wind Reader, the Wuwang Kid, and the Yunlai Angler were honored as the Three Hermits of Guizang. They and the Two Sages of Lianshan were all human.\\nThe Jade-Plumed Silverwing had a deep connection with Wind Reader, who was a truly remarkable individual. It was he who first taught the Lan clan the secrets of the Qimen arts.\\nThe silver ornament that Lan Yan now wears in her hair has been passed down from generation to generation so that the descendants of the Lan clan never forget where they came from.\\nLan Yan knows the story of the Eight Adepts well and regularly makes trips to watch Liyue opera performances that tell of their exploits. Despite this, their story never left a strong impression on her.\\nThroughout Liyue\'s long history, selfless acts for the benefit of future generations — or "planting trees for the children of tomorrow," as the locals like to say — have been a recurring motif. Many such tales have already been lost to the winds of time, while others have entered the collective psyche and become part of Liyue\'s living folk memory.\\nAnd because such stories exist, carefree, exuberant young men and women like Lan Yan are free to roam the wild slopes of Chenyu Vale, smiling and laughing and singing folk songs amidst nature\'s beauty.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Whenever Lantern Rite rolls along, the Ministry of Civil Affairs in Liyue Harbor is especially busy organizing street fairs, performances, and all sorts of other festive activities.\\nMinistry officials — often rushed off their feet — can be seen dashing hither and thither, attempting to enlist the most capable members of Liyue society to contribute toward the most important festival of the year.\\nIn previous years, the Chenyu Vale Artisans Association has always been happy to send their representatives to help. This year, the Ministry of Civil Affairs asked specifically for Lan Yan.\\nFor Lan Yan, who grew up in the leafy confines of the vale, rarely venturing beyond its verdant slopes except to accompany her grandfather on his travels, this was her first real journey to the city.\\nLike so many customers who have traveled to Chenyu Vale to seek the services of the famed rattan weaving master, those at the Ministry of Civil Affairs were shocked to discover that the master artisan whose help they sought was a fresh-faced, unimposing young woman.\\nThe young artisan politely rejected the food and lodging the ministry offered, preferring to wander the city streets by herself, conversing with visitors and citizens alike — to use her own words, "This is my first time coming as far as Liyue Harbor, I\'d like to find my own way around."\\nShe ate her first meal in the Wanmin Restaurant, where she was taken unawares by the spicy boiled fish, and was left gulping down water to cool the fires on her tongue.\\nShe then spent much of her first evening wandering Chihu Rock, before Liyue Harbor\'s nighttime soundscape soothed her to sleep.\\nHer first conversation was with a soldier returning home from a posting to the Chasm. The soldier helped a lost Lan Yan find her bearings and, upon hearing she had come from Chenyu Vale, told her at length of the red mountains of the Chasm and played her a melodious tune.\\n"The world truly is a large place," she thought.\\nLiyue itself is already home to many people and places, each unique in their own way. The waters of Chenyu Vale sport gentle beauty and natural charm, the clamorous streets of Liyue Harbor burst with bustling color, and the stark landscapes of the Chasm are vast and imposing. And outside Liyue... an even larger world awaits.\\nFor the first time in her life, Lan Yan desired to see more of the world, to use the rattan strands of her hometown to weave the scenes she might see there to become one with her own heart.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "It is rare to see Lan Yan without a smile on her face, and even her best friends would be hard-pressed to recall a time they've seen her cry.\\nOf course, she too has moments of unhappiness, though they are few and far between. Whenever she feels sad, all she needs to do is allow a mischievous lamb to butt its head against her leg or a fluffy puppy to nip her hand, and her worries melt away like morning snow.\\nAs far as Lan Yan is concerned, every second spent thinking unhappy thoughts is time that could be better devoted to playing happily with the beasts of the fields and forests.\\nMost of the time, an afternoon whiled away among the tea trees with her animal friends is enough to dispel unpleasant feelings.\\nHowever, there are times when more drastic action is required — such as letting her cares wash away while swimming in the wilds.\\nThere isn't a pool or waterway between Qiaoying Village and Mt. Lingmeng that Lan Yan hasn't swum in, nor a crisp mountain spring that hasn't filled her cupped hands or reflected her face.\\nShe reclines in the water, the gentle current keeping her afloat, as her black hair swirls on the surface and tiny fish nibble playfully at her feet. All the while, warm rays of sunlight cast dappled shadows on the streambed below.\\nHere she daydreams in viridian and emerald hues of a life much the same as hers.\\nShe wakes at dawn in such dreams, in a house with white brick walls and a gray tiled roof. There she drinks a cup of morning tea, before punting a bamboo raft down the stream outside, singing all the while. In her dream, too, she weaves rattan objects, as a tiny dog bounds over to her side and licks her hand. And with that, she awakens.\\nLike every son and daughter of Chenyu Vale, Lan Yan is as simple and pure as a clear mountain spring.\\nShe has everything she wants and so doesn't dwell on dreams.\\nThe bright lights and exotic sights of the world outside are no more attractive to her than a butterfly to a deer. Sure, a curious deer may leave its verdant slopes to gaze upon a passing butterfly, but it will soon return to whence it came to happily graze once more.\\nWherever Lan Yan's travels may take her, it is never long before she returns home to Chenyu Vale.\\nEven the most wonderful dreams cannot compare to the scent of freshly roasted tea leaves, just as even the most distant fantasies cannot compete with the beauty of the swirling mountain mists that wreath Mt. Xuanlian.\\nAfter wringing out her hair by the water's edge and getting back into her dry clothes, Lan Yan carefully dons each of her silver bracelets, earrings, and necklace. It is time for her to return home.\\nThe silver ornamentations that adorn her are gifts from her family, and they chime and jingle as she walks, playing a melodious mountain tune. Wherever she goes, she is accompanied by joyful music.\\nSwimming in the wilds is not without its dangers, and she has been reprimanded by her grandfather on more than one occasion. There would surely be more stern words if she were to be caught again today. Next time, she muses, it might be better to take a friend.\\nBut that's a matter for another day. Tonight, there is Tea-Smoked Squab on the menu.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Song of Swallows',
      title2: null,
      text: '"Swallows nest when skies are fair, but hide when storms are in the air."\\n"When death is near and all hopes fade, the swallow comes, a life to trade."\\nThis is one of the many superstitions that Lan Yan has told you of. She warned you to treat swallows with care, for when our final moments approach, a swallow may well appear before the gates of Tao Dou to take your place in death. To hear her tell it, her grandfather also claimed that swallows could bring about an early demise if treated unkindly.\\nIt\'s easy to get on board with the message preaching kindness and the sanctity of life, but the part about dying if you\'re not quite nice enough seems a little extreme.\\nMany such old superstitions are as unfathomable to people today as rain that falls from a cloudless sky — ideas such as "fingernails shouldn\'t be cut at night," "chopsticks mustn\'t be laid horizontally on bowls," or "a new season\'s first picking of tea cannot be drunk by children."\\nIn truth, even though kindness to swallows is a widely practiced folk tradition in Chenyu Vale, to most youths, the idea is nothing more than a nursery rhyme, sung to them as infants.\\nOnly the Lan family upholds this tradition with the rigor of an unwritten rule — any swallow that builds its nest beneath their eaves is welcome to stay for as long as it may please.\\n"They can be bothersome at times, but once the swallows get to know me, they like to hop up on my shoulder and keep me company while I weave."\\nWhen she told you this, you were with her in Jademouth, riding Uncle Bosu\'s bamboo raft. The old man\'s singing was accompanied by a gentle breeze, while a pelican lay fast asleep in the back of the boat.\\nThe silver swallow in her hair glinted brightly in the sunlight, as warm and lustrous as her eyes.\\nGazing at that ornament, you couldn\'t help but wonder if the Lan family\'s tradition of caring for swallows might stem from their history with the Jade-Plumed Silverwing, and your thoughts turned to the stories of those ancient days.\\nSeeing the glazed expression in your eyes, Lan Yan leaned in and gently tweaked your nose.\\nAs though waking from a dream, you were greeted by her smiling face, and not far in the distance, the sights and sounds of the docks told you that your journey was almost at an end.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Much like all handicrafts, rattan weaving is a skill that relies more on the body than the mind.\\nOnce a frame has been crafted and the overall shape of an object set, Lan Yan must use the utmost care to weave each warp and every weft. After years of practice, the skills and movements of her craft have not only been burned into her brain but become second nature and muscle memory.\\nOn a deeper level, this process has also gradually refined and clarified her spirit.\\nLan Yan is a master rattan weaver. She has never been given over to grandiose dreams of chasing the moon and the stars, nor of forsaking all that she has and living her life as a hermit on some distant mountain.\\nHer life is a simple one, natural and unadorned.\\nAs she weaves, her hands honor the memories of days past, retracing their steps to expertly craft delicate patterns and shapes.\\nAll the while, her heart does not lie idle, for she is thinking of the mountain mists, the vines that climb the cliffs and crags, and the sensation of freshly fallen leaves beneath her bare and carefree feet.\\nShe thinks of Chenyu Vale — of her family amidst the mountains and rivers — and the rattan in her hands becomes supple and pliable to her will.\\nShe dreams of weaving these beautiful things with her own two hands so that her memories can live forever in the objects she creates. Perhaps because her heart is filled with warmth and kindness, the objects that Lan Yan crafts exude a simple, gentle spirit.\\nPerhaps that\'s also why the cats, dogs, birds, and squirrels of Chenyu Vale are never scared to approach her.\\n"Even the adepti come to watch Lan Yan weave." Her grandfather had once proudly claimed.\\nNo one could know for sure if the adepti had ever truly stopped in passing to watch Lan Yan perform her craft. Lan Yan herself believes that beings who would pour their power into protecting the waters and mountains of the vale, and all those who dwelt there, would surely have an appreciation for handicrafts so lovingly created and imbued with the spirit of their creator.\\nSo when she discovered a Vision glinting softly at the bottom of her rattan basket, she was not surprised. She simply picked it up and continued on her way, gathering rattan vines.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
