export const sayuVL = {
  quotes: {
    '0': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Bye!',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Gotta dash~!',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Poof!',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: "I'm outta here.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: "Can't catch me~!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'And away I go.',
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Twinjutsu!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Come on out!',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Hah! ...Phew...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Make my escape.',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Looks kinda cozy in here... Nap time!',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Mission accomplished! Can I go back and sleep now?',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Ooh, what's in here? Maybe a growth serum?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'What was that escape method again...?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'I feel kinda woozy.',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'Whew, so tired.',
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "I'll protect you.",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Take 5. Or maybe 10.',
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Almost. Got. Away...',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Uh, sw—sweet dreams...',
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'My fault for being so lazy...',
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Ow.',
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Almost dodged that.',
      tips: '',
      tasks: null,
    },
    '23': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: "I'm about to pass out over here.",
      tips: '',
      tasks: null,
    },
    '24': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'So sleepy.',
      tips: '',
      tasks: null,
    },
    '25': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Can I go catch up on my sleep?',
      tips: '',
      tasks: null,
    },
    '26': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Drat, you caught me.',
      tips: '',
      tasks: null,
    },
    '27': {
      title: 'Hello',
      audio: '1000',
      text: "___, Shuumatsuban, at your disposal! Whew, but if you don't need me right now, I'm gonna grab some sleep. Nope, no need to tuck me in — I need the extra room to grow into.",
      tips: '',
      tasks: null,
    },
    '28': {
      title: 'Chat: Asleep',
      audio: '1101',
      text: '*yawns* *snoring*',
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'Chat: Work',
      audio: '1102',
      text: 'Seems like I should have just stayed in bed today.',
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'Chat: Height',
      audio: '1103',
      text: 'Surely I should be due a growth spurt by now?',
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'When It Rains',
      audio: '1201',
      text: "Eek, let's find shelter, quick! Watering works on plants, but not people...",
      tips: '',
      tasks: null,
    },
    '32': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Phew, this weather is wild! Best thing to do is dive under the covers where it's dark and snug and warm and nyam nyam nyam~ *sleeps*",
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'When It Snows',
      audio: '1203',
      text: "It's really easy to hide in weather like this. There's this ninjutsu technique called Cloak of Snow where you can pretty much make yourself invisible — all other people see when they look at you is the snowflakes dancing in the air. Wait, it's confidential though! Don't tell any of this to the shrine maiden...",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "Loooove it when the weather's like this, just makes you wanna... *yawn* doze off for a while.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "When It's Windy",
      audio: '1205',
      text: 'A windy day is a good day for a getaway.',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'When the Wind Is Blowing',
      audio: '1206',
      text: "I always know it's time to get some shut-eye when the wind's so strong that I can't open my eyes anyway.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Good Morning',
      audio: '1001',
      text: "...Morning? Already? Okay, I'm just gonna snooze for, like, 10 more minutes... Please, just 10 minutes... No? Okay, 5 minutes then? *snores*",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Is it noon yet? Finally, I'm so ready for my nap.",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Recon confirms, no sign of the shrine maiden within a 3-mile radius. Moving to the next phase: sleepy time!',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Good Night',
      audio: '1004',
      text: "At long last... bed time... G'night...",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'About ___: Shuumatsuban',
      audio: '2001',
      text: "Yeah, I'm in the Shuumatsuban, but they only ever get me to do stuff like... *yawn* information gathering and stealing. So, y'know... it's not really a big deal if the work doesn't get done.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'About ___: Skiving',
      audio: '2002',
      text: "So I don't do any important work at the Shuumatsuban, and anything that gets put off for long enough ends up getting done by someone who's more suited to it anyway. Sleep, on the other hand — that is of the utmost importance. Because I need to get enough sleep to make sure I get my growth spurt.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '43': {
      title: 'About Us: Favor',
      audio: '2003',
      text: "Hey, will you do me a favor and let me know if you see the shrine maiden coming? I'm just gonna, um... rest my eyes for a moment.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'About Us: Headpats',
      audio: '2004',
      text: "I'm not a pet, y'know! Hmm, but since it's you... Okay, you can pat my head and I promise not to bite your hand. Just a little, though! If you pat someone's head too much, it stunts their growth.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '45': {
      title: 'About the Vision',
      audio: '3001',
      text: "My sword is crazy heavy, even with my ninjutsu training there's no way I could lift it without the help of my Vision. So yeah, having a Vision is a huge help for me.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '46': {
      title: 'Something to Share',
      audio: '3002',
      text: "Sensei says I'll be the last ninja ever in our line. I guess it can't be helped, because this style of ninjutsu wouldn't be much help in a fight anyway — all I've been taught is how to escape and how to cover your tracks.",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Do you know the mujina? It looks similar to a tanuki, but it's way cuter. I'll take you to see one next time!",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'About Kamisato Ayaka',
      audio: '4001',
      text: "As the eldest daughter of the Kamisato Clan, she always looks very graceful and elegant. But she got one of the shrine maidens to keep tabs on me and make sure I don't slack off... Why would she do that?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '49': {
      title: 'About Kamisato Ayato',
      audio: '4002',
      text: "Sometimes, when I'm taking a rest up in a tree, I overhear the shrine maidens talking about him. Sounds like he's pretty important and super busy most of the time. I don't get it, though — it's only work, or whatever, so why doesn't he just... not do it?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '50': {
      title: 'About Thoma',
      audio: '4003',
      text: "He's got a Vision, and yet for some reason he pesters me about learning ninjutsu every time I run into him. I don't know what his deal is. It's not like I'd have the time to teach him anyway, I barely get enough sleep as it is.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '51': {
      title: 'About Yoimiya',
      audio: '4004',
      text: "Every time she sees me she says, \"Hey, little tanuki! Let's go hang out at the festival.\" Firstly, I'm not a tanuki. Secondly, I don't wanna go to a festival. Thirdly, she says she wants to hang out — but really, she just wants me to do a ninjutsu performance during the fireworks show. That's not even related to my work for the Shuumatsuban!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '52': {
      title: 'About the Raiden Shogun',
      audio: '4005',
      text: "Her Excellency? Definitely not someone I'd ever get to meet. If you've got questions, maybe Miss Ayaka's the person to ask.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '53': {
      title: 'About Yae Miko',
      audio: '4006',
      text: "She's always patting me on the head... I've never bitten her, though, or even said anything, because I'm frightened of how she'd react if I stood up to her. But what am I gonna do? Because if she keeps on patting my head, I'm gonna get stuck at this height forever!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '54': {
      title: 'About Arataki Itto',
      audio: '4007',
      text: 'Why does he have to make such a racket? And how did he get so tall!?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '55': {
      title: 'About Kuki Shinobu',
      audio: '4008',
      text: "Doesn't ring a bell, umm... What? Arataki Itto's little sidekick? Ugh, well she's definitely gotta be a sleep disturbance then. Birds of a feather flock together...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '56': {
      title: 'About Kirara',
      audio: '4009',
      text: "One time, when I woke up from an afternoon nap, I felt something warm against my back. I turned around and saw a cat curled up fast asleep. You wouldn't believe this — it had not only one, but two fluffy tails! I almost fell from the tree in surprise. I—Is this some form of ninjutsu too?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '57': {
      title: 'About Yumemizuki Mizuki',
      audio: '4010',
      text: "That strange, purple youkai... Every time she looks at me, I get this feeling like she could devour me whole... Eek! I can't afford to get on her bad side, so I'm just gonna stay out of her way!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '58': {
      title: 'More About ___: I',
      audio: '5001',
      text: 'Zzzz...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'More About ___: II',
      audio: '5002',
      text: "Huh? You wanna know the name of my style of ninjutsu? Uhh... Y'know what, I can't think straight right now, I'm still half asleep here. Lemme snooze a while longer, maybe my mind'll be clearer when I wake up.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '60': {
      title: 'More About ___: III',
      audio: '5003',
      text: "Alright, fine... I'll tell you. But you'd better not laugh, or I'm never talking to you again. Uh so, my style of ninjutsu is called... um... Yoohoo Art.\\nThe reason is supposedly that our style focuses on making fun of the enemy, but still... I mean... *sigh*",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '61': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Do you know how to climb trees? I'm an expert, I can teach you. There's this tree down at the shrine — it's the perfect place, you could just literally sleep there all day if you wanted and no one would ever find you... Uh, I just mean, it's a great place for a power nap. Next time you wanna take a nap, let me know, I'll take you there.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '62': {
      title: 'More About ___: V',
      audio: '5005',
      text: "It was actually Sensei who gave me this outfit. They said it was modeled after the mujina, and it could help with escapes, or something... and then Sensei said that I was all grown up and ready to go it alone, but that I should still be careful to protect myself... then they left me. Am I really ready to go it alone, at my height?\\nUm... Hmm? Y—You'll keep my company? Really? Promise you won't leave me?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '63': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "When I put my hood on, I can snooze away to my heart's content without having to worry about the shrine maiden finding me. *sigh* I think it must be one of the best feelings in the whole world.",
      tips: '',
      tasks: null,
    },
    '64': {
      title: "___'s Troubles: Misunderstanding",
      audio: '6002',
      text: 'For some reason, when people meet me for the first time, they always call me tanuki, or teddy-bear, or kitty-cat... But ___ is just ___ — and definitely not a tanuki.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: "___'s Troubles: Height",
      audio: '6005',
      text: "When is my growth spurt gonna come? Everyone my age practically twice my height, and I'm still... Ugh, enough, I need sleep, sleep is the answer. Good night!",
      tips: '',
      tasks: null,
    },
    '66': {
      title: "___'s Troubles: Feedback Loop",
      audio: '6006',
      text: "Recently someone told me that if you get annoyed too easily, that'll stunt your growth, too! ...Gah! I dunno what I can do about that...",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'High-carb foods that give you instant energy, like rice balls. If you eat one the moment you wake up, it stops you feeling so groggy and bleary-eyed. Then, you can just relax and get straight back to sleep.',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Can't be picky about food when you've still got growing to do! ...That said, I haven't gained any height recently — maybe I'm not eating enough vegetables? But salad isn't filling enough and sometimes it can be really bitter... *sigh*",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "I'm soooo full, time for a nap...",
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'If you eat enough of this... it makes you really sleepy.',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Uh oh... Need an escape plan.',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Birthday',
      audio: '7001',
      text: "Wanna learn some ninja skills? I can teach you! Well, only the skills I know, of course. Hmm? Why aren't I asleep? ...Uhh, because I'm not sleepy... and also because today is a special day! I had to stay awake today so I'd have the chance to say it to you in person: Happy Birthday.",
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Is it just me, or did I get a little taller!?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '74': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Awesome, now I can slip away faster than ever. Hee-hee, they can't catch me now.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '75': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Hey, thanks for going and gathering all those materials for me. I would've gone myself, but... I probably would've got about halfway before falling asleep.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '76': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I think I'm finally ready to go it alone now, just like Sensei said I should. And... maybe it's not such a big deal now if I can't grow any taller. Because what really matters... is that I have you to keep me company.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Most Inazumans are unaware of the existence of the Shuumatsuban. In fact, the Shuumatsuban is a secret organization under the Yashiro Commission.\\nThere is also a little ninja who goes by the name of ___ in the Shuumatsuban, and this fact is even less known.\\n___ is a special existence in the Shuumatsuban. She has been raised in the Shuumatsuban since she was a child, and is extremely loyal to the organization.\\nThat said, her most prominent trait is not "loyalty," but "laziness."\\nLazing around is what ___ does best. She has long mastered the various arts of ninjutsu, particularly those that help her to slack off or shirk her duties, such as escape techniques and aura concealment.\\nPeople who don\'t know about her habits will have to make a lot of effort to find her.\\nHowever, if you ask ___ about her slacking, she will shrug and reply, "It\'s not that I\'m lazy, I just want to spend my time on more meaningful things."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: '___ is petite and can even be described as delicate.\\nThis is also something that bothers her —\\nOne by one, her peers are growing taller, but she still has the stature of a child, as her height has not changed at all.\\n___ is really anxious about this matter.\\nDay by day, the world seems to be sprouting skyward, and only she remains small as ever.\\nGrowing taller has gradually become an obsession in ___\'s mind.\\n"As long as I sleep long enough, I can definitely grow taller!"\\nShe came to believe this ever so firmly, seizing every opportunity to sleep as much as possible, creating every opportunity and circumstance, even when there were none.\\nPeople around little ___ often let her be, as they don\'t have the heart to disturb her sleep.\\nSo now, the situation has progressed such that ___ is able to fall asleep, even whilst standing.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "The ninjutsu that ___ has learned is not very powerful in combat, but it is quite useful in the matter of slacking off.\\nShe is extremely skilled at hiding and covering her tracks, and is an expert in this area. Therefore, if she has the intention to hide, ordinary people absolutely cannot find her.\\nHowever, even the most ingenious puzzles have answers, and even the most elusive treasures have clues for people to find them. This also holds true for ___.\\nAfter spending enough time with ___, one will understand her habits and preferences. Trying to find her doesn't seem so difficult anymore.\\nFor example, if you go to ___'s room early in the morning and lift the covers, the odds are that you will find her in bed.\\nAt noon, you can check out the trees near the shrine and who knows, you may find something unexpected.\\nIt will be more challenging to find ___ at night, but it's a good idea to go to her house and wait for her to emerge.\\nHowever, please remember not to disturb ___, who is busy growing taller, unless it is absolutely necessary.\\nEven gentle rabbits bite when provoked, let alone ___...",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "That said, finding ___ doesn't mean that she can be put to work quietly.\\nMoreover, ___'s work at the Shuumatsuban is not that of a fixed daily routine, but missions that pop up if and as needed.\\nAnd so, this happens:\\nWhen new missions are assigned, you won't see hide or tail of her.\\nBy the time she has been found (and with much effort), a more suitable person has been assigned for the mission.\\nAnd in case there is no other suitable candidate other than ___, all the more she will try to slip away, so as not to be overwhelmed by the mission.\\nIt's just that... If ___ used her ninjutsu to work hard, she would have had great accomplishments in the Shuumatsuban.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "___ is the last successor to the Ninjutsu Art — Yoohoo Art.\\nIn this school of ninjutsu, which is known for teasing its enemies, ___ has learned only ninjutsu such as escape and clone techniques.\\nThese ninjutsu are of little use in actual combat, but have an undeniable aesthetic flair.\\nAmongst falling leaves, a silhouette vanishes in a flash, a gentle breeze blows, and a kite suddenly appears on the ground... The incredible scene is comparable to an artistic performance.\\nThus, whenever there is a festival, ___ will be invited by various parties to perform her mysterious ninjutsu.\\nIf it's Yoimiya who's searching for her, ___ can still find ways to hide.\\nBut if the person in question is Lady Guuji Yae, resistance is futile for ___.\\nClone techniques do nothing to fool the Lady Guuji's sharp eyes, and aura concealment doesn't help ___ at all in escaping from the Lady Guuji's grasp.\\nRunning for the hills is even less feasible, and might even risk angering the Lady Guuji...\\nFortunately, there are very few circumstances that require Lady Guuji Yae to make a personal appearance.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'For as long as ___ can remember, she has been studying ninjutsu with her sensei in the Shuumatsuban.\\nAlthough the Shuumatsuban is a clandestine organization, the elders are very kind and have taken good care of young ___.\\n"Being overly reliant on others is never a good thing for a ninja."\\nAfter ___ had reached a bottleneck in learning ninjutsu, her sensei observed her situation and thought thusly.\\nAs the years passed, ___ grew steadily. Once she was capable enough to defend herself, her sensei chose to leave quietly.\\nA young animal that leaves the protection of its parents will grow up rapidly. The same is true of the sensei\'s expectations for ___.\\nThe young ninja did not disappoint her sensei. Soon after, ___ obtained a Vision.\\nAnd then, she started working diligently in the Shuumatsuban... diligently shirking her duties.\\n___ is always busy sleeping and hiding from people, so in that sense, she also has a lot to do.\\nOccasionally, when ___ is free and alone to enjoy the moonlight, she feels lost deep inside.\\nThe people who have always been with you will one day leave...is this how life is meant to be?\\nBut perhaps someday in the future, I will also meet the person who will always be with me.\\nPondering the matter, the little ninja fell asleep again...',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Mini Mujina',
      title2: null,
      text: "___'s outfit is said to be a gift from her sensei.\\nThe style references the form of a small animal — the \"mujina,\" and ___'s favorite colors were also specially chosen for it.\\nIt is light and flexible, thus making it suitable for a ninja.\\n___ is especially fond of the huge hood, as it brings about a sense of security.\\nThe long tail is designed for ___ to maintain balance on the branches.\\nAs for the only drawback... this outfit probably looks too much like a tanuki, and ___ often gets misunderstood because of it.\\nInitially, she would seriously explain to the other party that:\\n\"I'm not a tanuki, I'm ___.\"\\nHowever, over time, similar incidents have occurred too many times, and ___ now bears a grudge against tanuki.\\nNowadays, if such a situation happens again, ___ will pout in anger.\\nSo, in order to get along well with ___, please memorize the following:\\n___ is not a tanuki, but ___.\\nHer outfit is also not that of a tanuki's, but a mini mujina.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "This is the story of ___ when she just started being on her own.\\nFragile beings walking alone in this world inevitably find themselves in scary situations. The only way to understand what it's like is to have experienced it.\\nThis is exactly what happened to ___. Adept at observation and evasion, she has always understood that she is not suitable for combat.\\nHer overly petite stature gives her no advantage in terms of strength to speak of, and her ninjutsu will not be of much use in actual combat.\\nYet missions do not wait for ninjas to grow fully before descending upon them. In an era of turmoil, ___ would also find herself in trouble because of not-so-important work.\\nSurrounded by strong foes, she had to do her best and barely managed to escape. It cost her almost everything to bring the information back safely.\\nExhausted and wounded, ___ was about to faint, but only one thing lingered in her mind:\\n\"It's not only strong brute force that can overpower everything, the weak have their own way of surviving. It's because you're weak that you can notice those unseen moments that change your fate... The chances of escaping from here are slim, but that's what my ninjutsu is for.\"\\nThe moment the leaves fell, she disappeared. All her pursuers were incredulous. The tiny ninja disappeared as if she were dust in the wind.\\nThe next morning, ___ struggled to get up, and found that the ninja pack strapped to her leg had long since disappeared.\\nHowever, a surprising object appeared in the same place instead — a Vision gleaming in the sunrise.\\nNow, with the power of the Vision, ___ can wield a claymore taller than herself. She no longer has to fear the omnipresent strife of a chaotic world.\\nUnfortunately, ___'s most immediate worries have not yet been resolved.\\nRegarding her growing taller, it seems that even a Vision is unable to do anything about it.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
