export const ventiVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "*Yawn* That was a refreshing sleep. Ah, Traveler, we meet again! What? You don't remember me? Ahaha, well, allow me to join you on your quest once again. I must see to it that the bards of the world tell the Traveler's tales!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Playing the Lyre',
      audio: '1101',
      text: "Sure, I'll play you another tune, but it'll cost you an apple.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Apple Cider',
      audio: '1102',
      text: 'Right now I wish I was sitting at the top of a tree, looking out over a meadow, cider in hand...',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Ballads',
      audio: '1103',
      text: "Come on Traveler, let's go! The world is full of lost ballads just waiting to be rediscovered.",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Let's go jumping in puddles and see who can make the biggest splash!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: '1202',
      text: "It's stopped raining already? A shame, I wanted to play some more.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Let's wait till the snow gets heavier and have a snowball fight!",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: "The wind has returned! Quick, let's go gliding!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning! Ah... what's in store for today?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "My tummy is rumbling, but I can't get caught pilfering food from the Dawn Winery again... Oh, it's you! Where are you heading? May I join?",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Hmm, I'm still not sleepy. Fancy an evening stroll?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: 'Off to the land of nod? Haha, farewell, my friend!',
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___',
      audio: '2001',
      text: "Practice? Me? There's no need — I already know every song in Teyvat!",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: New Songs',
      audio: '2002',
      text: "I have decided to write a song about you! What are you giving me that look for? Can't afford it? Don't be preposterous, the price for you, my friend, is precisely zero Mora! Although... one thing you could do is tell me a few more of your stories!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Heroes',
      audio: '2003',
      text: '#Haha, once the {M#hero}{F#heroine} in the song has actually rescued the {M#princess}{F#prince}, I will ensure this song spreads to every corner of the continent!',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About Us: Apostles',
      audio: '2004',
      text: "Ahh... an evening breeze really sets the mood for becoming my disciple, don't you think? We can do it right now... you just need to make me a small offering...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 396,
              questTitle: 'Ending Note',
              chapterId: 1003,
              chapterTitle: 'Song of the Dragon and Freedom',
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About Us: Requests',
      audio: '2005',
      text: "What's that? You think I should try harder to be a good Anemo Archon? Well, you could be a better devotee too... you could be more pious, more passionate, or... um...",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 396,
              questTitle: 'Ending Note',
              chapterId: 1003,
              chapterTitle: 'Song of the Dragon and Freedom',
            },
          ],
        },
      ],
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: 'Hmm? You want to know about my Vision? Oh, go on then, take a look for yourself. I can make you a matching one if you like! Hehehe.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: 'Olah! Haha, that\'s how the Hilichurls say "hello." Why, I learned it to aid with my songwriting, of course! Vast knowledge makes for a richer composition... That said, I haven\'t actually written any songs in Hilichurlian so far...',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Traveler, have you ever seen a Cecilia? It's a magnificent white wildflower that only grows on the most remote mountains and clifftops. To me, at least, it is the most beautiful flower in all of Teyvat.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Jean',
      audio: '4001',
      text: "Acting Grand Master Jean... Well, what do you think of her? Yes, I couldn't agree more: conscientious, courageous... kind and considerate too. Reminds me of another good friend...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Diluc',
      audio: '4002',
      text: "I'm not surprised you want to befriend Master Diluc. Just think of all the vintage wine he must have stored away... Mwuhahaha... Huh? He doesn't let you sample it? Not even the slightest drop? Huh... Well, I guess you can still appreciate the aroma. That's still better than no wine at all, right? No?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Barbara',
      audio: '4003',
      text: "The darling Deaconess with the sweet singing voice — do you know her? You do? Idol, huh? Meet and greets? Concerts? Wow... That's the power of music for you...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Razor',
      audio: '4004',
      text: 'Ah yes, the white-haired fellow from Wolvendom? Raised by wolves? Really? ... No wonder his scent is so familiar...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Mona',
      audio: '4005',
      text: "Oh, that astrologer? How should I put it? Fortune-telling and my singing are the same: Both lead to you being so poor you can't even cough up the money for a drink! ...You think that astrology is a cultural tradition, so at least still has some value? Hmph, so rude. In that case, so too is singing, so it still has its value too!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Diona',
      audio: '4006',
      text: "There's a special drink known far and wide at Cat's Tail. But it ah... ahh... ACHOO! *sniffs* How about you go and fetch one for me? I'll be truly thankful, I promise.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Albedo',
      audio: '4007',
      text: "How do you explain white chalk in black soil, or the earth's dense crust amidst the emptiness of space? Same reason the purest soil gave birth to human life... It's an ancient power with unmistakable properties. Trying to harness it is dangerous indeed, I can't imagine what would happen if someone lost control of it in the city... Ah, never mind! What goes on within Mondstadt's walls is up to Mondstadt's people to deal with!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Morax',
      audio: '4008',
      text: "Have you seen that gentleman around? Huh? He's just a normal man by the name of Zhongli now? That must be quite the change for that old block-head. Come with me to see him, will you? I have a vintage I dug up from Windrise that I can take as a condolence gift. Oh, ahh... did he still seem strong when you saw him? How strong? Am I likely to get blown away?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '28': {
      title: 'About Eula',
      audio: '4009',
      text: "Eula has good taste when it comes to beverages of the alcoholic variety. Come summer or winter, she always likes them ice-cold. That's rare among Mondstadters these days! She and I would make great drinking buddies. Huh? My songs about the Lawrence Clan... She's heard them already? Eh, no harm done. Maybe she and I can do a duet sometime!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Baal',
      audio: '4010',
      text: 'So, I hear you defeated the mighty Raiden Shogun? Ah, I recall the days when she was a kagemusha, seeking to perfect her martial prowess. Hehe, she now no doubt employs a wide range of reasoning to get you to train with her. Oh but yes, come close and I shall let you in on her weakness — desserts!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 2021,
              chapterId: 1204,
              chapterTitle: 'Omnipresence Over Mortals',
            },
          ],
        },
      ],
    },
    '30': {
      title: 'About Buer',
      audio: '4011',
      text: 'The first thing you think of when you hear "Dendro Archon" is her power over dreams. Her dreams are akin to my ballads: full of emotion and imagination. It goes without saying that we get along really well.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 3026,
              chapterId: 1305,
              chapterTitle: 'Akasha Pulses, the Kalpa Flame Rises',
            },
          ],
        },
      ],
    },
    '31': {
      title: 'About Furina',
      audio: '4012',
      text: "A bard must be versed in both music and song, but a stage performer requires far more skills than just these... Hey, don't you think we should invite her over to put on a show at the next Windblume Festival? ...Huh? You want me to talk about how she saved Fontaine? Well, I mean, she's such a talented artiste, it's no wonder. I wouldn't be surprised even if she'd saved the entire world.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4025,
              chapterId: 1405,
              chapterTitle: 'Masquerade of the Guilty',
            },
          ],
        },
      ],
    },
    '32': {
      title: 'About Haborym',
      audio: '4013',
      text: 'This world sure is cruel, forcing generation upon generation of human heroes to become cannon fodder in the fight against darkness. But, under Mavuika\'s leadership, they achieved a truly god-like feat... Hehe, starting with "her," I suppose the Natlanese have always been like that. Ah, right! I heard Mavuika likes to drink! Are you thinking what I\'m thinking...?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 5029,
              chapterId: 1504,
              chapterTitle: 'Incandescent Ode of Resurrection',
            },
          ],
        },
      ],
    },
    '33': {
      title: 'About Dahlia',
      audio: '4014',
      text: "O, Traveler, do you seek to hear the voice of the wind and know its guidance? Then I say to you... chatting to the deacon is your best bet. Haha, I'm kidding — come chat with me over a drink any time you want! The reason I usually get Dahlia to be my intermediary is because... well, I imagine you can probably guess why. He loves listening to the blustering of the wind, but crucially he has his own compass, too.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'More About ___: I',
      audio: '5001',
      text: 'Perfect timing, Traveler! I was about to ask you — what is your greatest wish?',
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'More About ___: II',
      audio: '5002',
      text: "There's never a dull moment traveling with you! The only minor inconvenience is that pesky little pixie thing that follows you everywhere... She never stops eating — I can't begin to imagine how much you spend on food!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '36': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'The Pyro Archon is a wayward, warmongering wretch, and the Geo Archon is a brutish, blundering buffoon! How do I know? Because, this is written in the epic poems of days gone by!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '37': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "Celestia... I'm not sure even I could fly that far. In any case, the water there tastes foul, and the fruit is bland. You know what that means? No cider! Haha, in that case, I wouldn't go there even if I was invited.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '38': {
      title: 'More About ___: V',
      audio: '5005',
      text: 'My greatest wish? It has always been to roam free and experience the whole world. Now, I would add that wherever I go, it simply must be with you! Each day with you is an adventure, and where adventurers go, storytellers must follow!',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '39': {
      title: "___'s Hobbies",
      audio: '6001',
      text: 'I like to drink! And I like the wind! If only there were such a thing as wind-brewed cider...',
      tips: '',
      tasks: null,
    },
    '40': {
      title: "___'s Troubles",
      audio: '6002',
      text: "I'm actually highly allergic to cats. I start sneezing as soon as they enter the vicinity, and... Aah... Aa-choo! Ugh, apparently I can't even THINK about cats without sneezing. Do you think there is a cure for this monstrous affliction?",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Favorite Food',
      audio: '6003',
      text: 'Here, have an apple. I just picked it. Look how ripe and juicy it is... *munching* ... Truly the fruit of the gods.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Hmm, what's that tasty morsel you've got there...? Eww! A melted cheese pancake? A smelly, sticky, slimy, disgusting mess!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Ahh, quite delightful! So... could I get the same again tomorrow? ...And maybe the day after that?',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Oof, I'm so full... I'll have to pass on the post-meal fruits this time...",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "I can't believe it, but I don't think I can stomach this... Oh boy... What a predicament.",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Birthday',
      audio: '7001',
      text: "Someone once told me you're supposed to eat a cake on your birthday... Tada! Here's your birthday cake — it's apple-flavored! And here's a spoon. The cake didn't rise properly in the oven... That's why it looks more akin to an apple pie... Ugh, baking is really quite complicated!",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'Whoa! What was that?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Good work. Shall we repose for a moment with a tune? Shall it be a capriccio or a serenade?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Come, sit with me. I\'ve written a new poem. I call it "Wind of the Traveler."',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '50': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Hmm... Though I've long since viewed this scenery a great many times, there is something different about seeing it again with you. Surely you're not still concealing some other wondrous abilities? Hmm, even if you were, it would simply further prove that my intuition is correct.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Yoo-Hoo!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Here we go!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Brace yourselves!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: "Let's play!",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Think you can get away?',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Time for takeoff!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: "Wouldn't gliding be faster?",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Deploying Wind Glider: I',
      audio: '800001',
      text: 'Yahoo!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: '*clears throat* Have you heard The Ballad of the Treasure Chest?',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Thank Barbatos! Wait a minute...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "What a find! I wonder how many bottles this'll be worth...",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Ugh, I'm not in the mood for this!",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Oh, dear!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'That was uncalled for.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Let me try!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Don't give up!",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Let me sleep a while...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Oh no, my lyre is broken...',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Ah... Ugh...',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Ah!',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'How rude!',
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Give me a moment to compose myself.',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Didn't keep you waiting, did I?",
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Ready for a rehearsal?',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'An unknown bard that came from nowhere. He sometimes sings outdated songs, other times he hums new ones that none have ever heard of.\\nHe likes apples and lively atmospheres, but hates cheese and anything that is slimy.\\nWhen channeling Anemo, it appears in the form of feathers, because he likes things that look light.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Back when traveling bard ___ had only been in Mondstadt for a few months, his income was far less than the other more established bards in town. But once he had a few Mora in the pot from his performance, you could be sure he would hurry off to spend it at the same place every time — one of the city's taverns.\\nUnfortunately for ___, his childlike appearance meant that his attempts to acquire alcohol failed at every turn.\\nThe first time he was refused service, he was heard grumbling: \"I'm sure there were no such preposterous regulations last time I was here...\" Once he realized that the same rule applied to all taverns in town, he decided he would have to change his approach...\\nThe strategy he developed was drinking on the job — that is to say, playing the lyre while holding a wine cup in his mouth, urging his audience to buy him a drink from the bar if they liked his performances instead of giving him Mora.\\nThe novelty of this made him quite popular in Mondstadt.\\nThere was just one snag — he couldn't help but sneeze if a cat came close...\\nAnd if he happened to be holding a wine cup in his mouth when it happened... needless to say, it would spell disaster.\\n___, therefore, has one golden rule when selecting a spot to perform, and that is that there must be no cats in the vicinity.\\nEasier said than done — the stray cats of Mondstadt seem to be quite drawn to him.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "There is a towering oak tree at the center of Windrise, said to have sprouted when Vennessa ascended to the heavens a millennium ago.\\nIn the past few months, travelers resting in the shade of the great oak sometimes hear a young boy singing the tales of Barbatos, the Anemo Archon.\\nUnlike the ruling deities of the other nations, Barbatos has long left Mondstadt. In fact, the only visible proof of his connection with Mondstadt is the Statues of The Seven that appear across the land — even then, the resemblance is vague at best. Fortunately, Barbatos's past deeds are recorded in books and epics, sung and passed on by the bards.\\nIn contrast to these more canonical works, ___'s ballads tend to include bizarre adventures and acts of mischief, such as the time that Barbatos pinched the Cryo Archon's scepter and replaced it with a hilichurl's wooden club...\\nWorshippers of Barbatos are quick to decry these frivolous tales as blasphemous fabrications. But whenever someone confronts ___ about this, his response suggests that he has not an ounce of remorse.\\n\"How can you know that they're fabrications?\"\\nHe has a point — even the most devoted sister could not possibly know the details of all of Barbatos's deeds from a millennium ago.\\nOnly ___ knows the truth behind his song lyrics, and it is a truth he hides behind an enigmatic smile.\\nReason being, yes — ___'s tall tales of Barbatos's unorthodox exploits are entirely fabricated.\\nHey, ___ finds that a few drinks really gets his muse going. Can you really blame him?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Around 2,600 years ago, the Archon War had yet to end, and the world had yet to fall under the dominion of The Seven.\\nIn those days, the city called "Mondstadt" was surrounded on all sides by gales impenetrable even to the birds of the air. The wind\'s ceaseless howling ground the soil and the rock of that city into smooth, flowing dust.\\nThe Lord of Wind who lived in his high tower was Decarabian, God of Storms. He squinted from on high at his subjects, who bowed before him in the unceasing wind, and, believing them submissive, thought this good.\\nIn those days, ___ was but a single thread of the thousand winds that roared through the northern lands.\\nHe who would in latter days be known as "Barbatos" was but a tiny elemental spirit, without a shred of divine dignity, a breeze that brought subtle changes for the better, or tiny seeds of hope.\\nIn Mondstadt of old, ___ met a young boy. This lad knew how to play the lyre, and longed to write the greatest poem of all.\\n"I do so wish to see the birds in flight."\\nSo said the boy who had never seen the blue sky, eagles, or the green grass, his voice almost utterly drowned by the wind.\\n"Friend, will you not come along?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'The elemental being ___ obtained the feather of an eagle for the lad living in that storm-shrouded city, who had never seen a bird in his life.\\nThen, war broke out in Mondstadt, in the name of freedom.\\nWith the feather tucked away in his breast pocket, ___ watched the fall of the eccentric ruler amid the wrack and ruin of revolt together with his friend.\\nThe ruler had believed that he had given his subjects a city free from the bitter cold, and to the end, he believed that they had loved him as he loved them.\\nYet, despite the victory, ___ was never able to give that feather to the lad, for that lad had fallen in the battle for the sake of song, sky, and birds, and for the people who, like him, had dwelled within the storm-wall.\\nWith the crumbling of an ancient seat of divinity, a new god was born. The Anemo Archon Barbatos felt power flowing at his fingertips.\\nHis first use of this power was to reconstitute himself in the likeness of that young lad.\\nFor only if he wore human shape could he play the lyre that the lad so loved.\\nPlucking its strings, he scattered the ice and snow and split the mountains with a divine wind.\\nHe bade Mondstadt become a city of freedom, a nation without a king.\\nIn future, he believed, it would become a better, more romantic city.\\n"Surely, he too would have wanted to live in such a place."\\nThus, a new age began for Mondstadt.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "The Anemo Archon cannot take credit for everything in Mondstadt.\\nCredit should be given where credit is due, I shall sing now the praises of things beauteous and true:\\nWe thank the West Wind, whose enduring caress\\nBrings the blossoms of Spring, by whose scent we are blessed.\\n\\nFinches, ducks, rabbits and boars,\\nMondstadt's revival bid them thrive evermore.\\nIn summer the lion walks the plains,\\nNo words one finds to praise it but these:\\nDo you sweat out your water to make way for wine?\\nComes the heat of the summer from your mane of sunshine?\\n\\nThe mountain mouths and gorges low like drunkards wayward lie...\\nBut the East Wind cares not, for it doesn't walk — it flies!\\nOver the fruit trees it brushes low,\\nAnd its wings bring the harvest of things that grow.\\n\\nThe North Wind in the silent forest slumbers,\\nAnd around it pace the wolves in their numbers.\\nThough most have never a glimpse of them seen, for the Wind knows that none is of winter too keen,\\nYet the Anemo Archon glimpses and sees, that it dreams each night of warm reverie.\\n\\n—As the four seasons in turn shall say their piece, so the four winds too shall never cease.\\nOf course, to look at it differently, I am the one who should be credited here, and not they.\\nCredits should be given where credits belong — if not for the bard who pens the song, then who shall ensure that these tales are passed on?",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Where the Wind Doth Not Blow',
      title2: null,
      text: 'After 1,600 years of history, Mondstadt\'s "freedom" had sunk to a heretofore unseen low.\\nBarbatos, unwilling to become a tyrant, had departed. But he had never imagined that those to whom he had gifted freedom would make for themselves a tyrant.\\nThe aristocracy ruled Mondstadt with a cruel hand, bringing slaves into this land and ignoring the cries of the oppressed.\\nThus the Anemo Archon returned after these 1,600 years to what was once the City of Freedom. He heard the cry of the slave girl Vennessa, and together with her raised a rebellion that overthrew the aristocracy.\\n—Now, the above is what all know to be the official history of Mondstadt.\\nThe story has an interesting, little-known twist, however.\\nThe one who united the people of Mondstadt in this conflict was indeed the hero Vennessa — but that which caused many of the aristocracy\'s troops to turn coat was a "treachery against the wind."\\nA secret treaty was found, a betrayal of the city — the aristocrats had forsaken the wind, and sold everything in Mondstadt to the Geo Archon of the neighboring land.\\nAt the treaty\'s end was carved an insignia inimitable by all save the deity so named: Rex Lapis.\\nHow the soldiers that had once oppressed the slaves shuddered when they saw that they too would become slaves in a foreign land.\\nThe news, and the conflict, spread like wildfire, consuming the aristocracy. It was only many years later that historians would discover that this treaty was fake.\\nAs it turned out, ___ had once practiced the art of forgery in order to play pranks on the Geo Archon, but could never deceive the god of wealth and transactions. Even so, his adeptness would come into play after several hundred years.\\nWhat a happy coincidence.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'The Seven Archons do not need Visions, for they already have great power.\\nYet Barbatos was fond of the mortal world, and wanted to roam Mondstadt more freely as "___." As such, he constructed a glass ornament very much like the Visions worn by those chosen by the gods.\\nThe imitation has no special abilities, nor does ___ rely on it to channel elemental power.\\nHowever, since ___ does not keep the Holy Lyre der Himmel by his side, and since he is too lazy to bring a normal lyre, he gave his fake Vision the ability to turn into the wooden lyre "Der Frühling."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
