export const xiaoVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: 'If you awake to a knife at your throat, if monsters dig their claws into you, if death comes knocking at your door... Call out my name. Adeptus ___. I will be here when you call.',
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Idleness',
      audio: '1101',
      text: 'Reduced to just standing around... How absurd.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Wandering Spirits',
      audio: '1102',
      text: 'The damned will sooner die again than lay a hand on me.',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Corruption',
      audio: '1103',
      text: 'Grrgh... Those memories, so dark...',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Demons do not stop for the rain. Move.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: '1202',
      text: "The rain stopped? I don't concern myself with the weather.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When Thunder Strikes',
      audio: '1203',
      text: 'Many mortals fear lightning... Incomprehensible. Fear of something so common.',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When It Snows',
      audio: '1204',
      text: 'Once the snow is thick enough, we can eat it...',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "We're wasting time. Let's go.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Lunch... We'll go back to Wangshu Inn.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Night... When the darkness comes to envelop you. Don't stay outside.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Go. I'll be here.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Inhuman',
      audio: '2001',
      text: "I'm far from human. I can't make much of human emotions.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Liyue',
      audio: '2006',
      text: 'Liyue is changing. Rapidly... Forget it. It means nothing to me.',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Warnings',
      audio: '2002',
      text: 'If a day comes where even you are taken by the darkness, it will be up to me...',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Trust',
      audio: '2003',
      text: 'Do not fall prey to the darkness. I have no mercy.\\nThough, perhaps you can stand your ground alone.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Drowsiness',
      audio: '2004',
      text: "Who's there? Oh... You think I sleep? You have no respect for the ways of the adepti.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: Lantern Rite',
      audio: '2005',
      text: 'The Lantern Rite? The time for humans to discard their glowing trash into the sea has returned... How childish...\\nThough, if you insist... I will go with you.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About the Vision: Desires',
      audio: '3001',
      text: 'Visions? Desire? Ha. Do not judge adepti by your mortal ideals. I have no desire.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '19': {
      title: 'About the Vision: Reasons',
      audio: '3004',
      text: "Hiding? I'm hiding nothing. I just won't speak of desire to others.\\nDo you mortals not have a rule about spoken wishes never coming true? Hm? What do you mean that's not the same?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '20': {
      title: 'Something to Share',
      audio: '3002',
      text: 'I deal in death. If you cannot bring yourself to kill — speak my name.',
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Interesting things',
      audio: '3003',
      text: 'Dihua Islet was once deserted.\\nThough that was many decades... no, centuries ago...',
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'About Zhongli',
      audio: '4002',
      text: 'Can I ask... Zhongli — what does he do with his days? Huh? Birds, antiques, flowers...\\nHmm... What deeper meaning do they hold?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 1025,
              questTitle: 'The Fond Farewell',
              chapterId: 1103,
              chapterTitle: 'A New Star Approaches',
            },
          ],
        },
      ],
    },
    '23': {
      title: 'About Beidou',
      audio: '4003',
      text: 'Beidou? I have nothing to do with her. Though there is such a thing as the leviathan. As a mere human, she has proven her power in defeating Haishan.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Baizhu',
      audio: '4004',
      text: 'You want... Baizhu to make a medicine to take away my pain? I understand your intentions, but mortal medicine has no effect on adepti.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Hu Tao',
      audio: '4001',
      text: 'Hu Tao? Her liveliness is irritating. Fortunately, she is also humorous, so you need not worry about her growing into a boring human.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Venti',
      audio: '4005',
      text: "Venti? So that's the name he goes by. His tunes are... forget it.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Ganyu',
      audio: '4006',
      text: 'Ganyu is neither mortal nor illuminated beast. Wandering both the mortal and adepti realms with duty as her sole guide, it was inevitable that she would become perplexed... What? Me? You believe a yaksha who knows nothing more than how to massacre countless souls and emerge unscathed is a suitable mentor for such an individual? ...Your mind occupies a very different world from that which your body inhabits.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Shenhe',
      audio: '4007',
      text: 'It seems Shenhe places a great deal of trust in you. Well, how could she not. There are few people in the world as kind and good-natured as you.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 11015,
              questTitle: 'Where the Heart Finds Rest',
              chapterId: 1205,
              chapterTitle: 'The Crane Returns on the Wind',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'About Yelan',
      audio: '4008',
      text: "I've heard that she once investigated The Chasm, following the trail of the Millelith. If she can investigate mysteries like that on her own, she must be someone of rare skill.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About ___: I',
      audio: '5001',
      text: "I'm willing to protect you.\\nBut don't think about getting close, and stay out of my way, or all that awaits you is regret.",
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About ___: II',
      audio: '5002',
      text: 'In the thousands of years that have passed, I have taken countless wraiths. If you want no trouble, stay away from me. See me as a weapon, and nothing more.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About ___: III',
      audio: '5003',
      text: 'Their voices... I can always hear them. Their screams, their cries, demanding more death...\\nThis is my burden to carry. It has nothing to do with you.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About ___: IV',
      audio: '5004',
      text: 'Morax...? What do you know of this name!?\\nHe gave me the name ___, and released me from the endless pain I endured.\\nI will not forgive those that dare to speak against him, even you.',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '34': {
      title: 'More About ___: V',
      audio: '5005',
      text: "It's too late. The connection between us is too strong. Even if you wanted to, it's too late to sever it. Hm? You've never thought to sever it?\\n*sigh* This eternal dance of demon subjugation... My fight goes on.\\nBut, I would like to know more about you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "There's nothing timid about you, having the courage to ask about my hobbies.\\nSo, fight me. How long do you think your body will last against my blows?",
      tips: '',
      tasks: null,
    },
    '36': {
      title: "___'s Troubles",
      audio: '6002',
      text: 'Trouble? Ha. Trouble means nothing to adepti. There is no trouble that can last for a thousand years.',
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food: Almond Tofu',
      audio: '6003',
      text: 'I have no interest in mortal food. Cooking is tedious and the wait is long. The one thing I can manage to stomach is almond tofu.',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Favorite Food: Memories',
      audio: '6004',
      text: 'The taste of Almond Tofu feels like a fond dream...',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Least Favorite Food',
      audio: '6005',
      text: 'Wait. I am expected to place slices of meat in wrappings myself? And then... eat them? Together? Ugh, humans these days do not know what they are doing.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Mm... Not bad... Why are you staring at me?',
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'No need.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Try something else next time.',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Birthday',
      audio: '7001',
      text: "This mortal concept of commemorating the day of your birth really is redundant. Ahem. Wait. Uhh, have this. It's a butterfly I made from leaves.\\nOkay. Take it. It's an adepti amulet — it staves off evil.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'This is it? Nothing worth getting excited about.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'New power? All it will be used for is death.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "The limit to one's power is self-destruction. Answer me. Why do you persist?",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'Countless souls have fallen prey to these hands. I too have been swallowed by the darkness — and yet you dare to drive me on. You may think of me as... your companion. You seek to find me salvation? \\n...You... really are a difficult being to comprehend.',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Hmph.',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Boring.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Useless.',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Plunging Attacks: I',
      audio: '110001',
      text: 'Here!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Plunging Attacks: II',
      audio: '110002',
      text: 'Worthless!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Disappear!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Evil conquering!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Lament!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "If it's useful, I'll take it.",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Why would anyone want... *sigh* Forget it, it's not my concern.",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Hmph... there's quality here.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Shut it.',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Prepare to die, fool!',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: '*grunts* Good.',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: '...Weak.',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Get back if you wanna survive.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Is this... retribution?',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'The day... has finally come.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Impossible...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: "That's it?",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ugh, get out of my way!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'You called?',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Evil shall be dispersed.',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Conquering demons is what I do.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "___ may have the appearance of a young man, but his true age is something over two thousand years.\\nFortunately, people do not tend to underestimate him on the basis of his appearance — one only needs to spend a short time with ___ to clarify that he is not someone to be trifled with.\\n___ is a man of few words. He is highly dangerous, and has the most piercing gaze you've ever seen.\\nHe enjoys a formidable reputation and high level of seniority among the adepti, but is relatively unknown in the mortal realm.\\nThis is inevitable. ___ is not one of those popular deities to whom people pray for wealth and protection, nor is he a mystical sage of Jueyun Karst to whom pilgrims flock in search of divine wisdom.\\nNo... If any mortal witnesses ___ unleashing his true power, it is certain to be under the direst of circumstances — and they will be extremely lucky if they survive the ordeal.\\nThis is not because ___ seeks to harm people. Rather, since ___ wages a constant war against dark forces powerful enough to devour Liyue in its entirety, any bystanders who witness him in the heat of battle are likely to end up as collateral damage.\\nNot that this is a secret worth going around silencing witnesses for.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'What exactly is ___ wrestling with?\\nThe tactful answer would be old grudges, unfulfilled dreams, the lamentations of the vanquished...\\nThe unmitigated truth is that ___ fights against the remnants of the defeated gods from the Archon War, which took place prior to the rise of The Seven.\\nMorax defeated those gods and buried their remains beneath the rocks of the earth.\\nHowever, gods are immortal. Their consciousness may diminish, but their power and hatred will always remain and spread like poison, relentlessly stirring up chaos for the world and its inhabitants.\\nLiyue\'s rulers, who are aware of the truth regarding ___, refer to him in his millennia-long experience as the "Bane of All Evil." \\nThe war he fights can never be won, and will never come to an end.\\nIt is also an invisible war that no one will ever witness or thank him for.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '___ is not this yaksha\'s true name, but a name given to him in the interests of his own protection.\\nBack in a younger, more naive time, a god had gotten a hold of ___\'s weakness and forced him to serve as their bloodhound, in which capacity he was forced to perform cruel and violent acts.\\nMany died at his hand, many hopes were crushed, and he was even forced into devouring his victims\' dreams. As much as it pained him to do this, he was helpless to resist.\\nFinally, on the battlefield of the Archon War, Morax, the Geo Archon, had a fateful encounter with the yaksha\'s master.\\nThe current state of the world has already revealed the results of that battle.\\nRex Lapis liberated the yaksha and gave him the name "___." \\n"In the fables of another land, the name ___ is that of a spirit who encountered great suffering and hardship. He endured much suffering, as you have. Use this name from now on."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "To repay his debt of gratitude to the Geo Archon, ___ shouldered the burden of protecting Liyue in the millennia that followed.\\nHis past of service under the evil god had rid ___ of his innocence and gentleness. All that remained within him was the means to kill and the weight of his sins.\\nThe only way he could be of service to mortals was in doing battle.\\nBut what could people do for him in return?\\nNo ordinary person would ever stop to ask such a question. The sight of ___, even far off in the distance, was intimidating enough to send people instantly running for their lives.\\nThat said... if ever someone did want to show some appreciation for ___, there is perhaps one thing they could try.\\nThere is a certain secret agent of the Qixing who is tasked with supporting ___ in subduing demons. That secret agent runs a front organization called the Wangshu Inn.\\nOccasionally, ___ stops by the inn for a bowl of Almond Tofu, and if you could see the look on his face when he eats it... there's no mistaking it — he clearly loves the stuff.\\nNonetheless, it is not the sweet taste that ___ hankers after. It's the texture he finds irresistible — apparently, it's very similar to that of the dreams he used to devour.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "What exactly is ___ wrestling with?\\nTo those in Liyue's corridors of power, ___'s battle is against the evil manifestations produced by the remnants of defeated gods.\\nHowever, if you asked ___ the same question, he may well give you an entirely different answer.\\n___ was once enslaved by an evil god and suffered immensely under their rule until finally regaining his freedom thanks to Rex Lapis.\\n___'s powers were highly regarded by the adepti and he seemed to vanquish all manner of evil demons with consummate ease.\\nBut the evil gods also held immense power, and their lust for revenge ran deeper than mere mortals could ever contemplate. ___ relentlessly slaughtered the endless, impure manifestations of their vengeful souls, but in doing so, he caused them to fracture. Eventually, these fragments of their hatred were able to taint ___'s own soul.\\nThe only way to eradicate such hatred is to accept the karmic debt it brings. The magnitude of the bad karma ___ has accumulated over the years is enough to consume flesh, bone, and soul alike.\\nAnd yet, ___ does not feel any hatred. Having lived for over two thousand years, no single karmic debt constitutes anything more than a fleeting memory.\\nNo grudge can last a thousand years, nor is any debt so great that it cannot be paid off in this time.\\n___ has spent many long years alone.\\nBut his battles have never been in vain.\\nBecause ultimately, the one with whom ___ wrestles is himself.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "What does ___ fight against?\\nThe Traveler understands very well that ___ fights against the darkness that threatens Liyue. He fights to defend Liyue.\\nBut who will defend him?\\nThere was once when most of ___'s strength was spent fighting from dusk till dawn, with him emerging victorious by a mere hair.\\nThe reeds in the fields had been sliced to ribbons in the fierce fighting. Plucking his spear from where it had been planted in the ground, ___ began the trek home.\\nWell, one says \"home\" — yet, where did ___ have to return to? He was merely leaving the battlefield.\\nLong exhausted, ___ felt the divine hatred that tainted his body take effect.\\nLimitless hate flooded his senses, and he fell to the ground in agony.\\nBut it was also at that moment that the pain vanished without warning.\\nThis was not by ___'s own strength, for he had been rescued by the sound of a flute.\\nThe clear, lovely sound of the flute came over the mountains and rivers, carried on the wind to where he lay.\\nAnd clear it continued to ring till the first light of dawn brought with it the startled flight of distant birds.\\nIt protected ___, massaging his wild senses, and giving him a moment's peace.\\nWho was playing this music? ___ was curious but did not pursue the matter. For he already had something approaching an answer.\\nThe last person who could help him was one of The Seven themselves. So this person, too, must be—",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Ode to Windborne Wraith',
      title2: null,
      text: 'A scholar of the Sumeru Akademiya once did folklore studies in Liyue, the result of which was a book called "Tour of the Land of Liyue," with separate editions being available in Sumeru and Liyue.\\n"Hidden Diamond and Cloudy Moon: Wonders and Folklores of Liyue" is the version available in Liyue, and has had many mystical and magical portions removed.\\nThe "Ode to Windborne Wraith" is one of the mystical chapters that remain recorded within the complete version at the Akademiya.\\nThe document mentions that though the yaksha were mighty and upright among the adepti, they were bound by their own karma to suffer great horrors and tribulations. As such, they wandered the land in a state of unending suffering.\\nThe chapter lists many methods of comforting the yaksha, such as food offerings, holy chants, and the like. These would appease the yaksha and help them to continue defending the peace.\\nAs noble warriors among adepti, the yaksha would often descend upon the battlefield in person. However, as conflicts grew over the millennia, they have almost been wiped out. Today, large statues of the yaksha subduing demons remain within Liyue\'s borders, but they have had their features destroyed.\\nBy the by, the language used in that text was so meandering, and its contents so dense, that it sold far fewer copies than the Teyvat Travel Guide and the international cultural summaries written by El Musk.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'All adepti are known as the "mighty and illuminated" adepti, and this "illumination" refers to the light of a third "eye" that they possess: a Vision.\\nBut do adepti receive their Visions as a form of acknowledgment from Celestia, like humans do?\\n___ no longer remembers the moment he received his Vision. To humans, this would be an unforgettable event. But for him, this was just the beginning of his endless battle.\\nThe thing that ___ truly cannot forget is something different.\\nThere are a great many human festivals, and few remember the stories behind them.\\nThe greater part of these days coincide with occasions where man-eating monsters were defeated by the adepti host. People imitated their deeds and staged exorcism rituals to remember their ancient heroism, with these practices eventually evolving into celebratory festivals.\\nThe hatred and residual might of many of the gods defeated by Morax throughout Liyue will sometimes erupt with abnormal force amid their half-awake, half-dreaming state. Among them, the eruption that takes place during the Lantern Rite is the most extreme in scale.\\n___ has his mission to perform the time-honored "Nuo Dance of Evil Conquering," and so he fights night and day during the Lantern Rite. Thus, he has come to hate it.\\nNow, ___ did not consider battle dangerous. It was due to his hard work that Liyue was kept safe. People lit their lanterns, and the blessed lights shone across the night sky and the nearshore.\\nAt that moment, another special feeling blossomed in ___\'s heart. Loneliness? Peace? Or was it his fears for the future? The young-seeming adeptus searched his heart, only to find no answers.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
