export const bennettVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "This is your team? Cool... I like the vibe. I'm ___, leader of ___'s Adventure Team. Any chance we can team up? Please?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Treasures',
      audio: '1101',
      text: "Let's go find some treasure!",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Adventures',
      audio: '1102',
      text: "No one's joined me on an adventure in ages. C'mon, let's go!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Self-Deprecation',
      audio: '1103',
      text: '"Good things come to those who don\'t wait around!" That\'s what they say, anyway. Knowing my luck, the opposite is probably true for me...',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'It always rains when I go on an adventure.',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Don't stand too close to me, or you might get hit by lightning too.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: "Weather's not bad today... Oh crud, I jinxed it! Now it's bound to rain.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: "Careful! In this kind of wind, it's easy to get hit in the head by flying rocks.",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning! Where's the adventure at today?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "I brought a sandwich. You want some? I'll give you hal- *choking* *spluttering* ...Phew. Sorry, nearly choked to death there!",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Hey, wanna go talk to my dads for a bit? They tell the best adventure stories!',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "You're headed off? Cool. It was awesome adventuring with you. We should totally do it again!",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About ___: Adventure Team',
      audio: '2001',
      text: "I'm the leader of ___'s Adventure Team — a rising star in the Mondstadt Adventurers' Guild! ...Where are the others? Ah, haha, they're all on leave right now.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About ___: Bad Luck',
      audio: '2002',
      text: "Eh, it's not as bad as you've heard! Everyone falls into a trapper's pit or gets hit on the head by a falling tree now and then, right?",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Teammates',
      audio: '2003',
      text: "Hahaha, you wish! ___'s Adventure Team has had no vacancies in ages... I mean, you must be spoiled for choice, right? Why'd you wanna join the unluckiest adventurer alive, anyway?",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Division of Labor',
      audio: '2004',
      text: "From now on, I'll distract the monsters and set off the traps while you grab the treasure. Sound good? ...You don't like it? Oh — don't worry about me getting injured! It's what I'm best at... And for you, it would be my pleasure!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Dangerous Places',
      audio: '2005',
      text: "I think I get why you teamed up with me now. It's 'cause we're the same, you and I — we both like that adrenaline rush you get from being in dangerous situations. That's what makes adventuring so addictive!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "Getting recognized by the gods was the last thing I expected, seeing as how I'm so unlucky all the time. But if the gods haven't given up on me, I guess that means I shouldn't give up on me either.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "Do you wanna come and see the view of Mondstadt from above some time? It's real pretty at night, when the city's all lit up and you can see the moon reflected on Cider Lake... Huh? From where? Haha, well, there was this one time when I got picked up by a tornado and ended up on this cliff way up high— Not interested? Oh, okay then, never mind.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "I actually quite like cabbage. It's not much to look at, but you can't imagine a world without it. You can grow it anywhere, it goes with everything, and the flavor never gets in the way. I dunno, there's something... nice about being ordinary.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Barbara',
      audio: '4001',
      text: "She's the best singer and dancer out there! I always go to watch her in concert after an adventure goes south — it really lifts my mood, chanting along with all the other fans, cheering her on. It's really kinda magical! It's no wonder she's so popular... Boy, if I had even half her popularity as leader of my adventure team...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Klee',
      audio: '4002',
      text: "She's a cute kid... but I have to keep my distance. Whenever she plays with me, her bombs always end up going off... It's not so much me I'm worried about, it would just be awful if something happened to Klee. The Knights of Favonius would never forgive me, that's for sure.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Fischl',
      audio: '4003',
      text: "Oh yeah, the Prinzessin der Verurteilung from the world beyond! She's amazing. I keep asking her if we can go adventuring in her home world together, but each time I bring it up she sort of avoids the topic... She's probably just worried about my safety. Her home world sounds like a dangerous place, for sure.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Jean',
      audio: '4004',
      text: "I keep meaning to ask Master Jean for some help with the Mondstadt Adventurers' Guild, but I don't know how to go about it. The Guild doesn't have as many rules and regulations as the Knights of Favonius, the dads and I are pretty laid back about everything. Pretty sure that attitude wouldn't fly with Jean though... I guess I should read up on the Knights' etiquette or something?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Varka',
      audio: '4005',
      text: "He's my role model! Talk about team leaders — he's the Grand Master! Leads the whole darn Knights of Favonius! How incredible do you have to be to do that!? Recently, though, I've been thinking that having a smaller Adventure Team isn't such a bad thing after all. I mean, if things got too busy in the team, I'd have no time to look after all my dads in the guild, would I? Yeah... Yeah, things are fine the way they are.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Razor',
      audio: '4006',
      text: "Wolvendom guy! Looks a little on the feral side... doesn't talk much... but he's alright! We both love eating meat, so we got that in common. I sometimes cook some meat for him, and he teaches me how wolves communicate in return. Haha! You should join us next time!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Amber',
      audio: '4007',
      text: "Oh, I know who you mean. The girl who's always charging around all over the place. She's always off adventuring in the wild, just like me... But if you ever see her near a cooking pot, you'll soon find a cloud of thick black smoke blowing in your direction, followed by the smell of burnt steak... Huh, maybe she was born unlucky too?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Noelle',
      audio: '4008',
      text: "Noelle's someone I've been watching for a while. She's really talented, and extremely hardworking. But somehow she's still a maid — the Knights of Favonius still haven't made her a knight. It's a shame, don't you think? Boy, if she switched to the Adventurers' Guild, she'd easily be one of the best there is.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'More About ___: I',
      audio: '5001',
      text: "Oh... you wanna know about me? Haha, I'm just your average adventurer. 'Cept I'm more unlucky than average. Anyway, I'm nothing compared to you — you're the star of all those legendary tales. What do I got to show for myself?",
      tips: '',
      tasks: null,
    },
    '29': {
      title: 'More About ___: II',
      audio: '5002',
      text: '"The dads..." That\'s how I refer to all the older adventurers in Mondstadt. Apparently, I was an orphan kid that they rescued from the most perilous situation ever. How cool is that? I have such terrible luck all the time, and yet I was rescued against the odds and survived all this time. It\'s a miracle if you ask me.',
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '30': {
      title: 'More About ___: III',
      audio: '5003',
      text: "You've, uh, noticed then... Heh. Yeah, ___'s Adventure Team has been me on my own for a long time now. Reason is, I have such bad luck that even the most benign of adventures end up turning into the adventure from hell, and no one wants to come with me... Do you feel the same way?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'More About ___: IV',
      audio: '5004',
      text: "I was born unlucky. That's just the way it is, and I've lived with it so long now that I'm just used to it. But you know what? Maybe it's a good thing. It means I know that whatever luck I do have left is gonna run out sooner rather than later... so I'd better make the most of my life while it lasts. You know, go on plenty of adventures, meet loads of people... I mean, if I didn't live like that, I may never have even met you! Can you imagine? Haha!",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '32': {
      title: 'More About ___: V',
      audio: '5005',
      text: "Time flies! We've been a team for a while now, haven't we? Anyway, I have a dream I wanna tell you about. Once the Mondstadt Adventurers' Guild becomes the biggest branch in Teyvat, I wanna go adventuring all over the whole world! ___'s Adventure Team will be the greatest adventure team there ever was, because you and me are the greatest adventurers! ...\"Since when?\" Uh... I don't remember exactly when you signed onto ___'s Adventure Team. But whatever, it's just details, right?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '33': {
      title: "___'s Hobbies",
      audio: '6001',
      text: "I like all kinds of things, but most of all, I like adventures! One day, I'm gonna find the most valuable treasure in the whole world, and then my dads can have a better life... and the Mondstadt Adventurers' Guild will be back in business!",
      tips: '',
      tasks: null,
    },
    '34': {
      title: "___'s Troubles",
      audio: '6002',
      text: "Hmm... Well, if you really wanna know... When I have a bad day, I feel a bit glum. Like, it sucks when I come back empty-handed from an adventure, or when one of my dads' old injuries starts acting up. But... they're just small things, really. After a good night's sleep, I forget all about them. New day, new start! Haha!",
      tips: '',
      tasks: null,
    },
    '35': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Meat! Meat is the best sustenance there is. Chicken-Mushroom Skewers, Steaks, and Sweet Madames are all my specialties. You won't go hungry if you come adventuring with me, that's for sure!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "You can't really afford to be picky as an adventurer. That said, I can't really handle spicy food. I find it hard to breathe after eating Jueyun Chilis, like the spice went right into my lungs. And there's no avoiding the diarrhea afterward... It's the devil's fruit, I say. Who knows where it came from?",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Whoa, lucky me! Haha... Oh wait! Does that mean I just used all of my good luck for today...?',
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Literally everything you cook ends up tasting amazing. Hehe, you're awesome!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Oh no... my stomach hurts...',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! Best of luck in the year ahead. Don't worry, bad luck isn't contagious! As long as I'm around, it'll be drawn to me and not you, so you're safe.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'I feel stronger in every sense! Just as unlucky as ever, though. Hehe.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I'm catching up with you, Traveler! One step at a time.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Wow, check out all this power! How can I repay you, though? Hmm... Oh yeah! I know this Domain where there's a priceless treasure hidden somewhere inside! Let's go hit it up!",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Thanks to your help, I should finally be able to keep everyone safe now. Hopefully, people's opinions of me will start to change. Once the unluckiest guy alive, with a million cuts and bruises to show it. Now, a dependable adventurer at long last! ...Heh, well, I—I can hope.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '45': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Hah!',
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: "Let's light it up!",
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Get outta here!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: IV',
      audio: '100004',
      text: 'Haah!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: V',
      audio: '100005',
      text: 'Take cover!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: VI',
      audio: '100006',
      text: 'Outta the way!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Everybody stand back!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "I'm going in!",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Teamwork is dreamwork!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Adventure time!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: 'Off we go!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Now that's what I call treasure!",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Even better than I imagined! It's my lucky day!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "*chuckle* It's a miracle!",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Shoot, I can't afford any more bandages...",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: "Don't worry. I got this.",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'I always bounce back, just watch me...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "You're in over your head! Lemme try!",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Hey, pick on someone your own size!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: "___'s Adventure Team... I have failed you...",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'This is just my luck...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: "Couldn't break... the curse...",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: "Didn't see that coming.",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: "That's gonna hurt in the morning...",
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Why do they never miss?',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Y—You want me on your team?',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "I won't hold you back! ...Much.",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Gonna be epic!',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "___'s Adventure Team is an exception to the norm in the Adventurers' Guild, Mondstadt Branch.\\nInitially, the team mechanism requiring at least 3 or 4 regulars in each team was set up to promote mutual support and prevent accidents.\\nAs for ___'s Adventure Team, however, its only regular member has been ___ himself.\\nThe lack of team members essentially has everything to do with ___'s infamous bad luck.\\nHowever, being the passionate adventurer he is, ___ never feels lonely.\\nWell, maybe once or twice, sometimes...",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'The adventurer Jack was the first victim of ___\'s Adventure Team.\\nJust a few feet away from the treasure, an extremely rare Geo Turbulence occurred, tearing the ground apart and opening a bottomless chasm right before everyone\'s eyes.\\n"So close, yet so far... like love."\\nJack only suffered minor injuries, but he was never the same as an adventurer thereafter. The event seemed to have left him with a broken heart.\\nAnother member, Royce, heard someone shout "Heyo!" before losing consciousness in a huge explosion. The culprit, Klee, was sent to the confinement room for seven days for mistaking the cave the adventurers were still exploring in for a giant rabbit hole and blowing it up.\\nHeckler suffered from a severe bout of diarrhea for a week after joining the team. Although it turned out to be food poisoning, he insisted it was because of ___\'s bad luck.\\n"They\'ll be back! They\'re just... on leave. Please don\'t invalidate my team\'s registration with the Guild..."\\nSeeing ___ beg and plead before her eyes, Katheryne sighed and decided to spare him the truth that his "teammates" had long jumped ship.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'There was once a predicament of incomparable despair.\\nA predicament that had all but swallowed an old adventurer.\\nThe scorching flames scalded his skin, the deafening thunder almost ruptured his eardrums, and the hollering winds threatened to rip his soul from him.\\nAt the end of his hellish journey, what awaited him was... a baby.\\nThe old adventurer thought he was the first living thing to pass through this arduous ordeal. But how could he explain that which lay before him?\\nIn that moment, it hit him, and he believed it to be true.\\n"This baby must be... a child abandoned by the world itself."\\nThough there were no mighty artifacts, jewelry, or gold, the old man\'s face did not seem disappointed in the slightest, for he regarded this baby, whose life hung by a mere thread, to be his treasure.\\n"This child is what I was meant to find on this journey," he thought as he took the baby into his arms.\\nEven if what he was about to do opposed the will of the world itself, he was unafraid.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'The old adventurer died from severe injuries before being able to tell this story, leaving only the child he had saved.\\nOn his deathbed, he only managed four final words: "will," "adventure," and "final treasure."\\nSeveral single, childless, old adventurers in the Adventurers\' Guild in Mondstadt raised the child as their own and named him ___.\\nBeing raised by the Guild, ___ referred to everyone as "Dad."\\n"Dad, your dentures fell into the bowl!" "Dad, you should stop wearing that old leather armor. Where are the undergarments I bought you?" "Dad, it\'s raining, better keep your distance from me so you don\'t get struck by lightning!"\\nTaking care of all his aging dads who have no family has taken up most of his time outside of adventuring.\\n"The dads certainly have found a treasure, haha!"\\nCyrus, the current Guild Master, laughed, giving ___ a pat on the back.\\nThough he is unlucky himself, he can at least try to bring luck to those he cares about. At least, that\'s how ___ feels.\\n___ the Unlucky still strives to find his own lucky treasure through his series of unfortunate events.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Oz the Raven, Fischl\'s familiar, said ___ is "the most tenacious young man in the world."\\nIndeed, ___\'s share of bad luck throughout his life can be seen from his scars, old and new.\\nAttacked by monsters, buried in collapsed ruins, falling from cliffs... A wealth of "unfortunate events" has taught ___ how to deal with more of them in the future.\\nBarbara, the Deaconess at the Church of Favonius, was once surprised by how skilled ___ is at treating dislocated joints.\\nAnother gift from his ordeals is his jaw-dropping talent for combat.\\n"Look at his moves... Doesn\'t that hurt?" Grand Master Varka of the Knights was extremely intrigued after seeing ___ in combat.\\nIt\'s not that ___ doesn\'t feel pain — he has simply gotten used to it. He adapted to the pain as others would to pungent smells or blinding light.\\nTherefore, the way ___ dives into battles head-on without reservation has become a signature of his.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'What does death mean, exactly? Always walking the thin line between life and death, ___ can\'t help but wonder.\\n___ knows that the old adventurer who saved him has left many praiseworthy stories and legends after his death.\\nHe knows that adventurers will not have weeping at their funerals, only toasts made in their names by old comrades.\\nHe knows, to the adventurers of Mondstadt, a "good death" comes at the end of a life given to the pursuit of treasure and the secrets of the world. Once over, their souls are brought back to their homeland by Barbatos.\\nHe once feared death.\\nHowever, after pondering on this matter some more, he now feels death may be something fortunate for an adventurer...\\nNot that fortune has anything to do with him.\\n"Onto the next treasure!" And with that, ___ puts this thinking business behind him.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Adhesive Bandage',
      title2: null,
      text: 'Whenever he suffers severe injuries such as fractures or excessive loss of blood, ___ will go to the Cathedral to seek treatment from Deaconess Barbara.\\n"Sorry, it\'s me again..." ___ will say, scratching the back of his head.\\nBarbara, however, will just shake her head, and with a "let\'s deal with those scratches as well," she will toss him some adhesive bandages.\\nSuch displays of concern may be inadvertent, but they have a special place in ___\'s heart. He sticks those bandages on his wounds with the care of one pinning a medal to their chest, before thanking her wholeheartedly.\\n___ keeps many such bandages in his utility pouch when he goes on adventures. Ones he gets from his dads, from Barbara, from Katheryne... and from adventurers he sometimes meets by chance after getting injured.\\nThese tiny tokens of goodwill form a tangible collection of fair fortune unique to ___.\\n"Well, since everyone\'s by my side, I guess I\'m not that unlucky after all."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: '___\'s passion for adventure is unstoppable.\\nHe wants to constantly explore, challenge, sweat it out, and eventually grow old on the adventurer\'s path.\\nBut there was once when he met with a true crisis.\\nJust as that old adventurer had so long ago, ___ was in a predicament that would cause any other person to despair.\\n"Losing this much blood... Not good."\\nBut ___ did not stop. "There\'s no reason to turn back," he thought.\\nSomehow, he just knew that all the agonizing misfortune he had suffered up till this point was for the sake of overcoming this precarious position.\\nBut at the end of his hellish journey, what he found at the end was — nothing at all.\\n"Ha, returning empty-handed is... part of an adventure. I... don\'t mind..."\\nAt last, his tightly-wound emotions came loose, allowing his many injuries to rob him of his consciousness, and he collapsed.\\nWhen he reawakened, he found that his wounds had been cauterized by a mysterious flame, stopping both the bleeding and the pain.\\nA jewel pulsed warmly in the palm of his hand, its rhythm in time with the heartbeat in his chest — the beating heart of an adventurer.\\nThis was not the mercy of the world, or that fate took pity on him. Rather, this was his "final reward," one befitting a person with ___\'s burning passion.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
