export const hutaoVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Yoh, now why might you be looking for me, hm? Oh, you didn't know? I'm the 77th Director of the Wangsheng Funeral Parlor, Hu Tao. Though by the looks of you... Radiant glow, healthy posture... Yes, you're definitely here for something other than that which falls within my regular line of work, aren't you?",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Wangsheng Funeral Parlor',
      audio: '1101',
      text: 'Wanna come over for tea?',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Customers',
      audio: '1102',
      text: 'One client, two clients, three clients!',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Taking a Break',
      audio: '1103',
      text: "When the sun's out, bathe in sunlight. But when the moon's out, bathe in moonlight~",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: '*sigh* What a bummer...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "Lightning! Let's bolt!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Snow!',
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: 'Ahhhh~ What a nice breeze~',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: "My hat's gonna get blown away!",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Well are those who rise in the early morn, while those late to bed I shall forewarn~',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'Yo! Afternoon! Had lunch?',
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Hee-hee, moon's out, and so am I!",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: "Oh, you sleepy? Get some rest, I'm gonna take a walk by myself...",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Hu Tao: Name',
      audio: '2001',
      text: 'Hu as in "Who put me in this coffin?" and Tao as in "I can\'t geT OUt!" Hehe... No, not funny?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Hu Tao: Favorite Tricks',
      audio: '2002',
      text: 'Lemme show you some fire tricks. First... Fire! And then... Whoosh! Fire butterfly! Be free!',
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Curiosity',
      audio: '2003',
      text: "You've been all over, so you must've seen a lot. When you've got the time, tell me your story, yea?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Night',
      audio: '2004',
      text: "Run around all you like during the day, but you should be careful during the night. When I'm not around, best keep your wits about you.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About Us: Helper',
      audio: '2005',
      text: "Need a hand, need a hand? I'm here! If you need some assistance, I'm here to give it my all to the very end!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '18': {
      title: 'About Us: Battle',
      audio: '2006',
      text: "Fighting's a pain. For me, it's not an objective so much as a means to an end. Using the means to reach the end, to fight for that which I will not compromise on — it's in this way that you and I are the same.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '19': {
      title: 'About the Vision',
      audio: '3001',
      text: 'Vision... Vision...? Oh, this thing? Yeah, whatever...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'Something to Share',
      audio: '3002',
      text: 'We are entrusted by the people to loyally see out their wishes. Wangsheng Funeral Parlor is special, in that it carries a dual responsibility, to those both of this realm, and the next.',
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Some plants only grow in gloomier spots with ample moonlight. You ever seen any? Oh, no? Well, I'll have to show you next time.",
      tips: '',
      tasks: null,
    },
    '22': {
      title: 'About Zhongli',
      audio: '4001',
      text: "Zhongli looks young, but his personality is a bit dusty. Knows everything, but doesn't fret over anything. Hmm... Couldn't be that he's a...\\nHehe, forget it, whatever.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Qiqi',
      audio: '4002',
      text: 'Have you seen Qiqi? Tell me where she is, quickly. I need to go seal her away, hee-hee!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Baizhu',
      audio: '4003',
      text: 'Baizhu? Ugh, that guy...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Ningguang',
      audio: '4004',
      text: 'Tianquan Ningguang... Well-off, a radiant gaze, exquisite face, in the know and capable of anything!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Beidou',
      audio: '4005',
      text: "Beidou is well-known in Liyue. She doesn't know me, but that's cool, me just knowing about her is enough. Aw man... I really do wanna make friends with her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Xingqiu',
      audio: '4006',
      text: "I hear master Xingqiu is writing a book? Standard novella, or a ghost story? I think I should go tell him about all the things I run into — that'd make for a really good read!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Chongyun',
      audio: '4007',
      text: 'All yang and no yin? Huh, who knew such people existed in this world?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Xiao',
      audio: '4008',
      text: "What would I know of the adepti? Ai-yai-yai, that kind of stuff is top-secret! Don't come asking me about it!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Keqing',
      audio: '4009',
      text: "The Yuheng, Keqing... she's quite hard to talk to. She's so uptight, hehe... Really makes me wanna mess with her. She wouldn't knock me in the head with her sword though, right? Or would she...?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Xiangling',
      audio: '4010',
      text: 'Xiangling\'s a riot! Only a little "boo" and she jumps, she\'s so easy to scare! Being in the industry that I am, I just love these kinds of people the most. Gotta keep it in check though, in case Guoba ends up toasting me instead.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Yun Jin',
      audio: '4011',
      text: "Yun Jin always appears so graceful on formal occasions, but you'd be surprised how friendly she is in private! I made a bet with her once, and the loser had to sing lyrics of the winner's choice in their own singing style. My my, I wish you could have heard her operatic version of the Hilitune!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'About Shenhe',
      audio: '4012',
      text: "She is quite the fascinating individual, completely different from anyone else I've encountered. Do you think if I started eating divine herbs and drinking the dew of the mountains every single day, I'd be able to look as pure and pristine as she does? Oh~!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '34': {
      title: 'About Lan Yan',
      audio: '4013',
      text: "Lan Yan, you say? She's a lot stronger than she looks. She claims to only know a few of the Qimen arts, but she can get rid of dangerous things like fetor and illnesses! Aiya, there's only one problem... Removing all the bad stuff and making everyone all fit and strong isn't exactly good for the funeral business!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '35': {
      title: 'More About Hu Tao: I',
      audio: '5001',
      text: '♪Silly-churl, billy-churl, silly-billy hilichurl. Frilly-churl, willy-churl, frilly-willy hilichurl♪ \\nAh, hehe...',
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'More About Hu Tao: II',
      audio: '5002',
      text: "Versemonger of the darkest alleys — that's me!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '37': {
      title: 'More About Hu Tao: III',
      audio: '5003',
      text: "If you ask me, there's nothing hard or scary about working at Wangsheng Funeral Parlor, it's just a pain is all. It's a shame — others see us going out to work at night and just don't understand — and that's what scares them. *sigh* You all just don't understand!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '38': {
      title: 'More About Hu Tao: IV',
      audio: '5004',
      text: "I'm Wangsheng Funeral Parlor's 77th Funeral Director, my grandfather was the 75th. First thing I took over was funeral affairs. Haha, surprising huh? And just like that, it's already been a few years... Time really does go by so quickly.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '39': {
      title: 'More About Hu Tao: V',
      audio: '5005',
      text: 'Balance must be maintained, and yet destinies remain variable. Death has its own rules, and yet is still hard to predict. Remember — no matter where, no matter when, no matter what the reason — one should never poke fun at death. Only once you know and respect death can you truly understand the value of life.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '40': {
      title: "Hu Tao's Hobbies",
      audio: '6001',
      text: 'A bright moon aloft amid the vast, clear skies... Moments like these are just perfect for writing poetry.',
      tips: '',
      tasks: null,
    },
    '41': {
      title: "Hu Tao's Troubles",
      audio: '6002',
      text: '*sigh* I gotta find something fun to do... Sitting around doing nothing is a fate worse than death.',
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Favorite Food',
      audio: '6003',
      text: '♪La~la~la~ Steamed fish with a side of prawn dumplings~',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: 'Qingxin Slime Condensate... Bleugh... Surely this is Xiangling getting payback...',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Splendid, splendid! Now, allow me to compose a poem in loving memory of this dish.',
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Sure you don't want my help? C'mon, it's a great deal: cook twice the amount in the same time!",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: 'Ugh, I declare this dish dead, rest in peace.',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Birthday',
      audio: '7001',
      text: "Tonight the stars are dazzling and the moon majestic, it must be a special day... But just what day could it be... Haha, I know, I know! It's your birthday! It really is a great day.",
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: 'O-ya? O-ya-ya-ya?',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Yeah, this is good, thanks!',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '50': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'I never imagined that I, Hu Tao, could ever be like this. Energy like a rushing torrent, a heart soaring like a gliding eagle! I feel great!',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '51': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "If I reach my full physical potential, then the next test is of the heart. It's largely thanks to you that I've been able to step foot into this uncharted territory. It is here that heart and soul are as one like clouds. Death is a constant for all among the multitudes that sit beneath the heavens.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Huh!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Chi!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Suh!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Time to go!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Cross over!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Pyre, pyre, pants on fire!',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Huyoh!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: 'Go~',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Sprint Start: III',
      audio: '700003',
      text: 'Hyu~',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Deploying Wind Glider: I',
      audio: '710001',
      text: 'With the wind~',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Jackpot!',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Oh, what a cute treasure coffin!',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "If we bury it, maybe it'll spring back to life!",
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Ayaya!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Eeeeeee!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Low HP: III',
      audio: '410003',
      text: "This isn't good!",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Take it easy!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Lemme have a go!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Is it... my time?',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Fallen: II',
      audio: '500002',
      text: "I'll remember that...",
      tips: '',
      tasks: null,
    },
    '72': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Argh...',
      tips: '',
      tasks: null,
    },
    '73': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Quit it!',
      tips: '',
      tasks: null,
    },
    '74': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Oh? Is it time for me to join you?',
      tips: '',
      tasks: null,
    },
    '75': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Good eye!',
      tips: '',
      tasks: null,
    },
    '76': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Send one, send 'em all!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "The 77th Director of the Wangsheng Funeral Parlor, a young lady managing the parlor's operations. Despite her position, she's an amiable person who puts on no airs.\\nHer antics are as plentiful as the sand on Yaoguang Shoal. She never ceases to shock people with her countless bizarre ideas.\\nHu Tao may seem like all play and no work, spending every free moment on leisure and being widely considered a laissez-faire business owner.\\nIt is only during funeral ceremonies, when she personally leads her undertakers through lamp-lit alleys, that she shows her dignified and solemn side.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "Funeral ceremonies allow mortals to leave this world with dignity.\\nAnd Liyue's Wangsheng Funeral Parlor is said to be painting the last strokes on the scrolls of people's lives in the most respectful way.\\nTraditional funerals include multiple steps such as holding a wake, burial, putting up a memorial plaque... All of which are subject to strict rules.\\nRegardless of their social standing and level of wealth, all who depart deserve a ceremony that would do them honor. This is the Wangsheng Funeral Parlor's client service philosophy.\\nOne would think that such a reputable organization ought to be led only by an individual of utmost learning and sagacity.\\nYet the heavy mantle of the 77th Director has fallen on the shoulders of a young lady like Hu Tao.\\nShe has got quite a reputation in Liyue. Whenever someone mentions Hu Tao, their neighbors find it extremely hard to navigate the conversation.\\nAlthough she is widely praised for her wit and shrewdness, her eccentric notions are not as welcome, as she often lets her imagination run wild.\\nAs a three-year-old, she would read through volumes of classic texts while doing handstands. At six, she would cut classes and fall asleep in coffins. When she was eight, she started living in the parlor and learning the etiquette of funeral ceremonies...\\nOne would never use the word \"measured\" to describe her behavior.\\nDuring her teenage years, Hu Tao was tasked with conducting a funeral ceremony for the first time.\\nThe parlor's undertakers and consultants were anticipating her debut with their stomachs in knots as if they were suspended over the peaks of Jueyun Karst.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Fortunately, Hu Tao treats the parlor's operations with the utmost importance and is always looking to grow her business.\\n\"At the Wangsheng Funeral Parlor, the living give us Mora to see the dead on their way. We have a responsibility to both parties, so we gotta make sure both sides are happy.\"\\nWhen it comes to the parlor's rules, Hu Tao knows them all like the back of her hand.\\nEach day when the parlor closes its doors, Hu Tao invites consultants from different walks of life to pass their teachings on to the undertakers.\\n\"The funeral tradition is like science. It cannot be performed based on impressions and personal habits.\"\\nOf all the lecturers, Zhongli is the most revered one. As such, his lessons have proven to be the most effective in cultivating the competence of Wangsheng Funeral Parlor's undertakers.\\nDespite often being teased by Hu Tao due to his old-fashioned style, he is also the person that she trusts the most.\\nApart from that, Hu Tao always instructs her undertakers to respect their clients' wishes and not insist on any particular form of funeral.\\n\"Some clients want nothing more than a peaceful ceremony, some opt for a more lively style of event. There are also wealthier clients who would request a funeral arrangement of the most pompous kind. The services we provide have to be tailor-made according to the clients' needs.\"\\nEver since Hu Tao took over, the parlor's operations have been solid and reliable, with ceremonies conducted so tactfully that quite a few superstitious people in Liyue have changed their attitudes towards funerals.\\nEven so, Hu Tao still has a tendency to wander off, disappearing as soon as her undertakers are busy listening to lectures.\\nThe hobbies and interests of this young director are just as eccentric as her personality, and yet it is difficult to say with certainty if those activities are of a purely leisurely nature.\\nHu Tao's shadow can be seen in the moonlit docks or at the highest, most precarious viewpoints in the mountains, where she's likely to take in the scenery and shape her thoughts into beautiful poetry.\\nShe loves to roam freely at night, looking for inspiration. When it strikes her, no matter where she is, she cannot help but compose a poem on the spot.\\nIf they are particularly lucky, the traveling merchants taking respite around the Huaguang Stone Forest can spot a mysterious girl keeping herself amused in solitude.\\nHu Tao can play a four-player card game accompanied by no one for hours on end.\\nThat said, the joys of engaging in such activities remain a mystery to all but Hu Tao herself.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "The Ministry of Civil Affairs is guarded by two life-like stone lions, a symbol of power and authority.\\nHowever, Hu Tao, who happened to be passing by the ministry building one day, saw them in a different light. At first, she examined the lions with a thoughtful look, but soon enough, her pensive face gave way to a wide smile, as she slapped them on the fore-paws.\\nFrom that moment on, Hu Tao often visited and petted the stone statues. Not only would she talk to them, but also give them pet names — Whiskers for the one on the left and Mittens for the one on the right.\\nOn occasion, she would even bring a bucket of water and a big brush to bathe them, each move so careful and deliberate that one might think that they were her actual pets.\\nAs it happened, another feline, a living and breathing calico cat, could be found enjoying the local delicacies in front of Xinyue Kiosk, not too far from the ministry building. One day, some city folk came to play with the restaurant's favorite, providing an interesting foil for Hu Tao's peculiarities. Met with befuddled gazes of the bystanders, Hu Tao showed unwavering confidence.\\n\"Sure, your kitty's cute, but the same can be said about my Whiskers and Mittens. Their fur might be harder, but they're still just as fluffy! Any animal that brings people joy may become a pet. And when it comes to majestic looks, your little fur-ball simply can't measure up to my lions!\"\\nSuffice to say that this explanation was met with even greater consternation from the onlookers.\\nYet the group of people shocked the most and most often by Hu Tao's antics were the ministry guards. Soft footsteps could often be heard in front of the building at around midnight. Initially, the guards suspected that it had been a thief preparing to rob officials. To their unceasing surprise, it would turn out to just be a young lady playing with the stone lions.\\nThe guards were faced with an even bigger conundrum when, once everyone had reluctantly got used to her presence, Hu Tao discontinued her visits.\\nThat meant that the responsibility for cleaning the statues fell on the guards' shoulders once again.\\nSubsequently, they decided to keep guard by the lions for many days, anticipating Hu Tao's return. Once they finally had the opportunity to ask her why she would not visit anymore, they received the most absurd of answers.\\n\"Whiskers and Mittens are adults now and can take care of themselves! Excuse me, I'm running late for my heart-to-heart with a Statue of The Seven regarding the meaning of life!\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: "Not long after her initial meeting with the little zombie, Hu Tao decided that, as her self-proclaimed true friend, she should grant Qiqi eternal peace.\\nHu Tao would go on to kidnap Qiqi several times following much deliberation in every instance, including calculating the most auspicious time for the ceremony, aiming to follow the standard procedure of cremation, after which she would place Qiqi in a tomb on the outskirts of the city.\\nIn fact, she would have succeeded already if not for Baizhu's timely interventions.\\nEach time the Bubu Pharmacy's owner managed to catch up with them, Hu Tao had already had Qiqi packed in a bag, with only her head sticking out, staring in utter confusion as Hu Tao was vigorously digging a hole for the pyre.\\nAfterwards, Hu Tao sent Qiqi an apology letter, in which she expressed deep regret that she had not been able to lay Qiqi to rest fast enough.\\nIn Hu Tao's eyes, Qiqi passed away a long time ago, but has been trapped in this world and cannot free herself of her eternal suffering.\\nBaizhu, for his part, had grown ever more relentless in his pursuit of eternal life after meeting Qiqi. This act of defiance against the cycle of life and death was unacceptable to Hu Tao.\\nShe wanted to bury Qiqi not only out of consideration for her friend but also to restore the natural order.\\nBut Qiqi could not disagree more, as she was afraid of death and disliked Hu Tao for her attempts.\\nBecause the struggle between Hu Tao and her had been going on for so long, Qiqi has experienced a breakthrough. She has started to remember places where she might hide to avoid being captured by Hu Tao.\\nPerhaps it was due to those desperate survival efforts that Hu Tao decided to do something unusual and dig deeper into Qiqi's past.\\nThe story of her accident and the mystery of the adepti... That series of coincidences filled Hu Tao's heart with hesitation.\\nSince Qiqi's will to live is so strong, she should not be forced to move on. Given the circumstances, she could only be treated as a rare exception that eludes the natural laws.\\nEver since, Hu Tao's attitude towards Qiqi has changed drastically, to the point that she would pamper her.\\nUnfortunately, the damage has been done and Hu Tao has become Qiqi's bugbear. The little zombie may need several years more to let go of her grievances.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Hu Tao is not, in fact, best known for her role as Director, but for her other great accomplishment: the creation of poetry.\\nShe dubs herself the "versemonger of the darkest alleys," and free verse flows forth untamed from her mouth whenever she has free time to be out on the streets.\\nThe "Hilitune" is Hu Tao\'s most famous work, well-loved not only by the people of the harbor, but ever on the lips of children as far as Qingce Village as well.\\nHobbyists and critics alike were greatly surprised by the simple but profound originality of the "Hilitune" and its creation, and went to Wanwen Bookhouse in droves to search for the works of this great poet. Unfortunately, Hu Tao\'s anthologies, named "Fiddlesticks" and "Of Common Lives" respectively, have yet to be published.\\nXingqiu, ever immersed in books, also wanted to meet this strange person, and so chose an auspicious date to visit, bringing a gift with him.\\nThe two hit it off immediately, and they exchanged pointers and impromptu poetry in Wangsheng\'s main hall — and when faced with the poetry of Xingqiu\'s traditional, artistic bent, Hu Tao could always return in kind with some strange and marvelous verse.\\nAnd there was meaning in the chaos, indeed, a rhythm to the bizarre that anyone could perceive, and it was catchy, too.\\nThus did she "beat the old master with untrained fists," leaving Xingqiu at a loss for words.\\nAt length, the poetic spar ended amiably, and they have been friends ever since, reading and composing poetry with one another when they have the time to meet.\\nOver time, Chongyun, too, was pulled in to serve as an umpire, their laughter filling the streets.\\nThe poems born from these sessions would also be recorded by bystanders.\\nIf ever you should hear a pair of matched verses, one strict and the other playful, you are most likely to have heard one created jointly by Hu Tao and Xingqiu.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Harmony Hexagram Hat',
      title2: null,
      text: 'This hat is somewhat on the hard side, and the insignia of the Wangsheng Funeral Parlor adorns its front.\\nIt is said that this hat was passed from the 75th Director to Hu Tao. However, that director was large, musclebound, and had a head at least two sizes larger than hers.\\nUltimately, Hu Tao had to spend an entire day and night to modify the hat with her own hands such that its dimensions would fit hers. When she meets others, she tells them: this hat is magical, upholding good and repelling evil, and is a bringer of peace!\\nThe undertakers laugh and leave it at that, but the 77th Director clearly does treasure that hat.\\nNo matter the rain or storm, or if Hu Tao returns late covered in muck, that hat will remain spotless and clean.\\nThe plum blossom that adorns the side of the hat is plucked from a plum tree that Hu Tao planted and grew herself.\\nIts creation process is as follows: pluck and air-dry, then paint, lacquer, and outline carefully before sun-drying for three days and voila — a beautiful accessory, soft to the touch and bearing a delicate fragrance.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'This tale should begin with the funeral of Hu Tao\'s grandfather.\\nTen days before the funeral itself, Old Hu had passed away following a bout of illness. For its 75th Director, Wangsheng Funeral Parlor held a grand funeral, in accordance with the last wishes of the old man himself, to be conducted by Hu Tao.\\nOnly thirteen at the time, Hu Tao, who would later go on to become the Director in turn, made all the arrangements herself to the highest standard, greatly impressing the undertakers.\\nAfter the funeral, the thirteen-year-old Hu Tao grabbed her traveler\'s bag and crept out alone in the dead of night. In her bag were only a few rations, some water, and a means to create some light. She was headed to a mysterious and seldom-seen frontier.\\nHeading straight from Wuwang Hill, one may arrive at the "border." It is the line that separates life and death, the secrets of which have been managed by Wangsheng Funeral Parlor for generations. According to legend, it is a place where the souls of past relatives and the spirits of those with unfulfilled aspirations linger. For Hu Tao, this journey was a chance to see her grandfather once more before he departed forever.\\nFor two days she journeyed unceasingly before finally arriving at her destination, yet was unable to locate her grandfather upon arrival. Between the innumerable spirits she walked, but not one of them resembled the old man.\\nShe stayed there the whole day before falling asleep in exhaustion, awakening to a night sky and heavy dew. Around her were gathered a few lone spirits, clapping and laughing:\\n"Silly girl, why would Old Hu be here of all places? What were you thinking, looking for your relatives here?"\\nNot one to be swayed so easily, Hu Tao continued to wait, day after day. Her rations gradually disappeared and her water supplies drained away, but her grandfather did not appear. In the end, it was a little old woman who came to her.\\nShe laid eyes on the exhausted Hu Tao and smiled as she spoke: "Look at your stubbornness, you\'re exactly like Old Hu. It\'s a shame, but none of the Wangsheng Funeral Parlor Directors would ever linger here. You come from a family of plain speakers, so let me return the favor... Go back. Go back to where you came from."\\nThe old woman bid farewell to Hu Tao, before passing over the border and into the distance. Hu Tao watched as the figure of the mysterious woman grew smaller and disappeared, as a sense of doubt tinged with relief manifested itself.\\nAt last she came to the conclusion: her grandfather\'s absence was due to him having passed over the border as soon as he\'d arrived, to the place where he was bound. He had been open and honest in life, leaving behind no regrets, so was it right for his departure to be framed in regretful terms?\\nWith a smile, she set forth on the return journey.\\nThe faraway moon had been casting a thin light on the way over but had now been replaced by the bright light of dawn. As she walked, Hu Tao thought of a saying that her grandfather had often quoted: "Live in life, die in death. Follow your heart, do what you can."\\nIt was noon when Hu Tao arrived home. She climbed over the wall into the rear courtyard, went straight to her room, and unpacked her travel bag.\\nWith her food and water long gone, and the rest of her belongings unpacked, the bag she had taken for empty instead contained a colorful Vision. Just when had it arrived?\\nAs one of the few living that had dared to visit the border, perhaps Hu Tao\'s actions had moved some unknown god.\\nPerhaps this then constituted a heavenly gift... the ultimate recognition of her strength.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
