export const kleeVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Spark Knight Klee of the Knights of Favonius, reporting for duty! ...There's some more, but uh, I forgot. I'm not so good at remembering...",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Spoils',
      audio: '1101',
      text: 'Klee was a brave girl today! I found a really weird-looking lizard! Want me to show it to you?',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Adventures',
      audio: '1102',
      text: "Do you wanna come fish blasting with me? I'll get grounded for a whole day, but it's way worth it 'cuz the fish taste sooo goood!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Rules',
      audio: '1103',
      text: '"Explosion inside city wall, grounded be thy woe," "Explosions can hurt people, Jean can be dreadful," "Mondstadt be bombed, Klee be doomed." Those\'re the survival rules that the Knights of Favonius gave me.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Mwuhahaha, lucky all my new bombs are waterproof!',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "What'd I blow up!? ...Oh wait, it's just thunder and lightning. Phew.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Wind Is Blowing',
      audio: '1203',
      text: "Dear Anemo God, please make Klee's bombs blow in the right direction and only blow up bad guys. The end.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Good Morning',
      audio: '1001',
      text: 'Good morning! Can I come play with you today? Pleeeease? I wanna go on an adventure!',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Afternoon',
      audio: '1002',
      text: 'Lunchtime! What do you wanna eat today? Let me see if the Teyvat Travel Guide has any suggestions...',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Evening',
      audio: '1003',
      text: 'Good evening! Can you please tell Huffman that Klee is not a baby and is definitely allowed out to play at night? Please take me out to play together!',
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Night',
      audio: '1004',
      text: "Hey... Um... I know I said I don't wanna go home and all, but now it's nighttime and I can't find my way home in the dark... Can you please take me home on your way back? Pleeeease?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'About Klee: Incidents',
      audio: '2001',
      text: "Ohhhhh... I broke one of the blades on the windmill— I'm really sorry!",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Klee: Reparations',
      audio: '2002',
      text: "I'm really good at fixing things though. I can help! Huh? What do you mean that's child labor? What even is child labor? Does that mean I can't help?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Us: Knights',
      audio: '2003',
      text: "Hee-hee, you're an Honorary Knight but I've been a Spark Knight longer... That means I'm higher up than you, right? So you have to do what I say! So, um... Ca—Can you not say anything about the big disaster I caused? It was an accident...",
      tips: 'Complete "For a Tomorrow Without Tears"',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 384,
              questTitle: 'Reunion With the Dragon',
              chapterId: 1002,
              chapterTitle: 'For a Tomorrow Without Tears',
            },
          ],
        },
      ],
    },
    '14': {
      title: 'About Us: Playmates',
      audio: '2004',
      text: "No! It's only nine o'clock, I'm staying up to watch the circus' special midnight performance! You're supposed to be my best friend! Don't even think about trying to send me home!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: '3001',
      text: "This little marble is supposed to be a present from Barbatos to say well done? Well done for what though? ...Hmm, he is the god of freedom I guess, maybe that's why he likes me? Alright, from now on I'll say thank you to Barbatos by showing that I have the freedom to blow up as many fish as I want! ...Am I doing it right?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share',
      audio: '3002',
      text: "At the Knights of Favonius building, you're not allowed to blow up the walls. Shame, it would make getting out of solitary confinement way easier... but if I did so much as try to blow up the wall, Jean would make sure Klee never sees the light of day again. That's what Jean said, Kaeya told me.",
      tips: '',
      tasks: null,
    },
    '17': {
      title: 'Interesting Things',
      audio: '3003',
      text: 'Every lizard has a different pattern on his back, and some of them you can use their dried-out tails to make gunpowder with. I know because Albedo told me so.',
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'About Razor',
      audio: '4001',
      text: "Razor's one of my best buddies! Whenever a disaster happens, he always knows the best way to fix it and helps keep Klee safe. Um, but most of the time I'm the one who caused the disaster...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'About the Parents',
      audio: '4002',
      text: 'My mom and dad are the famousest travelers in Teyvat! Mom writes the Teyvat Travel Guide, so all the restaurants and hotels in the whole world care what she thinks about them.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Kaeya',
      audio: '4003',
      text: 'Kaeya is the best! He wrote the Favonius Survival Rulebook for me and he always helps me cover it up when I make a big disaster.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Amber',
      audio: '4004',
      text: 'Amber is the best! Baron Bunny is so fluffy and he even explodes! So. Cool.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Jean',
      audio: '4005',
      text: "Master Jean is the best! But she's also a little bit scary.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Diluc',
      audio: '4006',
      text: "He's one of the weird grown-ups. He's so grumpy all the time... Why does he never smile?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Lisa',
      audio: '4007',
      text: 'Lisa is the best! She always sneaks me some treats when I visit her at the workshop. ...Huh, I just remembered I was gonna ask her if I could use the workshop to make some new gunpowder. But I totally forgot...',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Bennett',
      audio: '4008',
      text: 'Bennett is the best! I always find way more treasure if I go adventuring with Bennett! ...But he never finds any. Why is that, anyway?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Diona',
      audio: '4009',
      text: "Diona is the best! I like listening to her, last time I heard her say, \"I'm gonna destroy the wine industry in this city if it's the last thing I do!\" And I'm gonna help her using my bombs! ...I don't know what a wine industry is though. Is it a monster?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Albedo',
      audio: '4010',
      text: "Me and Albedo have a secret code! Whenever he puts a sign on his workshop door saying \"Experiment in Progress,\" that's code for \"Come Back Later, Klee.\" Albedo's really nice and he's so patient with me, so I don't mind waiting until he's finished with his work.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Mona',
      audio: '4011',
      text: "Mona is the best! It's so much fun when she comes to play with me and Albedo. She talks about all these amazing things, and I don't understand most of it but... Ah, I just love it when Mona comes round!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Sucrose',
      audio: '4012',
      text: 'Sucrose is the best! This one time she asked me if I wanted a Jumpy Dumpty that can run as well as jump. Tee-hee, well duh! Of course I do, I want hundreds of them! I wanna put them on every street, every staircase, and every square in Mondstadt!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About Klee: I',
      audio: '5001',
      text: 'Hello, are you here for playtime with Klee?',
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About Klee: II',
      audio: '5002',
      text: "Yeah! This is my new and improved bomb! Whaddya think? Great huh? ...Oh, but ahh... If you find it near any fires, it's not mine. Definitely. Not. Mine.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About Klee: III',
      audio: '5003',
      text: "Sure, time in solitary confinement gives lots of time to think about new gunpowder formulas... But it'd still be better to not be in solitary in the first place.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About Klee: IV',
      audio: '5004',
      text: 'This is Dodoco, my oldest and bestest friend! Okay, now I\'ve introduced you, don\'t forget her name again alright? No more calling Dodoco "that silly doll Klee always hangs on her rucksack."',
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '34': {
      title: 'More About Klee: V',
      audio: '5005',
      text: "Thanks for helping me out every time I get in trouble! I have a thank-you present for you — barbecued fish, made with my own secret recipe! ...Okay, so the secret recipe is exploding the fish out of the water. Tee-hee, they're fully cooked by the time they land! But it's a secret, right, so you don't get to tell anybody. Just pretend like you don't even know.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: "Klee's Hobbies",
      audio: '6001',
      text: "I like things that are fluffy~! Like Dodoco! And dandelions! And Razor's hair!",
      tips: '',
      tasks: null,
    },
    '36': {
      title: "Klee's Troubles",
      audio: '6002',
      text: "*sigh* You're a good person, but I'm a bad girl. Once I'm out of solitary confinement and am done reflecting on my actions, we can go play together again, okay?",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Mondstadt's basses are delicious, especially the ones you grab yourself from Cider Lake! I'm not even kidding, even my mom thinks so.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I hate, hate, hate Mondstadt's crabs! All of them! I wanna go out and play, I don't wanna just sit there tryna de-shell a crab all day...",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Yummy, yummy! Oof, I'm so full...",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "Yay, I got to eat something tasty today. I'm so happy! Thank you!",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "It looks yummy, but it's kinda hard work to eat... Hee-hee, how about you help me? Pretty please!",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Birthday',
      audio: '7001',
      text: "♪Happy birthday to you, happy birthday to you, happy birthday dear Traveler, happy birthday to you!♪ You're older than me right? That means you've had way more birthdays than me... I'm sooo jealous!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Mm, new-bomb research complete! Now, let's get outta here before Jean finds out...",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Aw yeah, I improved again! But as Jean says, \"Continuous self-improvement is one's duty.\" She says that means I'm allowed to be a bit happy about it, but not the most happy I've ever been in my whole life about it.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "Thanks for helping me gather so much stuff for my research! If you ever wanna learn how to make a bomb, I can teach you y'know.",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I remember the first time I ever heard an explosion... I wasn't scared at all. Later on, I found out that apparently, that's not \"normal,\" and most people would've been scared. But hey, you're not scared of my bombs right? Tee-hee, I knew it! That's why you're my bestest friend ever!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Jumpy Dumpty go!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Boing, boing, boom!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Pieew.',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Sparks 'n' Splash!",
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Blazing Delight!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Blow them aaaalll up!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Sprint Start: I',
      audio: '700001',
      text: 'Lalala~',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Sprint Start: II',
      audio: '700002',
      text: 'Da-da-da~',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'More treasure, more treasure! Hee-hee...',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Yay, shiny!',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Maybe there's even more buried below...",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'What did you do that for!?',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: II',
      audio: '410002',
      text: "Jeeeean... they're picking on me!",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'I feel kinda woozy...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'I can make a big bang if you want!',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'Are you okay?',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: I',
      audio: '500001',
      text: "Yay, I did it! Oh wait, no I didn't...",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'I wanna go home now...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'It was an accident...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'No fair!',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'That really hurt!',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Klee can help!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Ta-da! Klee is here!',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Yea! Let's go on a big adventure!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "When the patrons of Mondstadt's taverns are asked about the strongest knight of the Knights of Favonius, three names are likely to come up:\\nThe highly reputable Acting Grand Master Jean, Cavalry Captain Kaeya, and the mysterious tycoon, Diluc.\\nHowever, some claim to have witnessed, albeit through bleary, drunken eyes, a knight in red, leveling the entire Stormbearer Mountains.\\nIf one wants to find this mysterious knight, then they need look no further than the solitary confinement cell inside the Knights of Favonius Headquarters.\\nIf the cell is found vacant... then something explosively unfortunate is likely about to take place...\\nKlee is well known for the danger she presents. As an official member of the Knights of Favonius, her strength in combat cannot be underestimated.\\nAs a hyperactive child, meanwhile, her destructive capabilities cannot be overstated.\\nAfter all, while other Mondstadt children her age are still playing with regular toys, Klee's favorite toys are... live explosives.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Three years ago, Klee was entrusted to the Knights of Favonius by her parents, who were famed adventurers.\\nThis was how the fates of Klee and "that boy in white" became intertwined with their "family" in Mondstadt.\\nKlee is curious about everything in the outside world. She has an innocent passion for explosives, and is incredibly enthusiastic in all that she does.\\nUnder the protection of the Knights of Favonius, she is protected from harm and those of ill intent.\\nThis young girl soon forged an unbreakable bond with everyone in the Knights of Favonius.\\nBeing sent to the solitary confinement room by Jean, helping Amber improving Baron Bunny, as well as developing new bombs...\\nThese parts of Klee\'s life are all invaluable treasures to her.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: '"The apple doesn\'t fall far from the tree..."\\nJean sighs to herself as she sits down at her desk, head in hands, faced once again with a stack of damage reports.\\nCarts blasted beyond repair, storage shacks burnt down, forest fires that the knights barely managed to contain...\\nNot to mention the suspiciously high number of deaths from unnatural causes among the fish of Starfell Lake.\\nThere\'s only one potential culprit behind all of this, and she just so happens to be one of their own...\\n"Klee!"\\nFaced with Jean\'s stern glare, the harmless-looking Klee surrenders all her concealed explosives.\\nShe is then escorted to solitary confinement, despite her protests amidst floods of tears.\\nThis occurs about once or twice a week at the Knights of Favonius.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "Of course, Klee always tries to help clean up the messes she's made.\\nHowever, sometimes her reckless personality makes things worse still.\\nFor example, she once wanted to apologize to everyone by making some BBQ fish, but ended up blowing the stove sky-high.\\nThen there was the time she got into a fluster and tried to put the fire out... with wind — which obviously resulted in the whole plain going up in flames.\\nKlee is not a bad kid by nature, it's just that her curious and playful nature always results in her failing to think before she acts.\\nAnd every time she gets into trouble, she guiltily tries to make up for it.\\nThough once Jean lets Klee out of solitary confinement, there's usually no more than a day or two before the sound of explosions return to Mondstadt.\\nThe \"Spark Knight\" always manages to live up to her title in a range of unexpected ways.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Though Klee always ends up causing trouble for the Knights of Favonius and Mondstadt, she isn\'t just some rookie who drags the team down.\\nOn the contrary, her skills with explosives can be quite handy if applied correctly.\\nOnce, Jean was able to defeat a horde of invading hilichurls utilizing Klee\'s special talents alone.\\nHowever, Klee also forever changed the face of Stormbearer Mountains in that same operation due to recklessly placing too many charges...\\nNeedless to say, everyone was more than a little shocked, but at least no one from the Knights of Favonius was injured.\\nSince then, the legend of the "Red Knight of the Stormbearer Mountains" began to circulate around Mondstadt.\\nRumor has it that she is cloaked in red, and clutches the greatest treasure the Knights of Favonius have.\\nHowever, only Klee knows what this "treasure" truly is.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "To Klee, the Knights of Favonius are family, and she can't imagine life without them. Her biggest role model, however, is still her birth mother — the avid adventurer, Alice.\\nA highly renowned adventurer and author of the popular Teyvat Travel Guide, there is nothing this incredible mother cannot do — as far as Klee is concerned, anyway.\\nWhether it's the way she used to guide Klee step-by-step through the techniques for adding gunpowder and selecting fuses, or the encouragement she'd give Klee to express her creativity through ever-bolder and more beautiful fireworks...\\nOr that time she taught her how to identify Starsnatch Cliff's load-bearing points, then place explosive charges accordingly to bring the whole thing down...\\nOr that time they stuck their tongues out at each other awkwardly while being told off by Huffman of the Knights of Favonius...\\nKlee has many treasured memories of her mother.\\nThis was the way things were until her parents left to travel to somewhere dangerous and far away. They entrusted Klee to the care of Albedo and the Knights of Favonius.\\nThough still small, Klee knew she would one day become just like her mother.\\nOne day, her explosives would become something that her mother would be proud of.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: '"Dodoco"',
      title2: null,
      text: 'Dodoco is Klee\'s first friend, and one of her best.\\nA very long time ago, her mother made this doll for her by hand.\\nAlice affixed it to Klee\'s four-leaf clover, and hung on her big backpack.\\nFrom that day forth, Klee and Dodoco became inseparable.\\nHer mother said that this would ensure that Klee would never be lonely and that she would have a friend to confide in even when she was alone.\\nThey would also protect each other in times of danger, just like Amber and Baron Bunny.\\nThis, however, worried the Knights quite a fair bit — considering the other things Alice and her daughter had invented, perhaps this, too, might explode at any time...\\n"Dodoco" is a name Klee picked herself.\\nWhen asked what this name meant, she flushed red for a good long while before replying: "It means... Klee\'s best friend!"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Asking Klee how she obtained a Vision will probably get you nowhere — she doesn\'t know, either.\\nA natural-born pyromaniac, Klee had already been acknowledged by a Vision from a very young age.\\nAccording to Klee herself, she had been creating a bomb that was "even bigger than super big!"\\nThis was her very first solo project, but the results were far from expected—\\nWell, she "only" blew her small workshop sky high, leaving a mountain of smoking ash.\\nBut rather than being disappointed, Klee was pleasantly surprised to see a flaming Vision emerge from those ashes.\\nHow did Klee receive this divine acknowledgment?\\nWas it her talent and passion for explosives, the individualistic nature she got from her mother, or her shining innocence?\\nRegardless, Klee had already obtained such a coveted item at a tender, carefree age.\\nRegardless of what she faces as she grows up, she will never give this "present" up.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
