export const lyneyVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1006',
      text: "This is no mere illusion, tis I, Lyney! The greatest magician in all Teyvat! How are we feeling today? Excited? Surprised? Oh, you're curious how I appeared in front of you like this? Well... Hmm, your eyes are like topaz, precious, pure, and lovely. I like them! I've decided — I'm going to put on a show just for you. Watch carefully now. Blink, and you might miss it!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Distraction',
      audio: '1101',
      text: "This is no time for distractions! Seriously, you have a great magician standing right here... You don't want to miss the best part, do you!?",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Sister',
      audio: '1102',
      text: "I wonder what my dear sister Lynette is doing right now? Missing me to death, I'm sure!",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Seeing is Believing',
      audio: '1103',
      text: 'So long as the audience thinks that "seeing is believing," there\'s no limit to the number of tricks I can pull off!',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "There's no way we'll be able to see the stars tonight in this weather. Unless... I try making the stars appear anyway!",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'After the Rain',
      audio: '1202',
      text: "Great, the weather's clearing up! I wonder if there's someone up there performing magic too...",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Achoo! Phew... I've heard some say that when you sneeze, it means that someone's thinking about you. Is it Lynette, I wonder? Or... is it you?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: "When It's Windy",
      audio: '1204',
      text: 'Whoa, that was close! If this wind blows my hat off, all the props I keep inside it would come tumbling down onto my head.',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'When the Wind Is Blowing',
      audio: '1205',
      text: 'The wind is really picking up... Ah, all my magic cards! Wait! No, no, not that way, come back! Come to Lyney!!!',
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Morning',
      audio: '1001',
      text: "...C'mon, just five more minutes... Huh? Oh! It's you! I thought it was the radiance of the sunlight on my skin that I felt — turns out it was your radiance all along!",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "I'm going to check out some products used for magic tricks later this afternoon. Perhaps they'll spark some inspiration for some new tricks. Want to come along? Come on, don't be shy, you know you want to! You can feed some of my animal assistants I use in my shows — I'm sure you'll get along great!",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Evening',
      audio: '1003',
      text: "Good evening. The Great Magician Lyney will be performing later tonight... but I'm sure you didn't need me to tell you that!",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'Good Night',
      audio: '1004',
      text: 'Good night. If you have trouble falling asleep, I have a few little props used for hypnosis that might help... Or maybe not. Either way, sweet dreams!',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '13': {
      title: 'About Lyney: Sweet Talker',
      audio: '2001',
      text: "I should probably emphasize again that I'm rarely so open with anyone — I guess it's because you're not just anyone.",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Lyney: Partnership',
      audio: '2005',
      text: "*sigh* I'm afraid I'd find myself going into standby mode without Lynette by my side. I mean, I can handle my own business just fine, but it takes some getting used to. I'm sure you can understand. You also have... I mean... always have Paimon with you, after all.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '15': {
      title: 'About Us: Withholding the Truth',
      audio: '2003',
      text: "Wow, you're not beating around the bush! ...Let me put it this way — delicious berries must often grow in areas thick with thorns, otherwise they would be devoured by greedy foxes. This is what we call self-defense! I mean, sure, I don't mind telling some small lies to others at times, but between the two of us, I've never done anything worse than omitting a minor detail here and there, right?",
      tips: '',
      tasks: null,
    },
    '16': {
      title: 'About Us: Principles',
      audio: '2002',
      text: "Magicians generally do not reveal the core secrets behind their tricks, but if you don't mind becoming my apprentice and calling me \"Master Lyney,\" then that would be different. I'm curious how much of it you'd understand, and how long you'd last, hehe.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "If a magician were to go onstage with their Vision in hand, people might suspect the authenticity of their tricks, so I habitually take it off before performing. But since you're interested, why don't you help me hold on to it while I perform? Just be sure to keep an eye on it, though — or it might just sneak its way back to me!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share',
      audio: '3002',
      text: "Magic isn't just a performance art, it's also a way of thinking. Many things in this world seem simple at first glance but play host to all sorts of secrets if you look deeper.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things',
      audio: '3003',
      text: "Cats can use their ears to express their feelings. If they flatten them backwards, it indicates fear or caution, and if their ears are perked up and occasionally face forward, that usually means they're happy. Constant swiveling indicates that they are vigilantly assessing their surroundings... How do I know this? Experience and observation!",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About "Father": Family',
      audio: '4001',
      text: '"Father" gave us a family, raised us, and told each of us what we should work towards. In turn, what I can do is very simple... Remain loyal, and protect our home.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About "Father": King',
      audio: '4002',
      text: 'Ours is a kingdom consisting only of children, and "Father" is our king. No king rules forever, of course, and I know that one day I will be chosen as "Father\'s" successor... But that also terrifies me... Please don\'t mention this to anyone, especially my sister and Freminet.',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '22': {
      title: 'About Lynette: Modes',
      audio: '4003',
      text: "You think my sister doesn't talk much? Oh, she's probably just not in the right mode. Next time, start by saying \"Activate Chat Mode\" to her. If you're lucky, she might have a great deal of things to say to you. Hmm, and if you're not lucky...? Well, she'll just stare for a while, but hey, at least you'll get to see a different side of her!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Lynette: Twins',
      audio: '4004',
      text: "My sister and I have always been inseparable. There's no hardship we can't overcome as long as we're together, and similarly, we share all our joys with each other. There's nothing in the world I treasure more than my family, so I know what it must be like for you... And if I find out anything at all that might help you, I'll be sure to let you know.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Freminet',
      audio: '4005',
      text: "My naive little brother still believes in fairy tales. I envy him, really. Uh, just to be clear though, he didn't actually tell me that. I just happened to see what he keeps in his secret drawer once... Really, it was an accident! So please don't tell him, or he'll get mad at me for sure.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Neuvillette',
      audio: '4006',
      text: "Monsieur Neuvillette rarely appears in public, almost as if he's intentionally trying to put some distance between himself and the people. At first, I thought it might be just me, but my ever-observant sister noticed it too, so I suppose that must really be the case.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Furina',
      audio: '4007',
      text: 'The Hydro Archon, Lady Furina, is very unpredictable, and her manner of speech can be quite provocative, almost as if she sees talking itself like some sort of performance. The people of Fontaine have a particular soft spot for excitement and drama, which is why many hold her in high esteem.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Chiori',
      audio: '4008',
      text: "Flattery won't get you anywhere with her. She'll only give those who can truly appreciate her art a second look. How does she see me, you ask? Come on now, that hurts! Not only am I a connoisseur of the arts, but honest about it too, as I am in all my dealings!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Navia',
      audio: '4009',
      text: "I didn't think that she'd be willing to help strangers like us. If it hadn't been for all of you, Lynette and I wouldn't have been acquitted... Thank you so much. I'll have to wait for a lovely, sunny day to invite everyone to Café Lutece for the most wonderful afternoon tea!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '29': {
      title: 'About Charlotte',
      audio: '4010',
      text: "Charlotte has been trying to get me to agree to an interview ever since we met... Ugh, it feels like she's already asked twenty times now. She has a good nose for finding news, and she's the persistent type, too. But to be honest, I have no desire to find myself in the spotlight of one of her breaking news stories, and so I've found all sorts of reasons to decline each time.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishMainQuest',
          questList: [
            {
              id: 4002,
              chapterId: 1402,
              chapterTitle: 'As Light Rain Falls Without Reason',
            },
          ],
        },
      ],
    },
    '30': {
      title: 'About Clorinde',
      audio: '4011',
      text: "Clorinde's quite famous as a Champion Duelist. But from what I've read in the papers, she seems to have gotten into a bit of a pickle. The media's been all over her story, and she's... Well, she's the type that definitely doesn't enjoy that kind of attention.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Emilie',
      audio: '4012',
      text: "Have you ever gotten a whiff of the perfumes she makes? I quite liked them and was thinking to buy myself a bottle... But Lynette's tail indicated that she didn't share my opinion, so that was the end of that!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About Lyney: I',
      audio: '5001',
      text: "It seems we're both keenly interested in each other. Well, know that the honor is mine! Haha, relax. I couldn't ever tell lies to your mesmerizing eyes — not even if I tried!",
      tips: '',
      tasks: null,
    },
    '33': {
      title: 'More About Lyney: II',
      audio: '5002',
      text: "Of course, there's no way to ensure that you'll never slip up when performing magic tricks. The way I see it, the point is not to perform perfectly, but to stay calm at all times and adapt as needed. Even if some small flaws occur, you just need to make the audience believe that it's all part of the show, and you'll still deliver an entertaining and unforgettable performance!",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '34': {
      title: 'More About Lyney: III',
      audio: '5003',
      text: "As orphans without parents to shelter us, Lynette and I were forced to roam the streets since childhood, so we've been through a lot. But those experiences have also made us who we are today. We're doing alright these days. I have a hat full of hopes and dreams... Heh, and a family, and audience, hoping that I don't let them down!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '35': {
      title: 'More About Lyney: IV',
      audio: '5004',
      text: "Haha, so even now you still don't completely trust me, huh? You're a vigilant one — not that that's a bad thing. I'll never need to worry about you getting duped by someone else. But on the other hand, since you've taken it upon yourself to watch my every move, you'd better be careful when you blink... Who knows, I might just tell a huge, terrible lie while you're not paying attention! You'd be in a real pickle then, wouldn't you?",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '36': {
      title: 'More About Lyney: V',
      audio: '5005',
      text: 'Actually, the real me is nowhere near as outgoing or chatty as I appear. More often than not, I only work my verbal "magic" as a means of getting closer to people. Sometimes I think people would feel sorry for the real me. Do you? *sigh* Or do you find my little games absurd?',
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '37': {
      title: "Lyney's Hobbies",
      audio: '6001',
      text: "Hey, what do we have here? Ah, a cute, little white rabbit — you like it? Curious about when it got here? You should be! Hehe, the look of amazement on our audience's face is what we magicians love the most.",
      tips: '',
      tasks: null,
    },
    '38': {
      title: "Lyney's Troubles: It's All a Disguise",
      audio: '6012',
      text: 'Ah, what to do, what to do? The thing that troubles me is... the fact that you can even think of troubling things when you have such a great magician like myself standing right in front of you.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: "Lyney's Troubles: Doves",
      audio: '6011',
      text: "In the past, I would let the doves I raised fly freely, and they would always return to me. But there was once when a few didn't return, and by the time we tracked them down, they'd been turned into dove pie. Even now I still don't know how to give them both freedom and safety.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: '6003',
      text: "See this fishbowl? Come, put your hand inside it. Filled with just ordinary water, right? Are you sure? Then let's begin! See this cloth? I'm going to cover the bowl with it and... Well, what do you know? There's a fish in there now! How was that? Maybe this fun little performance could earn me one of your very own fish dishes?",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Our performances require that Lynette and I have matching physiques, so we have to avoid eating any oily food. Now, that's not a huge problem for me, but it can be tough for my sister — the fried fish they sell on the streets smells amazing, after all...",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "It's quite an honor to enjoy such wonderful food made by you.",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "My, this is delicious! You're quite the cook. Thanks for the treat.",
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Would you like to see a magic trick? Now, let me place this ordinary cloth on top of the dish. Count down with me — three, two, one! Tada! Where'd the food go?",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: '7001',
      text: "I have a feather here, just an ordinary feather... Go ahead, you can hold it and see for yourself. Ready? And... boom! It was a party popper all along. Happy Birthday! See this? I caught one of the paper streamers floating down. Now, make a wish and picture a birthday gift in your mind's eye as I light it. Three... two... one... Great! Verrry good, I know exactly what you were thinking now. The last step, put your hand inside my hat... Well? Is it the gift you wanted?",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Oho, and here I thought you'd ask me to perform some magic with these materials!",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'Would you be more shocked if nothing changed about me at all?',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Nothing could make me happier than having your trust.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: 'Doing all this for me... Are you trying to steal this magician\'s heart, by any chance? Well, in that case, congratulations, my dear apprentice — or should I say, "companion." For you have succeeded!',
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Step right up!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'And... voila!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Now, disappear!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Here comes the finale!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "Let's get this show on the road!",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'A round of applause!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "And now I'll make it all disappear... Hehe, just kidding~",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: "Guess this'll go into my magic pocket!",
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'I wonder if this chest is some kind of trick...',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: "Magic can't cheat death, you know!",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Clever trick...',
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: "It'll be alright.",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Why don't you let me take the stage!",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Your timing's off!",
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Lynette...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: "My show... mustn't fail...",
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Quick... drop the curtains...',
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: "I'm fine.",
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: I',
      audio: '910002',
      text: 'Stay calm, stay calm...',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "Ah, we'll be a traveling magic troupe.",
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Prepare to be amazed.',
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "It's an honor to be here.",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "The people of Fontaine love their tales of mystery. The intricate case setups and unexpected twists and turns are captivating for all.\\nMagic recreates this experience under the converging spotlights. For the price of a ticket and some of your free time, you can embark on a wondrous journey amidst thunderous applause and astounded cries.\\nIf you were to ask around as to which of Fontaine's \"guides\" is best at setting up such fantastical tours, most fans will tell you that it is Lyney.\\nSuave, romantic, and talented, he performs miracle after miracle with a casual air.\\nIn this industry, one needs only a stable of staple tricks to ensure a renowned reputation and comfortable life.\\nHowever, Lyney's shows always feature some new trick. Some say that he was born into poverty, and the resultant burning hunger for fame and fortune drives his boundless desire to create.\\nIn truth, he simply pursues novelty in his capacity as a performer — indeed, he feels that if he cannot put his whole heart into the show, his deep desire to perform cannot be fully satiated.\\nThis is why, despite the applause rising to a fever pitch and beyond, he will rarely satisfy the crowd's calls for a reprise of his most well-known tricks. Some devoted fans consider this to be a bit of a shame...\\n...And for them, such regret will only continue to increase each time they purchase a ticket and go in to watch his show.",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: "While Lyney first began his journey in magic to fill his stomach, he has continued to perfect his art even after becoming a person of some renown in Fontaine.\\nMagic, after all, has been his benefactor. Not only has it allowed him and his sister to survive, but it has also allowed them to gain the \"acknowledgment\" that most children, growing up in a loving home, would have received from their parents.\\nEven from an early age, performance was something closely tied to Lyney's life. Each time he would go on stage, Lyney would have the audience whooping and clapping. And yet, he did not lose himself in their adulation — if anything, it often troubled him.\\nIf audiences were simply drawn to the spectacle of magic, then who was to say that they wouldn't abandon Lyney's stage as soon as they caught wind of a more enthralling show in town?\\nIn other words, just as an audience would be attracted by petals and cards, they would also be pulled away by grander fireworks and crackling gun salutes. What else did magicians have up their sleeves to capture the hearts of their audience, beyond enticing them with ever more grandiose impressions of shock and awe?\\nIn all of Lyney's performances afterward, audiences would begin to notice a change — Lyney would add many segments between performances in which he would interact with them.\\nIndeed, this magician seemed without any airs, sharing various fascinating anecdotes about his life, not even minding if the audience should try to guess at the secret behind his tricks.\\nOf course, the sharper wits amongst them would notice that Lyney's tales were not truth, but instead a way to build up the atmosphere, a bedding laid for a greater magic trick to land upon.\\nYet no one would quibble about these white lies. After all, truth and falsehoods were already inextricable in many parts of the performance — why, even the magician himself could be said to have become a part of the magic.\\nThus does Lyney sometimes appear near and dear, and other times just out of the reach of his audience, balancing human affinity and magical mystery perfectly in the palm of his hand, his smile leaving the audiences' imaginations free to run wild.\\nNo matter how rich or poor, sad or glad the audience member, imagination is the great equalizer, carrying the charm of magic to all.\\nThus did the mystery and elegance of this magician spread far and wide, with people even opining that his skill at creating an atmosphere is itself as exquisite as magic.\\n\"Is that so? Well, I'm just trying to invite everyone to take a brief break from reality, that's all.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Lyney's new home was the Hotel Bouffes d'ete, located in a corner of the Court of Fontaine.\\nThe place was home to many orphans who shared similar experiences with him and his sister. The people here helped each other like a family would, greeting the fallout and consequences of those tragic years together.\\nBut the siblings, even with a recommendation from the manager of the Hotel, did not find it all that easy to fit in, nor was it easy for the children there to immediately accept these new \"outsiders.\"\\nAnd in this environment, oppressive in its gloom, the water pumping equipment broke while Lynette was using it, right before everyone's eyes, deepening the distrust to the extreme.\\nLyney could only step up and take responsibility, agreeing to fix the equipment so as not to affect everyone's daily lives.\\nIn truth, he did not know all that much about repair work, but given Lynette's propensity for damaging various small devices, he had long gotten used to following his intuition to do some fixes here and there.\\nUnfortunately, he underestimated the complexity of the pumping equipment and difficulty of fixing it. While he succeeded in restoring it to normal operations, he remained at a complete loss as to whether he had solved the root problem or not, he could not tell.\\nBut just as he was at his wit's end, a seemingly reticent young fellow stepped forth, examined, and restored the facilities, even expressing his apologies.\\nAs it turned out, he was the one in charge of maintenance at the Hotel, and as he saw it, Lynette had been the unfortunate victim of his failure to detect and replace the aging components in the system in a timely manner.\\nLyney, for his part, was far more impressed by the young fellow's skills than any talk of responsibility. He wanted to learn from the youth — if nothing else, this would make helping Lynette all the easier.\\nThe youth was, for his part, no good at refusing, and thus did Lyney become his assistant in the Hotel's small workroom — and over time, he and this Freminet would become friends.\\nLyney would prove unselfish in spending time on other Hotel residents, whether it be Freminet or others, but he would keep them company in comforting silence rather than ask them about their experiences.\\nIn this he was guided by Lynette's succinct life advice: \"No one needs self-satisfied concern.\"\\nIn time, the residents became more willing to share some of their pasts with him, and Lyney would thus become better able to help them with their issues.\\nFreminet was somewhat perplexed by this, believing that Lyney, who was slowly becoming the core around which the Hotel spun, did not need to go this far.\\nLyney joked that he had helped Freminet when they first met because he knew that his sister would cause further machine-related troubles down the line, and he was uncomfortable with that.\\nBut at this point, there was no fooling Freminet with such words. Under his attentive gaze, Lyney could only tell him the truth.\\n\"Because Lynette's my one and only family, I've learned from her how one should treat all members of their family.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'On the Hotel Bouffes d\'ete\'s Founding Day, all the children were abustle, draping festive colors all over the place.\\nTo the residents, outside festivals and events were cold and emotionless things, foreign elements in their lives, and only this dwelling could bring them true warmth.\\nEveryone worked in concert to execute Lyney\'s plan. Lynette had purchased large amounts of festive ornaments, and together with the other children, she strung up colored streamers and hung handwritten festive greetings.\\nFreminet was ensuring that the magical props would operate properly — Lyney had faith in his craftsmanship, so much so that Freminet was completely entrusted with all the magic props this time.\\nLyney himself was the busiest of all — not only did he have to ascertain everyone\'s progress, but he was also laying the final groundwork for a grand, unique magic trick in secret.\\nAnd thus was the banquet successfully held with everyone\'s support. The children danced to the joyous music playing from the grand hall\'s phonograph and enjoyed delicious food — this was the birthday of no one in particular, but this was the day they all felt they had gained new lives.\\nThe finale, of course, was Lyney, Lynette, and Freminet\'s Founding Day magic show. The magic box was at the center of the room, and all waited with bated breath.\\nTo preserve the secret behind the magic trick, even Lynette and Freminet knew not what was within. But as the room darkened and all eyes turned to Lyney, standing as he was in front of the box, even the highly-experienced magician showed some rare signs of trepidation.\\n"Now, you might consider the following words an exaggeration, but the "present" I am about to present to you all is, without doubt, the most important one we have received in our lives."\\nThe paper firecrackers burst, and the once-empty box suddenly opened by itself. The crowd cheered, amazed — then fell suddenly into stunned silence.\\nWhat stood onstage was no present — nay, this was the Hotel\'s manager, its owner, and their "Father."\\nHer image was one of unsmiling dignity, and thus, though she did not come by often, no one dared to horse around whenever she was around.\\nSurely, Lyney had gone completely mad to have her make her appearance in such a frivolous way.\\nYet, upon seeing the crowd\'s reaction, "Father" did not snap at anyone, opining merely that Lyney had kept this secret perfectly, just as a magic show should, declaring it worthy of praise.\\nThat night, the children and their "Father" delighted in the various desserts together, and she personally sliced a serving of cake for each of them, which she herself enjoyed some of as well.\\nPerhaps the most amazing aspect of Lyney\'s Founding Day magic show was its ability to have even "Father" lay down her heavy burden and enjoy a brief moment of familial love.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Magic and secrets piled up at Lyney\'s feet, growing ever taller like a tower. Gazing down from the top at the people as they passed by in the world below, Lyney knew there was no going back.\\nBoth the dazzling sleights of hand and the missions he would come to receive from Hotel Bouffes d\'ete had made a habitual liar out of him.\\nAnd while lies could sometimes be useful for seizing an advantage, they were more often employed to keep more people from being dragged into trouble.\\nLyney knew very well that once trust had collapsed, the scales of judgment would no longer remain impartial, and even noble goals would become twisted and thought of as evil.\\nAs such, not revealing more than was absolutely necessary was prudent when working with others. More often than not, this makes things go more smoothly, with everyone getting the results they want.\\nBut lies will not simply scatter on the wind, and Lyney must maintain this illusion with utmost care, all the while keeping his distance from those affected.\\nAs so the tower extended towards the skies, until there would be no one to take his hand if he reached out, and even their visages blurred in his eyes.\\nFalsehood was Lyney\'s constant and only companion on the path that he walked, and this road was long and lonely — this he was always clear-minded about.\\nEveryone knew the brilliant "Great Magician Lyney," but they loved only the mystery, the romance, the unattainable nature. They knew no love for the heart that lay deeper within.\\nHe felt he had no right to pour out his mind to others, and yet he must carry on with gritted teeth, for the price of a fall from such heights was more than he could bear.\\nHaving played too many parts, even Lyney would sometimes find himself questioning who "he" really was.\\nHis dreams often took him back to the tower, where his resting place at the pinnacle vantage would grow smaller and smaller, and with the fog of death they called "betrayal" extending all around, there was nowhere for him to go.\\nBut just before he could plummet, a hand grabbed onto him — and from it, he felt a familiar warmth that drew his soul back into his body, steadying "him" within himself once more.\\n"Thank you, Lynette..."\\nThe awakening youth mumbled to himself.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "While Hotel Bouffes d'ete's operations in Fontaine work toward a just cause, its methods can often be radical. Only the influence of \"Father\" and her control over the inner workings of the Court of Fontaine prevent any serious incidents from occurring.\\nThere was once an official funded by Lyney who served in the Maison Gardiennage. This person provided both intel in support of the Hotel's operations and scrubbed clean the effects of some of the Hotel's clandestine actions.\\nThese were actions that came with no small risk, but the official always performed them well, for he believed that the Fontaine of the present day needed someone like \"Father\" who could bypass the many layers of laws and regulations and take direct action.\\nLyney once joked to him: \"I'll be there if you ever need help, and if you're in danger, I'll come to rescue you... Well, don't expect too much of that last bit. Just stay on guard, alright?\"\\nThe official knew that this was Lyney's way of expressing concern, of course. Yet even words spoken in jest could prove prophetic later, and so they did — this official's deeds were eventually discovered, and on the brink of capture, he used an emergency communication device to send a message to Lyney.\\nUpon discovering the device, the Gardes who arrived at the scene mocked the official's naivete, claiming that the signal sent merely informed his compatriots to save themselves — no one would be stupid enough to try to save him.\\nThe official's reply was also quite simple — even such an ending would have been fine for him, for he did not believe that his prior cooperation was the wrong decision.\\nBut just as the Gardes were about to arrest the official, thick smoke began billowing forth from dispensers pre-planted nearby, and the official caught sight of a brilliant blaze—\\nThe next moment, he was in the drink in the Fleuve Cendre, and was rescued by Freminet.\\nIt was said that the Gardes spent a great deal of time chasing after the skyborne flame-trail, believing that the criminal must have used some flying machine to flee the scene, only to discover later naught but wood dressed in clothes, affixed to a glider.\\nIn truth, Lyney had earlier used this device to draw the Gardes' attention away before getting the official out of his predicament.\\nThe official admitted that he had not had high hopes when pressing the device. Magicians were untrustworthy, after all — but still, he had chosen to gamble on that tiny chance.\\n\"Haha. Well, it is indeed a gamble to place your trust in others.\"\\n\"But don't worry. Magicians might be full of hot air, but we will never betray the expectations of our audience.\"",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Rosseland',
      title2: null,
      text: "There is a special entity amongst the cats adopted by Lyney and Lynette, and its name is \"Rosseland.\"\\nEvery cat in the Hotel has its own territory, but Rosseland has a special affinity for Lyney's hat.\\nA hat is a magician's most important prop, and each time Lyney must use it, he must first chase Rosseland out — a difficult affair when its displeased meows in response are so heartrending, especially to siblings like Lyney and Lynette, who themselves once struggled to find a home.\\nThus the siblings began their search for a replacement, only to be met by refusal each time, no matter how lovely the new home — indeed, Rosseland would not even give them a second glance.\\nLyney even specially commissioned an identical hat, thinking that this might put an end to the cat's choosiness, only for Rosseland to lay claim that new hat also, becoming aggrieved no matter which was whisked away.\\nBut this was no feline tyranny. Indeed, Rosseland's requests were not terribly excessive. After much thought, Lyney eventually came up with a solution — to incorporate the cat into his magic shows.\\nHe and Lynette constructed a little puppet inside the hat that would normally serve as Rosseland's cushion. During performances, Rosseland would burrow inside the puppet, causing it to jink this way and that in a mischievous and adorable manner.\\nAnd as it turned out, Rosseland was not at all shy — indeed, it greatly enjoyed its new job. Perhaps the spotlight brought it much enjoyment indeed, for it would never prove quite so predisposed to exclusive ownership again, even when it had to temporarily leave its nest when off-stage.\\nDuring one of his shows, Lyney once made a rare error, having left a card he needed to produce on-stage backstage.\\nWith all eyes on him, he had mere seconds to think of a way to save the situation while maintaining his easy-going demeanor.\\nBut to his surprise, there was an unexpected weight in his hovering hat — it should have been empty, but Rosseland had somehow found its way inside.\\nOut came the puppet, and out with it came the card Lyney had needed, to the instantaneous applause of all. Lyney heaved a sigh of relief, but he was also quite shocked, in truth.\\nSome thought was put into this matter — but Lyney could only conclude that Rosseland had, influenced by the twins as it was, also mastered the art of the magical performance somehow.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'After Lynette gained the favor of the gods, the missions she had to undertake grew more dangerous and difficult.\\nOnly Vision-wielders like Lynette could fulfill the most dangerous missions while remaining completely anonymous, and the twins began to operate separately more often as a result.\\nLyney found himself unable to adapt to this. Not only had the siblings been together since childhood, but he knew that he was not the only one who felt disturbed by this split.\\nHe still desired to be beside her, lending her all the help he could — this was his non-negotiable desire.\\nKnowing his desire for power was no longer pure, Lyney concluded that he had become undeserving of divine favor. Yet he still desired a means to bridge the vast gulf in strength between him and his sister, which he did not possess. Unless...\\nTo this end, he solemnly sought out "Father," expressing his belief that he needed the mysterious and perilous might of a Delusion to operate alongside his sister.\\n"Father" was silent for a long while, till at last two slanted crosses pinned him in place with a wrath rarely shown to the children of the Hotel, her gaze seeming to pierce his very soul.\\n"And would Lynette want you to do this?"\\nHer simple yet powerful question cut through the strings that bound his heart, and in a daze, his sister\'s words once more reverberated in his ears.\\n"No one needs self-satisfied concern."\\nLyney did not need to ask his sister to know that she would never accept his desire to stay by her side with the use of a Delusion. It was only then that he realized the absurdity of his wish.\\n"Father" stood up and left, but not before reminding him that this was not the first time he had lacked power, but that he had found an answer before.\\nLyney would lock himself in his room, trying to digest the reasoning behind the words "Father" had left him with. When he and his sister had been out on the streets, the answer he had found then had been "magic." What, then, would the answer be now?\\nLyney found the dossiers for all the missions Lynette had taken up during this period, carefully analyzing the process of each one and modeling his sister\'s every action.\\nWas it really necessary to pass through this dangerous valley to get close to a target?\\nWas it really a must to leap into such a swift river to flee the scene?\\nNo, this was just the Vision\'s light covering her.\\nThus did Lyney start to make comprehensive plans for his sister\'s missions, using his understanding of her to design the most suitable routes, make the most practical tools, and choose the best rendezvous points.\\nThe trust between them did not change. The look in Lynette\'s eyes when she left was no longer so strained, and they often embraced heartily and happily when meeting at the rendezvous point.\\nThe pure desire to protect one\'s family would not be moved, gods\' favor or no.\\nBut even the best laid plans of mice and men may go awry. After conducting dozens of successful missions, the children of the Hotel were caught up in a betrayal, and as a result, Lynette\'s movements were exposed.\\nBefore the siblings was a towering cliff, just like the night when Lynette had gained her Vision — but this time, it was Lyney\'s turn to reverse their fortunes in a moment of crisis.\\nHe opened his emergency paraglider, and grabbing her, threw himself off the edge. But their pursuers followed, raining gunfire down on them.\\nLyney twisted this way and that, avoiding many a shot, but still the glider was punctured in several spots. Unable to maintain balance, they began to plummet downward towards the embrace of the ground below.\\nStill, Lyney grit his teeth and refused to despair — should fate itself conspire to refute the answer he had come up with to protect his family, he would defy it to the end.\\nTheir pursuers began to snicker, knowing that a fall at such speeds would be fatal — only to have a flame light up the skies, pushing the stricken glider toward a fast-flowing river nearby.\\nThe power of Pyro changed the direction of their fall, while Anemo defended them from harm — and thus did the twin lights intertwine and spread under the moonlight, fading slowly like the applause that fills the stage during a curtain call.\\nLyney did not guess at the meaning of the shining Vision he saw in his hand. The answer was, after all, no longer important.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
