export const thomaVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "It's good to meet you at last, Traveler. I've been hearing about you for a long time now. I'm your new buddy, Thoma — as long as that's okay with you, of course!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: "Chat: Thoma's Treat",
      audio: '1101',
      text: 'Hey... how about we go for a nice meal some time? My treat, of course.',
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Concern',
      audio: '1102',
      text: "I feel like there's something I forgot to do... hmm, I tidied the courtyard, put the tea on... Eh, it's probably just my mind playing tricks on me.",
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Mora',
      audio: '1103',
      text: "I really did spend a lot recently, only 10 Mora left... Still, 10 Mora's better than no Mora!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "Where'd this rain come from? Are you gonna be okay? Here, I'll lend you my coat...",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "You don't wanna be out in open country in this kind of weather. You'll get struck by lightning for sure.",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: "Don't run on the ice... 'cause if you fall down, I won't help you up, you gotta learn somehow.",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Sun Is Out',
      audio: '1204',
      text: "Lovely weather we're having! Will you join me for a walk?",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Morning! If you're free, why not come with me to the market? The vegetables are freshest earlier in the day.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "On the lunch menu today, we have Sakura Tempura and Tricolor Dango! Here, there's some for you, some for Paimon, and I also put some aside for milady and the man of the clan himself. Ah, wait, I forgot someone... There's none for me...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Come quick, we gotta get down to the market — they slash the prices on fish around this time of day. Oh, and if you find something that you just can't do without, I'll help you haggle the price down.",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Okay, good night. You had a busy day today, you should get some rest, too. Don't stay up too late.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Thoma: Housekeeper',
      audio: '2001',
      text: "It was never Ayaka or Ayato's intention to make me the housekeeper, I volunteered. I like this kind of work. Putting everything in order gives me a great sense of achievement, and based on everyone's reactions... Yeah, I think I do a pretty good job.",
      tips: '',
      tasks: null,
    },
    '13': {
      title: 'About Thoma: Meaning',
      audio: '2005',
      text: "For me, housework is about keeping a space clean and tidy, so that everyone who lives there has a smile on their face. And now... it looks like I'm responsible for another smile. I'll do my best to deliver!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '14': {
      title: 'About Us: Eating Alone',
      audio: '2003',
      text: "Hey, how come you're eating here all alone? ...Uh, is it okay if I join you? Or did you just want some space?",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Oath',
      audio: '2002',
      text: "If you hadn't put yourself out there during the Vision Hunt Ceremony and taken on the Raiden Shogun all by yourself, I would've lost my Vision, and with it all my aspirations. I've been thinking about this a lot, and it seems like there's only one way I could ever properly repay you... \\nI, Thoma, give to you my weapon and my loyalty, and I promise to fight for you, no matter what.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '16': {
      title: 'About the Vision',
      audio: '3001',
      text: "Those that receive Visions should look after them. I certainly don't plan on losing mine.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share',
      audio: '3002',
      text: "I've gotten to know all kinds of people over the years, and I'd say that Inazumans are more particular about etiquette than Mondstadters. If you make sure you're always polite to people, it's much easier to get things done.",
      tips: '',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things: Tanuki',
      audio: '3003',
      text: "I've always wanted to see a tanuki shapeshifting. They say it can change into all kinds of things, and that it likes to play pranks on passersby. It's a creature with a sense of humor, that's for sure.",
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'Interesting Things: Animals',
      audio: '3004',
      text: "Are you an animal person, too? If you are, let me take you to the outskirts some time, it's great. I just need to give a whistle, and all these puppies and kittens will come out of nowhere and start strutting around your ankles, clamoring for your affection. Haha, just imagining it is already brightening my day.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'About Yae Miko',
      audio: '4001',
      text: "Lady Miko? Wh—What about her? *sigh* Every time Miss Kamisato sends me out to deliver messages, my least-favorite destination is the Grand Narukami Shrine... Oh! N—Not because Lady Miko scares the bejeebers out of me, it's, uh... respect. Yes! She strikes respect deep into my heart, ahahahaha...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About the Raiden Shogun: Comparison',
      audio: '4002',
      text: 'In my homeland of Mondstadt, almost everyone has great reverence for the Anemo Archon, Barbatos. But people in Inazuma feel a little differently toward the Shogun. How can I put this... They feel love, respect, gratitude... but also fear.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About the Raiden Shogun: The Unknown',
      audio: '4003',
      text: "Honestly, I don't harbor any resentment toward the Shogun. Yes, she almost took my Vision away, but ultimately that's just because of her unique perspective. Everyone has their own perspective, there's nothing strange about that.\\nThe only thing I don't understand is her goal in doing so. What does she imagine eternity really looks like for Inazuma? And why is sacrificing her people's aspirations so necessary to achieve it? I can neither understand nor agree with her approach.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '23': {
      title: 'About Beidou',
      audio: '4004',
      text: "The captain of The Crux — a formidable woman indeed. She once promised to take me out onto the open ocean to get a look at the thunderstorm that seals off Inazuma from the outside world. It's a shame that to this day, I've never had the chance to take her up on the offer...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '24': {
      title: 'About Kamisato Ayato',
      audio: '4005',
      text: "As head of the Kamisato Clan, he's in a tough position. With all the political upheaval, he has to contend with public disquiet on one hand and a bunch of self-serving, degenerate public officials on the other. It's best not to dwell on it. All I can do is make sure to look out for him when he's at home.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Kamisato Ayaka',
      audio: '4006',
      text: "Milady is in all respects a well-rounded person: erudite, compassionate, well-mannered, and elegant... The one thing she could do better is to speak her mind more. In fact, watch out for this the next time you're talking to her — sometimes, she looks like she's about to say something, but then she holds back. If that happens, keep asking her opinion, see if you can encourage her to open up a little.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: [
        {
          type: 'finishSubQuest',
          questList: [
            {
              id: 2009,
              questTitle: 'In the Name of the Resistance',
              chapterId: 1203,
              chapterTitle: 'Stillness, the Sublimation of Shadow',
            },
          ],
        },
      ],
    },
    '26': {
      title: 'About Yoimiya',
      audio: '4007',
      text: "Of Naganohara Fireworks fame? She's so easy to get along with. Super straightforward, just says whatever she thinks. Oh, and Naganohara fireworks are just incredible, you should take every chance you get to see them in action. Ah, on that note — here, have a coupon!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Sayu',
      audio: '4008',
      text: "Ah Sayu, stubborn Sayu. I've asked her countless times to teach me ninjutsu, but she always refuses. She even goes out of her way to avoid me now... I'm just a student looking for a teacher, am I really that out of line?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Kujou Sara',
      audio: '4009',
      text: "The Tenryou Commission General... Mm... Make sure to be extra careful if you have any dealings with her. She has a lot of power in her hands, and she's not very open to persuasion. Smiling and batting your eyelids certainly won't get you anywhere with her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Arataki Itto',
      audio: '4010',
      text: "Hmm... Word on the street is that he's quite a character — apparently, he even has youkai heritage. Have you met him? If you two are close, maybe you could introduce me sometime. It's good to make friends from all walks of life... youkai included!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'About Shikanoin Heizou',
      audio: '4011',
      text: "Ho, that guy is a detective for the Tenryou Commission. He seems to have his own way of doing things — not the easiest person to get along with. Also... Any situation that involves a detective is probably not one that's going to end well. I think I'll keep on giving him a wide berth.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '31': {
      title: 'About Jean',
      audio: '4012',
      text: 'Oh, so Jean from the Gunnhildr Clan is the Master of the Knights of Favonius now? She definitely deserves it, she\'s known all over for her impeccable conduct... Oh, just the "Acting" Grand Master? Haha, well, someone of her standing won\'t care about titles.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'About Eula',
      audio: '4013',
      text: "You've had a run-in with Eula Lawrence before, huh? All I know is that their whole family are about the worst-tempered people you could ever meet. You're better off steering clear of them if you can help it. Ah, now I'm in a Mondstadt mood again... The memories.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About Thoma: I',
      audio: '5001',
      text: "Anything I can lend a hand with? If something needs doing around the house or you're having some interpersonal strife, just say the word. Hmm? A conversation... I see, I see. That's a little different from what I'm used to, but I'm all for it.",
      tips: '',
      tasks: null,
    },
    '34': {
      title: 'More About Thoma: II',
      audio: '5002',
      text: "I'm not from Inazuma originally — I think I've told you that before, right? I took a boat all the way here from Mondstadt, found I liked the place, and was also lucky enough to meet the wonderful Kamisato siblings, so I just ended up staying.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '35': {
      title: 'More About Thoma: III',
      audio: '5003',
      text: "I get homesick once in a while, too, so I completely relate to all the international merchants on Ritou. I try to look out for them as much as I can. The difference between us is that they see themselves as just passing by, and have no intention of trying to integrate here. And because that's how they think, it becomes their reality. The majority of Inazumans will never see them as anything more than outsiders.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '36': {
      title: 'More About Thoma: IV',
      audio: '5004',
      text: "For some of the more conservatively minded people in Inazuma, the idea of an outlander working as a retainer for one of the Commissions is unthinkable. So there was a time when I was not that welcome here. I'm pretty sure I'd have been deported a long time ago without a couple of Kamisatos fighting my corner. I couldn't let the clan down after they'd been so kind to me, so I put in a lot of honest work, and eventually, everyone was finally able to accept me.",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '37': {
      title: 'More About Thoma: V',
      audio: '5005',
      text: "I'm not sure if I should get into this, but... Ah, hopefully you won't mind. I went through a period where I really just wanted to go home — Mondstadt is my homeland, after all. But I was torn... It wouldn't be easy to leave Inazuma behind, either. I mean, just look how good the people here have been to me. The Kamisato Clan always has a room for me, and there are people I've met here that are like family. So, I went back and forth over it, and ultimately decided I'd stay in Inazuma. When I'm missing Mondstadt... I can just chat with you. You don't mind my rambling, do you?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '38': {
      title: "Thoma's Hobbies",
      audio: '6001',
      text: "I've been really getting into stories about the unnatural recently. Especially ones about shapeshifting youkai — they're so fascinating. Before that, I was really into ninjutsu for a while, and before that... Hmm? You think I'm not dedicated enough? N—No! It's not like that, you got me all wrong!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: "Thoma's Troubles",
      audio: '6002',
      text: "I'm in a real pickle here. The chief is hosting a banquet for his friends tonight, and he says he wants me to splurge a little by cooking some Butter Crab. The only problem is that for the last two days, I haven't been able to buy crab anywhere! So, what, am I gonna have to dive into the ocean and grab them myself?",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Without a doubt, my favorite food is Rice Cake Soup. I like cooking up a big, delicious potful for everyone to share. It's a recipe for a good time.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "As far as food is concerned, I'm fine with anything. If we're counting beverages, though... I'm not very good with alcohol. Don't laugh, and before you say it — yes, I've wondered what this says about my identity as a Mondstadter. But, y'know... too much alcohol is bad for you, anyway. So not drinking is a good thing.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Delicious! Could I get another bowl of rice?',
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'Um, are you free right now? Would you mind sharing some of your cooking tips with me?',
      tips: '',
      tasks: null,
    },
    '44': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "I don't think I've ever tasted anything like this... Oh, it's not too bad, though.",
      tips: '',
      tasks: null,
    },
    '45': {
      title: 'Birthday',
      audio: '7001',
      text: "Quick, come with me! I remembered it's your birthday, obviously, so I thought I'd throw you a proper party. There's food, there's drinks, and I invited a whole bunch of your friends, too. Hey, this is your birthday we're talking about! I wasn't about to let you spend it all alone!",
      tips: '',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "Really? This'll make me stronger? You'd better not be kidding, I have stacks of laundry to do.",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '47': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: 'It feels like... a fire inside of me has just begun to burn.',
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '48': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'I have all of this power, but how should I use it? I need to give this one some serious thought.',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '49': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Thank you for placing your trust in me. Your kindness warms my heart more than the brightest flame ever could. But not to worry, I've figured out what I want to do now. My strength is your shield, and I will always be here to protect you.",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '50': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Fire it up!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Check this out~',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: "Don't get too close!",
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: "Here's backup.",
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Supporting fire!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'I got you covered.',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: "Ooh, what's in here?",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Mm! The fortune slip was right...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Hehe, finders keepers.',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Hey! What was that for?',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Low HP: II',
      audio: '410002',
      text: "I'm done for...",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Low HP: III',
      audio: '410003',
      text: '*grimace* Right where it hurts...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Don't despair, I'm here to help.",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'What a mess... go on, take a rest.',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Fallen: I',
      audio: '500001',
      text: 'Time to go home...',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'Take care, everyone...',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Fallen: III',
      audio: '500003',
      text: "I couldn't save everybody...",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ow ow ow...',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Heavy Hit Taken: II',
      audio: '910002',
      text: 'Stop it!',
      tips: '',
      tasks: null,
    },
    '69': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'I guess the housework can wait.',
      tips: '',
      tasks: null,
    },
    '70': {
      title: 'Joining Party: II',
      audio: '600002',
      text: "Let's get out there and make some friends.",
      tips: '',
      tasks: null,
    },
    '71': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Where are we headed this time?',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Thoma\'s official title in the Kamisato Clan is that of a "housekeeper," and as such, he is responsible for matters such as cleaning and cooking.\\nWhenever he appears at the Yashiro Commission, Thoma is almost always busy with such work. He is able to get everything done well, and even Furuta, the butler of the Kamisato Clan, is full of praise for his housekeeping skills.\\nHowever, most of the time, Thoma does not stay in the Yashiro Commission, but goes elsewhere to deal with some special matters discreetly.\\nFor example: solving the problems encountered by the Yashiro Commission, asking for information for the head of the Kamisato Clan, fulfilling Ayaka\'s wishes, etc.\\nIn those unknown corners, Thoma has always used his own way to develop the influence of the Yashiro Commission.',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Thoma seems to have been born with a good temper.\\nRegardless of whether he\'s dealing with a dignitary or a street vendor, Thoma can easily find an opening to join the conversation and have a good time with them.\\nThoma, who is good at socializing, has a wide range of contacts in Inazuma. When he first arrived in Inazuma, he relied on his insight and communication skills to make friends with people in various industries. Later, many people would take the initiative to get to know Thoma.\\nThe more people you know, the more resources you can get. Thoma would learn a lot of first-hand information from them, or quietly strike "deals" that are beneficial to the Yashiro Commission.\\nHowever, although Thoma has a vast network of contacts, he has never used it for personal gain, nor has he ever forced others to do things in the name of the Yashiro Commission.\\nSociability, precise judgment, and just the right amount of tact. Perhaps this is the reason why Thoma can thrive as a "fixer" in Inazuma.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Surprisingly, the handsome and cheerful Thoma has no resistance when it comes to cute animals.\\nWhen Thoma's out, he always carries some small snacks for animals, and feeds stray cats and dogs when he sees them.\\nIt never fails to make him smile seeing animals scarf food down.\\nTo Thoma, these animals, like himself, are part of what makes up the world.\\nEven if they don't seem to be eye-catching, they are still trying to live.\\nAs long as you live, good things will always happen... This is what Thoma has always believed in.\\nEven if these animals had not encountered good things before, he hoped that at least his presence would be a good thing worth celebrating for.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "As the housekeeper of the Kamisato Clan, Thoma is an \"all-rounder\" when it comes to housekeeping.\\nWhether it's cleaning, cooking, sewing, gardening, caregiving, or socializing, he can handle it all with ease.\\nFor Thoma, housekeeping is not only a job and duty, but also his hobby.\\nHe would clean the house like new, making sure that there was not a single grain of dust left on the railings. He would be in a very happy mood when faced with a clean and tidy Yashiro Commission.\\nPerhaps it's the sense of accomplishment that comes with cleaning. Whenever he has the chance, Thoma will pick up a broom or duster and sweep away any unsightly stains.\\nIn addition, he also takes special care of the daily lives of his colleagues around him.\\nThere was a winter when Inazuma's temperature suddenly dipped, and a guard of the Yashiro Commission accidentally caught a cold while out on patrol. A few days later, he unexpectedly received a sweater hand-knitted by Thoma.\\nThe sweater that was just the right size made the guard think back to the clothes he received from his mother every winter. Now that his mother was old, she hadn't sent him clothes for many years.\\nWith this in mind, the guard took a long leave of absence to visit his family. The day he came back, he brought Thoma a special souvenir from his hometown, and they became good friends.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'Thoma\'s father is an Inazuman and his mother is a Mondstadter.\\nThoma grew up in Mondstadt and has been accustomed to its carefree and happy atmosphere since he was young. Influenced by this, he can easily mingle with anyone.\\nHowever, he has also been taught by his father since he was a child and places great importance on the word "loyalty".\\nAfter Thoma\'s father returned to Inazuma, he was worried that his old man would not be able to drink Mondstadt\'s wine there, so he sailed to Inazuma alone in a boat carrying Dandelion Wine.\\nOn the way, a huge wave overturned the boat and Thoma fell into the water. Fortunately, he just drifted unconscious down the water until he got washed ashore on a beach in Inazuma.\\nAt that time, Thoma had nothing and no family with him, but still started his life in Inazuma with optimism.\\nHowever, despite his best efforts, he was unable to find his father, who was supposed to be in Inazuma.\\nBut at his most difficult moment, Thoma met someone in Inazuma who was worthy of his "loyalty" to the end.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'Due to his hailing from Mondstadt, Thoma is often regarded as an "outsider" by the local residents of Inazuma.\\nDespite the strange looks and gossip directed towards him, Thoma never showed any dissatisfaction, and always smiled at all doubts.\\nThoma is recognized as the most amiable person in the Yashiro Commission, but to outsiders, it is another story.\\n"Don\'t offend Thoma! Otherwise, things will be difficult to handle."\\nNo one is sure when it started, but this saying has gone around so much that many people are convinced of this when they hear it.\\nAs for those who have had unpleasant run-ins with Thoma, the mention of him still instills fear:\\n"Don\'t be fooled by that guy! He\'s always smiling kindly, but all I did was cheat the Yashiro Commission out of a small sum of money, and he..."\\nThat\'s right, if anyone dares to harm the interests of the Yashiro Commission or disrespect the Kamisato siblings, Thoma will make them pay.\\nHe sees this as his duty and does his best, but does not like to boast about his achievements. Even if he is criticized for this, he will not defend himself too much.\\n"Gee, who cares about such trivialities? And it doesn\'t matter what kind of person I am, as long as those who should know know it."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Old Duster',
      title2: null,
      text: 'Thoma\'s favorite duster has been with him in many "conquests".\\nAs it has been used for too long, no matter how Thoma cleans and takes care of it now, it still looks old and gray. Despite this, Thoma is still reluctant to discard it.\\nThis duster was given to Thoma when he was first assigned cleaning duties at Yashiro Commission. As soon as he sees it, he recalls those hard but happy times.\\nAt that time, Thoma had yet to comprehend various cleaning techniques. Due to his lack of experience, he was often busy doing all kinds of cleaning and tidying work until late at night.\\nAccompanying him were the moonlight above his head, the chirping of insects in the summer night, and the sound of a duster tapping on the beams.\\nThere are many different kinds of cleaning. From a simple cleaning to an all-out deep cleaning, Thoma has experienced it all.\\nAt first, he found the work boring, but after he got used to it, he found that he could think more quietly when cleaning.\\nSo to this day, Thoma often uses this duster to perform his work.\\nWhile brushing away the dust in front of him, he also brushed away the fog in his head in a quiet and steady state of mind.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'In his early years living in Mondstadt, Thoma did not have particularly strong aspirations.\\nEach day, he was awakened by the early morning sun and the fresh fragrance of flowers. After breakfast, he could choose to take a relaxing stroll through the city or explore the wilderness freely.\\nAt that time, Thoma thought that people should have the happiness of living a leisurely life. Perhaps it would have been better to live a peaceful life.\\nThis calm mood disappeared the moment when he was swept into a strange country by the waves, across the ocean in a small boat.\\nHere, he had to receive a favor to survive, and thus the thought of "repayment" arose.\\nTen years ago, when the Yashiro Commission\'s Kamisato Clan was losing its power.\\nKamisato Ayato, who was embroiled in the dispute over the succession rights of the clan due to the death of both parents, told Thoma:\\n"Now that the situation in Inazuma is unclear, the trouble the Kamisato Clan faces will only increase. You are someone who can see what\'s at stake, so if you don\'t want to get involved, leave early."\\nCould Thoma, who had received so many favors from the Kamisato Clan, just leave like that? Choosing to leave would mean that he would have to return to his ordinary, stable life with regrets and guilt.\\nThe storm was imminent, and Thoma was like a leaf drifting in the sea.\\nBut after much deliberation, Thoma\'s answer was:\\n"If I leave at this time, I will lose my loyalty and righteousness. Father has always taught me to be a loyal and righteous man... I would like to do my best to do my part for the young master and the young lady. You will certainly need me as a helper in the path you embark on in the future."\\nThe will to burn for loyalty and righteousness forged a strong desire that drew the attention of the gods.\\nAs if to respond to Thoma\'s choice — on this night of divergent destinies, a Vision, bright red like a blaze, appeared beside him.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
