export const xinyanVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "Xinyan's the name, an' rock 'n' roll's the game — and I'm the only one who plays it in Liyue Harbor. Been thinking about staging concerts elsewhere lately, but... Hmm... Well, word is that you've been all over the place, Traveler. So, what say you sign me up for your world tour? Anywhere's good!",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: Vigor',
      audio: '1101',
      text: "If there's fire in your soul, you gotta rock 'n' roll. So c'mon! Let's get movin'!",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: New Song',
      audio: '1102',
      text: 'I just came up with an awesome new riff, wanna hear it?',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Look!',
      audio: '1103',
      text: "Whatever's going on over there... Looks pretty rock 'n' roll to me!",
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: "It's really comin' down... Would be all sorts of bad if my guitar got wet.",
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When Thunder Strikes',
      audio: '1202',
      text: "This rain ain't clearin' any time soon... but the show's still on, people!",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When It Snows',
      audio: '1203',
      text: 'Hmm... How do we attract more folks in this weather? Right! How about we stage a rock-till-you-drop snowstorm endurance challenge?',
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'When the Wind Is Blowing',
      audio: '1204',
      text: "Ack! Gotta find some cover, quick, or my hairdo's gonna fall apart!",
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Morning',
      audio: '1001',
      text: "Mornin'! I was just warmin' my voice up. We're in real good shape today.",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "Alright, that's a wrap! *yawns* If there's nothin' else, I'll go take a nap somewhere...",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Evening',
      audio: '1003',
      text: "Almost about to go live over here. You comin'?",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'Good Night',
      audio: '1004',
      text: "Me? Oh, I've got a guitar to maintain, tunes to rewrite... I mean, I just got offstage, there's no way I can sleep right now.",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Xinyan: Frightening',
      audio: '2001',
      text: "Not afraid of me, are you? Some folks say I've got eyes like knives, that I don't wear my clothes right, that I don't speak right. They give me a pretty wide berth, too. Really, can't a girl sport her own style without bein' looked at like she's some weird creature outta who-knows-where?",
      tips: '',
      tasks: null,
    },
    '13': {
      title: "About Xinyan: Rock 'N' Roll",
      audio: '2002',
      text: "Rock 'n' roll came to Liyue from Fontaine, so I guess you could call it a new thing. But it's not too hot around here. Most think it's an awful racket not fit for human ears. And that's why I appreciate everyone who does come listen, haha!",
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: The Audience',
      audio: '2003',
      text: "You wanna hear me play? Come to the front — it sounds best from there! *clears throat* Alright then, comin' at you from the one and only rock stage in Liyue!",
      tips: '',
      tasks: null,
    },
    '15': {
      title: 'About Us: Kindred Spirits',
      audio: '2004',
      text: "And here I was wonderin' why we got on so well! So you're not from this world, and that's why you don't care for its rules. Now that's how life should be like! Lose the red tape, and live free!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '16': {
      title: 'About Us: Invitation',
      audio: '2005',
      text: "I'd sure love to add some extra flavor to my rock 'n' roll. Wanna get on the drums next time? You've got a good sense of rhythm. ...You've never played? Don't sweat it, it's a question of soul, not skill! Give it a go, I just know you'll be great!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '17': {
      title: 'About the Vision',
      audio: '3001',
      text: "I'm guessin' that I'm the only person in Teyvat who uses the fire from their Vision in rock performances. Some say I should respect that power more... But the way I see it, the gods gave the Vision to me, so they like my style, don'cha think?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Something to Share: Naming',
      audio: '3002',
      text: 'I made this guitar myself, y\'know? Based it off a rock \'n\' roll instrument from Fontaine at first, but it stopped looking like the original real fast. I wanted to give it a rad name, like "The Fyre Lyre," or "The Jadebreaker," or "The Hill Stiller." Still, feels like we\'re missin\' something... Any ideas?',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '19': {
      title: 'Something to Share: Opera',
      audio: '3003',
      text: "You ever heard of opera? It's what those rich guys listen to at their banquets. It's all tenor this and falsetto that... Gettin' so uptight about music, ugh — it's just not rock 'n' roll.",
      tips: '',
      tasks: null,
    },
    '20': {
      title: 'Interesting Things',
      audio: '3004',
      text: "My favorite stage outfit's one I made by hand outta Silk Flowers. You must've seen those flowers before, haven'tcha? Passion-red, they are — a perfect match for my music!",
      tips: '',
      tasks: null,
    },
    '21': {
      title: 'About Xiangling',
      audio: '4001',
      text: "I have dinner at the Wanmin Restaurant often. If Xiangling's got some time on her hands, we'll chat till it's real late. Eh? You wanna know what I order? See... I actually eat everything she makes. It's never the same thing, and the flavor's different each time, too. Ooh, she's the rock star of the culinary world, she is!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Zhongli',
      audio: '4002',
      text: "There was this one fellow who invited me to perform at his place, back when there weren't many who would give my music the time of day. I was touched, let me tell you what. Like, hey, someone gets it! I agreed right away... But when I got there, I found out that he was the consultant at the Wangsheng Funeral Parlor. What a weird guy. I mean, how was that appropriate?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Ningguang',
      audio: '4003',
      text: "Y'know, the Millelith used to get in my way all the time. Can't set up a stage here, can't perform there. Real bother, it was... Ahem. But after I wrote to the Ministry of Civil Affairs, I heard that the Tianquan amended one of Liyue's... Uh, some rule or something. She designated some spots for performances to take place, so long as you apply. *sigh* It's still a load of trouble if you ask me, but it's better than being harangued by those Millelith every time, so...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Baizhu',
      audio: '4004',
      text: "Dr. Baizhu's prescriptions are the tops at preserving my voice. I did an impromptu performance for him as thanks, but... the snake he keeps around his neck fainted away. Haha, now it ducks up Dr. Baizhu's sleeve every time I'm around. I only discovered afterwards that snakes are very sensitive to vibrations.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Beidou',
      audio: '4005',
      text: "Her? She speaks her mind and has a big heart, and we get on great. The Crux's adventures are real epic. They've given me tons of inspiration in the past! I even wrote them a song. Nowadays, I just need to sing the first line, and most all the sailors will join in. It's fast becoming a new sea shanty, it is.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Chongyun',
      audio: '4006',
      text: "He's one interesting guy. He looks introverted enough, but there was this one time when he came to one of my performances. A friend brought him or something, and he had some words for me, but I couldn't hear 'em over the music. Before I knew it, he was right up there on the stage with me, singing and rockin' his heart out. Guess you really can't judge a book by its cover!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Hu Tao',
      audio: '4007',
      text: "I've no clue what she's thinking, going around looking all happy-clappy like that when she's the head of the Wangsheng Funeral Parlor. Always greets me cheerily too, saying \"I like people who play with fire, they're good for business\" or somethin' like that... She's a bit bizarre, I tell you.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Yun Jin',
      audio: '4008',
      text: "Tell you a secret — but you gotta keep it that way, you hear? She's real fond of rock 'n' roll. Comes to watch me at least three times a week no matter how packed her schedule is. You'd think that the head of Heyu Tea House's troupe would be into finer arts and all, eh? But I guess it gets suffocating after a while. Haha.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'About Gaming',
      audio: '4011',
      text: "The first time Gaming told me I had a bad case of \"rock 'n' roll fever,\" I checked my forehead to see if he was right. My temperature was fine, so I denied it. But he insisted it was true. We went back and forth arguing about it for hours before I realized it was all just a misunderstanding. Gaming explained that it was just another way to say you're a fan of something. Hahaha, there's never a dull moment when Gaming's around. Anyway, I've definitely come 'round to \"rock 'n' roll fever\" as an expression — I'll have to work it into the lyrics next time I write a song!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '30': {
      title: 'More About Xinyan: I',
      audio: '5001',
      text: "You wanna know more about me? Haha! Well, aren't you just odd? Most people would do just the opposite. Well, where should we start? ...Eh, I guess we'll start with rock 'n' roll.",
      tips: '',
      tasks: null,
    },
    '31': {
      title: 'More About Xinyan: II',
      audio: '5002',
      text: "Back when I was little, the adults all said I had to be more girly, that I should learn and study all these things. Wasn't ever any good at it, though, and I'd often get roasted bad. Rock 'n' roll's a different story. No one ever taught me, but I can do it just fine. And of course, the adults say \"that's unladylike!\" *sigh* Talk about prejudice.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '32': {
      title: 'More About Xinyan: III',
      audio: '5003',
      text: "Say, do you notice anything different 'bout me today? I did some facial massages to relax my mouth and eyes, and practiced smiling less broadly in front of a mirror for half an hour. So, how'd it go? Do I look a bit less fierce than usual? ...Even scarier? Huh, okay...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '33': {
      title: 'More About Xinyan: IV',
      audio: '5004',
      text: "Thanks for staying to jam with me! It's almost time for lunch. I've brought your share as well! We've got tomatoes, sausages, fried eggs... Say what? I don't seem like the type? H—Hey now, don't you look down on me. M—Making a nice-looking meal was no problem at all!",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '34': {
      title: 'More About Xinyan: V',
      audio: '5005',
      text: "I believe in rock 'n' roll's spirit of resistance, but I don't think it means that I have to go around shoving it in people's faces. I'm perfectly capable of living normally. I can sew, I can grow flowers and keep fish, and make nice-looking meals. I'm allowed to like anything... or anyone I want, right?",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '35': {
      title: "Xinyan's Hobbies",
      audio: '6001',
      text: "Hobbies? Rock 'n' roll, of course! You ever have that something you put your all into? When everything you love comes together into one thing, the place and time loses all importance. You just need to enjoy it to the fullest, and express yourself to your heart's content! Haha... Ah, I can never get enough of that feeling.",
      tips: '',
      tasks: null,
    },
    '36': {
      title: "Xinyan's Troubles",
      audio: '6002',
      text: "*sigh* I send children a-crying every time I accidentally lock eyes with them on the road. *sigh* If only there was a way to make me look a little less scary. But I've tried everythin', and nothing sticks...",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Favorite Food',
      audio: '6003',
      text: "The lunch down at the Liyue dockyards rocks! Ahh, oily, meaty... Bit skimpy on the vegetables, but I could never get tired of it! Far as I'm concerned, a whole day in the dockyards is worth it just for the lunch!",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "Not that I'm picky, but I can't stand bland food. If it's supposed to be salty or spicy, make it salty or spicy! You can't have a good time if you don't go all-in on the flavor! Even if all I had on hand were enough ingredients for one serving of Jewelry Soup, I'd make sure I'd do right by them!",
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: "Wowee, you've rocked my socks off with this one. I am moving to the groove of your awesome food! Mm-mm!",
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: "The taste ain't bad, but it's lackin' that special spark... I can help you with the presentation if you want?",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "Hmm... You don't mind if I add a little something to spice things up, do ya?",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! I made some embroidery especially for you. Check it out — I sewed both our images on in the style of Fontaine's dolls. Pretty cute, eh? ...Why are you looking at me like that? Wh—What, it's not that weird that I can do embroidery!",
      tips: '',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: "That's the groove, alright! That's what I'm talkin' about!",
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "I'm on fire lately. Look out for my next performance!",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: "With such power, who knows what never-before-seen bangers I'll be able to come up with? Thanks so much! My next work won't disappoint!",
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '46': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "I feel your awesome, overflowing passion! Tell you what, I'll write you a rock song. It'll be your song — and I'll play it just for you!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Feel the beat!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Power chord!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Pyrotechnics!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Time to rock!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: "Shred 'til I'm dead!",
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Amp it up!',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Time to celebrate! Ready? 1, 2, 3, 4...',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'This rocks!',
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: 'Woohoo! Let me hear ya!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: I',
      audio: '410001',
      text: "That was jus' the intro...",
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Alright, that sounded kinda bad.',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Low HP: III',
      audio: '410003',
      text: "I'm used to this much.",
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: "Rockin' to the rescue!",
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: "Hey now, don't rock till you drop!",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: I',
      audio: '500001',
      text: "The beat's all... messed up.",
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: II',
      audio: '500002',
      text: "Didn't make it... to the chorus...",
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'Went... out of tune...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Light Hit Taken: I',
      audio: '900001',
      text: 'Tch! Not cool.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Hey! Not the guitar!',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: I',
      audio: '600001',
      text: "I'm takin' the stage!",
      tips: '',
      tasks: null,
    },
    '67': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'Aw yeah, rock on!',
      tips: '',
      tasks: null,
    },
    '68': {
      title: 'Joining Party: III',
      audio: '600003',
      text: "Let's jam!",
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: "Rock 'n' roll originates in Fontaine and is just starting to find its feet in Liyue Harbor, where Xinyan is pioneering the art.\\nEvery night, she slings on her self-built instrument, steps onto her self-constructed stage, and plays her self-composed songs to a crowd of enthusiastic supporters.\\nHer music reflects her personality: bold and defiant, loud and proud.\\nShe is no virtuoso, but this doesn't bother her dedicated fans one bit as they let loose and enjoy the show, singing their hearts out and shaking off the stress of the day.\\nIn the heat of the moment, the fire that leaps from Xinyan's Vision seems ready to turn night into day.\\n\"She is a rare rock 'n' roll talent and a master performer who really knows how to create an atmosphere,\" said a review of one of her live shows in The Steambird.\\nLiving in Liyue is expensive, especially when you want to enjoy the finer things in life. But as Xinyan would say to those tied down by worldly worries:\\n\"If you know how to rock, then it's easier to roll.\"",
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'Xinyan does not adhere to traditional performance norms at all. Anything can be used as her instrument.\\nThe pillars on-stage, the floorboards, the cheers and yells of the audience, and even the explosions and sparks created by her Vision are valid brushes with which she paints her performance.\\nThe impromptu stage often starts to burn somewhere after the halfway mark of the performance, till all that\'s left is a smoking pile of charcoal.\\nAfter many warnings, the Millelith were finally forced to tighten their patrols and try to find ways to stop Xinyan from staging her performances.\\nThe subsequent battles of wits tended to turn out in Xinyan\'s favor — she was often able to find a place to perform, set up a stage with frightening speed, and begin a raucous night with her audience.\\nThe more reliable word on the street is that many patrolling Millelith were themselves infected by the "spirit of rock \'n\' roll," becoming her loyal fans in the process.\\nXinyan would get wind of the Millelith\'s latest patrol plans from these "friends of rock," and was thus able to avoid their eyes with ease.\\nEventually, tiring of the lack of results, and in the absence of any evidence that anyone was harmed during Xinyan\'s performances, the Millelith came to adopt a "one eye open, one eye shut" approach to her actions.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: "Xinyan is tall, has a sharp gaze, and always wears her stage costume in public to keep herself in the right mood for her music.\\nIn the eyes of bystanders, this makes her quite the imposing sight as she walks down the street, and many assume she means trouble.\\nWhen she lines up to buy a snack, people in front of her in the queue will panic and move well out of her way.\\nIf she happens to lock eyes with a young child, even for a brief moment, they will run crying to their parents.\\nEven when she has done nothing at all, Xinyan is often suspected of wrongdoing, purely because her fierce appearance makes her look like some sort of heinous villain in the eyes of some people.\\nXinyan didn't care all that much about how other people saw her, but she did think that it wasn't a good thing to scare others and make trouble for them, if she could at all help it. Thus, she constantly looked for ways to make a change.\\nEvery day when she woke up in the morning, she would look at herself in the mirror and massage her face with her fingers to stretch and relax her eyes a little.\\nShe would even practice smiling and study expressions — verbal and facial alike — of great elegance.\\nAfter a significant amount of practice, she once came across a group of children bullying another child, and instinctually she went over to rescue the bullied child.\\nShe gave the kid what she thought was a friendly smile and a gentle pat on the head. To say that the upset child quietened down after this would not be incorrect...\\nHowever, the reality of the matter was that the child was stood there frozen in fear as urine dribbled down their pants.\\nAs for the would-be bullies, they screamed and fled in panic.\\n\"Run! Run! The angry lady's turned into a monster! Sh—She's gonna eat us all!\"\\n\"Hey!!! I ain't gonna eat y'all! ...And I ain't no monster, either!\"\\nBut it was to no avail. The moment she raised her voice, all her hard work was undone.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: 'Xinyan has one standard by which she judges all things: is it or isn\'t it "rock \'n\' roll?"\\nAll that is just and upright — standing up for those who have been wronged, taking on challenges — is "rock \'n\' roll," and all that is reprehensible — fearing the wicked, oppressing the kind, dirty tricks, scheming ways — is "not rock \'n\' roll."\\nRock is the spirit of rebellion and resistance, yes, but patently immoral acts are nonetheless "not rock \'n\' roll."\\nXinyan reserves the right to make these judgments, and whether these judgments are based on results or her mood, the difference between the things covered by these two opposing terms is clear.\\nThe only catch is that these standards sound odd in certain contexts.\\nDue to her fierce appearance, Xinyan nearly has no friends, with Xiangling of Wanmin Restaurant being one of the few exceptions with whom she can speak most freely.\\nXinyan has a special reason for coming to Wanmin Restaurant — for musical inspiration.\\nWhenever Xiangling is researching new recipes, others may run for the hills, but not Xinyan. She intentionally eats all the experimental products, and amid the taste bud explosion that results from the never-before-seen flavors, inspiration flows into her mind.\\n"Tell you what, Xiangling, that dish rocked!"\\nThough Xinyan considers this to be the highest praise, Xiangling finds it a little hard to be happy about such ratings.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'The eternal subject of rock \'n\' roll is resistance.\\nBut the thing that Xinyan resists is not a concrete thing, but rather, the conceptual shackles of "prejudice."\\nShe was born into a poor family, and her parents placed great stock in her, giving her the best of what little they had in the hopes that she would be able to rise to "become a phoenix."\\nOf course, this "phoenix" would have to be something that they would recognize.\\nBut things don\'t always turn out as planned. Xinyan grew to be taller than most girls, and her looks were far from anything that might be considered "cute." Nor was she any good at any of the feminine arts, whether it was cooking, chores, needlework.\\nSo, since her childhood was so deeply impacted by such "prejudices," Xinyan understands how terrifying they could be.\\nYet becoming a rock \'n\' roll star has not caused her to give up on these other arts.\\nThis is not only because she hates losing, but because she feels that "giving up because you have no talent" is itself a prejudiced belief.\\nNot long ago, a fan of Xinyan\'s named Yun Jin was invited to her place as a guest.\\nBut if Xinyan hadn\'t opened the door herself, Yun Jin would have thought that she had the wrong house.\\nThe house was spick and span, the windows were clean, and the home ornaments were hand-made and immaculately arranged.\\nThe cooktop was still moist, indicating that someone had been cooking not long before, and there was half-sewn cloth by the bedside that looked much like the decorations Xinyan wore during her performances.\\nWhy, this was practically the room of some refined lady of reputable upbringing, with nary any spirit of rock \'n\' roll to be found!\\nXinyan was quite worried that this fan of hers would find the difference between their impression of "rock \'n\' roll" and this reality too jarring.\\nUnexpectedly, Yun Jin\'s support and fandom would only grow more intense after this.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: 'The way Xinyan sees it, many adults fail to realize their potential because they are tied down by prejudice, giving in to fear and endless anxiety.\\nThey do not understand what life is about, or where they are going.\\nShe wrote these thoughts into her songs, but invited scorn from the very same adults. "What does this brat know?"\\nEven so, Xinyan did not waver. After all, such mockery was born of prejudice towards her age.\\nAnd if prejudice were something so easily overthrown, there would be no value in resisting it, would there?\\nShe believes that rock \'n\' roll is like a seed. After every performance, some seeds might sprout within the hearts of those adults who listen.\\nWhen they wake up the next day, perhaps they might receive some inspiration, or perhaps a change of mood will come over them...\\nEven if it only changes their thinking a little bit... Perhaps they might find that the real-life troubles they are facing are nothing but a storm in a teacup.\\nOf course, few people other than her audience and the "friends of rock" would credit this to rock \'n\' roll.\\nBut people do nonetheless say this around the tables after tea.\\n"Well, having a girl who plays rock \'n\' roll is pretty interesting, no?"',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: "Xinyan's Instrument",
      title2: null,
      text: "Xinyan's main instrument is a hand-made guitar of a very unique design. She based it off the rock 'n' roll instruments that were imported from Fontaine before adding additional modifications based on personal understanding.\\nFor example, she mounted a crescent-shaped axe-blade on the tail end of the instrument so it might serve as a weapon in a pinch.\\nShe also connected it to her Vision, allowing it to spew flames and sparks. Its internals can also spew flame, all the better for it to self-destruct if it falls into the wrong hands, preventing its misuse...\\nThe list of modifications goes on, and they are too numerous to count.\\nThis instrument is thus unique, and its sound profile is also special.\\n—Sorry, what? What do you mean, \"these modifications sound like they have nothing to do with music?\"\\nSounds like you, too, need to attend one of her performances. You'll understand then.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: "Xinyan was someone who never fit in in Liyue Harbor, and she only found where she belonged when she encountered rock 'n' roll.\\nBut because she lived in a land that had no place for rock 'n' roll yet, she needed to be able to attract enough attention.\\nShe immersed herself in the world of music, looking for a way to move people's hearts. She broke many an instrument and played till calluses formed on both hands, but still, it was unsatisfactory.\\n\"Who'd want to listen to this racket?\"\\nThe rotten-tomato reviews she received were starting to get to her. She wondered if she should quit.\\nSitting on top of Mt. Tianheng, she looked down over Liyue Harbor. But though the lights lit the streets and alleys of the harbor, they could not light the flame of the spirit of rock 'n' roll.\\nShe considered leaving, to go someplace where rock 'n' roll was appreciated. But would this not be running away? Would it not be a betrayal of rock 'n' roll's spirit of resistance?\\nNo, she would not leave. She would become a \"flame\" that could light Liyue Harbor up.\\nShe started experimenting with the use of fire to move people, adding sparks and explosions to her music.\\nBut this was no mean feat for an ordinary person.\\nWho knows how many times she must have burnt her fingers or blown her instrument up. But still, she continued to practice every single day on top of Mt. Tianheng.\\nAnd perhaps it was that the gods themselves had great expectations of this new form of music that would soon grace the seven nations...\\nBut regardless, the boiling-hot Vision would be the final stroke of perfection.\\nXinyan dashed down the mountain and began her very first rock 'n' roll concert in Liyue Harbor.\\nThus did her musical journey begin, with showers of sparks and explosions keeping time.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
