export const yanfeiVL = {
  quotes: {
    '0': {
      title: 'Hello',
      audio: '1000',
      text: "My name is Yanfei, top legal expert in Liyue — and for the avoidance of doubt, no one else comes close! From commercial litigation, to civil mediation, to criminal lawsuits, I'm fully versed in every area of the law, and I guarantee you a swift and satisfactory conclusion to your case! My contact details... Where should I write this down? ...Hmm, paper will just get lost, and it'll only rub off if I write it on the back of your hand, so... Aha! I know, I'll just write it here, on the clothes of this... whatever this thing is that follows you around.",
      tips: '',
      tasks: null,
    },
    '1': {
      title: 'Chat: The Law',
      audio: '1101',
      text: "I'll remind you again: The law can be both a help and a hindrance.",
      tips: '',
      tasks: null,
    },
    '2': {
      title: 'Chat: Work',
      audio: '1102',
      text: 'Sometimes the law is compatible with human nature, but sometimes the two conflict. Balancing the two is a discipline in its own right...',
      tips: '',
      tasks: null,
    },
    '3': {
      title: 'Chat: Reading',
      audio: '1103',
      text: 'The case before us... is a strange and unprecedented one indeed.',
      tips: '',
      tasks: null,
    },
    '4': {
      title: 'When It Rains',
      audio: '1201',
      text: 'Rain! Oh, Lord of Geo, please, do us a favor and clear this up at your earliest convenience... I submit that we cannot afford for the codices to get damp...',
      tips: '',
      tasks: null,
    },
    '5': {
      title: 'When It Snows',
      audio: '1202',
      text: "What the... What kind of injurious weather is this!? It's c—cold... Achoo...",
      tips: '',
      tasks: null,
    },
    '6': {
      title: 'When the Sun Is Out',
      audio: '1203',
      text: "Ah, this weather's got me in the mood for reciting some laws. Let's see... \"Commercial Law of Liyue,\" Chapter 27, Section 6, Article 3 stipulates that— Wait, what was it...? Oh my goodness, I've completely forgotten! What is wrong with me today...?",
      tips: '',
      tasks: null,
    },
    '7': {
      title: 'Good Morning',
      audio: '1001',
      text: 'I have to head out this morning to meet a client about a creditor dispute, but I also have to follow up on a consultation from last week by noon... Alright, time to get to work!',
      tips: '',
      tasks: null,
    },
    '8': {
      title: 'Good Afternoon',
      audio: '1002',
      text: "*yawn* I'm a little sleepy... I know, a vigorous debate should wake me up! And I've got just the topic: \"The Northland Bank's presence in Liyue does more harm than good for our economy.\" ...So, are you for or against?",
      tips: '',
      tasks: null,
    },
    '9': {
      title: 'Good Evening',
      audio: '1003',
      text: "The night market? Hmm... I was planning on organizing some files this evening, but if you're going, I can join you. Oh, I should mention — lots of vendors go for the hard sell in the evenings, because they want to be able to start with fresh produce the next day, but also don't want to lose profit on what they have left today.\\nSo, leave the negotiating to me. And... If you have any leftovers, those can be my fee.",
      tips: '',
      tasks: null,
    },
    '10': {
      title: 'Good Night',
      audio: '1004',
      text: "Need a cure for insomnia? Let me read you the history of the development of Liyue's legal system! None of my friends have ever lasted longer than 20 minutes... Oh, you want something more fast-acting? Then I'll recite from the legal codices! Let me know in the morning which section I got to before you fell asleep! Okay, here I go...",
      tips: '',
      tasks: null,
    },
    '11': {
      title: 'About Yanfei: Atmosphere',
      audio: '2001',
      text: "You think I come across as quite imposing when I'm reading through case files? Huh. Well, that's only when I'm in work mode. It's like... I have an invisible switch, flick it one way and I'm in normal mode, flick it the other way and I switch to work mode. Surely you must have a switch like that, too?",
      tips: '',
      tasks: null,
    },
    '12': {
      title: 'About Yanfei: Weakness',
      audio: '2002',
      text: "Civil cases are the ones I dread the most. Divorces, custody disputes... It's a thankless task trying to unpack these kinds of cases with logic and reason. You have to be kind, courteous, and patient with your clients, even though half the time they are completely incapable of participating in a constructive discussion. *sigh* I know I advertise myself as being fully versed in every area of the law, but honestly, if it were up to me, I'd rather everyone could just get along, so we wouldn't have so many of these cases.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '13': {
      title: 'About Us: Rates',
      audio: '2003',
      text: 'You want legal advice from me? Sure. For legal opinions, I charge a flat rate of 6,000 Mora, for advisory services, my hourly rate is 180,000 Mora, and for commercial law, I charge 710,000 Mora per case — final quote and commission rate depending on the details of your case. Not a bad deal, right?',
      tips: '',
      tasks: null,
    },
    '14': {
      title: 'About Us: Relationships',
      audio: '2004',
      text: "If you're concerned about what kind of complicated issues you might get tied up in during your travels, your best bet is to bring someone with you who knows and understands the law. Someone like me, for example, whose expertise goes beyond just the law of Liyue... Well, actually, having said that, Fontaine's law is notoriously complicated... Though, with my level of intelligence, getting acquainted with it should be no problem! Anyway... My point is, you can always rely on me!",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '15': {
      title: 'About the Vision',
      audio: '3001',
      text: "Visions appear in response to strong desire, so as someone with ideals, it's only natural that I should have received one. Because, above all, I wish for all people to live honest lives and abide by the law. But some people will always insist on playing by their own rules and causing havoc for everyone else... Hah, those people can expect to be prosecuted so hard, they won't know what hit them!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '16': {
      title: 'Something to Share: Balance',
      audio: '3002',
      text: "This steelyard balance was a gift from my father. It weighs objects to determine their value. I usually use Mora for the weight, but it can only give the original price. For example, a thousand years ago, Liyue was covered in Glaze Lilies, and they weren't worth anything in monetary terms. Then, when they suddenly declined in number, the price shot up in response, but the value shown by this steelyard wasn't updated. It still shows them as their original value... in other words, dirt cheap.\\nSo, most of the time, this isn't a very useful tool for work purposes... Hmm? You want to try weighing something? How about... We could weigh your little friend here, will that do?",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '17': {
      title: 'Something to Share: The Rule of Law',
      audio: '3003',
      text: 'I have a self-defense method that I call "Wrath of the Flame," based on a punishment called the "Wrath of the Rock," which is detailed in the ancient work "The Comprehensive Compendium of Liyue Law." The Lord of Geo is the God of Contracts, and contracts, too, can be seen as a way of restraining people. Haha, ergo, Liyue Harbor has been the City of Contracts since time immemorial.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '18': {
      title: 'Interesting Things',
      audio: '3004',
      text: 'The Historia Naturalis Liyue has an entry about a waterborne plant called the Horsetail. It claims that "The Horsetail is a medicinal herb that stands alone on the banks of Dihua Marsh. Its color is that of the clouds at sunset." Apparently, if you grind it into a powder and mix it into your ink, it makes your writing water-resistant. But it\'s a shame, I\'ve been to Dihua Marsh at least a hundred times, and each time I end up with baskets and baskets of the common purple variety, but not a single one of the kind that the book describes.',
      tips: '',
      tasks: null,
    },
    '19': {
      title: 'About Qiqi',
      audio: '4001',
      text: 'I heard that little herb gatherer has written out a whole set of behavioral rules for herself. She may be small, but boy, has she got her head screwed on! She\'s definitely destined for greatness...\\n"The young of today shall outperform us tomorrow," as they say. I must admit, she has my respect.',
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '20': {
      title: 'About Ganyu',
      audio: '4002',
      text: "Ganyu is kind and thoughtful, it's just a shame she's so busy all the time. Most of the time, she's buried in an endless pile of paperwork — the only exception being her nap at noon. Don't get me wrong, I have to put in some hours at work, too. But I'm happy with the job I've chosen, and it's certainly a lot less taxing than hers.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '21': {
      title: 'About Xingqiu',
      audio: '4003',
      text: "The Feiyun Commerce Guild is one of my oldest clients. Their approach to business is meticulous and thorough, and every business meeting I've had with them has always been attended by the head of the house himself. Last time, though, I happened to meet their youngest, Xingqiu. To my complete surprise, the lad had no trouble whatsoever keeping up with my train of thought. He was very eloquent, too, and had excellent manners. Mm, definitely not a simpleton.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '22': {
      title: 'About Hu Tao',
      audio: '4004',
      text: "I always hear people saying that the director of the Wangsheng Funeral Parlor has an unorthodox approach to business. They think she's gone a little non compos mentis after being in the funeral business so long... What are these people talking about? The Wangsheng Funeral Parlor provides a legitimate and necessary service, which is the cornerstone of any successful enterprise. Work is just work — there are no good and bad jobs, or lucky and unlucky jobs, just jobs that need doing.\\nIf I had one gripe, it would be that the director rarely comes to me for legal advice, hmph...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '23': {
      title: 'About Zhongli',
      audio: '4005',
      text: "Mr. Zhongli has so much in-depth knowledge on so many topics, he's like a walking library, you know what I mean? He's a total savant, though he never flaunts it. I could tell just by looking at him. People like him rarely shy away from taking on complex problems alone, so in my estimation he's certainly not a potential client.\\nAnd yet, somehow, I can't help but think I know him from somewhere, it's hard to describe the feeling... I asked my father about it, and he just said something to the effect of he didn't know either, though he seemed a little evasive. It was so strange... Anyway, makes me wonder if my father is hiding something from me. Hmph, alright then — if he won't tell me what's going on, I'll just have to find out for myself...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '24': {
      title: 'About Ningguang',
      audio: '4006',
      text: "You must have heard of the Tianquan, Ningguang? She's the highest authority where the law is concerned, and often makes amendments to the legal codices. Every round of additions, retractions, and revisions generates mountains of material. Why, the latest edition of the legal codices contained three new laws, 121 revised legal annotations, and an array of new legal precedents. Archons know how long it's going to take me to commit them to memory...\\nHmph... still, she's a businesswoman at heart, I'm not about to let her beat me when it comes to the law. Once I've finished memorizing these, I need to step up my productivity...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '25': {
      title: 'About Keqing',
      audio: '4007',
      text: "The Yuheng doesn't deal with matters of the law, and thank goodness... Knowing Keqing's attitude toward work and ruthless efficiency, I'd end up losing a lot of work. Although... No, surely it wouldn't come to that. She's a stickler for doing things the right way — no doubt she'd offend people... but if she had someone like me as her legal assistant... No way! Why should an eminent legal expert such as myself be relegated to the role of assistant!? If she needs legal counsel, she can come and find me.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '26': {
      title: 'About Eula',
      audio: '4008',
      text: "Eula saved me once, and we've kept up correspondence ever since. She's very familiar with the Knights of Favonius' legislation, but has never been one to be bound by convention. She uses cunning logic to deal with problems flexibly... Perhaps the reason we get along so easily is that I'm a similar type myself. Still, I'll never acquire that carefree spirit of hers. We are in very different professions, after all.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '27': {
      title: 'About Yelan',
      audio: '4009',
      text: "Yelan is an employee of the Ministry of Civil Affairs — she once helped me crack a tough accounting fraud case. I treated her to dinner afterward. The only thing is... I feel like she's able to read my mind at any given moment when talking to her... Yes, in the future, I need to make absolutely sure I don't get on the wrong side of her.",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '28': {
      title: 'About Kuki Shinobu',
      audio: '4010',
      text: "Shinobu? I remember her, she's the Inazuman girl that came to Liyue as an exchange student to specialize in law. When she was doing her coursework, she used to meet with me to discuss some cases, and after we were done, she'd always bow and thank me, which would always make me a little embarrassed. I always felt like she was going to make an excellent lawyer in the future. Thinking about it, Inazuma went into lockdown right around the time she would have graduated. I wonder how she's been doing since she went back...",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '29': {
      title: 'More About Yanfei: I',
      audio: '5001',
      text: "A client? Very pleased to meet you, here's my card. I'm afraid I can't leave my desk today, if it's a dispute we're dealing with then please bring the relevant parties here to see me. Let me just give you a breakdown of my fees — one moment...\\nHuh? You came just to chat? Uh... no fee necessary then. So just to clarify... you came to chat as friends with a legal expert that you've never met before... care to explain?",
      tips: '',
      tasks: null,
    },
    '30': {
      title: 'More About Yanfei: II',
      audio: '5002',
      text: "These antlers? Oh... well my father is an adeptus, so I have adeptus blood myself. Still, I was born during peacetime here in Liyue — I never signed a contract with Rex Lapis. Naturally, I don't have to concern myself with adeptal affairs — I'm free to focus on the life I want to live. Works for me! Hee-hee.",
      tips: 'Unlocks at Friendship Lv. 3',
      tasks: null,
    },
    '31': {
      title: 'More About Yanfei: III',
      audio: '5003',
      text: "Contracts of that magnitude — lifelong commitments... I've only ever signed one with my father. Uh... it's about living happily, I suppose. That's the kind of person he is. I'm proud of him for that. If he'd wanted me to sign a different contract, say... one about working myself into the ground, or stepping on others to achieve success... I would've ran away by now!",
      tips: 'Unlocks at Friendship Lv. 4',
      tasks: null,
    },
    '32': {
      title: 'More About Yanfei: IV',
      audio: '5004',
      text: "Sometimes, the commercial disputes I handle don't end very pleasantly. The other party might win compensation way in excess of the damages, or pay damages far exceeding the costs... Such is the price of violating a contract. Some people say I'm pretty terrifying, others try to avoid me altogether, but I don't need to explain myself to anyone. Since the very beginning, the welfare of Liyue has been my primary concern!\\nThink about it — the origin of disputes can be traced back to the violation of contracts. People are a lot less likely to violate contracts when they see the fallout. Making sure that people realize the importance of contracts is a crucial part of my work!",
      tips: 'Unlocks at Friendship Lv. 5',
      tasks: null,
    },
    '33': {
      title: 'More About Yanfei: V',
      audio: '5005',
      text: "Most of the time, I feel that I have a happy and laid back existence. I have a successful career, clothes on my back, and the freedom to go wherever I please. I've also got quite a way with words — nobody can beat me in a debate. And yet, there is no law or standard that can define a happy life.\\nFor me... interesting people and engaging affairs, knowing where to go and which path to choose... these are all enough to bring me happiness. And on that note, you too are a source of happiness for me.\\nIn any case, whatever the life you live, the most important thing is to respect and understand the law. After all, as soon as you stray from the law, the world begins to fall to ruin.",
      tips: 'Unlocks at Friendship Lv. 6',
      tasks: null,
    },
    '34': {
      title: "Yanfei's Hobbies",
      audio: '6001',
      text: "My hobbies are reading and appraisal. Reading begets knowledge, appraisal improves judgment. As such, I read everything and appraise anything. If you don't believe me, bring something over sometime. If there's a market for it, my estimate won't be far off. Take this stone for example... must be... 600 Mora.",
      tips: '',
      tasks: null,
    },
    '35': {
      title: "Yanfei's Troubles",
      audio: '6002',
      text: "My friends from the Communications Office often get me to go fishing with them. They say it's to exchange angling tips, but deep down everyone's keen to show off. I've gotten the better of everyone a hundred different ways, but they continue to scrutinize my business... After so much success, it's gotten a little embarrassing... So every time, I end up taking advantage of my ingenious acting skills to make myself seem humble, you know? What's with the face — are you doubting me?",
      tips: '',
      tasks: null,
    },
    '36': {
      title: 'Favorite Food',
      audio: '6003',
      text: "Oh! On that note, let me recommend my one true love. Tofu — tofu all the way! Light in flavor, tender in texture, not to mention smooth and nourishing. It goes well with all manner of soups and dishes, and more importantly — it's available throughout the seasons! Beauty over complexity... tofu dishes are my kind of flavor.",
      tips: '',
      tasks: null,
    },
    '37': {
      title: 'Least Favorite Food',
      audio: '6004',
      text: "I don't like cold dishes... maybe it's because I rarely eat them. When I would get home late, my father used to keep a lantern lit for me. He'd hear me coming and ask me if I was hungry. In his words: \"The best dishes are served hot.\"",
      tips: '',
      tasks: null,
    },
    '38': {
      title: 'Receiving a Gift: I',
      audio: '6007',
      text: 'Tastes pretty great! Seems like you did your homework when it comes to the unwritten Law of Tofu.',
      tips: '',
      tasks: null,
    },
    '39': {
      title: 'Receiving a Gift: II',
      audio: '6008',
      text: 'There\'s a saying in Liyue: "Food is life." I gotta admit, the supporting evidence is pretty compelling.',
      tips: '',
      tasks: null,
    },
    '40': {
      title: 'Receiving a Gift: III',
      audio: '6009',
      text: "...I got it! I'll put it back on the fire for a bit, that'll do the trick.",
      tips: '',
      tasks: null,
    },
    '41': {
      title: 'Birthday',
      audio: '7001',
      text: "Happy birthday! Here, this is for you. I've collated legislation from all the nations — you're planning to go traveling, right? It will serve you well to familiarize yourself with the law of the different lands.\\nDon't study too hard mind you, or else... I won't be of any use to you.",
      tips: '',
      tasks: null,
    },
    '42': {
      title: 'Feelings About Ascension: Intro',
      audio: '8001',
      text: '"Do not seek to emulate the past, for there is no law that can suffice for all time"... This is a lesson I must always bear in mind.',
      tips: 'Unlocks at Ascension Phase 1',
      tasks: null,
    },
    '43': {
      title: 'Feelings About Ascension: Building Up',
      audio: '8002',
      text: "Only by adhering to the law can the people solve life's myriad of problems.",
      tips: 'Unlocks at Ascension Phase 2',
      tasks: null,
    },
    '44': {
      title: 'Feelings About Ascension: Climax',
      audio: '8003',
      text: 'Studying the law allows one to have grounded conversations, whilst learning martial arts allows one to prevail against groundless violence. Hey, wait a minute... does this count as martial arts...?',
      tips: 'Unlocks at Ascension Phase 4',
      tasks: null,
    },
    '45': {
      title: 'Feelings About Ascension: Conclusion',
      audio: '8004',
      text: "Well, I guess I've mastered both the pen and the sword! I've been lucky to have you with me through to the end of my training. Compensation? Uhh... a twenty-four-hour specialist personal advisor? Sounds good... But no haggling!",
      tips: 'Unlocks at Ascension Phase 6',
      tasks: null,
    },
    '46': {
      title: 'Elemental Skill: I',
      audio: '100001',
      text: 'Boom boom!',
      tips: '',
      tasks: null,
    },
    '47': {
      title: 'Elemental Skill: II',
      audio: '100002',
      text: 'Incinerate!',
      tips: '',
      tasks: null,
    },
    '48': {
      title: 'Elemental Skill: III',
      audio: '100003',
      text: 'Motion to compel!',
      tips: '',
      tasks: null,
    },
    '49': {
      title: 'Elemental Burst: I',
      audio: '200001',
      text: 'Time for your arraignment!',
      tips: '',
      tasks: null,
    },
    '50': {
      title: 'Elemental Burst: II',
      audio: '200002',
      text: 'Wrath of the Flame!',
      tips: '',
      tasks: null,
    },
    '51': {
      title: 'Elemental Burst: III',
      audio: '200003',
      text: 'Inadmissible evidence!',
      tips: '',
      tasks: null,
    },
    '52': {
      title: 'Opening Treasure Chest: I',
      audio: '300001',
      text: 'Ooh, we can definitely write this off as "incidental gains."',
      tips: '',
      tasks: null,
    },
    '53': {
      title: 'Opening Treasure Chest: II',
      audio: '300002',
      text: 'Remarkable condition!',
      tips: '',
      tasks: null,
    },
    '54': {
      title: 'Opening Treasure Chest: III',
      audio: '300003',
      text: "Huh, let's appraise the value on this...",
      tips: '',
      tasks: null,
    },
    '55': {
      title: 'Low HP: I',
      audio: '410001',
      text: 'Objection!',
      tips: '',
      tasks: null,
    },
    '56': {
      title: 'Low HP: II',
      audio: '410002',
      text: 'Keep within the law...',
      tips: '',
      tasks: null,
    },
    '57': {
      title: 'Low HP: III',
      audio: '410003',
      text: 'But my defense was watertight...',
      tips: '',
      tasks: null,
    },
    '58': {
      title: 'Ally at Low HP: I',
      audio: '400001',
      text: 'Hey, leave it to me!',
      tips: '',
      tasks: null,
    },
    '59': {
      title: 'Ally at Low HP: II',
      audio: '400002',
      text: 'The verdict is... emergency measures!',
      tips: '',
      tasks: null,
    },
    '60': {
      title: 'Fallen: I',
      audio: '500001',
      text: "It's a... hung jury...",
      tips: '',
      tasks: null,
    },
    '61': {
      title: 'Fallen: II',
      audio: '500002',
      text: 'The law... has loopholes...',
      tips: '',
      tasks: null,
    },
    '62': {
      title: 'Fallen: III',
      audio: '500003',
      text: 'I... object...',
      tips: '',
      tasks: null,
    },
    '63': {
      title: 'Heavy Hit Taken: I',
      audio: '910001',
      text: 'Ugh...',
      tips: '',
      tasks: null,
    },
    '64': {
      title: 'Joining Party: I',
      audio: '600001',
      text: 'Next time, be sure to make a proper appointment.',
      tips: '',
      tasks: null,
    },
    '65': {
      title: 'Joining Party: II',
      audio: '600002',
      text: 'I charge a higher rate to meet outside the office.',
      tips: '',
      tasks: null,
    },
    '66': {
      title: 'Joining Party: III',
      audio: '600003',
      text: 'Ready for trial.',
      tips: '',
      tasks: null,
    },
  },
  story: {
    '0': {
      title: 'Character Details',
      title2: null,
      text: 'Liyue is a port that prizes contracts and trade, and it is a place where wealth accumulates.\\nMerchants from various nations are active here, which has contributed to Liyue\'s abundance, but has also brought up many disagreements. The Tianquan, Ningguang, has written a very comprehensive compendium of laws to deal with this, but not everyone has the patience to study them.\\nThus was born the role of the legal adviser in Liyue society. Highly familiar with Liyue\'s laws, they help those in need to navigate any contradictions, earning recompense for their efforts.\\nYanfei is the premier legal adviser in Liyue Harbor.\\nShe is always able to obtain the most benefits for her clients, insofar as the law will allow. Some even call her "the law that walks."\\nBut in truth, what Yanfei — one of the few half-illuminated-beasts who have yet to sign a contract with Rex Lapis — really wants to do is live a free and happy life.\\nAs for the copy of "The General Law of Liyue" that she carries around on her person, Yanfei has this to say:\\n"If you don\'t wish to be bound by the rules, you have to first understand them all."',
      text2: null,
      tips: '',
    },
    '1': {
      title: 'Character Story 1',
      title2: null,
      text: 'As the most sought-after legal adviser in Liyue Harbor, Yanfei\'s rates are also top-of-the-line.\\nEven so, she never lacks for people coming to seek appointments. After all, merchants are not stingy about mediation fees, but are very picky indeed about the mediator.\\n"Money is no object — we must have Yanfei come and settle this matter for us."\\nMany rate Yanfei in this fashion, not only for her quick-thinking or her masterful oratory, but also because she very greatly emphasizes the cornerstone of the law — "fairness."\\nHer mediations often end in win-win situations, and even merchants with daggers drawn will temporarily set their prejudices aside.\\nThough she is unbound by a contract, Yanfei has made her own contribution to the peace and prosperity of Liyue.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 2',
    },
    '2': {
      title: 'Character Story 2',
      title2: null,
      text: 'As a legal adviser, Yanfei does have her fair share of weaknesses. An example is the mediation of civil disputes that involve emotions and relationships.\\nDivorces, inheritances, custody disputes, senior care, severances... The list continues.\\nIt is said that upright officials are hapless in household affairs, and so it also is with Yanfei, who grew up surrounded by love — these matters fall right into her blind corner.\\nSometimes, she will find that both sides have reason on their side, and other times she will find them to both be unreasonable. Child custody disputes are the absolute worst, as no matter how she settles them, the settlement will have a great psychological impact on the innocent children. Even if Yanfei chooses to soldier on, she will only tire herself out.\\n"Hopefully, everyone can meet the right person and be spared this particular grief."',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 3',
    },
    '3': {
      title: 'Character Story 3',
      title2: null,
      text: "As a result of her greatly tolerant nature, Yanfei has a wide variety of personal relationships throughout Liyue.\\nThere is no need to worry about rubbing a sore spot, and you'll be able to get along with her whether you're an avid conversationalist or not.\\nOf course, this is true as long as you don't attempt to debate with her or start a conversation about the legal profession... Yanfei in work mode is a completely different beast to deal with.\\nAdditionally, Yanfei has cultivated the habit of being overly rigorous from her long years of studying the law. When chatting, Yanfei will vigorously eliminate any ambiguity or loopholes present in the discourse and can seem like a bit of a chatterbox. When she realizes this, Yanfei is wont to knock herself on the head with a book in irritation.\\nHowever, so long as she constantly bathes in a sea of legal literature, this habit will probably be quite hard to break.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '4': {
      title: 'Character Story 4',
      title2: null,
      text: 'When investigating the law, Yanfei\'s habit is to look past the cold letters of the law to perceive their point of origin.\\nAs such, she is also something of a master of "reading comprehension" in her relationships.\\nOnce, the Traveler met Yanfei by chance and said, "Huh. Didn\'t expect to see you here."\\nThis should have been a line that one might hear just about anywhere, but it wound up holding a completely different meaning for Yanfei.\\n"Didn\'t expect to meet you here" implied that the Traveler had at least thought about a scenario in which they would meet. Then why the use of "didn\'t expect"? One could only postulate that the Traveler had some expectation of where she might appear, and that her current location was not such a place. But whence came the expectation? Could it be that the Traveler had always been paying attention to her in secret?\\n"Does this mean that the Traveler...?"\\nYanfei tossed and turned in bed that night, unable to sleep.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 5',
    },
    '5': {
      title: 'Character Story 5',
      title2: null,
      text: "Yanfei's most prized possession is the steelyard balance that her father gave her.\\nIt is said that this balance was a treasure given by Rex Lapis that can be used to measure the value of all things. For convenience, Yanfei tends to use Mora to balance the scales, which is to say that she uses Mora to evaluate objects.\\nThe prices of many objects have slowly changed over the years, but weighing an object with this balance only gives its value at the time Mora was created, leaving the rest to Yanfei to exercise her own wisdom and judgment.\\nAcross the measurements of countless objects, Yanfei is able to see the changes in Liyue. Some objects that were once common have become vanishingly rare, and some exotic objects of the past have been rendered pedestrian today.\\nThis steelyard balance reminds her that many things cannot be valued by the standards of the world.\\nYanfei once tried to weigh the value of a Vision, but no matter how much Mora she added, the scales would not be balanced.\\nIn frustration, she placed on the scale the box at her waist, which contained her heavy, handwritten legal notations. Only then did the weights at last even out.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
    '6': {
      title: 'Codex Finalem',
      title2: null,
      text: "This is the most special of the many legal treatises that Yanfei collects.\\nAs opposed to the codices that grow heavier and more complicated with time, this book is unbelievably light and thin.\\nAfter opening it and getting past the prologue, one will find naught but the most basic few principles of the law inscribed.\\nAs Yanfei sees it, this is the final form of the law. In the far future, the law will have entered into the people's hearts. All people will be amiable, modest, and live happily in this world. The halls of judgment will lie empty and the mountains of legalese shall be caked in years of dust.\\nThough this may sound like something very far off, for someone like Yanfei, in whom flows the blood of an illuminated beast, living till that day is hardly a great accomplishment.\\n\"Hmm, but if I think about it more deeply, I'd be out of a job then, wouldn't I?\"\\nAfter encountering one of Xinyan's performances by chance, Yanfei was quite taken by this new wave of performance art.\\nThat said, learning an instrument from scratch proved to be a bit difficult, so after consulting a great many resources, Yanfei came to what she considered to be a decent backup plan.\\nIf such a day were to arrive, she would just become a rapper.\\nFor someone who can recite tens of thousands of words' worth of Liyue law from front to back within an hour, speed at least should be no challenge.",
      text2: null,
      tips: 'Unlocks at Friendship Lv. 4',
    },
    '7': {
      title: 'Vision',
      title2: null,
      text: 'Yanfei\'s father is an illuminated beast, while her mother is an ordinary mortal merchant. Born into peaceful times, Yanfei did not sign a contract with Rex Lapis, but instead has one with her parents to "live happily."\\nAs Liyue\'s leading legal exegete, she is no stranger to exploiting some existing loopholes in the law — at times for herself, and sometimes for others.\\nIt has been made clear often enough that Yanfei is not a stickler for the rules and has no wish to be shackled by strictures.\\nStill, she contributes to the betterment of Liyue as she seeks her own pleasure, and will not use these loopholes for ill.\\nWhen making amendments to legal loopholes each year, Ningguang the Tianquan will often study Yanfei\'s doings, as if she were Liyue\'s unofficial legal troubleshooter.\\nIn a sense, one could argue that Yanfei makes the laws better at the lowest possible price... This principle is also the reason why she has never been convicted of exploiting any such loopholes.\\nYanfei believes in "no structure without laws," and what she wishes for is to "live as one pleases without overstepping."\\nEveryone in Liyue, adeptus or mortal, protects it in their own way.\\nThat is why Yanfei possesses a Vision, one that is of equal weight to her principles.',
      text2: null,
      tips: 'Unlocks at Friendship Lv. 6',
    },
  },
};
